- Orange/widgets/evaluate/owtestlearners.py
Number of decimals is set by putting strings into the data model rather than floats. The more proper alternative would be to define a new data model, but that's much to much work for this small effect.
I also changed the alignment and fixed resizing.
> Fix number of decimals and layout of Test Learners table

- Orange/widgets/evaluate/owtestlearners.py
Added support for multiclass classifier in AUC metric.
> TestLearners AUC multiclass metric.

- Orange/widgets/data/owdatasampler.py
This fixes a bug in Data Sampler, where Random sampling with replacement of one example failed.
> Sampling of one example.

- Orange/widgets/data/owtable.py
- Orange/widgets/utils/colorpalette.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owscatterplotgraph.py
* remove OWWidget as a base class for dialogs
* remove old no longer relevant code
* fix scatter plot's handling of NaNs for color scale
> Color palette cleanup

- Orange/widgets/visualize/owscatterplotgraph.py
Also allow view redo (with ViewBox default key "+").
> Fixed view undo so that it returns to the exact previous point. 

- Orange/classification/__init__.py
- Orange/classification/knn.py
- Orange/classification/linear_regression.py
- Orange/classification/logistic_regression.py
- Orange/classification/mlp.py
- Orange/classification/random_forest.py
- Orange/classification/softmax_regression.py
- Orange/classification/svm.py
- Orange/classification/tree.py
- Orange/data/impute.py
- Orange/data/preprocess.py
- Orange/regression/linear.py
- Orange/widgets/classify/owclassificationtree.py
- Orange/widgets/classify/owknn.py
- Orange/widgets/classify/owlogisticregression.py
- Orange/widgets/classify/owmajority.py
- Orange/widgets/classify/ownaivebayes.py
- Orange/widgets/classify/owrandomforest.py
- Orange/widgets/classify/owsvmclassification.py
- Orange/widgets/regression/owlinearregression.py
- Orange/widgets/regression/owmean.py
- Orange/widgets/regression/owsgdregression.py
- Orange/widgets/regression/owsvmregression.py
Added data preprocessor support to Fitter classes.
> Preprocessors

- doc/modules/classification.svm.rst
> Fix SVM example in documentation

- Orange/classification/knn.py
- Orange/classification/linear_regression.py
- Orange/classification/logistic_regression.py
- Orange/classification/mlp.py
- Orange/classification/random_forest.py
- Orange/classification/softmax_regression.py
- Orange/classification/svm.py
- Orange/classification/tree.py
- Orange/data/table.py
- Orange/distance/__init__.py
- Orange/evaluation/cross.py
- Orange/evaluation/scoring.py
- Orange/evaluation/testing.py
- Orange/regression/linear.py
- Orange/tests/test_tree.py
- Orange/widgets/data/owdatasampler.py
- Orange/widgets/evaluate/owconfusionmatrix.py
- Orange/widgets/evaluate/owliftcurve.py
- Orange/widgets/evaluate/owrocanalysis.py
- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/unsupervised/owpca.py
- Orange/widgets/visualize/owparallelgraph.py
- Orange/widgets/visualize/owvenndiagram.py
Import sklearn modules using skl_name naming convention.
> Skl rename

- Orange/distance/__init__.py
- Orange/widgets/unsupervised/owdistances.py
> Added support for categoric attributes when computing distances

- doc/modules/classification.svm.rst
- doc/modules/distance.rst
> Added distances and example to doc, fixed SVM example

- Orange/classification/base.py
The meta class is used for docstring templating/generation.
> Add meta class for wrapper classes.

- Orange/clustering/dbscan.py
- Orange/clustering/kmeans.py
- Orange/tests/test_clustering_dbscan.py
- Orange/tests/test_clustering_kmeans.py
Implementation of Kmeans clustering and DBSCAN algorithms from Scikit. Classes extend SklProjection.
> Kmeans dbscan

- Orange/clustering/dbscan.py
- Orange/clustering/kmeans.py
- Orange/evaluation/clustering.py
- Orange/tests/test_clustering_dbscan.py
- Orange/tests/test_clustering_kmeans.py
- Orange/tests/test_evaluation_clustering.py
Implemented a framework on top of Results, Score for evaluation of clustering algorithms (super- and unsupervised).
> Clustering evaluation

- Orange/preprocess/__init__.py
- Orange/preprocess/fss.py
- Orange/preprocess/score.py
- Orange/tests/test_fss.py
> Feature selection.

- Orange/evaluation/scoring.py
Merge multi-class into old AUC, add weights for folded scores, ignore nan results.
> Scoring weighted auc

- Orange/classification/simple_tree.py
Marko found a bug. This should fix it.
> Call ascontiguousarray before building simple tree

- Orange/classification/_simple_tree.c
Move double declaration outside for loop.
> Syntax error during compilation fix.

- Orange/preprocess/fss.py
- Orange/preprocess/score.py
- Orange/tests/test_fss.py
- Orange/tests/test_score_feature.py
New signature is (data, feature=None). If feature is not provided, scores for all features will be returned.
> Change signature of feature scorers.

- Orange/classification/_simple_tree.c
Now correctly builds with both mingw32 and msvc compiler.
> Mark exported functions.

- Orange/evaluation/clustering.py
Silhouette plot with image save.
> Silhouette plot generator.

- Orange/preprocess/discretize.py
- Orange/widgets/classify/owclassificationtree.py
- Orange/widgets/classify/owclassificationtreegraph.py
- Orange/widgets/classify/owknn.py
- Orange/widgets/classify/owlogisticregression.py
- Orange/widgets/classify/owmajority.py
- Orange/widgets/classify/ownaivebayes.py
- Orange/widgets/classify/owrandomforest.py
- Orange/widgets/classify/owsvmclassification.py
- Orange/widgets/data/owconcatenate.py
- Orange/widgets/data/owdiscretize.py
- Orange/widgets/data/owimpute.py
- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/owrank.py
- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/regression/owlinearregression.py
- Orange/widgets/regression/owmean.py
- Orange/widgets/regression/owsgdregression.py
- Orange/widgets/regression/owsvmregression.py
- Orange/widgets/utils/scaling.py
- Orange/widgets/visualize/owheatmap.py
Fix various issues in widgets.
> Widgets fix

- Orange/data/domain.py
- Orange/data/sql/table.py
- Orange/data/table.py
- Orange/tests/test_domain.py
Built upon #320, which fixes pickling tests.
> Store var indices in domain.

- Orange/widgets/visualize/owscatterplotgraph.py
Fix scatter plot auto scale problem, and change the draw order of selection item.
> Scatter plot fix

- Orange/widgets/unsupervised/owpca.py
Fixed components selection in PCA widget
> Fixed components selection in PCA widget

- Orange/widgets/visualize/owscatterplotgraph.py
Explicitly store/restore the relative anchor positions instead of absolute
offsets.
> Fix scatter plot's legend position persistence between replots.

- Orange/canvas/scheme/widgetsscheme.py
Create/initialize the OWWidget instances from the event loop, to allow
the canvas view to display the newly created widget icon.
> Delay widget initialization.

- Orange/widgets/utils/colorpalette.py
- Orange/widgets/visualize/owscatterplotgraph.py
A slight style fix for the scatterplot's legend frame (using a lighter background color, and left aligned labels) and a couple of bug fixes.
> Scatterplot style

- Orange/data/table.py
- Orange/tests/test_table.py
Fixed X/Y/metas array indexing when both row and column indices are not simple slice/Ellipsis.
> Table indexing fix

- Orange/widgets/evaluate/owtestlearners.py
TestLearners class selection comboBox.
> TestLearners class selection comboBox.

- Orange/data/io.py
- Orange/data/table.py
- Orange/tests/test_basket_reader.py
- Orange/tests/test_classification.py
- Orange/tests/test_sparse_reader.py
- Orange/tests/test_tab_reader.py
- Orange/tests/test_table.py
- Orange/tests/test_txt_reader.py
- Orange/tests/test_xlsx_reader.py
- Orange/widgets/data/owfile.py
- Orange/widgets/data/owsave.py
I don't know how to modify the mock in one of the tests, so I disabled the test. @astaric , is there an elegant way to solve this?
> .pickle format for Table, reorganization of file writers and readers

- scripts/windows/build-win-application.sh
- scripts/windows/install-common.nsi
- scripts/windows/install-standalone.nsi
I.e. it installs python without registering it with windows, and
installs all dependencies into that environment.
> Add NSIS script for installing a 'standalone' Windows application.

- Orange/data/value.py
- Orange/widgets/gui.py
- Orange/widgets/utils/datacaching.py
... discovered while porting bioinformatics widgets.
> Fix various bugs

- Orange/distance/__init__.py
- Orange/misc/distmatrix.py
- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/unsupervised/owmds.py
When calculating distances between columns (rather than rows as ususal) we add the *Attribute names* label.
> Fixed lables in MDS, hierarchical clustering and distance map for distances between columns

- Orange/widgets/visualize/owscatterplotgraph.py
Reveerted brush for selection since Qt.NoBrush sometimes causes black colors.
> reveerted brush for selection

- doc/modules/data.domain.rst
var_from_domain does not exist anymore (6345e9f4)
> Remove documentation of removed method.

- Orange/canvas/__main__.py
- Orange/widgets/data/owtable.py
> Data table widget header labels fix

- Orange/widgets/unsupervised/owdistancemap.py
* Add selection of columns if the distances are between variables
* Fix broken elastic band item selection.
* Show error messages.
> Distance map fix

- Orange/widgets/gui.py
- Orange/widgets/visualize/icons/LinearProjection.svg
- Orange/widgets/visualize/owlinearprojection.py
Add a Linear Projection widget.
> Linear projection

- Orange/widgets/gui.py
> Widgets I get to use repeatedly

- Orange/widgets/evaluate/owtestlearners.py
Test Learners reports an error instead of crashing when one of the learners crashes.
> Test Learners - report an error instead of crashing.

- Orange/base.py
Fixes learners that do not support weights,
which crashed on data with weights.
> Add default value of supports_weights.

- .travis.yml
> Coveralls might have been unable to find .coverage file?

- requirements-sql.txt
Remove sqlparse requirement. The last module using it was removed in d387837.
> Remove sqlparse requirement.

- .travis.yml
- travis/install.sh
Please see, particularly @biolab/owners, individual commits and messages. If the build passes, might be good to go. :+1:
> Exploit more free services

- Orange/distance/__init__.py
- Orange/widgets/unsupervised/owdistances.py
> Replace NaN values in distance matrix with 0 for Pearson and Spearman metrics

- Orange/classification/svm.py
- Orange/clustering/dbscan.py
- Orange/regression/linear.py
- Orange/tests/test_clustering_dbscan.py
See http://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html#sklearn.cluster.DBSCAN
> Update default parameters deprecated in scikit-learn.

- Orange/regression/linear.py
Add missing preprocessors argument in linear regression learners.
> Preprocessors argument in linear regression.

- Orange/widgets/classify/owclassificationtreegraph.py
- Orange/widgets/classify/owtreeviewer2d.py
Increase the margin around the tree graph, plus some bug fixes.
> Classification tree graph margins

- Orange/widgets/visualize/owscatterplotgraph.py
> Fix legend decimals format.

- Orange/widgets/visualize/owdistributions.py
Fix weights condition to be consistent with curve estimation condition
> OWDistributions - Fix condition

- Orange/clustering/hierarchical.py
- Orange/clustering/kmeans.py
- Orange/data/table.py
- Orange/misc/distmatrix.py
- Orange/projection/manifold.py
- Orange/tests/test_color.py
- Orange/tests/test_distances.py
- Orange/tests/test_table.py
- Orange/tests/test_util.py
- Orange/util.py
- Orange/widgets/gui.py
- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/utils/colorpalette.py
Blocks https://github.com/kernc/orange3-network ...
~~Is blocked by https://github.com/biolab/orange3/pull/451.~~
> 4 networks

- doc/conf.py
- doc/index.rst
- doc/orange_extras.py
- requirements.txt
Fix parsing of images in markdown files that are defined using <img> tag.
Update documentation toc to include all widgets.
> Documentation fixes

- Orange/widgets/data/owselectcolumns.py
Remove redundant code for drag/drop move code.
> Select columns speedup

- Orange/preprocess/discretize.py
- Orange/tests/test_discretize.py
I still prefer round to double string formatting.
The if clause is different just because it can be :)
(maybe just a bit more clear at first glance)
> Fix discretization intervals, now for real (version 2)

- Orange/data/value.py
- Orange/widgets/utils/colorpalette.py
> Various fixups

- Orange/widgets/evaluate/owtestlearners.py
- doc/widgets/evaluation/testlearners.md
Changed the widget and the widget documentation, but did not change the images in the documentation.
> owtestlearners: renamed to test and learn

- Orange/widgets/regression/owlinearregression.py
- Orange/widgets/regression/owunivariateregression.py
With these enhancements the two widgets play nicer together when used in demonstrations (which is the main purpose of Univariate regression widget).
> GUI enhancements in widgets for univariate regression and linear regression

- Orange/widgets/unsupervised/owdistancemap.py
Something that should have been fixed in 4fd5d288433b377e815d8cb2d3c8ed6bcf1adedf
> owdistancemap: Fix distance matrix tool tips

- Orange/widgets/classify/owclassificationtreegraph.py
Tree Viewer output continuized data, which looked weird, and was not useful for, say, Mosaic and Sieve.
> Tree Viewer: Output data in original domain

- scripts/build-osx-app.sh
- scripts/windows/build-win-application.sh
- setup.py
Also fix osx and windows application build scripts to ensure install_requires dependencies are included.
> Add openpyxl dependency to setup.py install_requires

- Orange/widgets/unsupervised/owmds.py
Similar pairs are no longer drawn in every iteration of MDS, but only in the end. Beside that, instead of pyqtgraph.PlotCurveItem, QtGui.QGraphicsLineItem is used for drawing.
> OWMds: Optimize similar pairs

- Orange/widgets/visualize/owscatterplotgraph.py
Change select/deselect keys to be consistent with other widgets.
> OWScatterplotgraph: Change select/deselect keys

- Orange/widgets/unsupervised/owmds.py
Always specify the number of colors to use in a discrete color palette.
> OWMDS: Fix IndexError in discrete color palette

- Orange/widgets/visualize/owmosaic.py
Selection with keys Shift, Ctrl and Alt is now consistent to selection in OWScatterPlot.
> OWMosaic: Selection

- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/owlinearprojection.py
Selection with keys Shift, Ctrl and Alt is now consistent to selection in OWScatterPlot.
> OWMds, OWLinearProjection, OWHeatMap: Selection

- Orange/widgets/visualize/owlinearprojection.py
Always specify the number of colors to use in a discrete color palette.
> owlinearprojection: Fix color palette IndexError

- Orange/canvas/application/canvasmain.py
- Orange/canvas/scheme/scheme.py
- Orange/canvas/scheme/widgetsscheme.py
- Orange/widgets/data/owfile.py
- Orange/widgets/widget.py
Store/restore recent file paths based on a set of predefined known/fixed
search paths (including loaded workflow scheme relative path if available).
> OWFile relocatable recent file paths

- Orange/data/domain.py
- Orange/tests/test_domain.py
This improves sorting of attribute names.
If the pull request is rejected, some of the new tests for anonymous domains can still be added.
> Domain.from_numpy: Add padding zeros to variable names

- Orange/widgets/visualize/owvenndiagram.py
- Orange/widgets/visualize/tests/test_owvenndiagram.py
Alternative approach to #600
@VesnaT please check
> OWVennDiagram: Show intersection of multiple datasets (2)

- Orange/tests/test_discretize.py
> Discretize: Add Instance conversion test.

- Orange/widgets/visualize/owheatmap.py
Fix an assertion error in clustering when encountering a discrete
feature.
> owheatmap: Remove discrete feature columns from input

- Orange/preprocess/discretize.py
> discretize.EqualWidth handles all-NaN series

- Orange/widgets/data/owfile.py
Accordingly, data file combo box is now editable.
> [WIP] OWFile: Enable open file from url

- Orange/widgets/data/owpreprocess.py
- Orange/widgets/utils/overlay.py
- Orange/widgets/widget.py
Add support for optional overlay messages intended to inform the user of a particular
new (or old) feature.
> Overlay widget

- Orange/widgets/visualize/owheatmap.py
* Add a new row sorting method (by row mass center; ported from Orange 2).
* Add an exponential ramp up color palette interpolation (ported from Orange 2).
* Disable (Ordered) Clustering on large input sizes.
* Improve the automatic heatmap layout on widget resize.
> Heatmap improvements

- Orange/data/io.py
Fix saving of data instance weights.
> io: Save weights.

- Orange/data/table.py
- Orange/tests/test_table.py
> table: Fix shape of weights.

- Orange/widgets/regression/owlinearregression.py
> Revert "OWLinearRegression: output table with coefficients"

- Orange/widgets/unsupervised/owhierarchicalclustering.py
The problem was introduced in c23297c87bf5a8b5796b12061a2af260781523ff
This solves the root of the problem by removing use of QPolygonF.united
to build a tree covering polygon.
> owhierarchicalclustering: Fix dislocated leaf node selection geometry

- Orange/widgets/data/owtable.py
@ales-erjavec please confirm this is the best place to do this, or not.
> OWTable: right-align continuous data

- Orange/widgets/data/owselectrows.py
Plain DomainContextHandler could/would restore/activate invalid conditions list.
> owselectrows: Use PerfectDomainContextHandler

- Orange/widgets/data/owfile.py
Fixes [issue 177](https://docs.google.com/spreadsheets/d/1spQ3zuXUEvoD-hpYEm33-lyS3OzV6cjhE7YlFlBoOw8/edit#gid=0).
@ales-erjavec can you confirm this has no negative consequences?
> OWFile: Fix Reload for local files

- Orange/widgets/data/owdatasampler.py
Samples can be time or percentage based.
> owdatasampler: Show custom sampling options for SqlTables

- Orange/canvas/__main__.py
> canvas: ask to open survey before opening it

- Orange/widgets/unsupervised/owmds.py
Send selected data instead of all data by default.
> OWMds: Send selected data by default

- Orange/evaluation/testing.py
- Orange/tests/test_evaluation_testing.py
- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/owtestlearners.py
Test and score now also returns predicted values and probabilities
> Test&Score,Predictions: output predictions and probabilities

- Orange/widgets/gui.py
Not tested beyond it's still working for widgets using it as currently and my own use case.
> gui.auto_commit: allow callback specified other than commit()

- Orange/data/sql/table.py
- Orange/widgets/visualize/owscatterplot.py
Replaces a one-time sample with the option to incrementally sample and update the visualization.
> Scatter Plot: Incremental sampling and plotting

- Orange/widgets/data/owsql.py
Add option to OWSql widget to store result of a custom select to a table and use that table in the analysis.
> OWSql: Materialize custom select

- Orange/widgets/data/owsql.py
Prevent multiple Do you want to guess domain dialogs when schema is opened.
> OWSql: Prevent multiple confirmation dialogs

- Orange/widgets/gui.py
> gui.auto_commit: commit() doesn't accept any args

- Orange/data/table.py
- Orange/tests/test_table.py
- Orange/widgets/data/owfile.py
Perhaps review individual commits.
> OWFile reads Google Sheets URLs

- Orange/widgets/visualize/owheatmap.py
Clicking very near the top of a heatmap image would trigger an KeyError
> owheatmap: Fix an error during selection

- Orange/widgets/classify/owlogisticregression.py
- Orange/widgets/classify/owsvmclassification.py
Sklearn logistic regression and svm learners crash when given data with only one class value.
Instead of crashing, widgets OWLogisticRegression, OWSVMClassification now show error message.
> OWLogisticRegression, OWSVMClassification: Handle one class value

- Orange/canvas/canvas/items/controlpoints.py
The ControlPoint graphics object was relying on the default
QGraphicsItem for movement (QGraphicsItem.ItemIsMovable), but
this moves all items in the scene that are selected and movable
including the selected ArrowAnnotation item. Therefore Qt would move
both items, but the ArrowAnnotation's shape/geometry would then be
'fixed' on the control point's positionChanged signal. However when
processing a mouseMoveEvent which did not actually move from the last
reported position the control point would not signal a changed position
(as it did not change) but Qt's default event handler would still
move/set positions for all selected movable items (relative to the
initial move starting point and not a difference from the last
reported mouse position).
This is fixed by reimplementing …
> canvas/annotations: Fix jerky arrow annotation editing

- Orange/data/table.py
- Orange/widgets/data/owfile.py
@ajdapretnar should merge this.
> Fix Table.from_url on Windos

- Orange/classification/simple_tree.py
- Orange/regression/__init__.py
- Orange/tests/test_simple_tree.py
Include simple tree in regression package
Print average instead of sum in regression tree. 
Number of decimals depends on value of root's sum.
> Simple Tree

- Orange/widgets/unsupervised/owkmeans.py
Use the row id preserving Table.from_table constructor.
> owkmeans: Preserve input row ids

- Orange/widgets/evaluate/owcalibrationplot.py
- Orange/widgets/evaluate/owliftcurve.py
- Orange/widgets/evaluate/owrocanalysis.py
Widget crashed when given regression data. Show error message instead.
> OWCalibrationPlot: Handle regression data

- Orange/widgets/data/owdatasampler.py
Widget crashed when given dataset smaller than desired output. Now it shows error message insted.
> OWDataSampler: Show error message when given small dataset

- Orange/widgets/data/owselectcolumns.py
OwSelectColumns: Add "Apply on change". Task 178
> OwSelectColumns: Add "Apply on change". Task 178

- Orange/regression/linear.py
Added default preprocessors to PolynomialLearner.
It is derived from base Learner, which does not have any, so it failed on missing values etc.
> PolynomialLearner: Add default preprocessors

- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/gui.py
- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/utils/scaling.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/owscattermap.py
- Orange/widgets/widget.py
Packs `progressBarInit` and `progressBarFinished` into context manager to ensure the progress bar is removed in case of exceptions.
If PR is accepted, this should become the preferred way of handling progress bars.
> Progress bar context handler and decorator

- Orange/canvas/application/canvasmain.py
Fixed link for 'Documentation' in Welcome screen.
> Splash screen fix

- Orange/tests/test_evaluation_scoring.py
Orange.evaluation.scoring.Score.from_predicted uses only classes, but LogLoss needs probabilities. In order to verify correctness of Orange.evaluate.LogLoss, new unit test was written.
> LogLoss: Unittest

- Orange/base.py
- Orange/preprocess/preprocess.py
- Orange/projection/base.py
- Orange/regression/linear.py
- Orange/tests/test_classification.py
All data sets need preprocessors for testing as we can always have unknown values in testing data even when there are none in learning data.
> Ability to learn without and predict wih missing values

- Orange/widgets/evaluate/owpredictions.py
Partially revert 35bb9bbb40cfde51de3b133f473986f3897804b5, which caused
the "Predictions" output to no longer be sent if the input dataset did
not contain the actual/true class column.
> OWPredictions: Output predictions when no class_var is present

- Orange/widgets/classify/owclassificationtree.py
- Orange/widgets/classify/owmajority.py
- Orange/widgets/classify/owsvmclassification.py
- Orange/widgets/regression/owknnregression.py
- Orange/widgets/regression/owlinearregression.py
- Orange/widgets/regression/owmean.py
- Orange/widgets/regression/owrandomforestregression.py
- Orange/widgets/regression/owregressiontree.py
- Orange/widgets/regression/owsgdregression.py
- Orange/widgets/regression/owsvmregression.py
- Orange/widgets/regression/owunivariateregression.py
> Learner-providing widgets: minor fixup that didn't make it into 38446d3

- Orange/distance/__init__.py
- Orange/tests/test_distances.py
Fixed Spearman tests and axises in all examples.
> tests: fixing distances tests

- Orange/widgets/data/owdatasampler.py
Beside adding bootstrap sampling, I made some minor fixes to error messages (especially for cross validation). @VesnaT, please check.
> OWDataSampler: Add bootstrap, minor fixes in GUI

- Orange/widgets/visualize/owscatterplot.py
Pairs of attributes where data has no missing values should have better ranking.
> Rank projection: Consider missing values

- Orange/preprocess/discretize.py
~~@thocevar Can you confirm this is what was intended?~~ This was intended as evident from commit log 2717ee0c.
> Discretizer: fix OWScatterMap bug

- Orange/data/filter.py
- Orange/data/table.py
... but should make Table class more extensible!
Plz review pronto.
> Table._filter_values: small refactoring that shouldn't break anything

- Orange/widgets/evaluate/owpredictions.py
Undo c6add85ae118b1cb5edaa1a942dc10cc357abb12 and extend the widget functionality (simlilar to how it was in Orange 2)
> owpredictions: Display input data and predictions in the widget

- Orange/data/table.py
- Orange/tests/test_contingency.py
- Orange/tests/test_distribution.py
- Orange/widgets/visualize/owboxplot.py
- requirements.txt
If meta attribute is discrete, it is included to Variable and Grouping.
If it is continuous, it is only included to Variable.
> OWBoxPlot: Add meta attributes to selection

- Orange/base.py
- Orange/classification/softmax_regression.py
- Orange/classification/svm.py
- Orange/classification/tree.py
- Orange/regression/linear_bfgs.py
- Orange/regression/svm.py
- Orange/tests/adult_sample_missing.tab
- Orange/tests/test_classification.py
- Orange/tests/test_regression.py
- Orange/widgets/regression/owlinearregression.py
Preprocessor checks for missing values in class variable and removes associated instances.
> Add RemoveNanClasses preprocessor

- Orange/projection/pca.py
- Orange/tests/test_pca.py
- Orange/widgets/data/owrank.py
- Orange/widgets/unsupervised/owpca.py
Add an output to PCA widget that can go to Rank widget.
> PCA: Use it as feature scorer

- Orange/widgets/evaluate/owpredictions.py
Add option to visualize predicted distributions by means of a distribution bar
> owpredictions: Visualize predicted distributions

- Orange/preprocess/_relieff.cpp
- Orange/preprocess/_relieff.pyx
- Orange/preprocess/score.py
- Orange/tests/test_score_feature.py
- Orange/widgets/data/owrank.py
- doc/data-mining-library/source/reference/preprocess.rst
... is what the title says. The method is pretty popular ([1068+ citations](https://scholar.google.com/scholar?q=fast+correlation-based+filter+fcbf)) for reducing datasets with lots of features by extracting "optimal" feature sets, like [mRMR](https://en.wikipedia.org/wiki/Minimum_redundancy_feature_selection) does.
It's fast compared to ReliefF and can be enabled by default.
> [WIP] score.FCBF: a Fast Correlation-Based Filter for feature selection

- Orange/distance/__init__.py
- Orange/tests/test_distances.py
- Orange/widgets/unsupervised/owdistances.py
See also:
https://github.com/biolab/orange3/pull/997#issuecomment-183279100
> Revert "OWDistances, SklDistance: support discrete variables"

- Orange/data/io.py
- Orange/data/variable.py
- Orange/tests/test_variable.py
- Orange/widgets/gui.py
- Orange/widgets/utils/__init__.py
- doc/data-mining-library/source/reference/data.io.rst
- doc/data-mining-library/source/reference/data.variable.rst
> Time variable

- Orange/data/__init__.py
- Orange/data/io.py
- Orange/data/table.py
- Orange/tests/test_table.py
> Replace Table references with cls or self.__class__

- Orange/widgets/data/owrank.py
- Orange/widgets/unsupervised/owmds.py
Output scores from Rank widget in a Table and allow them to be used as annotations in MDS widget.
> [FEATURE] Rank outputs scores

- doc/development/source/widget.rst
while reading the docs i encountered error in documentation (widget.rst)
> Error in Documentation widget.rst

- Orange/classification/random_forest.py
- Orange/regression/random_forest.py
#1028 was merged as a partial fix, opening a pull request with proper method signature (as in sci-kit).
> Scikit RF params sync

- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/owsieve.py
In sieve and mosaic widgets. Fixes #1049
> Allow user to select meta attributes

- Orange/misc/distmatrix.py
This makes sure they are closed at the end (they were not before).
> distmatrix: Use with statement to open files

- Orange/widgets/regression/owlinearregression.py
> Report Creation for Linear Regression

- Orange/tests/__init__.py
- Orange/tests/test_doctest.py
- Orange/tests/test_preprocess_cur.py
- Orange/util.py
* Fix core unittests/doctest discovery on Windows
* Allow core unittests to run even if PyQt4 is not installed
> Fix core unittest run errors

- Orange/widgets/regression/owunivariateregression.py
@ajdapretnar please review this code.
>  Report for Univariate Regression #1080

- Orange/widgets/unsupervised/owdistancetransformation.py
Fixes #1081 
Continued from PR #1100.
> [ENH] Add report for Distance transformation widget

- scripts/build-osx-app.sh
Fix an error due to a failed glob expansion (`shopt -s failglob` is in
effect in the script).
The error was introduced in b00469481b7c609f219d88a216160df25d283822
> Quote cmd line requirement arguments for pip

- Orange/widgets/regression/owsgdregression.py
Fixes #1078 and layout improved. Now box is adjusted.
> Layout Fixed and Report Generated for SGD Regression

- Orange/widgets/settings.py
- pylintrc
Fix PyLint warnings/errors for settings module.
Mostly added missing docstrings and reformatted code.
> Settings: Handle pylint warnings

- Orange/widgets/unsupervised/owmds.py
Fixes the following workflow that visualizes distances between columns.
> [FIX] Allow use of feature metadata in MDS

- Orange/widgets/classify/owknn.py
[ENH] KNN classify widget: added weight option with reporting
> Feature knn widget: added weight option

- Orange/projection/pca.py
> [FIX] PCA: decrease memory consumption.

- Orange/canvas/report/report.py
Fixed Report of Rank Widget does not contain the feature names in the table #1022.
Added the check for vertical headers (line 222) and displayed it if available.
> [FIX]Report of Rank Widget does not contain the feature names in the table. #1022

- Orange/widgets/classify/owsvmclassification.py
Tol spin widget doesn't display value properly.
> OWSVMClassification: minor gui fix (change the width of tol widget)

- Orange/tests/test_ada_boost.py
> test_ada_boost: fasten up the test

- Orange/widgets/gui.py
- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/owsieve.py
> [ENH] Update mosaic (rebased)

- Orange/widgets/data/owfile.py
- Orange/widgets/settings.py
PR #1074 (@rahulroxx) + minor fixes related to settings. Closes #1045.
> [ENH] Add sheet selection to file widget

- Orange/widgets/visualize/owmosaic.py
Mosaic widget has been reimplemented and the changes were recently merged into the master branch. This PR merges changes from #1050 (by @RachitKansal) into the new widget since rebase of #1050 was impractical (i.e. impossible).
> [ENH] Mosaic handles discrete attributes

- Orange/widgets/data/owpreprocess.py
Add Relief and FCBF according to issue #1126 in Select Relevant Features' preprocessor.
> Added Relief and FCBF as in issue #1126

- .travis/check_pylint_diff
> pylint: ensure md5sum on OSX

- Orange/widgets/widget.py
Alternative to https://github.com/biolab/orange3/pull/1175, works beautifully on Windos 10.
> OWWidget: restore fullscreen into maximized instead

- Orange/preprocess/preprocess.py
> SklImpute: fix table's weights dropping.

- Orange/widgets/settings.py
- Orange/widgets/utils/owlearnerwidget.py
> SettingsHandler: Fix defaults for subclassed widgets

- Orange/canvas/scheme/widgetsscheme.py
Fix an error on Windows due to the settings pickle filename containing invalid path characters (<>).
> [FIX] widgetsscheme: Disable global settings persistence for the dummy widget

- Orange/tests/test__orange.py
- Orange/tests/test_color.py
- Orange/tests/test_datasets.py
- Orange/tests/test_distribution.py
- Orange/tests/test_domain.py
- Orange/tests/test_evaluation_scoring.py
- Orange/tests/test_evaluation_testing.py
- Orange/tests/test_fss.py
- Orange/tests/test_impute.py
- Orange/tests/test_instance.py
- Orange/tests/test_logistic_regression.py
- Orange/tests/test_majority.py
- Orange/tests/test_manifold.py
- Orange/tests/test_mean.py
- Orange/tests/test_naive_bayes.py
Changes:
- Adding iterators in tests where is similar code, but only parameters are changing
- Deleting some duplicated rows
- Adding some functions into setUpClass and changed some assertTrue into assertGreater...
> Cleaning unittests

- Orange/tests/__init__.py
- Orange/widgets/settings.py
- Orange/widgets/tests/__init__.py
- Orange/widgets/tests/test_perfect_domain_context_handler.py
Fix PerfectDomainContextHandler and add tests.
> [FIX] PerfectDomainContextHandler: Fix crash, add tests

- Orange/widgets/unsupervised/owdistancemap.py
> [FIX] DistanceMap: Labels displayed after changed sorting, string labels w/o quotes

- Orange/data/filter.py
- Orange/tests/test_filter.py
> HasClassFilter: Tests and bug fixing

- Orange/widgets/data/owpreprocess.py
Preprocess: Add number of intervals to discretize slider
> Preprocess: Add number of intervals to discretize slider

- Orange/base.py
- Orange/classification/elliptic_envelope.py
- Orange/classification/svm.py
- Orange/classification/tree.py
- Orange/regression/svm.py
- Orange/regression/tree.py
- Orange/tests/test_base.py
This flag was missed in some learners (e.g. LogisticRegression, RandomForest)
> SklLearner: add supports_weights property.

- Orange/widgets/utils/owlearnerwidget.py
This is quite urgent. The released version opens red screens in canvas with almost any learner.
> [FIX] check_learner_adequacy problem.

- Orange/widgets/data/owfile.py
Remove unused import XLRDError , after merging refactored io.py
> Removed unused import

- Orange/widgets/data/owpreprocess.py
> Equal width discretization slider

- Orange/widgets/evaluate/owconfusionmatrix.py
- Orange/widgets/gui.py
Confusion matrix now stores the selection in context settings and keeps the learner selection after `set_results`. @ajda, @BlazZupan, schemata with multiple confusion matrices and selections now work. PR is ready, I guess, unless...
@astaric The context is determined by the class, so the learner selection is not context dependent. Keeping the learner selection after `set_results` is a bit convoluted and could perhaps be improved, but we first have to decide whether we should move it to context settings (and have it stored for free). In this case, we need a useful `EvaluationResultsContextHandler`. There is one in `widgets.evaluation.contexthandler`, but it's written for some specific case (requires target class) and not used anywhere.
> Confusion matrix: Add context settings, store selection

- Orange/data/variable.py
- Orange/tests/test_variable.py
- Orange/widgets/data/owselectrows.py
> BUG: Handle TimeVariable in Select Rows widget

- Orange/widgets/gui.py
- Orange/widgets/tests/test_itemmodels.py
- Orange/widgets/utils/itemmodels.py
Obsoletes https://github.com/biolab/orange3/pull/1208
> Table model (list of lists) for QTableView

- README.md
- codecov.yml
Codecov configuration has been moved from the website to a config file
in repository.
> Codecov: Add configuration

- Orange/widgets/data/owpurgedomain.py
In reference to issue #1084. 
In addition to adding the meta purging functionality, I also made the interface slightly clearer in the face of new elements. [Reference image](http://imgur.com/4RUKtLn).
> Purge domain widget: add meta purging

- Orange/widgets/data/owmergedata.py
> [ENH] OWMergeData: merge by instance ID.

- Orange/evaluation/scoring.py
- Orange/evaluation/testing.py
- Orange/tests/test_evaluation_testing.py
- Orange/widgets/evaluate/owtestlearners.py
Working on  #1102 I have found that there are something that can be improved:
- inherit TestOnTrain from TestOnTest.
- Make the main loop body in `__init__` method of each method as a separated method (`fit(data)`).
- Some settings/data raises errors in sklearn functions (for example, when test set is too small). Possibly, we need to add 'check(data)' method.
- Use LeaveOneOut from sklearn.
- `sample` function is used only in tests.
- remove preprocessor per sample calls.
Work in progress, but I want your suggestions.
> Refactor evaluation.testing module

- CHANGELOG.md
> [FIX] Changelog: Fix links

- Orange/widgets/data/owmergedata.py
Clear the output of Merge Data when some inputs are removed.
> [FIX] owmergedata: Reset output on cleared signals

- Orange/widgets/widget.py
> OWWidget: round progress percentage

- Orange/data/filter.py
- Orange/tests/test_filter.py
Added tests for IsDefinedFilter and fixed implementation.
> IsDefinedFilter: Tests and bug fixing

- Orange/data/filter.py
- Orange/tests/test_filter.py
- Orange/tests/test_table.py
Rebased https://github.com/biolab/orange3/pull/1210
> Rebased #1210 (SameValue filter tests)

- Orange/preprocess/impute.py
- Orange/preprocess/score.py
- Orange/tests/test_util.py
- Orange/util.py
- Orange/widgets/io.py
- Orange/widgets/settings.py
- Orange/widgets/utils/owlearnerwidget.py
> util.abstract: Remove this useless decorator

- Orange/data/io.py
- Orange/data/table.py
- Orange/tests/test_tab_reader.py
- Orange/tests/test_table.py
> [ENH] Table.attributes field.

- scripts/windows/build-win-application.sh
All of the packages are included/bundled in the installer so any
extra link urls can only have a deterimental effect on installation
process.
Fixes gh-1261
> [FIX] Remove --find-links from the packed installer's requirements.txt

- Orange/classification/naive_bayes.py
> naive_bayes: Speed up NaiveBayesModel

- Orange/widgets/visualize/owdistributions.py
> OWDistributions: Added meta attributes

- Orange/data/domain.py
Since `bool(source)` checks `__len__`, which returns the number of attributes and class_vars, this check fails for Domains with only meta attributes.
> Domain: Fix bool(source) for only-metas data set

- Orange/canvas/application/addons.py
- Orange/canvas/config.py
- Orange/canvas/gui/utils.py
- Orange/widgets/data/owfile.py
> [ENH] Install add-on by dragging zip/tgz/wheel onto the addons dialog

- Orange/canvas/report/tests/test_report.py
- Orange/widgets/data/owpreprocess.py
> [ENH] OWPreprocess: Add report

- Orange/widgets/classify/owlogisticregression.py
- Orange/widgets/utils/owlearnerwidget.py
Sometimes, the data sets are small, the models are simple, and recalculations in light of changed parameters are fast. No need to have to navigate up and down all the time.
> [ENH] [sic] Add auto-apply checkboxes to learner dialogs

- Orange/widgets/unsupervised/owsilhouetteplot.py
The widget crashed when passed dataset (with metas) where an arbitrary class value belonged to only one data instance.
> [FIX] OWSilhouettePlot: Fixup

- Orange/canvas/report/index.html
- Orange/canvas/report/report.py
- Orange/widgets/evaluate/owpredictions.py
Added report button to Predictions widget. 
Also, modified `report_table` in `report.py` to:
* use `QTableView.itemDelegate()` for formatting values, 
* skip hidden columns.
> [ENH] Predictions: Report, Data <--> Predictions, fixups

- setup.py
Make it possible to invoke setup.py and retrive basic package metadata without
numpy installed. This makes it possible to `pip install ./` into an
environment without numpy preinstalled (https://pip.pypa.io/en/stable/reference/pip_install/#installation-order)
> setup.py: Tolerate missing numpy until build_ext is actually invoked

- scripts/windows/build-win-application.sh
- scripts/windows/install-standalone.nsi
- scripts/windows/install.nsi
> [FIX] Fix windows installer build scripts due to changed project name

- scripts/build-osx-app.sh
* Upgrade numpy in the osx application bundle (The scikit-learn (0.17.1) wheel files for macosx seem to require numpy >= 1.10 ABI
* Run basic tests in the application bundle
> [FIX] OSX app build fix

- Orange/widgets/utils/owlearnerwidget.py
An extremely crucial fix. :smile:
> Change default in learners to auto-apply

- scripts/windows/build-win-application.sh
- scripts/windows/install-standalone.nsi
- scripts/windows/install.nsi
> [ENH] Win installer: upgrade bundled numpy version to 1.10.4

- Orange/canvas/application/addons.py
Revert Add-ons sort, due to introduced type errors.
> Revert add-ons sort

- Orange/preprocess/fss.py
- Orange/widgets/data/icons/SelectColumnsRandom.svg
- Orange/widgets/data/owpreprocess.py
Added a new preprocessor to the Preprocessor widget. Selects
features at random. Both selection per proportion and selection per number of
features implemented. FIxes #1087.
> [ENH] Preprocessor widget: add random feature selection

- Orange/widgets/widget.py
For better forward compatibility with PyQt5
(was already done in d280b7d592fd2bcd180d4b664f10e0e4739f3fed but then reverted in 72412cad5ef2c44ce445a6ffbb4ed103f7e92fad)
> OWWidget: Store geometry as bytes

- Orange/widgets/data/owselectrows.py
> Select Rows: Improve layout

- Orange/data/table.py
The parameter caused an error and the warning was not shown.
> [FIX] Table: Remove parameter from warn() call

- Orange/data/domain.py
- Orange/tests/test_domain.py
- Orange/widgets/data/owselectrows.py
- Orange/widgets/utils/itemmodels.py
When working with Bag of Words models it is very inconvenient if all BoW features are present in dropdown menus. This PR filters them out for SelectRows widget.
> [ENH] Skip Hidden Attributes in SelectRows

- Orange/canvas/help/manager.py
Related to: https://github.com/biolab/orange3-example-addon/pull/4
> Allow DATA_DIR to be used in path to help files

- Orange/widgets/unsupervised/owkmeans.py
When the upper bound is higher than the number of data instances, the widget shows only a warning instead of an error (and temporarily adjusts the upper bound), as requested by @ajdapretnar in todo ticket 291, if I understood it correctly.
> KMeans: Change some errors to warnings

- Orange/preprocess/preprocess.py
> Normalize: Fix wrong example in docstring.

- Orange/widgets/data/owpaintdata.py
Paint data crashed when the data contained no (discrete) class. @ajdapretnar, this is to-do ticket 311. Please check.
The widget used to label classes as C1, C2 ... instead of using the labels present in the data.
The widget didn't disable attr2 (and probably crashed) if the data contained only a single attribute.
The widget used the input data for setting the data once, but then the only way to reset it was to re-emit the signal. I added a button Reset to Input Data, which is enabled when the input data is present. (I initially showed/disabled it, but prefer enabling/disabling since the presence of the button hints to the user that she can feed the data into the widget.)
The widget now also issues proper information and warning messages.
I removed redundant import (`File Format`).
> [ENH] OWPaintData: Fix and improve handling of input data

- Orange/widgets/data/owfile.py
- Orange/widgets/utils/domaineditor.py
- Orange/widgets/utils/filedialogs.py
> OWFile: Enable domain editing

- Orange/canvas/application/addons.py
The API is no longer accessible over plain http:
https://mail.python.org/pipermail/distutils-sig/2016-June/029125.html
> [FIX] Use https to query pypi API

- Orange/widgets/evaluate/owtestlearners.py
This PR contains the @rokgomiscek's commit from #1320 + some fixes (call `unconditional_commit`, remove unnecessary checking for `auto_apply`) + some cosmetics (renamed button, removed box).
> [ENH] Add auto apply to Test & Score

- Orange/canvas/gui/toolgrid.py
- Orange/widgets/_highcharts/orange-helpers.js
- Orange/widgets/tests/test_itemmodels.py
- Orange/widgets/utils/itemmodels.py
These are actually pretty joyful to use. We should do this more often. :smiley:
> Some PyTableModel & PyListModel touch-ups

- Orange/distance/__init__.py
- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/unsupervised/owdistances.py
- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Added support for sparse data in Distance widget. An error is raised if the metric cannot work on sparse data.
- Skip hidden attributes in HierarchicalClustering and DistanceMap Annotation combos.
> [ENH] Support Distances on Sparse Data

- Orange/widgets/data/owpaintdata.py
- Orange/widgets/data/owtable.py
Move Data Table higher in the 'suggested widgets' list
> [ENH]Move Data Table higher in the 'suggested widgets' list

- Orange/canvas/report/report.py
- Orange/widgets/visualize/owlinearprojection.py
The widget's report used to freeze and could not be opened.
> [FIX] OWLinearProjection: Fix report

- Orange/regression/linear.py
- Orange/widgets/regression/owunivariateregression.py
Fixes to Univariate regression: 
1. Widget outputs regression coefficients
2. Fixed preprocessing. It is now correctly applied to data and visible in the line plot.
> [ENH] Univar regression coefficients

- .travis/stage_script.sh
- Orange/canvas/report/report.py
- Orange/canvas/report/tests/__init__.py
- Orange/canvas/report/tests/test_report.py
- Orange/tests/test_util.py
- Orange/util.py
- Orange/widgets/evaluate/owconfusionmatrix.py
Original title: "Fix report for Confusion Matrix"
> [ENH] Nicer reporting of tabular data (e.g. Confusion Matrix)

- Orange/widgets/data/owfile.py
> [FIX] OWFile: Consider missing values when changing domain

- Orange/widgets/visualize/owsieve.py
The second part of issue #1050. Mosaic was already done some time ago.
Continuous meta attributes are not discretized and shown. If we want this, it must be solved in `Discretize`, not here.
> [ENH] Sieve: Discretize continuous variables

- Orange/data/table.py
- Orange/tests/test_sparse_table.py
- Orange/tests/test_table.py
> [FIX] Table.insert: Make a copy if necessary.

- Orange/widgets/data/owtable.py
Fix selecting when not selecting whole rows. Also make this work for sparse X.
> [FIX] Selecting in Table

- Orange/widgets/tests/test_itemmodels.py
- Orange/widgets/utils/itemmodels.py
Before it would overwrite elements which were not supposed to be overwritten when setting a slice in the middle of a sequence.
Add tests.
> [FIX] Fix and error in `PyListModel.__setitem__`

- Orange/clustering/kmeans.py
- Orange/widgets/unsupervised/owmds.py
> [FIX] Sparse K-Means, MDS

- scripts/create_changelog.sh
A script that parses git log from the last release and produces a list of introduced enhancements and fixes
Changes are output in the format that can be copy pasted to the CHANGELOG.md
> Scripts: Add create_changelog

- Orange/widgets/data/owtable.py
Support selection of separate cells on sparse data.
> [FIX] OWTable: Support selecting cells on sparse data

- Orange/widgets/data/owimageviewer.py
Fix an error revealed by gh-1381
> owimageviewer: Mark the item for update on pixmap change

- Orange/evaluation/testing.py
- Orange/tests/test_ada_boost.py
- Orange/tests/test_evaluation_scoring.py
- Orange/tests/test_evaluation_testing.py
- Orange/widgets/evaluate/owtestlearners.py
- requirements-core.txt
> Revert "[ENH] Parallelized cross validation & other evaluation methods"

- Orange/widgets/utils/progressbar.py
Convert progress bar value to int so it can be used with the %d format.
> ProgressBarMixin: Round value before showing

- Orange/base.py
- Orange/data/filter.py
- Orange/data/io.py
- Orange/data/table.py
- Orange/data/util.py
- Orange/preprocess/preprocess.py
- Orange/statistics/util.py
- Orange/tests/test_basic_stats.py
- Orange/tests/test_contingency.py
- Orange/tests/test_data_util.py
- Orange/tests/test_statistics.py
- Orange/tests/test_util.py
- Orange/util.py
- Orange/widgets/classify/tests/test_owlogisticregression.py
- requirements-core.txt
- scripts/build-osx-app.sh
- scripts/windows/build-win-application.sh
Another try at https://github.com/biolab/orange3/pull/1337.
> Bottlechest, Bottleneck (v2)

- Orange/canvas/application/addons.py
> [ENH] Proxy support for add-on installation

- Orange/evaluation/testing.py
- Orange/tests/test_ada_boost.py
- Orange/tests/test_evaluation_scoring.py
- Orange/tests/test_evaluation_testing.py
- Orange/widgets/evaluate/owtestlearners.py
- requirements-core.txt
> Revert "Revert "[ENH] Parallelized cross validation & other evaluation methods""

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
> Statistics.util.stats: Support sparse data

- Orange/canvas/preview/previewbrowser.py
Sample first 10 items to get a better height hint due to text's
line wrapping.
> [ENH] canvas/preview: Improve size hinting for the LinearIconView

- Orange/base.py
- Orange/regression/linear.py
- Orange/tests/test_linear_regression.py
- doc/data-mining-library/source/reference/regression.rst
Polynomial learner used to construct 1 degree polynomials by default.
This PR also includes it in documentation.
> Update defaults in PolynomialLearner

- Orange/classification/logistic_regression.py
- Orange/tests/test_logistic_regression.py
> Logistic Regression: Handle single class data

- Orange/widgets/classify/owknn.py
- Orange/widgets/classify/tests/test_owclassificationtree.py
- Orange/widgets/classify/tests/test_owlogisticregression.py
- Orange/widgets/classify/tests/test_owmajority.py
- Orange/widgets/classify/tests/test_ownaivebayes.py
- Orange/widgets/classify/tests/test_owrandomforest.py
- Orange/widgets/regression/tests/test_owknnregression.py
- Orange/widgets/regression/tests/test_owmean.py
- Orange/widgets/regression/tests/test_owrandomforestregression.py
- Orange/widgets/regression/tests/test_owregressiontree.py
- Orange/widgets/regression/tests/test_owsgdregression.py
- Orange/widgets/regression/tests/test_owsvmregression.py
- Orange/widgets/tests/base.py
- Orange/widgets/utils/owlearnerwidget.py
> [ENH] Support learner widgets testing

- Orange/widgets/classify/owlogisticregression.py
- Orange/widgets/classify/tests/test_owlogisticregression.py
Add nonstandard output (coefficients) test.
Set up learner parameters-gui mapping.
> LogisticRegression: Improve tests

- Orange/widgets/visualize/icons/PythagoreanForest.svg
- Orange/widgets/visualize/icons/PythagoreanTree.svg
Remove an image element referencing a non-existent "6422615809691E22.jpg"
> Cleanup Pythagorean Tree/Forest icons

- Orange/widgets/classify/owclassificationtree.py
- Orange/widgets/classify/tests/test_owclassificationtree.py
- Orange/widgets/regression/tests/test_owregressiontree.py
> [ENH] TestWidgetTree: Cls and reg tree widgets test upgrade

- Orange/widgets/visualize/utils/__init__.py
Give data to scatter plot, remove it, and it shows message "There is nothing to rank".
> VizRank: Display error message in dialog, not in master

- Orange/widgets/data/owmergedata.py
- Orange/widgets/visualize/owvenndiagram.py
Fixes https://github.com/biolab/orange3/issues/1450
> OWMergeData: replace list views with combos, save settings

- Orange/widgets/classify/owrandomforest.py
- Orange/widgets/tests/base.py
> [FIX] OWRandomForest: Show/hide error message

- Orange/widgets/utils/messages.py
- Orange/widgets/widget.py
> MessagesMixin: Retrieve attributes without triggering dynamic lookup

- Orange/widgets/classify/tests/test_owadaboostclassification.py
- Orange/widgets/classify/tests/test_owclassificationtree.py
- Orange/widgets/classify/tests/test_owknnclassification.py
- Orange/widgets/classify/tests/test_owlogisticregression.py
- Orange/widgets/classify/tests/test_owrandomforest.py
- Orange/widgets/regression/tests/test_owadaboostregression.py
- Orange/widgets/regression/tests/test_owknnregression.py
- Orange/widgets/regression/tests/test_owrandomforestregression.py
- Orange/widgets/regression/tests/test_owregressiontree.py
- Orange/widgets/tests/base.py
> WidgetLearnerTest: GuiToParam refactor

- Orange/canvas/report/tests/test_report.py
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/visualize/owsilhouetteplot.py
Seems to run without segfaulting.
> Enable report testing

- MANIFEST.in
- setup.py
Documentation datasets for distances (*.dst) were not included in packages.
> Include .dst files in packages

- Orange/widgets/visualize/owscatterplot.py
> [FIX] ScatterPlot: Score Plots window title changed to title case

- Orange/widgets/gui.py
> gui: Fix a broken widget layout produced in lineEdit

- Orange/widgets/data/owpreprocess.py
> OWPreprocess: increase widgts' sizeHint

- Orange/widgets/regression/owlinearregression.py
- Ensure a width of at least as many pixels as it has steps (ie >100)
- Change upper limit to 0.99 (from 1), we do not allow 0 either.
(use explicit L1 or L2 for pure versions)
> owlinearregression: Improve slider for EN mixing

- Orange/widgets/unsupervised/owkmeans.py
> [FIX] Fix K-means commit behaviour

- Orange/data/table.py
- Orange/preprocess/transformation.py
- Orange/tests/test_data_util.py
> SharedComputeValue: functions called only once also with later transformations

- scripts/build-osx-app.sh
> Updated pip in OS X dmg because newer version handles wheels better

- Orange/data/domain.py
> Avoid frequent recomputation of domain hashes.

- Orange/widgets/data/owfile.py
- Orange/widgets/utils/domaineditor.py
Focusing on URL now selects text (todo id 241)
Entering an empty URL no longer reports an error (todo id 331)
> [ENH] File widget improvements

- Orange/widgets/data/owpythonscript.py
- Orange/widgets/data/tests/test_owpythonscript.py
- Orange/widgets/tests/test_scatterplot_density.py
The widget didn't clear variables from previously executed scripts.
> OWPythonScript: Update locals when script is executed

- Orange/widgets/data/owpaintdata.py
- Orange/widgets/gui.py
> gui: Remove return icon

- Orange/widgets/data/owrank.py
But only if header has not been clicked. In that case, attributes remains sorted the way user wanted.
> OWRank: Sort attributes by first visible score

- Orange/canvas/application/workflows/450-cross-validation.ows
We changed the settings for the Confusion Matrix since the schema was created.  To reproduce the bug, just open the (old) schema.
> Cross validation example workflow: fix confusion matrix settings

- Orange/widgets/visualize/owscatterplotgraph.py
> Subset selection in Scatter Plot now made bolder.

- Orange/widgets/data/owpythonscript.py
> OWPythonScript: Don't trigger reporting on errors

- Orange/widgets/visualize/owscatterplot.py
> [FIX] OWScatterPlot: Fix progress bar percentages

- Orange/preprocess/preprocess.py
- Orange/tests/test_normalize.py
Enable skipping of normalisation for data sets where all features are marked as already normalised. Used for enabling SVMs on sparse BoW data.
> Sparse SVM

- Orange/widgets/tests/base.py
> WidgetTest: Reset context settings

- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
> [FIX] OWBoxPlot: Reset widget's appearance when data is removed

- doc/development/source/orange-demo/orangedemo/OWLearningCurveA.py
- doc/development/source/orange-demo/orangedemo/OWLearningCurveB.py
Related to discussion in #1443.
> Updated development documentation.

- Orange/classification/_tree_scorers.c
- Orange/classification/_tree_scorers.pyx
Use numpy's npy_isnan instead of clib's isnan.
Fix an 'unresolved external symbol _isnan' when compiling with MSVC 2010
(default compiler for Python 3.4).
> [MAINT] tree_scorers: Fix compatibility with MSVC 2010

- README.md
> Updated README.md for Anaconda installation

- Orange/widgets/visualize/utils/__init__.py
This was implemented for Box plot, but it's not needed: the widget shows a list view and we can simply order attributes there. The class may still be useful elsewhere.
> Add VizRankDialogAttr

- Orange/data/sql/table.py
- Orange/widgets/data/owsql.py
Widget should work even if psycopg2 is not installed as there might be some other backend available.
> OWSql: Decouple from psycopg2 driver

- Orange/widgets/__init__.py
Documentation wasn't working if offline. Now the path is fixed.
> Fixed path to built documentation if online.

- Orange/widgets/classify/owknn.py
Typo in the `__main__` test function.
> Fix knn anyqt: Fix typo

- Orange/widgets/visualize/owvenndiagram.py
- Orange/widgets/visualize/tests/test_owvenndiagram.py
> OWVennDiagram: Output Annotated Data

- Orange/widgets/tests/test_itemmodels.py
- Orange/widgets/utils/itemmodels.py
- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
<del>Based on #1405 (not master).</del>
> VizRank-like function for Box Plot

- Orange/widgets/visualize/owpythagorastree.py
- Orange/widgets/visualize/pythagorastreeviewer.py
- Orange/widgets/visualize/tests/test_owpythagorastree.py
Fix weight adjustment in Pythagorean tree widget - they were broken with the new trees.
> Fix pythagorean weights

- Orange/widgets/unsupervised/owmanifoldlearning.py
Editors weren't derived from `OWComponent`, were not registered as `SettingProvider` and their settings were not saved in schemata.
> Manifold learning: fix settings

- .github/PULL_REQUEST_TEMPLATE.md
Descriptions of Pull Requests are often uninformative or even missing.
PR template updated.
> github: Update PR template

- Orange/widgets/visualize/owpythagoreanforest.py
- Orange/widgets/visualize/tests/test_owpythagoreanforest.py
Add tests for Pythagorean forest UI options.
> Tests pythagorean forest

- Orange/widgets/visualize/owpythagorastree.py
- Orange/widgets/visualize/tests/test_owpythagorastree.py
Add widget tests for Pythagorean tree widget and fixup some deprecation warnings from `gui` library.
> Pythagorean tree: Add tests for widget

- Orange/canvas/application/errorreporting.py
> errorreporting: also report exception locals()

- Orange/projection/manifold.py
- Orange/tests/test_manifold.py
- Orange/widgets/unsupervised/owmanifoldlearning.py
- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py
- Orange/widgets/unsupervised/tests/test_owmds.py
> [ENH] OWManifoldLearning: MDS - enable PCA initialization

- Orange/widgets/unsupervised/owmanifoldlearning.py
- requirements-core.txt
The distance was not added before, since there was a bug in sklearn, which is now fixed.
https://github.com/scikit-learn/scikit-learn/pull/7732
> OWManifoldLearning: Add cosine distance to t-SNE

- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/tests/test_owdistributions.py
Distributions should work on meta attributes as well (if they are continuous or discrete)
Include discrete metas in Group by combo box.
Fix bug when meta attribute is selected.
> OWDistributions: Consider discrete and continuous metas

- Orange/data/sql/backend/mssql.py
- Orange/data/sql/backend/postgres.py
- Orange/data/sql/table.py
- Orange/tests/sql/test_sql_table.py
- doc/visual-programming/source/index.rst
- doc/visual-programming/source/widgets/data/sql.rst
Some features were missing from mssql backend.
Add the missing features.
> Improved mssql support

- Orange/distance/__init__.py
While exploring Orange codebase, Orange.distance seemed not to follow PEP8 (Style Guidelines for Python Code), specially maximum line length.
Made the code more readable while not touching the doctrings.
> made the code more readable as per PEP8 in Orange.distance

- Orange/__init__.py
- Orange/widgets/classify/owloadclassifier.py
- Orange/widgets/classify/owsaveclassifier.py
- Orange/widgets/classify/tests/test_owloadclassifier.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
- conda-recipe/meta.yaml
- requirements-core.txt
... which supports (nearly) arbitrary Python objects.
Fixes https://github.com/biolab/orange3/issues/1758
> OWSaveClassifier: Pickle stuff with dill

- Orange/widgets/visualize/tests/test_owboxplot.py
Selection is saved to Context setting and therefore should be tested
> OWBoxPlot: Test saved selection

- Orange/misc/distmatrix.py
- Orange/regression/tree.py
- doc/data-mining-library/source/conf.py
- doc/data-mining-library/source/reference/classification.rst
- doc/data-mining-library/source/reference/code/imputation-average.py
- doc/data-mining-library/source/reference/code/imputation-default.py
- doc/data-mining-library/source/reference/data.io.rst
- doc/data-mining-library/source/reference/data.value.rst
- doc/data-mining-library/source/reference/data.variable.rst
- doc/data-mining-library/source/reference/preprocess.rst
Scripting documentation missing reference on imputation.
A sorry attempt at updating scripting documentation. Some typos fixed. Imputation added.
> Updates to scripting documentation: Impute and typos

- Orange/widgets/visualize/owscatterplot.py
> [FIX] Scatterplot: Allow labelling by string attributes

- Orange/widgets/data/owimageviewer.py
Image Viewer won't display images from Import Images on Windows.
Set path to local files properly. Thanks @astaric.
> OWImageViewer: Fix missing images on windows

- Orange/modelling/base.py
- Orange/widgets/utils/owlearnerwidget.py
Typo in base learner widget comments, also in Fitter meta exception.
> Learner: Fix typo in learner comments

- Orange/widgets/visualize/owheatmap.py
> OWHeatmap: consistent threshold limits and attribute checks

- Orange/widgets/utils/colorpalette.py
- Orange/widgets/utils/tests/test_colorpalette.py
Fixes gh-1888
Make ColorPalette extend gui.OWComponent to satisfy gui.{comboBox,checkBox}
> [FIX] colorpalette: Fix AttributeError 

- Orange/widgets/data/owoutliers.py
- Orange/widgets/data/tests/test_owoutliers.py
Fixes #1906
Show error message when dataset has multiple class variables.
> [WIP] OWOutliers: Fix crash for multiclass dataset

- MANIFEST.in
- Orange/widgets/evaluate/owconfusionmatrix.py
- Orange/widgets/visualize/owvenndiagram.py
- setup.py
> Include metadata in distribution.

- Orange/widgets/utils/domaineditor.py
Use numpy instead of python lists. Faster name changes.
Fixes #1866.
> Domain editor speedup

- Orange/widgets/data/owimpute.py
- Orange/widgets/data/tests/test_owimpute.py
Imputation widget did not catch exceptions from imputers
> [FIX] Impute: Fix crash when model-based imputation fails

- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/tests/test_owheatmap.py
Fixes:
https://sentry.io/biolab/orange3/issues/196744359/
https://sentry.io/biolab/orange3/issues/196744301/
https://sentry.io/biolab/orange3/issues/205034712/
https://sentry.io/biolab/orange3/issues/205413981/
https://sentry.io/biolab/orange3/issues/196744355/
To reproduce use:
1. File (iris) -> Data Table (select one line) -> HeatMap (try different combinations of Sorting and Merging)
2. File (iris) -> Select Columns (select one feature) -> HeatMap (try different combinations of Sorting and Merging)
> OWHeatMap: Fix crash when data is one instance or one feature

- Orange/canvas/application/errorreporting.py
> ErrorReporting: Escape string representation of value

- CONTRIBUTING.md
- Orange/tests/test_preprocess.py
- Orange/tests/test_util.py
- Orange/widgets/_highcharts/chart.html
- Orange/widgets/_highcharts/orange-selection.js
- Orange/widgets/highcharts.py
- Orange/widgets/tests/test_highcharts.py
- Orange/widgets/utils/__init__.py
- Orange/widgets/utils/_webview/helpers.js
- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_webview.py
- Orange/widgets/utils/webview.py
- Orange/widgets/visualize/owmap.py
> Geomap & webview updates

- Orange/widgets/highcharts.py
- doc/development/source/code/owScatterplot.py
Closes https://github.com/biolab/orange3/issues/1500
> doc/devel/highcharts: mention evaluating JS expressions

- Orange/widgets/tests/base.py
- doc/development/source/index.rst
- doc/development/source/testing.rst
Mention widget testing base class in documentation.
> Widget testing documentation stub.

- .travis/stage_script.sh
They are randomly segfaulting too often
> travis: do not run report tests

- Orange/widgets/visualize/ownomogram.py
- Orange/widgets/visualize/tests/test_ownomogram.py
Fixes https://sentry.io/biolab/orange3/issues/210022780/
> OWNomogram: Handle data with constant features

- Orange/widgets/visualize/ownomogram.py
When opening report right edge of the scene fell out.
> [FIX] OWNomogram: Adjust scene rect

- Orange/widgets/visualize/ownomogram.py
> OWNomogram: Initialize values of continuous features

- Orange/widgets/data/owdatasampler.py
- Orange/widgets/data/tests/test_owdatasampler.py
> [FIX] OWDataSampler: Fix 'Fixed proportion of data' option

- .coveragerc
- .travis.yml
Make tests with pyqt5 and lint mandatory again
Include widgets in coverage
> Stricter travis

- Orange/widgets/widget.py
> OWWidget: Mark as explicitly positioned on first show

- Orange/widgets/data/owmergedata.py
Make workflows with OWMergeData, create before #2012, work.
Set 'replaces' parameter for output signal
> OWMergeData: Set 'replaces' for output signal

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
Inconsistent behaviour and crashes when predictors have mismatching targets
Fix.
> Predictions: Fix handling of mismatching targets

- Orange/canvas/application/workflows/250-tree-scatterplot.ows
Fixes #2005. 
Schema set to the new Classification Tree so the learner doesn't fail.
Output of Tree Viewer set to Data Subset for both Box Plot and Scatter Plot.
> Updated Classification Tree schema

- Orange/widgets/data/icons/Random.svg
> [FIX] OWRandomize: New icon

- Orange/__init__.py
Refs: 2d5d88c35601e758f24bdab897aa14993b2ce558
Fixes: https://github.com/biolab/orange3/pull/2072#issuecomment-284980687
> Have AnyQt pin the chosen PyQt version before other libs

- doc/data-mining-library/source/index.rst
- doc/data-mining-library/source/reference/projection.rst
Add basic documentation for working with PCA in the scripting part.
> Basic docs for PCA

- Orange/widgets/data/owpaintdata.py
- Orange/widgets/gui.py
Fixes #2055. 
Changed QListView to Orange's view with size hint.
> owPaintData: Fixed Labels column size

- Orange/base.py
- Orange/classification/__init__.py
- Orange/classification/neural_network.py
- Orange/modelling/__init__.py
- Orange/modelling/neural_network.py
- Orange/regression/__init__.py
- Orange/regression/neural_network.py
- Orange/tests/test_neural_network.py
- doc/data-mining-library/source/reference/classification.rst
- doc/data-mining-library/source/reference/regression.rst
Add supervised neural networks from sklearn (for classification and regression)
Closes https://github.com/biolab/orange3/issues/28.
Wrap MLPClassifier and MLPRegressor to get classification.NNClassificationLearner and regression.NNRegressionLearner.
Merge them into model.NNLearner.
> NeuralNetwork: Add sklearn neural networks

- Orange/classification/rules.py
- Orange/tests/test_rules.py
- Orange/widgets/tests/base.py
- Orange/widgets/tests/datasets/testing_dataset_cls.tab
- Orange/widgets/tests/datasets/testing_dataset_reg.tab
Widgets crash on 'ugly' datasets (datasets with constant features, missing values, ...). It should be supported in tests.
> WidgetLearnerTestMixin: Replace testing datasets with 'uglier' ones

- Orange/widgets/visualize/owsilhouetteplot.py
> OWSilhouettePlot: Color each cluster with different color

- Orange/canvas/report/report.py
> Report: Display only first 100 rows when reporting table

- scripts/create_changelog.sh
Changes for a new release were repeating items from previous bugfix releases.
Grab all PR ids (#XXXX) from existing changelog and filter them out from the proposed new ones.
> create_changelog: Filter out already reported items

- Orange/__init__.py
- Orange/modelling/__init__.py
- Orange/modelling/ada_boost.py
- Orange/modelling/constant.py
- Orange/modelling/knn.py
- Orange/modelling/linear.py
- Orange/modelling/neural_network.py
- Orange/modelling/randomforest.py
- Orange/modelling/svm.py
- Orange/modelling/tree.py
- Orange/widgets/model/owsvm.py
> Fitter import fixes

- Orange/widgets/evaluate/tests/test_owrocanalysis.py
Prevents strange test failure.
Tests failed sometimes (but very rarely).
> test_owrocanalysis: fix random seed

- Orange/widgets/data/owdatasampler.py
> [FIX] OWDataSampler: Fix typo boostrap to bootstrap

- Orange/data/table.py
- Orange/preprocess/preprocess.py
- Orange/tests/test_sparse_table.py
> Randomize: Support sparse matrix randomization

- Orange/widgets/unsupervised/owmanifoldlearning.py
- Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py
> OWManifoldLearning: Show error msg when data is sparse

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
> Scatter Plot: Now stores selection in Settings

- Orange/widgets/unsupervised/owhierarchicalclustering.py
> Hierarchical Clustering: lint

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
> Revert "Scatter Plot: Rank Informative projections & color variable"

- Orange/canvas/document/schemeedit.py
> Canvas Schema: show widget upon clicking it

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owscatterplotgraph.py
Enable/disable class density on changes to color variable.
> [FIX] Scatter Plot: update class density

- Orange/canvas/application/errorreporting.py
No new error reports in the last five day.
http -> https
> [FIX] Error Report: URL changed

- Orange/widgets/model/owtree.py
> Tree: compatibility when loading old schemes

- Orange/widgets/unsupervised/owpca.py
- Orange/widgets/unsupervised/tests/test_owpca.py
Fixes #2159.
Show error message when sparse data comes into the PCA widget.
> PCA: Show Error Message for Sparse Data

- Orange/tests/test_table.py
Table Test (_test_table.py_) does not remove a created file after the end of the test.
> [FIX] Table Test: remove created file

- Orange/widgets/evaluate/owtestlearners.py
When test data was missing the target variable, the error for it missing in train data was shown.
Show correct error.
> [FIX] owtestlearners: Show correct error

- Orange/widgets/visualize/owsieve.py
- Orange/widgets/visualize/tests/test_owsieve.py
> Sieve Diagram: Sparse Support

- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/tests/test_owmosaic.py
> Mosaic: tests

- Orange/widgets/data/owpaintdata.py
- Orange/widgets/data/tests/test_owpaintdata.py
> Paint Data: Show error msg when data is sparse

- Orange/preprocess/impute.py
- Orange/tests/test_impute.py
> Impute: remove nan values in sparse

- Orange/canvas/icons/Search.svg
- Orange/canvas/styles/orange/Arrow.svg
- Orange/canvas/styles/orange/Document Info.svg
- Orange/canvas/styles/orange/Grid.svg
- Orange/canvas/styles/orange/Search.svg
I don't know if you will like this icons but the changes that I made are mainly to differentiate the search icon from the zoom icon.
> Change toolbar's icons

- Orange/data/table.py
In discussion with @astaric and @nikicc we dediced that each function working with sparse matrices should handle the conversion to csc or csr, whatever is more convenient at that moment.
Then, of course, then, the type of data.X can be either and is never guaranteed.
> Sparse distributions speedup

- doc/development/source/tutorial.rst
> outpus->output

- Orange/widgets/visualize/icons/Nomogram.svg
> nomogram icon

- .travis.yml
- .travis/install_postgres.sh
- .travis/install_pyqt.sh
Builds failing.
Disable Py3.5,Qt4, enable Py3.6, enable dist=trusty, Qt5 default.
> travis: disable Py3.5,Qt4, enable Py3.6, enable trusty, Qt5 default

- Orange/widgets/model/owrules.py
- Orange/widgets/model/tests/test_owrulesclassification.py
- Orange/widgets/utils/owlearnerwidget.py
#2161
Added error message when data is sparse.
> CN2 Rule Induction: Show error message when data is sparse

- Orange/evaluation/testing.py
- Orange/tests/test_evaluation_testing.py
- Orange/widgets/gui.py
- doc/development/source/index.rst
- doc/development/source/orange-demo/orangedemo/OWDataSamplerA.py
- doc/development/source/orange-demo/orangedemo/OWDataSamplerB.py
- doc/development/source/orange-demo/orangedemo/OWDataSamplerC.py
- doc/development/source/orange-demo/orangedemo/OWLearningCurveA.py
- doc/development/source/orange-demo/orangedemo/OWLearningCurveC.py
- doc/development/source/tutorial-responsive-gui.rst
- doc/development/source/tutorial-utilities.rst
Add a tutorial on responsive GUI programming
* Yet another Learning Curve example widget is implemented.
> [ENH] Add a tutorial section on responsive GUI

- Orange/widgets/data/owoutliers.py
- Orange/widgets/data/tests/test_owoutliers.py
https://sentry.io/biolab/orange3/issues/196743615/
> [FIX] Outliers: handling memory error

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
https://sentry.io/biolab/orange3/issues/288212407/
> [FIX] Scatter Plot: features and no data

- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/tests/test_owdistributions.py
https://sentry.io/biolab/orange3/issues/288148330/
> [FIX] Distributions: do not crash on empty data

- Orange/clustering/hierarchical.py
- Orange/tests/test_clustering_hierarchical.py
Validate the the input linkage matrix and raise an error if invalid
> clustering/hierarchical: Check the input linkage matrix

- Orange/evaluation/scoring.py
- Orange/tests/test_evaluation_scoring.py
- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
We want to let add-ons add new classes for scoring models. The Test & Score widget should recognize and use them.
- PR implements a registry of subclasses of `Score` through meta class `ScoreMetaType`. It is derived from `WrapperMeta` and implements a registry. Multiple inheritance (from `Registry`) can't be used since a class can't have two `__new__` methods.
- Subclasses of `Score` can provide a better name and a tooltip for the column. This is undesirable (the code on this level shouldn't be aware of GUI) but rather inevitable if we want to let add-ons add stuff to widgets.
- Subclasses of `Score` can be declared abstract (see `ClassificationScore`, `RegressionScore`)
- The Test & Score widget takes all non-abstract scores from the registry. Built-in scores are ordered as they were …
> Scoring: Implement a registry of Score classes

- Orange/data/domain.py
- Orange/data/variable.py
- Orange/tests/test_domain.py
Implements methods to verify if a variable is of time TimeVariable and if there is any TimeVariables in the domain's attributes or class
Add new methods to Variable and Domain classes
> Add verification methods for TimeVariable

- .travis/stage_script.sh
> Debug travis lint failures

- .travis/stage_script.sh
> Do not use exit in travis scripts

- doc/data-mining-library/source/tutorial/classification.rst
- doc/data-mining-library/source/tutorial/code/classification-accuracy-train.py
- doc/data-mining-library/source/tutorial/code/classification-classifier1.py
- doc/data-mining-library/source/tutorial/code/classification-classifier2.py
- doc/data-mining-library/source/tutorial/code/classification-models.py
- doc/data-mining-library/source/tutorial/code/regression-tree.py
- doc/data-mining-library/source/tutorial/code/zoo.tab
- doc/data-mining-library/source/tutorial/data.rst
Fixes #2446.
Attempt at updating and improving the scripting tutorial.
> [RFC] Update scripting tutorial

- .codeclimate.yml
Too many similar code "false positives" on CodeClimate.
Raise duplicate snippet mass threshold.
> MNT: codeclimate: configure duplication check for less false positives

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
- Orange/widgets/visualize/ownomogram.py
- Orange/widgets/visualize/tests/test_ownomogram.py
Fixes https://github.com/biolab/orange3/issues/2280
Fix slowness by only recomputing what is selected/drawn.
Also split main view into three parts.
> Update Nomogram widget

- Orange/widgets/visualize/owmap.py
- Orange/widgets/visualize/tests/test_owmap.py
Tests sometimes ran something and didn't run other times, influencing changing coverage percentage across runs.
Make more deterministic, calling functions explicitly.
> OWMap: make tests more deterministic

- Orange/widgets/data/owcreateclass.py
- Orange/widgets/data/tests/test_owcreateclass.py
https://sentry.io/biolab/orange3/issues/284516465/
> [FIX] Create Class: class name cannot be empty

- Orange/widgets/unsupervised/tests/test_owpca.py
Appveyor tests sometimes failed.
> owpca: fix nondeterministic? tests

- Orange/widgets/visualize/owscatterplotgraph.py
> [FIX] Scatter Plot Graph: legend symbols color

- Orange/widgets/gui.py
Docstring was incorrect.
Change documenation to reflect actual code.
> [DOC] auto_commit: Fix outdated docstring

- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/utils/__init__.py
The old code added some GUI manipulation into the thread. To prevent this in
the future I moved the computation loop into the worker class.
> owmosaic: fix VizRank crashing or freezing

- Orange/widgets/widget.py
> [FIX] Widget: splitter sizes

- doc/data-mining-library/source/reference/projection.rst
> doc: projection

- .travis/stage_script.sh
- Orange/widgets/tests/test_workflows.py
Coverage reports random increases/decreses
Exclude workflow compatibility from coverage
> tests: Compatibility with old workflows without coverage

- .travis.yml
- .travis/install_postgres.sh
> travis: Add python3.6 to build matrix

- Orange/classification/simple_tree.py
- Orange/data/io.py
- Orange/tests/test_simple_tree.py
- Orange/tests/test_tab_reader.py
> io: Compute number of decimals for numeric variables

- Orange/data/io.py
Attempt at solving #2404. 
Increase csv field limit.
> Increase field limit

- Orange/widgets/visualize/owscatterplotgraph.py
> [FIX] ScatterPlotGraph: fix labelling when there are missing data

- Orange/widgets/evaluate/owconfusionmatrix.py
> Nicer layout for OWConfusionMatrix

- Orange/widgets/model/icons/AdaBoost.svg
Fixes #2619
Also checked add-ons bio, educational, associate, geo, imageanalytics, network, prototypes, text (I will open a pull request there), timeseries.
> Encoding in all .svg files is now utf-8

- Orange/widgets/unsupervised/owmds.py
> [FIX] MDS: Primitive metas

- Orange/widgets/widget.py
The widget height can't be smaller than control area even when the control area is hidden.
- Override splitter's `sizeHint` and `minimumSize` to ignore the control area when hidden.
- Call `updateGeometry` on splitter when hiding/showing the control area.
- I see no reasonable non-trivial way to test this.
> Allow the widget height to be smaller than control area when the control area is hidden

- Orange/widgets/utils/tests/test_webview.py
- Orange/widgets/utils/webview.py
- Orange/widgets/visualize/tests/test_owmap.py
Cover more of webview code → avoid [random coverage](https://github.com/biolab/orange3/wiki/Random-coverage).
> TST: cover more of webview/owmap with tests

- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owscatterplotgraph.py
* Scatter Plot Graph cannot handle sparse data.
* As of #2648 MDS did not work for sparse data.
* Scatter Plot Graph and Scaling can now handle sparse data and primitive data in metas by themselves.
* Fix MDS to handle sparse data.
> MDS: Fixup for Sparse Data

- Orange/widgets/data/owdatasets.py
- Orange/widgets/data/tests/test_owdatasets.py
Yesterday's change broke datasets that were not cached.
> owdatasets: fix dataset download

- Orange/widgets/data/owpythonscript.py
- Orange/widgets/tests/workflows/3_5_0_python_script.ows
Old schemas did not open. Someone forgot that "replaces" should be a list.
> Fix PythonScript old schema compatibility

- Orange/canvas/report/owreport.py
Fixes https://github.com/biolab/orange3/issues/2708
> OWReport: fix printing to PDF on WebEngine

- Orange/widgets/visualize/owtreeviewer2d.py
Fixes #2704 .
2. Set minimum line width to make sure that it is visible.
> [FIX] Tree Viewer: reset view to top left

- Orange/widgets/visualize/owscatterplotgraph.py
Zoom does not work. (CTRL + and CTRL -)
> [FIX] ScatterPlotGraph: fix zoom CTRL + and CTRL -

- Orange/widgets/data/owdatasets.py
- Orange/widgets/data/tests/test_owdatasets.py
Refactoring:  Moved constants with local and remote locations inside the class along with some util functions. This makes the widget more self contained and allows easier reuse / modifications.
> owdatasets: Move constants and util functions

- Orange/widgets/data/owdatasets.py
Selected data set was not saved (something else was)
> OWDatasets: fix saving selection

- Orange/widgets/visualize/owsilhouetteplot.py
QSizeF.transposed is not available on Qt4.
> owsilhuetteplot: use QSizeF.transpose

- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/utils/domaineditor.py
Fixes https://github.com/biolab/orange3/issues/2744
> DomainEditor: fix round-continuous-with-nans to string conversion

- Orange/classification/naive_bayes.py
- Orange/tests/test_naive_bayes.py
Fixes https://github.com/biolab/orange3/issues/2740
> NaiveBayes: fix computation on all-nan instances

- Orange/widgets/data/owdatasets.py
Some leftover uses of (prefix, filename) were causing problems.
Use file_path
> owdatasets: Further generalizations of the widget

- MANIFEST.in
> Typo in MANIFEST

- doc/visual-programming/source/widgets/model/neuralnetwork.rst
Doc for NN were off.
Fixed critical issues reported by Sphinx.
> Small doc fix for NN

- Orange/canvas/preview/previewmodel.py
- Orange/canvas/preview/scanner.py
Old sins die hard.
* Render preview icons without writing the svg to disk
* Strip the node 'properties' from the .ows before parsing for preview rendering.
> [ENH] Canvas: Improve preview rendering

- Orange/widgets/widget.py
Widgets store their geometry but not the visibility of `controlArea`.
Store the visibility as a setting.
> OWWidget: Store control area visibility as setting

- Orange/widgets/data/owsave.py
- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/data/tests/test_owsave.py
- Orange/widgets/utils/filedialogs.py
OWSave refactored to use open_filename_dialog
> Refactor OWSave

- doc/visual-programming/source/widgets/data/mergedata.rst
Minor fixes to Merge data widget documentation.
> Merge data documentation

- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/owradviz.py
Code a little bit too complicated.
Simplifying. See https://github.com/biolab/orange3-network/pull/62#discussion_r161043132 .
> [REF] Radviz, FreeViz: mouse cursor

- Orange/widgets/visualize/owsieve.py
- Orange/widgets/visualize/tests/test_owsieve.py
No test for removing data input.
Test added. Also a minor streamlining of tests. Couldn't add 'titanic' to the final one, I reckon file too big.
> Added a simple unittest to Sieve

- .travis/install_pyqt.sh
- README.md
Fixes https://github.com/biolab/orange3/issues/2891
> [MNT, DOC] Build failures and update Readme

- Orange/widgets/evaluate/tests/test_owtestlearners.py
Added unitests for checking the correctness of scores in Test and Score widget.
> Test and Score: Unittests that test the correctness of scores

- Orange/data/io.py
- Orange/tests/test_txt_reader.py
Fixes gh-2997
* Preserve `original_values` to pass to `guess_data_type`.
* Add a namask argument to it.
> [FIX] Fix variable type guessing
