biolab/orange3

Orange/distance/__init__.py
Orange/tests/test_distances.py
Orange/widgets/unsupervised/owdistances.py

Mahalanbois was removed due to instability. Calculation of inverse of covariance matrix causes the results to vary between different machines. This causes the problems when running tests.

Removed Mahalanobis distance

---

Orange/widgets/visualize/owscatterplotgraph.py

When the selected area has height 0 and the mouse is currently over a legend, Orange crashed with the following error:
`Assertion failed: (transform_is_valid(m)), function CGMutablePathRef CGPathCreateMutableCopyByTransformingPath(CGPathRef, const CGAffineTransform *), file Paths/CGPath.cc, line 168.`
To fix this we update the `self.updateScaleBox` in a safe manner by forcing the height to be at least one pixel.

Fixed assertation failed error for Scatterplot

---

Orange/widgets/data/owtable.py
Orange/widgets/gui.py
Orange/widgets/utils/colorpalette.py
Orange/widgets/utils/plot/owplot.py
Orange/widgets/utils/plot/owplotgui.py
Orange/widgets/utils/toolbar.py
Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/owsieve.py

I believe I correctly ported all signals to new style. The only place which I knowingly omitted is line 1257 in owplot.py, `if self.receivers(SIGNAL('point_hovered(Point*)')) > 0:`. I have not found any documentation whether new style signals have method `receivers` and the code belongs to a class derived from orangeqt, therefore it is obsolete, difficult to test and may even not be portable to Qt 5, so there is not much point in changing it to new style.

New style signals

---

Orange/projection/manifold.py
Orange/projection/pca.py
Orange/widgets/unsupervised/owmds.py
Orange/widgets/unsupervised/owpca.py

Use Orange projections in MDS and PCA widgets instead of projections from Sklearn.

Use Orange projections in MDS and PCA widgets. 

---

Orange/evaluation/scoring.py

Seems that IP notebook can display a graph that was created within the function withouth returning the graph object. If this later is returned, the notebook displays two figures instead of one.

Returning fig redundant for IP Notebook.

---

Orange/data/variable.py
Orange/testing/__init__.py
Orange/tests/sql/test_sql_table.py
Orange/tests/test_continuize.py
Orange/tests/test_domain.py
Orange/tests/test_simple_tree.py
Orange/tests/test_variable.py

@astaric Almost there. The tests that fails is test_SimpleTree_classification_pickle, yet the problem is general. The test uses data with domain with variables that have no names (e.g. empty strings) and have values [0, 1]. Variable unpickler cannot distinguish between them and thus cannot unpickle them correctly. We can't solve this: this test will never pass.
Solutions:
- anonymous variables cannot be pickled (`Variable.__reduce__` raises an exception if `not self.name`),
- anonymous variables are not allowed at all (`Variable.__init__` raises an exception if the name is empty).
I vote for the former. Let us allows "quick variables", but they are temporary in nature, so they cannot be pickled.
Perhaps we should go further: anonymous variables should not be stored in `all_vars` and …

Variable unpickler uses make; anonymous variables are no longer stored

---

Orange/data/domain.py
Orange/data/instance.py
Orange/data/table.py
Orange/data/variable.py
Orange/tests/test_domain.py
Orange/tests/test_table.py
requirements.txt
setup.py

This is done by changing isinstance(_, int) to
isinstance(_, numbers.Integral) where appropriate.
Also increase the required numpy version to 1.9.0 (numpy scalars are
registered with python's ABC system since v1.9.0)

Fix Table/Domain/Instance indexing with numpy.int* scalars.

---

Orange/data/table.py
Orange/tests/test_table.py

Add tests to ensure a table can be reconstructed from X, Y, metas and W
even when some have zero size.
Also remove one overzealous and confounding try except block.

Fix an error in from_numpy constructor when W has zero size.

---

scripts/windows/install-standalone.nsi

This properly enables current user installation scheme
as well as makes the GUI more standard and much prettier.

Use MultiUser.nsh and MUI2.nsh for the NSIS installer.

---

Orange/widgets/visualize/owboxplot.py

A quick fix. A fix would be to add legend to the widget.

Display value description in tooltip.

---

Orange/data/table.py
Orange/widgets/data/owtable.py
Orange/widgets/utils/itemmodels.py

This is to prevent the QTableView from querying the full model due to an integer overflow in the table row layout.
Also fix memory overhead when no sorting is applied.

Table widget row count limit

---

Orange/canvas/styles/orange.qss

Use the same background color for the tool box container widget
and the tool grid contained within. Otherwise if the tool grid does
not expand to fill the whole box the border of the tool grid becomes
visible.

Fix canvas tool box style.

---

Orange/widgets/visualize/owscatterplotgraph.py

The relative anchor positions (for the legend) are undefined when the
parent (view box) has an empty/zero size (which happens if the plot
was not yet displayed).

Fix a zero division error in scatter plot widget.

---

Orange/widgets/gui.py

Autocommit button is usually used for actions, that take a longer time. Setting the cursor to waiting informs the user that something is going on.

Change cursor to waiting during commit.

---

Orange/widgets/data/owtable.py

If array contains masked nans, missing value percentage would be shown
as higher than 100%.

Revert "Show correct percentage of missing values for masked arrays."

---

Orange/widgets/data/owpreprocess.py

Add a minimum width constraint to the instantiated preprocessors list view in order
to avoid a horizontal scroll bar.
Also add a keyboard shortcut for removing a preprocessor.

Preprocessor widget width

---

Orange/widgets/data/owimageviewer.py

This fixes an incorrect image layout which should fit in a single row
(but would always be broken in two).

Fix an off-by-one error in image viewer flow layout.

---

Orange/widgets/data/owdiscretize.py

Purge the restored variable states of Default discretization states
(use the current selected default instead). Before the GUI and the
actual discretization settings would be left in an inconsistent state.

Fix restore from context settings in Discretize widget.

---

Orange/widgets/evaluate/owtestlearners.py

When deleting input to TestLearnes widget the following error was triggered:
`AttributeError: 'NoneType' object has no attribute 'domain'` in line 156 since there is a call to `self.openContext(data.domain.class_var)`. I added the check so this is only done when we set the data and not also when we remove it.

Fixed error when removing data for TestLeaners.

---

Orange/widgets/classify/owclassificationtreegraph.py

When one of the lines in a node's text is significantly longer and
the node has a fixed (smaller) width, the shorter lines are also cliped
even though there is ample space to display them.

Left align text in a node.

---

Orange/data/domain.py
Orange/widgets/data/owdiscretize.py

The discretizer failed since has_discrete_class returned None, not False. disc_var should also work when source is None.

has_discrete_class always returns a boolean, discretize handles None class.

---

Orange/widgets/unsupervised/owmds.py

Use `from_table` constructor which preserves `ids` of the source table.

Preserve data row ids in the MDS output.

---

Orange/widgets/visualize/owboxplot.py

Allow the box plot median/mean labels in 'Compare medians/means' mode.
General code cleanup.
Clear the test report text below the plot when none is available.

Box plot fixes

---

.coveragerc

None of the tests we run on travis are for canvas/widgets.

Do not check coverage on canvas/widgets.

---

.travis.yml
Orange/tests/sql/test_naive_bayes_sql.py
travis/install.sh
travis/install_postgres.sh

This travis configuration is based on #503. I have moved PostgreSQL related installation code to a separate script, which builds and installs PostgreSQL and both extensions we use.
First Travis run that builds Postgres takes about 8 minutes. Subsequent runs finish in about 2.5 minutes, which is much better than the current 4.5 minutes per run.

Enable container-based builds on Travis.

---

doc/modules/regression.rst

Models are not documented for other learners
and not accessible from top level modeules (Orange.regression).

Remove MeanModel autoclass from documentation.

---

Orange/canvas/application/addons.py
Orange/canvas/document/interactions.py

On Windows and Linux all windows get a default window title (executable
name - in our case 'python') unless specified otherwise.

Set a non empty window title on all dialogs.

---

Orange/widgets/evaluate/owconfusionmatrix.py
Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/unsupervised/owkmeans.py
Orange/widgets/visualize/owheatmap.py

Fix an 'QObject::startTimer: QTimer can only be used with threads
started with QThread' warning on program exit, and the model outlives the
QApplication instance.

Parent the QStandardItemModel to the widget so it is destroyed with it.

---

Orange/datasets/datasets.info
Orange/datasets/list_update.py

Otherwise, features with same names that are present in different
datasets contain merged values, resulting in wrong count.

Clear variable cache when generating datasets.info.

---

Orange/canvas/scheme/widgetsscheme.py
Orange/widgets/settings.py
Orange/widgets/tests/test_settings_handler.py

* Fix erroneous initial widget geometry due to shared OWWidget.savedWidgetGeometry setting.
* Store/retrieve the settings from the widget when removing from the workflow (ensures that settings
are restored between undo/redo operations.

Widget settings fix

---

Orange/widgets/classify/owclassificationtree.py
Orange/widgets/classify/owknn.py
Orange/widgets/classify/owloadclassifier.py
Orange/widgets/classify/owlogisticregression.py
Orange/widgets/classify/owmajority.py
Orange/widgets/classify/ownaivebayes.py
Orange/widgets/classify/owrandomforest.py
Orange/widgets/classify/owsaveclassifier.py
Orange/widgets/classify/owsvmclassification.py
Orange/widgets/data/owconcatenate.py
Orange/widgets/data/owcontinuize.py
Orange/widgets/data/owpreprocess.py
Orange/widgets/data/owpurgedomain.py
Orange/widgets/data/owsave.py
Orange/widgets/data/owsql.py
Orange/widgets/evaluate/owpredictions.py
Orange/widgets/gui.py
Orange/widgets/regression/owmean.py
Orange/widgets/regression/owsgdregression.py
Orange/widgets/regression/owsvmregression.py
Orange/widgets/widget.py

Make widgets which do not have expanding GUI non-resizable.
This is done by using (existing) ``OWWidget.resizing_enabled`` widget class member flag.
Also improve Preprocess widget's size hints and fix a bug in ``gui.lineEdit``

Widgets size constraint

---

Orange/canvas/application/canvasmain.py

If the settings were already reset, the dir was deleted
and creating DELETE_ON_START file failed.

Make sure the settings dir exists before settings reset.

---

Orange/widgets/data/owpreprocess.py

Call apply and send outputs after _initialize().
Loaded settings were not applied if the widget had no inputs.
E.g. loading a saved schema did not send preprocessor outputs.

Fix preprocessor output (not working after inital load)

---

Orange/canvas/help/manager.py
Orange/canvas/help/provider.py
Orange/widgets/__init__.py
doc/conf.py
doc/index.rst
requirements.txt
setup.py

@markotoplak @BlazZupan
The most straightforward tool for building documentation from markdown `mkdocs` unfortunately does not build it in a way suitable for local viewing/browsing (i.e. it builds the htmldir style directory structure and all the links in it point to 'something/' directory listing instead of the actual html file, making navigation extremely frustrating).
I think the best solution would be to incorporate the .md documentation in the existing sphinx build, which is (will be) easy but requires ~~an unreleased development version of sphinx 1.4a~~  sphinx 1.3 and recommonmark

Build and provide help for widgets from the markdown files.

---

Orange/data/instance.py
Orange/data/table.py
Orange/tests/test_instance.py

Currently only RowInstance supports ids, but there is no reason that
Instance should not have it as well.

Add instance id to Instance.

---

Orange/widgets/unsupervised/owmds.py

The MDS plot should preserve the axis range on color, shape, size, ...
change. The autoRange should only be called when the mds embedding
coordinates change.

Only call autoRange at the most opportune time.

---

Orange/preprocess/discretize.py
travis/install_postgres.sh

The function it provided (bin) is now available in core PostgreSQL (as width_bucket).

Remove dependency on custom SQL extension "binning"

---

Orange/distance/__init__.py
Orange/tests/test_distances.py

The method used to remove one dimension from table.X if there was only one feature left in the table.
Beside that, the method used to replace class_vars with class_var which resulted in incorrect domain for multiclass datasets.

Distances: Fix _preprocess()

---

Orange/widgets/unsupervised/owmds.py

Widget crashes when passed data with only one continuous attribute. In that case size of distance matrix is 1x1.

OWMds: Draw a point when distance matrix is 1x1

---

Orange/widgets/utils/scaling.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owscatterplotgraph.py

Incorrect mask computation crashed class density visualization
(and probably introduced other bugs).

Scatter Plot: fix filtering of points with missing values

---

Orange/widgets/visualize/owdistributions.py

I have chosen average shifted histograms (with a gaussian kernel) as the only visualization for continuous attributes, because it returns similar results as gaussian KDE estimation from scikits but it was much (more that 10x) faster.
All visualizations are changed.
I have not implemented class probabilities yet.

Simplified the distributions widget

---

Orange/widgets/visualize/owsieve.py

When dataset with only continuous features was passes to
owsieve (after some other dataset) it crashed with key error
since `self.attrX` and `self.attrY` was not properly cleaned.
Also, since `self.warning` redraws the graph, `self.initCombos`
should be called before `self.warning`.

owseive: Fixed key error for continuous datasets

---

Orange/widgets/data/owrank.py

When the new data is set into Rank widget it did not send the data
to output until something was changed in the control area. This change
auto selects attributes (unless for Manual) and sends this to output.

owrank: Select and send attributes after setData

---

Orange/widgets/visualize/owscatterplotgraph.py

When no data is present in the Scatterplot, clicking on Zoom/Select caused an error.
`getViewBox()` now works with `plot_widget` instead of `scatterplot_item`.

owscatterplotgraph: Zoom/Select error without data

---

Orange/widgets/visualize/owscatterplotgraph.py

When unselecting the data by mouse click the points were unselected on the plot but the empty selection was not sent to the output. The `unselect_all` now also calls `self.master.selection_changed()` to propagate empty selection to output.

owscatterplotgraph: Unselect by click fixed

---

Orange/data/table.py
Orange/tests/test_table.py

When a dataset with non matching domain was passed in extends, the last
inserted row was overwritten with the id of the last instance.

Table: Fix extends method

---

Orange/widgets/unsupervised/owdistancemap.py
Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/visualize/owheatmap.py

* Fix an graphics error where the selection rectangle[s] would go out of sync with the underlying
heatmap images on annotation visibility change
* Allow row selection by clicking on the dendrogram.

Heatmap selections

---

Orange/canvas/application/canvasmain.py

Setting both the `checkable` and `checked` properties by constructor
keyword arguments (a PyQt feature) does not work reliably (depends on
the dictionary traversal order - i.e. the checked property is
unsuccessfully set before the action is made checkable).

CanvasMainWindow: Fix initialization of QAction

---

Orange/widgets/gui.py

Some styles render the items differently depending on the passed widget
instance.

gui: Improve ItemDelegates native styling

---

Orange/widgets/visualize/owscatterplotgraph.py

When computing the size/shape data use the 'valid_data' mask to filter
out points with invalid x, y coordinates.

OWScatterPlotGraph: Fix compute_sizes/symbols

---

Orange/widgets/data/owselectcolumns.py

With this we match the notation in Data Table widget, where "target variable" is used. Class in some way implies that this feature is discrete, not continuous, and hence we (Janez and myself) voted for renaming.

owselectcolumns: renamed Class to Target Variable in GUI

---

Orange/preprocess/discretize.py

Rstriping was intended for numbers like 4.0, but it also stripped the right zero from 60 (changing it into 6).

Fix rstripped 0 in number of decimals

---

Orange/canvas/application/outputview.py

The canvas workflow model/executor requires that model
changes and notifications do not yield control to the event loop.
However they use Python's logging extensively. This would not be a
problem unless the logger for the root or Orange.canvas namespace is
reconfigured to write to the OutputView's "redirected" sys.stdout/err.

OutputView: Do not yield control to the event loop

---

Orange/data/sql/table.py
Orange/data/table.py
Orange/statistics/contingency.py
Orange/tests/test_contingency.py

Therefore owdistributions does not crash anymore. Sparse tables with
unknown values of row variable (usually class) are still not supported.
The implementations could probably be faster but we would need
to modify bottleneck for it.

Contingency for ordinary tables with unknowns

---

Orange/tests/test_util.py
Orange/util.py

Orange.util: @abstract decorator handles non-method descriptors also

---

Orange/widgets/visualize/_grid_knn.cpp

Add constructors for point struct.
Add a stub python extension module definition (PyInit_ModuleName symbol
needs to be defined because it is explicitly exported by distuils's MSVC
compiler/linker invocation).

grid_knn: Fix for compiling with MSVC 2010

---

Orange/tests/__init__.py
Orange/widgets/data/owimpute.py

Fixing the problem mentioned in #495 based on fix suggestion by @ales-erjavec.
Does not fix the problem of missing compute_value on imputed variables.

owimpute: Create copy of table before imputation

---

Orange/widgets/visualize/owboxplot.py

If not all classes from domain were passed in the input dataset, boxes had incorrect labels.

OWBoxPlot: Connect boxex with correct labels

---

Orange/widgets/visualize/owmosaic.py

Remove Class distribution option from Color comboBox, when dataset has no class variable.

OWMosaicDisplay: Remove Class dist if no class_var

---

Orange/widgets/evaluate/owconfusionmatrix.py

Some improvements applied to #638 
The fixed ResizeToContents column width is better for smaller matrices, but for many columns and/or long header names it is awkward to _see_ the matrix structure (e.g. the diagonal is not straight). And the columns can't be resized by the user...
This changes the presentation for big matrices as explained in the commit message.
(compare on primary-tumor or audiology datasets to see the difference)

Confusion matrix: Cell width adjustments (2)

---

Orange/widgets/unsupervised/owmds.py

Temporarily disable drawing similar pairs, until the procedure is sped up.

OWMds: Remove similar pairs

---

Orange/widgets/visualize/owscatterplot.py

In order to choose color by variable, that used to be a class variable, but was moved to meta attributes (e.g. through clustering algorithm), all primitive metas were moved to table.X before passed to ScatterplotGraph.

OWScatterplot: Add metas to comboBoxes

---

Orange/canvas/application/addons.py

They should be shown even when pypi is misbehaving (like now).

addons: Hardcode official add-ons.

---

Orange/widgets/regression/owsvmregression.py

This name is now also consistent with the name used in the widget documentation.

owsvmregression: renamed widget to SVM regression

---

Orange/evaluation/testing.py
Orange/tests/test_evaluation_testing.py
Orange/widgets/evaluate/owtestlearners.py

Preprocessing was incorrectly applied to all data, including testing.
I added argument preprocessor to CrossValidation, LeaveOneOut and other functions.
I also had to change the way the widget works: if it tested each learner separately (by calling, e.g., CrossValidation), also preprocessing would be applied for each learner separately. The widget now calls CrossValidation with a list of learners.
As a consequence, the otherwise brilliant loops had to be removed since it now all happens with CrossValidation.
Progress bar is now finer - instead of reporting the number of learners tested it reports learners*folds.
@ales-erjavec Should we move Try to some utils library? It's great. I also liked the class for the loop in Test Learners. It cannot be used in the new code, but I guess we should …

Fix Test & Score: preprocessing, progress bar

---

Orange/widgets/widget.py

Restore the widget geometry only on first show event. This should fix a problem on windows where restoring a widget from a minimized state would resize it to a less then perfect shape.

OWWidget geometry restore fix

---

Orange/widgets/visualize/owscatterplot.py

VizRank sorted attributes by ReliefF and then by their instance (Variable). These are not orderable, e.g.
File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Orange/widgets/visualize/owscatterplot.py", line 558, in score_heuristic
self.parent_widget.data.domain.attributes))
TypeError: unorderable types: ContinuousVariable() < ContinuousVariable()
I changed this to sort by names, assuming that no two variables have the same name (if they do, sorting is ambiguous but so is any other operation on such data). This is better than using id's because the widget later constructs a list of names anyway. The fix thus does not impose any memory or time overhead.

VizRank: Fix sorting of candidate pairs

---

Orange/widgets/visualize/owscatterplotgraph.py

Selection markers in the scatter plot were ugly. I changed the z-order, putting the markers behind the items they mark.

Scatterplotgraph: Put selection markers behind the items

---

Orange/canvas/application/addons.py

Add Orange3-Network to the list of add-ons that are shown in the add-ons dialog, even if pypi does not return them.
This list will not be needed once
https://bitbucket.org/pypa/pypi/issues/325/searching-by-keywords-stopped-working
is resolved.

official addons: Add Orange3-Network

---

Orange/preprocess/score.py

When the data domain is not fully represented (i.e. no appearances of some value of Discrete attribute), there are zero columns in contingency array. These columns are now removed to be able to devide by np.sum(D, axis=0) when calculating entropy.

Score: Remove zero columns

---

Orange/widgets/visualize/owvenndiagram.py

Selection with keys Shift, Ctrl and Alt is now consistent to selection in OWScatterPlot

OWVennDiagram: Selection

---

Orange/widgets/unsupervised/owkmeans.py

There was a call self.send("Data", None) instead of self.send("Annotated Data", None)

k-Means widget: Fix the signal name in send

---

Orange/widgets/data/owselectcolumns.py

Has only limited support for editing the class_vars (can only move them out
of class_vars).
Fixes gh-706

owselectcolumns: Support multiple class_vars on input

---

Orange/widgets/evaluate/owtestlearners.py

The widget should not eagerly run of and start a long computation on any change especially if setting up the parameters can be a multi step interaction.
Confounded by reentry from the event loop (by means of qApp.processEvents()). This does not completely solve that problem.

Test learners: reintroduce 'Apply' button

---

Orange/widgets/unsupervised/owhierarchicalclustering.py

Selection with keys Shift, Ctrl and Alt is now consistent to selection in OWScatterPlot.

OWHierarchicalClustering: Selection

---

Orange/tests/__init__.py
Orange/tests/test_widgets_outputs.py
Orange/widgets/tests/test_widgets_outputs.py

A tests that parses all widget files for `self.send("<signal name>"` and checks whether the <signal name> is defined as an output.
The test uses regular expression which requires that this is the first non-white thing in the line; this excludes sends that are commented out. There may be false positives (e.g. commented within triple quotes) or false negatives (if sends are written in a more contrived way). The former are easy to fix and the latter do not and should not appear. The test is thus sufficient.
The test takes some time since it requires the widget registry to scan for all widget files (and even import them, if run on Travis).

Add tests for declarations of widget outputs

---

Orange/evaluation/testing.py
Orange/tests/test_evaluation_testing.py
Orange/widgets/evaluate/owtestlearners.py

ShuffleSplit replaces Bootstrap, because Bootstrap will be removed in 0.17 version of Scikit-learn.

Testing: ShuffleSplit replaces Bootstrap

---

Orange/widgets/visualize/owmosaic.py

Mosaic Display crashed occasionally when changing the input data.
Resetting the information dialog in setData causes a redraw. This happened
after changing the data and before updating the combo boxes, which led to
a crash because of inconsistent attributes and data.

Mosaic: Fix a minor bug

---

Orange/widgets/classify/owclassificationtreegraph.py
Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/data/owimageviewer.py
Orange/widgets/data/owimpute.py
Orange/widgets/data/owselectrows.py
Orange/widgets/evaluate/owcalibrationplot.py
Orange/widgets/evaluate/owliftcurve.py
Orange/widgets/evaluate/owrocanalysis.py
Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/gui.py
Orange/widgets/regression/owunivariateregression.py
Orange/widgets/unsupervised/owdistancemap.py
Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/unsupervised/owmds.py
Orange/widgets/visualize/owdistributions.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/owscattermap.py
Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/owvenndiagram.py

Add a maximumContentsLenghtHint parameter to prevent the combo box from
growing uncontrollably depending on its contents.

gui.comboBox: Limit the combo box width

---

Orange/canvas/scheme/widgetsscheme.py

... allowing the widget to be garbage collected as soon as possible.

WidgetManager: Delete a no longer necessary widget reference

---

Orange/canvas/scheme/widgetsscheme.py

Do not block signal delivery to dependent widgets between calls to
OWWidget.progressBarInit/Finish

SignalManager: Fix canvas signal propagation

---

Orange/widgets/data/owpaintdata.py

Add a field to name the painted dataset to distinguish between them in the Hub widget.

PaintData: Add Table name.

---

scripts/create-dmg-installer.sh

SetFile executable should always be on PATH (in /usr/bin/).

create-dmg-installer: Remove absolute path to SetFile executable

---

Orange/widgets/visualize/owheatmap.py

Ocassionaly some old artefacts remain on the plot after the image updated; e.g. when turning on the row annotations the end of the previous scale could be seen in the top right corner. This PR clears these problems.

heatmap: clear redraw artefacts

---

Orange/widgets/evaluate/owconfusionmatrix.py
Orange/widgets/gui.py

I didn't like the positions of labels "Actual" and "Predicted".
- I still need to replace grid view in main area with something simpler
- VerticalLabel class is useful and has to be saved somewhere
- Widget may needs some additional cleanup and testing after this change

Confusion matrix: Make it nicer

---

Orange/widgets/visualize/owscatterplot.py

Provide an explicit domain instead of allowing it to be guessed from
data (the rules for that changed, and might again someday).

owscatterplot: Fix temporary Table creation

---

Orange/canvas/help/provider.py

`strict` has been deprecated since Python 3.3 and removed in 3.5
https://docs.python.org/3.4/library/html.parser.html

provider: Remove non-existent argument (Py3.5)

---

Orange/widgets/gui.py

In the horizontal layout, the should be some space between the checkbox label and the button.
The problem becomes apparent if another button is added to box created by `gui.auto_commit`, like in https://github.com/biolab/orange3/commit/ea37c2f1cbf5aed84588b0caf2007ee07758de32#diff-a2cbec3457e61cdb3228e0e4b7b95585R227.

gui.auto_commit: Add spacing between label and button

---

Orange/widgets/visualize/owboxplot.py

Minimal working example. The method of display is imperfect
in that:
* it shows the same labels multiple times when the variable
is grouped by another variable,
* one variable's label may occlude another when the
former value's count is low (relative to label length).

Boxplot: plot discrete variables' labels (legend)

---

Orange/data/io.py
Orange/data/variable.py
Orange/tests/test_tab_reader.py
Orange/tests/weird.tab

If the first three lines of a dataset match the three-line header
format => it's a three-line header (regardless of the column names
used in the first line).
Otherwise, if the first and second line don't have all-digits in
exactly the same places and not-all-digits everywhere else => it's
a single-line header.
Otherwise, no header.
Also, (@BlazZupan) string variables are considered discrete only if at most `int(round(len(values)**.7))` values, so for 5 instances, there can be at most 3 distinct values for the variable to be considered discrete, and for 100, 25.

io: New heuristic for discerning headers from data

---

Orange/data/io.py

@lanzagar Please review as you're still familiar with it. This is simpler and less error-prone assuming technical people don't normally use sole numbers as identifier names.

io: Single-line header only if none of the 1st line values is a number

---

Orange/data/io.py

This is (probably) what 0aeda0934ab19f290580e35b576cef9ca8b82d53 should be.

io: Fall back to UTF-8 if everything else fails

---

Orange/preprocess/remove.py
Orange/tests/test9.tab
Orange/tests/test_remove.py
Orange/widgets/data/owselectrows.py

Before, remove.py handled only attributes and classes. The only strange piece of code is line 273, `column = np.array(column, dtype=np.float64)`, which I had to add since for meta attributes the column values were of type float, and this caused problems for `np.isnan()`.

remove.py: purge domain now handles meta attributes

---

Orange/canvas/__main__.py
Orange/canvas/application/welcomedialog.py

The two links are:
* http://orange.biolab.si/short-survey.html should redirect to short survey shown when Orange is first run;
* http://orange.biolab.si/long-survey.html should redirect to longer feedback form.
@markotoplak and @ajdapretnar are on it.

Popup short survey and show feedback link on the Welcome screen

---

Orange/widgets/visualize/owheatmap.py

* Add an option to merge/compress heatmap rows with k-means.
* Also remove the GUI for split label selection. It was undocumented/unused but used quite a
lot of vertical space.

Heatmap: Merge/compress rows by k-means

---

Orange/widgets/visualize/owheatmap.py

By default, use extremes from the color gradient instead of white/black.

owheatmap: Change the default under/overflow colors

---

Orange/data/io.py
Orange/tests/test_tab_reader.py

JSON doesn't support single-quote-quoted strings. So were working with Python object dumps now
> a=b c=['d', 3] e={True: False}
Is this an issue?

io: load var attributes as python objects (like JSON except not)

---

Orange/widgets/classify/owclassificationtree.py

Do not use split stopping parameters when disabled by the user.

owclassificationtree: Fix learner initialization

---

Orange/widgets/classify/owclassificationtreegraph.py

The inplace divide would change the internal scikit-learn's node
distribution array.

owclassificationtreegraph: Dot not write over sklearn internal array

---

Orange/widgets/data/owfile.py

Orange 2 used to detect when a file in .tab format had extension .txt and vice versa. Orange 3 does not, so this commit removes the corresponding code in the widget.

OWFile: Remove handling of case when .tab is loaded as .txt

---

Orange/widgets/data/owdatasampler.py

When selecting to download data after sampling do it explicitly, without limitations of the automatic download.

owdatasampler: When selected, download data without a limit

---

Orange/widgets/unsupervised/owpca.py

1) Adds option to normalize data
2) Downloads small SqlTables (incremental learning not sensible), and samples when remote execution not supported
Last commit disables normalization for SqlTables (currently broken) and should be reverted when it is implemented correctly.

owpca: Improvements (normalization option, sql inputs)

---

Orange/classification/svm.py
Orange/regression/linear.py

OWSVMClassification crashed OWSVMClassifier crashed when used on data subset that does not contain all class values included in data domain.
To reproduce the error use OWFile(Iris) + OWDataTable (select subset with only two class values) + OWSVMClassifier + OWPrediction
Flag was removed from LinearModel as well because Orange does not support multiclass learning anyway.

SVM, Linear: Do not override support_multiclass flag

---

Orange/classification/logistic_regression.py
Orange/classification/random_forest.py
Orange/preprocess/score.py
Orange/regression/linear.py
Orange/regression/random_forest.py
Orange/tests/test_linear_regression.py
Orange/tests/test_logistic_regression.py
Orange/tests/test_random_forest.py
Orange/widgets/classify/owrandomforest.py
Orange/widgets/data/owrank.py
Orange/widgets/regression/owlinearregression.py

OWRnk can now get signals from OWLinearRegression and OWRandomForest.
Therefore Liner regression learner and Random forest learner extend Scorer, which is additional input to OWRank.
When attribute is continuized, an average of related scores in given.

OWRank: Get scores from linear regression and random forest

---

Orange/widgets/data/owfile.py

Do not re-enter the event loop from within widget's `__init__`.

owfile: Fix widget initialization

---

Orange/widgets/gui.py

Fixes a todo related to GEO Browser (ID 145) where it was very hard to read the ID (blue on blue) in the line of a selected data set.

gui: Render text of selected link as other highlighted text

---

Orange/widgets/visualize/owdistributions.py

Fixes todo 41: Distributions, the title of the graph (attribute name, at the very bottom) is aligned only after resize. This bug appears when attribute names have really long names.

owdistributions: Align axis labels at text change

---

Orange/regression/linear.py
Orange/tests/test_linear_regression.py
Orange/tests/test_regression.py
Orange/widgets/regression/owlinearregression.py

I added properties `intercept` and `coefficients` to `LinearModel`.
All linear regression fitters are now derived from `LinearRegressionModel`; the models are thus wrapped into `LinearModel` (they were not before).

Output coefficients from Linear regression widget

---

Orange/widgets/visualize/owscatterplot.py

Use RReliefF instead of ReliefF for regression datasets. 
I'm not sure whether this is the right solution or should I just disable rank projection for regression datasets.

OWScatterplot: Rank projection fix

---

Orange/widgets/data/owpreprocess.py

This fixes a spurious error due to the model being in an inconsistent state when the
preprocesors were being drag/dropped.

Preprocess widget: Improve/fix preprocessor model reordering

---

Orange/widgets/gui.py

If lineEdit and some other default push button are on the same page, pressing Enter after typing into lineEdit activated the default push button as well.

gui.lineEdit: commit button should accept default action

---

Orange/classification/base_classification.py
Orange/data/domain.py
Orange/regression/base_regression.py
Orange/tests/test_classification.py
Orange/tests/test_regression.py

Learner widgets used to crash when given multiclass datasets.
Widgets should show error message instead.

Learner: Handle multiclass datasets

---

Orange/regression/linear.py
Orange/tests/test_linear_regression.py

Any parameters passed to LassoRegressionLearner and RidgeRegressionLearner were ignored with introduction of LinearModel. Now fixed. Noticed it while running Linear Regression widget, where change of alpha did not change Coefficients nor the Model.

linear: fixed parameter handling to linear regression learner

---

Orange/widgets/data/owtable.py

Replace a `O((R*C)^2)` with a `O(R*C)` procedure (where R and C
are selected row and column counts).

owtable: Optimize table selection restore

---

Orange/widgets/data/owfeatureconstructor.py

* Remove GUI controls for setting the number of decimals, base value, ...
* Replace the QListView controls for editing discrete variable's values
with a QLineEdit (values are comma separated, escaped with '\' if necessary.
* Move the QListView with defined variables below the 'Editor'.

Simplify 'Feature Constuctor' widget GUI

---

Orange/canvas/preview/scanner.py

canvas/preview: Do not render link names in preview thumbnails

---

Orange/widgets/data/owfile.py

Before two recent items would compare equally if they both had
`prefix is None` and `relpath is None`. As a consequence, the recent
items list would only ever contain one item which is not stored relative
to some known prefix.

owfile: Fix RecentPath's equality test

---

Orange/evaluation/scoring.py
Orange/tests/test_evaluation_scoring.py

Add argument, since its default value is deprecated and removed in Sklearn 0.18.

Scoring: Add average kwarg to Precision and Recall

---

Orange/data/table.py
Orange/widgets/regression/owlinearregression.py

For unnamed data in the input of OWDataTable (e.g. coefficients) the tab had no name. 
Now the name is set to 'untitled' by default and renamed if possible (e.g. coefficients in OWLinearRegression).

OWLinearRegression: Set coefficient table name to 'coefficients'

---

Orange/widgets/classify/owclassificationtree.py
Orange/widgets/classify/owknn.py
Orange/widgets/classify/owlogisticregression.py
Orange/widgets/classify/owmajority.py
Orange/widgets/classify/ownaivebayes.py
Orange/widgets/classify/owrandomforest.py
Orange/widgets/classify/owsvmclassification.py
Orange/widgets/regression/owknnregression.py
Orange/widgets/regression/owlinearregression.py
Orange/widgets/regression/owmean.py
Orange/widgets/regression/owsgdregression.py
Orange/widgets/regression/owsvmregression.py
Orange/widgets/regression/owunivariateregression.py
Orange/widgets/utils/owlearnerwidget.py

Apply user-provided preprocessors first, but always apply learner-dependent default ones afterwards so that algos just work™.
Requires default preprocessors to be idempotent, which `SklLearner.preprocessors` are.
@lanzagar, @VesnaT, @BlazZupan might want to review this?

Unite preprocessor handling in Learner-outputting widgets

---

Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/visualize/owheatmap.py

Change where tree's leaf nodes are anchored. Before the left/rightmost
leafs would coincide exactly with the widgets's contentsRect().left/right
(or top/bottom). Now the anchors are placed more naturally in the center
of N subdivisions of the contents width/height.
This simplifies the client code, which before had to set/match the contents
rect in order to ensure proper visual alignment with side by side
dendrogram, labels, images, ...

DendrogramWidget: Change the dendrogram widget's layout

---

setup.py

`docutils` was missing as a requirement and consequently in the bundle on our website. This caused the description of add-ons not to be properly formatted.

setup.py: added docutils as a requirement

---

Orange/widgets/data/owselectcolumns.py

Widgets with Apply button usually don't output anything before the apply button is clicked. Although this is the norm, in this particular widget, this behaviour is unexpected (I was confused yesterday by it, and I though we had a bug...).
Typically, application of settings takes time (e.g. for building the model), which is why the settings are not applied immediately. This case is different: the application is free, but the user performs multiple actions in a row and we don't won't to commit all, due to further widgets. But the first application should happen immediately.

Select columns: unconditionally commit new data

---

Orange/widgets/data/owcolor.py

Color widget failed to update when it received new data because the model did not emit the necessary signals.

Color: Fix model reset

---

Orange/canvas/application/canvasmain.py
Orange/canvas/scheme/readwrite.py

Revert changes to `parse_ows_stream` introduced in 6182d62cdbf701739315a5d06f666adb11a551db.
If the `stream` parameter is a string it should be interpreted as a filename path (as `ElementTree.parse` does).
This fixes workflow preview rendering (which uses `parse_ows_stream`)

canvas/readwrite: Fix `parse_ows_stream`

---

Orange/classification/naive_bayes.py
Orange/preprocess/discretize.py
Orange/tests/test_clustering_kmeans.py
Orange/tests/test_distances.py
Orange/tests/test_domain.py
Orange/tests/test_pca.py
Orange/tests/test_softmax_regression.py
Orange/widgets/utils/colorpalette.py

Various fixes of test errors and warnings:
* test_kmeans_parameters (RuntimeWarning: Mean of empty slice.)
* Reduce the number of clusters.
* GradientPaletteGeneratorTest (RuntimeWarning: invalid value encountered in rint)
* Avoid NaNs by temporarily settings them to 0.
* test_all_models_work_after_unpickling (ERROR: pickling a NaiveBayes model crashed)
* Convert class_freq to numpy array.
* TestDiscretizer (ERROR: np.digitize doesn't accept empty lists of cut points anymore)
* Wrap np.digitize (changed in numpy 1.10) for use in Discretizer.transform
* TestDomainInit (FutureWarning: numpy equal will not check object identity in the future.)
* Avoid array comparisson with NaNs.
* test_SoftmaxRegressionPreprocessors (RuntimeWarning: invalid value encountered in multiply)
* Reduce the values …

Compatibility with newest Numpy and Scipy.

---

Orange/widgets/data/owpaintdata.py

Say that the user paints some data with a single class only. The widget still outputs the class column, with all instances belonging to this class. To remove this column from the output, the user must delete the second class from the listbox in the control area.
I changed this so that the widget checks whether two classes are actually present in the data. This is more convenient for the user.
The drawback is that the user now cannot paint a data with a single class but still have the class column. This scenario is very unlikely, though, and I think it's better cover the common scenario.

Paint data: Do not output class column if only a single class is present

---

Orange/widgets/classify/owknn.py
Orange/widgets/classify/owlogisticregression.py
Orange/widgets/classify/owmajority.py
Orange/widgets/classify/ownaivebayes.py
Orange/widgets/regression/owknnregression.py
Orange/widgets/regression/owmean.py

Report button was under Apply, but slightly wider.
Blocked by #951: before merging, check whether #951 solves the problem. In this case, we keep only the changes where Report is put beside Apply since the widget is wide enough for that.

Classification and regression widgets: Put Report button at better position

---

Orange/widgets/classify/owsvmclassification.py
Orange/widgets/regression/owsvmregression.py

The layout of the SVM widget has always been terrible.
- The two widgets now use common code for initialization.
- Instead of giving formulae at each radio button, only the formula for the chosen kernel is shown
- Parameters are on the right, below the formula and they are shown/hidden according to the chosen kernel type
- I also changed the default value of `g` to something sensible (1) and the steps in spinboxes to 0.1.
- Other minor adjustments to the layout (Report button etc)
Before:
After:

Improve layout of SVM widgets

---

Orange/widgets/unsupervised/owhierarchicalclustering.py

Increase spacing between dendrogram and the item 'annotations' column.

owhierarchicalclustering: Fix layout spacing

---

Orange/widgets/visualize/owdistributions.py

Task no231. @BlazZupan Check if this is what you had in mind. Legend now takes argument from overall color palette, but we might want to separate args for legend and plot.

Distributions: both plot and legend colors made bolder.

---

Orange/data/sql/table.py
Orange/tests/sql/test_sql_table.py
Orange/widgets/data/owtable.py
Orange/widgets/utils/itemmodels.py

Fixes bug where Data Table widget crashed with IndexError when trying to display nonexistent rows (expected because of approximate size)
Various improvements described in individual commits.

SqlTable: Improved approx_len handling in Data Table

---

Orange/widgets/classify/owloadclassifier.py
Orange/widgets/classify/owsaveclassifier.py

Fixes:
http://stackoverflow.com/questions/34489451/orange3-save-classifier-widget

OWSaveClassifier: append .pickle extension if not already provided

---

Orange/canvas/application/addons.py

canvas/addons: Fix an error when PyPi package meta data is empty

---

Orange/classification/simple_tree.py
Orange/widgets/utils/classdensity.py

In Python 3.5 windows extension modules (.pyd) are ABI tagged, but
`sysconfig.get_config_var("EXT_SUFFIX"), contains the untaged suffix.
Import the actual stub modules and use the module's `__file__`
attribute to locate the library.

extensions: Change how ctypes 'extensions' are located/loaded

---

travis/install.sh

Orange3-requirements are only used for scipy, everything else can be installed on travis, and cached using provided caching mechanisms.
After this pull request is merged, travis caches should be deleted and rebuilt.

travis: Use master branch of orange-requirements.

---

travis/install_postgres.sh

Since Postgres 9.5.0 has been released, travis can use that instead of the alpha version.

travis: Use Postgres 9.5.0

---

Orange/canvas/application/canvasmain.py

Don't know if anyone else experienced it, but I did and it is pretty obnoxious to have had to scroll hundreds of lines in the console whenever the "red window" gained or lost focus to see the just-appeared traceback again.
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::save: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::setRenderHint: Painter must be active to set rendering hints
QPainter::brush: Painter not active
QPainter::setBrush: Painter not active
QPainter::pen: Painter not active
QPainter::pen: Painter not active
QPainter::setPen: Painter not active
...
(600 more lines)
Unsure if the "solution" is right, but it does seem to work. …

canvas: add noop paintEvent() to DockableWindow => fix QPainter wall-of-text error

---

Orange/widgets/io.py

Some widgets (i.e. BoxPlot) resize sceneRect (usually make it smaller than itemsBoundingRect).
Therefore, when saving an image or showing it in report, an image with to much empty space is produced.

ImgFormat: Use sceneRect instead of itemsBoundingRect

---

Orange/widgets/visualize/owscatterplotgraph.py

Opacity was ignored when color "(Same color)" was selected.

OWScatterPlotGraph: Consider Opacity when (Same color) is selected

---

Orange/canvas/report/report.py
Orange/data/io.py
Orange/widgets/classify/owtreeviewer2d.py
Orange/widgets/data/owimageviewer.py
Orange/widgets/data/owpaintdata.py
Orange/widgets/data/owsave.py
Orange/widgets/evaluate/owcalibrationplot.py
Orange/widgets/evaluate/owliftcurve.py
Orange/widgets/evaluate/owrocanalysis.py
Orange/widgets/io.py
Orange/widgets/unsupervised/owcorrespondence.py
Orange/widgets/unsupervised/owdistancemap.py
Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/unsupervised/owmds.py
Orange/widgets/unsupervised/owpca.py
Orange/widgets/utils/filedialogs.py
Orange/widgets/utils/saveplot.py
Orange/widgets/visualize/owboxplot.py
Orange/widgets/visualize/owdistributions.py
Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/owscattermap.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/owvenndiagram.py
Orange/widgets/widget.py

Alternative to #940, w.r.t. auto save: the file name is here shown as button text. This design is cleaner than an extra label.
Abusing this widget for saving graphs was a bad idea and did not really work. When reused for this purpose the widget showed Save As button that doesn't make sense, the widget didn't close but remained as a modal dialog after saving.
Save graph button in all widgets now opens the standard dialog for saving files, without detour to the modal `OWSave` with format selection and two buttons with the same function. This works on Linux, too, since it uses `getSaveFilenameAndFilter` function.
- `want_graph` is replaced with `graph_name` that can contain the name of the attribute with the graph (e.g. `plot.plotItem`). This attribute is used for both, saving and reports.
- …

Add auto save to OWSave; Move saving of graphs to separate function

---

Orange/widgets/utils/colorpalette.py

Fix IndexErrors encountered when the color palettes were incorrectly
used with a large number of colors.
Add a `ColorPaletteGenerator.resolve` helper method to aid in more
robust/flexible palette use.

colorpalette: Fix use of ColorPaletteGenerator

---

Orange/data/io.py
Orange/data/table.py
Orange/data/variable.py
Orange/tests/test9.tab
Orange/tests/test_table.py
Orange/tests/test_variable.py
Orange/widgets/data/tests/test_owmergedata.py
Orange/widgets/tests/test_io.py
Orange/widgets/visualize/tests/test_owvenndiagram.py

IsDefined filtering did not work because String missing values were represented as np.nan.
Now String missing values are represented as None.

FilterString: Fix is_defined filtering

---

Orange/widgets/data/owoutliers.py

Gamma=0.0 will be removed in sklearn 0.18.

OWOutliers: Get rid of deprecation warning

---

Orange/data/domain.py
Orange/data/sql/table.py
Orange/projection/cur.py
Orange/tests/test_discretize.py
Orange/tests/test_tab_reader.py
Orange/tests/test_txt_reader.py
Orange/tests/test_xlsx_reader.py
Orange/widgets/visualize/owdistributions.py

When using positive indices, the result is the same, but indexing of
domain is shorter.

domain: Index domain instead of domain.variables

---

Orange/data/table.py
Orange/data/variable.py
Orange/tests/test_domain.py
Orange/tests/test_instance.py
Orange/tests/test_table.py

* Change `Value` constructor to better handle missing values for StringVariables
* Update the StringVariable.Unknown constant (now a `""`)
* Change tests which which assumed a single unknown value representation
* Fix `Value.__hash__` and `Value.__contains__`

Unknown str value fix

---

Orange/widgets/visualize/owdistributions.py

When discretizing an attribute with only one value, it was removed.

OWDistributions: Do not remove constant attribute

---

Orange/canvas/__init__.py

Old hack for python 3 seems not to work any more.
A hack seems not to work for `python 3.5` and orange-canvas fails to start (throws) when `pkg_resources.__init__.py` calls resource_exists with orange.qss when loader is commented out it all works

loader hack for python3

---

Orange/widgets/data/owfile.py

The existing layout is ugly (which is my fault, not @VesnaT or anybody else's).
- Editable combo box is not intuitive - will users really know they can type URLs and that they should not type file names?
- Button "..." applies just to file and not to URL
- Icons in front of files names look ugly.
- "Browse documentation data sets" is hidden, especially for fresh users
The new layout is nicer, more intuitive and also allows for future extensions with additional sources.
URL is refreshed on Return key, like in web browsers.
The button for documentation data sets does not take any extra space because we have the Report button anyway.

Changed layout of File widget

---

Orange/widgets/gui.py

Most calls of `gui.widgetBox` have argument `orientation="horizontal"` or `orientation="vertical"`, which is annoyingly long and uses strings instead of constants.
Functions `gui.verticalBox` and `gui.horizontalBox` call `gui.widgetBox` and supply the `orientation` argument.

gui.py: Add verticalBox, horizontalBox

---

Orange/distance/__init__.py
Orange/tests/test_distances.py
Orange/widgets/unsupervised/owdistances.py

Distances widget traditionally stripped discrete variables, requiring an additional Continuize step, which finally would make Distances favor fewer-valued features. Now, it counts distance between two values of a discrete variable as binary, either 1 (different) or 0 (same).

OWDistances, SklDistance: support discrete variables

---

Orange/widgets/gui.py

When a item/row in a view was selected the item's text background would
overlap (and paint over) the bar line.

TableBarItem: Fix overlaping bar line and text background

---

Orange/classification/base_classification.py
Orange/regression/base_regression.py
Orange/tests/dummy_learners.py
Orange/tests/test_classification.py

Fix `SklLearnerClassification` to use the correct default return model `SklModelClassification`.
Previously, this was not set, which meant the base class `SklModel` was used for classification and probability predictions were not expanded correctly for unseen classes.
Similar fix for regression, although the correct class does not do anything special there.
Replaces #1011.

SklLearner: Set correct __returns__ values for subclasses

---

Orange/widgets/data/owpreprocess.py

Fix an error where a wrong preprocessor would be created as a result of
a drag/drop.

owpreprocess: Use unique qualified names for PCA and CUR preprocessors

---

Orange/classification/random_forest.py

Brieman: "Each tree is grown to the largest extent possible. There is no pruning."
We should probably use that as default. It yields much better performance.
More info: http://stats.stackexchange.com/questions/36298/why-is-pruning-not-needed-for-random-forest-trees

RF without pruning by default

---

Orange/widgets/data/owfile.py
Orange/widgets/gui.py

URL Combo is again editable.
For Google sheets, the combo shows the last known sheet name for this URL (the underlying model maps the URL through dictionary of known names). In the line edit, the URL is shown as placeholder. The user is not expected to edit Google sheet URLs.
Other URLs are editable since they may be human friendly. Also, other URLs don't have any associated names so they're not mapped.
Alternative is that Google sheets get a separate radio button in which the user can either enter a new URL or select one from history. In this case, we could also show additional data, such as time stamps, last editors, previous versions... if available.

Change the URL line edit in the File widget back to combo box

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/owsieve.py

Sieve is ancient. It contains, for instance, its own simple implementation of context settings. So far, I:
- removed checkboxes that were never used,
- removed conditions combos haven't been used since Gregor defended his thesis,
- removed code for "optimization" that was never used, not ported to Orange 3 and commented out,
- reorganized controls to save space (the layout is non-standard now, but the control area would be almost empty),
- refactored controls to use models and context settings,
- properly implemented handling of input signal Features (other widgets should follow this model, IMHO; set the values in combos and disable them for as long as the signal is present and useful)
- let the user select areas; the widget outputs them without apply button, since this is more intuitive, …

Sieve enhancements

---

Orange/misc/distmatrix.py
Orange/tests/__init__.py
Orange/tests/test_distances.py
Orange/widgets/data/owfile.py
Orange/widgets/unsupervised/icons/DistanceFile.svg
Orange/widgets/unsupervised/icons/SaveDistances.svg
Orange/widgets/unsupervised/owdistancefile.py
Orange/widgets/unsupervised/owsavedistances.py
Orange/widgets/utils/filedialogs.py

The PR contains
- methods for loading and saving to `DistMatrix` from/to file
- the corresponding widgets
- some additional tests
- removal of `DistMatrix.get_KNN`
It also pulls the code for recent paths from the file widget into a separate module, so it can be reused in multiple widgets.
Widgets for file distances intentionally support just a single data format. Let's try to keep it simple this time.

Widgets for saving and loading distances

---

Orange/widgets/data/owcolor.py

This caused the generation of all continuous palettes, which was slow. Now only the discrete table is resized, while the continuous has a fixed width (which makes sense anyway)

Color: Do not resize columns in continuous table to contents (fixes #1055)

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/owsieve.py

Fixes bug introduced in the previous PR, pointed out by @lanzagar.  It was introduced when I was trying to iterate through both `data.domain` and `data.domain.metas` using `+` and a type mismatch occurred. `chain` does not have any such issues.

Fix for Mosaic and Sieve attributes

---

setup.py

This partially reverts commit 36f27c48c2c16a0c4da781e6ff01e1291bcc27db.

setup.py: Remove build date from the public version identifier

---

Orange/widgets/unsupervised/owdistancematrix.py

Error occured during closing unused DistanceMatrix widget.
Added context checker in settings_from_widget method.

DistanceMatrixContextHandler: error after closing DistanceMatrix

---

.travis.yml

The dist fails to download on the Travis worker far too often.

Travis: allow build failures for Python nightly

---

Orange/widgets/settings.py

A call to storeSpecificSettings should only be made when the widget has
an opened context.
Complements #1093

[FIX] ContextHandler: Fix settings_from_widget

---

.travis.yml
.travis/build_doc.sh
.travis/install.sh
.travis/install_postgres.sh
.travis/upload_doc.sh
MANIFEST.in
Orange/tests/__init__.py
README.md
requirements-dev.txt
scripts/build-osx-app.sh
scripts/windows/build-win-application.sh
setup.py

* Always use the same consistent `install_requires` (fixes a incomplete install using `pip install [-e]`; docutils and pyqtgraph would not get installed but still listed as requirements in the package metadata, causing pkg_resources to raise errors)
* Remove dependency on setuptools-git
* Rename gui_script entry point from "orange" to "orange-canvas".

Consistent install requirements

---

Orange/classification/logistic_regression.py
Orange/classification/random_forest.py
Orange/preprocess/score.py
Orange/projection/pca.py
Orange/regression/linear.py
Orange/regression/random_forest.py
Orange/tests/test_evaluation_scoring.py
Orange/tests/test_linear_regression.py
Orange/tests/test_logistic_regression.py

It used to have model as a parameter and now it gets the data directly.
This allows more freedom for individual learners to define how to score
variables.
E.g. Logistic regression and Linear regression models need to normalize
the data first, before the coefficient make sense.
Random forest on the other hand does not require normalization.

[WIP] LearnerScorer: Change signature of score method

---

scripts/windows/build-win-application.sh
scripts/windows/install-standalone.nsi
scripts/windows/install.nsi

Fix an installation error when running windows installers due to older installed pip (requires at least version >=6).

Windows installer: update pip on target system if required

---

Orange/widgets/settings.py
Orange/widgets/visualize/owscatterplot.py

Fixes a problem that can be reproduced by deleting scatter plot from the following schema:

[FIX] Settings: Warn when setting values are not present on instance

---

Orange/preprocess/score.py
Orange/widgets/data/owrank.py

- Add existing feature scorers from sklearn to the widget (ANOVA, Chi2, Univariate Linear Regression)
- Add imputation to preprocessors for scores from sklearn (they fail with missing data)
- Attempt to score individual attributes in datasets with mixed attribute types

OWRank: Add ANOVA, Chi2 and Univariate Linear Regression

---

Orange/data/io.py
Orange/tests/test_variable.py

Otherwise saving and reloading a CSV with TimeVariable didn't work.

[FIX] TimeVariable values are saved in ISO 8601 format

---

Orange/widgets/unsupervised/owpca.py

The movement of threshold is now restricted to only snapping the grid.

Fixed  Dragging of the threshold (# of dimensions) in the PCA Widget #1051 

---

Orange/widgets/classify/owclassificationtreegraph.py

Text was redundant when split by the same attribute more than once.

OWTreeGraph: Prune node hover tooltip

---

Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/data/tests/test_owfeatureconstructor.py

* Fix an error in Feature Constructor widget due to a change in Python 3.5 ast (`AttributeError: 'Call' object has no attribute 'starargs'`)
* Add tests
* Some other minor fixes and code cleanup

[FIX] Feature constructor Python 3.5 ast support

---

Orange/canvas/document/schemeedit.py

A workaround for a segfault in `QGraphicsSceneFindItemBspTreeVisitor::visit`

[FIX] Disable bsp index on the main canvas scene

---

Orange/canvas/document/schemeedit.py

A workaround for a segfault in `QGraphicsSceneFindItemBspTreeVisitor::visit`
Continues from biolab/orange3@c7f138083948aaf9941795340d505dfa82845fdf
This time for the *actuall* scene instance that is used.

canvas: Disable bsp index on the main canvas scene Pt2

---

Orange/widgets/io.py

Fixed "Save Graph doesn't save axes" issue #1134. The graphs are now saved with a white background. Scaling issue still exist.

[FIX] Save Graph doesn't save axes #1134 (updated base)

---

Orange/widgets/visualize/owscatterplot.py

[FIX] Scatter plot: Fix vizrank's crash when pair had no valid data

---

Orange/preprocess/transformation.py
Orange/tests/test_logistic_regression.py

Transformation.transform can sometimes return 0d ndarray.
This happens for instance in ReplaceUnknowns, when np.where is called on a Float value (produced by a nested call of compute_value).

[FIX] Transformation: fix a bug in nested transformation of instance

---

Orange/tests/test_filter.py

1) Start a new file with filter tests for Storage subclasses that do not have filters implemented.
2) Add test for Values filter.

test_filter: Add non-Table test for Values filter

---

doc/development/source/tutorial.rst

Changed:
- Fix broken link to setuptools `entry_points` documentation

Fix broken link to setuptools entry_points docs

---

setup.py

This reverts commit 6afe45865fedaeb2e37dad5beaba3c817f8dfaef.
The setup.py should not assume that the python env (or even the user)
which runs the setup.py has any relation to where the package will
eventually be installed.
As it stands, wheel format does no even (currently) support absolute paths
(they end up in e.g. site-pacakges/usr/local/share).

Revert "setup.py: Install desktop file and icon on GNU/Linux/FreeBSD"

---

Orange/data/io.py
Orange/data/table.py
Orange/tests/test_basket_reader.py
Orange/tests/test_tab_reader.py
Orange/tests/test_table.py
Orange/tests/test_txt_reader.py
Orange/tests/test_variable.py
Orange/tests/test_xlsx_reader.py
Orange/widgets/data/owfile.py
Orange/widgets/tests/test_io.py

Current singleton implementation of file readers/writers is hard to extend when additional features are needed (such as selecting sheet for excel files and overwriting header in #1012).
This PR replaces
FileFormat.read(filename)
with
FileFormat.get_reader(filename).read()
The new way enables us to set additional properties on reader before the read method is called.

Refactor data.io

---

Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/data/owselectrows.py
Orange/widgets/settings.py
Orange/widgets/tests/test_context_handler.py

Fix a bug when changing dataset with descriptors in FeatureConstructor would cause an error.
Implement partial matching of contexts (feature constructed on adult_sample that uses variable age can also be used on titanic dataset)

[ENH] Support context cloning in FeatureConstructor and SelectRows

---

doc/development/source/orange-demo/setup.py

As discovered in [discussion around issue #1184](https://github.com/biolab/orange3/issues/1184#issuecomment-214215811), the tuple is not necessary here. Only a single string is necessary, as is documented in the setuptools official [entry_points example](https://pythonhosted.org/setuptools/setuptools.html#dynamic-discovery-of-services-and-plugins).

[REF] Remove unnecessary parentheses

---

Orange/widgets/visualize/owscatterplotgraph.py

A simpler take on #1096: `OWScatterPlotGraph` already checks for nans, so we can just add warnings/information. `OWScatterPlotGraph` is also more general and can be used in some other widgets in the future.

Scatterplot warnings

---

pylintrc
requirements.txt

We need more arguments in parameterized scientific functions,
more methods in Qt subclasses.
Functions map and filter can be nice and even clearer than
comprehension in some cases, e.g.
```py
max(map(len, rows), default=0)
filter(len, transactions)
```
vs.
```py
max((len(row) for row in rows), default=0)
(t for t in transactions if len(t))
```

pylintrc: change some defaults

---

Orange/distance/__init__.py
Orange/tests/test_distances.py

```
import numpy as np
from Orange.data import Table, Instance
from Orange.distance import Euclidean
iris = Table('iris')
inst = Instance(iris.domain, np.concatenate((iris[0].x, [2])))
Euclidean(iris[0], iris[1])  # works
Euclidean(iris[0], inst)  # fails
```

[FIX] Compute distances between constructed Instances.

---

Orange/widgets/visualize/owdistributions.py

Currently the Distributions widget crashes on empty data.
This shows a warning instead.

[FIX] owdistributions: Check that the data is not empty

---

Orange/widgets/settings.py

Finding a suitable context when open_context is called works in mysterious ways, but it all boils down to searching all known contexts and finding the one that is a best match for the data at hand.
Currently, there are two ways to get all "known contexts". Widgets loaded from workflows use the list of contexts that were available when the workflow was saved. Newly created widgets use another list of contexts which is shared among all the widgets of the same kind.
This PR unifies the behaviour. When widget is added from canvas, it gets its own (empty) list of context settings. When different datasets are selected, used context settings are stored in this instance-specific list. A global list of contexts still exists, but is only updated when widget is removed from canvas.
Widgets loaded …

[ENH] Context per widget

---

Orange/preprocess/impute.py
Orange/tests/test_impute.py
Orange/widgets/data/owimpute.py

Switch to Model-based imputer in case learner is provided.
Added learner adequacy checker.

OWImpute: fix model based imputer. Fixes #1082.

---

Orange/clustering/kmeans.py
Orange/widgets/unsupervised/owkmeans.py

Silhouette score can be computed only for 2 <= k < n. Prevent its call in other cases.
Reproduce the bug by e.g. setting k=n in the kmeans widget.
Side note: I do not like the fact that this and other scores are computed automatically after every clustering run. Currently, other code depends on the scores being there, but a future PR could address this and at least make it optional, but preferably separate the scoring methods into individual functions, which can be called after clustering.

[FIX] kmeans: Compute silhouette only when possible

---

Orange/canvas/report/report.py

Unnecessary instantiation of PngWriter caused an error when saving scenes to reports.

[FIX] report: Saving scenes in reports

---

Orange/widgets/evaluate/owpredictions.py
Orange/widgets/utils/itemmodels.py

Changed the column's order in `Data Table` and `Predictions` widgets. Class attributes are displayed first, followed by metas and attributes. Consequently, the scrolling to maximum (right) in `Predictions` was also disabled.

TableModel: Change columns order to class, metas, attrs

---

Orange/widgets/data/owfile.py
Orange/widgets/data/tests/test_owfile.py

Allow files to be opened by dragging them to OWFile window. 
Does not work on OSX10.10+ with Qt4 (see https://bugreports.qt.io/browse/QTBUG-40449).
When applied on top of #1171, it should work as expected.
Could use some testing on other platforms.

[ENH] OWFile: Open dragged files

---

Orange/data/variable.py

Discrete values used to be sorted alphabetically. If they look numeric, they are now sorted as numbers.

[ENH] DiscreteVariable: sort values as numbers if possible

---

Orange/canvas/application/canvasmain.py
Orange/canvas/report/owreport.py

When closing the schema, canvas now also asks whether to save & clear, clear or keep the report.

Clear report on schema reload, save on close

---

Orange/classification/logistic_regression.py
Orange/preprocess/score.py
Orange/projection/pca.py
Orange/tests/test_linear_regression.py
Orange/tests/test_logistic_regression.py
Orange/tests/test_pca.py
Orange/tests/test_random_forest.py
Orange/widgets/data/owrank.py
Orange/widgets/unsupervised/owpca.py

score_data now returns numpy array, to support multiclass ranking (e.g. logistic regression coeficients for each class value). Scores for each class can be shown in Rank widget.
Similarly multiple PCA components can bw shown in Rank widget.

LearnerScorer: Support multiclass ranking

---

requirements-core.txt

`scikit-learn==0.16` did not yet have `gamma="auto"` option for SVM (`svm.py`, line 30) and hence the defualt SVM on Iris failed.

[FIX] Bump scikit-learn version

---

Orange/widgets/visualize/owlinearprojection.py

*You may want to check the two commits separately. The second is just cosmetics.*
Linear projection had a weird check box.
Also, this check box is enabled/disabled when selecting a discrete/continuous variable in the color combo a few lines higher up.
I fixed the checkbox and moved it below the color combo. This made the opacity slider look weird. Besides, the opacity belongs to the color setting. I hence ended up with
I also made it a bit narrower by decreasing the widths of the combos.

Linear projection: Improve GUI

---

scripts/windows/build-win-application.sh

Upgrade the minimum required pip version needed for installation
Require pip 8.* in order to install .whl files created by wheel>=0.27
Keep the wheel==0.26.* in the build env just to be sure.
Upgrade included scikit-learn to 0.17.1

Win installer: upgrade pip and scikit-learn in the windows application installer

---

Orange/canvas/config.py

A hack for issue #1143, where Qt failed to find the correct path for SVG plugin.

Manually specify plugins path

---

Orange/canvas/report/owreport.py

Fixes error when saving report with special chars to html.

Fix UnicodeEncode error for saving reports in html

---

.gitignore

pip collects package metadata by invoking `python setup.py egg_info` and
reading information from the generated *.egg-info/ under the assumption
that there is only one such directory. This can cause problems for
developers who might have remaining Orange.egg-info directories in their
git checkouts, causing pip install -e . to pick up obsolete
dependencies, version, ...
This does not solve the problem, but at least `git status` will indicate
there are untracked files in the checkout and that `git clean` is in
order.

Remove Orange.egg-info dir from .gitignore

---

Orange/canvas/canvas/items/annotationitem.py

* Fix an error in text annotation's selection state GUI indicator where, during user interaction, the frame could be removed but the item stays selected
* Make annotation items selection states somewhat more visible (this could still be improved)
Fixes #1301

[FIX] Canvas item selection indicators

---

Orange/data/io.py

Some classes that extend Table (like Corpus) did not yet have attribute `attributes` which prevented storing them using Save Data widget. I fixed it for Corpus but this I think this is a safer way to check for attributes.

[FIX] io: Safer check for attributes when storing

---

Orange/widgets/data/owimageviewer.py

Do not use (Qt's) queued connection to set the retrieved image.
When a scene is cleared all the pending tasks are cancelled and target
widgets deleted, however if the signal is already enqueued, when the
scene is cleared, the signal handler would attempt to set the pixmap on
an already deleted widget.
Also fix an file/socket descriptor leak.

[FIX] Image viewer runtime error

---

Orange/widgets/gui.py

`addToLayout` was given twice, both in `**misc` and as keyword argument.

[FIX] gui.auto_commit: Fix crash when caller gives  argument

---

setup.py

While nice in theory, 'Framework :: Orange' is not a valid pypi identifier and needs to be removed in order to make setup.py upload work.

Setup: Remove invalid classifier

---

Orange/classification/majority.py
Orange/data/table.py
Orange/preprocess/fss.py
Orange/tests/test_fss.py
Orange/tests/test_table.py

* Modified RemoveNaNColumns to skip sparse data sets so most classifiers (except Naive Bayes) can work on sparse data.
* Modified `Table.from_table` to work if `table.X` is sparse.
* Changed a few `len(data.X)` to `data.X.shape[0]` since len does not work on scipy sparse matrices.

[FIX] Support Sparse Matrices

---

Orange/widgets/data/owdiscretize.py
Orange/widgets/gui.py

To consider: the orders of options for general and individual setting are no longer the same. We can
- keep them different
- reorder them and disregard the compatibility with saved settings
- reorder them and keep the compatibility, which would require having some trivial, but annoying code for reshuffling.
Before:
After:

Discretize: Improve gui

---

Orange/preprocess/preprocess.py

Data table can include "attributes" attribute that stores object to be passed along with the data. SklImpute created a new data set from numpy objects, thus not storing the "attributes" from original data table. This has now been fixed. 
I was not able to find a better, general fix that would modify Preprocess class to do so for any kind of preprocessing.
The unwanted behavior fixed in this pull request was found through combination of Distance -> MDS widgets where the "attributes" attribute of the incoming data was lost when selecting data from MDS, and the loss was contributed to management of the data in Distance widget.

[FIX] Pass data attributes after preprocess.

---

Orange/data/variable.py
Orange/tests/test_variable.py

Time information might be specified as a unix timestamp. Currently such values are not compatible with TimeVariable, as it assumes data in one of the ISO (human-readable) formats.
Numeric values between 1 and 9999 could be either timestamp or year (iso format "%Y"). For those cases, the values is assumed to be in iso format and parsed accordingly (the existing behaviour).

[ENH] Support unix timestamps in TimeVariable

---

Orange/widgets/utils/owlearnerwidget.py

`OWBaseLearner` assigned `learner_name` to `model.name` but not to `learner.name`. Widgets like Test & Score or Confusion Matrix thus showed the type of the model (e.g. "naive bayes") instead of the name specified in the widget (e.g. "Naive Bayes", as is the default in Naive Bayes widget).
The fix is roughly nine times shorter than this message. :)

[FIX] OWBaseLearner: Add name attribute to learner

---

Orange/widgets/data/owimageviewer.py

Calling QGraphicsScene.clear when the scene has selected items will
trigger a selectionChanged signal, however the containing items will
have already been deleted (C++ side).
Avoid this by removing all python references to the graphics items
before calling scene.clear()

[FIX] Fix a RuntimeError in 'Image Viewer' when clearing the scene

---

Orange/widgets/data/owselectcolumns.py

Beforehand, changes on auto-apply were not reflected correctly.
Drag&drop did not work as expected. The fix includes calls
to `self.update_completer_model()` whenever either of the
VariablesListItemModels is changed (`rowsRemoved`).

[FIX] OWSelectColumns: auto-apply

---

Orange/widgets/visualize/owlinearprojection.py

The widget crashed when setting the points shape to class variable.
Besides, it reset the shape when checking "Show class density".

[FIX] OWLinearProjection: Fixups

---

Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/tests/test_itemmodels.py
Orange/widgets/utils/itemmodels.py

Granted the Qt documentation can be a bit misleading at times, however the Qt's item view framework does not impose the restriction that the data associated with a DisplayRole be a string. After all a MVC abstraction is intended to separate the data from its presentation.
For instance there are many situations where preserving the type of the item intended for display is beneficial (when displaying numerical data, dates, ...), as the view can then benefit from the default behavior of QSortFilterProxyModel model and have proper sorting with the default configuration out of the box (i.e. no `setSortRole` necessary, as the item to be displayed is also the one defining the ordering), locale specific date formating, decimal separator, .... (courtesy of `QStyleItemDelegate.displayText`). 
In …

[FIX] Revert PyListModel display role change

---

Orange/canvas/document/quickmenu.py

When one types "di", she probably means "**di**scretization" or "**di**stances" not "E**di**t domain".
The pattern matches beginnings of words, that is, "ma" also matches "Distance Matrix".

[ENH] Canvas quick menu: match only at the beginning of word

---

Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/gui.py
doc/development/source/gui.rst

Continues from #1352 -- see the discussion there.
In a nutshell, we would like to have auto-apply as default, but for this we need to disable tracking and change spins into combos.
Class attributes were renamed to avoid compatibility problems with older saved settings.
@kernc, please comment on 820d34c8bd1072f98978fb7209d3b6e7f91287d1. I think we need something like this; the implementation is a bit of a hack, but this is easier than passing arguments to constructor. Besides, it fixes all controls in `gui` with a single change.

Test score - Changes in GUI

---

Orange/widgets/visualize/owmosaic.py

After all the fuss needed to get the example indices for the original data, Mosaic output discretized data. :)

[FIX] Mosaic: Output original data, not discretized

---

Orange/data/table.py

If class attribute comes from sparse X it should be made dense since sickit learn does not work well with sparse Y (e.g. sklearn.cross_validation.StratifiedKFold does not work).

[FIX] Table.from_table: Assure Y is dense

---

Orange/widgets/data/owcolor.py

@ajdapretnar, was this (ticket 301) your idea?
Please see whether you like this implementation.
It is only for continuous attributes. For discrete, it may not make much sense since the number of values varies across features.

[ENH] OWColors: Implement copy-to-all for continuous pallettes

---

Orange/widgets/unsupervised/owmds.py
Orange/widgets/utils/plot/owplotgui.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owscatterplotgraph.py

The ticket was about doing this for all widgets. I found only these two.
The first and the thirs commit implement the option for the two widgets.
The second commit reorganizes the Scatter plot GUI. The original layout had separate boxes for combos and for checkboxes. The new checkbox so obviously belongs to the label combo that I've put it there. By the same logic, other checkboxes belong to different places in the widget. I'm not totally satisfied with the result; I think it's better than the original (cleaner and smaller), but I can revert it if you dislike it.
Original:
Changed:

[ENH] Scatter plot and MDS: Show labels only for selected points

---

Orange/widgets/data/owimageviewer.py

Display all images scaled to 'same' (aspect preserving) size

[ENH] Image viewer thumbnail size

---

Orange/evaluation/testing.py
Orange/tests/test_ada_boost.py
Orange/tests/test_evaluation_scoring.py
Orange/tests/test_evaluation_testing.py
Orange/widgets/evaluate/owtestlearners.py
requirements-core.txt

Parallel multiprocess execution of model evaluation methods.
Assumptions:
* there is some `n_cpu * (data.nbytes + C)` extra RAM available,
* passed arguments (learners, data) are picklable, else it fallbacks to one single thread.

[ENH] Parallelized cross validation & other evaluation methods

---

Orange/widgets/classify/owtreeviewer2d.py
Orange/widgets/io.py
Orange/widgets/widget.py

This should work for all widgets that have `graph_name` attribute (~ the Save Image button).
Can somebody check it on Linux and Windows? Scatter plot and Box plot, for instance.
@VesnaT, you're an expert for Linear Projection - and saving graphs in general. Can you check why it copying doesn't work for Linear Projection and Distributions?

[ENH] Implement copying graph to clipboard using Ctrl-C (Cmd-C)

---

Orange/widgets/utils/owlearnerwidget.py

If we provide a data set without any features (as unpreprocessed Corspus) learners crashed with a red screen. This PR adds a check for this and shows an error message instead.

[FIX] OWLearnerWidget: Don't crash when no features 

---

Orange/canvas/__main__.py

An error in `fix_win_pythonw_std_stream` prevented it from setting a
valid stream to stderr/stdout. Without a valid stderr stream the logging
module raises errors when attempting to write to stderr.

[FIX] Fix an logging error on windows

---

Orange/canvas/registry/description.py
Orange/widgets/data/owcolor.py

Widget docstrings (required by lint) give the same information as descriptions. I recommend preferring docstrings. With this PR, if the widget class does not have `description` and/or `long_description`,
- the docstring is used for `long_description` and/or
- the `long_description` up to the first `\n\n` is used for `description`.
Usage is demonstrated on widget `OWColor`.
If the docstring actually contains technical info (e.g. a real Napoleon-style docstring), the widget must use `long_description` (and `short_description`, if necessary).

Use widget class docstrings as descriptions

---

Orange/widgets/data/owfile.py

Widgets that deal with images use `origin` attribute of the string feature with file names that stores the original location of the data file. This is used when image files are referred to with relative location. Initially, `self.loaded_file` stored this location, but this has been broken and only works when file is chosen from the file browser, and not when the file is selected from the combo box with history. To be on the safe side, I keep this variable but if empty add the filename from `self.last_path()`. Ideally, only `self.last_path()` would be sufficient, I guess.

[FIX] File: Stores filenames to image attributes

---

Orange/widgets/unsupervised/owpca.py

Ticket 133 from the to-do list wants "*PCA widget: vertical bar should travel in grid (dimensions are integers). Also, mark the intersection of the bar with a dot, and show the projection like of the two dots to the y axis.*"
Rounding was already implemented (with errors). I added the lines, but also numeric labels, which make the lines redundant. @BlazZupan, do I keep the lines (in this case, you can merge the PR) or do the number suffice?

[ENH] PCA: Add lines and labels showing the explained variance

---

Orange/canvas/registry/description.py

Fix a bug introduced in #1384.

Registry: Do not crash on widgets with empty docstrings

---

Orange/widgets/data/owselectrows.py

In `set_data` we calculate the index of an attribute that is passed to `add_rows`. Since `add_rows` only consider visible attributes the index has to be calculated only on visible as well.
Otherwise this caused `attr_combo.setCurrentIndex` to be set to values larger than the number of items inside it. Strangely this works but causes `attr_combo.currentText()` to returns an empty string which of course breaks indexing on domain.

[FIX] SelectRows: Index attrs only by visible in set_data

---

Orange/data/table.py
Orange/preprocess/score.py
Orange/widgets/data/owrank.py

[ENH] Rank adopted for sparse data

---

Orange/preprocess/preprocess.py
Orange/tests/test_discretize.py
Orange/widgets/data/owcolor.py
Orange/widgets/gui.py
Orange/widgets/utils/__init__.py
Orange/widgets/utils/domaineditor.py
Orange/widgets/utils/progressbar.py
Orange/widgets/utils/scaling.py
Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/owparallelgraph.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owscatterplotgraph.py
Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/utils.py
Orange/widgets/widget.py

- Add VizRank for Sieve diagram.
- Refactor the ancient methods for drawing the graph.
- Fix discretization of classes and metas.
- Partially unrelated: allow specifying the size policy as tuple in calls to `gui`
Commit 512c35b0a20d87e733f0571be6a84c50d949ec04 is a massive clean-up which puts some classes shared across multiple widgets into different utility modules, and puts the general viz rank code into a common base class.

[ENH] Ranking for Sieve, refactoring of Sieve, Mosaic and VizRank

---

Orange/widgets/data/owsql.py

Try to create the required extensions if they do not exist on the selected database.
Show error if unable to do so.
Fixes #1388

[ENH] Automatically create required SQL extensions

---

Orange/widgets/classify/owrandomforest.py

Random forest for classification had a parameter that in the GUI said "Do not split subsets smaller than", but was actually setting another parameter, `max_leaf_nodes`. To keep it faithful to the GUI description, the `max_leaf_nodes` was replaced with `min_samples_split`, so that now the GUI description matches what the learner actually does.
Minimum to another pruning parameter, `max_depth`, was changed to 1 (scikit-learn counts this as root plus one more level).
Some minor cleaning of code was also done to line length to 80 and thus get rid of PyCharm warnings.

[FIX] Rand Forest Class: Min sample replaces max leaf nodes

---

Orange/canvas/registry/qt.py

Tooltips on widget toolbars showed "(from Orange3)" after the name of each widget due to mismatching project name.
@ales-erjavec, @astaric, is there a better, long-term solution? Comparing with `Orange.setup.NAME` doesn't seem appropriate - or is it?

[FIX] Remove '(from Orange3)' from widget names in canvas

---

Orange/widgets/data/owpaintdata.py

Before, the widget would send out the data table despite not including any data instances. This happens, for example, when sending the data is set to automatic (every change is committed) and the user removes all the data. With the empty data sets, some of Orange's widget crash (a problem on its own), so it is safer and according to convention in Orange to send None if the data set is empty.

[FIX] PaintData: Sends None when the paint includes no data points

---

Orange/widgets/utils/overlay.py

Register `__on_destroyed` as a Qt slot so it can be automatically
disconnected when the overlay widget is deleted/destroyed.
This fixes a possible 'RuntimeError C/C++ object was deleted ...' error
when the overlay is deleted before the target widget.

[FIX] overlay: Auto disconnect when the overlay widget is deleted

---

Orange/widgets/unsupervised/owpca.py

[FIX] PCA: Fix the variance spin.

---

Orange/widgets/visualize/owscatterplot.py

In the previous version ScatterPlot would send the data table with no instances, which would crash some widgets. This has been fixed now, such that if no instances are selected, None is send. Similar for sending out un-selected instances.

[FIX] Scatterplot: Sends none in no instance selected

---

Orange/data/sql/table.py
Orange/data/variable.py
Orange/tests/sql/test_sql_table.py
Orange/tests/test_variable.py

The following database fields are now automatically mapped to TimeVariable:
date, time, timetz, timestamp, timestamptz

[ENH] SqlTable: Automatically recognize date/time fields

---

Orange/data/variable.py
Orange/widgets/data/owselectrows.py

... as they are skipped for ordinary ContinuousVariables.
Previous implementation parsed empty strings first into nan objects which were not skipped over later.

[FIX] Select Rows: skip undefined TimeVariable filters

---

Orange/widgets/unsupervised/owkmeans.py

Previous format string in silhouette plot caused crashes of k-means. Fixed to integer now.

[FIX] KMeans: Silhouette format fixed to integer

---

Orange/evaluation/testing.py
Orange/widgets/classify/owlogisticregression.py
Orange/widgets/regression/owlinearregression.py

Both linear and logistic regression committed the learner twice upon initialization. The first time when setting (changing) the attributes for initial setup, and the second time once the initialization was over and when the auto commit was set to True. If the widgets were connected to Test & Score, this resulted in running the testing (e.g. cross validation) twice.
Debugging of these widget lead to discovery a bug of crashing the parallel execution of cross-validation, but only when in debug mode and running through PyCharm on OS X. The fix is to change to sequential execution  (`n_jobs = 1`) but issuing a warning instead of raising an error.

[FIX] Lin and Log Regression: Prevent double commit

---

Orange/widgets/visualize/owboxplot.py

[FIX] OWBoxPlot: Show corresponding label when ploting discrete variable

---

Orange/classification/naive_bayes.py
Orange/tests/test_naive_bayes.py

[FIX] NaiveBayes: Handle degenerate cases

---

Orange/statistics/util.py
Orange/tests/test_statistics.py

Should supposedly help in preventing the need for further PRs like https://github.com/biolab/orange3/pull/1425, https://github.com/biolab/orange3/pull/1428, https://github.com/biolab/orange3/pull/1431.

bottlechest.stats: return zeros for empty tables

---

Orange/data/sql/table.py
Orange/tests/sql/test_sql_table.py

Unknown SQL field types are mapped to Orange StringVariables.
Before, if they were e.g. used in filters they could be compared to string constants etc. which might not be supported for that type.
Now if we read the data into StringVariables, cast them to text type first in the database.

[FIX] SqlTable: Cast to text for unknown and string types

---

Orange/classification/tree.py
Orange/regression/tree.py

The preprocessors in tree.py were in the incorrect order (continuize must be in front of impute). Revert to the inherited order.

[FIX] Tree preprocessor order.

---

Orange/widgets/unsupervised/owkmeans.py

After some consultation with Google I notice that the name of the widget should be k-Means, as this is the name of the algorithm and as we are using camel case for widget names.

k-Means: Renamed k-means widget to k-Means

---

Orange/widgets/visualize/owscatterplot.py

[FIX] OWScatterPlot: Fix crash on classless data

---

Orange/widgets/visualize/owdistributions.py
Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/owscattermap.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/owvenndiagram.py

Widget priority determines the order in which widgets are displayed in the Orange toolbox. I have updated this order for widgets in Visualization pane as the previous order was not consistent with the order in which these widgets are normally used. For some of the widgets the priority (=100) was wrong, and for some it was not defined - both is now fixed.

Reorder visualisation widgets

---

Orange/classification/logistic_regression.py
Orange/tests/test_base.py

The liblinear solver does not support weights in SKL, even though the parameter is there. Override the property to prevent errors.

[FIX] Stop advertising support for weights in LogisticRegression.

---

Orange/widgets/data/owpaintdata.py
Orange/widgets/settings.py
Orange/widgets/tests/test_settings_handler.py

Introduce a concept of schema only setting - a setting that does not update its defaults, but is still saved with schema.
Use schema only setting to store painted points in PaintData widget.
Fixes #1451

[ENH] Save painted data to schema

---

Orange/widgets/utils/owlearnerwidget.py

Learner name field didn't have callback when it is changed. Problem was when user changed name and auto apply was on, because name haven't changed on output. It is fixed with this PR.

[FIX] OWBaseLearner: Learner name is changed on output when user changes it and auto apply selected 

---

Orange/widgets/unsupervised/owdistances.py
Orange/widgets/unsupervised/owmds.py

* Add more input data checks in MDS widget
* Preserve selected metric in 'Distances' widget

[FIX] MDS and Distances widges fix

---

Orange/canvas/report/owreport.py
Orange/canvas/report/tests/test_report.py
Orange/widgets/classify/owadaboost.py
Orange/widgets/classify/owsvmclassification.py
Orange/widgets/classify/tests/test_owadaboostclassification.py
Orange/widgets/classify/tests/test_owknnclassification.py
Orange/widgets/classify/tests/test_owlogisticregression.py
Orange/widgets/classify/tests/test_owsvmclassification.py
Orange/widgets/data/tests/test_owfile.py
Orange/widgets/regression/owadaboostregression.py
Orange/widgets/tests/base.py
Orange/widgets/tests/test_widget.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owscatterplotgraph.py
Orange/widgets/visualize/tests/test_owscatterplot.py

This PR contains fixes for (random) segfaults related to gui tests on travis, as well as (slightly modified) tests from #1262 and #1334.

[ENH] Test widgets on travis

---

Orange/statistics/util.py
Orange/tests/test_statistics.py

`np.bincount` has a length of the maximal element and can hence be shorter than the number of columns (e.g. when some of the last columns have all zeros). This forces it to count non zero elements for all columns.

[FIX] statistics.utils: Fix stats for sparse when last column missing

---

Orange/data/table.py
Orange/tests/test_table.py

`ensure_copy` is checking whether an array is a view through the `.base` argument which doesn't exist on `scipy.sparse` matrices. Since `scipy.sparse` don't work with views (e.g. indexing returns a copy of the matrix) the check should only be performed for dense matrices.

[FIX] Table: Fix ensure_copy for sparse matrices

---

Orange/widgets/gui.py

Updated docstring of `minv`, `maxv` and `step` because it can be also float in case `spinType` set to `float`.

[DOC] Docstring update, because spin can be also used with float values 

---

Orange/statistics/util.py
Orange/tests/test_statistics.py

This commit fixes three issues about weights. First, multiplication does work since X is 2d and weights are 1d (e.g. `operands could not be broadcast together with shapes (1000,2) (1000,)`). This is fixed by transforming weights to 2d. Further, weights should only be used for calculating mean. Third, we should not apply weights if X contains objects (like StringVariable).

[FIX] statistics.util: Fix applying weights

---

Orange/widgets/data/owimageviewer.py

Introduce a 'OSX Preview' like window to step through the images.

[ENH] ImageViewer: Add a 'Preview' like window

---

Orange/widgets/regression/owsgdregression.py
Orange/widgets/utils/owlearnerwidget.py

If apply is called before the auto_commit button is added to layout, it
is executed regardless of the auto_apply setting. By delaying the
calls to _something_changed callbacks, we can revert the workaround in
the OWBaseLearner's settings_changed method.

SGDRegression: Delay apply until after gui is constructed

---

Orange/widgets/classify/owadaboost.py
Orange/widgets/classify/tests/test_owadaboostclassification.py
Orange/widgets/regression/owadaboostregression.py
Orange/widgets/regression/tests/test_owadaboostregression.py
Orange/widgets/tests/base.py
Orange/widgets/utils/owlearnerwidget.py

[FIX] Fix AdaBoost widgets and add some tests

---

Orange/base.py
Orange/classification/knn.py
Orange/regression/knn.py
Orange/tests/test_knn.py
Orange/widgets/classify/tests/test_owknnclassification.py
Orange/widgets/regression/tests/test_owknnregression.py

[FIX] KNN: Fix crash when Mahanalobis metric is used

---

Orange/widgets/classify/owrandomforest.py
Orange/widgets/classify/tests/test_owrandomforest.py
Orange/widgets/regression/tests/test_owrandomforestregression.py

[FIX] OWRandomForest: Fix, refactor and widget tests

---

Orange/widgets/classify/tests/test_owrandomforest.py
Orange/widgets/regression/tests/test_owrandomforestregression.py
Orange/widgets/tests/base.py
Orange/widgets/tests/test_widget.py

Reset widget settings to defaults defined in code. This ensures that a
test always gets a widget with (same) default values, regardless of the
order in which the tests are run.

WidgetTests: Create widgets with default settings

---

Orange/widgets/gui.py
Orange/widgets/tests/test_gui.py

The fix prevents the gui element to crash when 'checked' parameter is forwarded, ie. is not None.

gui: Fix crash in doubleSpin when checked parameters is set

---

Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/tests/test_owheatmap.py
Orange/widgets/widget.py

The widget crashed, because its properties (which use settings) were accessed before the settings were initialized.

[FIX] OWHeatMap: Fix crash when creating an instance of the widget

---

Orange/data/io.py
Orange/data/table.py
Orange/tests/test_basket_reader.py
Orange/tests/test_tab_reader.py
Orange/tests/test_xlsx_reader.py
Orange/widgets/data/owfile.py

Although Tables should ideally be constructed using Table methods (e.g. from_file), sometimes readers are used directly (as in owfile.py). Currently names are not set properly in that case, leading to 'untitled' datasets.
This changes readers (csv,tab,excel) to return more complete data Tables with names set.

[FIX] Table names set by readers

---

Orange/widgets/utils/itemmodels.py

When data is requested (and DisplayRole forwarded), value presentation is now correct & consistent, even if abs(value) equals to 0. This handles a display bug (consequently, no tests are included).

[FIX] PyTableModel: DisplayRole value presentation

---

Orange/widgets/evaluate/owpredictions.py

Reimplement sizeHintForColumn
The default QTableView.sizeHintForColumn can iterate over the entire
model's contents, which can be unforgivingly slow for large models.
In particular this happens when the `sizeHintForColumn` is called while
the view is not visible.

[FIX] Predictions: column size hint

---

Orange/widgets/utils/domaineditor.py

When trying to display many (as in 100k) values in a discrete attribute in the File widget, there is a significant performance hit. This PR solves this issue by limiting display to 20 values, instead of trying to display all of them and then ellipsizing the grossly long text.

Performance improvement with many discrete values in File widget

---

Orange/canvas/application/addons.py

Remove proxy model mapping in `__data_changed` slot as the reported
changed indices are already from the real source model.
Fixes #1532

[FIX] canvas/addons: Remove wrong/unnecessary proxy mapping

---

Orange/widgets/regression/owlinearregression.py

At some point (perhaps when reorganizing the bottom parts of the widgets), the label move to some weird place in the layout.

Linear regression: Move mixing ratio under the slider

---

Orange/canvas/registry/description.py
Orange/canvas/registry/qt.py
Orange/widgets/data/owcolor.py
Orange/widgets/data/owfile.py
Orange/widgets/data/owpaintdata.py
Orange/widgets/data/owsql.py
Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/owsilhouetteplot.py
Orange/widgets/widget.py

As discussed with @janezd, I'm introducing standard widget descriptions that get displayed in canvas. Now only `description `variable gets displayed - it needs to be short and telling. `long_description `is no longer displayed but remains in the code. This also somehow prevents showing docstrings, which is good.

Changes to widget descriptions.

---

Orange/widgets/evaluate/owconfusionmatrix.py
Orange/widgets/evaluate/tests/test_owconfusionmatrix.py
Orange/widgets/gui.py

Fixes #1505.
The actual fix is in `gui.py`, in the constructor for `ControlledList`. The remainder of the PR deals with another related error: the widget wanted to store the `selected_learner` as an `int`, but since it represents the selection in `gui.listBox`, it kept changing to `list` at various places. It's simpler/safer to have a single-element list.

[FIX] Confusion matrix: fix selected_learner setting

---

Orange/data/io.py
Orange/tests/test_tab_reader.py

Fixes a problem where a dataset containing image filenames save from Orange could not be read again.

[FIX] Fix loading of datasets with paths in variable attributes

---

Orange/data/table.py
Orange/data/util.py
Orange/projection/pca.py
Orange/tests/test_data_util.py

Speedup of transformations into the PCA space on my laptop:
- adult:
6.07s -> 0.21s
- an infrared dataset with shape (16384, 1608):
(more than 40 minutes - cancelled) -> 6.69s

[ENH] PCA transformation speedup

---

Orange/clustering/hierarchical.py
Orange/tests/test_clustering_hierarchical.py
Orange/widgets/unsupervised/owdistancemap.py
Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/visualize/owheatmap.py

* Enable ward clustering in Hierarchical clustering widget
* Implement a workaround for scipy's input checking in scipy.cluster.hierarchy.linkage in scipy 0.16 and 0.17 (scipy issue 5220)
* Adjust limits for clustering in 'Distance map' and 'Heatmap' widgets.

[ENH] Enable Ward clustering in Hierarchical clustering widget 

---

Orange/widgets/classify/owsvmclassification.py
Orange/widgets/classify/tests/test_owsvmclassification.py
Orange/widgets/regression/owsvmregression.py
Orange/widgets/regression/tests/test_owsvmregression.py
Orange/widgets/tests/base.py

[ENH] Upgrade OWSvm unittests

---

Orange/widgets/data/owimageviewer.py

Using QNetworkAccessManager to 'retrieve' many local files can lead
to temporarily running out of available file descriptors.
Presumably this is because the associated open fd is not closed
until the QNetworkReply is actually deleted (and not just closed).

[FIX] owimageviewer: Open local images directly

---

Orange/preprocess/score.py
Orange/tests/test_score_feature.py
Orange/widgets/data/owrank.py

Gini coefficient and Gini impurity are not the same. Docstring fixed to proper Wikipedia source.
As observed in many [sources](https://en.wikipedia.org/wiki/Decision_tree_learning#Gini_impurity), the formula for Gini impurity never contains division by 2. @BlazZupan, please check whether this is the right formula or not.
Also, "Gini" was a misleading attribute name in Rank widget. Here we're actually measuring Gini decrease. So even perhaps "Gini Gain" might not be the right name for this. Comments? @lanzagar @astaric 
Probably some fixes to names should be made elsewhere, too.

[FIX] Gini impurity: formula and docstring fixed.

---

pylintrc

Linter is meant to be helpful, not ignored.

pylintrc: make more lax to show fewer errors

---

Orange/tests/test_classification.py
Orange/tests/test_rules.py

Tests for pickling and handling missing values doubled the execution time of the entire suite. I tried and failed to tune the parameters to decrease the time to something reasonable.

CN2: Remove time consuming tests and prints

---

Orange/data/variable.py
Orange/widgets/data/oweditdomain.py
Orange/widgets/data/tests/test_owcolor.py
Orange/widgets/data/tests/test_oweditdomain.py
Orange/widgets/settings.py
Orange/widgets/tests/base.py

Color widget stores colors as a list inside the variables attribute dict. This caused a number of problems when used with EditDomain widget. For details, see individual commits.
Fixes #1527

[FIX] Fix compatibility with Color widget

---

Orange/widgets/highcharts.py
Orange/widgets/webview.py

It is required that also axis labels are provided in a report.  
Also fixed svg function in webview to take return whole svg. Before svg was returned without last `>`

[FIX] Fixed svg function to return svg chart together with container div for highcharts

---

Orange/widgets/classify/owloadclassifier.py

Filenames are stored in settings but when the new instance is created the most recent file was not loaded - it was only added to dropdown. The manual click on reload was necessary to load the classifier.

[FIX] Load Classifier widget sends classifier on init

---

Orange/canvas/canvas/items/linkitem.py
Orange/canvas/canvas/scene.py
Orange/canvas/scheme/link.py
Orange/canvas/scheme/signalmanager.py
Orange/canvas/scheme/widgetsscheme.py

Track and display the state of signal propagation on links in the canvas.

[RFC] [ENH] canvas: Indicate runtime state on links

---

Orange/statistics/util.py
Orange/tests/test_statistics.py

Stats returned negative numbers of nans on non-numberic data (metas). Hence, for metas, table widget always showed 'no missing values'. The problem was in priorities. We should first negate binary array and only then sum. Without brackets binary array was first summed and only then ~ was applied. On integers ~ returns -(x+1) which lead to negative values.

[FIX] Stats: Fix counting of missing values for non-numeric data

---

Orange/widgets/classify/owloadclassifier.py

Fixes loading to use single shot timer as discussed in #1584.

LoadClassifier: Use singleShot timer for loading

---

Orange/data/__init__.py
Orange/data/domain.py
Orange/data/filter.py
Orange/data/instance.py
Orange/data/io.py
Orange/data/sql/filter.py
Orange/data/sql/table.py
Orange/data/table.py
Orange/data/variable.py

Fixes 35% of lint errors in Orange.data errors
It was about time to remove `import *` imports, the rest are more or less cosmetic changes.

Improve code style in Orange.data module

---

Orange/widgets/data/owrank.py
Orange/widgets/data/tests/test_owrank.py
Orange/widgets/tests/base.py

Enable selection of scoring method. Scores are computed only when checked and when deselected stored in cache for later use.
Attribute selection is context dependent and progress bar is added to the widget to show percentage of computed scores.
Fixes #1547 and #1556

[ENH] OWRank: Widget improvements

---

Orange/data/io.py
Orange/tests/test_tab_reader.py

If a name appears multiple times, _1, _2, _3 ... is appended to all occurrences (including the first one, to prevent the case when the user would index a later occurrence and get the first)

io.py: Enumerate duplicated column names

---

Orange/data/variable.py
Orange/tests/test_variable.py

Due to static constructors in Variable.copy and ContinuousVariable.copy
the StringVariable.copy and TimeVariable.copy used to return Variable
and ContinuousVariable instances respectively.
Fix this by dispatching on `type(self)`.
Also add the missing entry for `vartype(Variable)` in
`gui.attributeIconDict`

[FIX] Variable: Fix Variable.copy for StringVariable and TimeVariable

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/owsieve.py

Fixes a similar problem as #1538, but for Sieve and Mosaic.
The fix for Mosaic has no effect since context settings in Mosaic do not work. @astaric, can you check why?
We can modify Mosaic to use models (like Sieve), which would make the problem go away, but we still need to fix the bug in settings (if there is one).

[FIX] Context attributes with metas in Sieve and Mosaic

---

Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/utils/__init__.py

Add VizRank to a widget requires setting up the class and the button and overloading methods for closing and hiding the widget. This PR provides a convenience function that constructs everything needed and monkey patches the `closeEvent` and `hideEvent` methods.

VizRank: Add convenience method for construction

---

Orange/widgets/gui.py
Orange/widgets/settings.py
Orange/widgets/tests/test_gui.py
Orange/widgets/utils/itemmodels.py
Orange/widgets/visualize/owboxplot.py

Working with models is cleaner and usually more convenient than with lists of strings. This PR adds `gui.listView`, which is similar to `gui.listBox` but uses a model instead of list, so values can be instances of `Variable` instead of their names. The code is tested on the box plot widget.
This currently does not work with context settings. We need to modify them to store the `name` if the value as an instance of `Variable` and to restore the `Variable`. For the latter, we need a flag either in the definition of the setting or in the saved settings. @astaric, any recommendations?

gui: Add listView

---

Orange/widgets/utils/owlearnerwidget.py

When the name of the learner had been changed, the entire model was re-calculated.

[FIX] OWBaseLearner: Do not re-fit if name has changed

---

Orange/widgets/evaluate/owrocanalysis.py
Orange/widgets/evaluate/tests/test_owrocanalysis.py

Check for any valid individual curves before averaging them.
Fixes gh-1590

[FIX] ROC Analysis - Fix roc averaging

---

Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/owparallelcoordinates.py
Orange/widgets/visualize/owpythagorastree.py
Orange/widgets/visualize/owpythagoreanforest.py
Orange/widgets/visualize/owruleviewer.py
Orange/widgets/visualize/owscattermap.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/owsilhouetteplot.py
Orange/widgets/visualize/owvenndiagram.py

The order of widgets was weird: it started with CN2 rules viewer, while Scatter plot was somewhere in the third row. I changed it to put the common visualizations to the front, and model visualizations towards the end.

Reorder visualization widgets

---

Orange/widgets/regression/owlinearregression.py
Orange/widgets/regression/tests/test_owlinearregression.py
Orange/widgets/tests/base.py

- Elastic net were mixed L1 and L2 in the opposite proportions(!).
- The related slider used to be in the wrong part; while this was already fixed a few weeks ago, the code for constructing the slider was still in `add_bottom_buttons`.
- The widget did not have the auto-apply button and would fail the base learner widget tests; this was cause by the redundant method `add_bottom_buttons`.
- The widget did not have any tests (I assume that it's because it'd fail them)
I added a test to the base test class for learner widgets, which checks whether the class has `unconditional_apply` method. This method is be required for proper implementation of force-apply. If the widget intentionally removes it, it will have to override this test (or avoid being tested).

[FIX] Linear regression: Fix Elastic net; Fix Auto-apply buttons

---

Orange/data/table.py
Orange/tests/test_table.py

OWSelectRows widget crashed, when filtering discrete meta attribute (if metas consist of both, discrete and string attributes).
Used condition was "is defined".

Table: Fix non-string metas filtering

---

Orange/widgets/visualize/owsilhouetteplot.py

Changing the checkbox `Add silhouette scores` didn't trigger auto commit. Now it does.

[FIX] Silhouette: Auto-commit on changing checkbox state

---

Orange/widgets/classify/owlogisticregression.py
Orange/widgets/classify/owsvmclassification.py
Orange/widgets/regression/owlinearregression.py
Orange/widgets/regression/owsvmregression.py
Orange/widgets/widget.py
doc/development/source/tutorial-channels.rst
doc/development/source/widget.rst

This ensures that Coefficients/Support Vectors are never auto connected
to a Test & Score widget.

[FIX] :  Add `Explicit` flag to supplementary Table learner output

---

Orange/widgets/gui.py
Orange/widgets/utils/buttons.py

Use it to fix `auto_commit` generated layout.

[FIX] gui: Add a push button class adapted for variable width text

---

Orange/canvas/scheme/signalmanager.py
Orange/canvas/scheme/widgetsscheme.py
Orange/widgets/gui.py
Orange/widgets/utils/progressbar.py
Orange/widgets/widget.py

* Extend widget creation policy so widgets can be created only on
demand. This makes it possible to open/edit workflow without any
OWWidget instances being created until they are activated (opened/double
clicked). This policy is active when the stop signal propagation action is checked
in the canvas (Pause/Play button in the bottom toolbar)
* Better guard against explicit event loop reentry from OWWidget's `__init__`

[ENH] Extend widget creation policy

---

Orange/widgets/tests/base.py
Orange/widgets/utils/owlearnerwidget.py

Always output the initial learner, disregarding the `auto_apply`.

[FIX] owlearnerwidget: Fix output initialization

---

scripts/windows/build-win-application.sh

scikit-learn no longer provides wheels for Python 3.4 on windows for the latest 0.18 release.

[FIX] win-installer: Build scikit-learn in windows installer build script

---

Orange/canvas/application/errorreporting.py

[FIX] errorreporting: Fix an KeyError for a missing 'Widget Module' entry

---

Orange/widgets/gui.py

Invoke callbacks on `focusOutEvent` only if text actually changed.
This restores behaviour prior to 8f3968d5dfa1848b1e7a3d271df8fb344102d7d0

[FIX] gui.lineEdit: Restore changed state tracking

---

Orange/widgets/data/owfeatureconstructor.py

This is ugly, but since domain does not iterate over metas, I do not know of a better solution.
@ajdapretnar this should fix your feature constructor issues with twitter data set.

[FIX] OWFeatureConstructor: Fix domain check for only meta data sets

---

Orange/widgets/data/owfile.py

If the file was in incorrect format, the exception was sometimes thrown already by `FileFormat.get_reader`. To see this, rename an arbitrary file to .xlsx and try to load it.
The code would be simpler with a single try-except. However, since it catches any exception, I prefer wrapping a single call, hence two separate try-except blocks.

[FIX] OWFile: Report errors for incorrect file formats instead of crashing

---

Orange/data/table.py
Orange/preprocess/discretize.py
Orange/preprocess/impute.py
Orange/preprocess/normalize.py
Orange/preprocess/transformation.py
Orange/tests/test_discretize.py
Orange/tests/test_impute.py
Orange/tests/test_normalize.py
Orange/tests/test_table.py
Orange/widgets/visualize/owheatmap.py

Various bug-fixes required for sparse data:
- `preprocess.Transformation` should not call .squeeze since sparse matrices does not support it.
- `ReplaceUnknown` should be skipped for sparse since _missing_ are considered to be zero.
- `Discretizer` support sparse data.
- `Normalizer` support zero-based sparse data.
- `Table.from_table` should consider sparsity of initial array. For example, when adding columns to sparse X it should remain sparse.
- `Table._compute_contingency` fix for sparse on bottleneck.
- `OWHeatMap` widget converts sparse data to dense. Though this is probably not optimal it at least enables the use of heat map on sparse data where number of attributes is reasonable. On larger we probably couldn't see anything anyway. I tried and failed to make it work on sparse. The …

Sparse fixups

---

Orange/widgets/gui.py
Orange/widgets/widget.py

Pressing Enter in line edit should remove the focus. This signals that the data has been "entered". At least on Os X, keeping the focus looks as if the field is still being edited.
Second, when the widget open, the first field shouldn't have focus - especially if this is line edit. Editing should be triggered by the user.
For an example, open the Paint widget. The first line edit has focus and pressing Enter does not release it.

Focus adjustments

---

Orange/widgets/data/owfile.py

As noted by @lanzagar, #1635 no longer sets `self.data` to `None` in case or error. Fixed.

OWFile: Set self.data to None on error

---

Orange/canvas/scheme/readwrite.py

Having to resort to pickling is common and it is not an error. Moreover, it is annoying since the stack trace is printed after the stack trace of an actual error.

Workflow saving: Log pickle fallback as debug and without stack trace

---

Orange/widgets/credentials.py
Orange/widgets/tests/test_credentials.py
requirements-core.txt

Credential Manager is used for safely storing passwords in system's keyring services.

[ENH] CredentialManager: Store passwords in System Keyring Services

---

Orange/widgets/visualize/owboxplot.py
Orange/widgets/visualize/tests/test_owboxplot.py

[FIX] BoxPlot crashes on variables with no known values (#1568)

---

Orange/canvas/report/report.py
Orange/widgets/data/owtable.py
Orange/widgets/data/tests/test_owtable.py

QBrush. https://doc.qt.io/qt-4.8/qt.html#ItemDataRole-enum
Fixes report in Data Table.

[FIX] Reporting tabular in Data Table and Rank widgets

---

Orange/widgets/visualize/owscatterplot.py

Fixes #1621.
@ajdapretnar also complained about the missing sliders, but I told her that it was intentional. We want to simplify the GUI's by selecting optimal colors/sizes/shapes... ourselves instead of having dozens of options.
I remember discussing this, but I'm no longer sure that we reached a conclusion and that the change was indeed intentional: the commit in which this was removed, 71ccfcdd3de7dc0bdc0170dd752800cdf806ab99, is named "Lint" and doesn't make any other non-lint-related changes.

[FIX] Scatterplot: Reintroduce sliders for size and opacity

---

Orange/widgets/data/owsql.py

Move the attempt to create missing extensions right after the connection to the database is established.
Before, this could be attempted even before the connection existed, which resulted in an error (reproduced by setting parameters and before refreshing tick a checkbox).

[FIX] owsql: Fix bug when using connection before established

---

Orange/widgets/evaluate/owconfusionmatrix.py
Orange/widgets/evaluate/tests/test_owconfusionmatrix.py

[FIX] OWConfusionMatrix: Output None when no data is selected

---

Orange/widgets/visualize/owpythagorastree.py

Fix pythagoras tree widget tooltip for regression trees and improve the `main` function for easier debugging.
The tooltip originally tried to emulate the classification one where the samples are written like this:
Obviously this can't be emulated in a regression problem, but I missed this problem. This fix changes the tooltip to simply shows the # of samples in the node, which makes more sense.

[FIX] Fix pythagoras tree tooltip for regression trees

---

Orange/widgets/visualize/owpythagorastree.py
Orange/widgets/visualize/owpythagoreanforest.py
Orange/widgets/visualize/pythagorastreeviewer.py
Orange/widgets/visualize/utils/tree/skltreeadapter.py
Orange/widgets/visualize/utils/tree/treeadapter.py

TreeAdapters are great and potentially useful elsewhere, too.
When implementing another adapter, I guess I found two (cosmetic) slips:
- `get_instances_in_nodes` accepts instances of `TreeNode`, which is specific Pythagorean trees,
- `ROOT_PARENT` is defined as `-1`, which is specific to SKL trees. A value of `None` would be more pythonic. Besides, the code in pythagorasviewer.py compares the node with `-1` instead of with `ROOT_PARENT`. Finally, the constant is defined in the base `TreeAdapter` as well as in the derived `SklTreeAdapter`.
@pavlin-policar, can you take a look at these two cosmetic changes? Did I overlook any place that needs to be changed w.r.t this?

Make TreeAdapters for Pythagorean trees more general

---

Orange/widgets/unsupervised/owdistancemap.py
Orange/widgets/unsupervised/owhierarchicalclustering.py

When some drop down values are changed, no more data is selected. Therefore Selected Data output should be resend as None.

OWHierarchicalClustering, OWDistanceMap: Resend "Selected Data" when settings change

---

Orange/data/io.py
Orange/datasets/iris.tab.metadata
Orange/tests/test_tab_reader.py
Orange/tests/test_table.py
Orange/widgets/data/owfile.py

@astaric, you meant something like this?
Orange already read and wrote .metadata files, but in pickle format. This is highly inconvenient since the user can't edit it. I changed the format to a (very) simplified YAML: the file is expected to contain a single block mapping. Data is read as string. If we wish, we can either try to evaluate it (with fallback to string) or use PyYAML, although I don't think we need it.

[ENH] Metadata for data files

---

Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/tests/test_owheatmap.py

[FIX] OWHeatMap: Resend 'Selected Data' when settings change

---

Orange/data/sql/table.py
Orange/tests/sql/base.py
Orange/tests/sql/test_misc.py
Orange/tests/sql/test_sql_table.py
Orange/widgets/data/owsql.py
Orange/widgets/visualize/owparallelgraph.py
Orange/widgets/visualize/utils/lac.py

Sql code is currently coupled with SqlTable, making support for other sql backends hard to implement. This PR moves (some of the) code that is dependent on sql driver to a separate class (Psycopg2Backend) which could (in theory) be replaces by another implementation of the database backend.

Refactor SqlTable

---

Orange/widgets/visualize/owlinearprojection.py

* Fix an AttributeError when using latest pyqtgraph develop branch.
* Lock aspect ratio on the plot view.

[FIX] Fix an error when using latest pyqtgraph develop snapshot

---

Orange/widgets/unsupervised/owmds.py

Filter out QGraphicsLineItem with zero length. When using the Qt's
raster graphics system they cause bad rendering artifacts.
Fixes gh-1668

[FIX] MDS Widget: Fix zero length line, gray square bug

---

Orange/statistics/util.py
Orange/tests/test_statistics.py

Computing the number of nans for sparse matrices was broken and sometimes returned negative numbers.
Variable `non_zero` contains the number of defined values in each column. So to calculate the number of undefined (nans) for each column we have to substract `non_zero` from the number of values in the column i.e. `X.shape[0]` and not `X.shape[1]`. The bug was noticed when the number of defined values in some column was larger than the number of features and consequenlty the number of nans was negative. This caused density in OWTable to exceeded 100%.

[FIX] Statistics.util.stats: Fix negative #nans for sparse

---

Orange/widgets/visualize/owruleviewer.py
Orange/widgets/visualize/tests/test_owruleviewer.py

[ENH] CN2RuleViewer: Output sample of training data in absence of separate data

---

Orange/tree.py
Orange/widgets/evaluate/owconfusionmatrix.py
Orange/widgets/evaluate/tests/test_owconfusionmatrix.py
Orange/widgets/tests/base.py
Orange/widgets/tests/test_annotated_data.py
Orange/widgets/unsupervised/owdistancemap.py
Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/unsupervised/owmds.py
Orange/widgets/unsupervised/tests/test_owdistancemap.py
Orange/widgets/unsupervised/tests/test_owhierarchicalclustering.py
Orange/widgets/unsupervised/tests/test_owmds.py
Orange/widgets/utils/annotated_data.py
Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owtreeviewer.py
Orange/widgets/visualize/tests/test_owheatmap.py
Orange/widgets/visualize/tests/test_owscatterplot.py
Orange/widgets/visualize/tests/test_owtreegraph.py

[WIP][ENH] Scatterplot, HeatMap, TreeGraph, ConfusionMatrix and Unsupervised widgets: Output Flagged Data 

---

Orange/widgets/utils/itemmodels.py

Data Table crashed when for example X was in sparse format, but was empty (0 columns).

[FIX] TableModel: Don't crash on empty sparse data

---

Orange/canvas/application/errorreporting.py

Do not save through CanvasMainWindow.save_as. This records the last
save directory, so that the next time the user saves/opens a new
workflow they are presented with $TMPDIR

[FIX] Error Reporting: Temporary last open/save directory

---

Orange/widgets/utils/itemmodels.py

Continuous variables inside meta attributes are currently sorted by their string represenation and not by float values. This happens since dtype for metas is object and we map all object to strings before sorting. This PR checks whether the sorting variable is ContinuousVariable and casts values to floats.

[FIX] OWTable: Sort Continuous metas as floats; not strings

---

Orange/canvas/document/interactions.py

Numerous widgets now provide the signal with annotated data (#1655), which will be used quite often, but it is not the default output. Selected data should stay the default; even always showing the dialog would be annoying. The user thus has to connect the widgets, double click the link, and reroute. This annoyed me a lot.
I suggest that holding shift while connecting should trigger opening the link dialog. To not confuse the user, this should happen even when there's just a single signal on both sides.
I know this feature is a bit of easter egg, but a really useful one.
@ales-erjavec, the change is really simple. Have I overlooked anything?

[ENH] Canvas: Always show the link dialog if the user holds Shift

---

benchmark/base.py
benchmark/bench_basic.py

To ease my benchmarking of pandas code, I created a simple benchmark suite. It's based on `unittest` and is `timeit`-like, but does not use `timeit`.
I've included some basic tests. See if this is something we want included with Orange. I'm only not sure about the location, for now, I've put this in `/benchmark/`
Example output on current master:
```
Running benchmark with CPython v3.5.2 on Darwin-15.6.0-x86_64-i386-64bit (OSX 10.11.6 x86_64)
[adult_create_X] with 50 loops, best of 3:
min 0.518 usec per loop
avg 0.528 usec per loop
[adult_filter] skipped: Not a pandas environment.
[adult_read] with 5 loops, best of 3:
min 748 msec per loop
avg 786 msec per loop
[iris_basic_stats] with 50 loops, best of 3:
min 206 usec per loop
avg 247 usec per loop
[iris_contingency] with 10 loops, best …
```

[ENH] Simple benchmarking suite.

---

Orange/widgets/data/owtable.py
Orange/widgets/data/tests/test_owtable.py
Orange/widgets/evaluate/tests/test_owconfusionmatrix.py
Orange/widgets/tests/base.py
Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/unsupervised/tests/test_owdistancemap.py
Orange/widgets/unsupervised/tests/test_owhierarchicalclustering.py
Orange/widgets/unsupervised/tests/test_owmds.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/owpythagorastree.py
Orange/widgets/visualize/owruleviewer.py
Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/owsilhouetteplot.py
Orange/widgets/visualize/owtreeviewer.py
Orange/widgets/visualize/tests/test_owheatmap.py
Orange/widgets/visualize/tests/test_owlinearprojection.py
Orange/widgets/visualize/tests/test_owmosaic.py
Orange/widgets/visualize/tests/test_owpythagorastree.py
Orange/widgets/visualize/tests/test_owruleviewer.py
Orange/widgets/visualize/tests/test_owscatterplot.py
Orange/widgets/visualize/tests/test_owsieve.py
Orange/widgets/visualize/tests/test_owsilhouetteplot.py
Orange/widgets/visualize/tests/test_owtreegraph.py

[ENH] Visualize widgets: Output Annotated data and Fixups

---

Orange/data/sql/__init__.py
Orange/data/sql/backend/__init__.py
Orange/data/sql/backend/base.py
Orange/data/sql/backend/mssql.py
Orange/data/sql/backend/postgres.py
Orange/data/sql/table.py
Orange/tests/sql/base.py
Orange/tests/sql/test_sql_table.py
Orange/util.py
Orange/widgets/data/owsql.py
Orange/widgets/utils/messages.py
requirements-sql.txt

Backends moved to a separate package, moving backend-specific code from SqlTable/widgets to the appropriate backend

[ENH] SQL Server support in SQL widget

---

Orange/widgets/visualize/owscatterplot.py

... when the attr_* were stored by name.
For example open the second workflow (Interactive Visualizations) in the 'MenuBar->Help->Examples'

[FIX] Scatter Plot: Fix a error when restoring from pre DomainModel workflows

---

Orange/canvas/scheme/widgetsscheme.py
Orange/widgets/tests/test_widget.py
Orange/widgets/utils/messages.py
Orange/widgets/widget.py

<s> * Move the message bar to the bottom of the widget.</s>
* Allow subclasses to disable the default constructed message widget.

[ENH] widget: Allow subclasses to disable the default message bar widget

---

Orange/canvas/application/canvasmain.py
Orange/tests/sql/base.py
Orange/tests/sql/test_misc.py
Orange/tests/test_manifold.py
Orange/widgets/data/tests/test_owfile.py

- Fix tests so they run with PyQt5, without sql backend and on Windows.
- Fix QtWebEngine availability test in canvasmain.py

[FIX] Fix tests

---

Orange/widgets/evaluate/owconfusionmatrix.py
Orange/widgets/evaluate/tests/test_owconfusionmatrix.py

Confusion matrix set a warning (instead of error) when it received regression data. After that, it tried to use it and crashed.
The widget now shows an error and proceeds as if the data was None (e.g. clears the table if shown, disables the report button etc.)

[FIX] Confusion Matrix: Show error on regression results

---

Orange/widgets/data/owdatasampler.py
Orange/widgets/data/tests/test_owdatasampler.py
Orange/widgets/unsupervised/owdistances.py
Orange/widgets/unsupervised/tests/test_owdistances.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/tests/test_owscatterplot.py

Some widgets retain (error, warning, info) messages event hough data is removed from the input.
When widgets receive None, any warning should go off (use Titanic and Distances to reproduce).
The problem was found and solved for widgets: OWDataSampler, OWDistances, OWScatterPlot.

[FIX] Do not show messages when data is removed

---

Orange/preprocess/preprocess.py
Orange/tests/test_randomize.py
Orange/widgets/data/owpreprocess.py
Orange/widgets/data/tests/test_owpreprocess.py

Randomize should have a check box for replicable results
Enable setting random seed for Randomize preprocessor.
Add checkbox to OWPreprocess (Randomize editor).

OWPreprocess: Randomize - Enable replicable shuffling

---

Orange/widgets/evaluate/owconfusionmatrix.py
Orange/widgets/gui.py

If labels in the list view are changed before changing the selection, unselecting items crashes. 
Fix clears the (invalid) selection in this case.

Confusion matrix: Fix crash when unselecting non-existing items

---

Orange/widgets/data/owfile.py
Orange/widgets/data/tests/test_owfile.py

[FIX] OWFile: Do not load large files automatically

---

Orange/widgets/data/owfile.py

There was an error report where os.path.split failed because filename was None
Return immediately if no filename.

[FIX] owfile: Skip add_origin if no filename

---

Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/unsupervised/tests/test_owhierarchicalclustering.py

* Prevent a ZeroDivisionError when the dendrogram has zero height.
* Also remove a duplicated layout insertion.

[FIX] DendrogramWidget: Prevent a zero division error

---

Orange/widgets/data/owpythonscript.py

Fix QFileDialog.get{Save,Open}FileName usage in 'Python Script' widget
Broken since 032afd295581770a9b81c893710a6e89c11ab514

[FIX] owpythonscript: Fix QFileDialog.get{Save,Open}FileName usage

---

Orange/widgets/settings.py
Orange/widgets/tests/test_context_handler.py
Orange/widgets/tests/test_settings_handler.py
Orange/widgets/widget.py
doc/development/source/tutorial-settings.rst

When widgets are opened with old version of settings, they break in many different ways.
This PR introduces the concept of setting versions and migrations. When a widget changes its settings in a way that is not compatible with old version, it should raise its settings_version attribute and implement the migrate_settings (migrate_context for context settings) method.

[ENH] Setting migration

---

Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/data/tests/test_owfeatureconstructor.py

Add a new FeatureConstructor widget, select New > ContinousVariable (without connecting data first).
Widget crashes.
(Solves multiple error reports)
Add a None check

[FIX] FeatureConstructor: Fix crash when new variable is created without data

---

Orange/widgets/data/oweditdomain.py
Orange/widgets/data/tests/test_oweditdomain.py

The `VariableEditor.var` attribute was left uninitialized causing a error on when calling editor methods before a call to `set_data`.
Fix an AttributeError due to an uninitialized attribute

[FIX] oweditdomain: Initialize `var` attribute

---

.travis.yml

Trusty (beta) causes build failures with python3.4 builds

travis: disable trusty builds (for now)

---

Orange/widgets/gui.py
Orange/widgets/regression/owlinearregression.py
Orange/widgets/tests/base.py
Orange/widgets/tests/test_control_getter.py
Orange/widgets/tests/test_gui.py
Orange/widgets/tests/test_widget.py
Orange/widgets/unsupervised/owmanifoldlearning.py
Orange/widgets/utils/constants.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/tests/test_owboxplot.py
Orange/widgets/visualize/tests/test_owheatmap.py
Orange/widgets/visualize/tests/test_owsilhouetteplot.py
Orange/widgets/widget.py
doc/development/source/widget.rst

The motivation behind this is that we refer to the control by the name of the attribute it controls. 
This should reduce the number of attributes per widget and save us from similar names, like `binarize` for the attribute and `cb_binarize` for the checkbox that controls binarization.
If we decide we like it, I have to close one possible problem; in the dictionary that is used here to map attributes to controls, an attribute can be related to multiple controls. This is rare and can be fixed easily.

Expose widget controls by attribute names

---

Orange/widgets/data/owfile.py

After changes to domain editor the Apply button appears. It was not hidden again when different data was selected.
Hide apply button when load_data is called and editor_model reset.

[FIX] owfile: Hide apply button after resetting editor_model

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/tests/test_owmosaic.py
Orange/widgets/visualize/utils/__init__.py

VizRank for Mosaic. Computes chi-squares, either across class distributions for each cell (when the widget shows class distributions) or across cells.

[ENH] Add VizRank to Mosaic

---

Orange/widgets/data/tests/test_owdatasampler.py
Orange/widgets/settings.py
Orange/widgets/tests/test_context_handler.py
Orange/widgets/tests/test_settings_handler.py
doc/development/source/tutorial-settings.rst

<strike>Needs #1724.</strike> Usage example in #1642 (8227b626609a5cae23430ef2dbfde4d7584c246e)
Add utility functions for two common setting migrations.

Context: Add rename and migrate_str_to_variable

---

doc/visual-programming/build_widget_catalog.py

Categories are shown as h3 elements in the documentation, not h2.

doc: Include category in widget catalog

---

Orange/widgets/visualize/owboxplot.py

If quantiles can't be computed, the widget sets them to -1 and shows a mess (issue #1648).
Set them to `None` and skip drawing.

[FIX] Box plot: Handle situation when quantiles can't be computed

---

Orange/widgets/unsupervised/owpca.py
Orange/widgets/unsupervised/tests/test_owpca.py

When an user set covered variance to 100, the widget crashed.

owpca: fix error when variance is set to 100

---

Orange/canvas/gui/toolgrid.py

Under some circumstances a MouseRelease event could be delivered without a preceding MousePress event causing a `AttributeError: 'NoneType' object has no attribute 'underMouse'` in the `ToolButtonEventListener.eventFilter`
Remove the `ToolButtonEventListener` altogether as the mouse press tracking was not even used.
Parts that were needed were merged into the `ToolGrid` class itself.

[FIX] canvas/toolgrid: Remove (unused) mouse press event tracking

---

Orange/widgets/classify/owrandomforest.py

Value of min_samples_split parameter for sklearn.tree.DecisionTreeClassifier (and Regressor) must be at least 2.

OWRandomForest: Fix min_samples_split minimum value

---

Orange/widgets/visualize/owsilhouetteplot.py
Orange/widgets/visualize/tests/test_owsilhouetteplot.py

* When the number of clusters was the same as the number of instances the widget crashed with an `ValueError: Number of labels is {num} Valid values are 2 to n_samples - 1 (inclusive)` error from scikit-learn.
* If the cluster column contained missing values the widget would crash with an assertion error (`assert Ck[0] >= 0 and Ck[-1] < len(values)`) in SilhouettePlot.setScores
* Check (and show an error message) if the number of clusters is the same as the number of instances
* Omit instances with missing cluster assignment from the display (and the "Selected Data" output) and show a warning when this happens. When the "Add silhouette scores" is selected, output missing values for scores corresponding to instances with unknown cluster assignment.

[FIX] Silhouette Plot: Fixes

---

Orange/widgets/utils/webview.py

When loading multiple JS scripts in WebView and one of the first n-1 ends with a comment syntax error is raised even when the code is syntactically correct. This happens since these scripts are joined with a `;` and hence the first line of the following script is commented out.
Join multiple JS scripts with `;\n` instead.

WebView: Fix evalJS for scripts ending with comments

---

Orange/widgets/classify/owloadclassifier.py
Orange/widgets/classify/tests/test_owloadclassifier.py

Load Classifier widget crashes instead of reporting an error when unpickling fails.
Show the message.

[FIX] OWLoadClassifier: Show message on unpickling error

---

Orange/data/io.py
Orange/tests/test_txt_reader.py
Orange/widgets/data/owfile.py

Fixes https://github.com/biolab/orange3/issues/1714
Prefer `Variable.make`-made `var` instead of the specified `coltype`.
Use logging to log file loading exceptions for simpler debugging.

Fix confusion

---

.ci_tools/appveyor/build.cmd
.ci_tools/appveyor/step-build.ps1
.ci_tools/appveyor/step-install.ps1
.ci_tools/appveyor/step-test-miniconda.ps1
.ci_tools/appveyor/step-test.ps1
Orange/classification/_tree_scorers.c
Orange/classification/_tree_scorers.pyx
Orange/tests/test_score_feature.py
Orange/widgets/classify/owloadclassifier.py
Orange/widgets/classify/tests/test_owloadclassifier.py
appveyor.yml
conda-recipe/meta.yaml

Add [appveyor](https://appveyor.com) CI service configuration for testing on Windows.
An example output can be [viewed here](https://ci.appveyor.com/project/ales-erjavec/orange3).

[ENH] Add appveyor configuration

---

Orange/widgets/utils/itemmodels.py
Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/tests/test_owsieve.py

Fixes #1546.
<strike>Breaks compatibility with old settings. See #1672 for a similar problem with the scatter plot.
Blocked by #1724 and #1727.</strike>

[FIX] Switch Sieve to DomainModel, which also fixes VizRank crash on meta attributes

---

Orange/widgets/unsupervised/owdistances.py
Orange/widgets/unsupervised/tests/test_owdistances.py

ValueError: 'Too few observations for the number of dimensions.'
Workflow:
1. Paint data (paint & send)  -> Distance.
2. Select columns and Mahalanobis metric.
Adds shape check and error notification.
owdistances.py: error notification when there is too few observations for Mahalanobis distance. Prevents ValueError exception from distance/__init__.py class MahalanobisDistance.

[FIX] OWDistances: Mahalanobis wrong dimensions notification.

---

Orange/preprocess/transformation.py
Orange/tests/test_transformation.py

When editing a StringVariable in "Edit Domain" widget an TypeError is raised:
```
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/gui.py", line 1978, in do_commit
commit()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/oweditdomain.py", line 543, in commit
new_data = self.data.from_table(new_domain, self.data)
File "/Users/aleserjavec/workspace/orange3/Orange/data/table.py", line 374, in from_table
is_sparse=sp.issparse(source.metas))
File "/Users/aleserjavec/workspace/orange3/Orange/data/table.py", line 324, in get_columns
a[:, i] = match_type(col(source))
File "/Users/aleserjavec/workspace/orange3/Orange/preprocess/transformation.py", line 27, in __call__
domain = Domain([self.variable])
File …
```

[FIX] Fix transformation for non primitive variables

---

Orange/widgets/gui.py
Orange/widgets/tests/test_gui.py

`gui.comboBox` calls `callfront.action` to set the current item, but the model is only set later, within the call to `miscellanea` (miscellanea calls `control.set<key>` for all keyword arguments). As a consequence, the first item is always chosen.
The issue was first noticed in #1748, where the default value is "Enumeration", which is the second and not the first value in the combo.
Set the model earlier.

gui.comboBox: Set model before calling callfront.action

---

Orange/canvas/canvas/items/linkitem.py

Long signal names should be split to two lines.

LinkItem: Split long signal names to two lines

---

Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/unsupervised/tests/test_owhierarchicalclustering.py

Alternative to #1739.
OWHierarchialClustering: Annotation drop down does not keep context settings.
Annotation index is replaced with a context setting that contains an attribute or a string. Context are used only if the data are distances between rows. Otherwise, separate settings for axis=0 and axis=1 are used.
Settings are not migrated: the previous settings didn't work anyway.
<strike>- [ ] Documentation</strike>

[FIX] Hierarchical clustering: Make annotation a context setting

---

Orange/data/filter.py
Orange/tests/test_filter.py
Orange/widgets/visualize/owboxplot.py
Orange/widgets/visualize/tests/test_owboxplot.py

Make OWBoxPlot clickable.
Enable data selection (and send selected data to output).
Only data instances in squares are selectable. This could be upgraded for continuous variables.

OWBoxPlot: Select and send selected data

---

Orange/widgets/unsupervised/owdistancematrix.py
Orange/widgets/unsupervised/tests/test_owdistancematrix.py

AttributeError: Context has no attribute 'annotation'
Workflow: 
1. File widget (iris) -> Distance (choose rows, euclidean) -> DistanceMatrix.
2. Open Distance widget and select columns.
Attribute check.
owdistancematrix.py: prevent attribute error when showing distances between columns with an empty context.

[FIX] OWDistanceMatrix: attribute in context

---

Orange/data/filter.py
Orange/tests/test_filter.py

Fixup and test improvement
Fix FilterContinuous __eq__ method and make unittests more sensible.

[FIX] Filter: Fix FilterContinuous eq operator

---

Orange/data/domain.py
Orange/tests/test_domain.py
Orange/widgets/visualize/owboxplot.py
Orange/widgets/visualize/tests/test_owboxplot.py

The widget crashed if continuous variables were only in metas. 
To reproduce, use File (iris) -> Select columns -> Feature constructor -> Box plot, to move continuous features to metas and to create a new StringVariable, which causes data.metas.dtype = object.

[FIX] OWBoxPlot: Fixups

---

Orange/widgets/classify/owadaboost.py
Orange/widgets/classify/tests/test_owadaboostclassification.py
Orange/widgets/regression/owadaboostregression.py
Orange/widgets/regression/tests/test_owadaboostregression.py
Orange/widgets/utils/owlearnerwidget.py

AdaBoost simply crashed when a learner without support for `sample_weights` was put onto the input.
This does not happen any more, but it uses the Orange widget Error that tells us that the learner doesn't support sample weights. I've also changed the control widths to match most of the other learner widgets.

[FIX] Improve ada boost widget

---

Orange/widgets/evaluate/owconfusionmatrix.py

ref #1794
For some period of time the 'selected_learner' property was changed from List[int] -> int (4e49bb3fd0e11262f3ebf4b1116a91a4b49cc982) and then back again (8a492d79a2e17154a0881e24a05843406c8892c0)
When opening a workflow that was saved between that time (between releases 3.3.4 and 3.3.7) the widget would raise an exception
```
File "/Users/aleserjavec/workspace/orange3/Orange/canvas/scheme/widgetsscheme.py", line 822, in process_signals_for_widget
handler(*args)
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/evaluate/owconfusionmatrix.py", line 225, in set_results
prev_sel_learner = self.selected_learner.copy()
AttributeError: 'int' object has no attribute 'copy'
```

[FIX] owconfusionmatix: Add migrate_settings

---

Orange/widgets/data/owrank.py

ref #1794
Fix an error when restoring from a workflow that was saved before widget supported ranking features on data with no class.
```
File "/Users/aleserjavec/workspace/orange3/Orange/canvas/scheme/widgetsscheme.py", line 454, in create_widget_instance
widget.__init__()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owrank.py", line 260, in __init__
if self.headerState[2] is not None:
IndexError: tuple index out of range
```

[FIX] owrank: Add migrate_settings

---

Orange/widgets/visualize/owtreeviewer.py

Classification tree example does not open (#1794)
Declare which widgets are replaced with the new TreeGraph widget.

[FIX] TreeGraph: Compatibility with old schemas

---

Orange/widgets/data/owtable.py

Copy to clipboard shortcut (Ctrl-C) did not work since 55d31c159d179a53700d96fca5d6359c9ea4349b due to ambiguous shortcut overload.
It also raised a TypeError when running with PyQt5.

[FIX] Fix copy to clipboard in "Data Table" widget

---

.coveragerc
.travis.yml
.travis/install_pyqt.sh
.travis/stage_script.sh
Orange/__init__.py
Orange/canvas/__main__.py
Orange/canvas/report/owreport.py
Orange/evaluation/testing.py
Orange/tests/test_evaluation_testing.py
Orange/widgets/tests/base.py

Runs Python 3.5, PyQt 5 tests on Travis Ubuntu 14.04.
Enables code coverage of multiprocessing code.
Implements fix proposed in https://github.com/biolab/orange3/issues/1779#issuecomment-263720466 because it didn't work without it. Hopefully closes https://github.com/biolab/orange3/issues/1779.
Moves AnyQt PyQt4 importhook into Orange.\_\_init\_\_ for convenience when PyQt5 is available and some single module is run.

[MAINT] Travis Trusty

---

Orange/data/variable.py
Orange/tests/test_variable.py

Fixes https://github.com/biolab/orange3-prototypes/pull/55#issuecomment-264719890 .. https://github.com/biolab/orange3-prototypes/pull/55#issuecomment-265985095
Resets `_colors` when new `DiscreteVariable.values` are added.

DiscreteVariable: reset colors when new values added

---

Orange/canvas/registry/base.py
Orange/canvas/registry/description.py
Orange/canvas/scheme/readwrite.py
Orange/widgets/visualize/owtreeviewer.py

Fixes remaining issue in #1794 and #1804
Add a 'replaces' field to {Input,Output}Signal class to declare old->new channel mappings and take them into consideration when loading a workflow.

[ENH] Input/output signal replacement declarations

---

Orange/widgets/data/owfile.py
Orange/widgets/data/tests/test_owfile.py
Orange/widgets/settings.py
Orange/widgets/utils/domaineditor.py
Orange/widgets/widget.py

File Widget doesn't persist column mappings (#1773)
Refactor edit_domain component to allow calls to open and closeContext.

[FIX] Store changed variables in File widget

---

Orange/data/table.py

When using Feature Constructor to add discrete features to sparse array the code crashed inside `Table.from_table` in `match_type` function. Most easily reproducible on Text addon. Load some tweets and use Feature Constructor to create a discrete variable if some word is present in the content.
`match_type` was modified to assure the input, when dense, is a numpy array. That is, if python's list is provided (as is the case for Feature Constructor) it is transformed to a numpy array.

Table.from_table: match_type handle python's lists

---

Orange/data/io.py

Orange.data namespace included a lot of junk.
Define `__all__` in data.io.

Orange.data: Clean up the namespace

---

Orange/data/io.py
Orange/data/table.py
Orange/tests/test_table.py
Orange/widgets/data/owsave.py

Save data allows storing sparse data to all formats; i.e. even formats that clearly do not support sparse formats (like `.tab` or `.csv`).
Each FileWriter has a `SUPPORT_SPARSE_DATA` flag and OWSave only offers supported writers when the data is sparse. Also, Table now has a `is_sparse` method to ease checking if sparse data is present.

OWSave: Offer Only Supported Writers for Sparse Data

---

Orange/canvas/application/canvastooldock.py

For categories (or add-ons) with short widget names, horizontal scroll bar appeared in the category popup window.
The size of the popup window has been adjusted to its content.

CategoryPopupMenu: Adjust size of popup window

---

Orange/widgets/widget.py

Ctrl-C/Cmd-C copies the widget's graph to clipboard. If the widget had no graph, this crashed.
(errors/Orange.canvas.report.owreport/3.3.9/Orange.util%3A141/)
Add the necessary check.

[FIX] Crash on ctrl-c/cmd-c in widgets without graphs

---

.travis/build_doc.sh
Orange/widgets/utils/itemmodels.py
README.md

Random stuff. See individual commits.
The commit that broke WebviewWidget has been moved to https://github.com/biolab/orange3/pull/1816.

Small changes here and there

---

Orange/widgets/evaluate/owtestlearners.py

Fixes #1823.
When there was more than one target variable in the data, Test&Score reported a 'missing target variable'.
New error message for 'too many variables' introduced.

Error message for multitarget prediction

---

Orange/preprocess/transformation.py
Orange/tests/test_transformation.py
Orange/widgets/data/icons/CreateClass.svg
Orange/widgets/data/owcreateclass.py
Orange/widgets/data/tests/test_owcreateclass.py
doc/visual-programming/source/widgets/data/createclass.rst

In line with my widely known and well established tradition of impeccable pull requests and thoroughly tested code, I am presenting a new widget that creates a class attribute with values based on substrings of the chosen string or discrete attribute. The widget is needed for infraorange and presumably also in bioinformatics.
The widget has zero pylint warnings, was assigned a straight A by radon, and has a 100 % coverage with unit tests of the highest quality. The latter rely on simulated user interaction with the widget, and restrict themselves from testing the implementational details except where appropriate. The abundance of documentation strings explaining even the smallest nuances of the private methods - but without going into unnecessary details - will make the future maintenance …

[ENH] Create Class widget

---

Orange/modelling/__init__.py
Orange/modelling/tree.py
Orange/widgets/classify/owclassificationtree.py
Orange/widgets/classify/tests/test_owclassificationtree.py
Orange/widgets/model/icons/Tree.svg
Orange/widgets/model/owtree.py
Orange/widgets/model/tests/test_tree.py
Orange/widgets/regression/owregressiontree.py
Orange/widgets/regression/tests/test_owregressiontree.py

Merge Tree learner Widget to handle both classification and regression problems.
Fairly straightforward merge. Keep widgets in classify and regression categories until all the learners are merged. No noticeable difference except that both learners can handle any data type.
We did discuss that it would be a good idea to move `Orange.tree` into `Orange.modelling.tree` but I haven't been able to figure this out yet due to some cyclic imports. Perhaps that should go into its own PR?

Merge OWTree

---

doc/data-mining-library/source/reference/data.io.rst
doc/data-mining-library/source/reference/data.rst
doc/data-mining-library/source/reference/data.value.rst
doc/data-mining-library/source/reference/data.variable.rst
doc/data-mining-library/source/reference/misc.enum.rst
doc/data-mining-library/source/reference/misc.rst
doc/data-mining-library/source/tutorial/data.rst
doc/visual-programming/source/loading-your-data/index.rst

Fix some docs warnings, include data.io.rst in TOC, add more time variable format info, replace "kind" with "role" in Loading your data.

Documentation updates

---

Orange/widgets/gui.py

Confusion matrix, and possibly other widgets, may change the items in the listview before triggering `ControlledList.__setitem__`. `__setitem__` already took care about this by checking whether `self.listbox(item)` returned `None`. This apparently doesn't always work since one user got
```
Traceback (most recent call last) 
File "E:\\ORANGE\\Python34\\lib\\site-packages\\Orange\\canvas\\scheme\\widgetsscheme.py", line 822, in process_signals_for_widget
handler(*args)
File "E:\\ORANGE\\Python34\\lib\\site-packages\\Orange\\widgets\\evaluate\\owconfusionmatrix.py", line 270, in set_results
self.selected_learner[:] = prev_sel_learner
File "E:\\ORANGE\\Python34\\lib\\site-packages\\Orange\\widgets\\gui.py", line 2062, in __setitem__
unselect(i)
File …
```

[FIX] Fix crash in listview if labels are changed before calling __setitem__

---

Orange/widgets/classify/owclassificationtree.py
Orange/widgets/classify/tests/test_owclassificationtree.py
Orange/widgets/utils/messages.py

Fixes #1835.
Allows error messages in multiple lines.
Overload `check_data` to check the number of values issue an error.

[FIX] Tree widget binarization

---

Orange/widgets/highcharts.py
Orange/widgets/utils/_webview/helpers.js
Orange/widgets/utils/_webview/init-webengine-webchannel.js
Orange/widgets/utils/tests/test_webview.py
Orange/widgets/utils/webview.py

Various WebviewWidget updates. See commit messages.

WebviewWidget updates

---

Orange/widgets/data/owselectcolumns.py
Orange/widgets/utils/itemmodels.py
Orange/widgets/visualize/owlinearprojection.py

`VariableListModel` drag and drop didn't work out of the box.
Make drag and drop work out of the box. Remove redundant duplicate implementations.
Expected by https://github.com/biolab/orange3-prototypes/pull/57.

itemmodels.VariableListModel drag-and-drop updates

---

Orange/widgets/visualize/owpythagoreanforest.py

The Pythagorean Forest had an issue if we changed the size calculation combo box while still handling the changes from before.
Disable the size calculation combo box when beginning to draw and re-enable it when the drawing process is complete. Hopefully the enabled/disabled flickering is not noticeable enough to cause a problem.

Fix pythagorean forest overlap

---

Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/tests/test_owscatterplot.py

Fixes #1839.
Do nothing when there is no data.

[FIX] Scatter plot: don't crash on report without data

---

.ci_tools/appveyor/step-test.ps1
Orange/widgets/data/owselectrows.py
Orange/widgets/data/tests/test_owselectrows.py

```
Error:
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owselectrows.py", line 362, in conditions_changed
self.commit()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/gui.py", line 1972, in unconditional_commit
do_commit()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/gui.py", line 1980, in do_commit
commit()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owselectrows.py", line 417, in commit
matching_output = self.filters(self.data)
File "/Users/aleserjavec/workspace/orange3/Orange/data/filter.py", line 216, in __call__
return data._filter_values(self)
File "/Users/aleserjavec/workspace/orange3/Orange/data/table.py", …
```

[FIX] Select Rows filter enum

---

Orange/data/table.py

OWTable crashed, when passed data table with no data (produced by OWTranspose).
To reproduce: transpose table that consists only of meta attributes and pass it to OWTable.
Alternative to #1845

[FIX] Table.transpose: Keep metas array two dimensional when no attributes in domain

---

Orange/data/io.py
Orange/data/table.py
Orange/tests/test_table.py

Attributes' data type is StringVariable by default. Use heuristic to guess it.
Refactor io.py to make guessing heuristic reusable. 
Use heuristic to guess data type of attributes to be saved to metas.

[ENH] Table.transpose: Use heuristic to guess data type of attributes of attributes

---

Orange/widgets/data/owimageviewer.py

For data sets with missing images indexing was incorrect. Instead of using positions in the Data Table, positions from the ThumbnailView were used, resulting in mismatch betwen selected instances and instances on the output.
Use correct indices for output mask.

[FIX] OWImageViewer: Fix Selection Indexing

---

Orange/widgets/data/owselectcolumns.py

Fixes gh-1856
Explicitly track and call commit when a user initiated move action completes.

[FIX] owselectcolumns: Fix auto commit on any change

---

Orange/data/io.py

With datasets with lots of different unicode characters (not pertinent to any single particular language) in utf-8 encoding (e.g. some twitter data), the detected encoding was wrong.
Only trust detected encoding if confidence is at a certain (arbitrary high) level, otherwise try utf-8 and continue.

io: detecting encoding, only trust chardet if confident

---

Orange/widgets/data/owsave.py

Some writers in addons did not have `SUPPORT_SPARSE_DATA` flag which caused `OWSave` to crash.
Check if writer supports sparse more safely; i.e. if there is no flag assume it does not support sparse.

[FIX] OWSave: Safer Check if Writer Support Sparse

---

Orange/canvas/application/errorreporting.py

When reporting errors we only got the version of Orange, but not the versions of all installed packages and addons.
Add equivalent of pip freeze to reported data.

[MNT] ErrorReporting: Add Pip Freeze to Report

---

Orange/widgets/visualize/owdistributions.py
Orange/widgets/visualize/tests/test_owdistributions.py

When data is removed from widget, initial state should appear in combo boxes.
Fixes #1885

[FIX] OWDistributions: Reset combos when data is removed

---

Orange/canvas/application/errorreporting.py

Parsing a list of strings seems harder when importing to sentry than simply working with a string.
Change pip freeze formatting to a string `<package1>==<version>, <package2>==<version>, ...`

[MNT] ErrorReporting: Change Pip Freeze Format

---

Orange/widgets/tests/base.py
Orange/widgets/utils/annotated_data.py

Any annotations that accompany the data set are passed from widget to widget by `attributes` attribute of the data table. Essentially, the attributes should be inherited from the input data set. Where the new, resulting data set is build from scratch (say, with Orange.data.Table), the attributes have to be copied manually (e.g., `new_table.attributes = old_table.attributes`). This was not done in the create_annotated_table function which is used by several widgets (Data Table, MDS, Hierarchical Clustering), resulting in crashes of the widgets that rely on table attributes.
Attributes are now set for the newly constructed table by copying from input data table.

[FIX] Copy data attributes for annotated data set

---

Orange/widgets/evaluate/owpredictions.py

The widget crashes when predictor's domain differs from data domain (and trying to open report)
Fixes #1883
To reproduce, use Iris dataset to learn on and Titanic dataset to make predictions for.

[FIX] OWPredictions: Fix crash when opening report

---

Orange/widgets/data/owrank.py

super cannot be used in migrate_settings because the method is invoked
during type creation by the widget's metaclass while the implicit
`__class__` cell is not yet bound.
Prevents a warning during class import:
Could not read defaults for widget <class 'Orange.widgets.data.owrank.OWRank'>
The following error occurred:
super(): empty __class__ cell

[FIX] owrank: Remove `super()` call from `migrate_settings`

---

Orange/widgets/visualize/owsilhouetteplot.py
Orange/widgets/visualize/tests/test_owsilhouetteplot.py

[FIX] owsilhouetteplot: Fix TypeError when cluster column is an object array

---

Orange/widgets/data/owconcatenate.py
Orange/widgets/data/tests/test_owconcatenate.py

Fixes #1872, #1869, and tries to fix a usability problem in #1865 by saner defaults and by deactivating a part of the widget settings that are not used in certain input combinations.

[FIX] Concatenate bugfix

---

Orange/canvas/application/addons.py

The AddonManagerWidget does no initialize `__items` attribute in its `__init__` and can raise an AttributeError on access if the dialog itself is accepted before the PyPi query completes.
```
File "/Users/aleserjavec/workspace/orange3/Orange/canvas/application/addons.py", line 590, in __accepted
steps = self.addonwidget.item_state()
File "/Users/aleserjavec/workspace/orange3/Orange/canvas/application/addons.py", line 311, in item_state
for i, item in enumerate(self.__items):
AttributeError: 'AddonManagerWidget' object has no attribute '_AddonManagerWidget__items'
```
Add a missing `self.__items = …

canvas/addons: Initialize `__items` list in `__init__`

---

Orange/base.py
Orange/classification/random_forest.py
Orange/classification/tree.py
Orange/regression/random_forest.py
Orange/regression/tree.py
Orange/tree.py
Orange/widgets/visualize/owpythagorastree.py
Orange/widgets/visualize/owpythagoreanforest.py
Orange/widgets/visualize/utils/tree/skltreeadapter.py
Orange/widgets/visualize/utils/tree/treeadapter.py

Since the Orange trees were added, the pythagorean forest output was unable to connect with other tree visualisation widgets.
The issue was that Orange trees didn't use the Tree interface and removed it entirely, which meant that sklearn trees were not able to be displayed in the pythagorean tree viewer. Sklearn trees are still present in Orange since we still use sklearn's random forests.
This PR re-introduces the tree interfaces so this at least the pythagorean forest and trees work together again. Since TreeViewer only supports Orange trees, random forest trees can't be visualised there. This could be fixed if changes were made to TreeViewer to use the TreeAdapter that the pythagoras tree widget uses, but that would require major changes to TreeViewer.
I'm not satisfied with the …

Fix tree models with rf

---

Orange/widgets/unsupervised/owpca.py
Orange/widgets/unsupervised/tests/test_owpca.py

Fixes gh-1896
* Check for 0 total variance in the pca solution and display a warning.
* Prevent a NaN value to propagate into `self.variance_covered`.

[FIX] owpca: Handle the case of 0 total variance in the PCA solution

---

Orange/widgets/visualize/owboxplot.py
Orange/widgets/visualize/tests/test_owboxplot.py

Fixes #1892 
Put values with statistics that can't be computed (`None`) to the end of the list. Fix potentials problems at other places.
The PR doesn't fix another bug related to ordering which was introduced in 272233b3470efbfc57da05b51fb6db82e66e42f8. @VesnaT, please review those changes there (I've commented the offending change).

Boxplot: Fix crashes when stats can't be computed

---

Orange/canvas/scheme/readwrite.py

bytes objects were not allowed in literal serialization format (2to3 conversion?)

[FIX]canvas/readwrite: Fix byte literal serialization

---

Orange/canvas/application/errorreporting.py

When schema is not sent `data[WIDGET_SCHEME]` was not empty but contained the scheme's filename.
Remove `WIDGET_SCHEME` from data when scheme is not sent.

[MNT] ErrorReporting: Don't send scheme filename when no schema

---

Orange/widgets/regression/owsvmregression.py

When changing any options inside the `SVR Type` box, the learner (and model) were not updated.
Settings are now updated on any change.

[FIX] OWSVR: Update learner when SVR type changes

---

Orange/widgets/visualize/owtreeviewer.py
Orange/widgets/visualize/owtreeviewer2d.py
Orange/widgets/visualize/utils/tree/rules.py
Orange/widgets/visualize/utils/tree/skltreeadapter.py
Orange/widgets/visualize/utils/tree/treeadapter.py

Trees output from Pythagorean forest are not compatible with the TreeViewer widget.
Having established that #1850  would cause far too much confusion and make the overall tree model code completely non-understandable (Adapter for sklearn trees, but now also vice versa, tree model for sklearn trees?), I've taken another stab at it.
It seems that converting the TreeViewer widget to use the TreeAdapter actually doesn't require any major changes at all. So this is what I did in this PR, TreeViewer now uses the TreeAdapter, just like PythagoreanTree, so at least it's less confusing.
This is still based on #1786 since that fixes the PythagoreanTree compatibility.

[FIX] Treeviewer sklearn tree compatibility

---

Orange/preprocess/preprocess.py
Orange/widgets/data/owpreprocess.py
Orange/widgets/data/tests/test_owpreprocess.py

OWPreprocess crashes on PyQt5 when using Normalize action. 
Fix the crash.

OWPreprocess: fix Normalize crash since 60e1369b

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/tests/test_owmosaic.py

Fixes #1911
To reproduce: Connect dataset with continuous meta attribute to Mosaic Display and select it.

[FIX] OWMosaic: Discretize metas as well

---

Orange/preprocess/preprocess.py

After normalization the scaled variable used the same number of decimals as the original.
This meant scaling integers 0..100 to a span of 1 resulted in numbers being shown as 0 or 1 only (instead of 0.4 for example)
After scaling, reset number_of_decimals to 3 (default value of the parameter)

[FIX] preprocess: Reset number_of_decimals after scaling

---

Orange/widgets/unsupervised/owpca.py
Orange/widgets/unsupervised/tests/test_owpca.py

Fixes #1913
To reproduce: 
- No attributes: File (Iris) -> move all attributes to metas -> PCA 
- No rows: File (Iris) -> SelectRows (condition that results in 0 rows) -> PCA

[FIX] OWPCA: Fix crash for dataset with no rows or no attributes

---

Orange/widgets/visualize/owboxplot.py

When display selection changed (i.e. from No comparison to Compare means), labels changed position but boxes stayed at the same place.
To reproduce: File (iris) -> BoxPlot. Open BoxPlot and switch between No comparison and Compare means.

[FIX] OWBoxPlot: Fix ordering of boxes

---

Orange/widgets/data/owfeatureconstructor.py

Indexing exception's args member in [owfeatureconstructor.py#L584](https://github.com/biolab/orange3/blob/662faf463ca4629c838fe142cbf7bb20ac970a86/Orange/widgets/data/owfeatureconstructor.py#L584) can raise an IndexError when an exception is constructed without arguments
Use `traceback.format_exception_only` helper to display the exception message. Also log the full stack trace for easier debugging.

[FIX] owfeaturecontructor: Fix an IndexError accessing exception's args

---

Orange/widgets/data/owselectrows.py
Orange/widgets/data/tests/test_owselectrows.py

Class and meta variables are listed after (possibly large number of) attributes.
Follow recent policy to list class_vars first, then metas, and attributes last.

owselectrows: Change order of variables in dropdown

---

Orange/widgets/classify/owclassificationtree.py

When two attributes had an equal number of values, the test before binarization tried to compare instances of `DiscreteVariable`.

[FIX] Tree: Fix crash when two attributes equal number of values

---

Orange/widgets/unsupervised/owmds.py
Orange/widgets/unsupervised/tests/test_owmds.py

Fixes gh-1930
Make `_setup_plot` more robust for NaN values in the data.

[FIX] MDS Widget: Handle NaN values for plot point styling

---

Orange/canvas/application/errorreporting.py
Orange/canvas/application/settings.py
Orange/canvas/config.py

A while ago we discussed it would be nice if developers could report errors with their names rather than machine ids.
Machine ID line edit was added to Preferences menu. If the name is provided use it for reporting errors else fallback to reporting machine ids as before.

[RFC] ErrorReporting: Report developer names to Sentry

---

Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/tests/test_owsieve.py

Fixes #1921
If any of chosen attributes has no values, show only another's values and a label "No data".

[FIX] OWSieve: Fix crash for attribute with no values

---

MANIFEST.in
Orange/widgets/tests/base.py
Orange/widgets/tests/datasets/missing_data_1.tab
Orange/widgets/tests/datasets/missing_data_2.tab
Orange/widgets/tests/datasets/missing_data_3.tab
Orange/widgets/tests/utils.py
Orange/widgets/unsupervised/tests/test_owmds.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/tests/test_owlinearprojection.py
setup.py

Add some utilities for testing widgets, some datasets, ...
Also includes fix (and test) for gh-1938

[ENH] Widget testing utilities

---

Orange/base.py
Orange/widgets/classify/owlogisticregression.py
Orange/widgets/classify/owsvmclassification.py
Orange/widgets/regression/owlinearregression.py
Orange/widgets/utils/owlearnerwidget.py
Orange/widgets/utils/tests/test_owlearnerwidget.py

The base widget for learners did not intercept errors occurring during fitting. 
Errors are now caught and a basic message that something went wrong is displayed. Widgets can provide more specific error messages when possible.
Some widgets tested `self.valid_data` to verify that fitting succeeded. This did not really work. Although it now would, the tests are replaced to check whether `self.model` is not `None`. This is more appropriate since the data may be valid when the model is not.
A minor fix needed for tests: `Model` checked whether the `domain` parameter is given by checking `if domain`. This is wrong since `Domain` does not have `__bool__`, so `__len__` is used instead, and so `Domain([])` is treated as `False`.

[FIX] Catch errors during learning in learner widgets

---

Orange/data/table.py
Orange/tests/test_table.py

Fixes #1950.
Fix `Table.__repr__` for sparse.

[FIX] Table.__repr__: Fix for sparse data with < 5 instances

---

Orange/widgets/data/owpaintdata.py
Orange/widgets/data/tests/test_owpaintdata.py

The widget outputs a table created from a view of its data which should have been used only internally to the widget as it is modified in-place.
Ensure the output data is not a view of the working data.

[FIX] Paint Data: in-place output modification

---

Orange/widgets/data/owdatasampler.py
Orange/widgets/data/tests/test_owdatasampler.py

DataSampler crashed when stratified was selected, but one class contained only one element. Bootstrap did not work (invalid signature).
If stratified sampling fails, show a warning and sample without.
Add argument data to Bootstrap to satisfy signature.

[FIX] DataSampler: Fix crash when stratifying unbalanced datasets

---

Orange/canvas/application/addons.py

Listing packages did not work behind a proxy. Now it does.
Tested on linux with https_proxy set (where a proxy is really needed this time).

Actually use the SafeUrllibTransport defined in c6b7bbf7

---

Orange/classification/majority.py
Orange/classification/rules.py
Orange/tests/test_preprocess.py

On Python 3.6 `bytes(numpy.array([1,2]))` raises a 
TypeError: only integer scalar arrays can be converted to a scalar index
Fix this use in two places where sha1 digest of an array is requested, passing the array memory view directly to sha1 (if the arrays is c contiguous this also avoids a copy.

[FIX] Python 3.6 compatibility

---

Orange/statistics/util.py
Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/tests/test_owmosaic.py

[FIX] OWMosaic: Fix crash for attribute with no values

---

Orange/widgets/data/owfile.py
Orange/widgets/data/tests/test_owfile.py

https://sentry.io/biolab/orange3/issues/196743788/
The error also appeared when I tried to reproduce some unrelated bugs.
Check whether `last_path` is `None` before checking its size.

[FIX] File: Fix crash when last_path is None

---

Orange/widgets/data/owconcatenate.py
Orange/widgets/data/tests/test_owconcatenate.py

A naive attempt of preserving column order resulted in every
column in the intersection being repeated times the number of
inputs.
(ref gh-1943)

[FIX] owconcatenate: Fix domain intersection (remove duplicates)

---

Orange/widgets/gui.py

Fixes #1973
Add a "changed" flag to SpinBoxWFocusOut and DoubleSpinBoxWFocusOut classes.

[FIX] gui: Trigger callback in SpinBoxWFocusOut only if value changed

---

Orange/widgets/data/owimpute.py
Orange/widgets/data/tests/test_owimpute.py

Fixes gh-1920 and gh-1965
* Fix reseting of individual variable imputers back to default (gh-1920)
* Prevent global modification of OWImpute.METHODS
* Properly disable the 'Value' {Combo,Spin}Box for setting fixed replacement values
* Fix editing of per-variable specific replacement values (gh-1965)

[FIX] owimpute: Fix editing of individual imputers

---

Orange/evaluation/testing.py
Orange/widgets/evaluate/owcalibrationplot.py
Orange/widgets/evaluate/owconfusionmatrix.py
Orange/widgets/evaluate/owliftcurve.py
Orange/widgets/evaluate/owpredictions.py
Orange/widgets/evaluate/owrocanalysis.py
Orange/widgets/evaluate/tests/test_owcalibrationplot.py
Orange/widgets/evaluate/tests/test_owconfusionmatrix.py
Orange/widgets/evaluate/tests/test_owliftcurve.py
Orange/widgets/evaluate/tests/test_owpredictions.py
Orange/widgets/evaluate/tests/test_owrocanalysis.py
Orange/widgets/evaluate/utils.py

Most widget in evaluation category fail when presented either an empty Evaluation Results instance or one containing nan values. The source of these is in most cases the 'Predictions' widget.
* 'Predictions' widget filters out unknown values from the 'Evaluation Results' when the corresponding true target value is unknown
* Confusion Matrix, ROC Analysis, Lift Curve and Calibration plot widgets handle empty results
* Confusion Matrix, ROC Analysis, Lift Curve and Calibration plot widgets check for the presence of Nan values and bail out early with an error message.

[FIX] Evaluation Results input validation

---

Orange/data/table.py
Orange/tests/test_distribution.py

```python
import Orange.data
from Orange.statistics import distribution
domain = Orange.data.Domain(
[], [],
[Orange.data.StringVariable("S"),
Orange.data.DiscreteVariable("D", ["a", "b"])])
data = Orange.data.Table(domain, [["", 1], ["", float("nan")]])
distribution.get_distribution(data, domain.metas[1])
```
results in
```
File "<stdin>", line 10, in <module>
File "/Users/aleserjavec/workspace/orange3/Orange/statistics/distribution.py", line 295, in get_distribution
return Discrete(dat, variable, unknowns)
File "/Users/aleserjavec/workspace/orange3/Orange/statistics/distribution.py", line 39, in __new__
return cls.from_data(dat, variable)
File "/Users/aleserjavec/workspace/orange3/Orange/statistics/distribution.py", line 63, in from_data
dist, unknowns …
```

[FIX] Table: Ensure correct dtype in `_compute_distributions`

---

Orange/widgets/data/owpaintdata.py
Orange/widgets/data/tests/test_owpaintdata.py

Input
```
X1,X2,D
c,c,d
,,class
1,1,a
1,1,?
2,1,b
```
To Paint Data widget (i.e. an unknown in the class column)
-> On current master
```
File "/Users/aleserjavec/workspace/orange3/Orange/canvas/scheme/widgetsscheme.py", line 822, in process_signals_for_widget
handler(*args)
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owpaintdata.py", line 1029, in set_data
self.reset_to_input()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owpaintdata.py", line 1051, in reset_to_input
self._replot()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owpaintdata.py", line 1237, in _replot
pen = [pens[ci] for ci in self.__buffer[:, 2].astype(int)]
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owpaintdata.py", …
```

[FIX] owpaintdata: Fix an error when the input dataset contains NaN

---

.travis.yml
Orange/widgets/utils/classdensity.py

The density image (crashes) in scatterplot doesn't display with the latest version of pyqtgraph 0.10.
Change the dtype of the computed numpy array of pixel values to reflect the actual range of values and prevent "automatic" scaling (crashing) by pyqtgraph.

[FIX] scatterplot: Fix density image

---

Orange/widgets/data/owpaintdata.py
Orange/widgets/data/tests/test_owpaintdata.py

Fix a IndexError when the input dataset's class variable has more then 17 values.
```
File "/Users/aleserjavec/workspace/orange3/Orange/canvas/scheme/widgetsscheme.py", line 822, in process_signals_for_widget
handler(*args)
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owpaintdata.py", line 1029, in set_data
self.reset_to_input()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owpaintdata.py", line 1051, in reset_to_input
self._replot()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owpaintdata.py", line 1230, in _replot
pens = [pen(self.colors[i]) for i in range(nclasses)]
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owpaintdata.py", line 1230, in <listcomp>
pens = [pen(self.colors[i]) …
```

[FIX] owpaintdata: Adjust color model to input dataset

---

Orange/widgets/data/owselectrows.py
Orange/widgets/data/tests/test_owselectrows.py
Orange/widgets/tests/utils.py
Orange/widgets/utils/__init__.py

Fixes https://github.com/biolab/orange3/issues/1782
Replace locale-dependent `QDoubleValidator` with custom, hopefully correct regex validator.

OWSelectRows: locale-independent numeric value validation

---

Orange/widgets/unsupervised/owkmeans.py
Orange/widgets/unsupervised/tests/test_owkmeans.py

If k-means crashed, so does the widget.
The widget now catches exceptions. If k-means fails only for some k's, it still shows the table but disables the corresponding rows. If all fail (or optimization is disabled), it reports an error.
While fixing the table, I also changed the scaling for silhouette, so the the bars are not normalized according to minimal and maximal observed score but between 0 and 1.

[FIX] KMeans: Fix crashes when underlying algorithm fails

---

Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/evaluate/tests/test_owtestlearners.py

Fixes gh-1993
Fill in the probabilities in `results_one_vs_rest`.

[FIX] Test Learners: Fix AUC for selected single target class

---

doc/development/source/tutorial.rst

- Missing assignment `=` in code example.
- Missing ending square bracket of list in code example.
- Missing blank line after `.. code-block:: python` resulting with an invisible code example.
Added the above.

Fix some Orange Widget writing tutorial errors

---

Orange/classification/__init__.py
Orange/classification/sgd.py
Orange/regression/linear.py
Orange/tests/test_sgd.py
Orange/widgets/classify/tests/test_owsgd.py
Orange/widgets/model/owsgd.py
Orange/widgets/regression/tests/test_owsgdregression.py

Output coefficients for SGD classification and regression widgets
Use Orange preprocessors instead of sklearn Pipeline 
- fixes: https://sentry.io/biolab/orange3/issues/210510912/
Modify OWSGD ancestor to output coefficients

[ENH] OWSGD: Output coefficients

---

Orange/widgets/utils/__init__.py

Get rids of a RuntimeWarning when starting Orange
Import from AnyQt instead from PyQt4

[FIX] Import from AnyQt instead from PyQt4

---

Orange/tests/test_util.py
Orange/util.py

`repr()` on complex Reprable objects with reprable properties of `np.ndarray` (or similar array_like types) would  fail with standard
```text
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Make equality comparison more robust. Can't believe how hard it is in Python to equals-compare two object's values in a generic fashion!

util.Reprable: more generic equals (handle array_like types)

---

Orange/data/io.py
Orange/tests/test_tab_reader.py

Do not save the metadata file (when saving the data) if this is empty (0 Bytes)
Change if statement and add third condition. It implies that attribute should not be empty. Add test file to check if metadata is saved when empty

[FIX] data/io.py Metadata file not saved anymore when it is empty

---

Orange/widgets/data/owpreprocess.py
Orange/widgets/data/tests/test_owpreprocess.py

Due to 60e1369 the ContinuizeEditor raises an:
```
File "/Users/aleserjavec/workspace/orange3/Orange/canvas/scheme/widgetsscheme.py", line 454, in create_widget_instance
widget.__init__()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owpreprocess.py", line 1015, in __init__
self._initialize()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owpreprocess.py", line 1036, in _initialize
self.set_model(model)
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owpreprocess.py", line 1108, in set_model
self.controler.setModel(ppmodel)
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/utils/preprocess.py", line 265, in setModel …
```

[FIX] Preprocess Widget: Continuize type error

---

Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/tests/test_owheatmap.py

Remove 'Sorting' combo boxes and replace them with 'Clustering' check boxes.
When the check box is checked, 'Clustering with leaf ordering' should be used.

OWHeatMap: Replace 'Sorting' with 'Clustering'

---

Orange/widgets/classify/tests/test_owadaboostclassification.py
Orange/widgets/classify/tests/test_owclassificationtree.py
Orange/widgets/classify/tests/test_owknnclassification.py
Orange/widgets/classify/tests/test_owrandomforest.py
Orange/widgets/classify/tests/test_owsgd.py
Orange/widgets/model/tests/test_owsgd.py
Orange/widgets/regression/tests/test_owadaboostregression.py
Orange/widgets/regression/tests/test_owknnregression.py
Orange/widgets/regression/tests/test_owrandomforestregression.py
Orange/widgets/regression/tests/test_owregressiontree.py
Orange/widgets/regression/tests/test_owsgdregression.py
Orange/widgets/regression/tests/test_owsvmregression.py
Orange/widgets/tests/base.py

Problem in #1878 was not caught by tests. Also, we were not able to test parameters specific to classification/regression datasets.
Fixed both of the above mentioned problems. Due to changes, I also had to set `valid_datasets` in each learner. These tests will all be removed when learners are fully merged.

Tests for settings_changed and fitter params

---

Orange/evaluation/testing.py
Orange/regression/linear_bfgs.py
Orange/widgets/data/owdatasampler.py
Orange/widgets/visualize/owvenndiagram.py

Sklearn cross_validation module is deprecated and will be removed in 0.20, so module model_selection should be used instead.

testing: Use sklearn model_selection module instead of cross_validation module

---

Orange/widgets/unsupervised/owmds.py
Orange/widgets/unsupervised/tests/test_owmds.py

Exceptions in MDS optimization were not caught.
Now they are.

MDS: Catch MemoryError in MDS optimization

---

Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/tests/test_owsieve.py

… selected
KeyError thrown when only one row selected in data table.
KeyError fix - Handle the error and show the message on top of the widget.

[FIX] Handle KeyError Sieve Diagram widget (owsieve) when one row

---

Orange/data/io.py
Orange/widgets/data/owfile.py

https://github.com/biolab/orange3/issues/1997
Load *.metadata as UTF-8. Additionally, fix reporting filename and filetype in OWFile.

[FIX] Loading iris on C locale

---

Orange/widgets/data/owpaintdata.py

Paint Data started with an oversized window.
Apply wasn't on by default.
Widget window now resized to a smaller frame.
Auto-apply is a default.

Paint Data: autoapply and resize

---

Orange/canvas/application/application.py

Fixes #2009 when used with pyqt5. Does not seem to break anything on OSX. Could use some more testing on linux (@kernc @lanzagar) and windows (@ajda)

Enable HighDPI support

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/tests/test_owmosaic.py

KeyError thrown.
Discretizer parameter remove_const set to False. Add test case.

[FIX] Handle KeyError Mosaic Display (owmosaic.py)

---

Orange/widgets/_highcharts/orange-selection.js
Orange/widgets/highcharts.py
Orange/widgets/tests/test_highcharts.py
Orange/widgets/utils/webview.py

Highcharts froze on Qt5.
No longer freezes on Qt5 by passing a core object into JS by a different mechanism and at a different time.

[FIX] Highcharts: Fix freezing on Qt5

---

Orange/widgets/data/owmergedata.py
Orange/widgets/data/tests/test_owmergedata.py
Orange/widgets/visualize/owvenndiagram.py
Orange/widgets/visualize/tests/test_owvenndiagram.py

The widget should support two ways of producing output:
1. Merge data only by values that match - outputs inner join of the inputs
2. Merge all data - outputs outer join of the inputs
Use check box to distinguish between the two ways.
Fix appearance of missing values when metas are merged.

OWMergeData: Merge by matching data

---

Orange/widgets/utils/webview.py

If running on WebEngine the call to `setHtml` grabs focus and sets it to WebViewWidget. This is quite annoying behaviour when for example one would like to filter some data set and show the results in WebView. Due to WebViewWidget's focus grabbing the input filter looses focus after every character is typed.
Override `setHtml` to that the widget's state is first set to disabled, then call `super().setHtlm` and finally restore the initial state.

[FIX] WebviewWidget: WebEngine Don't Grab Focus on setHtml

---

Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/tests/test_owheatmap.py

AssertionError thrown or error message shown if Low >= High.
Prevent horizontal sliders to set Low >= High.

[FIX] owheatmap: Prevent sliders to set Low >= High

---

Orange/widgets/unsupervised/owdistancematrix.py

Labels from string attributes included unnecessary double quotes (e.g., "turtle" instead of just turtle)
No quotes after this fix.

[FIX] OWDistanceMatrix: Remove quotes with string labels

---

Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/tests/test_owsieve.py

Chi-squared test is nan when there are attributes which are not in the data. It is caused by division by zero because  code does not calculate limits. It actually suppose to be 0.

[FIX] Fix Chi2 computation for variables with values with no instances

---

Orange/widgets/data/owfile.py
Orange/widgets/data/tests/test_owfile.py
Orange/widgets/utils/domaineditor.py

PickleError thrown if a column does not have a name.
Column name cannot be changed to an empty string or a string with whitespaces.

[FIX] Prevent PickleError (owfile.py)

---

Orange/widgets/settings.py
Orange/widgets/tests/test_domain_context_handler.py

Variables are encoded as `name, type` pairs so there is no reason that anonymous variables could not be stored as settings.
The error was caused by calling copy.copy on all values, even those that would not be used in encoded representation.
copy only when necessary

DomainContextHandler: Encode anonymous variables

---

Orange/widgets/visualize/owtreeviewer.py
Orange/widgets/visualize/tests/test_owtreegraph.py

To reproduce: File (iris) -> Classification Tree -> Tree Viewer -> Select i.e. Iris-setosa (Target class combo) -> nodes texts remain unchanged (only color changes).
Change nodes text after Target class has changed

[FIX] OWTreeGraph: Update node text when selecting target class

---

Orange/widgets/model/tests/test_owadaboost.py

Re-enable the tests for ada boost widget now that #1968 is merged.

Tests OWAdaBoost: Add param tests for classification/regression data

---

Orange/base.py
Orange/classification/tree.py
Orange/modelling/base.py
Orange/regression/tree.py
Orange/tests/test_fitter.py
Orange/widgets/regression/tests/test_owadaboostregression.py
Orange/widgets/regression/tests/test_owsgdregression.py
Orange/widgets/regression/tests/test_owsvmregression.py
Orange/widgets/tests/base.py

Running fitters on large enough datasets through the test and score widget and setting it to cross validation would result in a stack overflow error.
I am not particularly sure why this happened, my theory is that when test and score receives a large enough dataset, it runs cross validation in parallel, and that the learner attributes were probably accessed statically and failing.
Unfortunately, I have no idea what caused this and how exactly it was called, so I don't really know how to test against this. But since I will most likely change this in the near future, I wouldn't spend too much time on this.
No longer rely on `self.kwargs` being on the object, but raise attribute error by explicitly getting `kwargs` with `__getattribute__`.

[FIX] Fitter: Fix infinite recursion in __getattr__

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/tests/test_owmosaic.py

Widget crashes if the columns are empty.
To reproduce: Connect data to Select Columns. Remove features, target variable and meta attributes. Connect to Mosaic Display.
Added an extra check in in set_data().

[FIX] OWMosaic:  Fix crash for empty column

---

Orange/widgets/visualize/owsilhouetteplot.py

After selecting instance/s, move the selection using Up and Down keys.

OWSilhouettePlot: Use Up and Down keys to move selection

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/tests/test_owmosaic.py

ZeroDivisionError is thrown when invalid data is loaded into widget. For instance: [[0, NaN], [NaN, NaN]].
https://sentry.io/biolab/orange3/issues/204400244/
If the value "total" is zero aborts drawing the plot.

[FIX] ZeroDivisionError owmosaic.py

---

Orange/canvas/application/addons.py
Orange/canvas/application/tests/test_addons.py

Names in addon dialog should be nicer.
Remove Orange/Orange3 from addon names and add spaces before upper letters to separate words of the name.

addons: Show nicer names in addon dialog

---

Orange/widgets/_highcharts/orange-selection.js
Orange/widgets/highcharts.py
Orange/widgets/io.py
Orange/widgets/tests/base.py
Orange/widgets/tests/test_highcharts.py
Orange/widgets/utils/tests/test_webview.py
Orange/widgets/utils/webview.py

Of note:
* raise selected Highcharts points to front, and
* always suffix the evaluated JS code with `";0"` to avoid failing to interpret arbitrary complex objects the user's JS expression can evaluate to, and
* export SVG as SVG instead of HTML, and
* have `WidgetTest.wait_for()` that comes in handy with async GUI testing.

Highcharts+WebView minor updates

---

Orange/widgets/data/owselectrows.py
Orange/widgets/data/tests/test_owselectrows.py

Conditions in select rows are not loaded properly when reading from file (gh-2062)
Make sure the correct ordering of variables is used when restoring conditions.

[FIX] SelectRows: Fix loading of conditions

---

Orange/widgets/visualize/owdistributions.py
Orange/widgets/visualize/tests/test_owdistributions.py

File -> Select columns -> Distributions
Load Iris, move one of the (continuous) attributes to meta attributes and select it in the Scatter plot. Instead of that attribute, the scatter plot shows the class.
The first problem is that the attribute was selected incorrectly - as the first attribute in domain + metas. When the grouping attribute was an ordinary attribute and the shown attribute a meta, this resulted in showing the grouping attributes.
The second problem is that discretization classes do not discretize meta attributes.
Construct the table for discretization so that the attribute that has to be discretized always appears as a normal attribute.

[FIX] OWDistributions: Fix binning of meta attributes

---

Orange/clustering/kmeans.py
Orange/widgets/unsupervised/owkmeans.py

- widget crashes with a memory error on large datasets (e.g., adult)
- auto-commit doesn't work (disabling it has no effect)
- compute silhuette score on a sample of at most 5000 instances
- remove connections of apply() before calling auto_commit

[FIX] OWKMeans: Auto-commit fix and silhuette optimization

---

Orange/widgets/data/tests/test_owfile.py
Orange/widgets/utils/domaineditor.py

ValueError  - could not convert string to float: '02.02.17'
https://sentry.io/biolab/orange3/issues/196743724/
Datetime option only if numerical.

[FIX] File: Disallow changing string columns to datetime

---

Orange/widgets/data/owpreprocess.py
Orange/widgets/data/tests/test_owpreprocess.py
Orange/widgets/tests/base.py

ZeroDivisonError - Weights sum to zero, can't be normalized
In case when all rows in a column are NaN then it throws that error.
https://sentry.io/biolab/orange3/issues/227119466/
Add another except in try block and now it shows an error message in the widget.

[FIX] owpreprocess: Handle columns with only NaN values

---

Orange/classification/logistic_regression.py

Parameters of the wrapped scikit-learn method were outdated and missing e.g. multi_class treatment.
Sync parameters with latest version of sklearn. Only warm_start is omitted as that does not work in Orange wrappers (new instance is created in Learner).
No changes to GUI for now, although we might want to consider adding some options to the widget in the future.

logistic_regression: Expand parameter list

---

Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owscatterplotgraph.py
Orange/widgets/visualize/tests/test_owscatterplot.py

ValueError cannot convert float NaN to integer owscatterplot
In case when all column values are NaN then it throws that error.
https://sentry.io/biolab/orange3/issues/196744604/
Logarithm of zero and division by zero are prevented.

[FIX] ScatterPlot: Fix crash when coloring by column of unknowns

---

Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/tests/test_owheatmap.py

Invalid number of variable columns
Columns in a domain and in a table do not match.
https://sentry.io/biolab/orange3/issues/196744285/
If a column in a table is dropped, it is erased in a domain as well.

[FIX] Heatmap: Fix crash on data with empty columns

---

Orange/__init__.py

Orange install backport hooks for Qt4 in __init__ which
mess up pyqtgraph Qt dection. Importing pyqtgraph before
installing importhooks fixes this.

Fix pyqtgraphs Qt5 detection after importing Orange

---

Orange/data/table.py
Orange/tests/test_xlsx_reader.py

Allow choosing sheets when constructing a Table

---

Orange/modelling/base.py
Orange/tests/test_fitter.py

[FIX] Fitter: Properly delegate preprocessors

---

.travis/build_doc.sh

The docs building script didn't correctly recognize non-indexed images (see for example _Nomogram-LogisticRegression.png_ in [#2016](https://github.com/biolab/orange3/pull/2016/files#diff-ccb8318320da1f9b2bf947f0534d2c27)). Not certain why it failed as it worked locally.
Whitelist instead of blacklist. Now should work. Tested in https://travis-ci.org/kernc/orange3/jobs/208991228.

build_doc: fix recognizing RGB images in docs

---

Orange/widgets/tests/datasets/same_entropy.tab
Orange/widgets/visualize/owtreeviewer2d.py
Orange/widgets/visualize/tests/test_owpythagorastree.py
Orange/widgets/visualize/tests/test_owtreegraph.py

OWTreeViewer was not deterministic in showing trees. This was not specific to trees where attributes had the same entropy or whatever the selection criteria was, but occured on any tree (even with iris).
This happened because the layout was updated w.r.t the graph node edges, which were stored in a set object, which is unordered.
I assume that a set was used because speed is important, so I've implemented edges as an ordered dict, to keep the speed benefits as well as getting an ordering.
I've written a test that draws the tree 10x and compares the node positions, but since the ordering of the nodes was completely random before, this is not guaranteed to fail in case the trees are drawn with random ordering. The ordering could *happen* to be the same 10x. This hasn't actually happened to …

[FIX] OWTreeViewer: Fix trees being displayed differently for same tree object

---

Orange/widgets/unsupervised/owcorrespondence.py
Orange/widgets/unsupervised/tests/test_owcorrespondence.py

1) IndexError: index 1 is out of bounds for axis 1 with size 1
2) SVD did not converge
3) Must specify at least one of rect, xRange, or yRange. (gave rect=<class 'NoneType'>)
Check that the widget does not crash when domain has a discrete variable with only one value.
Discrete variables with only one value are not taken into account.

[FIX] owcorrespondence: Handle variables with one value

---

Orange/widgets/settings.py
Orange/widgets/tests/test_settings_handler.py

Clear settings, open canvas, add file widget, close, then open canvas again (to ensure that there are some stored settings).
Put two instances of file widget, select different file in each, save workflow, open workflow. Both widgets have the same file selected.
Also fixes #2030
Copy mutable default values before setting them to widget.

Settings: Copy mutable default values

---

Orange/canvas/report/index.html
Orange/canvas/report/owreport.py

Fixes https://github.com/biolab/orange3/issues/1899
Not sure what the problem was re comments. Removing `required=required` in HTML now works for me. in OWFile, `self.loaded_file` is now correctly set when the file is loaded, not when browsed for.

[FIX] report comments and OWFile reporting filename

---

Orange/data/io.py
Orange/tests/test_io.py

For one file format I would like to match extension ".[0-9]*" and this allows it.

File formats: wildcard matching

---

Orange/widgets/data/owselectrows.py
Orange/widgets/data/tests/test_owselectrows.py

The widget issues a warning "need more than 0 values to unpack".
Given a data set the widget would be able to select only instances where the value of some attributes are defined.
#2054
And third column in a row is not disabled when selected "is defined".

[FIX] Select Rows: "is defined" fails

---

Orange/widgets/visualize/owdistributions.py
Orange/widgets/visualize/tests/test_owdistributions.py

Fixes https://sentry.io/biolab/orange3/issues/232048055/
The widget crashed when variable (or group) with only missing values was selected.

OWDistributions: Fix crash for feature with no values

---

Orange/canvas/application/workflows/__init__.py
Orange/canvas/help/manager.py
Orange/canvas/registry/discovery.py
requirements-core.txt

When one of the requirements (of their requirements (or their requirements...)) is missing, Orange opens with no widgets.
To reproduce, uninstall keyring and open canvas
use .resolve() to load entry points
.resolve() is available from setuptools 11.3 forward (released in 2015),
does the same thing as .load(), but ommits the requirements check.

[FIX] Discover widgets when some dependencies are missing

---

Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/data/tests/test_owfeatureconstructor.py

Feature constructor silently ignored variables starting with numbers.
Variable names starting with a number are prefixed with a "_" so that we get a valid ast. Also added error reporting when expressions are not valid.

Feature constructor works with variables starting with numbers

---

Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/tests/test_owsieve.py

Widget should intepret meta data which are continuous or discrete in the same way
as features or target.
https://sentry.io/biolab/orange3/issues/231234770/
https://sentry.io/biolab/orange3/issues/232101010/

[FIX] Sieve Diagram: Using datasets with meta data

---

Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/tests/test_owscatterplot.py

Widgets crashes when table is None.
https://sentry.io/biolab/orange3/issues/196744557/

[FIX] Scatter Plot - Prevent crash due to missing data

---

Orange/widgets/gui.py

TableBarItem ignored ColorRole and always used the class color (or nothing).
The delegate now first tests whether it can use class colors, next it uses BarColorRole, otherwise it uses the default color.

gui.TableBarItem: Enable BarColorRole

---

Orange/distance/__init__.py
Orange/tests/test_distances.py
Orange/widgets/unsupervised/owdistances.py
Orange/widgets/unsupervised/tests/test_owdistances.py

Mahalanobis distance (intentionally) didn't work when the number of features exceeded the number of samples.
The restriction doesn't seem to be applicable anymore.
Added error handling of too large and singular covariance matrices.

Mahalanobis: Remove dimension restrictions.

---

Orange/tests/__init__.py
Orange/widgets/data/owfile.py
Orange/widgets/data/tests/test_owfile.py
Orange/widgets/settings.py

When files with similar domain (same variable names, different values of discrete vars) were opened, domain editor always showed values from the first opened file.
Fixes gh-2132
ContextHandler now takes variable's values in account.

[FIX] Fix invalid settings reuse in File widget 

---

Orange/classification/sgd.py
Orange/regression/linear.py
Orange/tests/test_sgd.py

SGD did not have correct default parameters. See sklearn docs for [classification](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html) and [regression](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor.html)

SGD: Fix default loss parameter

---

Orange/modelling/base.py
Orange/modelling/linear.py
Orange/tests/test_fitter.py

[FIX] Fitter: Change params uses default if None

---

Orange/widgets/data/tests/test_owfile.py

Datetime option only if numerical. Test only.
#2050

Test File: Disallow changing string columns to datetime

---

Orange/widgets/visualize/owdistributions.py

Distributions Report: Visualizations are now fitted to take a normal amount of space
Visualizations in report sometimes take too much space - extensive white space above visualization.
#2040

[FIX] Distributions Report: Visualizations are now fitted

---

Orange/widgets/visualize/utils/__init__.py

[FIX] VizRankDialog: Stop computation when parent widget is deleted

---

Orange/modelling/ada_boost.py
Orange/modelling/base.py
Orange/modelling/knn.py
Orange/modelling/linear.py
Orange/modelling/neural_network.py
Orange/modelling/randomforest.py
Orange/modelling/svm.py
Orange/modelling/tree.py
Orange/tests/test_fitter.py

#2125 6.
Since this is probably a pretty important bug, here is a quick fix that takes care of that. I've realised that a there is no particularly simple fix as discussed in #2128 but requires more thought. In the meantime, this should work. Also, I see no easy way to test this.
I've also removed the metaclass that checked that the fitters had their `__fits__` property set properly, which is kind of silly.

[FIX] Fitter: Fix used_vals and params not being set

---

Orange/data/table.py
Orange/widgets/visualize/tests/test_owmosaic.py
Orange/widgets/visualize/utils/__init__.py

When (at least) two VizRank dialogs are running (i.e. the calculations has not finished), only one is actually performing the calculations because they live in the same thread.
To reproduce: File(geo-gds360) -> two parallel ScatterPlots (Find Informative Projections -> Start)
Make dialogs work simultaneously by putting them in separate threads.

VizRankDialog: Support execution of multiple widgets at the same time

---

Orange/widgets/visualize/pythagorastreeviewer.py

When viewing larger trees, especially regression trees, the square borders would scale along with the zoom, and would appear almost invisible. On the other hand, zooming in close would make the border very bulky.
The border is now scale invariant.
Before (random forest on Boston housing prices dataset):
After:

[ENH] Pythagorean tree: Make border scale invariant

---

Orange/preprocess/preprocess.py

When loaded schema from file, function names are loaded as integers. That is why functions cannot be called anymore (int is not callable).
https://sentry.io/biolab/orange3/issues/227119437/
Enums in Scale preprocess now saved as string and not as int anymore.

[FIX] Preprocess: enums containing function names changed

---

Orange/widgets/data/oweditdomain.py
Orange/widgets/data/owimageviewer.py
Orange/widgets/data/owimpute.py
Orange/widgets/data/owpreprocess.py
Orange/widgets/data/owpurgedomain.py
Orange/widgets/data/owpythonscript.py
Orange/widgets/data/owselectcolumns.py
Orange/widgets/data/tests/test_owpythonscript.py
Orange/widgets/unsupervised/owdistances.py
Orange/widgets/unsupervised/owdistancetransformation.py
Orange/widgets/visualize/owsilhouetteplot.py

All widgets are set to autocommit/autoapply/autosend/autoexecute when they are used for the first time.
Python Script test changed.
GH-2038

[FIX] All widgets are set to auto* when they are used for the first time

---

Orange/classification/random_forest.py
Orange/regression/random_forest.py
Orange/widgets/tests/utils.py
Orange/widgets/visualize/owpythagorastree.py
Orange/widgets/visualize/owpythagoreanforest.py
Orange/widgets/visualize/owtreeviewer.py
Orange/widgets/visualize/pythagorastreeviewer.py
Orange/widgets/visualize/tests/test_owpythagorastree.py
Orange/widgets/visualize/tests/test_owpythagoreanforest.py
Orange/widgets/visualize/utils/owlegend.py
Orange/widgets/visualize/utils/tree/skltreeadapter.py
Orange/widgets/visualize/utils/tree/tests/test_treeadapter.py
Orange/widgets/visualize/utils/tree/treeadapter.py

Some of the Pythagrean tree and Pythagorean forest code was written very poorly with some duplication and poor handling of continuous vs discrete target classes.
Pretty major refactoring to remove all the duplicated code as well as several small fixes that were discovered along the way.
- Add `callback` to qt testing utilis `combobox_run_through_all` that enables us to call a function after the combobox changes to perform additional checks.
- Remove all the `tree_specific` stuff in the tree and forest in favour of more oop code so that messy callbacks are not needed.
- Make the `TreeAdapter` simpler by allowing it to store the data. This makes sense because since all the models have the data they were trained on, there really is no reason to complicate the adapter.
- Forest: Hide the …

Pythagorean trees: Refactor

---

Orange/widgets/utils/progressbar.py

Use a sane default and do not call QApplication.processEvents in the ProgressBarMixin.
(ref gh-2184)

ProgressBarMixin: Change the default processEvents parameter

---

Orange/widgets/evaluate/owpredictions.py
Orange/widgets/evaluate/tests/test_owpredictions.py

`OWPredictions` reported mismatching targets if the data had not target column (#2148).
This occurred because the data's `class_var` was `None`, and it was thus not the same as the target of predictors.
The widget's `self.class_var` is now set from the target of the models. All models must have the same target. Also, if the data has a target, it has to be the same as the models' target.
This required several other changes in the widget to cope with situations that could not occur previously.

[FIX] OWPredictions: Allow classification when data has no target column

---

Orange/canvas/application/addons.py

Critical error: add-ons installation does not work anymore. Probably due to the changes on the server side. It neither works in Orange 3.3.8.

[FIX] Add-ons: Problems with datetime parsing

---

Orange/widgets/data/owselectcolumns.py
Orange/widgets/tests/test_owselectcolumns.py

A box for Target variables is too small.
When one target variable is moved somewhere else, it cannot be moved  back if there is already one target variable.
#2086

Select Columns: multiple target variables problems

---

Orange/widgets/data/owrank.py
Orange/widgets/data/tests/test_owrank.py

Sometimes Rank calculates infinite values. Those cannot be put in Table.
https://sentry.io/biolab/orange3/issues/222918568/

[FIX] Rank: fixes creating Table with infinite numbers

---

Orange/widgets/utils/plot/owplotgui.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/tests/test_owlinearprojection.py
Orange/widgets/visualize/tests/test_owscatterplot.py

Several widgets (ScatterPlot, LinearProjection, MDS, Map, FreeViz) has similar control area, especially Points box. They should all use components created by OWPlotGUI.
Make Points box usable for any widget.

OWPlotGUI: Make Points box reusable

---

Orange/statistics/util.py

[FIX] stats: Open Corpus in OWDataTable after transposing it

---

Orange/widgets/model/owlogisticregression.py
Orange/widgets/model/tests/test_owlogisticregression.py

I can handle unused values
and instead of writing "coef" or sth similar I write a second value name
when only two values are considered.
https://sentry.io/biolab/orange3/issues/222366525/
https://sentry.io/biolab/orange3/issues/208659372/

[FIX] Widget Logistic Regression: can handle unused values

---

Orange/widgets/evaluate/owtestlearners.py

When Test & Score performs evaluation sb might disconnect connection from some learner. Widget then crashes.
https://sentry.io/biolab/orange3/issues/227231658/

[FIX] Test & Score: crashing prevented when learner disconnects

---

Orange/widgets/visualize/ownomogram.py
Orange/widgets/visualize/tests/test_ownomogram.py

[FIX] OWNomogram: Do not paint scene until the widget is not open

---

Orange/evaluation/testing.py
Orange/tests/test_evaluation_testing.py
Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/evaluate/tests/test_owtestlearners.py

Add type of CV where number of feature values determines number of folds.
Use only discrete meta features.
Add radio button option to select this type of CV.
Add combo box to select feature to give nr. of folds.
Documentation comes when gui is approved.

[ENH] OWTestLearners: Cross validation by feature

---

Orange/widgets/visualize/owmap.py

* don't fly to bounds if same domain (545882d couldn't have ever worked)
* zero-length data is no data

OWMap: fixes

---

Orange/widgets/evaluate/owpredictions.py
Orange/widgets/evaluate/tests/test_owpredictions.py

Widget throws an error similar to "index 1 is out of bounds for axis 0 with size 1". That occurs when predictions which are sent to Predictions widget are made from a data with different domain than a domain which is also sent to that widget. For instance, predictions predict only two possible target values but the data has also a third value.
https://sentry.io/biolab/orange3/issues/223474227/
https://sentry.io/biolab/orange3/issues/216151441/
Predictions table is extended to match the number of the data target's values.

[FIX] Predictions widget: handle similar but different domains

---

Orange/widgets/utils/webview.py
Orange/widgets/visualize/owmap.py

Waiting for execution to complete was handled in an unsafe way. As all
js executions set the same flag when they were done, it was possible
that multiple executions set the flag before the thread waiting for them
could have noticed it. As a result, if two or more executions ended at
the same time the first waiting thread to notice that would clear the
flag and remaining threads would keep waiting indefinitely.
To reproduce, try run visualization widget tests on my computer :)    
Track each scheduled execution separately

 WebviewWidget: avoid hangs with webengine

---

Orange/widgets/visualize/owscatterplot.py

[FIX] Scatter Plot: left margin (axis y) is now adapting

---

Orange/widgets/data/oweditdomain.py
Orange/widgets/data/tests/test_oweditdomain.py

Edit Domain enables us to write duplicate names and that should be allowed. However user should be informed about that.
#2143
User is warned when writing a duplicate name. Also, empty spaces are removed in the beginning and in the end of a new name.

[FIX] Edit Domain: Prevent duplicate variable names

---

Orange/widgets/unsupervised/owhierarchicalclustering.py

Meta attributes used for annotation were not saved in settings.
Allow meta attributes

OWHierarchicalClustering: Use meta attributes in settings

---

Orange/canvas/application/canvasmain.py
Orange/canvas/application/schemeinfo.py

[ENH] Canvas: Use 'windowFilePath' to display display current filename instead of the title

---

Orange/widgets/visualize/utils/owlegend.py

PyQt5 tests have been segfaulting occasionally. The culprit was sizeHint method, which crased from some reason. I cannot reproduce the exact problem, but I can move the code that computes the sizehint to __init__, where it will not segfault if it crashes.

owlegend: avoid computation in sizeHint

---

.ci_tools/appveyor/step-build.ps1
.ci_tools/appveyor/step-install.ps1
.ci_tools/appveyor/step-test-miniconda.ps1
.ci_tools/appveyor/step-test.ps1
appveyor.yml

$host.SetShouldExit() does not end the execution imediatelly, making it
hard to figure out what went wrong when one of the eary build
steps/tests fails.

appveyor: replace $host.SetShouldExit() with throw

---

Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owscatterplotgraph.py
Orange/widgets/visualize/tests/test_owscatterplot.py

Rank Informative projections with regard to the color variable
Scatter plot's find informative projections currently uses the class_variable to rank different projections. This should be modified to use the variable selected in color instead.
#2037

Scatter Plot: Rank Informative projections & color variable

---

Orange/widgets/unsupervised/owkmeans.py
Orange/widgets/unsupervised/tests/test_owkmeans.py

When there is less rows in a data than selected (from - to, second option) the widget crashes. 
https://sentry.io/biolab/orange3/issues/235248479/

[FIX] KMeans: should not crash when there is less data rows than k

---

Orange/projection/pca.py
Orange/widgets/unsupervised/owpca.py
Orange/widgets/unsupervised/tests/test_owpca.py

When changing number of components to a value which was higher
then components shown the variance was incorrect.

owpca: fix variance shown when changing ncomponents

---

.travis.yml
.travis/stage_after_success.sh

Our build on travis uploads coverage multiple times, resulting in weird changes in coverage (depending on the order of execution of builds).

travis: Avoid multiple uploads of coverage report

---

Orange/widgets/io.py
Orange/widgets/tests/test_io.py
Orange/widgets/utils/saveplot.py

Add PDF format to image exporters

[ENH] Add PDF format to image exporters

---

Orange/data/util.py
Orange/statistics/util.py
Orange/tests/test_statistics.py
Orange/widgets/visualize/ownomogram.py

#2165
* Statistics.utils: `nanmin`, `nanmax`, `average`, `unique` equivalents of numpy's that support sparse or dense matrices.
* SharedComputeValue: add variable attribute.
* Support nomogram on sparse data.
* Some speedups for nomogram. Time measured on a small BoW data set of shape (140, 3000):
*  `reconstruct_domain` method: 3.0s -> 0.03 s
* `calculate_log_reg_coefficients` method: TLDW (minutes+)  -> 1.5 s

[ENH] Nomogram: Support for sparse data

---

Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/tests/test_owscatterplot.py

[FIX] Scatterplot crashes when loaded from old workflow

---

Orange/widgets/settings.py
Orange/widgets/tests/__init__.py
Orange/widgets/tests/test_highcharts.py
Orange/widgets/tests/test_settings_handler.py

Sometimes settings cannot be saved due to file permission issues.
https://sentry.io/biolab/orange3/issues/242461786/
try block

[FIX] Permission error when saving settings

---

Orange/widgets/tests/base.py
Orange/widgets/unsupervised/owmds.py
Orange/widgets/unsupervised/tests/test_owmds.py
requirements-gui.txt

On Qt5 the widget does not visually update during optimization.
Change update scheduling to use a single shot timer instead of a custom event.

[FIX] FIX MDS widget update scheduling

---

Orange/widgets/unsupervised/owmanifoldlearning.py
Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py

https://sentry.io/biolab/orange3/issues/210202559/
Sometimes singular matrix is calculated from input data and that is now handled.

[FIX] Manifold Learning: handling numpy LinAlgError

---

Orange/widgets/utils/webview.py

When loading schemas with widgets that extend `Orange.widgets.highcharts.Highchart` Orange sometimes hangs with JS error:
```
js: Uncaught ReferenceError: fixupPythonObject is not defined
```
`WebEngineView._onloadJS` also calls `self.page().scripts().insert(script)` and not just connects it to `self.loadStarted`. In case that loading has already started (e.g. if WebEngineView receives QUrl among parameters to __init__) connecting of `self.loadStarted` occurs too late.

[FIX] WebEngineView: Insert JS if loading already started

---

Orange/widgets/unsupervised/owcorrespondence.py
Orange/widgets/unsupervised/tests/test_owcorrespondence.py

Widget crashes on discrete attributes with only one value.
https://sentry.io/biolab/orange3/issues/243133261/
Check if there is a second value.

[FIX] Correspondence: Prevent crashing when cont attr has one value

---

Orange/data/io.py
Orange/tests/test_io.py

https://sentry.io/biolab/orange3/issues/208584693/
Raise TypeError when PickleReader reads a pickle file without a table (and it suppose to be there).

[FIX] File: Raise and handle Exc. when file bad pickle

---

Orange/canvas/application/addons.py

https://sentry.io/biolab/orange3/issues/252756389/

[FIX] Add-ons: Handling ValueError due to connection problems

---

Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owscatterplotgraph.py
Orange/widgets/visualize/tests/test_owscatterplot.py

Orange add-on "Text mining" sends "Corpus" instead of "Table". "Corpus" uses sparse matrices and numpy hstack does not know how to handle them. That is why scipy sparse matrix is converted into numpy array.
https://sentry.io/biolab/orange3/issues/243775748/
Fixes #2157.

[FIX] Scatter Plot: dealing with scipy sparse matrix

---

Orange/widgets/data/owcontinuize.py
Orange/widgets/data/tests/test_owcontinuize.py

Crashing prevented when dealing with a column with NaN or equal values
and choosing option normalize by standard deviation or by span.
https://sentry.io/biolab/orange3/issues/242520198/
https://sentry.io/biolab/orange3/issues/227119466/
https://sentry.io/biolab/orange3/issues/242519777/

[FIX] Continuize: prevent crashing - column with equal and NaN values

---

Orange/statistics/util.py
Orange/widgets/data/owfile.py
Orange/widgets/data/tests/test_owfile.py
Orange/widgets/utils/domaineditor.py

Fixes #2188.
Enhance `DomainEditor.get_domain` to handle sparse data. Also instead of returning a list of columns' the method itself merges them to appropriate `X`, `y` and `meta` arrays.

[FIX] Support Sparse Data in Domain Editor

---

Orange/widgets/evaluate/owtestlearners.py

[FIX] Test & Score: Instantly recognize new input

---

Orange/widgets/tests/base.py
Orange/widgets/utils/webview.py

Tests sometimes freeze, restart usually helps.
Add timeouts to blocking operations, raise TimeoutError after a predetermined amount of time passes. This way the test results will show which tests are problematic and we can consider changing, skipping, or removing them.

Avoid random tests stalling

---

Orange/misc/cache.py
Orange/tests/test_misc.py

`.cache_clear()` / `.cache_info()` were not exposed on methods memoized with `misc.cache.memoize_method()`.
Expose by refactoring. Hope it's correct.

misc.cache.memoize_method: expose cache_clear() on memoized method

---

Orange/widgets/data/owpaintdata.py

No extra labels are saved when class has more than two values.

[FIX] Paint Data: Save and load labels

---

Orange/widgets/data/owpreprocess.py

Add missing feature selection methods to OWPreprocess

[ENH] Add all available methods to feature selection preprocessor

---

Orange/canvas/report/owreport.py
Orange/canvas/report/tests/test_report.py

https://sentry.io/biolab/orange3/issues/251030241/
Now shows a windows with error message and logs error as well.

[FIX] Report: handle PermissionError when trying to save

---

.travis/stage_after_success.sh
Orange/data/table.py
Orange/tests/test_table.py

Table throws error when trying to compare string values. A string value written in Select Rows widgets and a numerical value which is set as string.
https://sentry.io/biolab/orange3/issues/244859655/
Put _File_ and _Select Rows_ widgets and connect them. Then open _iris_. Set one of four features to _string_ and _meta_. Then choose that feature in _Select Rows_ and choose filter "_is before_" or some other one.

[FIX] Select Rows and Table: Filtering string values

---

CONTRIBUTING.md
Orange/evaluation/scoring.py
Orange/evaluation/testing.py
Orange/regression/tree.py
Orange/widgets/widget.py
doc/data-mining-library/source/conf.py
doc/data-mining-library/source/reference/data.variable.rst
doc/development/source/conf.py
doc/development/source/gui.rst
doc/development/source/tutorial-cont.rst
doc/development/source/tutorial-settings.rst
doc/visual-programming/source/widgets/unsupervised/manifoldlearning.rst
doc/visual-programming/source/widgets/visualize/linearprojection.rst
doc/visual-programming/source/widgets/visualize/nomogram.rst

When building documentation, lots of warnings are shown. Some resulted in badly rendered documentation (see lists in [manifold learning docs](https://docs.orange.biolab.si/3/visual-programming/widgets/unsupervised/manifoldlearning.html))
Fix most of the warnings.
What remains are warnings that are caused by "including" scikit-learn descriptions that contain references to labels in their user guide. We need to either inter-sphinx properly or remove those links.

Fix multiple warnings in documentation

---

Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/evaluate/tests/test_owtestlearners.py

We may want to add more scorers in the future, but we'd like to keep the widget simple. This PR allows the user to choose the columns by right-clicking in the top header.

[ENH] Test and Score: Allow choosing columns

---

Orange/data/io.py
Orange/tests/test_tab_reader.py
Orange/tests/test_table.py

Fixes a bug when meta data is removed, data saved. In this case the old meta
data file still exists and will be loaded the next time the data is opened.

Remove .metadata file if meta data is removed

---

Orange/widgets/visualize/owtreeviewer.py

Tree Viewer crashes when Target Class combo selected index number is higher than actual number of class values.
https://sentry.io/biolab/orange3/issues/205702715/

[FIX] Tree Viewer: check if there is selected class value

---

Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/evaluate/tests/test_owtestlearners.py

Old settings were not migrated correctly (`context_settings` might not be saved/exist)
Drop old/incompatible `context_settings` instead of modifying them.

[FIX] owtestlearners: Fix migration of old settings

---

pylintrc

- `no-len-as-condition` is triggered by our common idiom `if data is None or not len(data)`. We should either disable the warning or decide to use `if data is None or len(data) == 0`. I think disabling the warning is OK since we are not (mis)using `if len(s):` instead of `if s`, but changing the code instead is OK for me, too.
- `no-else-return` is triggered by `else`'s in code like
```
def compute_score(self, results, target=None):
if target is None:
if len(results.domain.class_var.values) <= 2:
return self.from_predicted(results, skl_metrics.f1_score, average='binary')
else:
return self.from_predicted(results, skl_metrics.f1_score, average='weighted')
else:
return np.fromiter(
(skl_metrics.f1_score(results.actual, predicted, average=None)[target]
for predicted in results.predicted), …
```

[RFC] Lint: disable no-else-return, len-as-condition

---

Orange/preprocess/fss.py
Orange/preprocess/score.py

As we discussed in #2205, features selection in the Preprocess widget shows ugly error messages. This happens since it shows exceptions raised by `preprocess.score.Scorer`, which are, in turn, in need of improvement.
This PR makes the exceptions issued by `preprocess.score.Scorer` presentable.
I think we should not do this in general since exceptions are for programmers and error messages in the widgets are for the end-user, so the former have to be exact and technical, including the type names etc, while the latter favour readability over exactness.
A check in `preproces.fss` is removed since it is also done in `preprocess.score.Scorer`.
No additional tests are needed.

preprocess.score.Scorer: Improve error messages

---

Orange/widgets/data/oweditdomain.py

Enter key resets the names and does not accept a new name.

Edit Domain: enter key accepts a name

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/tests/test_owmosaic.py

Mosaic plot uses only class variable to color the visualization.
#2036 
A new option added to the control area that allows the user to change the variable used for coloring. It defaults to class_var when it is available.

[ENH] Mosaic: Selectable color variable

---

.codeclimate.yml

codeclimate is stricter when checking radon complexity that our existing script
Allow both A and B methods in radon check.

codeclimate: relax radon check

---

Orange/base.py
Orange/tests/test_util.py

Fixes https://github.com/biolab/orange3/issues/2275
`patch.object()` (why was that used anyway?) didn't correctly restore _params_ key.
Use `patch.dict()` instead.

Fix subsequent repring of SklLearner

---

Orange/base.py
Orange/tests/test_base.py

Models store a pointer to the original training set. This can be huge and causes problems when pickling/unpickling.
Skip `original_data` when pickling `Model`s.

Model: Do not pickle stored data

---

Orange/base.py
Orange/canvas/scheme/signalmanager.py
Orange/distance/__init__.py
Orange/evaluation/testing.py
Orange/preprocess/preprocess.py
Orange/projection/base.py
Orange/projection/cur.py
Orange/projection/manifold.py
Orange/tests/test_distances.py
Orange/tests/test_evaluation_testing.py
Orange/tests/test_fitter.py
Orange/util.py
Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/evaluate/tests/test_owtestlearners.py
Orange/widgets/model/owrules.py
Orange/widgets/unsupervised/owdistances.py
Orange/widgets/unsupervised/tests/test_owdistances.py
Orange/widgets/utils/concurrent.py

Test & Score is non-interactive
Run the evaluations in a thread (not that Orange would be particularly thread-safe - at the very least DiscreteVariable's values can change during a run)
Other changes:
* Make SklImpute thread safe.
* Change Reprable implementation to allow thread safe use (remove all uses of `mock.patch` (??))
* Remove inplace modification of the learner sent from owrules (after already being sent)
* Remove instance modifications in manifold.py to make it thread safe (in some cases even just for repeated sequential use).
* Make the {Learner,Projector}.domain a property utilizing thread local storage behind the scenes. This is to work around a non thread-safe API design.
* Disable the global `distance.Mahalanobis` instance.

Test & Score: Offload evaluations to a separate thread

---

Orange/widgets/data/owpythonscript.py
Orange/widgets/data/tests/test_owpythonscript.py

Various errors reported by sentry. A user can write a code which sends data in incompatible or inappropriate variables. For instance it can send `String` instead of `Table` and that causes some other widget to crash.
Only proper variables are sent.

Python Script: Check for types of output variables

---

Orange/projection/manifold.py
Orange/widgets/unsupervised/owmanifoldlearning.py
Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py

Fixes https://github.com/biolab/orange3/issues/2158
Support sparse with method=t-SNE and tweaked params.

[ENH] OWManifold: support t-SNE on sparse

---

Orange/data/table.py
Orange/data/util.py
Orange/tests/test_table.py
Orange/tests/test_util.py
Orange/widgets/data/owconcatenate.py
Orange/widgets/utils/annotated_data.py

Add support for sparse tables to Table.concatenate. Fixes #2154.
Modify Table.extend to use vstack to concatenate compatible table, use scipy.sparse.vstack if some of the arrays are sparse.

Sparse concatenate

---

.codeclimate.yml
Orange/canvas/registry/description.py
Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/evaluate/tests/test_owtestlearners.py
Orange/widgets/tests/base.py
Orange/widgets/utils/signals.py
Orange/widgets/utils/tests/test_signals.py
Orange/widgets/widget.py
doc/development/source/code/owNumber.py
doc/development/source/orange-demo/orangedemo/OWDataSamplerA.py
doc/development/source/orange-demo/orangedemo/OWDataSamplerB.py
doc/development/source/orange-demo/orangedemo/OWDataSamplerC.py
doc/development/source/orange-demo/orangedemo/OWLearningCurveA.py
doc/development/source/orange-demo/orangedemo/OWLearningCurveB.py
doc/development/source/tutorial-channels.rst
doc/development/source/tutorial-cont.rst
doc/development/source/tutorial-settings.rst
doc/development/source/tutorial.rst
doc/development/source/widget.rst
pylintrc

A different take on #2292 and #2290.
Widget discovery code used to search for classes with metatype `WidgetMetaClass`, and then it extracted information contained in class attributes into `WidgetDescription`. The canvas thus had to import `WidgetMetaClass` and dug into the widget's attributes.
In this PR, the widget must describe itself. Discovery searches for any class that implements `get_widget_description`, which returns a `WidgetDescription`. Signals are described with `InputSignal` and `OutputSignal`; the widget can represent them internally in any way it wants.
The idea here is that canvas knows less about widget implementation. The entire API would be (more or less) that canvas exposes descriptive classes (`WidgetDescription`, `InputSignal`, `OutputSignal`) and requires that …

Move creation of widget description to widgets; Reimplement signal definition lists

---

Orange/widgets/unsupervised/owpca.py
Orange/widgets/unsupervised/tests/test_owpca.py

Fixes #2329
Make sure all variables are of type ContinuousVariable.

OWPCA: Components variables should be Continuous

---

Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/evaluate/tests/test_owtestlearners.py

https://sentry.io/biolab/orange3/issues/218529776/

[FIX] Test & Learn: handling memory error

---

Orange/widgets/visualize/owsilhouetteplot.py

[FIX]Silhouette Plot: elide hover labels if labels are long

---

Orange/projection/base.py
Orange/projection/pca.py
Orange/tests/test_pca.py
Orange/widgets/unsupervised/owpca.py
Orange/widgets/unsupervised/tests/test_owpca.py

Fixes #2255.
Use TruncatedSVD (LSA) on sparse data instead of PCA, since PCA does not work on sparse data. The difference is that TruncatedSVD truncates the vectors and does not center the data before calling svd. For dense data, functionality remains the same.
Workflow:
Corpus (Select bookexcerpts.tab) -> Bag of Words -> PCA
- widgets/unsupervised/owpca.py: Select decomposition with radio buttons. 
- projection/pca.py: TruncatedSVD model
- tests: test_pca.py

[ENH] PCA on sparse data.

---

Orange/widgets/model/owsvm.py

Fixes #2251
SVM widget should set `probability=True` by default.
This allows probabilities to be fitted and is more useful (e.g. when checking results in Predictions, ROC etc.)

owsvm: Fit probabilities by default in SVM widget

---

Orange/data/table.py
Orange/widgets/data/owmergedata.py
Orange/widgets/data/tests/test_owmergedata.py

[FIX] Merge: work with sparse

---

Orange/evaluation/testing.py

https://sentry.io/biolab/orange3/issues/267670404/
https://sentry.io/biolab/orange3/issues/269582517/
https://sentry.io/biolab/orange3/issues/282342454/
https://sentry.io/biolab/orange3/issues/282342206/
https://sentry.io/biolab/orange3/issues/196744688/
ContinuousVariable with Folds now contains string values instead of int.

[FIX] Test & Learn: number of folds causes many errors

---

Orange/data/table.py
Orange/tests/test_table.py

The condition `if self.sparse_x` works when it is false (`sparse_x == None`). But crashed when it was actually a sparse array since "The truth value of an array ... is ambiguous"
Test with `is not None`.

[FIX] RowInstance: Fix sparse check

---

Orange/preprocess/impute.py
Orange/preprocess/remove.py
Orange/preprocess/transformation.py
Orange/tests/test_transformation.py

We had three almost identical implementations of Lookup. None of them supported sparse data.
Remove two redundant implementations. Support sparse data by densifying it first.

Refactor Lookup & Support Sparse Data

---

Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/evaluate/tests/test_owtestlearners.py

_Iris_ table with only one class value (_Iris-setosa_). _Iris-setosa_ is selected in _Target Class_ box in Test & Score widget.
Work in progress.

[FIX] Test & Learn: class with only one value

---

Orange/widgets/credentials.py
Orange/widgets/tests/test_credentials.py

https://github.com/biolab/orange3-text/pull/253
try except block

[FIX] Credentials: handling password credentials error

---

Orange/widgets/data/owfile.py
Orange/widgets/data/tests/test_owfile.py

[FIX] File: no domain or empty domain -> no data

---

Orange/evaluation/scoring.py
Orange/tests/test_evaluation_scoring.py
Orange/widgets/evaluate/owtestlearners.py

Precision, Recall and F1 scores in Test & Score were showing incorrect results and not using the selected target class correctly.
Refactor scores by adding the TargetScore base class for Precision, Recall and F1. Call them correctly from the Test & Score widget.

[FIX] Fix and improve Precision, Recall, F1

---

Orange/widgets/gui.py
Orange/widgets/visualize/_owmap/owmap.js
Orange/widgets/visualize/owmap.py

Geo Map crashed when data input, then subset input, then data input cleared.
Geo Map showed warning when setting DomainModel-controlled master value attributes to None.
Neither of above should happen.

[FIX] OWMap: minor fixes

---

Orange/widgets/data/owpaintdata.py

https://sentry.io/biolab/orange3/issues/240133185/
One way to reproduce this behavior:
Use _Paint Data_ widget and draw some points. Then save it. Close the Orange. Open the Orange and then load the file and close the Orange again. Error should be thrown.
These steps were tested in Orange versions _master_, _3.4.2_, _3.4.1_ and _3.3.12_. In all those versions error occurred.

[FIX] Paint Data: now stores data in list and not np.array

---

Orange/widgets/visualize/owvenndiagram.py
Orange/widgets/visualize/tests/test_owvenndiagram.py

Fixes #2164.
Venn diagram is fixed to work on sparse data.
The methods `reshape_wide()` and `varying_between()` have been rewritten to 
work on sparse data, by iterating over non-zero values rather than all values.
Remaining issues:
1. Remaining computational bottleneck is `Table.transform(domain)` in the `reshape_wide()` method, which iterates over all columns.
Current timings:
~10 sec on 200 x 10000 dataset.
~2 min on 1200 x 24000 dataset.
too long on 61000 x 24000 dataset (_friends-transcripts_ ; takes 1.2 GB memory).

[ENH] Venn diagram on sparse data

---

Orange/preprocess/impute.py
Orange/statistics/util.py
Orange/tests/test_impute.py
Orange/tests/test_util.py
Orange/widgets/data/owimpute.py

Fixes #2349.
Work in progress.

[FIX] Impute: sparse

---

Orange/canvas/__main__.py
Orange/canvas/application/settings.py
Orange/canvas/config.py

Too many users using stale Orange versions.
Upon application startup, check if newer software version is available.

[ENH] Check if updates are available upon startup

---

Orange/clustering/dbscan.py
Orange/clustering/kmeans.py
Orange/data/variable.py
Orange/tests/test_classification.py
Orange/tests/test_discretize.py
Orange/tests/test_score_feature.py
Orange/tests/test_simple_tree.py
Orange/tests/test_table.py
Orange/tests/test_variable.py
Orange/widgets/data/tests/test_owrank.py

Test & Score created discrete variables with non-string values, which cause problems in Distributions. In #2274 we discussed that we should prohibit this and raise the exception early.
- Raise an exception in `DiscreteVariable`'s constructor and in `add_value` if the value is not a string.
- Add a test
- Remove a test that assigned `[1, 2, 3]` to values.
- Fix Results.get_augmented_data that used in int's instead of str's and broke Test & Score.
There are other ways to add a non-string value. But if one want to be destructive, she can easily assign a dict to `values`, and we're not preventing this either.

DiscreteVariable: Raise exception on non-string values

---

Orange/widgets/evaluate/owconfusionmatrix.py
Orange/widgets/evaluate/tests/test_owconfusionmatrix.py

[FIX] Confusion Matrix: do not append extra column if empty

---

Orange/widgets/unsupervised/owdistances.py
Orange/widgets/unsupervised/tests/test_owdistances.py

https://sentry.io/biolab/orange3/issues/196744070/events/5529227746/
Users sees an error message when calculating too large arrays and Orange does not crash.

[FIX] Distances: handling errors due to too large arrays

---

Orange/widgets/visualize/tests/test_owmosaic.py
Orange/widgets/visualize/utils/__init__.py

There were problems with vizrank crashing on some platforms.
Vizrank was crashing on some platforms: Ubuntu 14.04 and 16.04 with PyQt4 and some Windows with PyQt5.
Removed progressbar updates and some other GUI changes from the worker thread.

vizrank: interact with gui from main thread only

---

Orange/widgets/visualize/owsilhouetteplot.py
Orange/widgets/visualize/tests/test_owsilhouetteplot.py

[FIX] Silhouette Plot: handling memory error

---

Orange/modelling/base.py
Orange/modelling/linear.py
Orange/modelling/randomforest.py
Orange/preprocess/score.py
Orange/widgets/data/tests/test_owrank.py
doc/visual-programming/source/widgets/data/rank.rst
doc/visual-programming/source/widgets/model/linearregression.rst
doc/visual-programming/source/widgets/model/logisticregression.rst
doc/visual-programming/source/widgets/model/randomforest.rst
doc/visual-programming/source/widgets/model/stochasticgradient.rst

Rank didn't support Scorer (e.g Random Forest) inputs since the introduction of Fitters.
Have Rank support Random Forest as an input Scorer. Also SGD.

[FIX] Rank widget supports Scorer inputs

---

Orange/preprocess/score.py
Orange/tests/test_score_feature.py

Fixes https://github.com/biolab/orange3/issues/1916
Previously, FCBF always computed contingency as if the variable were discrete. Now uses Orange's Discrete contingency, which discretizes as necessary.
This should, hopefully, also fix segfault on OSX when all values are missing.

[FIX] score.FCBF: don't segfault on continuous variables w/ <0 values

---

Orange/widgets/data/owcolor.py

Fixes #2375.
`PerfectDomainContextHandler` matches by `PerfectDomainContextHandler.MATCH_VALUES_ALL`.

[FIX] OWColor: Use DiscreteVariable's values for matching contexts

---

Orange/tests/__init__.py
Orange/tests/test_instance.py
Orange/tests/test_table.py
Orange/tests/test_util.py

3 test failures when running with numpy 1.13.0
```
FAIL: test_init_inst (Orange.tests.test_instance.TestInstance)
File "C:\Miniconda35\conda-bld\orange3_1497021380284\_t_env\lib\site-packages\Orange\tests\test_instance.py", line 170, in test_init_inst
dtype=object))
File "C:\Miniconda35\conda-bld\orange3_1497021380284\_t_env\lib\site-packages\numpy\testing\utils.py", line 854, in assert_array_equal
verbose=verbose, header='Arrays are not equal')
File "C:\Miniconda35\conda-bld\orange3_1497021380284\_t_env\lib\site-packages\numpy\testing\utils.py", line 778, in assert_array_compare
raise AssertionError(msg) …
```

[FIX] tests: Fix test errors when running with numpy 1.13.0

---

Orange/canvas/__main__.py
Orange/canvas/application/welcomedialog.py
Orange/canvas/canvas/items/nodeitem.py
Orange/canvas/gui/toolbox.py
Orange/widgets/gui.py

Parts of the canvas are unaware of QPaintDevice.devicePixelRatio.
* Enable use of high dpi pixmaps if available. 
* Provide larger generated icons where applicable.
* Use QIcon.paint instead of going through QIcon.pixmap -> drawPixmap.
* Workaround for QGraphicsEffect lack of devicePixelRatio support.

[ENH] Improve support for HiDPI displays

---

Orange/widgets/unsupervised/owmanifoldlearning.py

Manifold Learning frequently deadlocks with the forking multiprocessing backend and a
threaded blas library.

[FIX] owmanifoldlearning: Remove `n_jobs=-2` parameter

---

Orange/widgets/evaluate/owcalibrationplot.py

Python 3.6, numpy 1.13.0:
```
ERROR: test_basic (Orange.widgets.evaluate.tests.test_owcalibrationplot.TestOWCalibrationPlot)
File "C:\test-install\lib\site-packages\Orange\widgets\evaluate\tests\test_owcalibrationplot.py", line 30, in test_basic
self.send_signal("Evaluation Results", self.res)
File "C:\test-install\lib\site-packages\Orange\widgets\tests\base.py", line 218, in send_signal
getattr(widget, input.handler)(value, *args)
File "C:\test-install\lib\site-packages\Orange\widgets\evaluate\owcalibrationplot.py", line 99, in set_results
self._replot()
File …
```

owcalibrationplot: Specify output type for the smoother

---

Orange/widgets/data/owpreprocess.py

The order of methods presented in the "Continuize Discrete Variables" is random
* Fix OrderedDict initialization.

[FIX] owpreproces: Stable order of continuizers

---

Orange/canvas/__main__.py
Orange/tests/test_third_party.py

```py
>>> from distutils.version import LooseVersion
>>> LooseVersion('3.4.dev') <= LooseVersion('3.4.1')
--------------------------------------------------------------------------------
TypeError: unorderable types: str() < int()
```
Use newer `package_resources.SetuptoolsVersion` which doesn't exhibit this problem.

[FIX] Update checker: LooseVersion doesn't handle str parts

---

Orange/widgets/data/owfile.py
Orange/widgets/data/tests/test_owfile.py
Orange/widgets/utils/filedialogs.py

If dlg_formats were set before an object was created, new file formats
from the add-ons were not detected unless OWFile was already cached in
the widget registry.
Fixes https://github.com/markotoplak/orange-infrared/issues/74

OWFile: dialog formats not set in class

---

requirements-core.txt

Scipy 0.16.1 is installed with the 32-bit Windows installer. Bumping
as we do not test with older scipy anyway.

Requirements: scipy version bump to 0.16.1

---

Orange/classification/_simple_tree.c
Orange/classification/simple_tree.py

SimpleTreeLearner does not release the GIL (as it is not thread safe)
* Remove use of global `compar_attr` variable. Use `qsort_(r|s)` with explicit context passing.
* Use GIL releasing ctypes call.

[ENH] SimpleTreeLearner: Release GIL & thread safety

---

Orange/widgets/data/owpaintdata.py
Orange/widgets/data/tests/test_owpaintdata.py

We create Paint Data widget, draw nothing, and save created workflow.
Then we open it:

[FIX] Paint Data: Fix crash on empty data

---

Orange/widgets/unsupervised/owmds.py
Orange/widgets/unsupervised/tests/test_owmds.py

[FIX] MDS: Support distances without domain information

---

Orange/preprocess/preprocess.py
Orange/tests/test_preprocess.py

Randomize, Scale, Continuize were not picklable since the corresponding Enums were not global.
Add `qualname`.

[FIX] Some preprocessors couldn't be pickled

---

.travis/stage_script.sh

Radon requirements occasionally cannot be met while a pass on Travis is required for all PRs.
Stop running radon on Travis and check codeclimate instead.

[MNT] Travis: Stop running radon in favor of codeclimate

---

Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/data/tests/test_owfeatureconstructor.py

Error occurs when _Values_ box is empty.

[FIX] Feature Constructor: no fail when no values

---

Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owscatterplotgraph.py

Put _Scatter Plot_ widget on the canvas. Then try to change shape. Select **(Same shape)**.
Put _Scatter Plot_ widget on the canvas.  Then do something. For instance, try to change color. **Find Informative Projections** button enables and it crashes when an user starts vizrank.

[FIX] Scatter Plot: two minor errors

---

Orange/widgets/evaluate/owrocanalysis.py
Orange/widgets/evaluate/tests/test_owrocanalysis.py

[FIX] ROC Analysis: color support for more than 9 evaluation learners

---

Orange/canvas/scheme/scheme.py

Alternative to #2390
Make no exception for dynamic signals if they type check.

[FIX] canvas: Fix proposed connection scoring for dynamic signals

---

Orange/widgets/evaluate/owcalibrationplot.py
Orange/widgets/evaluate/owliftcurve.py
Orange/widgets/evaluate/owrocanalysis.py

Disable menu and mouse zoom in all evaluate's plotting widgets.

[FIX] Disable menu and mouse zoom in all evaluate's ploting widgets.

---

Orange/canvas/document/schemeedit.py

When the canvas text annotation is selected and has edit focus, pressing *(Control|Command) + Backspace* raises an error
```
----------------------------- KeyError Exception ------------------------------
File "/Users/aleserjavec/workspace/orange3/Orange/canvas/document/schemeedit.py", line 1339, in __onEditingFinished
annot = self.__scene.annotation_for_item(item)
File "/Users/aleserjavec/workspace/orange3/Orange/canvas/canvas/scene.py", line 618, in annotation_for_item
return rev[item]
KeyError: <Orange.canvas.canvas.items.annotationitem.TextAnnotation object at 0x1246ee318>
```
Clear item's keyboard focus before removing it.

[FIX] schemeedit: Clear edit focus before removing items

---

Orange/base.py
Orange/widgets/model/tests/test_owlogisticregression.py

[FIX] Logistic Regression: impute

---

Orange/widgets/visualize/owsilhouetteplot.py
Orange/widgets/visualize/tests/test_owsilhouetteplot.py

Handling `nan` values.
https://sentry.io/biolab/orange3/issues/220334718/

[FIX] Silhouette Plot: now setting axis range properly

---

Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owscatterplotgraph.py

The left axis can observably jump when the widget receives new data on the 'Data Subset' input. This is observable only when the input data contains unknowns in currently displayed X, Y, color or size variables.
Example (load brown-selected in File widget, select rows in Data Table while Scatter Plot is visible):
Reset the axis text width hint only when switching between displayed variables.

[Fix] Scatter Plot: Reset the axis width only when needed

---

Orange/widgets/evaluate/owtestlearners.py

Test & Score does not show any columns by default.
An extensive list of changes (see below) makes sure that the settings are initially filled with the list of columns showed by default.

[FIX] Test and Score: Show default columns

---

Orange/canvas/document/quickmenu.py

Now Keyboard shortcuts (up, down, enter) work immediately, but search
line edit placeholder text is not shown anymore.
Pressing enter when quick menu opened only focused the search bar instead of putting the widget onto canvas.

Quick menu: always open with search bar focus.

---

Orange/canvas/canvas/items/annotationitem.py
Orange/canvas/canvas/scene.py
Orange/canvas/document/commands.py
Orange/canvas/document/interactions.py
Orange/canvas/document/schemeedit.py
Orange/canvas/scheme/annotations.py
Orange/canvas/scheme/readwrite.py
conda-recipe/meta.yaml
requirements-gui.txt
scripts/macos/requirements.txt

Implements inline text markup editing for canvas annotations. Html, rst and markdown are supported.
Use alt-right click on the annotation to change how the content should be interpreted.

[ENH] Canvas Annotations: Text markup editing

---

Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/unsupervised/tests/test_owhierarchicalclustering.py

> ---------------------------- ValueError Exception -----------------------------
> Traceback (most recent call last):
>   File "pyqtgraph/graphicsItems/AxisItem.py", line 525, in paint specs = self.generateDrawSpecs(painter)
>   File "pyqtgraph/graphicsItems/AxisItem.py", line 819, in generateDrawSpecs tickLevels = self.tickValues(self.range[0], self.range[1], lengthInPixels)
>   File "pyqtgraph/graphicsItems/AxisItem.py", line 691, in tickValues num = int((maxVal-start) / spacing) + 1
> ValueError: cannot convert float NaN to integer
> -------------------------------------------------------------------------------

[FIX] Distances: prevent inf numbers

---

doc/data-mining-library/source/conf.py
doc/development/source/conf.py
doc/visual-programming/source/conf.py

Doc builds on RTFS don't contain API (docstrings) docs due to unable to import Orange.
Instead of inserting at position 0, _append_ project root to `sys.path` to prefer importing _installed_ Orange version.

DOC: fix RTFD via append instead of inserting project root to sys.path

---

Orange/widgets/data/owsql.py

User name and password should not be saved in Settings.
Use credentials manager.

[ENH] SQL: save user name and password via credentials manager

---

Orange/data/table.py
Orange/tests/test_table.py

Fixes #2378 
Assure that when domains are equal, `from_tables` sets the resulting table's domain to the instance that was passed on the input.

[FIX] OWColor: Fix propagating changes to the output

---

Orange/data/sql/table.py
Orange/widgets/data/owsql.py

1) Custom SQL had a case-sensitive check for SELECT (lower case did not work correctly)
2) Only psycopg2.ProgrammingError was caught, but after refactoring the BackendError can be thrown as well
1) case-insensitive check
2) catch both errors

[FIX] owsql: Fixes for Custom SQL option

---

Orange/base.py
Orange/classification/rules.py
Orange/classification/softmax_regression.py
Orange/preprocess/preprocess.py
Orange/preprocess/score.py
Orange/regression/linear_bfgs.py
Orange/tests/test_filter.py
Orange/tests/test_preprocess.py
Orange/tests/test_rules.py
Orange/widgets/evaluate/owtestlearners.py

SklLearner methods do not work on SqlTable data because of the RemoveNaNClasses preprocessor.
Use an existing (more general) implementation of the RemoveNaNClasses preprocessor - the HasClass filter.
Why do we even have both (functionality looks exactly the same)?
Before merging, we should check whether the RemoveNaNClasses preprocessor can be removed completely and HasClass filter used in its place.

[FIX] preprocess: Fix RemoveNaNClasses / Use existing HasClass

---

Orange/statistics/util.py
Orange/tests/test_statistics.py

The statistics module did not have an implementation of [`digitize`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.digitize.html).
Add implementation of `digitize` which supports dense and sparse data.
@nikicc Would it perhaps make sense to return a sparse matrix if a sparse matrix is passed? Assuming that a large sparse matrix would be passed, and that all the "0"s would belong to the "0" bin, then it would be more efficient to return a sparse matrix instead of a dense numpy array. However there is absolutely no guarantee that the "0"s would indeed belong to the "0" bin, so this may not make sense, as it would just complicate the API. Is this of any concern, or is the current implementation ok?

Statistics.util: Implement digitize

---

Orange/data/table.py
Orange/tests/test_table.py

```
import Orange.data
d = Orange.data.Table("iris")
del d[2:]
d[[True, False]]
```
fails with
```
File "<stdin>", line 4, in <module>
File "/Users/aleserjavec/workspace/orange3/Orange/data/table.py", line 694, in __getitem__
return self.from_table_rows(self, key)
File "/Users/aleserjavec/workspace/orange3/Orange/data/table.py", line 449, in from_table_rows
self.ids = np.array(source.ids[row_indices])
IndexError: boolean index did not match indexed array along dimension 0; dimension is 150 but corresponding boolean dimension is 2
```
Update `ids` in `Table.__del__`

[FIX] table: Update `ids` in `Table.__del__`

---

.codeclimate.yml
.travis.yml

It has not passed for a single time since it was enabled and there is
no one working on fixing it.

travis: Disable python 3.6 build

---

Orange/widgets/utils/signals.py
Orange/widgets/utils/tests/test_signals.py

Fixes gh-2468
Record the order of Input/Output creation and order the instances in WidgetSignalsMixin.get_signals

[FIX] WidgetSignalsMixin: Fix input/output ordering for 'newstyle' signals

---

Orange/statistics/util.py
Orange/tests/test_statistics.py

The statistics module did not have an implementation of [`var`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.var.html) to compute the variance.
Add implementation of `var` which supports dense and sparse data.

Statistics.util.var: Implement variance

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/tests/test_owmosaic.py

[FIX] Mosaic: clear when data is disconnected

---

Orange/canvas/application/addons.py

Installing official add-ons through drag & drop doesn't work from cleaning the add-ons names onwards (3.4.0 onwards?). The mismatch occurs when we compare cleaned addon name with the zip file name. Since the official addon name was cleaned it doesn't match the uncleaned zip filename.
Clean the drag & drop file name in the same manner as official addons.

[FIX] Add-ons: Fix Installation of Official Add-ons Through Drag & Drop

---

Orange/classification/_simple_tree.c

*_simple_tree.c* did not compile using mingw compiler toolchain.

[FIX] simple_tree.c: Fix mingw compiler compatibility

---

Orange/classification/tree.py
Orange/widgets/model/tests/test_tree.py

Fixes #2370 .
Work in progress.

[FIX] Tree: Sparse Support

---

Orange/preprocess/remove.py
Orange/statistics/util.py
Orange/tests/test_remove.py
Orange/tests/test_statistics.py

When `remove unused features` is checked in Select Rows and some discrete variable comes from sparse data, Orange crashes with `AttributeError: ravel not found` error.
The problem is in the `remove_unused_values` method (`Orange/preprocess/remove.py`) which cannot handle sparse matrices.
Issue: https://sentry.io/biolab/orange3/issues/269413491/
* Implement `nanunique` function. `nanunique` returns unique values without missing (`np.nan`) values and works on sparse and dense matrices. 
* Fix `remove_unused_values` to use `nanunique ` and hance support sparse discrete columns.

[FIX] Select Rows: Removing Unused Values for Discrete Variables in Sparse Data

---

Orange/widgets/unsupervised/owpca.py
Orange/widgets/unsupervised/tests/test_owpca.py

Even though Normalize was set the data were not normalized, unless
the checkbox was unchecked and checked.
Moved preprocessor creating code to fit.

owpca: fix normalize checkbox

---

Orange/widgets/model/owrules.py
Orange/widgets/model/tests/test_owrulesclassification.py
Orange/widgets/utils/owlearnerwidget.py

[FIX] CN2 Rule Induction: handling memory error

---

Orange/canvas/document/schemeedit.py

In case the user opens a workflow whose nodes are very far from coordinate origin there is nothing visible in the viewport.
Example:
```xml
<?xml version='1.0' encoding='utf-8'?>
<scheme description="" title="" version="2.0">
<nodes>
<node id="0" name="Constant" position="(3779.0, 2765.0)" project_name="Orange3" qualified_name="Orange.widgets.model.owconstant.OWConstant" title="Constant" version="" />
</nodes>
<links />
<annotations />
<thumbnail />
</scheme>
```
Scroll the viewport to the first node.

[FIX] Ensure visible nodes after openning a workflow.

---

Orange/data/table.py
Orange/tests/test_sparse_table.py

Table `__str__` method crashed when the Y was sparse.
_Steps to reproduce:_
```
data = Table('iris')
data.X = sp.csr_matrix(data.X)
data.Y = sp.csr_matrix(data.Y).T
print(data)
```
Also, printing any Table would be missing the final closing `]` e.g.
```
[[0, 1],
[1, 0]
```
I've fixed this to
```
[[0, 1],
[1, 0]]
```
The `__str__` method no longer crashes on a sparse Y. Also, I've made it so `var_name=value` is printed for any non-zero value and all discrete values. The `var_name` is now also hidden for any target variable (the reasoning being that there are usually not that many target variables, and showing the variable name wouldn't add any clarity to the output).
@nikicc could you please check if this is ok?

[FIX] Table: Fix printing data with sparse Y

---

Orange/tests/__init__.py

Orange currently does not run unit tests placed in subpackage directories, e.g. Orange/distance/tests.
Discovery is patched so that it does. The trick to prevent the recursion similar to that in widget tests (https://github.com/biolab/orange3/blob/master/Orange/widgets/tests/__init__.py).

[MNT] Run tests from subpackages

---

Orange/widgets/unsupervised/owhierarchicalclustering.py
setup.py

Fixes gh-2297
The cause of the broken PDF export was a non aspect preserving implicit dendrogram scaling and use of cosmetic pen to implement fast resize in response to user interaction. QPDFWriter however cannot handle cosmetic pens.
Explicit transform/scale the dendrogram geometry to scene display coordinates and avoid use of cosmetic pens.

[FIX] owhierarchicalclustering: Explicit geometry transform

---

Orange/widgets/unsupervised/owmanifoldlearning.py
Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py

[FIX] Manifold Learning: handling out of memory error

---

Orange/widgets/visualize/owdistributions.py
Orange/widgets/visualize/tests/test_owdistributions.py

[FIX] Distributions: show probabilities upon selection

---

Orange/regression/tree.py
Orange/widgets/model/tests/test_tree.py

Regression Tree Sparse Support

[FIX] Regression Tree Sparse Support

---

Orange/classification/_tree_scorers.c
Orange/classification/_tree_scorers.pyx
Orange/tests/test_orangetree.py
Orange/tree.py

Tree prediction for sparse data does not work.
Added a corresponding function in Cython.

[FIX] Trees: Fix classification from sparse data

---

Orange/widgets/unsupervised/owpca.py
Orange/widgets/unsupervised/tests/test_owpca.py

owpca: prevent caching features of components output

---

Orange/widgets/settings.py
Orange/widgets/unsupervised/owmds.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owscatterplot.py

Fixes https://github.com/biolab/orange3/issues/2182

[ENH] OWMDS, OWLinearProjection: save selection in workflow

---

Orange/classification/majority.py
Orange/data/variable.py
Orange/widgets/data/owcontinuize.py
Orange/widgets/data/owdatainfo.py
Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/data/owfile.py
Orange/widgets/data/owpreprocess.py
Orange/widgets/data/owpurgedomain.py
Orange/widgets/data/owsql.py
Orange/widgets/data/owtable.py
Orange/widgets/gui.py
Orange/widgets/unsupervised/owdistances.py
Orange/widgets/unsupervised/owmds.py
Orange/widgets/utils/domaineditor.py
Orange/widgets/utils/itemmodels.py
Orange/widgets/visualize/owdistributions.py
Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/ownomogram.py
Orange/widgets/visualize/owparallelcoordinates.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owsilhouetteplot.py

Variable icons do not match names used in the File widget, which is usually where people set/check variable types now. Many places in Orange use the same icons and use various names inconsistently.
**Proposal**
We use:
- "categorical" marked with a "C" icon
- "numeric" marked with an "N" icon
Moving towards consistency will be a long (Sisyphean) struggle.
This PR makes the file widget consistent, using categorical (C) and numeric (N). It also updates the icons' tooltips. The same icons are used across all Orange.
If/When other labels and descriptions are found using different terms, they should be adapted to use the same names.

[FIX] Change Variable Icons: Discrete -> Categorical, Continuous -> Numeric

---

Orange/classification/tree.py

Setting "Min. number of instances in leaves" (or `min_samples_leaf` in the code) to K actually enforced leaves to have K + 1 instances.
Change the check for invalid nodes from `<= min_samples_leaf` to strict `< min_samples_leaf`

[FIX] tree: Fix min_samples_leaf check

---

Orange/widgets/model/owlinearregression.py
Orange/widgets/model/owlogisticregression.py
Orange/widgets/model/owsgd.py
Orange/widgets/model/owsvm.py

Connect Logistic Regression -> Test & Score
Coefficients -> Train connection is established, but Learner -> Learner would be expected.
Restore the 'explicit' hint flag on output declarations for Table outputs.

[FIX] widgets/model: Restore 'explicit' hint flag for 'Coefficients' output

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/tests/test_owmosaic.py

`compute_attr_order` is called every step. It does not need to be.

[FIX] Mosaic Vizrank: compute_attr_order is called every step

---

Orange/widgets/evaluate/tests/test_owtestlearners.py
Orange/widgets/tests/base.py
Orange/widgets/unsupervised/tests/test_owmds.py

Asynchronous tests for owmds and owtestlearners set inputs to their respective widgets when they should not (a per `OWWidget.isBlocking`).
* Raise RuntimeError in `WidgetTest.send_signal` if the target widget is not ready to receive inputs.
* Add `wait` parameter to `WidgetTest.get_output`.
* Fix test_owmds and test_owtestlearners.

[FIX] Fix asynchronous widget tests

---

Orange/canvas/canvas/items/nodeitem.py
Orange/preprocess/impute.py
Orange/widgets/data/owimpute.py
Orange/widgets/data/tests/test_owimpute.py
Orange/widgets/utils/concurrent.py
Orange/widgets/utils/tests/test_concurrent.py
doc/development/source/concurrent.rst

Imputer widget blocks the main GUI thread.
Move the column imputer fitting into background thread[s].

[ENH] Impute widget: Parallel execution in the background

---

Orange/canvas/__main__.py

Update checker crashed with (probably) SSLError on Windos with insufficient / outdated cert store.
Catch all exceptions.

Canvas: Update checker should never crash

---

.ci_tools/appveyor/step-test.ps1
Orange/tests/test_ada_boost.py

* scikit-learn 0.19 wheels on PyPI are no binary compatible with our testing numpy.
* TestSklAdaBoostLearner.test_adaboost_base_estimator fails with scikit-learn 0.19
```
Failure
File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py", line 58, in testPartExecutor
yield
File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py", line 600, in run
testMethod()
File "/Users/aleserjavec/workspace/orange3/Orange/tests/test_ada_boost.py", line 37, in test_adaboost_base_estimator
self.assertLess(ca[0], ca[1])
File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py", line 1199, in assertLess …
```

[MNT]  Fix appveyor tests

---

Orange/widgets/tests/test_widget.py
Orange/widgets/utils/messages.py
Orange/widgets/utils/messagewidget.py
Orange/widgets/utils/overlay.py
Orange/widgets/utils/tests/test_messagewidget.py
Orange/widgets/utils/tests/test_overlay.py
Orange/widgets/widget.py
setup.py

The OWWidget's 'message_bar' is placed in an inappropriate position above the rest of the GUI causing frequent re-layouts which both flicker the GUI and change the position of controls under the mouse from the unsuspecting user.
* Replace the top message area with a summary in a (permanent) status bar at the bottom.
* Also add a progress bar widget, mirroring the `progressBarValue` state.

[ENH] Widget status bar

---

Orange/canvas/document/schemeedit.py
Orange/canvas/scheme/scheme.py
Orange/canvas/scheme/widgetsscheme.py
Orange/widgets/settings.py
Orange/widgets/tests/test_context_handler.py

It is hard to see widget's settings
Add an action to the widget's context menu that is shown when canvas is run in debug mode (debug log level), which prints the current widget's settings to the log.

Add Show Settings to widget context menu

---

Orange/widgets/data/tests/test_owfile.py
Orange/widgets/utils/domaineditor.py

Fixes #2424 and #2423.
Conversion nominal -> numeric now retains the actual values (bugfix).
Conversion numeric -> * drops decimal places (e.g. 18.0 -> 18) if all entries are integer.

FileWidget: DomainEditor update of type conversions.

---

Orange/widgets/visualize/owsilhouetteplot.py
Orange/widgets/visualize/tests/test_owsilhouetteplot.py

Related to #2336.
Silhouette Plot already catches a memory error. However that error might be caught but another error is thrown. That is 
> ValueError array is too big; 'arr.size * arr.dtype.itemsize' is larger than the maximum possible size.
See: https://sentry.io/biolab/orange3/issues/196744070/events/6454328021/

[FIX] Silhouette Plot: another memory error

---

Orange/widgets/data/owfeatureconstructor.py

Implements new functions
* Add numpy 'nan' functions as replacement for min, max, sum
* Add other functions: mean, std, var...

[ENH] OWFeatureConstructor: Add new functions from numpy

---

Orange/widgets/data/owconcatenate.py
Orange/widgets/data/tests/test_owconcatenate.py

If the widget had no input and the `append_source_columns` was True,
it would crash in `apply` method with an
```
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/gui.py", line 2009, in do_commit
commit()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owconcatenate.py", line 183, in apply
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/utils/annotated_data.py", line 27, in add_columns
attributes = domain.attributes + tuple(attributes)
AttributeError: 'NoneType' object has no attribute 'attributes'
```

owconcatenate: Fix an AttributeError when widget has no input
