- Orange/widgets/evaluate/owcalibrationplot.py
- Orange/widgets/evaluate/owliftcurve.py
- Orange/widgets/evaluate/tests/base.py
- Orange/widgets/evaluate/tests/test_owcalibrationplot.py
- Orange/widgets/evaluate/tests/test_owliftcurve.py
- Orange/widgets/evaluate/tests/test_owrocanalysis.py
Similar as in #2394. This time fixed in widgets **Calibration Plot** and **Lift Curve**.
Additional info: https://sentry.io/biolab/orange3/issues/210623933/
Same solution as in #2394.
Three tests use the same code and that is why that code is moved to a separate file.
> [FIX] Another color palette when too many colors needed

- Orange/canvas/application/errorreporting.py
> [FIX] Error Reporting: open encode as unicode

- Orange/tests/test_table.py
- doc/development/source/tutorial-settings.rst
The fact that default values of settings are updated was not mentioned in the documentation. Now it is, along with a way to disable this behavior for a specific setting.
As promised in gh-2535
> doc: Mention schema_only settings in doc

- scripts/macos/build-macos-app.sh
- scripts/macos/create-dmg-installer.sh
- scripts/macos/sign-app.sh
This is a script I use to prepare a signed macos release. I had to modify the mac build process a bit in order to be able to sign the resulting app.
The script could (should?) be rewritten in a way that does not hardcode version and paths, but that would require some bash programming skills I do not possess.
> Scripts: prepare signed macos binary

- Orange/widgets/unsupervised/owmds.py
MDS similar pairs graphics construction was (unnecessarily) O(n**4).
* Speedup graphics item construction
* Replace use of individual QGraphicsItem for each line with a single PlotCurveItem
* Limit the number of displayed pairs to 10000
> [FIX] MDS: Optimize similar pairs graphics construction

- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/tests/test_owmosaic.py
> [FIX] Mosaic Display: subset data

- Orange/data/io.py
- Orange/tests/test_table.py
- Orange/widgets/data/owfile.py
- Orange/widgets/data/tests/test_owfile.py
https://github.com/biolab/orange3/issues/2388
> io, OWFile: if URL without scheme, assume http by default

- Orange/data/sql/backend/postgres.py
- Orange/data/variable.py
- Orange/tests/sql/test_sql_table.py
SqlTable does not reuse existing variable objects.
Use Variable.make instead of creating new ones.
> postgres: Use make to reuse existing variables

- Orange/widgets/evaluate/tests/test_owtestlearners.py
Random coverage: https://codecov.io/gh/biolab/orange3/compare/1a4652ab07fb1d4e4246f87c7f716d4783abea92...959a79e14344856da534d7dc1bc0b4f1f92aaaa4/src/Orange/widgets/evaluate/owtestlearners.py
> Fix owtestlearner random coverage

- Orange/widgets/settings.py
- Orange/widgets/tests/test_domain_context_handler.py
When domain is empty (but not None!) an if check was executed that should not have been.
Correctly check with `is None`.
> DomainContextHandler: Fix check for empty domains

- requirements-core.txt
Following instructions failed to install Orange on Ubuntu 14.04 with:
ValueError: ("Expected ',' or end-of-list in", 'Orange3==3.6.0.dev0+1278e52', 'at', '+1278e52')
This should fix similar issues.
> Added pip to requirements-core.txt

- Orange/widgets/tests/base.py
typing.Type was introduced only in Python 3.5.2 
try-except the import.
> [FIX] widgets/tests: Compatibility with Python 3.5.{0,1}

- Orange/canvas/__main__.py
Don't have enough usage stats.
Increase verbosity of client's user-agent string when connecting to check for updates. The expectation is this shall prove there are about as many Orange users on Loonix as there are Sheep.
> Update checker: more informative User-Agent string

- Orange/canvas/report/tests/test_report.py
2 tests fail:
- `test_report_widgets_evaluate`
- `test_save_report`
> [FIX] Fix failing report tests

- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/utils/domaineditor.py
Fixes #2424
See https://github.com/biolab/orange3/pull/2518#issuecomment-323717377
Problem: ExcelReader creates a Discrete variable with a list of integer floats.
Solution: Change the check for conversion of list of categorical values to floats.
> FileWidget: Fix conversion for integer floating-point values.

- Orange/widgets/utils/domaineditor.py
DomainEditor (e.g. in the File Widget) does not have horizontal header and hence doesn't allow the user to resize the columns. This is a problem when the features have longer names.
I added the header. While it is better in terms of functionality, the previous design may have been less cluttered. @BlazZupan, what do you think?
> [ENH] DomainEditor: Add horizontal header

- Orange/widgets/visualize/owscatterplotgraph.py
Fixes https://github.com/biolab/orange3/issues/2451
Changed selection of labels to correspond to its data points in scatterplot.
> Fixed scatterplot labels when not all data displayed due to missing values

- Orange/widgets/utils/annotated_data.py
- Orange/widgets/utils/plot/owplotgui.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owscatterplotgraph.py
Duplicated code.
1) Scatter Plot Graph can accept custom **ViewBox**. Some widgets need to use custom ones because they use special mouse events.
2) Some common things were moved to Scatter Plot Graph and Plot GUI. These common things can also be used in other widgets (Freeviz, Linear Projection, MDS, Radviz).
3) Static method `create_groups_table` moved to `annotated_data.py` as a function. Can be used by many other widgets as well.
Does not add scrollbars anymore. It is highly not recommended to use scrollbars in Orange.
> Move common things from Scatter Plot to SP Graph and Plot GUI

- Orange/canvas/report/owreport.py
- Orange/canvas/report/tests/test_report.py
This is urgent. The current release is broken: Reports cannot be saved because `ReportItems` (derived from `QStandardItem`) can't be pickled.
Add `ReportItem.__getnewargs__`.
I don't have Python 3.6 env on this machine so I ran tests from a bundle. Can somebody with "real" Python 3.6 check this?
> [FIX] Fix saving reports on Python 3.6

- Orange/canvas/canvas/scene.py
Most widget icons are not displayed in the workflow preview due to QTBUG-63159
Reimplement QSvgGenerator.metric to report proper device pixel ratio.
> [FIX] canvas/preview: Fix workflow preview rendering

- Orange/classification/tree.py
- Orange/tests/test_tree.py
Fixes #2565
Problem: Changing and filtering kwargs in Orange.modelling.base.Fitter drops preprocessors if they are not explicitly listed in the learner's constructor parameters.
Fix: Explicitly add preprocessors to the list of parameters in the TreeLearner's constructor.
> [FIX] Tree: Reintroduce preprocessors.

- Orange/canvas/canvas/items/linkitem.py
- Orange/canvas/scheme/link.py
Links in workflow previews are rendered as dotted lines. This is due to workflow mode's inability to account for the possibility that it has no associated runtime execution state.
Add (and use as default) a `NoState` flag to account for no runtime execution state. Style the graphical presentation accordingly.
> [FIX] canvas: Fix link runtime state modeling

- Orange/widgets/data/owfeatureconstructor.py
Types in Feature constructor are still named "Discrete", "Continuous" (and "String").
> OWFeatureConstructor: Rename attribute types

- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
The class is selected as the default grouping attribute, yet it's hidden on the bottom of the list.
Furthermore, we have pushed classed to the top in other widgets.
Reorder to put the class at the top.
> BoxPlot: Reorder the attributes to put the class at the top

- Orange/preprocess/preprocess.py
- Orange/tests/test_preprocess.py
- Orange/tests/test_randomize.py
9b5d6c4d57b0e47627b2e185d85e19b606131bef has broken shuffling of attributes in Randomize widget: `skl_shuffle` shuffles whole rows, so the effect of shuffling attributes is the same as of shuffling the class.
Dense data is handled as before 9b5d6c4d57b0e47627b2e185d85e19b606131bef.
Sparse data is converted to csc and indices are replaced with random indices. These indices are unique within each row.
The new method for randomization is now tested. I haven't added any other tests for this (otherwise untested) class.
> preprocess.randomize: Don't shuffle entire rows

- Orange/canvas/__main__.py
Fixes gh-2596
Disable pyqtgraph's atexit and QApplication.aboutToQuit cleanup handlers.
> [FIX] Disable pyqtgraph's exit cleanup handler

- requirements-core.txt
Fixes gh-2600
Increase required setuptools version to 36.3 
This is required for installing namespace packages from wheels
build with newer versions of setuptools (see setuptools issue 885)
> [FIX] setup: Increase required setuptools version

- Orange/widgets/data/owrank.py
- Orange/widgets/data/owtable.py
- Orange/widgets/data/tests/test_owrank.py
- Orange/widgets/gui.py
- Orange/widgets/tests/test_itemmodels.py
- Orange/widgets/utils/itemmodels.py
- doc/development/source/tutorial-settings.rst
Fixes https://github.com/biolab/orange3/issues/2478
Updated owrank  to use PyTableModel and its faster sorting, but then I kinda broke something. Then I kinda fixed it by refactoring the whole widget into something I could understand. And it still somewhat works.
Old selection settings won't restore correctly as they were saved as indices of _sorted_ values. Suggestions welcome.
> [FIX] Slow Rank

- Orange/preprocess/preprocess.py
- Orange/widgets/data/tests/test_owpreprocess.py
* File (iris) -> 
* Select Columns (select 'Petal width' as the only feature) ->
* Randomize (Select both 'Classes' and 'Features', 'Replaceable shuffling') -> 
* Test & Score; Achieves 0.95 AUC with logistic regression.
Use the initial supplied seed to issue a separate seeds for X,Y,meta parts.
> [FIX] preprocess.randomization: Do not use the same seed for X, Y, and meta

- Orange/widgets/visualize/owboxplot.py
Selection of instances in Box Plot had complexity O(n_all * n_selected), making it too slow / freeze for data with a couple thousand instances.
Use faster membership testing.
> [FIX] OWBoxPlot: Faster selection

- Orange/widgets/data/owpythonscript.py
- Orange/widgets/data/tests/test_owpythonscript.py
- Orange/widgets/tests/base.py
Alternative to #2418.
Allow multiple inputs, store them in dictionaries and expose them under their existing names (e.g. `in_data`) in case there is only a single signal, and with plural names (e.g. `in_datas`) bound to lists of inputs (zero, one or more).
Creation of inputs and outputs is automatized through a meta class. The advantage of this is, beside easier adding of new inputs and outputs, sharing the common code for all inputs. For instance, when testing multiple inputs, we only need to test `in_data` (`in_datas`) since other inputs work the same way.
> [ENH] Multiple inputs for OWPythonScript

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Selection saving did not work.
Selection saving needed only a small fix. To also save different selection groups I changed the format of saved selections.
> [FIX] Saving of multiple selections in ScatterPlot

- Orange/widgets/utils/owlearnerwidget.py
- Orange/widgets/utils/tests/test_owlearnerwidget.py
Learner names are not saved in workflows (Fixes #2601)
Declare learner_name as a schema_only setting. Fill default value in __init__ when not loading from workflow.
> [FIX] OWBaseLearner: Save learner name in workflow

- Orange/widgets/settings.py
- Orange/widgets/tests/test_settings_handler.py
Schema-only settings within components were not removed in SettingsHandler.update_defaults
> [FIX] Schema-only settings in components

- Orange/tests/test_score_feature.py
The `test_rrelieff` test currently fails on macOS when running the full [test suite](https://travis-ci.org/ales-erjavec/orange3-installers/builds/272581995#L541)
Remove 'AGE' from the expected results for rrelieff
> [TST] test_rrelieff: Remove 'AGE' from the expected results for rrelieff

- Orange/widgets/data/owrank.py
Rank widgets now has alternating row colors, but they don't go together well with the monotone header.
I tried and failed to color the header. `QHeaderView.paint` calls `QStyle.drawControl` which is OS-specific and overrides the background color, at least on Mac. Hence I reverted the table view so that it has grid instead of alternating colors.
An alternative would be to eliminate the header, like in Confusion matrix. This requires some additional work to support selections etc. I don't think alternating colors look nice here anyway, so I vote for a grid.
Fixes #2609.
> OWRank: Eliminate alternating colors, add grid

- scripts/windows/condainstall.bat
Standalone Miniconda installer (offline) does not include conda "executable" and does not use the conda-forge channel.
To reproduce use current miniconda installer (on a clean windows installation) to install orange.
Navigate to %LOCALAPPDATA%/Orange/Scripts
conda.bat is not present
Create conda.bat and .condarc files manually
> conda_installer: Include conda in environment

- Orange/widgets/utils/annotated_data.py
If Scatter plot's Data is connected to another widget, the column name in the output signal depends upon whether the user selects more groups or only one. If it is, for instance, connected to another scatter plot, the user has to change the name of the variable used for coloring.
Rename *Selection group* to *Selected*.
> Rename Selection Group to Selected

- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
Feature Constructor widget does not offer `abs` in the combo.
I added `abs` and, while at it, also some other builtin function that could be useful.
> Feature Constructor: Add some builtin functions

- Orange/widgets/data/owrank.py
- Orange/widgets/data/tests/test_owrank.py
- Orange/widgets/tests/test_itemmodels.py
- Orange/widgets/utils/itemmodels.py
Fixes https://github.com/biolab/orange3/issues/2617
Always sort NaNs last. Implemented by exposing reimplementable `AbstractSortTableModel._argsortData()`. Also fix header indicator by sorting via `view.horizontalHeader().setSortIdicator()` instead of its model.
> OWRank: sort NaNs last; fix sort indicator

- Orange/widgets/tests/test_annotated_data.py
- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/unsupervised/tests/test_owmds.py
- Orange/widgets/utils/annotated_data.py
- Orange/widgets/visualize/owscatterplotgraph.py
Too much duplicated code.
MDS now uses Scatter Plot Graph instead of (Mds)plotutils.
> MDS: use Scatter Plot Graph instead of (Mds)plotutils

- Orange/canvas/gui/stackedwidget.py
<s>(Maybe)</s> Fixes gh-2614
Check if the new geometry is the same as the old. Do nothing if they are the same.
> [FIX] canvas/stackedwidget: Check if the new geometry is the same as the old

- Orange/widgets/utils/itemmodels.py
The methods for mapping from/to source table rows in `TableModel` were renamed from _mapFrom**Table**Rows_ to _mapFrom**Source**Rows_ as of https://github.com/biolab/orange3/pull/2494. Hence mapping for all models extending `TableModel` in addons now crash with:
```
AttributeError: '*TableModel' object has no attribute 'mapToTableRows'
```
Add old style methods names and mark them as deprecated.
> TableModel: Add old style mappings as deprecated

- Orange/widgets/settings.py
- Orange/widgets/tests/test_context_handler.py
- Orange/widgets/tests/test_settings_handler.py
Widget settings version were not stored in the serialized defaults, but were still passed to  OWWidget.migrate_settings with an incorrect version of 0.
One example where this caused an error (due to wrong migration)
* Open canvas, add 'Test & Score', change the *Sampling* option to *Test on test data*, close canvas
* Open again, add 'Test & Score', observe that no *Sampling* option is selected at all. Without changing anything add a single file and learner input to the widget.
```
-------------------------- AssertionError Exception ---------------------------
File "/Users/aleserjavec/workspace/orange3/Orange/canvas/scheme/widgetsscheme.py", line 839, in process_signals_for_widget
widget.handleNewSignals()
File …
```
> [FIX] settings: Store settings version in the serialized defaults

- Orange/preprocess/preprocess.py
- Orange/tests/test_randomize.py
The choice of non-zero indices was dependent on the sparsity and
did not take the full index space into consideration.
For instance an input matrix with non-zero elements only in the first row would never be changed.
Actually permute the input's non-zero indices.  This is slower as the full random permutation is required for each column.
> preprocess.randomize: Fix randomization for sparse matrices

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Dead code. Commented code. Low coverage.
Some code removed.
Coverage increased from 74% to 83%.
> [FIX] Scatter Plot: remove dead and commented code, tests

- Orange/widgets/unsupervised/owmds.py
1) Combos do not clear when data connection is removed.
2) Adding or removing subset data clears connections between similar pairs.
> [FIX] MDS: similar pairs and combos not cleared

- Orange/data/io.py
- Orange/tests/test_io.py
- Orange/widgets/data/owfile.py
- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/utils/filedialogs.py
Same extension can describe different kinds of data files.
Users can explicitly select a reader in the file dialog. If they do not, Orange uses the reader for that extension with the lowest priority.
> [ENH] owfile: allow multiple readers with same extension

- requirements-core.txt
chardet>=3.0.2 is required by requests library
> Update chardet requirement

- Orange/widgets/unsupervised/owmds.py
Move to primitive metas moved to `_setup_plot`.
`init_attr_data` called alwasy when new data.
> [FIX] MDS: primitive metas, init_attr_values

- Orange/widgets/unsupervised/owmds.py
Contrary to the overlay instructions for selections, shift-selecting did not construct a new group in the output (though the two selected groups were visually distinct in the visualization)
Data output (with added Selected column) is now constructed as in Scatter Plot.
> [ENH] owmds: Support selection/output of multiple groups

- Orange/widgets/data/owoutliers.py
Multi-class check fails when data.Y is of dimension (n, 1) or (n, 0).
Small fix of Outliers widget checking for multi-class data.
> Outlier multi-class minor fix.

- Orange/widgets/data/owcolor.py
- Orange/widgets/data/owconcatenate.py
- Orange/widgets/data/owcreateclass.py
- Orange/widgets/data/owdiscretize.py
- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/owfile.py
- Orange/widgets/data/owimpute.py
- Orange/widgets/data/owselectcolumns.py
- Orange/widgets/unsupervised/owdistancefile.py
- Orange/widgets/unsupervised/owdistancematrix.py
- Orange/widgets/unsupervised/owdistances.py
- Orange/widgets/unsupervised/owdistancetransformation.py
- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/utils/owlearnerwidget.py
- Orange/widgets/visualize/owruleviewer.py
- Orange/widgets/visualize/owsieve.py
#2514 moved Report button to the status bar.
- Widgets that explicitly positioned the button still show it.
- The layout of widgets without the Report button is changed, and sometimes doesn't look good.
Remove Report button, check and fix layouts.
> Remove explicit Report button, improve widget layouts

- Orange/canvas/report/index.html
- Orange/canvas/report/report.py
When reporting a view (or model?) through `report_table` header column and row is printed in the same format as the data values. Although there is a code that mark header columns as `<th>` (and not as `<td>`) this is invalidated by the `font-weight` attribute.
E.g. in `Test & Score` before:
and after:
Set `font-weight` to `bold` when inside header so `<th>` is not invalidated.
> [FIX] Report Table: Make Table Headers Bold

- Orange/widgets/unsupervised/owhierarchicalclustering.py
The widget is slow to respond when the selection is changed in such a way that the number of groups diminishes significantly.
Example:
File (vehicle.tab) -> Distances (Euclidean) -> Hierarchical clustering (Average)
In the *Selection* box select and set *Height ratio: 0.1%*. Switch between that and *Top N: 3* Going from Height ratio to top N is significantly slower then the other way.
The code (`set_selected_items`) had quadratic time complexity in the number of deselected items.
Fixed by a more judicious placement of calls to `_re_enumerate_selections`
> [FIX] owhierarchicalclustering: Fix performance on deselection

- Orange/widgets/visualize/owsilhouetteplot.py
Rendering issues due to QTBUG-55070:
Remove use of QGraphicsProxyWidget. Also tweak scene rect update which did not update properly when decreasing the bar height.
> [FIX] Silhouette plot rendering

- Orange/widgets/visualize/owboxplot.py
Fixes #2652.
Add a checkbox.
I would like to discuss the change (perhaps live) before merging. We will have many controls that we'll want to add to the widgets and for each we need to think whether it can be avoided, lest we end up where we were in Orange 2.
> [ENH] Boxplot: Allow hiding labels

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
> [FIX] Scatter Plot: Scatter Plot automatically sends selection

- Orange/projection/__init__.py
- Orange/projection/base.py
- Orange/projection/freeviz.py
- Orange/projection/pca.py
- Orange/tests/test_freeviz.py
- doc/data-mining-library/source/reference/projection.rst
No FreeViz projection.
FreeViz projection scripting part similar as **MDS**, **PCA**.
```python
from Orange.projection.freeviz import FreeViz
from Orange.data import Table
data = Table("iris")
freeviz = FreeViz()
model = freeviz(data)
new_data = model(data)
```
Code coverage is 98%.
> [ENH] FreeViz script

- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/utils/domaineditor.py
- Orange/widgets/utils/itemmodels.py
Many muggles don't understand what's a *string*. They know what's *text*, though.
It seems that this appears only in Domain editor, and in icons. Fixing the former is trivial. <strike>For icons, "T" is already used for time variables. However, I think it's better to have the same letter (in an icon of a different color) then having the cryptic "string".
This follows the earlier change in which discrete and continuous were replaced by categorical and numeric.</strike> Icons are not changed to avoid confusion.
> Replace string with text as variable type (in GUI only)

- Orange/data/sql/backend/mssql.py
- Orange/widgets/data/owsql.py
Added functionality to the widget:
- The widget now saves the settings of the selected table name and SQL Query 
- Restoring of table name and SQL query is also now working when opening a workflow
- Connection to the database is done earlier to allow the tables list to be fetched
- Table name is saved and restored as text (or name of table) instead of Id (as previously)
- Empty username and password are now saved as '' (empty string) instead of None. This allows the use of SQL Server's Windows authentication (use of the current user credentials if both fields are empty).
- Placing 'Custom SQL' in second in the table list in order to see it faster when the list of tables is long.
- Execute SQL query only if minimum number of chars entered
Note also:
- A bug was found within SQL Server 2012 …
> [FIX] OWSql does not save selected table/query

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Fixes #2687.
Change the output type of `Feature` to `AttributeList`. Alternatively, input could be changed to `Table` but other widget (Sieve, Select columns...) use `AttributeList`; I see little use for `Table` in these contexts.
> [RFC][FIX] OWScatterPlot: Change output Feature to AttributeList

- Orange/widgets/data/owrank.py
- Orange/widgets/data/tests/test_owrank.py
Selecting rows was sending new selections even when auto-send was unchecked.
> [FIX] OWRank: Fix autocommit

- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_itemmodels.py
DomainModel shows all variables, even those, that are marked as hidden. 
DomainModel shows only non-hidden variables by default. If `skip_hidden_vars` is set to `False`, all variables are shown.
> [ENH] DomainModel: Don't Show Hidden Variables by Default

- Orange/widgets/utils/annotated_data.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
When selecting multiple groups in scatter plot, the Selected Data output contains no indication about the group.
- Add a Groups column and corresponding tests
- Refactoring of `send_data`.
> [ENH] Add Groups column to Selected Data in Scatter plot output

- Orange/classification/elliptic_envelope.py
- Orange/widgets/data/owoutliers.py
- Orange/widgets/data/tests/test_owoutliers.py
- Outliers widget does not work with multiple classes.
- ... and crashes when variance matrices is singular, instead of reporting an error.
- `EllipticEnvelopeLearner` removes instances without classes.
Fixes #2588.
- Remove tests for classes
- Fix the crash for singular data
- Set proper preprocessors for `EllipticEnvelopeLearner`
Tests do not add much new; they passed before, too. The PR actually removes tests that checked for what shouldn't had been checked.
> [FIX] Outliers widget no longer checks classes and doesn't crash on singular covariances matrices

- Orange/preprocess/preprocess.py
- Orange/widgets/data/tests/test_owoutliers.py
- Orange/widgets/data/tests/test_owpythonscript.py
- Orange/widgets/tests/base.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
`send_signal` didn't check the type of sent value. Sending around a Learner class instead of an instance led me to a behavior that took much too long to debug. In general, widget implementors aren't expected to validate types as canvas does it for them. So should the tests.
Assert passed signal value is of correct type.
> [TST] WidgetTest.send_signal: assert signal value of correct type

- Orange/widgets/unsupervised/owmds.py
~~1. MDS cannot handle sparse data.~~ That will be fixed in #2690 .
2. Optimization runs when subset data is sent to the widget. This is not necessary.
3. Plot resets when _Show similar pairs_ slider is moved.
4. Similar pairs are not removed when _Show similar pairs_ slider is set to 0. And they should be removed.
> [FIX] MDS: No optimization when subset data

- Orange/data/table.py
- Orange/statistics/distribution.py
- Orange/statistics/util.py
- Orange/tests/test_distribution.py
- Orange/tests/test_normalize.py
- Orange/tests/test_statistics.py
The statistics module implementation of `countnans` did not support the `axis` argument. Moreover, it appeared to have been computing number of NaNs incorrectly on sparse data in general.
- Refactor `bincount` to properly count implicit and explicit zeros, with full weight support.
- Add implementation of `countnans` which correctly counts NaNs and supports the axis keyword.
- Add `dense_sparse` decorator for facilitating testing.
See #2558 for discussion.
> [FIX] Statistics.countnans/bincount: Fix NaN Counting, Consider Implicit Zeros

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
- The statistics module implementation of `unique` returned incorrectly ordered arrays in case of a negative number e.g.
```
>>> unique(csr_matrix([-1, 0, 0, 1, 2]))
array([ 0, -1,  1,  2], dtype=int64)
>>> np.unique([-1, 0, 0, 1, 2])
array([-1,  0,  1,  2])
```
- The statistics module implementation of `nanunique` did not support any parameters that `unique` supported.
Fixes above issues. This PR depends on #2698 for the `dense_sparse` testing utility.
> [FIX] Statistics.unique: Fix Sparse Return Order For Negative Numbers

- Orange/widgets/settings.py
- Orange/widgets/tests/test_context_handler.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Since gh-2301 schema_only settings are destructively cleared when used in combination with a context handler. This breaks (what I would hope to be) a valid use case
```python
class A(OWWidget):
...
bar = Setting(None, schema_only=True)
def __init__(self):
if self.bar is None:
self.bar = ...  # not loaded from a saved workflow
def foo(self):
self.closeContext()
self.openContext(...)
assert self.bar is not None
```
This state where bar is None would then be saved in a workflow.
This pattern is used in Textable add-on for issuing uuids to widgets
The same pattern is also used in OWBaseLearner widget for the learner_name but without a context handler.
I am not sure what the intent there was. Presumably the semantics of the selection restore in scatter plot, ... is such that it is only applied …
> [FIX] settings: Do not clear schema_only settings on close_context

- Orange/canvas/application/addons.py
- Orange/canvas/application/settings.py
- Orange/canvas/config.py
- scripts/windows/condainstall.bat
Some add-ons have dependencies that are a pain to install on windows. Conda makes this easier
Add-on installation/upgrading/uninstallation calls conda commands before pip. If conda command succeeds, pip says that everything is up to date/uninstalled and does nothing.
Needs testing on win/linux, with different configurations (orange installed in conda root/conda environment, orange installed beside conda, ...)
> [ENH] Add-on installation with Conda

- Orange/widgets/visualize/owscatterplotgraph.py
> [FIX] Scatter Plot: regression line: show r instead of k

- Orange/widgets/data/owdatasets.py
- Orange/widgets/data/tests/test_owdatasets.py
Filtering of data sets was not supported.
Partially reuse filtering from GEO Data Sets (Orange-Bioinformatics). Includes pulling the class TokenListCompleter to core Orange and using it in owdatasets.
> [ENH] Data Sets: Add filter

- Orange/widgets/tests/base.py
- Orange/widgets/utils/scaling.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
> [FIX] ScatterPlot Crashes on Data With Infinity Values

- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_itemmodels.py
Cannot set order and skip separators
> [ENH] Domain Model: order without separators

- Orange/canvas/application/addons.py
Add-on installation with conda crashes when conda is not found in PATH.
Use full path to conda executable.
> [FIX] Add-on installation crashes (when conda not in PATH)

- Orange/canvas/application/errorreporting.py
Error reporting uses internal pip api, which will be [moved in Pip 10](https://mail.python.org/pipermail/distutils-sig/2017-October/031642.html).
Remove use of pip internal api
> [FIX] errorreporting: Remove use of pip internal api

- Orange/widgets/unsupervised/owcorrespondence.py
- Orange/widgets/unsupervised/tests/test_owcorrespondence.py
Widget crashes when there are no categorical variables in a data.
Check and show error.
> [FIX] Correspondence Analysis: do not crash when no categorical

- Orange/data/domain.py
- Orange/tests/test_domain.py
Copying a domain is tedious.
Add `Domain.copy()` method.
> [ENH] Domain: Add copy method

- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_itemmodels.py
Fixes #2728.
Test whether a list is empty before using it for indexing an array.
> [FIX] Fix AbstractSortTableModel.mapFromSourceRows for empty list or array

- Orange/data/variable.py
- Orange/preprocess/continuize.py
- Orange/preprocess/discretize.py
- Orange/preprocess/impute.py
- Orange/preprocess/normalize.py
- Orange/preprocess/remove.py
- Orange/tests/test_discretize.py
In order to properly support sparse features, this PR introduces the `Variable.sparse` flag, which indicates that the variable suggests to be stored in sparse format.
* Add `sparse` flag to variables.
* When copying variables, copy the sparse flag as well. This is far from correct, but it should do for a start.
> Variable: Add sparse flag

- Orange/widgets/evaluate/owpredictions.py
Missing space before "(" in the name of the meta variable when concatenating the classifier name and the class name.
Space added before "("
> [FIX] Predictions: space added before bracket in meta name.

- Orange/widgets/data/owrank.py
- Orange/widgets/data/tests/test_owrank.py
Sending data without attributes results in a crashed **Rank** widget.
Error is shown.
> [FIX] Rank: should not fail on data with no attributes

- appveyor.yml
AppVeyor tests segfault at the end. Started with commit https://github.com/biolab/orange3/commit/5854208ff56968218b13431784cb8fb1eb1b17cb on 3 Nov. Updated SIP was released on 2 Nov after >three months. A likely regression.
Pin SIP and PyQt5 to a version that had worked before.
> MNT: AppVeyor: pin SIP==4.19.3 to avoid segfault

- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/tests/test_owselectrows.py
**Rank** widget crashes because receives empty `Table` and empty `Domain` which is created by **Select Rows**.
**Select Rows** commits `None`.
> [FIX] Select Rows: None on output when no data

- Orange/canvas/application/addons.py
Installation of add-ons with dragging of wheels to the add-ons dialog broke in 3.7
Fix it.
> [FIX] Broken installation of Installation of wheels

- Orange/canvas/application/errorreporting.py
Sometimes error reporting crashes when trying to prepare a string with local variables. `RecursionError` is raised. Instead of the actual error this error is sent.
> [FIX] Error Reporting: send report even when recursion error is raised

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
**Scatter Plot** VizRank crashes when _class column_ has only `nan` values.
VizRank is disabled as it is when there is no `class_var`.
> [FIX] Scatter Plot: VizRank disabled when no class vars

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
**Scatter Plot** subset data is not shown.
Works again and test added.
> [FIX] Scatter Plot: subset data

- Orange/widgets/visualize/ownomogram.py
- Orange/widgets/visualize/tests/test_ownomogram.py
* Nomogram tooltips crashing on PyQt4.
Fixed.
> [FIX] Nomogram on PyQt4

- Orange/widgets/utils/scaling.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
**Scaling** does not stack metas with other arrays when metas array has all values set to zero.
Another check for metas array.
> [FIX] Scatter Plot Graph: crash on metas column with all 0 values

- Orange/canvas/application/canvasmain.py
The 'Welcome' dialog stays open after opening an example workflow:
Help -> Welcome -> Examples -> Open
Accept and close the welcome dialog on successful load.
> [FIX] canvas/canvasmain: Fix 'Examples' action handling in the welcome dialog

- Orange/data/domain.py
- Orange/data/table.py
- Orange/data/util.py
- Orange/preprocess/discretize.py
- Orange/preprocess/impute.py
- Orange/tests/test_domain.py
- Orange/tests/test_normalize.py
- Orange/tests/test_remove.py
- Orange/tests/test_table.py
- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/data/tests/test_owmergedata.py
- Orange/widgets/model/tests/test_tree.py
- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py
- Orange/widgets/utils/itemmodels.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/owsieve.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
- Orange/widgets/visualize/tests/test_owsieve.py
Fixes #2322.
Blocked on #2734. Blocked on #2736.
* `DomainConversion` now has three extra attributes telling whether X, Y, or metas should be sparse according to the features inside of them. Metas can only be sparse if no StringVariables are present.
* `Table.from_table` determines the density of X, Y, and metas according to domain conversion.
* Add `to_sparse` and `to_dense` methods to `Table`.
* Reset variables caches to alleviate interdependencies between test files.
* Fix showing sparse metas in Table widget.
> [ENH] Improved Sparsity Handling

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
Added NaN sum and median to Orange.statistics.util for consistent computation of medians and sums for dense and sparse matrices, if the data may contain NaNs.
> Add nansum and nanmedian.

- Orange/widgets/visualize/owscatterplot.py
Fixes  #2037
1) Scatter Plot VizRank uses jittered data which is wrong.
2) Uses custom code for calculating combinations.
3) Uses indices.
4) Informative projections are ranked based on the class variable.
1) Scaled data instead of jittered data.
~~2) Uses `combinations` from `itertools`.~~
~~3) Now it uses variables instead of indices.~~
4) Informative projections are ranked based on the selected color variable.
Also added one test to increase coverage (test method `row_for_state`). Sadly code coverage is not measured when running a code in a thread and that is why test calls this specific method.
> [FIX][ENH] Scatter Plot VizRank: some fixes and regard to color

- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/tests/test_owfreeviz.py
Widget crashes when there is no data and
1) Radius slider is moved
2) Class density, etc. is changed
> [FIX] FreeViz: 2 issues when no data

- Orange/data/table.py
- Orange/widgets/data/owtranspose.py
- Orange/widgets/data/tests/test_owtranspose.py
> [ENH] Allow custom (generic) names in Transpose Widget 

- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
Widget **Test & Learn** crashes when receives data with a class which has only `nan` values. This is because all data is removed and `Table` suddenly has length `0`.
The data is set to `None` when its length is `0`.
> [FIX] Test & Learn: do not crash on a data with class only nans

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
- Tooltip shows axes variables first and then classes, metas and attributes (in that order).
- Selected variables are no longer shown twice. Number of variables shown is limited.
- The overall look is improved by using proper HTML and some bold face fonts.
- Test for tooltips are added.
> [ENH] Scatter Plot: Improve tooltips

- Orange/widgets/visualize/owpythagorastree.py
- Orange/widgets/visualize/owpythagoreanforest.py
- Orange/widgets/visualize/owtreeviewer.py
- Orange/widgets/visualize/tests/test_owpythagorastree.py
- Orange/widgets/visualize/tests/test_owpythagoreanforest.py
- Orange/widgets/visualize/tests/test_owtreegraph.py
Fixes #2797 
Tree Viewer
Pythagorean Tree
Pythagorean Forest
~~Geo Map~~
> [ENH] New signals: Trees, Forest

- Orange/widgets/data/owconcatenate.py
Since loading a workflow doesn't produce a consistent ordering, indices aren't reliable.
Use names of the tables as values of the new (optional) source variable.
(Append indices if not unique)
> owconcatenate: Use table names for values of source var

- Orange/data/table.py
Y must be type `float`, not `object`.
> [FIX] Table: classes (Y) must be float

- Orange/widgets/visualize/owscatterplotgraph.py
1) somewhere still indices are used instead of vars
2) some dead code found
> [FIX] Scatter Plot Graph: vars instead of indices & remove dead code

- Orange/canvas/canvas/items/annotationitem.py
Arrow annotations in the canvas are rendered badly on high dpi monitors. Even more so in the 'Preview' for the 'Examples' and 'Recent' dialogs. The reason for this is that `QGraphicsEffects` render indirectly 'item -> pixmap -> effect -> draw pixmap'
Workaround for QTBUG-65035
Use a  separate item for shadow base that is stacked behind the 'true' arrow geometry item.
(the same was already done for the node items in 3be3f1a4f3af147cd0b66d9510be326e0c545a42)
> [FIX] canvas/annotationitem: Use separate item for shadow base

- Orange/widgets/unsupervised/owhierarchicalclustering.py
The dendrogram can be resized below its minimum width (without horizontal scroll bars shown).
* Set minimum width constraint in the graphics view to ensure scroll bars would not be needed.
* Improve size hinting.
* Fix cutoff line/slider updates.
* Fix dendrogram font scale (zoom) initialization.
> [FIX] Hierarchical Clustering: Fix size constraints

- Orange/widgets/visualize/owscatterplotgraph.py
See https://github.com/biolab/orange3/pull/2804#pullrequestreview-81485148 fourth bullet.
> Maybe for next PR : picture and legend should have the exact same colors/symbols
Take a look at Opacity Slider, Legend, and points!
> [ENH] Scatter Plot Graph: legend opacity

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
> [ENH] Scatter Plot Graph: max discrete values colors and shape

- Orange/widgets/visualize/owheatmap.py
Heat Map does not properly size its contents when transient scroll bars are in effect
Fix size constraints to always reserve space for scroll bars.
> owheatmap: Fix size constraints to account for 'transient' scroll bars

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
Fixes #2719.
Implement `is_discrete` etc. as descriptors for instance and class attribute access to allow using them in e.g. `filter(Variable.is_discrete, domain)`.
Add an optional argument to `is_primitive`. `is_primitive` is needed a different treatment because it's a class method and not a property.
> Variable: Allow using is_* as predicates

- Orange/canvas/application/addons.py
Removing Orange/Orange3 prefix in addon names.
Use Cleanup method when creating status message.
> cleanup addon name in action status dialog

- Orange/widgets/settings.py
If a domain has just meta attributes, `DomainContextHandler` does not open a context.
I encountered this when converting the Distance map widget to use variables instead of ints. I loaded 'conferences.dst' with Distance File, and connected it to Distance map, which failed since the widget had no current context. I no longer have this problem since I had to change the widget for other reasons, but the bug may reappear elsewhere.
I can write a test if @astaric agrees with the change.
> DomainContextSetting: don't skip meta-only domains

- Orange/widgets/settings.py
Start a fresh canvas session
```
File (iris) -> Scatter Plot
```
Change (one of) the selected axis variable. Remove the *Scatter Plot* and restart canvas and create the workflow again. The previous axis selection is not restored. Change the selection again. Remove the *Scatter Plot* widget then recreate (and connect) it again. The selected axis selection is restored. Restart canvas and recreate the workflow. The selected axis selection is restored.
Make the settings persistence consistent.
> [FIX] ContextHandler: Merge local context into globals before serialization

- Orange/canvas/application/addons.py
Go to *Options -> Add-ons*, wait until it updates the packages list then close the dialog. Open *Options -> Add-ons* again. The dialog is populated immediately, but wait ~4 sec. A progress dialog shows up and does not go away until cancelled.
Create the dialog only when starting a task.
> [FIX] canvas/addons: Fix progress dialog showing up when not necessary

- .travis/install_orange.sh
- Orange/data/pandas_compat.py
- Orange/data/tests/test_pandas.py
- appveyor.yml
- requirements-opt.txt
Various third parties work with pandas.DataFrames. Missing was a convenient method of transforming result DataFrame into Orange Table.
Add `table_from_frame` utility function. No hard pandas dependencies. Please advise on the best way to run the tests.
> ENH: Add pandas_compat.table_from_frame(df)

- Orange/data/sql/backend/mssql.py
Using a string like `foo\\bar` for the server parameter crashed the widget (with an uncaught ValueError).
> [FIX] mssql: Catch errors due to incorrect connection params

- Orange/projection/manifold.py
- Orange/tests/test_manifold.py
Speed up `torgerson`
Use arpack for solving eigen decomposition in `torgerson`.
> [ENH] manifold: Use arpack for decomposition in `torgerson`

- Orange/canvas/document/schemeedit.py
CMD-backspace on Mac is a bit awkward to use
> Add a keyboard shortcut to delete a widget with "backspace"

- Orange/canvas/__main__.py
- Orange/canvas/application/canvasmain.py
- Orange/canvas/application/widgettoolbox.py
- Orange/canvas/canvas/items/annotationitem.py
- Orange/canvas/canvas/items/linkitem.py
- Orange/canvas/canvas/items/nodeitem.py
- Orange/canvas/canvas/scene.py
- Orange/canvas/document/editlinksdialog.py
- Orange/canvas/document/schemeedit.py
- Orange/canvas/gui/dropshadow.py
- Orange/canvas/gui/toolbox.py
- Orange/canvas/styles/darkorange.qss
Canvas conflicts with dark theme/styles, e.g:
* Propagate the palette in the canvas where applicable
* Use palette's colors instead of hardcoded ones
* Add an option to specify --style=fusion:breeze-dark (the palette's colors are taken from KDE's t 'Breeze Dark' theme). **This is mostly just for testing, the fusion style is not a good with dark color themes**
* Suppress the default 'orange' styling in the main window if the application palette is to dark.
<s>If deemed necessary a GUI option in the preferences dialog can also be added to select the style.</s>
> [FIX] Canvas: Palette propagation

- scripts/windows/PythonHelpers.nsh
- scripts/windows/condainstall.bat
- scripts/windows/orange-conda.nsi
- scripts/windows/orange-install.nsi
* gh-2826
* Regular 32-bit installer for Python >= 3.5 would fail to find the correct Python installation (looks for 64 bit python instead)
* Validate conda install layout
* Fix registry key lookup for 32 bit python >= 3.5
> [FIX] Windows installers: Python lookup

- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owradviz.py
See https://github.com/biolab/orange3/pull/2480#issuecomment-353300444
Changing number of vars disabled when running.
> [FIX] VizRank (Linear Projection, Radviz): spin disabled/enabled

- Orange/projection/manifold.py
`torgerson` has incorrect assert (checks for strict increasing sequence)
Relax the assert.
> [FIX] mds: Fix incorrect assert

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/owpaintdata.py
- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_itemmodels.py
- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
`DomainModel` should not allow modifying the underlying list, except through `set_domain`.
- Decorate all list methods that would modify the underlying list to raise an exception, unless they are called from within `set_domain`. This also prevents modifying the model through `setData`, `setItemData`, `insertRows` and `removeRows`.
- Fix widgets that directly changed the model: MDS, Box plot
- Add tests for `DomainModel` and `PyListModel`
- Fix detected problems in `PyListModel`:
-- fix `__add__` and `__iadd__` which didn't work at all
-- remove a bug in `_is_index_valid`, refactor it, add checks to detect models broken by misuse of `wrap` (see #2771); current implementation used an additional argument to circumvent the potential bugs
-- remove unnecessary use of `wrap` in Edit domain
> DomainModel: Prevent modification except through set_domain

- Orange/widgets/visualize/owboxplot.py
Switching between selections of nominal and continuous variables in BoxPlot causes a resize of "Variable" and "Subgroups" listViews due to a different set of available display controls.
Set boxes containing display controls for nominal and continuous variables to equal heights.
> OWBoxPlot: prevent unwanted resizing of listViews

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
Utility version of `bincount` crashed on sparse vector of all NaNs.
> [FIX] Bincount: Fix crash on array with all nans

- Orange/widgets/visualize/owradviz.py
- doc/visual-programming/source/widgets/visualize/radviz.rst
See https://github.com/biolab/orange3/pull/2480#issuecomment-352015805 :
> we should support regression data in vizrank
Regression data supported.
> [FIX] Radviz: enable VizRank numeric color (class)

- Orange/widgets/widget.py
Since gh-2743 *Data Sets*, *Predictions* and *GO Browser* (from Bioinformatics add-on) raise a
```
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/widget.py", line 575, in showEvent
self.splitter.setControlAreaVisible(self.controlAreaVisible)
AttributeError: 'QSplitter' object has no attribute 'setControlAreaVisible'
```
Because they assign `self.splitter = ...`
Rename `OWWidget.splitter` to `OWWidget.__splitter`
> [FIX] OWWidget: Move 'splitter' to private members

- Orange/widgets/utils/webview.py
This reverts commit 6f7c4392b23374ebde88ade62a9457dd5972d30f.
Fixes https://github.com/biolab/orange3-prototypes/issues/113
> Revert "WebEngineView: delay showing the widget a bit"

- Orange/data/variable.py
Depending on your chosen IDE, type checker or Mk I eyeball, the Variable.is_{discrete,...} might be unrecognized.
Define the descriptors/predicates in the class body to make it more friendly for code completion and type hinting/checking.
> [ENH] Variable: Simplify the is_{discrete,continuous,...} implementation

- Orange/widgets/unsupervised/owdistances.py
- Orange/widgets/unsupervised/tests/test_owdistances.py
Add a 'Normalize' check box to the *Distances* widget GUI to enable/disable the `normalized` parameter to the metrics that support it.
> [ENH] owdistances: Add 'Normalize' check box

- Orange/canvas/__main__.py
- Orange/canvas/application/addons.py
Some clients (like requests, pip) don't detect proxy configuration that is not set via `http_proxy` environment variables.
We set proxy via environment for add-ons before, but it shouldn't hurt to just set it always? According to [getproxies()](https://docs.python.org/3/library/urllib.request.html#urllib.request.getproxies), if env vars are set, this is no-op. But on Windows/macOS, it ~~should~~might make a difference.
> canvas: always set http_proxy environment variables if proxy detected

- Orange/widgets/data/owpaintdata.py
Unable to adjust symbol size like, for example, in Scatter Plot widget.
Add another horizontal slider which controls symbol size.
> Add option to adjust symbol size

- Orange/widgets/utils/concurrent.py
- Orange/widgets/utils/tests/test_concurrent.py
It is possible that a client passes a empty futures list to `FutureSetWatcher`. In this case the `doneAll` signal is not emitted which might cause the client to never resume progress it it does not handle the empty futures list.
Ensure a `doneAll` signal is emitted even for an empty futures list.
> [FIX] utils/concurrent: Handle an empty futures list

- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/unsupervised/tests/test_owmds.py
> [FIX] Add labels to combo when data comes from distance matrix

- Orange/projection/__init__.py
- Orange/projection/lda.py
- Orange/tests/test_lda.py
- doc/data-mining-library/source/reference/projection.rst
No **Linear Discriminant Analysis** projection scripting part.
Scripting part written like **PCA** or **FreeViz**.
> [ENH] Linear Discriminant Analysis: scripting part

- Orange/canvas/application/addons.py
- Orange/canvas/application/settings.py
- Orange/canvas/config.py
install add-ons with Conda `false` by default
Changing install add-ons with Conda to be `true` by default.
> Enable Conda for installing add-ons by default

- Orange/canvas/application/canvasmain.py
- Orange/canvas/canvas/view.py
- Orange/canvas/document/schemeedit.py
Zooming is currently rather rigid. There is also no zooming out.
Add zooming by ⌘+scroll; zooming is continuous on trackpads, and discrete with mouse.
Add zooming by ⌘+ and ⌘- ,and reset by ⌘0.
Remove the zoom toggle button from the toolbar.
> [ENH] Canvas: Add zoom

- Orange/widgets/unsupervised/owmanifoldlearning.py
The Manifold Learning widget did provide tSNE, yet lacked all the important parameters with which to tune the embedding. Most notably, I find `learning_rate` to be the most important parameter and has a huge effect on the result.
Add relevant parameters (perplexity, early exaggeration, learning rate, max iterations and initialization).
> [ENH] Add parameters and similarity measures to tSNE

- Orange/data/domain.py
- Orange/data/table.py
- Orange/data/tests/test_domain.py
- Orange/evaluation/testing.py
- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/tests/test_domain_context_handler.py
- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/ownomogram.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_ownomogram.py
**Based on #2866 (1 commit). You may want to merge that request first.**
#2866 fixes an issue with labels in MDS that occured since `self.data.domain` was `False` for a `Domain` with only meta attributes. This occurs since `Domain.__len__` (correctly) returns the number of elements that `Domain.__iter__` iterates across, however, `Domain.__iter__` (incorrectly) ignores metas.
The issue will remain even after we fix `Domain.__iter__`: when checking whether a domain is true, we usually mean whether it's not `None`.
`Domain` has a new method, `empty`.
`__bool__` warns that it's ambiguous and suggests using either `empty` or `is None`. The behaviour of `__bool__` is unchanged - it returns `True` if the lenght of the domain is non-zero.
> Add Domain.empty, add warning to Domain.__bool__

- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owradviz.py
Thanks to @markotoplak and his new widget (https://github.com/biolab/orange3-prototypes/pull/117) a new issue has been found.
Data in widgets **Radviz**, **FreeViz**, and **Linear Projection** is not transformed properly. Data indices are not preserved.
Use `Table.transform`.
> [FIX] Projection widgets: transform data properly

- Orange/tests/test_doctest.py
Numpy 1.14 changed array str/repr causing doctest failures.
Skip doctests when using numpy >= 1.14
> [TST] tests: Skip doctests when using numpy>=1.14

- Orange/canvas/registry/discovery.py
When a widget module cannot be imported because a dependency is missing, Orange silently ignores the error (unless log level is manually increased).
Change log level of the message to error so they are always shown.
> discovery: log errors during import as errors

- Orange/__init__.py
- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
- Orange/widgets/model/owloadmodel.py
- Orange/widgets/model/owsavemodel.py
- Orange/widgets/model/tests/test_owloadmodel.py
- conda-recipe/meta.yaml
- requirements-core.txt
- scripts/macos/requirements.txt
- scripts/windows/specs/PY34-win32.txt
Fixes gh-2686
* Make owfetureconsctructior.FeatureFunc picklable
* Change how discrete variable's symbolic values are captured in the resulting lambda (via closure and not argument list).
* Remove dill as a dependency
> [FIX] Feature Constructor: Make FeatureFunc picklable

- Orange/widgets/data/owimpute.py
- Orange/widgets/data/tests/test_owimpute.py
```
File ---------------> Impute
^
Random forest ------/
```
Change some  individual variable imputer to *Model based (Random forest)*
Remove the *Impute* widget. Create a new *Impute* widget and connect it to *File* again (without connecting it to any learner):
```
File ---> Impute
```
with the same file opened in *File*. The *Impute* widget restores the variables' state as *model  (Random forest)* but there is no Random forest input.
The problem is that Impute stores actual constructed `Imputer` instances in its settings.
Explicitly model what the widget does and not only its (by) products.
> [FIX] Impute: Fix state serialization/restore

- Orange/misc/environ.py
- Orange/widgets/widget.py
The annoying quicktip overlays are displayed again on every minor version upgrade.
Store the displayed state in non versioned directory.
> [FIX] OWWidget: Store quicktip displayed state in non versioned settings dir

- Orange/canvas/application/addons.py
- Orange/canvas/application/canvasmain.py
- Orange/canvas/application/settings.py
- Orange/canvas/config.py
Installing add-ons as a normal user raises PermissionErrors on Windows 
Removed user_install option (pip's --user) because:
- it does not work with conda installers
- possible clashes between different installers
- the user_install check did not work in some cases (system-wide Win7
conda install)
Now Orange checks if it can write in site-packages folder. If it can not, it shows a warning instead of the add-on dialog.
> Add-ons: show warning on insufficient permissions

- Orange/canvas/application/addons.py
Add-on with has a new checkbox which by default hides unofficial add-ons.
Installed add-ons are always shown.
> [ENH] Add-ons: Option to list only trusted add-ons

- Orange/widgets/tests/test_widget.py
- Orange/widgets/widget.py
When widget declares want_basic_layout = False, __splitter is not set causing an error in showEvent.
Check whether __splitter exists before modifying it.
> widget: Do not restore __splitter if there is None

- Orange/canvas/__main__.py
- Orange/canvas/application/settings.py
- Orange/canvas/config.py
Users can now specify proxy settings in the Settings dialog
> [ENH] Settings for HTTP and HTTPS proxies in the canvas

- Orange/widgets/gui.py
Pressing Enter in line edit should show the user that the data has
been "entered". Selecting the field seems better than clearing the focus
because (1) it allows the field to be easily re-edited (maybe the user
just wanted to see the efects of her change) and because (2) we do not
lose the focus position (moving or field forward or backward is easy).
This is also what QSpinBox does on Enter.
> LineEditWFocusOut: Pressing enters selects text

- Orange/canvas/canvas/items/linkitem.py
I think displaying the actual position of the data flow is very useful, but the yellow color was so hard to notice that many people didn't even know about this feature. Red is definitely visible (although not colorblind friendly), but now it looks a bit funny because the sinkIndicator layer is below the shield. It could be considered to change the color of the whole input shield while the flow is pending or move the sinkIndicator layer above the shield.
Change the Qt.yellow color to Qt.red
> Change the color of the sinkIndicator while LinkItem is pending

- Orange/canvas/application/canvasmain.py
When an ows file is dropped on canvas window, nothing happens.
When an ows file is dropped on canvas window, it is opened.
> [ENH] canvas: Open dropped ows files

- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/utils/domaineditor.py
When two files that contain numeric/text feature with the same name are concatenated, the resulting table contains one variable with all values.
When variable type in file widget was changed to numeric/text via domain editor, variables are considered different and result in two columns after concatenation.
Use make to construct new variables in domain editor
> domain editor: make continuous/string variables

- Orange/widgets/data/owdatasets.py
Load data in a separate method so subclasses can modify that more easily.
> owdatasets: Load data in a separate method (for extensibility)

- Orange/widgets/visualize/owscatterplotgraph.py
Fixes #2683
Default vertical spacing is 6. Anything below 5 seems to mess up the spacing. 6 looks ok, so use that.
Screenshot of changes on same data from issue.
> [FIX] SPG Legend: Fix vertical spacing

- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/tests/test_owselectrows.py
- doc/visual-programming/source/widgets/data/selectrows.rst
Widget outputted only selected or unselected data, whereas in a number of cases one would benefit to have data with the Selected column, especially if selection would be performed on a combination or continuous meta attribute(s) and then used to test if we can predict the grouping.
Added an output channel (Data).
> [ENH] Select Rows: Add annotated data output

- Orange/widgets/data/owtable.py
- Orange/widgets/utils/itemmodels.py
Data Table is slow when it displays large a large table with large selection.
* Avoid enumerating all QModenIndex's in the selection; use QItemSelectionRange's
* Remove one proxying layer in favor of subclassing to minimize QModelIndex mappings.
* Use Qt5 layout change hinting in TableModel.
> [ENH] Data Table: Optimize performance

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
Contingency did not allow weights since our old bottlechest implementation of bincount (probably) did not support them. As our current bincount handles weights just fine, there is no need for the error anymore
Remove weights check in contingency, pass weights to bincount.
> contingency: allow weights

- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
K-means executed everything in the main GUI thread, leading to freezing when processing large datasets. Moreover, the computation started as soon as any data was connected, so connecting large datasets was, again, problematic.
Offload all the computation into separate threads, and start clustering only when Apply is clicked (or checkbox is checked).
Also some general refactoring, to improve consistency with other, newer widgets.
As far as I can tell, and the tests were written, the behavior remained the same as before (other than the time of execution).
@ales-erjavec Could you take a look at this please, since you're the thread master? I wasn't sure how to go about testing threaded code, is this method ok?
> OWKMeans: Perform clustering in worker threads

- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/tests/test_owheatmap.py
Heatmap with column clustering crashes when data contains a column an all-zero column.
Column clustering is done using Pearson distance which is nan for a column of all zeros.
Convert non-finite values to finite using np.nan_to_num. This results in zero feature being clustered with a random other feature, but the rest of the clustering should make sense.
> [FIX] heatmap: Do not crash on all zero column

- Orange/classification/sgd.py
- Orange/regression/linear.py
- Orange/widgets/model/owsgd.py
SGDClassificationLearner deprecated parameter (n_iter). Fixes #2917.
Deprecation fix: changed n_iter to max_iter (SGDClassifier)
> [FIX] sgd: Change deprecated n_iter to max_iter

- Orange/data/table.py
- Orange/tests/test_table.py
Table.from_table copied data matrices even if domain attributes did not
change. This increases memory usage for each conversion. As many widgets
output annotated data, each instance of such widgets made a copy of the
data.
This commit tries to convert indices into slices, which allows numpy to
reuse the original array.
> Optimize selection indices in Table (save memory)

- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
Binary scores were evaluated with target class when no target class was selected
This PR is fixing binary scores to use weighted scoring when no target class is selected
> [FIX] Test and Score: Fix averaging over classes for binary scores

- Orange/data/_valuecount.pyx
- Orange/statistics/contingency.py
- Orange/statistics/distribution.py
- Orange/tests/test_contingency.py
- Orange/tests/test_distribution.py
#2680, but without 7d675ba. Apparently force-pushing on a closed PR makes it impossible to re-open it, hence the new PR... @kernc could you take a look?
The function `class_distribution` was apparently never used throughout the entire codebase and was never tested, and the parameter ordering was incorrect.
af5a1c7 fixes the mentioned issue. The other commits add various tests, docstrings and code formatting fixes. I've also added a better `sample` method, similar to the python `random.sample`. I've also added `min` and `max` for ordered categorical variables.
> [FIX] distribution.py: Fix computation on multiclass data

- Orange/distance/distance.py
- Orange/tests/test_distances.py
* PearsonR is poorly implemented by a double for loop in python.
* SpearmanR quadruples it's workload only to throw most of it away. 
* Use `numpy.corrcoef` for PearsonR
* Implement a variants of corrcoef/spearmanr which compute correlations between two arrays more efficiently (without also computing all correlations within the two arrays).
> [ENH] Distances: Optimize PearsonR/SpearmanR

- Orange/widgets/data/owdatasampler.py
- Orange/widgets/data/tests/test_owdatasampler.py
- doc/visual-programming/source/widgets/data/datasampler.rst
Fixes #2850
Changes:
1. Set instances' limit when there is data and replacement is chosen;
2. Remove instances' limit otherwise;
3. Warn if sample with replacement is bigger than input.
Refactoring:
1. Extract 2 ** 31 - 1 constant;
2. Clear warnings when errors are cleared.
> Allow oversampling in Data Sampler widget

- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
#2926
Resort values based on the sort columns when scores change.
> [FIX] Test & Score: Resort scores when data changes

- Orange/widgets/io.py
- Orange/widgets/utils/SVGExporter.py
SVG export does not work on Qt5.
Changed two lines in the pyqtgraph. Including the file here as pyqtgraph rarely releases. This PR included a modified pyqtgraph/exporters/SVGExporter.py from PyQtGraph that included proposed fixes
pyqtgraph/pyqtgraph#641 and pyqtgraph/pyqtgraph#642
> [FIX] Save Image to SVG fixed on Qt5

- Orange/widgets/unsupervised/owkmeans.py
*K-Means* output connections saved in a workflow with Orange <= 3.10 cannot be restored.
Record the old name in the `replaces` parameter.
> owkmeans: Add `replaces` for the recently changed output name

- Orange/widgets/evaluate/owtestlearners.py
The scores table in *Test & Score* is editable (via a double click on a cell) since gh-1421.
Make it non-editable.
> [FIX] Test & Score: Make the scores view table non-editable

- scripts/windows/condainstall.bat
Almost half the lines in condainstall.bat were workarounds to make it work with conda 4.1. Since conda 4.1 is not available for python3.6 (included in installer), this PR drops support for it. conda 4.2 has been available for the past year and a half, which should be enough time.
When a new environment is created with no packages (supported in conda 4.2+), activate, deactivate and conda scripts are automatically created.
I also removed the separate installation of python into the created environment and I get no errors. If I missed something, let me know. 
Fixes #2921
> conda installer: drop support for conda 4.1

- Orange/widgets/data/owdatasets.py
https://github.com/biolab/orange3-single-cell/issues/121
Split large chunk of code into smaller methods, so we can easily override them.
Moved item model creation in a separate method.
> OWDataSets: refactor code, move some functionalities to new methods

- Orange/widgets/visualize/utils/__init__.py
*File -> Scatter Plot*
Run the vizrank dialog (on fairly large data), while the vizrank still runs delete the scatter plot from the canvas. The following error occurs:
```
--------------------------- RuntimeError Exception ----------------------------
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/visualize/utils/__init__.py", line 169, in <lambda>
vizrank.selectionChanged.connect(lambda args: set_attr_callback(*args))
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/visualize/owscatterplot.py", line 371, in set_attr
self.attr_x, self.attr_y = attr_x, attr_y
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/gui.py", line 182, in __setattr__
callback(value)
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/gui.py", line …
```
> [FIX] Vizrank: Properly shutdown/wait when parent deleted

- Orange/base.py
Improves #2957 
Convert an Instance to a Table with a single row right from the start. Handling a Table with a single instance seems to be more efficient than handling an individual Instance, which results in several conversions to a Table anyway.
Speed-up in the case mentioned in #2957 is by more than a factor of 7.
> [FIX] Speed-up prediction by circumventing Instance-specific prediction.

- Orange/statistics/util.py
Alleviates gh-2925
* Optimize countans for sparse matrices
> [ENH] statistics: Speed up countnans for sparse matrices

- Orange/widgets/data/owselectrows.py
By default *Select Rows* widget should not do more then what is says on the tin.
(references gh-2925)
Change the defaults for purging to False.
> [ENH] owselectrows: Change defaults for 'Purging'

- Orange/data/table.py
C library can allocates memory in a way where is not returned to the system and therefore the python process seems to leak memory (which is not true - the space can be reused by the same python process). At least on linux, this depends on size of allocated memory:
http://www.gnu.org/software/libc/manual/html_node/Malloc-Tunable-Parameters.htm
My file had 16384 instances and 1608 features. Therefore for SklImpute, from_table internally copied size 16384 array 1608 times, which is afterwards not be released to the system.
With parameter `MALLOC_MMAP_THRESHOLD_` (from the link above) I can get different kinds of behavior for my program:
1. export MALLOC_MMAP_THRESHOLD_=130000 - force mmap for my ids arrays - final memory usage: **131 MB**
2. export MALLOC_MMAP_THRESHOLD_=200000 - force the …
> Table.from_table: do not copy ids or weights

- Orange/canvas/application/addons.py
Orange3-Bioinformatics does not list as trusted. Bioinformatics add-on prior to version 3.0.0 is not supported anymore.
> addons: remove support for old bioinformatics

- Orange/widgets/utils/domaineditor.py
OWFile creates a uncollectable ref cycle by connecting the [VarTableModel.dataChanged](https://github.com/biolab/orange3/blob/468e3faae26ff7115bcae190241cdd888edca2f7/Orange/widgets/data/owfile.py#L212) to a lambda capturing self (and the VarTableModel instance) in the closure.
Make the VarTableModel a child of the DomainEditor so it is destroyed with it.
> [FIX] domaineditor: Give the VarTableModel a parent

- Orange/canvas/scheme/widgetsscheme.py
When the canvas editor creates a new workflow (via *New* or *Open* actions) the old OWWidgets are not deleted (promptly or even ever), like they are when explicitly deleted from the workflow.
Call deleteLater for managed widgets when the whole workflow is discarded.
> [FIX] WidgetManager: Schedule delayed deletion for managed OWWidgets

- Orange/widgets/gui.py
ControlledList is created behind the back by gui.listBox and commonly used as a setting which gets synced into a GLOBAL SettingsHandler which keeps the OWWidget instance alive via a reference in listBox (see gui.listBox)
Take a weak ref to the listBox
> [FIX] gui.ControlledList: Take a weakref to listBox

- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
- An issue pointed out by @ales-erjavec in #2901 :
>run optimization for 2 to (say) 10 clusters, uncheck 'Apply Automatically', increase "From" to 5. At this point the 'Silhouette Scores' table is not updated. Select '2' from the scores table (or '3' just as long as it causes a send_data to be called). On the output is a data table with 7 clusters.
- KMeans reclusters data when metas or class_vars change, even when X doesn't.
Fix both issues. Based on #2901. Remove possibility of crash on settings migrations (not that this ever happened)
> [FIX] KMeans clear results on k change, do not recluster

- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
Fixes #2945 (hopefully) @markotoplak 
I tried to be sneaky and dummy out KMeans since the widget shouldn't be testing the validity of Kmeans clustering, but that quickly turned out to be more complicated than you would want a test to be, so I simply extended the timeout to 5 seconds, as is defined for the [other tests that use a timeout](https://github.com/biolab/orange3/blob/master/Orange/widgets/tests/base.py#L45).
> Kmeans test timeout

- Orange/data/io.py
- Orange/tests/test_tab_reader.py
* fixes gh-1297
* Replace linear search in string -> index mapping for discrete columns.
* Generally speed up parsing ( ~50% improvement depending on the data)
> [FIX] Fix data reading speed

- Orange/widgets/visualize/owsieve.py
The longer the horizontal label, the more white space between the vertical label and the sieve rectangle. Try it on any data with long attribute names.
See the code.
> [FIX] Sieve Diagram: Fix spacing of axis labels

- Orange/data/io.py
- Orange/tests/test_tab_reader.py
Fixes gh-2293 and fixes gh-2956
* Increase the sample for csv dialect inference
* Use only the delimiter and quotechar from the inferred dialect.
> [FIX] Fix reading double quoted text fields

- Orange/widgets/data/owdiscretize.py
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/owimpute.py
- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/owtranspose.py
- Orange/widgets/gui.py
- Orange/widgets/unsupervised/owcorrespondence.py
- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/listfilter.py
- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owsilhouetteplot.py
- Orange/widgets/visualize/owvenndiagram.py
Variable selection/display or large (wide) tables is slow.
Related to gh-2972
* Set uniformItemSizes property on QListViews where appropriate
* Remove reimplementation of PyListModel.index. The default implementations in QAbstractListItemModel is sufficient and faster (it does call rowCount once for every created index).
> [ENH] Variable lists (with QListView) optimizations

- Orange/widgets/settings.py
module members not included in `__all__` are considered private.
SettingProvider is used in widgets to declare subcomponents and should
therefore be included in `__all__`.
> settings: include SettingProvider in __all__

- Orange/canvas/application/addons.py
The add-ons dialog can not find add-ons after the pypi.org server upgrade (#3001).
pypi announcement: https://mail.python.org/mm3/archives/list/pypi-announce@python.org/thread/JCNO7SWQTKY54MKOZQ22PV3TUJGRM3GR/
Official add-on list is now hosted on orange.biolab.si
> [FIX] Add-ons working again (PyPI JSON interface + local official index)

- Orange/canvas/application/addons.py
Allow adding add-ons not listed in the default list.
Allow entry of extra add-ons/packages via a name entry dialog.
> [ENH] canvas/add-ons: Add extra packages via a name input dialog

- .travis/install_orange.sh
Travis unitests fails since Pandas in the latest versions do not support Python3.4
Downgraded Pandas to version 0.20.3 which is the last version that supports Python3.4 for tests that run in Python3.4
> travis: pin pandas to 0.20.3 for Python3.4 tests

- Orange/widgets/gui.py
- Orange/widgets/tests/test_gui.py
FloatSliders can show a different values than stored (sometimes they are moved 1 step too much towards left). @stuart-cls, for the report.
Method set_value now avoid the // operator which can return wrong
results:
1.0//0.5 = 2 (as expected, what we would want)
1.0//0.05 = 19 (we would like to see 20 there)
> FloatSlider: fix rounding of values

- Orange/widgets/data/owdiscretize.py
*Discretize* widgets has quadratic complexity just in constructing the output domain.
Noticeable for instance on geo-gds360 dataset with the 'Leave numeric' default discretization and no individual variable overrides.
Remove the awkward linear search for the source variable in `discretized_var` method.
> [FIX] owdiscretize: Fix quadratic complexitiy in the n variables

- Orange/widgets/data/owdatainfo.py
- Orange/widgets/data/tests/test_owdatainfo.py
Some data in orange contain meta information about the data table. For instance, bioinformatics add-on passes the data on the organism or location of gene names by adding this information in .attributes field of the Orange data table. While this information is used in practically all bioinformatics widgets, there is no widget that would explicitly display this information.
The box Data Attributes was added to the widget.
> [ENH] Data Info widget displays data attributes

- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
When labels are wider than their respective bars in a boxplot, labels overlap:
Limit  (all but the last) label width to the width of the bar they are labelling. Hide labels for very short bars (unless the whole label can be displayed in available space).
> [FIX] boxplot labels overlap

- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
When feature expression in feature constructor widget contained anything else than simple variable names, they were not restored when opening a saved workflow.
Update matching logic to support variable names containing special characters and usage of builtin functions.
> [FIX] Feature constructor did not restore features when loading from saved workflow

- Orange/canvas/application/addons.py
Fixes gh-2101
Restore state after adding packages to the dialog (via Drag/drop or 'Add more...' dialog)
> [FIX] Add-ons dialog: Restore state

- Orange/canvas/__main__.py
- Orange/canvas/application/canvasmain.py
- Orange/canvas/application/errorreporting.py
- Orange/canvas/application/outputview.py
- Orange/canvas/config.py
- Orange/canvas/registry/cache.py
- Orange/canvas/scheme/widgetsscheme.py
- Orange/widgets/report/owreport.py
- Orange/widgets/report/report.py
Canvas does not support multiple open windows/workflows.
Implement multi window/workflow editing.
* CanvasMainWindow is responsible for creating and managing new instances. This is somewhat wrong and might be improved by implementing something like a controller/manager in the future.
* Log and Help views should probably be moved to separate singleton instances?
> [ENH] Implement multi window editing

- Orange/widgets/visualize/owscatterplotgraph.py
Fixes gh-2955
Use correct (unmodified) data source
> [FIX] owscatterplot: Use correct data for regression line

- Orange/canvas/application/addons.py
Add-ons are in unpredictable order https://github.com/biolab/orange3/issues/3007
Sorting add-ons in the alphabetical order
> [FIX] Sorting add-ons in the alphabetical order

- Orange/widgets/data/owselectcolumns.py
*Select Attributes* has severe performance degradation on filtering a long list of variables (in the *Available* view) when all the variables are selected.
For example:
*File ('geo-gds360')* -> *Select Attributes*
move all variables to *Available* view, press <kbd>Ctrl + A</kbd> and enter any text in the *Filter*
* Coalesce the calls to `update_interface_state` using a single shot timer.
> [FIX] owselectcolumns: Fix performance on filtering with selection

- Orange/widgets/visualize/tests/test_owmosaic.py
VizRank tests for OWMosaic leave threads running after test completion influencing other tests via reduced performance and resulting TimeoutErrors.
For instance, run in bash:
```bash
$ python -m unittest  Orange.widgets.visualize.tests.test_owmosaic.MosaicVizRankTests{,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,}
```
Cleanup/join threads on test tear down
> [FIX] test_owmosaic: Cleanup/join threads on test tear down

- Orange/widgets/tests/base.py
Sometimes tests seemingly [deadlock](https://travis-ci.org/biolab/orange3/jobs/383185760#L4309) but in reality it they spin (really sleep) in `WidgetTest.process_events` way past the real timeout (due to improper time keeping).
Use [`time.perf_counter`](https://docs.python.org/3/library/time.html#time.perf_counter) not `time.clock`. `clock` is deprecated and platform dependent, but mostly does not measure time
spent in sleep.
> [FIX] tests: Fix time tracking in process_events

- Orange/widgets/gui.py
The QComboBox popup sometimes hides immediately after being displayed. For this to happen the model displayed in the combo box must be sufficiently large and/or slow so that the popup display is somewhat delayed ([QTBUG-67583](https://bugreports.qt.io/browse/QTBUG-67583)).
Implement a workaround for QTBUG-67583
> [FIX] gui: Suppress mouse button release on the combo box popup

- Orange/widgets/data/owselectcolumns.py
- Orange/widgets/data/tests/test_owselectcolumns.py
- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_itemmodels.py
Drag/Drop between *Select Columns* list views is slow (as noticed in gh-3030)
Reintroduce efficient drag/drop in *Select Columns*
> [FIX] Select Columns: Drag/drop

- Orange/widgets/visualize/owheatmap.py
Heat map didn't allow labeling rows by TimeVariable.
Enable labeling by TimeVariable.
> [FIX] Heat Map: Allow labeling by TimeVariable

- Orange/widgets/visualize/utils/__init__.py
There was a race condition in the `toggle` method where VizRank could
be left without a running worker thread. This could happen between
setting `keep_running` from False to True and subsequent call to
`QThread.start`. The worker could read `keep_running` as False right
before that and not yet exit before the call to start. Then start would
be a noop and the thread would stop right after.
This manifests in a sometimes failing `Orange.widgets.visualize.tests.test_owmosaic.MosaicVizRankTests.test_pause_continue`
Fix by explicitly joining the thread on 'pause' as a synchronization point.
> [FIX] VizRank: Fix race condition in `toggle`

- Orange/canvas/application/canvasmain.py
- Orange/canvas/config.py
- Orange/canvas/scheme/widgetsscheme.py
When Canvas gets focus, all widgets get hidden behind it
View -> Float Widgets on Top flag to show widgets on top of all other windows.
> [ENH] Display Widgets on Top option

- Orange/base.py
- Orange/classification/neural_network.py
- Orange/modelling/neural_network.py
- Orange/regression/neural_network.py
- Orange/widgets/model/owneuralnetwork.py
- Orange/widgets/tests/base.py
In general, long computation shouldn't leave the GUI unresponsive. But the real issue is that I am not sure I can write threaded widgets, so I tried.
Implemented with the help of @ales-erjavec's example from the documentation with minor changes. Callbacks with scikit-learn are very hackish though. Does anybody have a better idea?
Just to test stopping, I also added a cancel button to the widget. Perhaps all interruptible widget should get a stop icon in the status bar and perhaps also some actionable "icon" on the canvas.
> [ENH] Neural network widget that works in a separate thread

- Orange/widgets/utils/listfilter.py
Inline filter completion in the Select Columns widget does not work.
Make QCompleter a child of the filter line edit.
> [FIX] listfilter: Fix filter line edit completion

- Orange/widgets/data/owdatasets.py
Alternative to gh-2767
Use `uniformRowHeights` property on `QTreeView` and reimplement item delegate's `sizeHint` for the first column to always include the icon.
> OWDatasets: Force uniform row heights in the view

- Orange/widgets/utils/annotated_data.py
- Orange/widgets/utils/tests/test_annotated_data.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
> [FIX] OWScatterOWScatterPlotGraph: Match group colors with marker colors

- Orange/classification/_simple_tree.c
> [FIX] BSD compatibility patch

- Orange/data/io.py
- Orange/widgets/utils/filedialogs.py
1. Saving with compression was prevented due to a file format extension check that used only the last extension (in e.g. file.tab.gz)
2. Compression was not supported when saving and loading in pickle format
3. Changed default extension for PickleReader from .pickle to the shorter .pkl (both were supported before and still are).
> [ENH] Save data with compression

- Orange/canvas/application/canvasmain.py
- Orange/canvas/scheme/widgetsscheme.py
On some platforms (Windows, Gnome) setting window flags and/or hide/show implicitly triggers
application deactivate/reactivate, triggering an endless back and forth
state changes. This can outright seemingly freeze desktop shell.
Remove window flags modification on application state change.
> [FIX] Canvas: Fix 'Widgest on top'

- Orange/canvas/application/canvasmain.py
- Orange/canvas/document/commands.py
- Orange/canvas/document/schemeedit.py
- Orange/canvas/scheme/readwrite.py
- Orange/canvas/scheme/widgetsscheme.py
- Orange/widgets/tests/test_widget.py
- Orange/widgets/widget.py
Partially implements gh-3048 
Implement storing of current open widgets geometry and layout state as window group presets.
> [ENH] Canvas: Window Groups

- Orange/__init__.py
The chosen approach was seen in
https://github.com/spyder-ide/spyder/pull/7029/files
#3092
The hack tries to load a shared library `libGL.so.1`
> [FIX] Workaround for segfaults with Nvidia on Linux

- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
Initialization (random or k-means++) was wrongly passed from widget to the library.
> [FIX] owkmeans: fix initialization choice

- Orange/widgets/visualize/owmosaic.py
Mosaic crashes if the user selects a string meta attribute as one of the variables.
A check is_primitive was used as a property but is in fact a method.
> [FIX] OWMosaic: Don't offer String meta attributes

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Fixes #2776 
Add TimeVariableEditor and update variable_description and variable_from_description to correctly handle TimeVariables.
> [FIX] EditDomain: Editing TimeVariable broke formatting

- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/tests/test_owmergedata.py
Fixes #2927
Add autocommit button.
> [ENH] MergeData: add autocommit button

- Orange/clustering/kmeans.py
- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
test_silhouette_column in test_owkmeans.py is a common cause of timeout on AppVeyor.
Decrease the number of samples used for silhouette computation in unit tests.
> OWKMeans: Speed-up silhouette test.

- Orange/widgets/data/owrank.py
- allow change of selection method from All to Manual
- add selection method and selected_rows to context settings
> [FIX] OWRank: Select Attributes fixes and improvements

- Orange/data/sql/backend/postgres.py
- Orange/tests/sql/test_sql_table.py
Fixes #3108 
Remove traling spaces.
> [FIX] postgres: Fix wrong discrete values

- Orange/widgets/data/oweditdomain.py
Fixes #3031
Add up/down arrows to rearrange the order of values of discrete variables.
> [ENH] OWEditDomain: Enable reordering of discrete variables

- Orange/data/io.py
Speed `write_data`.
Assemble column formatters beforehand, avoid inline logic deciding the
correct format for every cell value.
> [ENH] io: Speedup write_data

- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
Fixes #3094 
Groups that have zero elements are no longer shown.
> [RFC][FIX] BoxPlot: Hide groups with no instances

- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
#3103
Fixes #3075
K-means now always uses the same random seed and outputs the same data
> owkmeans: always use the same random seed

- Orange/canvas/application/canvasmain.py
`basedir` points to the parent directory of the basedir.
`basedir` changed to actually point to the base directory.
> Fixed workflow basedir when saving

- Orange/canvas/gui/dock.py
- Orange/canvas/gui/tests/test_lineedit.py
- Orange/canvas/gui/tests/test_toolbox.py
The `QStyle.standardPixmap` method is obsolete and will/should disappear in the future (http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html#deprecated-features)
* Use `standardIcon` method
* Also fix the *inverse* icon rendering in widget tool dock's header.
> [FIX] Replace use of obsolete QStyle.standardPixmap

- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
OWKMeans showed an uncaught error when given data with no attributes.
Check if input data has attributes, if not show error.
> OWKMeans: add error for data with no features

- appveyor.yml
Test on appveyor are failing
* Pin scikit-learn to 0.19.1 for Python 3.4 tests
* Bump numpy to 1.14 for the rest
Fixes failing tests due to incompatibility of scikit-learn 0.19.2
wheels with older numpy abi.
> [FIX] ci/appveyor: Update test dependencies

- Orange/canvas/application/canvasmain.py
- Orange/canvas/document/interactions.py
- Orange/canvas/document/quickmenu.py
- Orange/canvas/document/schemeedit.py
- Orange/canvas/document/suggestions.py
When adding an input or output to a widget, the suggested widgets in the search window follow a default ordering, regardless of which widget is being extended (aside incompatible widgets being filtered out).
Addition of Suggestions singleton class, which tracks which widgets the user most often connects, ordering the widgets presented in the 'quick menu' search tab accordingly.
> [ENH] Smart widget suggestions

- Orange/widgets/report/report.py
- Orange/widgets/utils/webview.py
1. _evalJS of WebEngine ignores the returned value since 3b11a9090b3111d0052faa8617e015de3ccdc1f7.
2. Report_plot doesn't work for webview (although it should).
1. Store ids together with results in IdStore for scheduled JS executions.
2. Unsuccessful search for `<svg>` tag results in ValueError (and not IndexError).
> [FIX] WebView fixes

- Orange/clustering/kmeans.py
- Orange/tests/test_clustering_kmeans.py
Fixes #2913 
Additionally, I noticed that you can not predict sparse data.
Replaced `len(X)` with `X.shape[0]`.
> [FIX][RFC] KMeans upgrade sparse support

- Orange/widgets/report/report.py
report_table sometimes incorrectly displays the number of hidden rows (e.g. in the word enrichment widget).
Minor bug fix.
> [FIX] report: Fix the number of hidden rows.

- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/utils/filedialogs.py
- Orange/widgets/utils/tests/test_filedialogs.py
When opening saved workflow and file widget detects missing file, check if the file is placed in the same directory as workflow is saved.
> [ENH] RecentFiles: Check for missing file in workflow dir

- Orange/widgets/visualize/owboxplot.py
Ref gh-1737
* Fix axis label formating.
* Tighter quartiles label layout
The first and third quartile labels can still fall out of view. To fix that would pretty much involve a complete rewrite.
> [FIX] OWBoxPlot: Plot axis labels and quartiles label layout

- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
Ref gh-1737
Fix quartiles computation
The code assumed that all quartiles would (or need to) be distinct.
Replace the linear scan in BoxPlot constructor with a numpy based implementation.
> [FIX] OWBoxPlot: Fix quartiles computation

- Orange/widgets/utils/concurrent.py
Fixes gh-3079, gh-3050
The default stack size of QThreadPool created threads is insufficient
to call OpenBLAS in common builds (see numpy issue 11551).
> [FIX] utils/concurrent: Switch default thread pool

- Orange/preprocess/score.py
Fixes #3129.
Replace Imputer preprocessor with SklImputer.
> [ENH] Rank: SklScorer should use the faster SklImputer.

- Orange/widgets/tests/test_widget.py
- Orange/widgets/widget.py
Implements gh-3144
Collapse/expand the widget on control area toggle by the control area width
> [ENH] OWWidget: Collapse/expand the widget on control area toggle

- Orange/data/__init__.py
- Orange/data/filter.py
It would be convenient to access filters in the same way as other classes from the data module.
```
import Orange
tab = Orange.data.Table("iris")
filter = Orange.data.SameValue("petal length", 5.1)
print(len(filter(tab)))
```
Import everything from filters in `data/__init__.py`.
> [ENH] Make filters available in Orange.data namespace.

- Orange/widgets/unsupervised/owlouvainclustering.py
The
`Orange.widgets.unsupervised.tests.test_owlouvain.TestOWLouvain.test_clusters_ordered_by_size` test errors randomly with:
```
ERROR: test_clusters_ordered_by_size (Orange.widgets.unsupervised.tests.test_owlouvain.TestOWLouvain)
Cluster names should be sorted based on the number of instances.
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/unsupervised/tests/test_owlouvain.py", line 47, in test_clusters_ordered_by_size
clustering = output.get_column_view('Cluster')[0].astype(int)
AttributeError: 'NoneType' object has no attribute 'get_column_view' …
```
> [FIX] owlouvainclustering: Make the task completion handler a single slot

- Orange/widgets/data/owsql.py
- Orange/widgets/data/tests/test_owsql.py
Fixes #3043 
SqlTable has poor support for non-PostgreSQL databases. This enforces the download of the selected table so that it works as a normal Table.
> [FIX] OWSql: enforce data download for non PostgreSQL databases

- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
A wrong check for empty continuous contingencies omits groups that it should not.
For instance on:  [vowel.tab.txt](https://github.com/biolab/orange3/files/2235833/vowel.tab.txt)
on variable: f0, group by: Class
Fix check for empty continuous contingency, add asserts where contingencies are summed over.
> [FIX] OWBoxPlot: Fix empty continuous contingency check

- Orange/data/pandas_compat.py
- Orange/data/tests/test_pandas.py
Convert Orange.data.Table instance to pandas dataframe
> [ENH] Add pandas_compat.table_to_frame(tab)

- Orange/widgets/visualize/owfreeviz.py
Fixes #2910 
Before on data change, freeviz displayed class density only for a small rectangle around the data points and not for the full window. Additionally, I noticed the same behavior when changing color, opacity and jittering options. This fixes all of those problems.
> [FIX] OWFreeViz: fix class density size

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
'Edit Domain' widget raises a:
```
---------------------------- IndexError Exception -----------------------------
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/oweditdomain.py", line 425, in on_value_selection_changed
i = self.values_edit.selectionModel().selectedRows()[0].row()
IndexError: list index out of range
```
... when editing a discrete variable and the current item in the 'Values' list view is deselected (via a <kbd>Ctrl</kbd> + mouse click or when selecting a different variable to edit in the left 'Domain Features' view.
Check for an empty selection.
> [FIX] oweditdomain: Fix an IndexError when all rows are deselected

- Orange/canvas/canvas/items/linkitem.py
- Orange/canvas/document/commands.py
- Orange/canvas/document/schemeedit.py
Insert a widget in-between two already connected widgets by either:
- dragging it from the widget selection menu onto the link,
- right-clicking the link and selecting 'Insert Widget'
- Added an 'Insert Node' command for purposes of undo/redo
- Added entry to 'right-click on link' context menu
- Widget drag from menu -> insert
> [ENH] Widget Insertion

- Orange/tests/__init__.py
- Orange/tests/test_contingency.py
- Orange/tests/test_distribution.py
Tests fail to run with numpy 1.15
E.g.
```
ERROR: test_discrete (Orange.tests.test_contingency.TestDiscrete)
File "/Users/aleserjavec/workspace/orange3/Orange/tests/test_contingency.py", line 22, in test_discrete
np.testing.assert_almost_equal(cont["amphibian"], [4, 0])
File "/Users/aleserjavec/workspace/numpy/numpy/testing/_private/utils.py", line 568, in assert_almost_equal
return assert_array_almost_equal(actual, desired, decimal, err_msg)
File "/Users/aleserjavec/workspace/numpy/numpy/testing/_private/utils.py", line 964, in assert_array_almost_equal
precision=decimal)
File …
```
> [MNT] tests: Fix compatibility with numpy.testing in numpy 1.15

- Orange/data/io.py
- Orange/data/table.py
- Orange/tests/test_io.py
- Orange/tests/test_tab_reader.py
Fixes #3087
Changed `io.sanitize_variable` to always use `Variable.make`.
> Data without specified column names can now be concatenated

- scripts/macos/create-dmg-installer.sh
- scripts/macos/python-framework.sh
- scripts/macos/sign-app.sh
- scripts/macos/sign-dmg.sh
Separate the application build and signing step so that an existing .app build can be signed. This is to better support CI test and build
* Change sign-app.sh to accept a .app directory on the input.
* Change python-framework.sh to fix the 'Current' version symlink (used to be done by sign-app.sh)
* Add --sign option to create-dmg-installer.sh script.
* Add a new sign-dmg.sh script that signs an existing unsigned application installer.
> [MNT] Improve macOS application signing

- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
Implements #3093.
Added option (checkbox) to allow sorting discrete distributions by their size. If checkbox is unchecked, original order is preserved.
> [ENH] OWBoxPlot: add option to sort discrete distributions by size

- Orange/data/io.py
- Orange/widgets/data/owsave.py
- Orange/widgets/data/tests/test_owsave.py
Resolves issue #3136 
Updated widget according to above issue. 
Does not include changes for biolab/orange3-network#80.
> [ENH] Selection of format and compression in save data widget

- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/utils/plot/owplotgui.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owfreeviz.py
- Orange/widgets/visualize/tests/test_owlinearprojection.py
- Orange/widgets/visualize/tests/test_owradviz.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
- doc/visual-programming/source/widgets/visualize/scatterplot.rst
Implements #3028 
Scatterplot computes the set of indices at each coordinate for later use in compute_sizes and compute_colors. The sizes are multiplied by log_2 of the number of points. The color represents the most frequent color (or one of them if there are several).
> [ENH] Scatterplot: indicate overlap of points.

- Orange/tests/test_evaluation_scoring.py
- Orange/widgets/io.py
- Orange/widgets/tests/test_io.py
- Orange/widgets/tests/test_matplotlib_export.py
- Orange/widgets/utils/matplotlib_export.py
- Orange/widgets/visualize/owscatterplot.py
- conda-recipe/meta.yaml
- requirements-gui.txt
- scripts/macos/requirements.txt
- scripts/windows/specs/PY34-win32.txt
Our outputs are ugly and non-configurable. Outputting python code could solve output flexibility problem for people with basic programming knowledge. 
The changes here just enable the user to save graphs as Python code. Currently a pyplot plot is drawn directly.
The code gets the data for drawing from the pyqtgraph's graph.
> [ENH] Matplotlib output for Scatter plot

- Orange/canvas/application/widgettoolbox.py
- Orange/canvas/document/schemeedit.py
- Orange/widgets/unsupervised/owhierarchicalclustering.py
This does not address a particular open issue.
Please consider this small PR to clean up some `if` statements in the project. I addressed two small problems:
1. The condition `if not parent is not None:` was difficult to read, so I recommend replacing with `if parent is None` (removing the double-negative)
2. There are a few places in the project where the convention `if <something> == True` is used. This can lead to subtle and silent issues (`1 == True` returns `True` while `1 is True` returns `False`)
Thank you for considering this PR!
> Fixed usage of `== True` in if statements

- Orange/data/variable.py
- Orange/tests/test_value.py
Values of StringVariable are hashed incorrectly (fixes #2912).
Values of DiscreteVariable are impossible to hash as dictated by the `__eq__` function. For example:
```
from Orange.data.variable import *
val = Value(DiscreteVariable("var", ["red","green","blue"]), 1)
print(val == 1, hash(val) == hash(1))  # True True
print(val == "green", hash(val) == hash("green"))  # True False
```
As we can not make `hash(1) == hash("green")`, we prevent hashing of Values of DiscreteVariables with an exception. Users should hash directly ids or domain values instead.
This might break things that use dictionaries or sets of Values. However, the tests didn't discover any such cases.
> [FIX] Variable: Prevent hashing of Values of DiscreteVariable.

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
`Orange.statistics.util` missing implementation of standard deviation.
Add the equivalent of `np.std` that also supports sparse matrices. Also, I ordered the imports in the test file.
> Sparse utils: Add std

- Orange/canvas/application/canvasmain.py
- Orange/widgets/data/owfile.py
- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/utils/filedialogs.py
File widget does not find file when opening the scheme generated on other computer. 
The file is moved together with the ows in the zip, the file should be on the same relative path than on computer where scheme generated.
In this PR, I enabled relative path generation before the scheme is saved.
> OWFile: Fix paths, file on relative path can be found on other computer

- Orange/canvas/canvas/items/annotationitem.py
- requirements-gui.txt
CommonMark release 0.8.0 breaks on case insensitive file systems (rtfd/CommonMark-py#134)
* Remove CommonMark dependency and markdown support
> canvas: Remove CommonMark dependency and markdown support

- Orange/widgets/data/owtable.py
Implements #3161 - adds a "deselect all" functionality to the top left corner button in Data Table.
As far as I can tell, the current "select all" functionality is actually built in by default, i.e. `clicked` is connected to a `selectAll()` call (please correct me if I'm wrong).  
This commit disconnects the default handler and connects a new one, which decides whether to **select all** (`selectAll()`) or **deselect all** (`clearSelection()`) data based on information about selected rows and columns.
> [ENH] Data Table: Enable deselection

- Orange/data/io.py
- Orange/tests/test_io.py
Fixes #1471 
Orange can't load fils where there are more data then header columns
Strip data columns
> [FIX] io: Handle mismatched number of header/data values

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
Fixes gh-3238
* Return proxies from DiscreteVariable.make (as already done in gh-2667 for other variables)
* Ensure `var.values` are preserved exactly on deserialization, even at the expanse of variable 'equality'.  This is done to ensure any indices into the `values` list, that are serialized alongside the variable, retain their meaning.
> [FIX] DiscreteVariable reconstruction

- Orange/widgets/evaluate/owrocanalysis.py
- Orange/widgets/evaluate/tests/test_owrocanalysis.py
- Orange/widgets/tests/utils.py
- Orange/widgets/utils/tests/test_combobox.py
Implements #3057.
When mouse is put over a point on ROC curve, the threshold that was used for calculation now appears. If threshold value is _nan_, the value does not get shown. Also, the displaying of thresholds is currently not implemented when showing individual curves.
My questions:
- currently thresholds are displayed when mouse goes 'perfectly' over a point - should this be changed so that they get displayed if mouse is in some very small radius of the point?
- what kind of a test do I write for this functionality (i. e. mouse events) - if any?
General comments are also welcome.
> [ENH] ROC analysis: show thresholds

- Orange/canvas/help/provider.py
#3247 
Follow redirects if Qt supports it.
> [FIX] Documentation fetching with redirects

- Orange/widgets/widget.py
Some widgets open with wrong initial position and size (see https://github.com/biolab/orange3/issues/3240#issuecomment-420569822)
* Fix OWWidget._Splitter size hinting. 
* Force invalidation of cached size hints before showing the widget.
> [FIX] OWWidget: Fix size hint propagation

- Orange/widgets/visualize/utils/__init__.py
**Issue**: user can edit the table in VizRank. 
**Description of changes**: Prevent it.
**Includes**: A new argument in initialization of the view
Fixes the first half of #3255.
> Vizrank: Disable editing of vizrank table

- Orange/widgets/data/owselectbydataindex.py
- Orange/widgets/data/tests/test_owselectbydataindex.py
- doc/visual-programming/source/widgets/data/select-by-data-index.rst
After transformation of the data such as PCA and then selecting some of the transformed data, users wish to remove the selected instances from the original data.
Added two outputs to Select by Data Index widget. Don't be shy If you remember better names for these outputs.
> owselectbydataindex: also output unmatched data

- Orange/canvas/gui/tests/test_utils.py
- Orange/canvas/gui/utils.py
Disabling updates may be useful for widgets that make a lot of subsequent changes, for instance putting a lot of labels on a pyqtgraph plot. Existing `updates_disabled` is a context manager, yet in practice we can often disable updates for entire methods. It is more practical to do so with decorators -- if for no other reason, it reduces the indentation.
The function is changed into a class with appropriate methods for context managing and calling (as decorator).
**Question:** Does this belong to Orange.**canvas**.gui.utils or is there a better place outside canvas? Widgets should (strive to) not import things from the canvas.
> utils.updates_disabled: Make it a decorator as well

- Orange/widgets/settings.py
- Orange/widgets/tests/test_context_handler.py
- doc/development/source/tutorial-settings.rst
A context may become invalid after some changes in the widget, e.g. removing discrete attributes from the scatter plot.
If `migrate_context` raises `IncompatibleContext`, the context is deleted.
> Settings migration: Allow rejecting a context

- Orange/widgets/unsupervised/owlouvainclustering.py
- Orange/widgets/unsupervised/tests/test_owlouvain.py
- Orange/widgets/widget.py
- appveyor.yml
There are race conditions in the Louvain clustering widget. 
The `pca_projection`, `graph` and `partitions` attributes are accessed and set directly from threads. In particular from the already 'cancelled' jobs. The code does not wait for cancelled jobs to finish, but they do modify the computed partial results. This can lead to undefined final results
on the output.
I can trigger this reliably by:
File: *wdbc.tab*
Louvain Clustering (both):
* Apply PCA is checked: 20 components
* Euclidean distance
* k neighbors: 10
* Resolution 2.5
* Apply automatically is checked
Python script contents:
```python
import numpy as np
d1, d2 = in_datas
c1, _ = d1.get_column_view("Cluster")
c2, _ = d2.get_column_view("Cluster")
assert np.array_equal(c1, c2)
```
In one of the Louvain clustering widgets tab …
> [FIX] owlouvainclustering: Fix race conditions

- Orange/widgets/data/owtable.py
- Orange/widgets/data/tests/test_owtable.py
Fixes #3261 
On domain change, selections should be reset.
Set selection settings to schema only.
> [FIX] OWDataTable: reset selections on domain change

- Orange/statistics/util.py
`Orange.statistics.util.bincount` was raising a deprecation warning
```
Orange/statistics/util.py:144: DeprecationWarning: 0 should be passed as minlength instead of None; this will error in future.
x.astype(np.int32, copy=False), weights=weights, minlength=minlength
```
Fixup deprecation warning.
> Statistics.utils: Fixup bincount numpy deprecation warning

- Orange/widgets/data/owrank.py
- Orange/widgets/data/owselectcolumns.py
- Orange/widgets/data/tests/test_owrank.py
- Orange/widgets/data/tests/test_owselectcolumns.py
Enable filtering dataset using selected features.
Implements #3300
- Upgrade Select Columns widget to accept Features on the input (as AttributeList). One can choose between using input features and data domain features to obtain output data. New button "Use input features" is added for this purpose. When features appear on the input, the button enables. After the features have been used, the "Features" list box disables.
The initial state is can be obtained by clicking "Reset" button.
- Upgrade Rank widget to output Features (as AttributeList).
> [ENH] OWSelectAttributes: Use input features

- Orange/data/io.py
- Orange/tests/test_io.py
Tests on all PRs will fail until this is merged, I guess. (Except for PRs based on this one).
From 3.18, tests fail because of deprecated arguments.
Remove deprecated arguments and the tests that were made to trigger a failure in 3.18.
> data.io.sanitize_variable: Remove deprecated arguments

- Orange/tests/test_linear_regression.py
Fixes #3355
Check that coefficients are (almost) equal directly instead of summing the difference.
> test_linear_regression: Improve a test of equal coefficients

- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/tests/test_owfreeviz.py
- Orange/widgets/visualize/utils/widget.py
The widget crashed when received dataset with missing values on the input.
> [FIX]OWFreeViz: Fix optimization for data with missing values

- Orange/widgets/tests/test_credentials.py
- requirements-core.txt
The test is dependent on system configuration
Use a minimal in-memory keyring implementation for the test.
Also update the numpy version in the requirements.
> [FIX] Use minimal keyring implementation for tests

- Orange/preprocess/preprocess.py
- Orange/widgets/tests/base.py
`sklearn.preprocessing.Imputer` has been deprecated in favour of `sklearn.impute.SimpleImputer`
EDIT: It seems that the two classes are not completely the same - in particular, the new one validates the data first and rejects np.inf values, while the old one just silently dropped that column.
Thus, most methods that imputed the data first (e.g. MDS), now raise an error in such cases. Which is fine, since inf values are not officially supported in Orange data tables (e.g. one cannot load a saved dataset that contained np.inf).
The second commit drops the inf dataset from a collection used for general testing of "annoying" data.
> preprocess: Update deprecated sklearn import (Imputer->SimpleImputer)

- Orange/widgets/unsupervised/owlouvainclustering.py
- Orange/widgets/unsupervised/tests/test_owlouvain.py
> [FIX] Louvain Clustering: Do not invalidate output on PCA slider change with apply disabled

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
I predictor fails, it sets results to a string describing an error. When `_call_predictors` is called again, it tests for ` pred.results is None or numpy.isnan(pred.results[0]).all()`, which crashes because `pred.results` is a string.
Test for `isinstance(pred.results, str)` and treat it as `None` or all nans.
> [FIX] Predictions: Fix failure after failed predictor

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
VizRank crashes when the data includes non-primitive meta attributes. Most notably, it crashes on Brown data!
When reimplementing projections, we removed the obsolete `graph.scaled_data`. Vizrank, which used to get the attributes from `graph.scaled_data.domain`, now takes them from widget's `data.domain`, but does not filter out primitive attributes (which it didn't have to do before, since `scaled_data` did not include them).
Add the check and the tests.
> [FIX] Scatterplot's VizRank no longer crashes in presence of nonprimitive metas

- Orange/widgets/visualize/tests/test_owprojectionwidget.py
- Orange/widgets/visualize/utils/widget.py
Fixes #3353.
`OWProjectionWidgetBase.get_tooltip` is called with indices of valid data points only, and the method did not skip invalid data.
> [FIX] Fix wrong indices in tooltips in projection when some data was invalid

- requirements-core.txt
Bump the required version of scikit-learn to 0.20.
(Contains the new impute module among other things...)
> requirements-core: Bump scikit-learn version

- .travis.yml
Updates the travis test matrix as follows:
Remove travis testing for Python 3.4.
Py3.5 is used only in conjunction with PyQt4 in a single "legacy" test.
The main testing is done using Py3.6.
There is also a Py3.7 test, which requires some additional travis parameters (see https://github.com/travis-ci/travis-ci/issues/9815).
Fixes #3341
> travis: Update test matrix

- Orange/widgets/tests/base.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owradviz.py
If the original data had missing values, and the embedding is therefore not available for all points, missing values should be assigned to those points instead of zeros.
Assign np.nan-s to embedding instead of zeros.
> Projections: Assign missing values to embedding

- Orange/projection/manifold.py
- Orange/tests/test_manifold.py
- Orange/widgets/unsupervised/owmanifoldlearning.py
- Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py
- appveyor.yml
- conda-recipe/meta.yaml
- requirements-core.txt
Scikit learn's implementation of tSNE is slow. It only supports the Barnes-Hut approximation. Adding new data to an existing embedding is not supported by and existing tSNE implementation.
Implement wrappers around my implementation of tSNE which includes both Barnes-Hut for small data sets and the interpolation based tSNE recently introduced which runs in linear time for larger data sets.
We can also now add new data points to an existing embedding by running optimization on those points only, w.r.t. the existing embedding.
Also, I've never packaged anything to pypi yet, and I've had a fair number of issues with this, but *hopefully* it's all ok now.
> [ENH] Replace scikit-learn tSNE with faster implementation

- scripts/macos/python-framework.sh
From https://github.com/biolab/orange3/issues/3370#issuecomment-437041569
> It looks to me that the python-framework.py script would create a new symlink inside the Current folder if the symlink already exists.
This is exactly what happens
Do not follow target if it already exists and points to a directory
> [FIX] python-framework.sh: Fix 'Current' symlink creation

- .travis.yml
- appveyor.yml
Since nobody objected and argued for support of older versions, we can remove the legacy test as well (py 3.5, pyqt4).
Currently everything should still work with those versions, but new features are coming that make use of pyqt5 (#3303) and conda is not building new packages for py 3.5 for over a month.
> CI: Remove legacy testing (py 3.5, pyqt4)

- .travis/build_doc.sh
See: https://github.com/biolab/orange3/pull/3345#issuecomment-437463620
Probable cause:
egg_info command used to be invoked during .travis/install_orange.sh
(as a sub-command of setuptool's sdist; since gh-3345 plain distutils
sdist is used)
Run egg_info command during in-place install
> [MNT] travis: Fix in-place install for building widget catalog

- Orange/preprocess/score.py
- Orange/tests/test_logistic_regression.py
- Orange/tests/test_score_feature.py
Ranking with a Scores did not work if the data was preprocessed with PCA (or anything else). Saving and loading the data (and thus obtaining primitive features) helped.
Search for original attributes in score-joining function used to go all the way up to primitive features. Now it stops when it comes to a feature from the input data.
> [FIX] LearnerScorer: fix for preprocessed data

- scripts/windows/condainstall.bat
conda 4.5 no longer installs activate.bat and conda.bat in the created environment.
Fixes gh-3375
Add conda.bat and activate.bat scripts again.
> [FIX] condainstall.bat: Add conda.bat and activate.bat scripts again

- Orange/base.py
- Orange/data/table.py
- Orange/tests/test_classification.py
- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
- Domain transformations in Test and Score (and Predictions?) are implicit. Users should be informed about them.
- Test and Score shows this exception as a user-readable error (without mentioning "domains")
- If train and test data have different domains but transformation does not result in all-nans, an information about the transformation appears.
> Test and Score: Warn about transformation, raise error if all is nan

- Orange/widgets/data/owdatasets.py
We have added support for HTTPS on domain datasets.biolab.si. Certificates are auto-renewed by Cloudflare, no more letsencrypt scripts. The datasets can be cached on Cloudflare.
This PR has to be merged before, otherwise urllib library will print warnings: https://github.com/biolab/serverfiles/pull/5
> Switch index url for datasets widget.

- Orange/widgets/visualize/owpythagorastree.py
- Orange/widgets/visualize/pythagorastreeviewer.py
- Orange/widgets/visualize/utils/tree/skltreeadapter.py
- Orange/widgets/visualize/utils/tree/treeadapter.py
Fixes #3330.
Implemented two new features that should enable visualizations of Pythagorean trees with less overlap:
- Add a button to completely redraw the tree with a random left/right ordering of children (this should give a user a good starting point).
- Double click on a node reverses the order of its children (for manual fine-tuning).
> [ENH] Pythagorean Tree: children order

- Orange/canvas/application/errorreporting.py
https://github.com/biolab/orange3/issues/3369
Orange check if it can connect to the server. If the server is available (~ user has an internet connection) it reports an error otherwise it just warns the user about the error.
> Fix: Orange does not report to the server when no internet connection

- Orange/projection/manifold.py
- Orange/widgets/unsupervised/owtsne.py
- Orange/widgets/unsupervised/tests/test_owtsne.py
Implements third part of #3342
> [ENH] tSNE: Output preprocessor

- Orange/preprocess/score.py
- Orange/tests/test_logistic_regression.py
I first noticed this issue on Kickstarted data (from the Datasets). There Rank with Random forest produced strange results. The feature "Type", has 7 values, is the root of a decision tree built on these data. But then, surprisingly, it gets very low rankings with Random forest. 
As often, this problem is caused by RandomForestsLearner not supporting nominal features. They are continuized. For learners that need continuization, a discrete feature is transformed to multiple continuous features. A learner then returns scores for each continuous feature, which need to be joined somehow. Currently, Orange uses mean value to join them, which seems not to be such a good idea.
This commit changes the joining function to max. because a feature is at least as important as its most important value. …
> LearnerScorer: join derived features by max value

- Orange/widgets/data/owdatainfo.py
No data set name displayed in the info box. This could be important when checking if the names of the data sets are set correctly.
Includes the box with the data set name.
> [ENH] Data Info display data set name

- Orange/widgets/settings.py
- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/tests/test_owmosaic.py
Fixes #3283 
Best if reviewed one commit at a time.
Change to DomainModels was not trivial because widget uses discretized data. Models are filled with original domain so that variables have the right icons, but the widget then has to convert variables from original to discretized and back.
PR also includes some refactoring. `interior_coloring` was declared as setting, yet it served just as an attribute and was not even needed since it was synonymous with `variable_color is None`.
I also reduced the number of lines to 1000. :)
> Modify Mosaic widget to use domain models

- .travis/build_doc.sh
- .travis/upload_doc.sh
Updated travis scripts to fix the following error:
ssh: connect to host orange.biolab.si port 22: Cannot assign requested address
SSH to orange.biolab.si failed, because traffic is routed through Cloudflare.
It is replaced with a different domain that points directly to virtual machine (no proxies).
orange.biolab.si -> biolab.si
Additional fix: Cloudflare does not support subsubdomains, replaced with a subdomain with equivalent config (redirect to orange.biolab.si/docs).
docs.orange.biolab.si -> docs.biolab.si
> Travis stage_after_success.sh fails.

- Orange/data/table.py
- Orange/tests/test_table.py
- Orange/widgets/data/owfile.py
Fixes issue #3157.
Info Box in widget File now displays the same information as the info box in widget Data Table
> [FIX] File: Provide percent missing values in Info box

- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/unsupervised/owtsne.py
- Orange/widgets/unsupervised/tests/test_owtsne.py
- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/plot/owplotgui.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owlinearprojection.py
- Orange/widgets/visualize/tests/test_owradviz.py
- Orange/widgets/visualize/utils/widget.py
Embedding was recalculated and the graph reploted even though the variables used remain the same with new input data.
Adjust OWDataProjectionWidget not to recalculate the embedding. 
Consider MDS separately since it takes two inputs (DataTable, DistMatrix).
Fix OWRadViz and OWLinearProjection not to plot data until available features list box is set.
> [FIX] Projections: Retain embedding if non-relevant variables change

- Orange/widgets/visualize/owscatterplotgraph.py
When reimplementing networks, I have put locks on `ScatterPlotItem`'s `paint` (see the [commit](https://github.com/janezd/orange3/commit/0c8080401b181f6bb2d5338c23c7723ffe468a99)). As @ales-erjavec explained later, Qt's graphics' paint must execute in the main thread, so this lock has no effect. This PR reverts the change.
> Projections: Remove locks from ScatterPlotItem

- Orange/widgets/tests/base.py
- Orange/widgets/visualize/utils/widget.py
When widget received (unchanged) data with missing values on the input (i.e. Reloading the file) the embedding was recalculated.
When comparing previous and current table.X, consider np.nan-s equal.
> [FIX] OWDataProjectionWidget: Consider tables with nan-s equal

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
- Orange/widgets/visualize/utils/widget.py
> [ENH] OWScatterPlotBase: Animate dot resize

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
The plot was not repainted when the widget received Features on the input.
> [FIX] Scatter Plot: Replot when input Features

- Orange/widgets/data/owsave.py
Save Data doesn't change the writer when the user changes the extension.
Upon changing the extension, writer is set accordingly.
> [FIX] Save Data: Reset writer upon changing the extension

- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/unsupervised/owtsne.py
- Orange/widgets/utils/plot/owplotgui.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/utils/widget.py
After reimplementing projections, the reference to an instance of `OWPlotGui` remained on the plot although it is actually used by the widget. This PR moves it where it belongs.
Justification for the move is obvious from the diff. :)
> Projections: Move OWPlotGUI instance from graph to widget

- Orange/widgets/visualize/owscatterplot.py
When inputing features and data into Scatterplot at the same time handleNewSignals() is invoked only once (handleNewSignals() then calls setup_plot()). Therefore attr_x and attr_y, set from settings, could be the same as input features and self.setup_plot() would never be called.
Always call self.attr_changed() when receiving Features on the input.
> [FIX] Scatter Plot: Always setup plot

- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/owtsne.py
> [FIX]t-SNE: Generate temporary projection data

- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/tests/test_owradviz.py
- Orange/widgets/visualize/utils/widget.py
If selecting less than two features (in features list box) to create projection, a warning is shown, which indicates inadequate setting and therefore should not be saved.
> [FIX] Radviz: Enable projection for less than two selected variables

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
> [ENH] Remove discrete attributes from scatter plot's axes

- Orange/preprocess/fss.py
- Orange/preprocess/score.py
- Orange/widgets/data/tests/test_owrank.py
OWRank crashed when input dataset with missing values (i.e. testing_dataset_cls, testing_dataset_reg).
> [FIX] Rank: Fix crash on dataset with missing values

- Orange/widgets/data/owfeaturestatistics.py
An issue popped up on sentry where Feature Statistics was crashing. This can be reproduced in the following way:
1. Open a workflow and connect File with some data to Feature Statistics and save the workflow
2. Remove/rename the data file in question so that the File widget can no longer find it
3. Re-open the workflow in Orange → Feature statistics crash
Fixes the bug. I have no idea how to test this, or indeed, how this even happened because this issue never occurred when disconnecting data. In both cases, the input signal data was set to `None`.
> [FIX] OWFeatureStatistics: Don't attempt to sort when no data on input

- Orange/projection/manifold.py
t-SNE spits out various user warnings. We've properly wrapped it in Orange, so these are completely unnecessary.
Disable loggers for `fastTSNE` module.
> t-SNE: Disable library user warnings

- Orange/canvas/scheme/widgetsscheme.py
An occasional `NameError: free variable 'name' referenced before assignment in enclosing scope` can be observed when running with debug logging level.
Remove use of QObject.destroyed for logging. Use weakref.finalize instead.
> [FIX] canvas/widgetsscheme: Remove use of QObject.destroyed for logging

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Scatterplot's Vizrank still adds discrete attributes, but scatter plot crashes when they're chosen.
Change the condition in vizrank filter from `is_primitive()` to `is_continuous`.
> [FIX] Scatterplot Vizrank: Don't use discrete variables

- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/tests/test_owlinearprojection.py
Variables in list box should be set before self.__invalidated flag is calculated.
Rebase to master when #3444 is merged.
> Linear Projection: Setup model_selected before calculating __invalidated

- Orange/widgets/visualize/icons/LinePlot.svg
- Orange/widgets/visualize/owlineplot.py
- Orange/widgets/visualize/tests/test_owlineplot.py
> [ENH] OWLinePlot: Move from prototypes to core

- Orange/data/io.py
- Orange/widgets/data/owsave.py
- Orange/widgets/data/tests/test_owsave.py
- requirements-core.txt
Implements #3096.
Continued from #3306.
Remove support for .ods, since it didn't work.
Implement simple save to Excel, support only .xslx (xlwt didn't work with .xslx).
> [ENH] Save Data: Support saving to Excel

- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owsieve.py
- Orange/widgets/visualize/tests/test_owmosaic.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
- Orange/widgets/visualize/tests/test_owsieve.py
- Orange/widgets/visualize/utils/__init__.py
#3255, second part. The problem can be re-viewed from a different perspective: the problem is that after the user selects something in VizRank, he can change the selection in the widget, while VizRank still incorrectly highlights the previously selected combination of attributes.
With this in mind, the correct solution is as follows.
As the user changes the selection in the widget, the widget emits signal that the attributes have been changed. Its vizrank highlights the newly selected combination if it exists, otherwise it clears the selection.
Caveat: if the user changes the selection while vizrank is running, nothing bad will happen. However, if the combination (s)he selected has not been evaluated by VizRank *yet*, it will not be highlighted neither at that moment (obviously) nor …
> Selection of attributes in the widget is reflected in VizRank

- conda-recipe/meta.yaml
- requirements-core.txt
The next version of fastTSNE (not yet released) includes a slight API change, which would cause tests to fail in current master.
To avoid any failing tests, I fix `fastTSNE==0.2.13` here (this is the latest release).
Once this is merged, I can release a new fastTSNE version, update the wrapper here and update the requirements.
>  Set requirements to fastTSNE==0.2.13, scikit-learn>=0.20.0

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owprojectionwidget.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
- Orange/widgets/visualize/utils/widget.py
It makes no sense to show > 500 labels. If there are too many, visualization becomes unresponsive.
Don't show labels if there are too many -- in the visible part of the plot. Show warning instead.
Graph communicates with widgets through signals. It's pretty awkward, but I see no better alternative. I wouldn't like to add methods to master or even directly access `self.master.Warning`.
> OWScatterPlotBase: Hide labels if there are too many

- Orange/widgets/data/owfeaturestatistics.py
As of the latest versions of scipy, `scipy.stats.mode` does not work on sparse data.
A quick fix so the tests aren't constantly failing. Will work on a more efficient solution shortly.
@janezd
> [FIX] OWFeatureStatistics: Fix scipy.stats.mode crash on sparse data

- Orange/distance/distance.py
Spearman distance fails on Scipy 1.2 because of stats.spearmanr failing when given a single matrix with a single row.
This distance should always return 0, so we can just hard code it.
> Spearman distances: Return 0 when comparing a single row to itself

- scripts/create_widget_catalog.py
create_widget_catalog.py segfaults when Python is freeing memory.
It seems that removing numpy helped - it almost always crashed before, and never crashed after. Numpy was used just to create a table with 50*50*4 zeros. `b"\x00" * 50 * 50 *4"` works just as well.
While searching for the problem I reordered the import order to match that in `canvas.__main__`. I kept it reordered.
I also added `QApplication.setAttribute(Qt.AA_ShareOpenGLContexts)`, as recommended in the output. This flag has to be set before `QApplication` to have an effect. I don't know about other flags, but I moved them, too.
> [FIX][MNT] Remove segfault in tests for building documentation

- Orange/widgets/utils/widgetpreview.py
When canvas is run from shell, it can be quit by Ctrl-C. Widgets can't.
Also, when widget is run from PyCharm, the "stop" button does not really terminate it (at least not on macOs). The widget is done only when clicked on in Dock, and even then it crashes.
Running a widget multiple times from PyCharm opens n copies of widgets instead of closing them.
**Includes a commit from #3491. Merge #3491 first.**
Set the default signal handler for `SIGINT`.
Canvas' `__main__` already has this.
> WidgetPreview: Terminate when receiving SIGINT

- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/tests/test_owmergedata.py
Fixes #3289
Merged data is added to original table instead of creating a new one.
> [FIX] OWMergeData removes table meta attributes

- Orange/projection/manifold.py
- Orange/widgets/unsupervised/owtsne.py
- Orange/widgets/unsupervised/tests/test_owtsne.py
> [ENH] t-SNE: Updates 2.

- Orange/clustering/louvain.py
- Orange/widgets/unsupervised/owlouvainclustering.py
- Orange/widgets/unsupervised/tests/test_owlouvain.py
Fixes #3278.
Version 0.12 of `python-louvain` was just released and with it the `random_state` parameter, which was missing before. I've added the parameter to our wrapper and set the random_state to a fixed value in the widget, so the results are deterministic in the widget.
> [ENH] OWLouvain: Ensure deterministic clustering

- Orange/widgets/utils/saveplot.py
Any errors in image export open a custom dialog and they can not be reported to sentry. 
Catch OSError as suggested in #3497. This still reports user-dependent errors (wrong permissions, out of disk space) to the user but our errors will open Orange's standard error dialogue.
> image export: show custom error dialog only for OSError

- Orange/widgets/utils/plot/owplotgui.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
Fixes #3376: subsets are similar to selections, so it would make sense to label the subset data instances, too.
**Based on #3500 for faster CI testing, but otherwise unrelated.** If reviews are positive, I'll rebase to master so it can be merged.
To keep the GUI simple, this PR does not introduce another checkbox, but just adds subset instances to those that are labelled. Checkbox is renamed from *Label only selected points* to *Label only selection and subset*.
> [ENH] Label subset

- Orange/data/tests/test_util.py
- Orange/data/util.py
- Orange/projection/base.py
- Orange/projection/pca.py
- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/owlouvainclustering.py
- Orange/widgets/utils/annotated_data.py
- Orange/widgets/utils/tests/test_annotated_data.py
- Orange/widgets/visualize/utils/widget.py
`Orange.data.util.get_unique_names` accept a list of used names. When we call it, we almost always have a domain. Let the function accept a domain, too.
While at it, the second argument could also be a string, not a list of strings.
While at it, write some tests.
Fixes #3495, too.
> util.get_unique_names: Add more flexible arguments

- Orange/data/util.py
- Orange/tests/test_util.py
- Orange/widgets/visualize/tests/test_owprojectionwidget.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
- Orange/widgets/visualize/utils/widget.py
1. Fixes #3484
2. The widget crashes when reloading sparse data, because sparse matrices equality can not be checked with numpy
1. return no coordinates when no valid data (return None instead of an empty array)
2. fix reloading sparse data
> [FIX] OWDataProjectionWidget: check validity, fix sparse data reloading

- Orange/data/table.py
- Orange/tests/test_sparse_table.py
- Orange/tests/test_table.py
#3501, which will be merged in 3.24 (this is negotiable) will remove methods that change the length of `Table`. People have a right to know.
Add deprecation warnings.
Change the `skip` decorators for the tests so that they will raise exceptions in >3.24, so we'll remember to remove the methods and we also won't forget the tests.
> Table: Warn about pending deprecation of methods that resize Table

- Orange/widgets/tests/base.py
- Orange/widgets/visualize/utils/widget.py
#3507 introduced checking of subsets in `get_subset_data`.
- `handleNewSignals` is a better place because this is where one would expect such test.
- checking the length of the mask was not the best idea because data instances appear multiple times; it's better to subtract the two sets
- checks need to be done on entire data not just `valid_data` to prevent false warnings.
Code is changed, but existing tests remain valid.
> OWProjectionWidgetBase: Move checking of subsets to handleNewSignals

- scripts/windows/orange-conda.nsi
When running the miniconda installer in silent mode, it might modify %PATH%, ... 
Ref gh-3524
Add `/AddToPath=0 /RegisterPython=0` to miniconda installer call when running in silent mode.
> [FIX] Don't add miniconda to path and register as system python

- setup.cfg
The default configuration option for `with-htmlhelp` (gh-3345) is wrong.
Only run the command when explicitly requested.
> [FIX] setup.cfg: Change the default for with-htmlhelp config option

- Orange/widgets/data/owpythonscript.py
- Orange/widgets/data/tests/test_owpythonscript.py
Users were losing their scripts:
1. If they added a new enrty to the library (button "+") they lost the current script.
2. If they did not save the script into the library it got lots.
Fixes #3531
1. Adding an entry to the library initializes that script with the current script text.
2. The current script text is saved as a schema_only settings and is restored on load. I also added an option to restore the library version.
> [FIX] Python script widget: prevent data loss 

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
'Edit Domain' widget does not allow changing the 'ordered' aspect of a categorical variable
Add an 'Ordered' check box control and implement the associated transform.
> [ENH] Edit Domain: Add support for ordered categorical variables

- Orange/data/io.py
- Orange/tests/test_io.py
- Orange/widgets/data/owsave.py
- Orange/widgets/data/tests/test_owsave.py
Addreses #2717. 
When saving, header types and flags are no loger saved in .csv and .tab.
> [FIX] Removed header types and flags from .csv and .tab

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
1. Feature Statistics would crash when it got a discrete variable with no `values`
2. Feature Statistics would crash when switching from a data set with a target variable to a data set with no target variable
1. Fix. This crashed because `DiscreteVariable.str_val` crashes if it has no `values`. This means that the problem may exist in other widgets as well. I thought about fixing the `str_val` implementation, but I don't really know what it should do in this case ([implementation here](https://github.com/biolab/orange3/blob/master/Orange/data/variable.py#L704-L715)). In both cases a string is returned, so it's not clear what to do here. Perhaps this was even left out by design, so I fixed the issue on the widget.
2. Fix.
3. Update tests to use new signal style i.e. `self.send_data("Data", …
> [FIX] Feature statistics fixes

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
It would be interesting to see separate regression lines for different colors - when points in the scatter plot are colored with discrete colors.
Also fixes #3519.
> [ENH] Scatterplot: Draw separate regression lines for colors; add orthonormal regression

- Orange/widgets/data/owneighbors.py
- Orange/widgets/data/tests/test_owneighbors.py
Neighbours chrashes when data and reference has different domains. 
It shows an error instead of a crash now.
> [FIX] Neighbours: Show error when data and reference have different domain.

- Orange/projection/pca.py
- Orange/statistics/util.py
- Orange/tests/test_pca.py
- Orange/tests/test_statistics.py
Scikit-learn's PCA does not support sparse data. This PR implements randomized PCA which efficiently handles sparse matrices, without ever centering the original matrix. This means that running PCA is now feasible (and quite fast) for very large, sparse matrices, which would not fit into memory if densified.
This implementation should be removed once I get it merged into scikit-learn and once that's released.
There are two reference implementations of which I'm aware of and which were used to put together this code:
- https://github.com/KlugerLab/pcafast
- https://github.com/facebook/fbpca/ (I would just use this, but it's not being maintained and doesn't support random seeds)
- I added degrees of freedom to `var` and `std` to be consistent with scikit-learn's covariance. I made the …
> [ENH] Implement better randomized PCA

- conda-recipe/meta.yaml
https://github.com/biolab/orange3/issues/3438#issuecomment-443900519
Like I mention in a lower comment, the changes probably need to be applied to the orange3 conda forge feedstock as well.
> Update conda recipe scikit-learn version to >=0.20

- Orange/widgets/data/owneighbors.py
- Orange/widgets/data/tests/test_owneighbors.py
When comparing the data and reference with domains that are different only in meats widget trigger the different domain error. https://github.com/biolab/lookalike-demo/issues/6
Comparing only the attribute part of the domain. The error is triggered only when attributes differ.
> Fix: Neighbours: Compare tables with domains that only differ in metas and class_var

- Orange/widgets/data/owtransform.py
- Orange/widgets/data/tests/test_owtransform.py
Implements  #3526
- [X ] Tests
> [ENH] OWTransform: add option to keep original data #3526

- Orange/widgets/data/owpaintdata.py
Move auto commit from left_side to control_area and fix plotview's size policy.
> [FIX] PaintData: Fix control area width

- Orange/classification/naive_bayes.py
- Orange/tests/test_naive_bayes.py
Implement `predict` to:
- avoid numpy warning about passing generator to sum
- loop over columns instead of over rows (usually better + more friendly to pandas sometime in the future)
- natively support sparse matrices
`predict_storage` now calls `predict` when possible.
`predict_storage` also didn't work for `Instance`. Fixed.
> [ENH] Naive Bayes: Implement predict, fix predict_storage

- Orange/canvas/application/canvasmain.py
Fixes #3267
Append "[*]" placeholder to the window title (if it's not already present) before calling setWindowTitle.
> [FIX] Warning about a window title without a placeholder

- Orange/__init__.py
- Orange/distance/distance.py
- Orange/distance/tests/test_distance.py
- Orange/evaluation/clustering.py
- Orange/projection/freeviz.py
- Orange/regression/linear.py
- Orange/statistics/util.py
- Orange/tests/test_distances.py
- Orange/tests/test_distribution.py
- Orange/tests/test_filter.py
- Orange/tests/test_logistic_regression.py
- Orange/tests/test_orange.py
- Orange/tests/test_score_feature.py
- Orange/tests/test_sparse_table.py
- Orange/tests/test_statistics.py
- Orange/tree.py
**Similar to #3502**, this PR deals with most warnings in the scripting part, except those in postgresql and a few in the code I don't sufficiently understand.
> [MNT] Fix test warnings in scripting part

- Orange/projection/manifold.py
- conda-recipe/meta.yaml
- requirements-core.txt
Due to some breaking API changes in my t-SNE implementation, I had fixed the version to 0.2.13. There are likely not going to be any more API changes, so this shouldn't be an issue anymore.
fastTSNE has been renamed to openTSNE in the meantime. Also, I've fixed a bug here and there from v0.2.13. I had also changed the way openTSNE.initialization.random was called, so I changed this here.
> Update openTSNE version to >=0.3

- Orange/widgets/unsupervised/owtsne.py
- Orange/widgets/unsupervised/tests/test_owtsne.py
Fixes #3448
- The widget was still using SVD on sparse data. I have changed this to PCA, since our PCA does support sparse data since #3532
- I basically copied over the functionality from the PCA widget. PCA currently doesn't support normalization on sparse data, so this option is disabled on sparse data, just like in the PCA widget.
- Lastly, I increased the error margin on one test. The test does this: it embeds a data set using t-SNE then embeds the same data onto the existing embedding (transform). Unfortunately, the points are bound to be jittered around each original corresponding point, but also how far away is also determined by the neighborhoods, so there's no clean way to check for this. But if we visualize what this actually produces, we can see that the result is still …
> [ENH] t-SNE: Add Normalize data checkbox

- requirements-core.txt
python-louvain version >= 0.13 is required for the 'random_state' parameter (gh-3492).
Update `requirements-core.txt`
> [FIX] setup.py: Specify python-louvain version constraint

- .travis/install_orange.sh
Since PyQt5 version 5.12 there are problems on travis:
`qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.`
Until resolved, fix PyQt5 version to 5.11.3 on travis.
> Fix PyQt5 to version 5.11.3 on travis, until 5.12 issues are solved

- Orange/widgets/unsupervised/owtsne.py
t-SNE was slow
- The multiscale option makes things slow for larger data sets, so turn it off by default.
- Use faster approximation setting for Barnes-Hut
- Update t-SNE plot only at the start and at the end, avoiding potentially many redraws
- Selecting data in t-SNE was slow because `transform` was being called. Avoid this.
> [FIX] t-SNE speed-ups

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
Fixes #3442
Maximum data size to animate resizing is now set to 1000.
> Scatterplotgraph: Do not animate resizing

- Orange/projection/pca.py
- Orange/statistics/util.py
- Orange/tests/test_statistics.py
While working towards getting the improved PCA merged into scikit-learn, I've found two improvements.
1. `np.float32` are now preserved
2. Apparently, scipys sparse `x.mean` method isn't the most memory efficient, and scikit-learn's utility function `mean_variance_axis` is much better (see benchmarks [here](https://github.com/scikit-learn/scikit-learn/pull/12841#issuecomment-460238233))
> [ENH] PCA: Preserve f32s & reduce memory footprint when computing means

- Orange/classification/simple_tree.py
- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/preprocess/preprocess.py
- Orange/tests/test_instance.py
- Orange/tests/test_orangetree.py
- Orange/tests/test_simple_tree.py
- Orange/tests/test_table.py
- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/model/owlinearregression.py
- Orange/widgets/model/owlogisticregression.py
- Orange/widgets/model/owsgd.py
- Orange/widgets/visualize/utils/tree/tests/test_treeadapter.py
Fixes #2692.
Numeric variables are currently printed with three decimals, unless the number is set to another default. The latter most often happens when the data is read from text file (tab, csv, but not Excel). Consequently, values close to 0 are printed as 0. To fix this, some code sets the number of decimals to 7, which defeats the purpose and even doesn't help for values below 1e-7.
- When number of decimals is not set (as in regression coefficients, variables constructed by PCA...), `%g` is now used for formatting, as suggested by @markotoplak. This will print a reasonable number of decimals or switch to scientific notation.
- When the number of decimals is set, nothing changes.
Some code used `Variable.number_of_decimals` to construct own format strings instead of calling …
> [ENH] Use %g (including sci notation) if number of decimals is not set

- Orange/classification/naive_bayes.py
- Orange/tests/test_naive_bayes.py
As suggested by @lanzagar, issue #2943 can be fixed by ignoring empty classes in Laplacian smoothing.
Plainly, say that `y` has values `male`, `female`, `yes` and `no` because `y` appeared in two different data sets loaded in the same session. Of course, only two values appear in each set. With this PR, only 2 is added to denominators in computation of probabilities, and the probabilities of empty classes are set to 0.
Variable reuse remains a large open issue.
The change also required a minor change in computation of probabilities: instead of computing `exp(log(class_probs) + sum(conditional_probs))`, the code now computes `class_probs * exp(sum(conditional_probls))` because `class_probs` can now be 0. This should not affect numerical stability.
> [FIX] Naive Bayes: Ignore existing classes in Laplacian smoothing

- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/unsupervised/tests/test_owmds.py
> [FIX] MDS: Fix crashes when feeding column distances

- Orange/preprocess/normalize.py
- Orange/preprocess/preprocess.py
- Orange/statistics/util.py
- Orange/tests/test_statistics.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
- Orange/widgets/tests/utils.py
- Orange/widgets/unsupervised/owlouvainclustering.py
- Orange/widgets/unsupervised/tests/test_owlouvain.py
*Edited on 4.2.2019*
In #3448 we found that normalizing the data can have beneficial effects for t-SNE. This likely also holds for Louvain clustering, when PCA preprocessing is applied. It also makes little sense to enable data normalization for PCA in one widget, but not another.
I tried to separate the PCA specific parameters from the "Enable PCA preprocessing" by adding an indent. IMO it looks better than if there we no indent, but it's not very pretty.
Description of changes:
- 024d125721c88c54b5a8dfedeeb5625fd8313804 Add the option to skip zero centering to the normalization preprocessor. This will also be necessary later on, when I add normalization for sparse matrices.
This is already implemented in `Orange.preprocess.preprocess.Scale`, which seems to do exactly the same thing as …
> [ENH] OwLouvain: Add normalize data checkbox to PCA preprocessing

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/utils/plotutils.py
Fixes #2789.
- To show selection rectangle, (pyqtgraph's) `ViewBox.updateScaleBox` is overloaded to use `self.mapToView` instead of `self.childgroup.mapRectFromParent`. This may not be equivalent if there are multiple viewboxes in the same view or something similarly complicated, but we don't have this.
- To fix selection, (our) `mouseDragEvent` is modified in the same way
- An unrelated fix: `select_by_rectangle` assumed that the top left corner is above and to the left of the bottom right. This was true only if the user dragged in this direction. `select_by_rectangle` now sorts the coordinates.
The PR doesn't pass the diff coverage threshold, but I won't write any tests because they would involve simulating user interaction with mouse, yet at the end there wouldn't be anything to …
> [FIX] ScatterplotGraph: Use mapToView instead of mapRectFromParent

- Orange/widgets/unsupervised/owpca.py
- Orange/widgets/unsupervised/tests/test_owpca.py
Based on #3573, needed so zero-centering can be skipped.
Until recently, PCA didn't support sparse data, so SVD was used instead in the PCA widget. However, PCA now fully supports sparse data, so SVD is no longer necessary.
- Remove SVD from the PCA widget
- Add option to normalize sparse data
> [ENH] PCA: Remove SVD & add normalization for sparse

- README.md
Fixes #3543.
I also moved instructions for conda to the top as the preferred way of installing Orange. (Is it?)
> README: Update to Python 3.6, remove references to Qt4

- Orange/widgets/data/owpythonscript.py
- Orange/widgets/settings.py
- Orange/widgets/tests/test_context_handler.py
- Orange/widgets/tests/test_settings_handler.py
- Orange/widgets/widget.py
storeSpecificSettings is only called with a ContextHandler. Also, it is called after packing normal settings and before packing context settings.
In #3529 I implemented a special SettingsHandler because I needed to prepare settings for saving just before saving them.
Then I tried, in #3541, to extend (store|retrieve)SpecificSettings to an ordinary SettingsHandler. I failed: they were designed and used in a way that I could not make them work with ordinary settings (and not break stuff).
Before, I thought making storeSpecificSettings would be easy and would not change the interface. But now the question is if something like this is useful enough to extend the OWWidget with. I only needed something like this twice.
Added a signal settingsAboutToBePacked.
> Added settingsAboutToBePacked signal to OWWidget

- Orange/canvas/application/canvasmain.py
- Orange/canvas/document/schemeedit.py
Fixes #2942
- Added keyboard shortcut Shift+A for aligning widgets to a grid
- Added keyboard shortcut Shift+F for freezing signal propagation
> [ENH] Added keyboard shortcuts for Align & Freeze/Unfreeze 

- Orange/distance/__init__.py
- Orange/distance/base.py
- Orange/widgets/unsupervised/owdistances.py
- Orange/widgets/unsupervised/tests/test_owdistances.py
Fixes #3559.
Other distances are similar and their errors, warnings and selection of attributes is handled through flags. Jaccard is specific, so I have not introduced more new flags to distances (because this flag would be used only for Jaccard, at least for now) but instead added a Jaccard-specific check to the widget.
> [FIX] OWDistances: Use only binary features for Jaccard distance

- Orange/base.py
- Orange/tests/test_classification.py
- Orange/tests/test_logistic_regression.py
- Orange/tests/test_naive_bayes.py
- Orange/tests/test_simple_tree.py
- doc/data-mining-library/source/tutorial/code/classification-classifier1.py
- doc/data-mining-library/source/tutorial/code/classification-other.py
- doc/data-mining-library/source/tutorial/code/regression-other.py
- doc/data-mining-library/source/tutorial/code/regression.py
Fixes #3561.
Interestingly, documentation for scripting indexed the result from the model (`[0]`) without explaining why.
`Instance` is not the only kind of 1d data that can be passed to `Model.__call__`: one can also pass a 1d array, list or tuple. The trick with recursion was thus inconvenient, also because the method can return either a single value or a pair, in which case going back to 1d requires taking the first element of each element in the pair.
The method now remembers whether the data was 1d, and turns it back into 1d at the end.
> Orange.base.Model: Return 1d predictions for 1d data

- Orange/preprocess/fss.py
- Orange/tests/test_fss.py
- Orange/widgets/data/owpreprocess.py
- Orange/widgets/data/tests/test_owpreprocess.py
Fixes #3226.
Implements the "Percentile" option for Select Relevant Features preprocessor.  
The option enables the selection of all features that fall >= the entered percentile. The rank of the first feature to be taken is computed using [nearest-rank method](https://en.wikipedia.org/wiki/Percentile#The_nearest-rank_method). There are 2 "special" cases: 0th percentile is defined as all the features and 100th percentile is defined as the best feature.  
I've also renamed "Strategy" to "Number of features" in Select Random Features and Select Relevant Features as was suggested in the original issue.
> [ENH] Preprocess: implement Select Relevant Feature's percentile

- Orange/canvas/application/addons.py
- Orange/canvas/application/canvasmain.py
Fixes #2581
Reset widget settings:
Also for add-on manager:
> [FIX] Orange restart dialogs: Improve wording

- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/tests/test_owlinearprojection.py
The widget crashed when feed a dataset with two classes.
To reproduce: File(heart_disease) -> LinearProjection(Select Linear Discriminant Analysis) 
Disable Linear Discriminant Analysis when dataset has target with less than three classes.
> [FIX] LinearProjection: Disable LDA for less than three classes

- Orange/__init__.py
Fixes #3482
There is unfortunately no straightforward way to add post install for wheels ([pypi/packaging-problems#64](https://github.com/pypa/packaging-problems/issues/64))
Add additional information if import of compiled libraries failes.
> [FIX] Orange: add more informatino on missing compiled libraries

- Orange/clustering/louvain.py
- Orange/tests/test_louvain.py
When Louvain clustering got `Orange.Table` or `ndarray` on the input it fails when convertin table to graph. 
The way to reproduce: 
data = Table("iris")
louvain = Louvain(2)
louvain.fit(data)
Fixed to accept `Table` or `ndarray`.
Added tests.
> [FIX] Louvain clustering fails when Table or ndarray on input.

- Orange/widgets/settings.py
Most widgets that implement migrate_context crash upon undo. 
To reproduce see #3600.
Add checks for required context values to all widget that implement migrate_context.
> [FIX] migrate_context: widgets crash when migrating context without version

- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/visualize/utils/widget.py
> [FIX] MDS: Handle subset data

- Orange/widgets/visualize/owsieve.py
Fixes #3578
Discretization of datasets with mixed attributes does not retain the same instances of discrete attributes. Is this correct behaviour? A check for a discrete attribute with the 'is' operator fails and results in a tooltip such as "gender in male" instead of "gender = male". Revert to an equality check with '=='.
Compress duplicate code for x and y tooltips.
> [FIX] OWSieve: Fix operators in tooltips

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
- Orange/widgets/data/owcorrelations.py
- Orange/widgets/data/tests/test_owcorrelations.py
- Orange/widgets/visualize/utils/__init__.py
Fixes #3504
Heuristic will be updates in a following PR.
- Send outputs when feed data
- Split attribute pairs into two columns
- Output p-values
- Compute correlations with chosen feature
> [ENH] Correlations: fixes and enhancements

- .travis.yml
- .travis/install_mssql.sh
- .travis/stage_install.sh
- Orange/data/sql/table.py
- Orange/tests/sql/base.py
- Orange/tests/sql/test_filter.py
- Orange/tests/sql/test_misc.py
- Orange/tests/sql/test_naive_bayes_sql.py
- Orange/tests/sql/test_pca.py
- Orange/tests/sql/test_sql_table.py
- Orange/widgets/data/tests/test_owsql.py
- appveyor.yml
Orange currently only supports testing for PostgresSQL although Microsoft SQL Server is also supported by Travis (#2839).
Extend testing so that one test can be run on multiple databases. Add testing for Microsoft SQL Server to Travis and AppVeyor.
> [MNT] Tests: add support for multi-database tests

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
Current implementation of False discovery rate is using python list and for loops and is therefore inefficient.
Implement FDR using numpy.
> [ENH] FDR: Calculate FDR using numpy

- Orange/data/table.py
- Orange/tests/test_table.py
Implements #2788
Replace infs in a numpy array with nans and raise a warning.
> [ENH] Table.from_numpy: Replace infs with nans.

- Orange/distance/distance.py
- Orange/distance/tests/test_distance.py
Hamming distance does not support sparse as stated in [sklearn documentation](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise_distances.html).
Set support_sparse to False. Add test to ensure error is raised when trying to compute distances with metrics that do not support sparse.
> Remove sparse support for Hamming

- Orange/data/io.py
- Orange/widgets/data/owsave.py
- Orange/widgets/data/tests/test_owsave.py
Fixes #3539.
OWSave widget didn't age well.
- **Choosing the format in a separate combo box instead of in the save dialog?** The GUI of its previous incarnation was clear to his creator (me), but I would have to explain it at workshops - not a good sign. But it made sense for as long as one set the format with "Save as". The current incarnation required setting the format in a combo and then use Save as (or Save) to set the name -- the save dialog was passed the filter chosen in the combo. Unusual and cumbersome.
- **Compression options.** I suppose this complication was needed because of the "Compression" checkbox, which the user would have to decide before clicking Save (and it's availability depended on the format). The widget offered three different compressions, one of which was even …
> [ENH] Improve Save widget's gui

- Orange/widgets/data/owpythonscript.py
- Orange/widgets/data/tests/test_owpythonscript.py
Drag and drop of files did not work in the Python script widget
Files can be dragged and dropped (or pasted) onto the script editor or widget's control area. Nothing changed for dropping or pasting text.
> [ENH] OWPythonScript: dropping and pasting of python scripts

- pylintrc
Pylint 2.3.0 introduced a lot of new false positives for `unsubscriptable-object`.
We use pylint mostly as style checker, while unsubscriptable objects are/should/can be/must be properly detected by unit tests.
> [MNT] Disable check for add unsubscriptable-object in pylint

- Orange/widgets/data/owcolor.py
> OWColor: PyLint

- Orange/widgets/data/owcorrelations.py
> OWCorrelations: PyLint

- Orange/widgets/data/owcreateclass.py
> OWCreateClass: PyLint

- Orange/widgets/data/owdatainfo.py
> OWDataInfo: PyLint

- Orange/widgets/data/owdatasampler.py
> OWDataSampler: PyLint

- Orange/widgets/data/owmergedata.py
... except for taking a length of a data table.
> OWMergeData: PyLint

- Orange/widgets/data/owneighbors.py
... except for taking a length of a data table.
> OWNeighbors: PyLint

- Orange/widgets/data/owconcatenate.py
> OWConcatenate: PyLint

- Orange/widgets/data/owrandomize.py
Fix pylint issue related to `Setting` not being recognized as `int`.
> OWRandomize: PyLint

- Orange/widgets/data/owfile.py
`OWFile` now almost passes pylint with disabling only `missing-docstring,  no-name-in-module,  too-many-ancestors, no-else-return`. The only remaning issue is redefinining the built-in `vars`.
Most of this PR is however about breaking long lines, and at the same time I converted formatting strings to f-strings, refactoring the corresponding code to something simpler.
> OWFile: PyLint

- Orange/widgets/data/owpythonscript.py
> OWPythonScript: PyLint

- Orange/widgets/data/owtable.py
- Orange/widgets/data/tests/test_owtable.py
> [FIX] OWTable: Include attributes from meta attributes in header row labels

- Orange/widgets/data/oweditdomain.py
> OWEditDomain: PyLint

- Orange/widgets/data/owfile.py
- Orange/widgets/utils/domaineditor.py
Fixes #2673 and fixes #3563.
Model remembers the original data and implements `FontRole` to return a bold font if the line was changed.
I sincerely don't know how to reasonably test this. It's all just a game of signals.
> [ENH] DomainEditor: Indicate changed variables with bold face font

- Orange/widgets/data/owpreprocess.py
- Orange/widgets/data/utils/preprocess.py
Now passes pylint with disabling only `missing-docstring`, `no-name-in-module`, `too-many-ancestors`, `no-else-return`, except for file length.
> OWPreprocess: PyLint

- Orange/widgets/data/owcorrelations.py
- Orange/widgets/data/tests/test_owcorrelations.py
Implements the last part of #3504.
- Improve heuristic to return all possible attribute pairs in most promising order, i.e. returning pairs within clusters first, followed by pairs among clusters (starting with closest clusters)
- Show `Need at least two continuous features.` and `Need at least two instances.` messages as warnings
- Fix feature model to contain only attributes (exclude class)
> [ENH] Correlations: Enhancements and fixes

- Orange/widgets/settings.py
#3637, @lanzagar argued against extra annotation needed to tell pylint that `Setting(0)` is an `int`. I agree. Without a better solution, we can only disable checking the type by confusing pylint with a fake annotation that is never executed.
The code has no side-effects, and should not have detrimental side-effects for pylint: currently it *thinks* it knows the type of setting, and after the PR it apparently *knows it doesn't*.
> [MNT] Confuse pylint to stop checking type for Setting

- Orange/widgets/data/owfeaturestatistics.py
> OWFeatureStatistics: PyLint

- Orange/widgets/data/owfeatureconstructor.py
Now passes pylint with disabling only `missing-docstring`, `no-name-in-module`, `too-many-ancestors`, `no-else-return`, except for the file length.
> OWFeatureConstructor: PyLint

- Orange/preprocess/preprocess.py
- Orange/widgets/data/owtransform.py
- Orange/widgets/data/tests/test_owtransform.py
- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/owpca.py
- Orange/widgets/unsupervised/owtsne.py
- Orange/widgets/unsupervised/tests/test_owpca.py
- Orange/widgets/unsupervised/tests/test_owtsne.py
- Orange/widgets/visualize/utils/widget.py
Fixes #3623 and #3675.
- remove 'Preprocessor' output from projection widgets (PCA, tSNE, Freeviz, Radviz, LinearProjection)
- OWTransform: use domain to transform data (instead of preprocessor)
> [FIX] Transform: Replace 'Preprocess' input with 'Template Data' input

- .gitignore
- setup.py
`python setup.py coverage` did not generate anything.
I added `coverage combine` into setup.py. I guess that command was probably necessary since we added concurrency to .coveragerc.
I was thinking of adding widget tests to the coverage command but I opted not to, because `python setup.py test` does not run them either.
> setup.py: fix generating coverage output

- Orange/projection/base.py
- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/unsupervised/tests/test_owmds.py
- Orange/widgets/utils/concurrent.py
- Orange/widgets/utils/tests/concurrent_example.py
- Orange/widgets/utils/tests/test_concurrent_example.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/tests/test_owfreeviz.py
Fixes #3579
- ConcurrentMixin - a new class - base class for concurrent mixins
- TaskState - a task class to be used within ConcurrentMixin
- ConcurrentWidgetMixin - a mixin to be used along with OWWidget
- OWConcurrentWidget - an example of using ConcurrentWidgetMixin
- OWFreeviz and OWMDS - extend OWConcurrentWidget and add `runner` methods to calculate projectiona in threads
> [ENH] Offload work to a separate thread

- Orange/widgets/data/tests/test_owsave.py
- Orange/widgets/tests/base.py
- Orange/widgets/tests/test_widget.py
- Orange/widgets/utils/owlearnerwidget.py
- Orange/widgets/utils/tests/test_owlearnerwidget.py
- Orange/widgets/visualize/owtreeviewer2d.py
- Orange/widgets/visualize/utils/widget.py
- Orange/widgets/widget.py
We always silently assume that widget classes are final. Without this, we wouldn't be able to redesign widgets, not even to change a badly named attribute.
Some widgets, like `OWDatasets` are, however, unexpectedly subclassed, as I was warned in #3642.
I propose to make all widgets final unless explicitly declared open. We will open abstract widgets like `OWWidget`, `OWProjectionWidgetBase`, `OWProjectionWidget`. If we really wish, we can also open non-abstract widgets, such as `OWDatasets`, but opening them will represent a commitment to avoid backward incompatible changes.
An open class shall be declared by adding `openclass=True` keyword to its definition, *e.g.* `class OWProjectionWidgetBase(OWWidget, openclass=True):`. Ordinary class attribute would not work because it would be …
> Make widget classes final, unless explicitly declared open

- Orange/distance/base.py
- Orange/distance/distance.py
- Orange/distance/tests/test_distance.py
- Orange/tests/test_distances.py
- Orange/widgets/unsupervised/owdistances.py
Jaccard did not support sparse data, making it useless for text mining.
Custom support for sparse Jaccard.
> [ENH] Support sparse Jaccard

- Orange/canvas/__main__.py
- Orange/canvas/document/usagestatistics.py
Fixes #3597
When closing Orange, usage statistics are saved. Then, when starting Orange, usage statistics are sent in the background.
> [FIX] Send usage statistics in a thread at startup

- Orange/distance/base.py
- Orange/distance/distance.py
Remove all pylint issues. No non-trivial changes.
> Pylint distances

- Orange/widgets/data/owcorrelations.py
- Orange/widgets/data/tests/test_owcorrelations.py
- Orange/widgets/visualize/tests/test_owlinearprojection.py
- Orange/widgets/visualize/tests/test_vizrankdialog.py
- Orange/widgets/visualize/utils/__init__.py
When fed large datasets to owcorrelations, the widget exited with segmentation fault, (probably) due to insufficient stack size for created task.
To reproduce: Generate a dataset with at least 26 features and 3361 rows, and feed it to OWCorrelations.
- VizRankDialog now inherits ConcurrentMixin, which uses ThreadExecutor that provides sufficient stack size.
> [FIX]  VizRankDialog: Use extended thread pool to prevent segfaults

- Orange/distance/distance.py
- Orange/distance/tests/test_distance.py
Jaccard did not handle two all zero instances.
Check to avoid division by zero. Add tests for all distances.
> distance.py: Fix zero division in Jaccard

- Orange/widgets/evaluate/owtestlearners.py
Fixes #2088
A user sees a warning although all displayed scores are successfully computed. The problematic score is not AUC but LogLoss, which the widget tries to compute (and fails) but is not displayed by default.
- hide warnings for hidden scores
- fix an error where the user couldn't display additional scores on Windows
We might want to consider fixing LogLoss for the case described in #2088.
> [FIX] Test & Score: hide warnings for hidden scores.

- Orange/widgets/visualize/owheatmap.py
Fixes gh-3678
Fix size policy for group title label.
> [FIX] owheatmap: Fix group label size policy

- Orange/widgets/visualize/owscatterplot.py
Fixes #3684.
`OWScatterPlot.set_data` compared data sets by their check sums. This remained from before Orange had context settings. It is now no longer needed and ignores that attributes were edited and Edit domain.
> OWScatterplot: Remove checking the checksum in set_data

- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
> [ENH] k-Means: Output centroid labels

- Orange/widgets/settings.py
- Orange/widgets/tests/test_domain_context_handler.py
- Orange/widgets/tests/test_setting_provider.py
If setting is a list, writing it to the widget does not change the list in place but replaces it with a new list. This is a problem if the list is (wrapped in a) model. In particular, models behind list views wrap a setting, and they are not updated when settings are changed.
I encountered the problem in RadViz and Linear projection. The base projection widget, which is common to all projections (scatter plot, mds, tsne, networks...) has a conspicuous method `use_context`, which is there just to be overridden in Radviz and Linear projection. Currently it is more complicated, but after #3508 it will have to do something like
```
def use_context(self):
self.selection_model.wrap(self.selected_variables)
```
where `selected_variables` is a setting (and a list behind the model at the same …
> In-place settings, and proper encoding and matching of lists of variables

- Orange/widgets/data/owsave.py
- Orange/widgets/data/tests/test_owsave.py
Fixes #3667.
Qt's non-native file save dialog was giving wrong extensions: instead of iris.tab.gz it had iris.gz, or, sometimes, apparently iris.tab.tab.
Now the function for removing extensions chips away any parts of extension that can appear in any filter.
> [FIX] Save Data: Remove extra file extensions

- Orange/widgets/data/owtable.py
Fixes #3451.
Fixes the bug by adding an additional check.
> [FIX] OWTable: Don't set selection when there is no data on input

- Orange/canvas/canvas/items/nodeitem.py
Fixes #3294, #3598
Logitech's Smart Move option moves the mouse pointer to a focused item after opening a new window. 
A double-click triggers two mouse press events and a double-click event between them. After the widget window opens, Smart Move triggers a mouse move event. A typical event sequence is [press, release, double click, press, move, release], which results in a relocation of the widget's node on canvas (moved while pressed).
The solution is to ignore the second press event if it is too close (closer than doubleClickInterval) to the previous one.
> [FIX] Compatibility with Logitech's Smart Move

- Orange/widgets/tests/base.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/utils/widget.py
Fixes #3717
In case dataset with missing values was reloaded, `valid_data` was not properly set, because `get_embedding() `was not invoked.
To reproduce: OWFile(heart_disease) -> OWRadviz -> OWFile(click Reload)
- set `valid_data` only in `get_embedding()`.
> [FIX] OWAnchorProjectionWidget: Retain valid_data when reloading dataset

- Orange/widgets/data/owsql.py
- Orange/widgets/data/tests/test_owsql.py
Fixes #3609
Move selection of current table to after a connectino is established.
> [FIX] SQL Table: Restore selected table from settings

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
> [FIX] stats: Fix statistics for primitive variables

- Orange/widgets/io.py
- Orange/widgets/tests/test_io.py
- Orange/widgets/utils/PDFExporter.py
- Orange/widgets/utils/saveplot.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/widget.py
Fixes #2887 for Qt >= 5.12.
Use Qt's PDF Writer for output on Qt >= 5.12, because some bugs with line widths and fonts prevent this to work properly on older Qt version.
A potential problem: because I wanted to support multiple formats with the same extension, I changed the format of OWWidget.graph_writers from dict to a list. This could crash unknown add-ons that were touching it. I do not see a good workaround though.
> image export: export PDF directly for Qt >= 5.12

- Orange/data/table.py
- Orange/data/tests/test_util.py
- Orange/data/util.py
- Orange/tests/test_table.py
- Orange/widgets/data/owtranspose.py
- Orange/widgets/data/tests/test_owtranspose.py
> [ENH] Transform: Values of primitive variables as feature names

- .github/PULL_REQUEST_TEMPLATE.md
Showing *Implements #2* besides *Fixes #1* is misleading because the latter closes #1 and the former does not.
> [MNT] Remove 'implements' from pr template [skip ci]

- Orange/widgets/gui.py
- Orange/widgets/settings.py
- Orange/widgets/utils/listfilter.py
- Orange/widgets/utils/plot/owplotgui.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/tests/test_owlinearprojection.py
- Orange/widgets/visualize/tests/test_owradviz.py
- Orange/widgets/visualize/utils/widget.py
We had two listviews which took too much space. So we switched to +/- buttons, which are better require more clicks and are somewhat inconsistent (to remove, you select and click -, while to add you click + and select) although similar to other dialogs (at least on macOS).
I propose a single list view in which the user can add and remove. I recorded three alternative visual indications; other suggestions welcome. The user can also drag a variable from shown to hidden or the opposite, which I forgot to record.
I don't particularly like the second one. I lean towards the third.
(Yes, I know, the indicator does not disappear when mouse leaves the view. It will. Settings and tests are also broken.)
Below the list view, we can add buttons Clear and Reset.
> Easier selection of variables in Radviz, Linear projection and similar

- Orange/widgets/visualize/owlinearprojection.py
The Linear Projection vizrank crashed. 
To reproduce:
OWFile (iris) -> OWLinearProjection (Suggest Features -> Start -> Filter by a nonexistent string)
Add a check.
> [FIX] LinearProjectionVizRank: Add a necessary check

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Implements gh-3371
Also fixes and assertion error when two values are renamed to the same value.
```
File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/data/oweditdomain.py", line 1165, in commit
var = apply_transform(v, tr)
File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/functools.py", line 803, in wrapper
return dispatch(args[0].__class__)(*args, **kw)
File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/data/oweditdomain.py", line 1430, in apply_transform_discete
dest_codes = positions(dest_values)
File …
```
> [ENH] Edit Domain: Merge categorical values

- Orange/widgets/data/owdatasampler.py
- Orange/widgets/data/tests/test_owdatasampler.py
- doc/visual-programming/source/widgets/data/datasampler.md
Closes #2035. 
#2035 required:
1. Modified DataSampler that allows selecting all instances (not just n-1)
2. DataSampler doc mentioning that the widget shuffles the dataset
3. A test that checks that DataSampler really shuffles the dataset
4. An example in Test & Score docs showcasing how this can be done (like #3245)
I've done them all, but I didn't have a good use case in 4. @ajdapretnar, in an already agitated state because of certain issues around #3722, told me in no uncertain terms to remove it. I'm married for 17 years, so I know better than to complain. On the contrary, I *must say* that I didn't like that text either, so I was very happy to remove it.
Documentation still explains that choosing the entire data set shuffles it, which, I must say, should suffice.
(Joke aside, it …
> Data sampler: Allow selecting 100% of data, shuffle it

- Orange/data/sql/backend/mssql.py
Views should be supported for analysis in Orange Canvas
SQL Table widget in Orange Canvas only displays tables. However, most database servers have  very useful views.
You could argue that why not just use "custom SQL", but the "custom SQL" part of the widget can become too complicated for large SQLs, and it does not support CTEs.
Extended select query from information_schema.tables to include views in addition to table
> Extend list_tables_query to show views

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/preprocess/continuize.py
- Orange/preprocess/impute.py
- Orange/preprocess/remove.py
- Orange/tests/test_continuize.py
- Orange/tests/test_impute.py
- Orange/widgets/data/owcontinuize.py
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owcontinuize.py
- Orange/widgets/data/tests/test_oweditdomain.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
- Orange/widgets/visualize/owvenndiagram.py
- Orange/widgets/visualize/tests/test_owvenndiagram.py
- doc/data-mining-library/source/reference/preprocess.rst
- doc/visual-programming/source/widgets/data/continuize.md
Closes #3690.
`base_value` was almost unused, and also not settable in the canvas, so we decided to remove it.
> Variable: Remove attribute base_value

- Orange/widgets/evaluate/contexthandlers.py
- Orange/widgets/settings.py
- Orange/widgets/tests/test_class_values_context_handler.py
- Orange/widgets/tests/test_domain_context_handler.py
- Orange/widgets/tests/test_perfect_domain_context_handler.py
- Orange/widgets/tests/test_setting_provider.py
Context settings contain obsolete unused undocumented code that can be removed or deprecated (and removed).
- Remove 'selected' flag that could be used (but was not used in Orange 3) for storing selections in list views.
- Remove attribute `not_attribute`.
- Warn that support for variables stored as string settings will be removed in 3.26.
- Require that `settings_to_widget` and `settings_from_widget` support `*args`; exception for those not accepting it was supposed to be removed in 3.10.
- PyLint.
> Settings cleanup

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
In Network Explorer, I wanted to draw lines to the edge of the circles, not to the center. I tried to override `update_sizes` to call `self.update_edges()` after `super().update_sizes()`... but this didn't work because `update_size` does not change sizes immediately but updates them from a separate thread.
Furthermore, it would be nice if edges were animated together with circles.
I added signals that are emitted at the start and end of resize, and at each step.
> OWScatterplotGraph: Emit signals when resizing data points

- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/tests/test_owmds.py
Fixes #3723
Wait until the widget stops blocking before checking number of calls.
> [FIX] ProjectionWidgetTestMixin: Fix test_plot_once

- Orange/widgets/utils/webview.py
`time.clock()` will be removed in Python 3.8...
https://docs.python.org/3/library/time.html#time.clock
> webview: Replace deprecated time.clock

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
- Orange/widgets/tests/utils.py
- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/owlouvainclustering.py
- Orange/widgets/unsupervised/owmds.py
Some time ago, I introduced [`statistics.util.array_equal`](https://github.com/biolab/orange3/blob/master/Orange/statistics/util.py#L17-L31), unaware of the existing [`data.util.array_equal`](https://github.com/biolab/orange3/blob/master/Orange/data/util.py#L101-L114). The latter is better because it treats NaNs equally i.e. normally NaN != NaN.
Louvain used my implementation (which would treat NaNs incorrectly), while MDS and kMeans used `np.array_equal`, which triggers a `SparseEfficiencyWarning` when comparing two sparse matrices.
1. Remove `statistics.utils.array_equal` in favour of the better implementation.
2. Louvain, MDS and kMeans now use the better implementation.
EDIT: In the process, I realised that the helper decorators for `dense_sparse` weren't resetting the state between …
> Replace statistics.util.array_equal with data.util.array_equal

- Orange/widgets/visualize/owdistributions.py
Implements #1848.
Added check box to display cumulative ditribution.
> [ENH] OWDistributions: add cumulative distribution

- doc/data-mining-library/source/conf.py
- requirements-doc.txt
Reference documentation fails to build with sphinx==2.0.1 and numpydoc==0.9.1. (raises `numpydoc.docscrape.ParseError: ...`)
Use sphinx.ext.napoleon instead of numpydoc
> [DOC] Replace numpydoc with sphinx.ext.napoleon

- requirements-readthedocs.txt
Fixed #3754
Here I built test documentation from this branch:
https://test-123-or-wid.readthedocs.io/en/latest/gui.html
Compare with
https://orange-development.readthedocs.io/gui.html
After this is merged, we also need to set requirements file on ReadTheDocs to "requirements-readthedocs.txt"
> [DOC] Add a requirements file for readthedocs

- Orange/projection/manifold.py
- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/owtsne.py
- Orange/widgets/unsupervised/tests/test_owtsne.py
The t-SNE widget previously performed all computation inside the main thread, while simulating a thread i.e. it would pause every once in a while and handle user action. For larger data sets, this meant the widget would freeze for a while until the widget received control again.
The widget now offloads all of the computation into a separate thread, and the widget is only responsible for preparing a `Task` specification, which is then handled by the other thread.
Other changes include:
- The widget now remembers partial results better, i.e. changing the exaggeration parameter doesn't recompute all the nearest neighbours again.
- More descriptive status message and the progress bar now takes into account all the steps of the procedure.
- Since t-SNE is deterministic, once the optimization …
> [ENH] OWTSNE: Offload computation to separate thread

- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
#3728 broke FeatureConstructor - I overlooked an extra argument in a function call.
> OWFeatureConstructor: Remove extra argument (base_value) from a call

- Orange/widgets/visualize/tests/test_owpythagorastree.py
- Orange/widgets/visualize/tests/test_owpythagoreanforest.py
- Orange/widgets/visualize/utils/tree/skltreeadapter.py
- Orange/widgets/visualize/utils/tree/treeadapter.py
Fixes #3414
Transform data to the discretized domain when computing the samples in leaves (SklTreeAdapter).
> [FIX] OWPythagorasTree: Enable node selection from forests with categorical variables.

- Orange/widgets/visualize/owlineplot.py
- Orange/widgets/visualize/tests/test_owlineplot.py
Fixes #3741
Subclass `pg.AxisItem` and override `tickStrings()` to display feature's names.
> [FIX] OWLinePlot: legible bottom axis labels

- Orange/canvas/canvas/items/nodeitem.py
- Orange/widgets/utils/messagewidget.py
- Orange/widgets/widget.py
Resolves #3377, #3699 
Using QPropertyAnimation and an opacity property, makes warnings and errors flash on update.
In nodeitem.py, GraphicsIconItem now subclasses QGraphicsWidget instead of QGraphicsItem (to allow QPropertyAnimation). I've not tested this change extensively, and am not aware of its implications.
> [ENH] Error Animations

- Orange/__init__.py
- Orange/tests/test_naive_bayes.py
- Orange/tests/test_orange.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py
- Orange/widgets/visualize/tests/test_owfreeviz.py
- Orange/widgets/visualize/tests/test_owsieve.py
- Orange/widgets/visualize/tests/test_owvenndiagram.py
Since Scipy==1.3.0, which was released on 17 May 2019, these warnings stopped appearing.
> Stop suppressing ".*the matrix subclass.* warnings

- Orange/base.py
- Orange/classification/logistic_regression.py
- Orange/classification/random_forest.py
- Orange/classification/rules.py
- Orange/modelling/linear.py
- Orange/modelling/randomforest.py
- Orange/preprocess/score.py
- Orange/projection/pca.py
- Orange/regression/linear.py
- Orange/regression/random_forest.py
- Orange/widgets/model/owrules.py
Fixes #3384.
To my observation, `domain` was used in two places:
- Rule learner implemented `fit` instead of `fit_storage` and, besides, it's methods retrieved the domain from an attribute instead of passing it as an argument ("attribute instead of argument" is basically the same as "global instead of argument"!). I replaced `fit` with `fit_storage` and moved `domain` to arguments.
- When learners are used as scorers, and if they preprocess the data so that the number of attributes is increased (e.g. one-hot-encoding) they need domain to "project" the scores back to original attributes. These domains were retrieved from models. Now, domain is returned as part of result, together with scores.
> Remove domain from model

- Orange/widgets/unsupervised/tests/test_owmds.py
OWMDS tests fail sporadically (e.g. https://ci.appveyor.com/project/ales-erjavec/orange3-installers/builds/24690873/job/8h2c2s0ya7qd5d7c)
Properly wait for the widget to complete.
> [FIX] owmds: Fix test for error display/activate

- Orange/widgets/visualize/owpythagorastree.py
- Orange/widgets/visualize/owpythagoreanforest.py
- Orange/widgets/visualize/tests/test_owpythagorastree.py
- Orange/widgets/visualize/tests/test_owpythagoreanforest.py
This fixes a couple of minor things I came across while reviewing #3775.
1. Remember selection in the Pythagorean forest widget so that reopening a workflow won't clear selection.
2. Remove some dead code from both widgets
3. Properly use context settings in Pythagorean tree and forest widget (before, it wasn't using the domain context settings handler.
4. The tree widget would crash if there was no data and we clicked "Redraw".
The tree widget does not currently remember selection (both when reopening a workflow or when redrawing), and this will be a bit trickier to implement, since Orange trees have no identifier for each node.
> [FIX] Minor improvements to pythagorean trees

- Orange/widgets/utils/webview.py
Widgets based on WebviewWidget have no options to change the timeout limit for running JavaSript code.
Expose a new js_timeout parameter.
> [ENH] WebviewWidget: expose JavaScript timeout limit

- Orange/widgets/gui.py
Long vertical labels (i.e. labels for table's vertical header) are cut off: 
Show the whole label.
> [FIX] VerticalItemDelegate: Do not cut long vertical labels

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
- Orange/widgets/data/owfeaturestatistics.py
We have some workarounds for older scipy versions: #3817
Our nanmode returns mode NaN if all values are NaN (scipy<1.2.0 wrongly returns zero). Also, it returns count NaN if all values are NaN (scipy=1.3.0 returns some number).
We keep it because scipy still returns strange counts if all values are NaN.
Because we keep the workaround, requiring newer scipy is not necessary.
> Update tests for scipy.stats.mode workaround

- Orange/widgets/tests/test_widget.py
- Orange/widgets/widget.py
If a widget has no basic layout (`want_basic_layout = False`) and error is raised on a mouse press
in an empty widget area.
```
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/widget.py", line 830, in mousePressEvent
self.message_bar.flashIcon()
AttributeError: 'NoneType' object has no attribute 'flashIcon'
```
> [FIX] OWWidget: Fix an error on mouse press when widget has no basic layout

- Orange/widgets/visualize/tests/test_owsieve.py
That filter causes test failures with scipy 1.2 and numpy 1.6. We do not want to filter for scipy.sparse warnings since #3808 anyway.
> Remove filterwarnings from test_owsieve

- Orange/canvas/document/quickmenu.py
When using certain add-ons, upon opening a quickmenu, Orange will crash and be stuck in a crash loop. 
After retrieving description from item model, null-check.
> [FIX] Rare quickmenu crash fix

- Orange/clustering/dbscan.py
- Orange/tests/test_clustering_dbscan.py
DBSCAN has wrong mapping of indices when make a Table. The first class is maped at `-1` group, `-1` is a group for nonclustered items. 
There will be a complete fix when https://github.com/biolab/orange3/pull/3814 will be merged. Since it will take some time I am proposing a quick fix.
> [FIX] DBSCAN: Fix predicted labels

- Orange/widgets/data/icons/Pivot.svg
- Orange/widgets/data/owpivot.py
- Orange/widgets/data/tests/test_owpivot.py
Add pivot widget.
Implements #2860
> [ENH] Pivot: New widget

- Orange/widgets/visualize/owlineplot.py
controlArea of LinePlot is unnecessarily wide.
Make controlArea narrower.
> OWLinePlot: controlArea too wide

- Orange/widgets/data/owpythonscript.py
- Orange/widgets/data/tests/test_owpythonscript.py
- Orange/widgets/tests/base.py
Fixes #3820.
PythonScript widgets on the same canvas now share namespaces. Consequently, namespaces are no longer cleared after execution and garbage is not collected.
This PR also fixes a glitch in the base widget test class.
> [ENH] Shared namespaces for PythonScript widgets

- scripts/windows/condainstall.bat
Fixes gh-3819
'CONDA_BAT' env variable is used by conda for running/activating scripts. Since conda 4.6.9, the use here breaks the subsequent post link scripts in package installs.
Move all the extra env modifications to the end of the script.
> [FIX] condainstall: Fix env for running conda

- Orange/widgets/model/owrandomforest.py
- Orange/widgets/model/tests/test_owrandomforest.py
Fixes #3724.
This PR removes the spin box for random forest. Neural networks have already been fixes elsewhere.
> OWRandomForest: Remove option to fit random seed

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
`bincount` failed for object arrays that contained `np.nan`, but worked on both float arrays with nans and object arrays without them.
This was a problem since metas are often stored as object arrays and contain primitive variables, for which bincount should work (even if there are missing values).
The array must contain numbers anyway (since it is later converted to int32 for np.bincount), so it should not hurt to cast it to float before checking for nans. Almost all arrays in Orange are either float or object anyway, so this should be a noop for float arrays and a fix for object arrays.
> [FIX] util: Fix bincount for object arrays

- Orange/widgets/visualize/owmosaic.py
Fixes #3739. Mostly. See comments there.
This is poor man's elide: chop off the characters until it fits.
> OWMosaic: Elide long labels at the bottom

- Orange/preprocess/discretize.py
- Orange/tests/test_discretize.py
Discretized `TimeVariable` has float-like labels instead of dates/times.
`Discretizer.create_discretized_var` now calls `str_val` to create labels for discretized variable.
This fixes the problem with `TimeVariable`.
Also, for numeric variables, it will properly format small numbers; current code circumvented the fix from 0a205f87cbe3faf68effb9e95eb8f5580f4711ed, which introduced formatting with `%g` when the number of decimals is too large. For normal numbers, the change should have not effect (although rounding is now replaced by stripping 0s and the dot).
> Discretization: Proper labels for discretized TimeVariable

- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/owsieve.py
- Orange/widgets/visualize/utils/__init__.py
Fixes #3742 (eliding of long labels for Sieve)
Moves code from #3845 (eliding for Mosaic) to `CanvasText`, so it can be used in other widgets (like Sieve), too.
> Sieve, Mosaic, CanvasText: Elide long labels

- Orange/widgets/evaluate/tests/base.py
- Orange/widgets/evaluate/tests/test_owconfusionmatrix.py
- Orange/widgets/evaluate/tests/test_owrocanalysis.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
Disable false positives, fix whitespace.
> Orange.evaluation.tests: Fix pylint issues

- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/unsupervised/owtsne.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/utils/widget.py
The property `left_side_scrolling` should be set on parent widget.
> OWDataProjectionWidget: Set 'left_side_scrolling' on the parent

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
- Orange/widgets/evaluate/tests/test_utils.py
- Orange/widgets/evaluate/utils.py
Resolves #2191.
- Factor out the table with scores out of Test and Score; it's valuable mainly because column chooser
- Add the table to Predictions
> Add performance scores to Predictions widget

- Orange/data/filter.py
- Orange/data/table.py
- Orange/data/tests/test_table.py
- Orange/widgets/data/owselectrows.py
Fixes #2223. Also fixes #3413.
> [ENH] Add conditions for all variables, or all numeric or textual variables

- Orange/widgets/model/owadaboost.py
- Orange/widgets/model/owknn.py
- Orange/widgets/model/owlinearregression.py
- Orange/widgets/model/owlogisticregression.py
- Orange/widgets/model/owneuralnetwork.py
- Orange/widgets/model/owrandomforest.py
- Orange/widgets/model/owsgd.py
- Orange/widgets/model/owstack.py
- Orange/widgets/model/owsvm.py
- Orange/widgets/model/tests/test_owsvm.py
Almost all issues in widgets/model are due to attributes being defined in methods called by `__init__` instead of in `__init__`. Most other issues are related to names that follow the usual names of parameters for models.
> Orange.widget.model: pylint

- Orange/evaluation/testing.py
`Orange.evaluation.testing.Results.__init__` can be called with learners or with predictions and probabilities (which is admittedly ugly). 
This constructor is six years old and today it was the first time that somebody (me) tried to call it in the second way (and failed). This PR fixes two obvious bugs.
I provide no tests. See the proposal in #3857 instead.
> testing.Results: Fix constructor

- pylintrc
This is pylint rcfile that I use internally and against which I test the pylint fixing PRs I'm occasionally making. The difference is that instead of disabling half of tests, I disable only
```
disable=
missing-docstring,  # I guess not
no-name-in-module, no-member  # too many false positives from Qt
too-many-ancestors, # I don't think this is a problem
no-else-return      # else's may actually improve readability
```
Compared to our usual file, I ignore `too-many-ancestors`, which we treat as the US debt ceiling -- we increase it as needed. :)
I don't yet suggest switching to these settings, but recommend using them internally.
> Add a stricter version of pylint rcfile

- Orange/data/table.py
- Orange/tests/test_sparse_table.py
- Orange/tests/test_table.py
- Orange/widgets/utils/owlearnerwidget.py
- Orange/widgets/utils/tests/test_owlearnerwidget.py
Fixes #2498.
`Table` now automatically densifies `Y`.
> Densify sparse targets when fitting models

- Orange/widgets/utils/plot/owplotgui.py
- Orange/widgets/visualize/owradviz.py
Fixes #3744
* Rotate variable labels according to the angel of position
* Shorten labels to 20 characters
* Show tooltip with the full label name 
* Limit number of selected variables to 20
> [FIX] OWRadviz: legible axis labels

- Orange/misc/distmatrix.py
- Orange/tests/test_distances.py
Fixes #3658
Due to DistMatrix.max() returning Python int objects, numpy functions like np.testing.assert_array_equal fail unexpectedly.
When returning zero dimensional array use indexing to get a numpy datatype.
> [FIX] DistMatrix should return numpy datatypes

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
- Orange/widgets/visualize/utils/widget.py
Fixes #3746 - displaying of datetime variables in visualization legends, as well as, probably, weird number of decimals for other numeric attributes.
Labels for color legend are created by palette, which is not aware of attributes. Palette is called by `OWScatterplotGraph`, which also doesn't know about attributes. On the other hand, the widget, which provides labels for discrete attributes (via `get_color_labels`), doesn't know how the graph will discretize continuous values, hence it can't provide a list.
A reasonable solution is that `get_color_labels`, which currently returns `None` for continuous variables, returns a formatter, that is, function that takes a number and returns a string. For most cases, this will be variables `str_val`. If it returns `None`, the widget uses the same …
> OWScatterplotGraph: Use get_color_labels to return number formatter

- Orange/widgets/data/owcreateclass.py
- Orange/widgets/data/tests/test_owcreateclass.py
Fixes #2346.
The widget now internally caches created variables. A comment in the code explains why `make` wouldn't work here.
> [FIX] OWCreateClass: Reuse variables created with same settings

- pylintrc
In the latest pylintrc file, `no-member` was erroneously enabled because of a missing comma.
> pylint: Add a missing comma in disable

- Orange/widgets/visualize/owboxplot.py
Fixes #3740.
The remaining problem is that axis labels may stick out of view.
> Box plot: Use str_val to print out labels

- Orange/widgets/data/owfile.py
Fixes https://github.com/biolab/orange3/issues/3538
Since URLs are case sensitive this PR I set the completer of the QComboBox to be case sensitive. With this setting, the combo box does not replace partly upper case URLs with lower case URLs from history and vice versa.
> OWFile: Make url combobox case sensitive.

- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/tests/test_owmosaic.py
- Orange/widgets/visualize/utils/plotutils.py
Fixes #3052.
The function for wrapping the legend is put into module `plotutil`, so it can also be used elsewhere.
~~*TODO*: When decreasing the widget height, the legend can fall out of view at the bottom, despite my attempts to correctly compute the maximal square size.~~
> [ENH] Mosaic: Wrap legend

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
Fixes #3589
1) Reused QPen, QBrush objects and rounded sizes to half a pixel so that the number of different symbols to draw is lower.
2) Deferred updateSpots() that gets called by pyqtgraph in set*() to paint(), where spot atlas is actually needed.
Now adult  with spots of same color, shape=occupation, size=fnlwgt displays in less than 1 second instead of 10.5s as before.
> [ENH] Faster drawing in scatterplot

- Orange/projection/manifold.py
Fixes #3523.
Load openTSNE (and, in turn, numba) as a lazy module.
> [ENH] t-SNE: Load openTSNE lazily

- Orange/widgets/visualize/owradviz.py
I added a limit to the number of selected variables in #3809 but forgot to add the limit to the RadvizVizRank.
Limit the number of variables in RadvizVizRank.
> [FIX] OWRadviz: limit number of vars in RadvizVizRank

- Orange/widgets/data/owcsvimport.py
- Orange/widgets/utils/encodings.py
- Orange/widgets/utils/textimport.py
- requirements-core.txt
Pylint the files added in gh-3876
Also fix other issues:
* CSV File Import needs `pandas` as a requirement
* One branch in `TablePreviewModel.data` had a missing return statement
> CSV File Import: pylint

- README-dev.md
Closes #3839
I tried a clean install from source on Windows and it was relatively straightforward after installing the huge (>1GB) visual studio build tools. I moved the basic development info to a separate readme, where we can elaborate on any other issues.
> [FIX] Development readme

- Orange/evaluation/clustering.py
- Orange/evaluation/testing.py
- Orange/tests/test_evaluation_clustering.py
- Orange/tests/test_evaluation_scoring.py
- Orange/tests/test_evaluation_testing.py
- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
- pylintrc
Fixes #3857.
`Results` stores results of validation, but derived classes also perform the validation. A vaguely remember making this (bad) decision at our retreat in Bohinj. :)
These changes break the backward compatibility with `Results` class, but the class itself has been broken for five years, so I doubt anybody used it. To my observation, all code calls `Results()` without arguments.
> Make Results (more like) a dataclass, separate Validation hierarchy

- Orange/widgets/visualize/tests/test_owfreeviz.py
Freeviz test do not shutdown/stop the concurrent task, starting new ones when old have not finished.
Shutdown in test's tearDown.
A small speed up from ~7s to ~4.5s when running `test_owfreeviz`
> test_owfreeviz: Shutdown when finished

- Orange/projection/manifold.py
Reverts biolab/orange3#3883 because of #3893
> Revert "[ENH] t-SNE: Load openTSNE lazily"

- Orange/widgets/visualize/owlinearprojection.py
Fixes #3743
Limit the number of displayed axis and labels length to 20.
> [FIX] OWLinearProjection: limit axis

- Orange/canvas/__main__.py
The user could perhaps download a new version and then forgot to install it.
Notify users about new versions unless they explicitly reject a specific update.
> Update check: keep showing at startup until explicitly rejected

- Orange/widgets/data/owcolor.py
- Orange/widgets/data/owconcatenate.py
- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/owneighbors.py
- Orange/widgets/data/owrandomize.py
- Orange/widgets/data/owtranspose.py
- Orange/widgets/data/tests/test_owcolor.py
- Orange/widgets/data/tests/test_owconcatenate.py
- Orange/widgets/data/tests/test_owmergedata.py
- Orange/widgets/data/tests/test_owneighbors.py
- Orange/widgets/data/tests/test_owrandomize.py
- Orange/widgets/data/tests/test_owtranspose.py
- Orange/widgets/unsupervised/owdistancematrix.py
- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/owmanifoldlearning.py
- Orange/widgets/unsupervised/tests/test_owdistancematrix.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
- Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py
- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
Fixes #3761.
Call `unconditional_apply` instead of `apply`; remove the pointless auto commit checkbox in box plot.
> [FIX] Update output on new input, even if auto commit is disabled

- Orange/evaluation/scoring.py
- Orange/tests/test_evaluation_scoring.py
Implements #3879
Added Specificity as a new score in Test&Score
> [ENH] Added Specificity as a new score in Test&Score

- Orange/data/table.py
- Orange/tests/test_table.py
- doc/data-mining-library/source/reference/data.table.rst
Fixes #3908 by making the warning visible (`DeprecationWarning` and `PendingDeprecationWarning` are ignored by default) and by adding a note into documentation.
> Table: Enable warning about deprecation of table changes, add it to doc

- Orange/canvas/config.py
After the website change, the widget catalog URL changed. This PR updates it to the correct URL.
> Fix 404ing widget documentation URL

- Orange/widgets/data/owneighbors.py
Manual apply didn't work for `number of neighbors` and `Exclude rows`. Those two fields were applied automatically even when `Apply automatically` unchecked.
Manual apply is enabled for `number of neighbors` and `Exclude rows`.
> [FIX] OWNeighbours fix manual apply for some options

- Orange/canvas/report.py
- Orange/canvas/utils/environ.py
Orange.canvas.utils.environ and Orange.canvas.report were at one point part of API intended for external use. They were both already deprecated before gh-3772, but never emitted visible deprecation warnings.
Restore Orange.canvas.utils.environ and Orange.canvas.report and raise visible FutureWarnings.
> [FIX] Backcompatibility stubs

- Orange/preprocess/discretize.py
- Orange/widgets/gui.py
- Orange/widgets/utils/annotated_data.py
- Orange/widgets/utils/tests/test_annotated_data.py
- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/tests/test_owdistributions.py
- Orange/widgets/visualize/utils/plotutils.py
- The widget does not look nice. In particular, numeric variables are discretized and histograms look like histograms of discrete variables
- Fixes #1849: Adds curve fitting
- Fixes #3736: legible axis labels
- Current non-parametric curves will become just one of possible curves
- Showing histograms and fitted curves should not be exclusive
- Widget's code should be improved and modernized
**To do:**
> [ENH] Shiny renewed widget Distributions

- Orange/canvas/config.py
- Orange/misc/environ.py
Fixes gh-3931
Since gh-3772 the `environ.widget_settings_dir` is no longer the authoritative directory path.
* Deprecate `Orange.misc.environ.widget_settings_dir`, (but make it return the correct path).
* Change the application name to 'Orange' to preserve historical directory layout (the application name is used as the path component in the settings path).
> [FIX] main: Fix widget settings directory path to clear

- Orange/canvas/__main__.py
- Orange/canvas/config.py
- Orange/canvas/mainwindow.py
- requirements-gui.txt
Usage tracking an related user preferences settings were lost in gh-3772 
* Extend preferences dialog and add back setting controls lost in the refactoring
* Re-enable usage tracking
> [FIX] Restore usage tracking

- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/unsupervised/tests/test_owhierarchicalclustering.py
- Orange/widgets/utils/stickygraphicsview.py
- Orange/widgets/utils/tests/test_stickygraphicsview.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/owsilhouetteplot.py
Fixes gh-3918
Fixes gh-1745
Add s StickyGraphicsView utility class implementing a sticky header/footer views to anchor scene header/footer in the view.
Hierarchical Clustering: Move the top and bottom scales into the same scene as the dendrogram (and are therefore exported to image along with it - gh-3918).
Silhouette Plot: Anchor top and bottom scales in the view.
Heatmap: Anchor top dendrogram/labels and bottom labels in view when applicable (gh-1745).
> [ENH] Sticky graphics header/footer views

- Orange/classification/svm.py
- Orange/preprocess/preprocess.py
- Orange/preprocess/transformation.py
- Orange/tests/test_preprocess.py
- Orange/widgets/model/owsvm.py
- Orange/widgets/model/tests/test_owsvm.py
- Orange/widgets/utils/owlearnerwidget.py
Fixes  #3202
SVM was failing because Corpus widget outputs sparse matrix which must be then turned to dense, if we want to mean shift it. We would like to avoid that, so the current proposal is to just scale the data. The user can opt out trough a check box. Currently the check box is in the optimization parameters box, perhaps something else is needed.
> [FIX] Change normalization to Scaling in SVM

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owprojectionwidget.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
- Orange/widgets/visualize/utils/widget.py
Fixes #3748
Projections now show six different shapes; if there are more,  they show five most frequent + "Other".
The first five shapes were, imho, also most visually distinct, I just swapped the sixth (square) with the last (star), which also makes sense because it will represent "Other".
Changes are not backward compatible, but I suppose (ehm, hope) nobody should notice. I prefer having clear arguments than methods with contrieved arguments for backward compatibility when this can be avoided. @VesnaT?
> Projection widgets: Reduce number of shapes to 6 (5 + other)

- Orange/data/table.py
- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/tests/test_owmergedata.py
Fixes #2121 by allowing multiple pairs of columns to be matched.
As a consequence, we require that the combination of values is unique, so combos list all available attributes. These lists are unfortunately longer, yet the upside is that the widget does not show a warning every time when it gets data with non-unique attributes (which is ... always). One may argue that it would be nice to show to the user which columns are useful for merging, but the user probably has a very good idea of what (s)he wants to match.
> [ENH] Merge data allows matching by multiple pairs of columns

- appveyor.yml
Tests starts to fail with
Could not find a version that satisfies the requirement numpy==1.9.3
Numpy version raised to 1.13.*
> Appveryor: Build numpy version raised to 1.13.*

- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
Fixes #2900. Fixes #3056.
- Lets the expression for discrete variables return strings instead of indices.
If the user defines values, the function must return integer indices. If function returns strings (or instances of Value), the user mustn't define values. It is contrived, but you can't have both. We will have to mention this in documentation. :) If you have a better solution, feel free to change the code.
- Casts string values into strings, so name[0] is now a valid expression for zoo. Before, you'd have to write str(name)[0] -- and, of course, list all possible values.
- Allows creation of Date / Time variables. If expression returns a string, it is parsed as date/time.
> [ENH] Feature Constructor: Easier categorical features, allow creation of date/time, easier use of string data

- Orange/widgets/visualize/owboxplot.py
Fixes #3927
Move the t-test or anova statistic from the widget onto the plot, which puts it in the report and on the exported image.
> [ENH] BoxPlot: Write the anova/t-test statistic onto the plot.

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/utils/widget.py
Fixes #3944.
@VesnaT, please confirm this is the right way to do it and that nothing else is needed - also considering possible other similar bugs.
> [FIX] OWProjectionWidgetBase: Update when domain is changed

- scripts/windows/condainstall.bat
The stock miniconda 4.7.0 installer (current latest) installs libarchive package that fails to import if env is not activated (and it is imported by the conda command).
Activate the root env in the condainstall.bat utility script.
Also install the vc runtime packages before the rest (again).
> installers: Activate the root conda env in the condainstall.bat

- Orange/widgets/evaluate/owcalibrationplot.py
Fixes https://github.com/biolab/orange3/issues/3973
The formula for specificity in description fixed to TN / N. I also checked the correctness of the method and found out that correct formula is used in the calculation of specificity.
> OWCalibrationPlot: Specificity definition fixed

- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
- Orange/widgets/evaluate/tests/test_utils.py
- Orange/widgets/evaluate/utils.py
Fixes #3947 by using a QSortFilterProxy that sorts numerically, if column values can be converted to numbers, or case-insensitive, if they can't.
> [FIX] Test and Score: Sort numerically, not alphabetically

- appveyor.yml
- requirements-core.txt
AppVeyor fails on openTSNE import - reason numba issue.
With this PR we fixed the numpy version on 1.1.6.* It can be undone when numba resolves an issue.
> Fix numpy version on 1.16.*

- Orange/widgets/visualize/owboxplot.py
Fixes #3976
Made boxplot showing box when one of the quartiles equal to median
> [FIX] Boxplot fix

- Orange/distance/distance.py
- Orange/distance/tests/test_distance.py
Hamming distances between input data and secondary data can not be computed.
Enable computation of Hamming distances between input and secondary data.
> Hamming distance:  Distances calculation between input and secondary data

- Orange/classification/elliptic_envelope.py
- Orange/classification/svm.py
- Orange/tests/test_elliptic_envelope.py
- Orange/tests/test_svm.py
- Orange/widgets/data/owoutliers.py
Fixes #1906
#1906 was fixed temporarily in #1907 and then more properly in #2677, but the fix was only in the `Outliers` widget and not in the underlying learner classes (`OneClassSVMLearner`, `EllipticEnvelopeLearner`).
This does the same transformation (remove classes), but in learners instead of the widget.
> Outliers: Move fix from widget to learners

- Orange/canvas/__main__.py
- Orange/canvas/config.py
Instead of setting `machine-id` to empty string by default, initialize it to a randomly generated value with `uuid.uuid4()`.
As the next release of Orange changes the name of the `.ini` config file due to the separation of orange3 and orange-canvas-core, all machines will initialize their machine ID this way, regardless of its value in previous installation of Orange.
A user should still be able to change their machine ID to an empty string, and this should be used in the useragent string and in error reporting. 
https://github.com/biolab/orange-widget-base/pull/11
> Add anonymous machine ID to useragent string

- scripts/windows/build-conda-installer.sh
- scripts/windows/condainstall.bat
- scripts/windows/sitecustomize.py
(Ana)conda python distribution expects to be 'activated', but we use it without in shortcuts and open commands etc.
Add the ${PREFIX}\Library\bin to PATH if not already there.
Transplated From: biolab/orange3-single-cell@5934d6d06783238c6fffceb3a611495d6708f397
> [FIX] Conda Installer: Restore compatibility with latest anaconda python

- Orange/canvas/__main__.py
> Usage statistics request specifics, anaconda addition

- Orange/data/table.py
- Orange/tests/test_sparse_table.py
- Orange/tests/test_table.py
- Orange/widgets/data/owconcatenate.py
- doc/data-mining-library/source/reference/data.table.rst
`Table.append`, `Table.extend`, `Table.insert` and `Table.__delitem__` are useless, unused, unsafe and caused problems in tests on Python 3.7. 
Remove them. Tests are already removed in #3500 on which this commit is based. (**Merge #3500 before this one.**)
> Remove methods that change table length

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
Tests fail because of @pavlin-policar's time bomb. Copycat.
> Remove deprecated Orange.statistics.util.array_equal

- Orange/widgets/data/owcorrelations.py
- Orange/widgets/data/tests/test_owcorrelations.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/tests/test_owlinearprojection.py
- Orange/widgets/visualize/tests/test_vizrankdialog.py
- Orange/widgets/visualize/utils/__init__.py
Fixes #4008
Since adding the progress bar was somehow trivial, making the widget responsive was not and I'm still not sure about the solution.
The widget was getting unresponsive for datasets with small number of instances and many features. In those cases correlation between a pair of features was calculated 'too fast' which caused a signal, for setting partial results, being emitted too frequently. Consequently the widget was getting unresponsive.
To prevent the congestion, the signal is only emitted every 0.01 second.
> [FIX] Correlations: Add progress bar, retain responsiveness

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Vizrank button was disabled for datasets with a constant feature. 
Enable the button for datasets with a constant feature.
Add a tooltip on the button with a reason for disabling it.
> [FIX] Scatterplot: Enable/disable vizrank button

- Orange/widgets/data/owsave.py
- Orange/widgets/data/tests/test_owsave.py
As discussed today with @BlazZupan, we will have separate widgets for saving different formats. (Arguments: we also have separate widgets for loading because they are very different (see, e.g. File widget); it is unclear how should the widget handle file names and extensions.)
These save widget can have a lot of code in common. See https://github.com/biolab/orange3-network/pull/133/commits/1e31a1152869284d931145d4574afe75fdb4bd61#diff-b0e9bcea74d7871d7cc674526283f1b0 for example of a simple save widget.
It would be possible to extract some more code by using a meta class for the base widget, but I prefer keeping this simple.
Unit testts still test `OWSave` and not `OWSaveBase`. `OWSaveBase` is an abstract widget that would require a lot of mocks to run, so it's simpler to just test …
> OWSave: Extract general code into a base class

- Orange/widgets/evaluate/owpredictions.py
Fixes #4029.
#3943 added two new columns that do not come from scorers. All widgets that use `Orange.widgets.evaluate.ScoreTable` need to adapt the models. Fortunately, there is only one, Predictions (besides Test and Score). Unfortunately, it was not adapted. :)
The first two columns are now initialized to N/A.
> [BUG] Predictions: Fix misaligned columns

- Orange/canvas/__main__.py
- Orange/canvas/config.py
- Orange/canvas/mainwindow.py
Adds a toggleable option to enable/disable pulling the notification feed (default enabled). Note, this does not affect the update check notification.
> Add config option to enable/disable notification feed

- Orange/widgets/data/owtable.py
- Orange/widgets/data/tests/test_owtable.py
- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/unsupervised/tests/test_owdistancemap.py
- Orange/widgets/unsupervised/tests/test_owmds.py
- Orange/widgets/unsupervised/tests/test_owtsne.py
- Orange/widgets/utils/tests/test_concurrent_example.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/owlineplot.py
- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/owsilhouetteplot.py
- Orange/widgets/visualize/owvenndiagram.py
- Orange/widgets/visualize/tests/test_owheatmap.py
- Orange/widgets/visualize/tests/test_owlineplot.py
- Orange/widgets/visualize/tests/test_owmosaic.py
- Orange/widgets/visualize/tests/test_owprojectionwidget.py
- Orange/widgets/visualize/tests/test_owsilhouetteplot.py
- Orange/widgets/visualize/tests/test_owvenndiagram.py
- Orange/widgets/visualize/utils/widget.py
Fixes #3762. Fixes #3763.
Following @markotoplak suggestion, instance selections are schema-only because data is not a part of the context.
> [FIX] Fix storing and retrieving selection, and unconditional auto commit

- Orange/canvas/__main__.py
> Machine ID initialization, inclusion in useragent string and statistics sessions

- Orange/widgets/data/icons/Pivot.svg
Adds a white background to pivot table's icon. I believe that with this change, all data widgets are correctly transparent/have a white background.
Other widgets should be inspected too (some that come to mind: Box Plot, Save Distances).
> Add white background to Pivot Table icon

- Orange/canvas/__main__.py
Deprecation warnings when running Orange.
- Change `formated` -> `formatted`
(https://github.com/biolab/orange-canvas-core/commit/36142fb48d46e9ca178501ca2668cdcdb30f1c13)
- Change `Orange.canvas.config.widget_settings_dir` -> `Orange.widgets.settings.widget_settings_dir`
(#3932) 
@ales-erjavec Can you double check that the second one is the correct new way of getting widgets settings dir?
> Update deprecated methods

- Orange/widgets/unsupervised/owpca.py
- Orange/widgets/unsupervised/tests/test_owpca.py
Fixes #4037.
Don't check whether new number of components equals the original after already updating the original.
If `_nselected_components` was called for side effects, it shouldn't had been: `self.ncomponents` cannot be out of range, and the only effect or computing `self.ncomponents` from `self.variance_covered` (which has itself been just computed from `self.ncomponets`) can be problems due to rounding.
> OWPCA: Fix invalid callback on treshold drag

- doc/widgets.json
Widget info that is built from an Orange installation and will be used by the website to show the widget catalog.
Created by:
~/orange3/doc$ python ~/orange-hugo/scripts/create_widget_catalog.py --categories Data,Visualize,Model,Evaluate,Unsupervised, --doc visual-programming/source/ 
(from my yet unmerged widget-catalog branch)
> widgets.json for the new website

- Orange/base.py
- Orange/widgets/evaluate/owconfusionmatrix.py
- Orange/widgets/evaluate/owrocanalysis.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
- Orange/widgets/evaluate/utils.py
> [FIX] Predictions: Handle discrete target with no values

- Orange/widgets/data/owcorrelations.py
- Orange/widgets/data/tests/test_owcorrelations.py
> [ENH] Correlations: Include continuous class and meta variables

- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
> [FIX] k-Means: Impute missing values

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/tests/data-regions.tab
- Orange/widgets/data/tests/test_owmergedata.py
Fixes #4070
- implement Variable.rename(name)
- check for duplicate variable names in domain and rename if any
> [FIX] Merge data: Rename variables with duplicated names

- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
Fix ```FutureWarning: 'processEvents' argument is deprecated.``` by removing the argument
> [FIX] Deprecated processEvents argument in Test&Score

- Orange/widgets/data/owconcatenate.py
- Orange/widgets/data/tests/test_owconcatenate.py
Fixes  https://github.com/biolab/orange3-text/issues/243
We concluded that bag of words can be concatenated only with other Bow, so error is issued if the user tries to concatenate anything else.
> Concatenation of BoW with Corpus

- Orange/canvas/__main__.py
Previously, start and end dates were mistakenly implemented exclusively.
> Consider YAML Notification start and end dates inclusively

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/widgets/data/owcolor.py
- Orange/widgets/data/tests/test_owcolor.py
After removing `Variable.make`, `OWColor` fails when loading settings because it tries to set `Variable.name` when loading settings.
The widget was misbehaving badly. `set_data` constructed the output table(!) and modified its attributes (not only colors but also names!). This most probably also broke `Domain`'s dictionary `_indices`.
Fixing this required reimplementing the way in which the widget stores the data. Instead of storing variables, it stores the data (names, colors) and constructs variables before sending output.
#3822 could have also been the result of the questionable behaviour of the widget and may be fixed with this PR.
> [FIX] Color widget failed after removing Variable.make

- Orange/__init__.py
- Orange/util.py
Orange was trying to kind, but it was actually misleading.
Case: in a new virtualenv I did:
```
pip install sip pyqt5==5.9.2
pip install orange3
```
Then orange-canvas returned
```
File "/home/marko/venvt/bin/orange-canvas", line 6, in <module>
from Orange.canvas.__main__ import main
File "/home/marko/venvt/lib/python3.6/site-packages/Orange/__init__.py", line 9, in <module>
"pip install --no-binary Orange3") from None
ImportError: Compiled libraries cannot be found.
Try reinstalling the package with:
pip install --no-binary Orange3
```
When I changed the exception to catch something else I got:
```
File "/home/marko/venvt/bin/orange-canvas", line 6, in <module>
from Orange.canvas.__main__ import main
File …
```
> Do not mask import errors of the Orange.data._variable

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
Fixes #4065.
This approach could be costly if getting the colors and sizes from master is slow -- which, I think, we said shouldn't be the case: the graph requests this data multiple times and the widget should have it cached if necessary.
The advantage of this approach is that it doesn't require a new function provided by widget.
@VesnaT's opinion would be appreciated.
> OWScatterPlotGraph: Don't combine color and shape legend for different data

- Orange/canvas/__main__.py
In certain cases, the UUID python object was written to config as `machine_id` instead of a string. This change casts it to string before writing it to config.
> Fix incorrectly set machine id

- Orange/base.py
- Orange/statistics/util.py
- Orange/tests/test_statistics.py
Fixes #3987 
Model's data_to_model_domain fixed to accept also sparse data.
> [FIX] Model's data_to_model_domain supports sparse matrix

- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
The K-Means widget does not save Silhouette Scores selection.
Create a new schema-only setting to save the Silhouette Scores selection.
> [FIX] K-means: Save Silhouette Scores selection

- Orange/widgets/unsupervised/tests/test_owdistancemap.py
- requirements-gui.txt
Remove upper version constraint for orange-widget-base requirement.
Update required version of orange-widget-base
Fix a test for owdistancemap's selection restore. It was always wrong, but would now fail since https://github.com/biolab/orange-widget-base/pull/13
> Update version constraint for orange-widget-base

- Orange/widgets/unsupervised/owsom.py
SOM restores height into width due to a trivial copy/paste mistake.
> [FIX] Self-Organizing Map: Fix restoring width

- Orange/widgets/data/owdatasets.py
- Orange/widgets/data/tests/test_owdatasets.py
Sapientem sat?
(Fixes #4069.)
To show indicators with different colors, it needs https://github.com/biolab/orange-widget-base/pull/17. Before https://github.com/biolab/orange-widget-base/pull/17 is merged, indicators will remain black, as they are now, but the widget will still work.
> [ENH] Datasets: Remove control area

- Orange/widgets/utils/domaineditor.py
Fixes #3963
Added additional branch when converting to string.
> [FIX] Datetime conversion to string

- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
Fixes #4075.
- Add normalization checkbox.
- Fix tests
- Remove obsolete argument `processEvents`
> [ENH] k-Means: Add normalization checkbox

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Feature selection is enabled, even though features are passed to the input of Scatterplot.
To reproduce: File (Iris) -> Scatterplot
-> Correlations -> Scatterplot -> Axis x, Axis y and Find Informative Projections are enabled
Similar to #4101.
- disable table and button on vizrank popup when features are not the input of the widget
- disable attr_x and attr_y selection when features are not the input of the widget
- initialize vizrank only when data (input) changes, not features
> [FIX] Scatterplot: Disable vizrank when features on input

- Orange/widgets/model/owlogisticregression.py
- Orange/widgets/tests/base.py
If slider was moved, the model was built multiple times, which was a problem for bigger data sets.
Needs biolab/orange-widget-base#7
> Logistic regression regularization slider acts when dragging stopped

- Orange/widgets/data/owcsvimport.py
After finishing the widget sometimes still displays the progress.
Make the progress update connection to the widget using a direct
connection to ensure no pending queued updates are received.
> [FIX] owcsvimport: Make the progress update a direct connection

- Orange/widgets/utils/owbasesql.py
- Orange/widgets/utils/tests/test_owbasesql.py
Some add-ons require a widget to connect to a database. 
To avoid copying the code over and over again, create a base widget that holds the common code for the DB connection.
- a base widget to establish a DB connection
- refactor OWSQL so it extends OWBaseSql  (TODO: in next PR)
> [ENH] OWBaseSql: Base widget for connecting to a database

- Orange/widgets/data/tests/test_owneighbors.py
Fixes #4117 
This PR implements a small addition to tests based on https://github.com/biolab/orange3/issues/4117
> Neighbours additional tests for different domains

- Orange/data/tests/test_io.py
- Orange/data/variable.py
- Orange/widgets/data/owfile.py
Fixes https://github.com/biolab/orange3/issues/4094
As @janezd suggested the variable with more than 100 different values should not be DiscreteVariable. This PR:
- changes guessing mechanism such that the variable with more than 100 different values is not a StringVariable
- add tests for `guess_data_type` function
- `OWFile` warns the user who set the variable with more than 100 different values as a DiscreteVariable
> [FIX] Warning for discrete variable with >100 values in OWFile

- Orange/preprocess/normalize.py
- Orange/tests/datasets/test10.tab
- Orange/tests/datasets/test5.tab
- Orange/tests/test_distances.py
- Orange/tests/test_normalize.py
Normalization crashes when data contains a feature without a value.
To reproduce: File (Iris) -> Feature Constructor (new `numeric` variable with expression: `nan`) -> Preprocess (Normalize Features (normalize to interval))
Feature with missing values retains missing values after normalization.
> [FIX] Normalize: Fix crash with nan column

- Orange/data/tests/test_sql_mssql.py
Fixes #4129
Skip unittess if pymssql is not installed.
> PymssqlBackend: Skip tests if pymssql not installed

- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/tests/test_owmergedata.py
> [ENH] MergeData: Don't remove duplicate columns with different data

- Orange/distance/__init__.py
- Orange/distance/distance.py
- Orange/tests/test_distances.py
- Orange/widgets/unsupervised/owdistances.py
- Orange/widgets/unsupervised/tests/test_owdistances.py
- doc/visual-programming/source/widgets/unsupervised/distances.md
A new metric is introduced in distances widget. Bhatthacharayya is used to measure the distance between distributions. Currently, the user has to already have the data that they see as a distribution. In the future, pivot could be extended to have aggregation of all features, filtered by column values, so distributions could be generated in Orange itself.
> [ENH] Bhatthacharayya distance

- Orange/widgets/data/owpreprocess.py
- Orange/widgets/data/tests/test_owpreprocess.py
Fixes #4145 and #4103
Select Random Features, Select Relevant Features and CUR Matrix Decomposition preprocessors as implemented in the Preprocess widget allow the user to enter only a very limited number of attributes.
Set maximum possible value to be 1000000.
> [ENH] Preprocess: Max number of features

- appveyor.yml
Appveyor CI step attempts and fails to build pre release of bottleneck 1.3.rc1
Remove '--pre' from the test install command and bump pip version to 19.*
> [MNT] CI: No pre-release deps in appveyor.yml

- Orange/widgets/evaluate/owliftcurve.py
- Orange/widgets/evaluate/owrocanalysis.py
Fixes #4115: Lift curve and ROC Analysis did not have context settings. (Also because there was no suitable handler before #3881; #3881 implemented such a handler for the new calibration plot widget and even [noticed that Lift Curve and ROC Analysis can now use it](https://github.com/biolab/orange3/pull/3881/files#r295931586) :).
Use `EvaluationResultsContextHandler` in the two widgets.
> [FIX] ROC and LiftCurve: Store context settings

- scripts/windows/build-conda-installer.sh
Fixes #4112
Updated installer fixes #4112 for users that do not have Miniconda installed. Those that already have the previous version need to uninstall it manually.
> Update miniconda version in Windows installer to 4.7.12

- Orange/widgets/unsupervised/tests/test_owsom.py
We don't know the exact cause, but it happens in a test that is not supposed to test optimization, so this PR mocks optimization in hope it will help.
> [FIX] Fix core dump in CI in SOM on sparse data

- Orange/widgets/unsupervised/tests/test_owsom.py
I am stupid.
When I wrote tests for SOM, I apparently noticed that `tearDown` doesn't call `self.widget.onDeleteWidget`. Instead of adding it to the inherited method, I added my own `tearDown` ... and haven't called the inherited.
`onDeleteWidget` still probably needs to be called in `WidgetTest.tearDown`.
> SOM tests: Call inherited tearDown

- scripts/windows/build-conda-installer.sh
- scripts/windows/orange-conda.nsi
Fixes gh-3830
Use the version from python package that will be installed and not miniconda python version for the compatibility check.
Also make Miniconda installer version configurable from the command line.
> [FIX] build-conda-installer.sh: Do not use python version from Miniconda

- Orange/widgets/unsupervised/owcorrespondence.py
- Orange/widgets/unsupervised/tests/test_owcorrespondence.py
- doc/visual-programming/source/widgets/unsupervised/correspondenceanalysis.md
Fixes #4088
Added output with correspondence analysis coordinates. I added coordinates off all components not just selected two.
> [WIP][ENH] Output to OWCorrespondence

- Orange/widgets/unsupervised/owsom.py
- Orange/widgets/unsupervised/tests/test_owsom.py
Fixes #4168.
Don't "reset" selection when clicking on empty canvas.
> [FIX] SOM: Fix crash when clicking on empty canvas

- Orange/preprocess/preprocess.py
- Orange/tests/test_preprocess.py
- Orange/widgets/data/owpreprocess.py
- Orange/widgets/data/tests/test_owpreprocess.py
- doc/visual-programming/source/widgets/data/preprocess.md
Preprocessor widget now enables removing sparse features. Threshold is up to the user. I thought we could use the same icon as feature selection and cur decomposition.
> [ENH] Add remove sparse features preprocessor

- MANIFEST.in
- appveyor.yml
- pyproject.toml
Add support for [pep518](https://www.python.org/dev/peps/pep-0518/)/[pep517](https://www.python.org/dev/peps/pep-0517/) build dependency specification.
Add pyproject.toml
> [ENH] Add pyproject.toml

- Orange/widgets/unsupervised/owlouvainclustering.py
- Orange/widgets/unsupervised/tests/test_owlouvain.py
Fixes #4182, also when just chaning the dataset and changing it back settings did not restored. 
Removed two lines that caused that settings did not restore to the old value. In my opinion, those two lines are not required since spin has the same functionality itself.
> [FIX] Louvain Clustering: fix setting to restore correctly

- Orange/canvas/__main__.py
- Orange/canvas/config.py
- Orange/canvas/mainwindow.py
In light of https://github.com/biolab/orange-canvas-core/pull/49, it's right to inform the user of updates to usage statistics collection and to request permission anew.
By renaming the `error-reporting` config category to `reporting`, the following config values are reset:
- `error-reporting/machine-id` [`uuid.uuid4()`]
- `error-reporting/send-statistics` [`False`]
- `error-reporting/add-scheme` [`True`] (default value for sending scheme along with error report)
Additionally, the preferences pane is narrower due to a smaller tab name.
> Reset statistics collection permission, add more info link

- Orange/widgets/visualize/owscatterplotgraph.py
For categorical: symbols on legend are not aligned with text.
For numerical: pallet and text are not in the center of legend, also legend window too wide.
Examples are from Dataset(Illegal waste dumpsites in Slovenia) -> Scatter Plot, then select "Location type" for categorical and "Waste volume" for numerical
Comparison:
> OWScatterPlotBase: fix unaligned items on legend

- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
Box plot shows distribution of some attribute and, if grouping is enabled, how the distribution of this attribute varies accross groups. It thus conveys information about conditional probability of the target variable given the value of the grouping variable.
If "Order by importance" is checked, the widget computes the chi square or ANOVA between all target variables and the currently selected group. This may help the user answer the question "If I divide the data into such and such groups, which is the attribute by which these groups differ most".
However, since the widget shows the conditional probability of the target given the grouping variable, it might make more sense to sort grouping variables. This will allow the user to set the target (typically the outcome, the class) and see …
> [ENH] Box plot: Add 'order by importance' checkbox to groups

- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
Box plot is uninformative if bars are stretched when group variable is the same as variable we are showing.
> [ENH] Boxplot no longer stretches bars when this is uninformative

- .travis/install_mssql.sh
- appveyor.yml
- requirements-sql.txt
Orange no longer builds because pymssql is discontinued and version 3.0 deliberately blocks building. 
The temporary solution proposed in pymssql is to freeze version. The longterm solution is to migrate to ODBC.
> pymssql: Freeze to version <3.0

- Orange/canvas/__main__.py
- conda-recipe/meta.yaml
- requirements-gui.txt
To be merged after https://github.com/biolab/orange-canvas-core/pull/49.
Call the `UsageStatistics.load()` static function instead of instantiating the class and calling the method.
> Adapt usage statistics for orange-canvas-core 0.1.9

- Orange/preprocess/fss.py
- Orange/preprocess/tests/test_fss.py
Fixes #4202 
When mask was empty, numpy assumed `dtype` is `float` instead of `bool`.
> [FIX] Fix crash in Preprocess' Select Relevant Features when there are no features

- Orange/widgets/data/owimpute.py
- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/owlouvainclustering.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
- requirements-gui.txt
Fixes gh-4028
Requires:
* https://github.com/biolab/orange-canvas-core/pull/34 (merged and released)
* https://github.com/biolab/orange-widget-base/pull/18 (merged and released)
Remove use of input blocking 'blocking' state in favor of non-blocking output invalidation.
> [ENH] Test & Score Widget: Cancellability on input change.

- Orange/widgets/visualize/owheatmap.py
Fixes #4206.
- Switch do using `DomainModel` to get everything for free.
- Store the annotation variable as an instance of `Variable` instead of integer indices into domain.
- Use the original domain and not just the numeric features for context!
Settings cannot be migrated because they were broken. The annotation variable was stored as an index into the original domain, while context was stored based on filtered domain. The two could mismatch and settings could have been stored incorrectly, so they can't be safely migrated.
> [ENH] Heatmap: Allow labeling by any variable

- Orange/widgets/unsupervised/owhierarchicalclustering.py
Fixes gh-4192
Sync annotations with gui
> [FIX] Hierarchical Clustering: Fix Annotations selection

- Orange/widgets/data/utils/histogram.py
Fixes #4195.
The code that computed bins for coloring produced just 9 bins because data instances with values equal to the last edge were put in the previous bin because of `right=True`. Removing the argument solves the issue.
> Feature Statistics: Fix coloring of the last bin

- Orange/widgets/data/owfile.py
- Orange/widgets/data/tests/test_owfile.py
When no changes have been made in domain editor, it nevertheless created a new instance of Table with the same domain.
In addition to needless work, this prevented loading pkl files with subclasses of Table.
If domain did not change, leave the data alone.
> [FIX] File: Fix domain edit on no changes

- Orange/widgets/data/owfeatureconstructor.py
Feature Constructor did not work on Python 3.8 due to AST changes.
- Add the newly required argument `posonlyargs`
As far as I can tell, this does not cause any problems on older versions of python and is silently ignored (always empty anyway).
- Add support for new expression type `Constant` (which is replacing `Num`, `Str`, ...)
> [FIX] Feature Constructor: Compatibility with Python 3.8

- Orange/widgets/data/owtable.py
When receiving updated input the its tab is always moved to the last position.
Preserve tab position for existing input id.
> [FIX] owtable: Preserve tab order of updated inputs

- Orange/data/io.py
- Orange/data/tests/test_io.py
- Orange/data/variable.py
Orange do not recognize TimeVariable when data seems to be discrete.
Fixing guessing function such that it recognizes TimeVariable even it looks discrete.
> [FIX] Fix guessing strategy for date and time variables

- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/tests/test_owheatmap.py
Heat map splits vertically by discrete class variable. This is hardcoded in the widget but not always desired.
Allow (rows) split by other class or meta categorical var (not just the class var), or disable spliting at all.
> [ENH] owheatmap: Add Split By combo box

- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/tests/test_owheatmap.py
> [ENH] Heatmap: option to center color palette at 0

- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/utils/domaineditor.py
File widget fails on an attribute name change. It happens just in cases when only the name is changed and the type of variable stays the same.
Fixed name change using the copy function. It seems that the variable name is protected (no setter function).
> [FIX] File widget: fix name change

- Orange/data/table.py
FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
Change a non-sequence iterable (map object) to a sequence type (list).
> table: Avoid deprecated hstack use in concatenate

- Orange/ensembles/stack.py
- Orange/tests/test_ada_boost.py
- Orange/tests/test_classification.py
- Orange/tests/test_knn.py
- Orange/tests/test_linear_bfgs_regression.py
- Orange/tests/test_linear_regression.py
- Orange/tests/test_logistic_regression.py
- Orange/tests/test_naive_bayes.py
- Orange/tests/test_neural_network.py
- Orange/tests/test_polynomial_learner.py
- Orange/tests/test_random_forest.py
- Orange/tests/test_sgd.py
- Orange/tests/test_softmax_regression.py
- Orange/tests/test_stack.py
- Orange/tests/test_svm.py
Fixes #4233 - Removed deprecated constructor calls in Validation.
> Validation: Deprecated constructor calls removed

- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/tests/test_owmergedata.py
> [ENH] Merge Data: Implement context settings

- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
Feature Statistics crashes on data with an empty Domain.
To reproduce: File (iris) -> Select Columns (remove everything) -> Feature Statistics
Sort only if there is something to sort.
> [FIX] Feature Statistics: Do not crash on empty domain

- doc/visual-programming/source/widgets/data/continuize.md
Documentation for continuation widget is horrible. Shame mostly or entirely on me.
Per @ajdapretnar's suggestion, I separate the general description from the example, but keep this within bullets, not entirely separately, otherwise the reader needs to read two parts of text in parallel.
I tried to use terms variable, categorical and numeric instead of attribute, discrete and continuous, although this is a bit hard if the widget itself is called continuize.
> [DOC] Continuize: Improve documentation

- Orange/widgets/unsupervised/owlouvainclustering.py
- Orange/widgets/unsupervised/tests/test_owlouvain.py
> [FIX] Louvain Clustering: Update graph output for compatibility with the new network add-on

- Orange/widgets/unsupervised/owpca.py
- Orange/widgets/unsupervised/tests/test_owpca.py
Closes #3801.
To maintain backward compatibility, this adds a new signal instead of adding the original data as metas (ugly, not done in other widgets) or moving components to metas (incompatible).
> [ENH] PCA: Add a signal with original data + pca

- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/tests/test_owselectrows.py
Fixes #3952. Widget's settings stored variable names without type, and retrieved settings that did not really match.
Add variable types to settings.
~~Previous settings are not migrated because we cannot guess variable types in migration. A possible workaround would be to skip migration and instead add specific code for handling old settings in `decode_setting` and `match`.~~
Settings are not migrated; what crashed will still crash, but the only way to prevent this would be to clear settings entirely, which would harm more users than letting the widget crash for the few users who have existing settings and will change variables types.
> [FIX] Select Rows: Fix crash on changed variable type

- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/owtsne.py
- Orange/widgets/unsupervised/tests/test_owdistances.py
- Orange/widgets/unsupervised/tests/test_owmds.py
- Orange/widgets/unsupervised/tests/test_owtsne.py
- Orange/widgets/utils/concurrent.py
- Orange/widgets/utils/tests/concurrent_example.py
- Orange/widgets/utils/tests/test_concurrent_example.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/tests/test_owfreeviz.py
ConcurrentWidgetMixin subclasses don't stop computation when an input changes.
Set `invalidated` widget state (instead of `blocking` state) when stopping/starting the task.
> [ENH] ConcurrentWidgetMixin: Cancel task on input change

- Orange/widgets/data/owtable.py
- Orange/widgets/data/tests/test_owtable.py
Fixes #4184.
The problem was that the widget removed pending selection even if the preceeding widget sent None before actual data (which PCA did).
> [FIX] Table: Keep pending selection if data is None

- doc/visual-programming/source/widgets/data/file.md
- doc/visual-programming/source/widgets/data/pythonscript.md
1.) In documentation of File widget the link to the Other Formats title within the document was not working.
2.) In documentation of Python Script widget there was no reference to Orange library documentation, which is required to work with Table class etc. 
1.) Removed the link to the section, retaining only the title. 
2.) Added link to Orange library documentation.
> [DOC] Python Script: minor fixes

- .coveragerc
- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Resolves gh-4181
Add option to change column type to 'Edit Domain' widget.
> [ENH] Edit Domain: Reinterpret column type transforms

- Orange/widgets/visualize/owtreeviewer.py
I think this better visually differentiates a node's prediction from its next branching feature.
On a tangent, is the background color of a regression tree's nodes always this color by default? Either the background's or the separator line's color should be changed.
> [ENH] OWTreeViewer: Bold predicted values in tree nodes

- Orange/widgets/data/owselectcolumns.py
- Orange/widgets/data/tests/test_owselectcolumns.py
Selecting a variable in the "Features" list and pressing Up/Down button (to the left of the view) triggers a: 
```
File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/data/owselectcolumns.py", line 436, in move_down
self.move_rows(view, selected, 1)
File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/data/owselectcolumns.py", line 416, in move_rows
newrows = [min(max(0, row + offset), len(model) - 1) for row in rows]
File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/Orange/widgets/data/owselectcolumns.py", line 416, in <listcomp>
newrows = [min(max(0, …
```
> [FIX] owselectcolumns: Fix move up/down type error

- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/tests/test_owcsvimport.py
- setup.py
'CSV Import' does not store the current file/options in a workflow scheme if the current file is not explicitly selected after the widget is placed in the workflow.
1) Place the widget on the workflow and let it load the last loaded file (do not change anything), save the workflow.
2) Create a new workflow and add the 'CSV Import' widget, select a different file to load.
3) Reload the workflow from step 1. The widget will load the file from the second step.
Selecting a different file in step 1 would correctly store the item.
Call `set_current_file` in `__init__` to record the initial loaded file in the `scheme_only` recorded  `_session_items`.
> [FIX] owcsvimport: Fix last/recent item serialization

- .travis/install_orange.sh
- .travis/install_pyqt.sh
Orange crashes on travis with Qt 5.14.
Temporarily pin Qt to version below 5.14 to avoid crashes on Travis.
This should be reverted after a permanent fix.
> Pin Qt version below 5.14

- appveyor.yml
Appveyor CI pins scipy version that is incompatible with the latest release of numpy 1.18.0
Unpin scipy version.
> [CI] appveyor: Unpin scipy

- setup.py
Building with numpy.distutils 1.18.0 fails with an error:
```
running build
running build_py
File "./setup.py", line 480, in <module>
setup_package()
File "./setup.py", line 475, in setup_package
**extra_args
File "/Users/aleserjavec/virtual/py36/lib/python3.6/site-packages/numpy/distutils/core.py", line 171, in setup
return old_setup(**new_attr)
File "/Users/aleserjavec/virtual/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
return distutils.core.setup(**attrs)
File "/Users/aleserjavec/.local/opt/python3.6/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
dist.run_commands()
File "/Users/aleserjavec/.local/opt/python3.6/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, …
```
> [BLD] setup.py: numpy 1.18.0 compatibility

- Orange/widgets/utils/textimport.py
In Qt 5.14 'exclusive' is no longer a Q_PROPERTY of QActionGroup and hence the call raises a type error.
Remove 'exclusive' kwarg from QActionGroup call
> [FIX] utils/textimport: Remove 'exclusive' kwarg from QActionGroup call

- Orange/data/io.py
Solves #2974, the remaining issue noted by @PrimozGodec: if an Excel file contains formulae, after #4279 they are loaded as formulae, not values.
Add a `data_only` argument when opening the workbook (https://openpyxl.readthedocs.io/en/stable/api/openpyxl.reader.excel.html#openpyxl.reader.excel.load_workbook).
> Excel Reader: Read values, not formulae

- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/tests/test_owdistributions.py
Resolves #4119.
- Add a checkbox for hiding bars; add an attribute 'hidden' to bars and don't paint when it's True
- Move the check box for cummulative distributions to the box below; for aesthetics and because it belongs there more than above (though both would be OK)
- Fill curves when bars are hidden
- Move legend to the plot above, so that it appears above curves
> [ENH] Distributions: Add option to hide bars

- README.md
The Discord, build and codecov shields are given a new look. They're larger, higher-contrast, and the chat shield shows a Discord icon and is orange.
Additionally, an Orange image is placed next to the title. I couldn't get it to align nicely, so I used a `kbd` tag and fiddled with the image height.
> README: Better shields, Orange img next to title

- Orange/widgets/data/owrank.py
Fixes #4285.
`np.array` cannot be saved as setting. `selected_rows` is now a list.
> [FIX] Fix saving workflows that contain a Rank widget

- Orange/util.py
Minor, repositions import back next to its explanatory comment.
> util: Move import to its matching comment

- Orange/clustering/hierarchical.py
- Orange/tests/test_clustering_hierarchical.py
- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/visualize/owheatmap.py
Scipy >= 1.0.0 has a compiled optimal_leaf_ordering implementation that can be used instead of the implementation here.
* Use `scipy.cluster.hierarchical.optimal_leaf_ordering` instead of the implementation contained here.
* Remove some scipy <= 0.18 compatibility code.
> [ENH] clustering/hierarchical: Use optimal_leaf_ordering from scipy

- Orange/widgets/unsupervised/owdistances.py
When saving a Distance widget with cosine distance it was restored as Mahalonobis. In https://github.com/biolab/orange3/pull/4280/files settings_version was not increased. 
Increasing the settings version.
> [FIX] Distances: Fix restoring the cosine distance

- Orange/statistics/contingency.py
- Orange/tests/test_contingency.py
- Orange/widgets/visualize/owboxplot.py
@lanzagar and I discussed that there should be also a box for missing values in subgropus for countinuous variables as it is done for discrete. 
When the selected variable is continuous there is now box with missing values if they are present in the subgroup. It shows the distribution of values that are missing in the subgroups variable.
> [ENH] Box Plot: Add box for missing group values

- Orange/widgets/data/tests/test_owrank.py
Setting type should not be` np.ndarray.`
Assign a list to `selected_rows`.
> [FIX] TestOWRank: Setting type should not be np.ndarray

- scripts/macos/sign-dmg.sh
The software that you sign it with must be notarized by Apple in order to run on macOS 10.14.5 or later. [More info.](https://developer.apple.com/developer-id/)
Use **--options=runtime** when signing app bundle. If you don’t enable the hardened runtime, notarization fails!
Add "sanity check" step to ensure a valid code signature. The **strict** flag increases the restrictiveness of the validation to match that required by notarization.
Requirements:
- Have Developer ID cerfiticate in you keychain
- Have xcode installed
- Find *Orange apple ID* and *APP-SPECIFIC-PASSWORD* in our 1Password manager. 
Run:
```
xcrun altool -t osx -f </Path/to/orange.dmg> --primary-bundle-id "si.biolab.orange" --notarize-app --username <Orange apple ID> --password <APP-SPECIFIC-PASSWORD>
```
Output example
``` …
```
> [ENH] Notarization Workflow

- Orange/widgets/tests/base.py
Replaced lines of codes do not wait when widget is calculating (computation performed using ConcurrentWidgetMixin) due to previous changes in tests.
The problematic block of code is replaced with wait_until_finished
> Fix blocking check

- Orange/data/io.py
- Orange/widgets/data/owsave.py
- Orange/widgets/data/tests/test_owsave.py
- Orange/widgets/utils/save/owsavebase.py
- Orange/widgets/utils/save/tests/test_owsavebase.py
Resolves #3701.
The first commit replaces class attribute `filters` of `OWSaveBase` with a class method `get_filters` to allow derived classes to create the list dynamically. Class attribute `filters` still exists and the provided `get_filters` returns it; this is to ensure the backward compatibility. Making `filters` a property instead of creating a method is not a good alternative: `filters` is used in some class methods that cannot be easily changed into ordinary methods (*i.e.* methods of classes that implement platform-specific dialogs). Thus `filter` would have to be a *class property*, but class properties are messy hacks (unless we want to have a meta class for `OWSaveBase`).
The second commit implements `get_methods` for `OWSave`.
> [ENH] Allow add-ons to register file format for the Save widget

- Orange/data/pandas_compat.py
- Orange/data/tests/test_pandas.py
> [FIX] table_to_frame: metas lost on conversion

- Orange/preprocess/preprocess.py
- Orange/tests/test_preprocess.py
- Orange/widgets/data/owpreprocess.py
- Orange/widgets/data/tests/test_owpreprocess.py
I extended Filter sparse features preprocessor with filtering columns by Nan's. We spoke about having 3 options, filter by 0, Nan's or both. I chose not to implement the third option, since the order of operation matters here and the user just use this preprocessor two times and have complete control that way.
> [ENH] Preprocess: Add filtering by missing values

- Orange/widgets/visualize/owsilhouetteplot.py
- Orange/widgets/visualize/tests/test_owsilhouetteplot.py
Silhouette plot does not accept distance matrix on input.
* Accept either table or a distance matrix (with an attached table) on input. If distance matrix is provided the associated 'Distance' GUI controls are disabled.
> [ENH] Silhouette plot: Accept distance matrix on input

- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/unsupervised/tests/test_owhierarchicalclustering.py
Fixes gh-2650
* Prescale the dendrogram geometry to a fixed range to avoid fuzzy comparisons in QPainterPath, ...
> [FIX] owhierarchicalclustering: Prescale dendrogram geometry

- Orange/widgets/data/owtranspose.py
- Orange/widgets/data/tests/test_owtranspose.py
Display input and output data info in status bar.
> [ENH] OWTranspose: data info displayed in status bar

- Orange/widgets/data/owcontinuize.py
- Orange/widgets/data/tests/test_owcontinuize.py
Display input and output data info in the status bar.
> [ENH] OWContinuize: data info displayed in status bar

- Orange/widgets/data/owdiscretize.py
- Orange/widgets/data/tests/test_owdiscretize.py
Display input and output data info in the status bar.
> [ENH] OWDiscretize: data info displayed in status bar

- Orange/widgets/data/owpreprocess.py
- Orange/widgets/data/tests/test_owpreprocess.py
Display input and output data info in the status bar.
> [ENH] OWPreprocess: data info displayed in status bar

- Orange/data/io.py
> [FIX] ExcelReader: Speedup

- conda-recipe/meta.yaml
- requirements-gui.txt
Orange does not work with pyqtgraph 0.11 release candidate.
See #4336
> Fix requirement pyqtgraph==0.10.0

- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/tests/test_owheatmap.py
In gh-2000 'Heatmap' widget lost the ability to cluster larger datasets (>1000).
Restore the ability to cluster without opt. ordering to allow clustering on larger datasets.
> [ENH] Heatmap: Restore ability to cluster larger datasets

- Orange/distance/distance.py
Due to floating point precision,  bhattacharayya distance would sometimes return negative distances.
Rounding numbers to 13th digit. I think this is precise enough for our purposes, otherwise, we could use decimal class instead of floats.
> [FIX] Round bhattacharayya

- README.md
- README.pypi
'https://github.com/biolab/orange' redirects to orange2 repo,
but the link should be explicit to aid readers and avoid
reliance on a uncontrollable github feature.
> README: Make links to orange2 more explicit

- Orange/widgets/unsupervised/owhierarchicalclustering.py
Fix what appears to be a quadratic time bottleneck in `DendrogramWidget.clear`
Alleviates gh-2663
* Remove event filters before removing items
Each `removeItem` seems to be linear in number of installed filters in the whole scene -> so this would be quadratic for us (not accounting any other filters not part of `DendrogramWidget`).
> [FIX] DendrogramWidget: Remove event filters before removing items

- Orange/widgets/utils/concurrent.py
In the new implementation of the ImageEmbedding widget, I have a case when I call `start` from `on_exception`. The case is I call `start` for the first time, then exception happens. in `on_exception` function I change something in the widget and call `start` with new configuration again. It works well.
The problem is that then wait_until_finished does not work correctly since after `on_exception` is called state invalidated is set to `False` (it happens after the start is called again). 
With @VesnaT we decided that it is not good practice to call start while fetching the results or exception. So I changed my implementation in ImageAnalytics to use partial results instead. With this PR I am just adding the assert that prevents user to call `start` from `on_done` or `on_exception`.
> Concurrent: Prevent running new task from on_done, on_exception

- Orange/data/variable.py
- Orange/preprocess/normalize.py
- Orange/tests/test_normalize.py
When copying a variable, number_of_decimals is copied along with other variable properties, causing the normalized integer variable being represented as an integer.
Override `number_of_decimals`, when copying a variable.
> [FIX] Normalize: Integer variable representation

- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
- doc/visual-programming/source/widgets/evaluate/testandscore.md
- requirements-core.txt
> [ENH] Test & Score: Add comparison of models

- Orange/widgets/unsupervised/owtsne.py
- Orange/widgets/unsupervised/tests/test_owtsne.py
Fixes #4354
Changed trigger for Error to number of attributes.
> [FIX] Error message on tSNE with one variable

- Orange/data/table.py
- Orange/tests/test_table.py
Table.from_table was locked to one thread only. This started being problematic now that more widgets are running in threads. If a long `Table.transform` is running in one thread,  another threads will block if they try to use `Table.transform`.
This happened, for example, while testing quasars/orange-spectroscopy#395 (see comment by @stuart-cls).
Table.from_table had a reentrant lock on its conversion cache. That lock was needed so that we knew when to purge the cache. Making the cache thread-local allows concurrent calls.
> [ENH] Allow concurrent transformation of tables into new domains

- Orange/base.py
- Orange/classification/svm.py
- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
- Fixes #4312
- Order of probabilities does not match the list on the left, colors do not match too.
- SVM works wrong when the class attribute has a value that does not appear in Y. In this case, we expect that probabilities shape match to class values, but they don't, since SVM has its own predict function that works differently than other models. 
- Fixing sorting problems from #4312.
- Fixing SVM which now uses the same predict function than other models. 
- Fixing problems with colors (when different orders of probabilities)
- Fix probabilities order when different values order in learners
> Sorting fixes in predictions widget

- Orange/classification/outlier_detection.py
- Orange/classification/svm.py
- Orange/classification/tests/test_outlier_detection.py
- Orange/tests/test_svm.py
- Orange/widgets/data/owoutliers.py
- Orange/widgets/data/tests/test_owoutliers.py
Outlier widget could be used for novelty detection using the Apply Domain widget.
- invoking model's call operator now returns original dataset, appended an Outlier meta variable
- save fitted model into the Outlier variable compute_value
- the data output of Outliers widget can be used as a template data for Apply Domain widget
- fix EllipticEnvelopeClassifier for dataset with missing values
> [ENH] Outliers: Save model into compute_value

- Orange/data/table.py
- Orange/tests/test_table.py
In `Table.from_table` id() of objects are used as cache keys. Because ids can be reused this can be a problem. 
If keys were not tuples we could use WeakKeyDictionary for cache, but here, because they are, I store weakrefs to original objects as values. The cached value is not used if the objects these weakrefs are pointing to do not exists anymore.
> [FIX] Table.from_table: fix caching with reused ids 

- Orange/data/__init__.py
- Orange/data/io.py
- Orange/data/io_base.py
- Orange/tests/test_io.py
Data saved in pickle format in python 3.8 was not readable on older versions of python.
Define a new constant `PICKLE_PROTOCOL` and fix it to a specific version (4, as was used now on py3.6 & py3.7). Use it instead of pickle.HIGHEST_PROTOCOL, which became 5 in py3.8.
Disclaimer: I also removed `from .io_base import *` in `data/__init__.py` as we don't need to make the base classes publicly visible in a top level module. `Orange.data` even had `Flags` imported twice into its namespace, since it was provided by `io_base` and later overwritten by `from .io import *`
> [FIX] Explicitly define the protocol version for pickling

- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/utils/graphicstextlist.py
- Orange/widgets/utils/tests/test_graphicstextlist.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/owsilhouetteplot.py
owheatmap, owdistancemap and owhierarchicalclustering use QGraphicsLinearLayout to position text labels in a list. Clearing the QGraphicsLinearLayout however is slow (seems to be another quadratic time complexity).
Extract a more limited (but sufficient) TextListWidget from owsilhouetteplot and replace the use of QGraphicsLinearLayout.
Fixes gh-2663
Fixes gh-4349
* extract and extend the TextListWidget from owsilhouetteplot
* use the TextListWidget in owheatmap, owhierarchiclustering, owdistancemap
> [FIX] Fix slow clear/delete in 'Heat Map' 'Hier. Clustering', 'Distance Map'

- Orange/widgets/visualize/tests/test_owprojectionwidget.py
- Orange/widgets/visualize/utils/widget.py
> [FIX] DataProjectionWidget: attribute Selected

- Orange/widgets/data/owtranspose.py
Fixes #4359.  A warning added if the input data contains categorical features.
> OWTranspose: Warning when transposing categorical features

- Orange/widgets/visualize/tests/test_owprojectionwidget.py
- Orange/widgets/visualize/utils/widget.py
> [FIX] DataProjectionWidget: Update combos on new data

- Orange/classification/rules.py
- doc/data-mining-library/source/index.rst
- doc/data-mining-library/source/reference/outliers.rst
Fixes small warnings that occurred during doc build.
Clean up documentation.
3 warnings could not be resolved, but this is because they originate from sklearn (in my expert opinion).
> [DOC] Fix warnings at doc build

- .coveragerc
- Orange/widgets/data/owpythonscript.py
- Orange/widgets/data/tests/test_owpythonscript.py
Ref: https://github.com/biolab/orange-widget-base/pull/35
* Save script list in plain dict
* Some code cleanup
> [FIX] Python script serialization state

- Orange/widgets/visualize/owheatmap.py
Ref gh-4380
* Improve size hinting
* Move 'Split by' labels/titles (when in effect) to the left of the heatmaps/dendrogram.
* Decrease spacing between consecutive heatmap parts when split
* Fix an error in 'resetting' fixed row size constraints which could cause QGraphicsGridLayout to enter an endless loop.
> [ENH] Heatmap: Tighter layout

- Orange/widgets/data/owcontinuize.py
- Orange/widgets/data/tests/test_owcontinuize.py
Fixes #4378
Disable `Normalize by span` and `Normalize by standard deviation` radio buttons for sparse datasets.
> [FIX] Continuize: Disable normalizing sparse data

- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
The drop-down list for choosing color of histograms was very narrow so feature names were not seen properly.
Display input and output data info in the status bar.
Made Color drop-down list wider.
> [ENH] OWFeatureStatistics: data info displayed in the status bar

- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
Fixes #4373.
This PR contains two different solutions: one is limited to missing variables (the problem in #4373), the other also catches other exceptions. I think we should do the latter.
Feature constructor assumes that all variables exist. If they don't, it shows an error -- but only for transformations that occur inside the widget, that is, on the input data. If the transformation is applied in another widget on some other data, it may crash.
#4373 can be reproduced with the following workflow, where Feature constructor transfroms the target variable, e.g. computes `log(MEDV)` for housing data:
Prediction constructs a class-less domain. The model transforms the data into it's training domain. The target in that domain tries to compute `log(MEDV)`, but Predictions removed MEDV, so …
> [FIX] Feature Constructor: Catch exceptions

- Orange/widgets/utils/state_summary.py
- Orange/widgets/utils/tests/test_state_summary.py
Replace 'features' with 'variables' in the formatted string.
> [FIX] format_summary_details: Replace 'features' with 'variables'

- Orange/widgets/visualize/owsilhouetteplot.py
- Orange/widgets/visualize/tests/test_owsilhouetteplot.py
Fixes #4403
Remove checkbox and always add silhouette scores to the output
> [ENH] Silhouette Plot: Always output scores

- Orange/data/io_base.py
- Orange/data/tests/test_io_base.py
- Orange/data/tests/test_util.py
- Orange/data/util.py
- Orange/tests/test_tab_reader.py
Fixes #4381 
File readers constructing a data table now rely on `get_unique_names_duplicates` from `data.util` instead of using their own similar logic.
Fixed `get_unique_names_duplicates` for cases where appending an index collides with an exiting name (`['x', 'x', 'x (2)']` now returns `['x (1)', 'x (3)', 'x (2)']`.
> [FIX] File: Construct unique column names.

- Orange/projection/manifold.py
Fixes #3523. 
#3883 crashed travis for unknown reasons. This fix is implemented a bit differently and replaces the lazy object with actual module once it is loaded.
It survived three runs of tests. If we're worried about random crashes, we can restart a few more times.
> [ENH] Import openTSNE lazily for faster loading of Orange

- Orange/widgets/evaluate/owpredictions.py
Fixes #4430.
Fails (and will continue to fail) at coverage.
Update splitter on resize event.
> [ENH] Predictions: Update splitter on resize

- Orange/preprocess/remove.py
- Orange/tests/test_remove.py
- Orange/widgets/data/tests/test_owselectrows.py
Fixes #4416.
When removing `Variable.make`, I assumed that we no longer needed `Lookup` in `remove_unused_values` because values are mapped anyway. This doesn't work when the variable that is being purged has `compute_value` defined, for instance if the variable is a discretized version of some numeric variable.
Re-add lookup.
Although the bug was in remover, I also kept the test in `test_owselectrows`, where we detected the problem.
> [FIX] Fix missing values after purging unused values

- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/evaluate/tests/test_owtestlearners.py
- Orange/widgets/gui.py
- Orange/widgets/tests/test_gui.py
- Orange/widgets/utils/plot/owplotgui.py
- Orange/widgets/utils/plot/owplotgui_obsolete.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owsieve.py
- doc/development/source/gui.rst
https://github.com/biolab/orange-widget-base/pull/21 eliminates `valueType` argument from `comboBox`. This PR removes the argument from calls.
https://github.com/biolab/orange-widget-base/pull/21 also implements full comboBox function in orange-widget-base, so the function no longer needs to be reimplemented in this repo.
This slightly modifies behaviour of combo boxes: previously, a box could have assigned a model, but use ints as settings. This was invalid and no longer works. Only one core widget did this, and the error should be easily detected by tests, probably already at widget's initialization.
> gui: Remove comboBox, use the one from orange-widget-base

- Orange/widgets/tests/base.py
- Orange/widgets/visualize/owvenndiagram.py
- Orange/widgets/visualize/tests/test_owvenndiagram.py
Fixes  #3989
Refactored venn over rows.
TODO:
> [FIX] Venn Diagram is slow for big datasets

- Orange/data/tests/test_util.py
- Orange/data/util.py
Widgets that construct new domains (see #4382) may need this function to prepare unique names.
> Add function data.util.get_unique_names_domain

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Fixes #4395 
The labels can be changed according to [`strftime`](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior) if anybody finds a better formating. It still doesn't look particularly nice when displaying days and hours. I also tried using binning `short_labels` but they didn't seem that nice.
The `timezone.utc` is used becous of a Python datetime [bug](https://bugs.python.org/issue31212).
> [RFC][ENH] OWScatterPlot: axis displays time specific labels for time variable

- Orange/widgets/data/owtranspose.py
- Orange/widgets/data/tests/test_owtranspose.py
> [ENH] OWTranspose: Data info displayed in the status bar

- Orange/data/domain.py
- Orange/data/table.py
- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/tests/sql/test_sql_table.py
- Orange/tests/test_domain.py
- benchmark/bench_domain.py
The first part of fix for #4406.
Two domains are considered equal if variables are equal. However, equality of discrete variables does not check for `values`.
Eliminate caching of domain conversions.
> Remove domain transformation cache

- Orange/base.py
- Orange/classification/outlier_detection.py
- Orange/classification/tests/test_outlier_detection.py
- Orange/data/tests/test_util.py
- Orange/data/util.py
- Orange/modelling/base.py
- Orange/tests/test_base.py
- Orange/tests/test_util.py
- Orange/util.py
- Orange/widgets/data/owoutliers.py
- Orange/widgets/data/tests/test_owoutliers.py
Responsive Outliers widget: the widget could make calculations in a separate thread to make Orange responsive.
- Create a `progress_callback` function that serves as a wrapper function for callbacks. It allocates the corresponding proportion of the progress to the callback.
- Add callback to `Learner` to enable preprocessing interruption.
- Add callback to `_OutlierModel`.
- Do work in a separate thread.
- Still impossible to terminate the fit/predict operations.
> [ENH] Outliers: Offload work onto separate thread

- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/owdatainfo.py
- Orange/widgets/data/owneighbors.py
- Orange/widgets/data/owpurgedomain.py
- Orange/widgets/model/owlinearregression.py
- Orange/widgets/model/owrules.py
- Orange/widgets/model/owsgd.py
- Orange/widgets/unsupervised/owdistances.py
- Orange/widgets/unsupervised/owlouvainclustering.py
Fixes #4410.
Remove explicit `SetFixedSize` calls, replace them with `resizing_enabled`.
Add `resizing_enabled=False` where appropriate.
Remove redundant parameters where they are already inherited from BaseLearner.
Small fix to run __main__ in PurgeDomain.
> Widgets: unify with resizing_enabled

- Orange/data/table.py
- Orange/data/util.py
- Orange/tests/test_table.py
- benchmark/bench_transform.py
Fixes https://github.com/biolab/orange3/issues/3923
Speedup from_table - tested on random data (10000, 3000):
- on dense data: 6s -> 4s
- on sparse data: 350s -> 1.3s
> from_table: speedup for sparse and dense data

- conda-recipe/meta.yaml
- requirements-gui.txt
> Require orange-widget-base==4.4.0

- .coveragerc
Some test folders are inflating code coverage. Should we consider dropping them from coverage report?
> Omit all test folders from .coveragerc

- Orange/widgets/unsupervised/owhierarchicalclustering.py
Fixes gh-4449
Set the scene's sceneRect, not just the view's. The scene's sceneRect is used when exporting the image.
> [FIX] owhierclustering: Update the scene's sceneRect

- Orange/widgets/data/owrank.py
- Orange/widgets/data/tests/test_owrank.py
Fixes #4437
When no class variable random forest fails with TypeError since it cannot decides either on classifier or regressor. It is now caught in the widget.
> [FIX] Rank: Fix error with Random forest

- Orange/widgets/gui.py
Removing ValueCallback from imports in gui (PR #4158) broke Spectroscopy.
Changing imports, to me, seems the same as renaming a function without deprecation period. I therefore brought it back.
> gui: add accidentally removed ValueCallback

- Orange/widgets/unsupervised/owcorrespondence.py
- Orange/widgets/utils/itemmodels.py
Sometimes, widgets require selecting multiple variables and saving them as a selection. Currently, we need this in Timeseries. I propose moving `select_rows()` function to utils.itemmodels, just under `select_row()`. This would make reusing the function in the add-ons much easier.
Move `select_rows()` from `OWCorrespondence` to `Orange.widgets.utils.itemmodels`.
> Move select_rows function to utils

- Orange/data/tests/test_util.py
- Orange/data/util.py
- Orange/widgets/data/owfile.py
- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/utils/domaineditor.py
- Orange/widgets/utils/tests/test_domaineditor.py
Fixes part of  #4382
File widget allowed renaming vars with no regards for possible duplicates it may create.
As in other widgets, duplicates are checked by get_unique_name_duplicates and a warning is shown.
> [FIX] Ensure unique var names in file

- Orange/data/variable.py
- Orange/widgets/data/owconcatenate.py
- Orange/widgets/data/tests/test_owconcatenate.py
Fixes #4406. Also fixes part of #4382.
The problem was that when merging domains, attributes from the first domain are used and other attributes values' that don't appear in the first table are turned into nan's.
This fix applies only when "primary table" is not present. When it is present, #4422 suffices.
When filtering for unique attributes, two (or more) attributes with different values are replaced by a new attribute.
> [FIX] Concatenate: Fix wrong merging of categorical features

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
> [ENH] OWEditDomain: Data info displayed in the status bar

- Orange/widgets/data/owcorrelations.py
- Orange/widgets/data/tests/test_owcorrelations.py
> [ENH] OWCorrelations: Data info displayed in the status bar
