biolab/orange3

Orange/widgets/data/owpythonscript.py

Fixes gh-3035, gh-2140
Add `flush` method for faked std(out|err)

owpythonscript: Add flush method for faked std(out|err)

---

doc/development/source/orange-demo/orangedemo/OWLearningCurveC.py
doc/development/source/tutorial-responsive-gui.rst

Reformatting of responsive GUI part of the widget tutorial.

[DOC] Responsive GUI documentation improvements

---

Orange/widgets/tests/workflows/3_14_0_distance_matrix.ows
Orange/widgets/unsupervised/owdistancematrix.py

Fixes #3082. 
Renamed output of Distance Matrix to match other widgets supporting selection.

Renamed output to Distance Matrix

---

Orange/data/util.py
Orange/data/variable.py
doc/data-mining-library/source/reference/data.variable.rst

I had to explain compute_value too many times.
Rewrote documentation, added a simple use case.

compute_value documentation

---

doc/data-mining-library/source/tutorial/data.rst

Spelling error "continous" changed to "continuous"

Spelling error "continous" changed to "continuous"

---

doc/visual-programming/source/widgets/visualize/boxplot.rst

Fixes #3065. 
Documentation now properly explains visualization.

Fixed doc for Box Plot

---

doc/visual-programming/source/widgets/evaluation/testandscore.rst

The documentation was not clear about scores computing in case of more classes. 
There were also wrong info in the documentation.
https://github.com/biolab/orange3/issues/3098
Fixed and extended description for target classes in the test&score's documentation.

[DOC] Test & Score: Fixed and extended description for target classes

---

Orange/widgets/utils/tests/test_webview.py

The test often randomly timeouts on travis.
Skip it

tests: Disable randomly timeouting test

---

Orange/widgets/data/owpreprocess.py

Fixes:
https://github.com/biolab/orange3-single-cell/issues/243
Make the widget inheritable for single-cell add-on purposes.

OWPreprocess: Make widget inheritable

---

Orange/canvas/document/suggestions.py

widget-use-frequency.p -> widget-use-frequency.pickle

Pickle Filename Correction

---

appveyor.yml

Add Python 3.7 to the CI tests
Add Python 3.7 to the CI tests

[MNT] appveyor: Add Python 3.7 to the test matrix, remove Python 3.4

---

doc/visual-programming/source/widgets/data/file.rst
doc/visual-programming/source/widgets/data/preprocess.rst
doc/visual-programming/source/widgets/data/pythonscript.rst
doc/visual-programming/source/widgets/data/rank.rst
doc/visual-programming/source/widgets/data/selectcolumns.rst
doc/visual-programming/source/widgets/evaluation/calibrationplot.rst
doc/visual-programming/source/widgets/model/linearregression.rst
doc/visual-programming/source/widgets/model/loadmodel.rst
doc/visual-programming/source/widgets/model/randomforest.rst
doc/visual-programming/source/widgets/unsupervised/PCA.rst
doc/visual-programming/source/widgets/unsupervised/distancetransformation.rst
doc/visual-programming/source/widgets/unsupervised/louvainclustering.rst
doc/visual-programming/source/widgets/unsupervised/manifoldlearning.rst
doc/visual-programming/source/widgets/unsupervised/mds.rst
doc/visual-programming/source/widgets/visualize/cn2ruleviewer.rst
doc/visual-programming/source/widgets/visualize/distributions.rst
doc/visual-programming/source/widgets/visualize/pythagoreanforest.rst
doc/visual-programming/source/widgets/visualize/silhouetteplot.rst
doc/visual-programming/source/widgets/visualize/treeviewer.rst

This PR does not address a particular issue, just miscellaneous typos in documentation.
Thank you for this great project! I'm getting familiar with the codebase, so I read through the documentation tonight. Please consider this PR to address minor misspellings I found in the docs.

fixed typos in documentation

---

doc/visual-programming/source/widgets/data/sqltable.rst

Fix wording in the last sql documentation PR (#3196)

SQL Table documentation fix

---

Orange/widgets/visualize/owscatterplot.py

Certain visualization widgets open with wrong initial size.
Introduce sizeHint that follows 16:9 ratio.

Introduce sizeHints for Scatter Plot

---

Orange/projection/radviz.py
Orange/widgets/report/tests/test_report.py
Orange/widgets/tests/base.py
Orange/widgets/unsupervised/owmds.py
Orange/widgets/unsupervised/tests/test_owmds.py
Orange/widgets/utils/plot/owplotgui.py
Orange/widgets/visualize/owfreeviz.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owradviz.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owscatterplotgraph.py
Orange/widgets/visualize/tests/test_owfreeviz.py
Orange/widgets/visualize/tests/test_owlinearprojection.py
Orange/widgets/visualize/tests/test_owprojectionwidget.py
Orange/widgets/visualize/tests/test_owradviz.py
Orange/widgets/visualize/tests/test_owscatterplot.py
Orange/widgets/visualize/tests/test_owscatterplotbase.py
Orange/widgets/visualize/utils/component.py
Orange/widgets/visualize/utils/plotutils.py
Orange/widgets/visualize/utils/widget.py

OWProjectionWidget: Introduce new parent for projection widget

---

Orange/statistics/util.py
Orange/tests/test_statistics.py

statistics util: Add function for standard deviation

---

Orange/widgets/tests/base.py
Orange/widgets/unsupervised/tests/test_owmds.py
Orange/widgets/utils/plot/owplotgui.py
Orange/widgets/visualize/utils/widget.py
doc/visual-programming/source/widgets/visualize/scatterplot.rst

[ENH] projections: Remove sizing by overlap

---

doc/visual-programming/source/widgets/unsupervised/kmeansclustering.rst

People on the course asked what it does and I could not answer them. I then showed them the magic F1 key - but it did not help. :)

K-means documentation: explain the number of reruns better

---

Orange/widgets/data/owfeaturestatistics.py
Orange/widgets/data/tests/test_owfeaturestatistics.py

Outputs were not being properly updated when data was cleared or when new data on input.
Outputs now behave properly.

[FIX] Feature Statistics: Update outputs on new data

---

doc/visual-programming/source/index.rst
doc/visual-programming/source/widgets/data/transform.rst

Transform: Basic documentation

---

Orange/projection/manifold.py
Orange/widgets/unsupervised/owtsne.py

Make the tSNE projection replicable.
Always use the same random seed in OWtSNE.

TSNE: Set fixed random seed

---

Orange/widgets/data/owfile.py
Orange/widgets/data/tests/test_owfile.py

[Fix] Missing url error

---

Orange/base.py
Orange/data/util.py
Orange/preprocess/preprocess.py
Orange/projection/__init__.py
Orange/projection/base.py
Orange/projection/freeviz.py
Orange/projection/lda.py
Orange/projection/pca.py
Orange/projection/radviz.py
Orange/tests/test_freeviz.py
Orange/tests/test_lda.py
Orange/tests/test_preprocess.py
Orange/tests/test_radviz.py
Orange/widgets/data/owpreprocess.py
Orange/widgets/tests/base.py
Orange/widgets/utils/annotated_data.py
Orange/widgets/utils/tests/test_annotated_data.py
Orange/widgets/visualize/owfreeviz.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owradviz.py
Orange/widgets/visualize/tests/test_owfreeviz.py
Orange/widgets/visualize/tests/test_owlinearprojection.py
Orange/widgets/visualize/tests/test_owradviz.py
Orange/widgets/visualize/utils/widget.py

Implements second part of #3342
Add Preprocessor output to OWFreeviz, OWRadviz and OWLinearProjection.
For this purpose Projector(s) and Projection(s) are implemented for belonging widget.
To ensure consistency among projections, "Projection" input is removed from OWLinearProjection.

Projections: Output Preprocessor

---

Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/unsupervised/tests/test_owhierarchicalclustering.py

Hierarchical clustering: Always output (annotated) Data

---

Orange/widgets/unsupervised/owtsne.py

t-SNE has no keyword, it is not easy to find it with quick search.
Add "tsne" keyword to quick search.

Add keyword to tSNE

---

Orange/classification/rules.py
Orange/tests/test_rules.py
Orange/widgets/model/tests/test_owrulesclassification.py

Sometimes the default rule would not classify to majority class.
When no more rules are found, the default rule classifies to majority class.

[WIP] OWRules: fix default rule

---

Orange/widgets/settings.py

settings: Continue workflow after error in setting migration

---

Orange/widgets/unsupervised/owtsne.py
Orange/widgets/unsupervised/tests/test_owtsne.py

The embedding in OWtSNE was replotted if any attribute changed.
Retain embedding if only meta attributes change.

tSNE: Retain embedding if metas change

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/tests/test_owmosaic.py

[FIX] Mosaic: Always reset discrete_data

---

Orange/preprocess/fss.py
Orange/preprocess/preprocess.py
Orange/preprocess/score.py
Orange/tests/test_fss.py
Orange/tests/test_preprocess.py

[FIX] RemoveNaNColumns: Move to preprocess

---

Orange/widgets/tests/base.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/tests/test_owscatterplot.py
Orange/widgets/visualize/utils/widget.py

Scatterplot: Refactor and enhancement

---

Orange/widgets/visualize/tests/test_owscatterplot.py
Orange/widgets/visualize/utils/widget.py

[FIX] OWDataProjectionWidget: Fix applying selection

---

Orange/widgets/visualize/owboxplot.py
Orange/widgets/visualize/owdistributions.py
Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/ownomogram.py
Orange/widgets/visualize/owpythagorastree.py
Orange/widgets/visualize/owpythagoreanforest.py
Orange/widgets/visualize/owruleviewer.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/owsilhouetteplot.py
Orange/widgets/visualize/owtreeviewer.py
Orange/widgets/visualize/owtreeviewer2d.py
Orange/widgets/visualize/owvenndiagram.py
Orange/widgets/visualize/tests/test_owdistributions.py
Orange/widgets/visualize/tests/test_owmosaic.py
Orange/widgets/visualize/tests/test_owpythagoreanforest.py
Orange/widgets/visualize/tests/test_owruleviewer.py
Orange/widgets/visualize/tests/test_owscatterplot.py
Orange/widgets/visualize/tests/test_owsilhouetteplot.py
Orange/widgets/visualize/tests/test_owvenndiagram.py

This PR fixes 90 issues that required some superficial changes.
Remaining 25 issues are about too many attributes, ancestors, branches or lines, or about accessing protected members. Fixing them requires deeper refactoring.

[MNT] Fix pylint issues in visualization widgets and tests

---

Orange/projection/manifold.py
Orange/tests/test_manifold.py
Orange/widgets/tests/base.py
Orange/widgets/unsupervised/owtsne.py
Orange/widgets/unsupervised/tests/test_owtsne.py

t-SNE: Updates 

---

Orange/widgets/visualize/owboxplot.py
Orange/widgets/visualize/tests/test_owboxplot.py

Box Plot wasn't showing view if all data in metas, but some were primitive.
Box Plot shows primitive metas.

Box Plot shows primitive metas

---

Orange/canvas/__main__.py

Since macOS Sierra the 'View' menu bar has a automatic 'Show Tab Bar' entry that causes tab bar to be displayed on all widgets, whether sensible or not.
Fixes gh-2672
Disable macOS native window tabbing on startup

canvas/main: Disable macOS native window tabbing on startup

---

Orange/widgets/report/owreport.py

Fixes #3331.
Portions of report can be copied to clipboard.

Report: Add copy to clipboard

---

Orange/datasets/bupa.tab
Orange/datasets/datasets.info

Fixes #3544.
Remove the class label.

[FIX] Documentation: Remove class from 'bupa'

---

doc/visual-programming/source/widgets/visualize/scatterplot.md

Scatter plot's documentation did not sufficiently explain how feature pairs are scored.
Explain two scoring methods.

[DOC] Add VizRank info to Scatter Plot

---

requirements-doc.txt

PyQt unnecessarily in requirements for documentation.
Remove PyQt5 from requirements.

Remove PyQt from documentation requirements

---

Orange/preprocess/normalize.py
Orange/widgets/data/owpreprocess.py
Orange/widgets/data/tests/test_owpreprocess.py

Fixes #2739 
Added radio buttons and options to normalize by span to [0,1] and [-1,1].

Preprocess: changed normalization features

---

Orange/widgets/data/owpythonscript.py
doc/visual-programming/source/widgets/data/pythonscript.md

Added a shortcut that runs the script.

OWPythonScript: run shortcut (Ctrl/Cmd + R)

---

Orange/widgets/data/owdiscretize.py

... except for `len-as-condition` caused by `if self.data is not None and len(self.data)`. See #3637.

OWDiscretize: PyLint

---

Orange/widgets/data/owpurgedomain.py

A trivial remove of a shadowed variable `data`.

OWPurgeDomain: PyLint

---

Orange/widgets/data/owcorrelations.py
Orange/widgets/data/tests/test_owcorrelations.py

Calculating (pearson/spearman) correlation coefficients on constant data returns nan. 
Therefore constant columns should not be included in the calculation.
Remove all constant columns before calculating correlation coefficients.

Correlations: Remove constant features

---

Orange/widgets/data/owpaintdata.py

Pylint reported a lot of irrelevant issues for Paint Data, so this PR is mostly about disabling them.

OWPaintData: PyLint

---

Orange/widgets/data/owoutliers.py

This one was interesting. Pylint complained that `OWOutliers` defines attribute `new_data` outside the constructor. This one was interesting: `add_metas` constructed a new table and "returned" it by storing it into the class instance. Method `_get_outliers` then assumed `new_data` exists, because it called `detect_outliers` which in turn called `add_metas`. (I suppose, however, that this contrived schema remained from the past when the widget may have been organized differently.)
Now, `add_metas` returns the table by returning it, and `detect_outliers` passes it on to `_get_outliers`.

OWOutliers: PyLint

---

Orange/widgets/data/owcontinuize.py

... except for `len-as-condition` caused by `if self.data is not None and len(self.data)`. We need to decide to define `Table.is_empty` or `Table.__bool__`. I vote for `Table.is_empty` because it's more explicit. We could also have `.size` like numpy arrays, but it is not clear whether this would include meta attributes or not.

OWContinuize: PyLint

---

Orange/widgets/data/owimpute.py

This PR is non-trivial (compared to others in the series) because it splits a method with too many branches into several parts.

OWImpute: PyLint

---

Orange/widgets/data/owdatasets.py

OWDatasets: PyLint

---

Orange/preprocess/remove.py

I think the `>` should be `<`
Disclaimer: If I saw this PR, I would complain that the bug is not described, there are no instructions on how to reproduce it, no tests, no nothing :) All of that is true, but instead of that I offer a new issue instead: #3690

remove: Fix inequality

---

Orange/widgets/data/owdatasets.py

Implements #3126.
Double clicks now triggers unconditional commit.

OWDatasets: Add unconditional commit on double click

---

Orange/widgets/gui.py
Orange/widgets/model/owsgd.py
Orange/widgets/tests/base.py
Orange/widgets/unsupervised/owmds.py
Orange/widgets/unsupervised/owtsne.py
Orange/widgets/visualize/owboxplot.py
Orange/widgets/visualize/owfreeviz.py
Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owradviz.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/widget.py

Eventually attempts to fix #3058.

Scrollable control areas of widgets

---

Orange/widgets/data/tests/test_owcolor.py
Orange/widgets/data/tests/test_owcorrelations.py
Orange/widgets/data/tests/test_owcreateclass.py
Orange/widgets/data/tests/test_owfeatureconstructor.py
Orange/widgets/data/tests/test_owfile.py
Orange/widgets/data/tests/test_owimpute.py
Orange/widgets/data/tests/test_owneighbors.py
Orange/widgets/data/tests/test_owoutliers.py
Orange/widgets/data/tests/test_owpythonscript.py
Orange/widgets/data/tests/test_owrank.py
Orange/widgets/data/tests/test_owsave.py
Orange/widgets/data/tests/test_owselectcolumns.py
Orange/widgets/data/tests/test_owselectrows.py
Orange/widgets/data/tests/test_owsql.py
Orange/widgets/data/tests/test_owtable.py

Fix issues in tests for widget in category Data. Mostly silencing.

Data widgets tests: pylint

---

Orange/widgets/data/owtable.py

OWTable: pylint

---

Orange/widgets/data/owfile.py
Orange/widgets/data/owmergedata.py
Orange/widgets/data/owneighbors.py
Orange/widgets/data/owpaintdata.py
Orange/widgets/data/owsave.py
Orange/widgets/data/owselectbydataindex.py
Orange/widgets/data/owtranspose.py

Trivial pylint issues that remained in some widgets that were already mostly cleaned.

Data widgets: PyLint

---

Orange/widgets/data/owrank.py

Fixes pylint issues in OWRank.

OWRank: pylint

---

Orange/widgets/data/owselectcolumns.py

OWSelectColumns: pylint

---

Orange/widgets/data/owsql.py

OWSQL: PyLint

---

doc/development/source/tutorial.rst

Copying widgets and running them now works.
The code from the widget tutorial did not work if you copied it.
Added imports and colons.

widget development doc: fix code in Getting started

---

Orange/data/tests/test_variable.py
Orange/data/variable.py

Fixes (the first part of) #3745
Show values in scientific format, if number of decimals exceeds 5.

ContinuousVariable: Show values in scientific format

---

Orange/canvas/help/manager.py

Fixes gh-3752
Fix an NameError in exception handler

[FIX] canvas/help: Fix a NameError in exception handler

---

doc/visual-programming/source/loading-your-data/index.md

Only Loading your data was still written in .rst.
Rewrite Loading your data to markdown.

Convert Loading your data to markdown

---

Orange/data/variable.py

ContinuousVariable: Always set _format_str when changing number_of_decimals

---

Orange/widgets/data/owrank.py
Orange/widgets/data/tests/test_owrank.py

Fixes #3758
Selection is a Numpy array which throws an error when converted to bool in the condition of `if` clause. 
Condition changed such that it checks whether a variable is not None.

OWRank: Fix crash when rows selected

---

Orange/widgets/visualize/ownomogram.py
Orange/widgets/visualize/tests/test_ownomogram.py

OWNomogram: Add feature list as output

---

Orange/widgets/data/owtransform.py
Orange/widgets/data/tests/test_owtransform.py

Apply domain: Remove 'Retain all data' option

---

Orange/tests/test_table.py

Tests fail to remove metadata files.
Remove also metadata files, along with saved files.

Tests: Remove also saved metadata

---

Orange/tests/test_io.py

Tests on master have two additional prints. I did not check that code thoroughly before merging it yesterday...

Remove two print statements from test_io

---

Orange/widgets/evaluate/tests/test_owrocanalysis.py

I ran tests after installation of a win conda package and I found a test using QToolTip.isVisible() failing.

Fix tooltip test that failed in installed win conda package

---

Orange/tests/test_datasets.py

One print() is in a test since March.

remove print in tests

---

.travis.yml
.travis/install_orange.sh

For the tests to work I also needed to install pyqtwebengine.

Test with PyQt5=5.12 on Linux (travis)

---

Orange/widgets/evaluate/owliftcurve.py

A trivial work-around for two pylint issues.

OWLiftCurve: Pylint

---

Orange/widgets/evaluate/owconfusionmatrix.py

The almost-non-trivial part is reduction of number of branches in `set_results`.

OWConfusionMatrix: Pylint

---

Orange/preprocess/discretize.py
Orange/tests/test_discretize.py
Orange/widgets/visualize/tests/test_owdistributions.py

OWDistributions: Fix crash on binning sparse data

---

Orange/widgets/data/owmergedata.py
Orange/widgets/data/tests/test_owmergedata.py

OWMergeData: Warn if any variables are non-unique and hidden

---

Orange/widgets/evaluate/owrocanalysis.py
Orange/widgets/evaluate/tests/test_owrocanalysis.py

Fixes pylint issues in the ROC Analysis widget.

OWRocAnalysis: Pylint

---

Orange/widgets/unsupervised/owhierarchicalclustering.py

OWHierarchicalClustering: Add labels to dendrogram

---

Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/tests/test_owheatmap.py

Closes #3884 
The change is not that big. For the shortest possible interval between high and low settings (5%) the old code still used 14 different colors. Now, up to 255 can be used, but only if the data has that many different values in the range that is set.
Before this change low and high thresholds cut the color palette. Thus, less colors were used for drawing. Now thresholds only change how the full palette is applied. Therefore, dynamic range improved.

owheatmap: greater dynamic range for colors

---

conda-recipe/meta.yaml

Add pandas to conda package requirements

---

Orange/widgets/model/owsvm.py
Orange/widgets/unsupervised/owmanifoldlearning.py
Orange/widgets/unsupervised/owpca.py
Orange/widgets/visualize/owpythagoreanforest.py

Words in signal names are capitalized. Four signals don't conform.
Capitalized some words.

Capitalization of signals

---

Orange/widgets/data/owrank.py

Rank widget: Allow up to 999 features

---

Orange/widgets/data/owdatasampler.py
Orange/widgets/model/owlogisticregression.py

Partially solves #3103. See comments there

Fix random seed in Logistic regression; make Data Sampler replicable by default

---

CONTRIBUTING.md

Add instructions for setting up development environment.

Development installation

---

Orange/evaluation/testing.py
Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/evaluate/tests/test_owtestlearners.py
Orange/widgets/evaluate/utils.py

Fixes #3784
Adds train and test times to owtestlearners

Add test and train times to owtestlearners

---

Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/tests/test_owheatmap.py

[FIX] Heat map: Cannot cluster a single instance

---

Orange/widgets/tests/base.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/tests/test_owscatterplot.py

[FIX] Scatter plot: Hidden variables fix

---

conda-recipe/meta.yaml

#3933 introduced a new dependency

Add pyyaml to conda recipe

---

Orange/widgets/data/owdatasets.py

Widget and title column are too narrow.
Changed the widget size hint and title column size

OWDatasets: change size hint and resize columns

---

Orange/widgets/model/owneuralnetwork.py

Fixes #3924.
Increase max spin value to 1000000.

OWNeuralNetwork: increase max interations

---

scripts/create_widget_catalog.py

The script was broken since gh-3772
Use correct configuration namespace.
Also fix exported icon backgrounds.

[FIX] Fix scripts/create_widget_catalog.py script

---

Orange/widgets/unsupervised/owpca.py

PCA widget uses randomized PCA, which is, well, randomized.
random_state = 0

Replicable PCA widget

---

Orange/statistics/util.py
Orange/tests/test_statistics.py

One of the common checks that widgets do is to check if there are nans in the data and handle them in some way. `np.isnan` is commonly used, and it doesn't support sparse.
Add dense/sparse compatible functions to cover some common cases for dealing with nans. These will be used in the single-cell addon, where these functions are needed.

Statistics.util: add nan_to_num, isnan and any_nan

---

Orange/widgets/visualize/owboxplot.py
Orange/widgets/visualize/tests/test_owboxplot.py

Fixes #3971.
@ajdapretnar, please do some clicking. It seems to work and it should pass the test, but this widget code is rather contrived, so I wasn't too comfortable changing it.

Boxplot: Show chi2 statistics

---

setup.py

https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata

(hopefully) fix PyPI to handle readme as markdown

---

doc/visual-programming/source/widgets/data/file.md

File widget did not explain how to load other data formats.
Explain which widgets support which formats.

File documentation: explain additional formats

---

Orange/widgets/data/owfile.py

File Widget: Add tips about other widgets for loading data

---

doc/visual-programming/source/index.rst
doc/visual-programming/source/widgets/unsupervised/kmeans.md

Docs: add SOM to index
Docs: match k-Means title with widget name

Docs: small fixes

---

doc/visual-programming/source/widgets/data/preprocess.md

One image from the documentation did not work on case sensitive filesystems.

Docs: fix case for image

---

Orange/widgets/unsupervised/owhierarchicalclustering.py

Most widgets (see e.g. scatterplot and cousins) put the variables like "Group" and "Selected" among meta variables and use sensible default names. Hierarchical clustering allows the user set the role of the attribute and its name (that can either cause duplicate names).
- This PR "standardizes" the widget to behave like others,
- and makes it nicer,
- and prevents duplicate variable names.

OWHierarchicalCluster: Remove output options

---

.travis/build_doc.sh
doc/widgets.json

Travis complains if doc/widgets.json is not up to date

---

Orange/widgets/evaluate/owtestlearners.py

[FIX] OWTestLearners: Vertically align to center

---

Orange/widgets/evaluate/owpredictions.py

Get rid of all them checkboxes!
Still missing: a decent way to sort by different probabilities.

[RFC] Cleanse the Predictions widget GUI

---

Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/tests/test_owsieve.py

[FIX] Sieve: Disable vizrank when features on input

---

README.md

New Discord server
Update Discord README badge

README: Update Discord badge

---

Orange/widgets/data/owfile.py

Fixes #4107 following @ales-erjavec's suggestion in #4113.

File: Limit the width of URL line edit

---

Orange/projection/som.py
Orange/widgets/unsupervised/owsom.py
Orange/widgets/unsupervised/tests/test_owsom.py

Fixes #4126. 
Check if data has single attribute.

SOM: check if data has single attribute

---

Orange/widgets/data/icons/Pivot.svg
Orange/widgets/data/icons/Transform.svg
Orange/widgets/unsupervised/icons/SOM.svg

Updated icons

---

Orange/data/sql/backend/postgres.py
Orange/widgets/data/owsql.py
Orange/widgets/data/tests/test_owsql.py

- refactor SQL Table widget so it extends OWBaseSql
- fix crash when postgres is not installed

SQL: Inherit from OWBaseSql

---

Orange/widgets/tests/base.py
Orange/widgets/unsupervised/owmds.py
Orange/widgets/visualize/utils/widget.py

Display input and output data info in status bar.

OWDataProjectionWidget: Set input/output summary

---

Orange/widgets/data/owrandomize.py
Orange/widgets/data/tests/test_owrandomize.py

Display input and output data info in status bar.

OWRandomize: data info displayed in status bar

---

Orange/widgets/data/owdatasampler.py
Orange/widgets/data/tests/test_owdatasampler.py

Display input and output data info in status bar.

DataSampler: data info displayed in status bar

---

doc/visual-programming/source/widgets/data/featurestatistics.md

Fixes #4159. 
Replace dispersion with coefficient of variation in the documentation.

[DOC] Feature Statistics: replace dispersion with coef. of variation

---

Orange/widgets/unsupervised/owdbscan.py
Orange/widgets/unsupervised/owpca.py
Orange/widgets/utils/slidergraph.py

Fixes #4149
Adding the legend to the SliderGraph which PCA uses for the plot.

OWPCA: add legend

---

Orange/widgets/visualize/utils/widget.py

Incorrect output default.
Use `NoOutput` instead of `NoInput`.

OWDataProjectionWidget: Set output summary

---

Orange/widgets/unsupervised/owmds.py

[FIX] MDS: Place lines under points and labels

---

Orange/preprocess/normalize.py
Orange/tests/test_normalize.py

[FIX] Normalizer: Retain attributes of attributes

---

Orange/widgets/evaluate/owrocanalysis.py
Orange/widgets/evaluate/tests/test_owrocanalysis.py

Fixes #4171
The widget computes target prior based on the class distribution in the data. Also, the target_prior was changed to the ContextSetting since now it depends on data.

OWROCAnalysis: Compute target_prior based on data

---

MANIFEST.in
README.pypi
setup.py

README for Github and README for PyPi should not be the same. The description should be shorter, without Github tags.
Provide a separate PyPi README.

Provide a separate README for PyPi

---

Orange/evaluation/clustering.py
Orange/tests/test_evaluation_clustering.py
Orange/widgets/data/tests/test_owcorrelations.py
requirements-core.txt

Fixes failing tests.
Update clustering test to sklearn=0.22.0 and update the requirements.

Updated tests to sklearn=0.22.0

---

Orange/tests/test_txt_reader.py

https://github.com/python/cpython/commit/7821b4c6d29933511d50bb42255e39790c6abf00#diff-9ba2eeca0f254ece0a9df4d7cb68e870

test_txt_reader: Update test for py38 error message

---

Orange/widgets/visualize/owboxplot.py
Orange/widgets/visualize/tests/test_owboxplot.py

Box Plot: Don't show hidden attributes

---

Orange/widgets/data/owmergedata.py
Orange/widgets/data/tests/test_owmergedata.py

Old workflows (with Merge data widgets) crash on migrate settings. 
To reproduce: 
- checkout 3d0787a
- save a workflow with: File (Iris) -> MergeData (data and extra data)
- checkout master
- open the workflow
Fix setting migration.

[FIX] Merge data: Migrate settings

---

Orange/widgets/model/owtree.py

[ENH] OWTree: Add 'Classification Tree' keyword

---

Orange/widgets/data/owsql.py
Orange/widgets/data/tests/test_owsql.py

[FIX] SQL: Save selected backend to settings

---

doc/widgets.json

Adds necessary things for #4283. 
Re-generate widget.json to match new keywords.

Renew widget.json

---

Orange/widgets/unsupervised/owdistances.py
Orange/widgets/unsupervised/tests/test_owdistances.py

Fixes #4277.
The problem occurs if we have too many rows when computing column-wise distances and vice-versa, because Mahalanobis must compute the inverse of the covariance matrix.
- When the dimensionality is too large, the widget shows and error and does not compute.
- Mahalanobis is moved towards the end of the list

OWDistance: Limit Mahalanobis to 1000 rows/columns

---

Orange/widgets/evaluate/owpredictions.py
Orange/widgets/evaluate/tests/test_owpredictions.py

Fixes #2929 
With these changes one can sort the right (data) view too and get data in the left view sorted according to sorting in the right view.

Predictions: Make both views sortable

---

Orange/widgets/visualize/ownomogram.py
Orange/widgets/visualize/tests/test_ownomogram.py

[FIX] Nomogram: Adjust scale considering label width

---

Orange/widgets/unsupervised/owdistances.py
Orange/widgets/utils/plot/owplotgui.py
Orange/widgets/visualize/owboxplot.py

Resolves #4318.
Add stateWhenDisabled where appropriate.

Set stateWhenDisabled where appropriate

---

Orange/widgets/data/owselectcolumns.py
doc/widgets.json

It helps to add tags like this to help new users with Orange, they tend to try to guess a widget's name before browsing for it.

OWSelectColumns: 'attributes', 'target', 'variable' tags

---

Orange/widgets/data/owfeaturestatistics.py
Orange/widgets/data/tests/test_owfeaturestatistics.py

Ref. https://github.com/biolab/orange-widget-base/pull/35
- convert selected rows to list

[FIX] FeatureStatistics: Convert selected rows to list

---

Orange/widgets/data/owsave.py
doc/widgets.json

owsave: add "export" keyword

---

Orange/widgets/utils/state_summary.py
Orange/widgets/utils/tests/test_state_summary.py

A function is created which formats the descriptive part (details) of the input/output summary. This is created in order for the details to be consistent for all widgets that output data.

String formatting for the input/output summary

---

Orange/widgets/data/owpreprocess.py
Orange/widgets/data/tests/test_owpreprocess.py

[ENH] OWPreporcess: Data info displayed in the status bar

---

Orange/widgets/evaluate/owpredictions.py

Fixes #4427
listBox selectionMode changed from MultiSelection to ExtendedSelection

Predictions: listBox from MultiSelection to ExtendedSelection

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Some people don't understand that these are templates: they keep the template as it is and write the actual issue as a comment (to the template). This change could perhaps help.
I also removed flag "suggestion" which serves no purpose. Whatever is not a bug is a suggestion.

Issue templates for dummies :)

---

Orange/widgets/data/owselectcolumns.py
Orange/widgets/data/tests/test_owselectcolumns.py

[ENH] OWSelectColumns: Data info displayed in the status bar

---

Orange/widgets/data/owrank.py
Orange/widgets/data/tests/test_owrank.py

[ENH] OWRank: Data info displayed in the status bar

---

Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/data/tests/test_owfeatureconstructor.py

[ENH] OWFeatureConstructor: Data info displayed in the status bar

---

Orange/widgets/data/owcontinuize.py
Orange/widgets/data/tests/test_owcontinuize.py

[ENH] OWContinuize: Data info displayed in the status bar

---

Orange/widgets/data/owselectcolumns.py
Orange/widgets/data/tests/test_owselectcolumns.py
Orange/widgets/settings.py
Orange/widgets/tests/test_domain_context_handler.py
Orange/widgets/unsupervised/owlouvainclustering.py
Orange/widgets/unsupervised/tests/test_owlouvain.py
Orange/widgets/unsupervised/tests/test_owmds.py
Orange/widgets/visualize/tests/test_owlinearprojection.py
Orange/widgets/visualize/tests/test_owradviz.py

Fixes #4415 and similar problems in other widgets.

Always match the latest applicable context in domain context handlers

---

Orange/widgets/data/owpreprocess.py

The preprocess widget is already used in SCOrange addon and is about to be used in Text addon, even though not set as open class.
Open the OWPreprocess class.

Preprocess: Inheritable widget

---

Orange/widgets/utils/image.py

Ref: gh-4518
Return early when image is empty

[FIX] utils/image: Return early when image is empty

---

Orange/widgets/data/owrandomize.py
Orange/widgets/data/tests/test_owrandomize.py

[ENH] OWRandomize: Data info displayed in the status bar

---

Orange/widgets/data/owcsvimport.py
Orange/widgets/data/tests/test_owcsvimport.py

[ENH] OWCSVImport: Data info displayed in the status bar

---

Orange/widgets/data/owfile.py
Orange/widgets/data/tests/test_owfile.py

[ENH] OWFile: Data info displayed in the status bar

---

Orange/widgets/data/tests/test_owsql.py
Orange/widgets/utils/owbasesql.py
Orange/widgets/utils/tests/test_owbasesql.py

BaseSql: Modify output summary

---

Orange/misc/server_embedder.py
Orange/misc/tests/example_embedder.py
Orange/misc/tests/test_server_embedder.py
Orange/misc/utils/embedder_utils.py
requirements-core.txt

The embedder server component is currently placed in ImageAnalytics, but since it will be now used in Text addon too I am moving it to core Orange.
Embedder server component moved to core Orange and modified to work with different types of data.
This PR is ready but I suggest not merging it yet. When word embedders will be implementing in Text I am sure some changes will be needed in this component.

[RFC] Embedding server component

---

Orange/widgets/data/owtable.py

Alternative to gh-4549
Suppress updates when drag selecting.

owtable: Suppress updates when drag selecting

---

Orange/widgets/tests/base.py
Orange/widgets/visualize/utils/widget.py

Add detail to data info summary in status bar.

[ENH] OWDataProjectionWidget: Upgrade status bar data info

---

Orange/projection/manifold.py

Fixes #4559.
Replace `is` with `==`.

manifold.py: Remove 'is' with literal

---

Orange/widgets/visualize/utils/heatmap.py

Ref gh-4522
Change tick display format for gradient color legend from .2f to .6g

heatmap: Change tick label display precison

---

Orange/widgets/data/tests/test_owoutliers.py
Orange/widgets/evaluate/owtestlearners.py
Orange/widgets/unsupervised/tests/test_owtsne.py

Ref gh-4553
Probably does not fix, but can't hurt either.
* Cleanup/wait for owoutliers, owtsne, and owtestlearners

Tests cleanup

---

Orange/widgets/data/owpreprocess.py

The unchecked 'auto apply' box says 'Send Selection'. 
Rename the box into 'Apply'.

Preprocess: Rename 'Send selection' into 'Apply'

---

Orange/widgets/data/owfeaturestatistics.py

Fixes #4522.
- Instead of `%.2f`, it now uses `str_val`. `str_val` will show a larger number of decimals in the future (in another pull request).
- Model's `data` method was split into functions for readability and lower cyclomatic complexity.

Feature statistics: Reformat numbers

---

Orange/widgets/data/owneighbors.py
Orange/widgets/data/tests/test_owneighbors.py

[ENH] Neighbors: data info displayed in the status bar

---

Orange/widgets/data/owmergedata.py
Orange/widgets/data/tests/test_owmergedata.py

[ENH] MergeData: data info displayed in the status bar

---

Orange/widgets/visualize/owdistributions.py
Orange/widgets/visualize/tests/test_owdistributions.py

[ENH] Distributions: data info displayed in the status bar

---

Orange/widgets/data/owconcatenate.py
Orange/widgets/data/tests/test_owconcatenate.py

[ENH] Concatenate: data info displayed in the status bar

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/tests/test_owmosaic.py

[ENH] MosaicDisplay: data info displayed in the status bar

---

Orange/widgets/data/owcsvimport.py
Orange/widgets/data/tests/test_owcsvimport.py

CSVImport: Set the name of the output table

---

Orange/widgets/data/owpaintdata.py
Orange/widgets/data/tests/test_owpaintdata.py

PaintData: data info displayed in the status bar

---

Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/tests/test_owheatmap.py

HeatMap: data info displayed in the status bar

---

Orange/widgets/visualize/owsilhouetteplot.py
Orange/widgets/visualize/tests/test_owsilhouetteplot.py

OWSilhouettePlot: data info displayed in the status bar

---

Orange/widgets/visualize/owsieve.py
Orange/widgets/visualize/tests/test_owsieve.py

OWSieve: data info displayed in the status bar

---

Orange/widgets/visualize/owtreeviewer.py
Orange/widgets/visualize/tests/test_owtreegraph.py

Input/output data displayed in the status bar.

TreeViewer: data info displayed in the status bar

---

Orange/widgets/visualize/owpythagorastree.py
Orange/widgets/visualize/tests/test_owpythagorastree.py

Input/output data displayed in the status bar.

PythagoreanTree: data info displayed in the status bar

---

Orange/widgets/visualize/owpythagorastree.py
Orange/widgets/visualize/tests/test_owpythagorastree.py

Revert "PythagoreanTree: data info displayed in the status bar"

---

Orange/widgets/visualize/owtreeviewer.py
Orange/widgets/visualize/tests/test_owtreegraph.py

Revert "TreeViewer: data info displayed in the status bar"

---

Orange/widgets/visualize/ownomogram.py
Orange/widgets/visualize/tests/test_ownomogram.py

Input data info displayed in the status bar.

Nomogram: data info displayed in the status bar

---

Orange/widgets/visualize/owruleviewer.py
Orange/widgets/visualize/tests/test_owruleviewer.py

RuleViewer: data info displayed in the status bar

---

.travis/upload_doc.sh

Documentation upload by Travis fails after the merge (for the last 10 days).
Updated ssh host address.

Fix documentation host url

---

Orange/widgets/visualize/owvenndiagram.py
Orange/widgets/visualize/tests/test_owvenndiagram.py

VennDiagram: data info displayed in the status bar

---

Orange/widgets/data/owdatainfo.py
Orange/widgets/data/owdatasampler.py
Orange/widgets/data/owselectrows.py
Orange/widgets/utils/owbasesql.py

Fixes #4694.
`len(data)` replaced with `data.approx_len()` in summary info in following:
For the OWDataTable this is in PR #4642.

Summary Info: Support SqlTable

---

Orange/widgets/evaluate/owtestandscore.py
Orange/widgets/evaluate/tests/test_owtestandscore.py

Input data info displayed in the status bar.

TestAndScore: data info displayed in the status bar

---

Orange/widgets/utils/owlearnerwidget.py
Orange/widgets/utils/tests/test_owlearnerwidget.py

BaseLearner: Add input summary info

---

Orange/widgets/data/owrank.py
Orange/widgets/data/tests/test_owrank.py

Fixes #4672.
Existing contexts are not migrated but removed. Old contexts store row indices instead of variables. These could be migrated if we assume that dictionary `context.attributes` is ordered, which is not necessarily true. They could also be migrated in `set_data`.
I however decided to remove them because they would match any domain and thus never really worked.

OWRank: Store selection as variables

---

Orange/widgets/unsupervised/owlouvainclustering.py
Orange/widgets/unsupervised/tests/test_owlouvain.py

LouvainClustering: data info displayed in the status bar

---

Orange/widgets/evaluate/owconfusionmatrix.py
Orange/widgets/evaluate/tests/test_owconfusionmatrix.py

ConfusionMatrix: data info displayed in the status bar

---

Orange/widgets/utils/graphicstextlist.py

Fixes gh-4712
Remove a wrong check

[FIX] graphicstextlist: Fix size/spacing adjustment for single item

---

Orange/widgets/unsupervised/owkmeans.py
Orange/widgets/unsupervised/tests/test_owkmeans.py

KMeans: data info displayed in the status bar

---

Orange/widgets/visualize/owboxplot.py
Orange/widgets/visualize/tests/test_owboxplot.py

[FIX] BoxPlot: Fix invalid data range

---

Orange/widgets/unsupervised/owdistancemap.py
Orange/widgets/unsupervised/tests/test_owdistancemap.py

DistanceMap: data info displayed in the status bar

---

Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/unsupervised/tests/test_owhierarchicalclustering.py

HierarchicalClustering: data info displayed in the status bar

---

Orange/widgets/data/owselectrows.py
Orange/widgets/data/tests/test_owselectrows.py

Fixes #4737, the real #4737, I hope.
After changing the attribute reset the choice to the previous, if it still exists.

Select Rows: Keep operator when possible

---

Orange/widgets/unsupervised/owpca.py

Ids were not copied when doing Table.from_numpy.

[FIX] PCA: fix subsets with the "Data" output

---

Orange/widgets/data/owselectrows.py
Orange/widgets/data/tests/test_owselectrows.py

Meta variables are not saved correctly in the context
Fix saving meta-variables in context - add missing type.

[FIX] Select Rows: Fix saving meta variables in context

---

Orange/widgets/visualize/owheatmap.py

Resolves gh-4782
Enable/disable clustering/cluster ordering on estimated time cost.

owheatmap: Disable/enable clustering on estimated cost

---

Orange/widgets/data/owfeaturestatistics.py
Orange/widgets/data/tests/test_owfeaturestatistics.py

Implements #4773
Implement report for feature statistics
It can be merged when https://github.com/biolab/orange-widget-base/pull/68 is merged and the orange widget base is released.

[ENH] Feature statistics report

---

Orange/widgets/unsupervised/owdbscan.py
Orange/widgets/unsupervised/tests/test_owdbscan.py

DBSCAN: data info displayed in the status bar

---

Orange/canvas/__main__.py
requirements-gui.txt

Closes https://github.com/biolab/orange-canvas-core/issues/54
Setup logging to display in main window output view.
<s>Depends on https://github.com/biolab/orange-canvas-core/pull/102 which must be merged and released before this.</s>(was released)

[ENH] main: Log to main window output view

---

Orange/widgets/data/owtable.py
Orange/widgets/data/tests/test_owtable.py

DataTable: data info displayed in the status bar

---

Orange/data/tests/test_variable.py
Orange/data/variable.py
Orange/widgets/data/owconcatenate.py

Test started to warn that TupleList should be removed in version >=3.27
TupleList removed

Remove TupleList

---

Orange/data/domain.py
Orange/tests/sql/test_sql_table.py
Orange/tests/test_contingency.py
Orange/tests/test_domain.py
Orange/tests/test_table.py
Orange/widgets/data/owpivot.py
Orange/widgets/data/owrank.py
Orange/widgets/data/tests/test_owconcatenate.py
Orange/widgets/data/tests/test_oweditdomain.py
Orange/widgets/utils/tests/test_domaineditor.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/owradviz.py
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/tests/test_owlinearprojection.py
Orange/widgets/visualize/utils/widget.py

Check that Domain is unique

---

Orange/widgets/data/owcsvimport.py

CSV Import: fix wrong type in astype

---

Orange/widgets/visualize/owdistributions.py
doc/widgets.json

Fixes #4906
Add histogram keyword in distributions widget

Add histogram keyword in distributions widget

---

Orange/widgets/evaluate/tests/test_owrocanalysis.py

- Miscellaneous workflow started to fail because of changes in the latest pyqtgraph (https://github.com/pyqtgraph/pyqtgraph/pull/1276/files).
- There is also an issue with ArrowItem which is fixed by @ales-erjavec in https://github.com/pyqtgraph/pyqtgraph/pull/1336
- Reset "mouseRateLimit" for unittests.

Fix tests that fails because of changes in pyqtgraph

---

Orange/misc/tests/test_server_embedder.py
requirements-core.txt

HTTPX released a new version which has a change that needed tests to be changed.
When introducing HTTPX I set the version limitation wrongly.
- Fixed test
- Version updated to ~=0.14.0

Fix embedders tests

---

Orange/widgets/tests/base.py
Orange/widgets/visualize/tests/test_owscatterplot.py

Implements #4891
Implement widget tests

Projections: Test visual settings

---

Orange/widgets/unsupervised/owpca.py
Orange/widgets/unsupervised/tests/test_owpca.py

PCA: clear output when input data is removed

---

Orange/widgets/unsupervised/owsom.py
Orange/widgets/unsupervised/tests/test_owsom.py

SOM: data info displayed in the status bar

---

Orange/misc/server_embedder.py
Orange/misc/utils/embedder_utils.py

[ENH] Proxy support for embeddings

---

README.md

Closes Issue #4933 
Like the title

Add Installing with winget (Windows only) section

---

Orange/misc/server_embedder.py

Server embedded did not close the event loop on exception. 
Closing the event loop on exception - this removes warnings

Server Embedder: remove warnings

---

Orange/widgets/unsupervised/owcorrespondence.py
Orange/widgets/unsupervised/tests/test_owcorrespondence.py

Input/output data info added to the status bar.

CorrespondenceAnalysis: data info displayed in the status bar

---

Orange/widgets/unsupervised/owmanifoldlearning.py
Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py

Input/output data info added to the status bar.

ManifoldLearning: data info displayed in the status bar

---

Orange/widgets/evaluate/owpredictions.py
Orange/widgets/evaluate/tests/test_owpredictions.py

Output data info added to the status bar.

Predictions: data info displayed in the status bar

---

Orange/widgets/visualize/owmosaic.py
Orange/widgets/visualize/tests/test_owmosaic.py

Resolves https://github.com/biolab/orange-widget-base/issues/87.

Mosaic Vizrank with fixed number of variables

---

Orange/widgets/utils/domaineditor.py

Three/Four clicks to change a feature role feels like a bit much, doesn't it? Click and release in OWFile to do it one click with this PR.

domaineditor: Edit in one click

---

Orange/widgets/visualize/ownomogram.py
Orange/widgets/visualize/tests/test_ownomogram.py

Just something to signal to new users what's interactable.

ownomogram: Flash dots until first interaction

---

Orange/widgets/utils/plot/owplotgui.py

Minor, just some wording and cleanup.

owplotgui: Add colon to jittering

---

Orange/widgets/data/owneighbors.py
Orange/widgets/data/tests/test_owneighbors.py

Fixes #5000.
Neighbors output copies original data ids.

OWNeighbors: copy original ids to neighbor output

---

Orange/widgets/visualize/owscatterplotgraph.py

[FIX] Scatter Plot: fix unzoom with density plot

---

Orange/widgets/visualize/owscatterplotgraph.py

owscatterplotgraph: Make + and x symbols thicker

---

Orange/widgets/data/owtable.py

[ENH] Table: Re-add info box about data properties

---

Orange/widgets/data/owtable.py
Orange/widgets/data/tests/test_owtable.py

Data Table: fix info for an empty table

---

Orange/widgets/model/owlogisticregression.py
Orange/widgets/model/owrandomforest.py
Orange/widgets/model/tests/test_owlogisticregression.py
Orange/widgets/model/tests/test_owrandomforest.py

Implements #4986.
Add checkbox to consider class weights in Logistic Regression and Random Forest.
Trigger Warning when checking the parameter.
Add tests.

RF and LogReg: add class_weight parameter

---

Orange/widgets/unsupervised/owdistances.py
Orange/widgets/unsupervised/tests/test_owdistances.py

Distances: data info displayed in the status bar

---

pyproject.toml
setup.cfg

Widget help files are not included in source and wheel files.
* Add sphinx and recommonmark to build time dependencies
* Build and install widget help documentation files automatically.

setup: Add sphinx and recommonmark to build time dependencies

---

Orange/widgets/data/owpivot.py
Orange/widgets/data/tests/test_owpivot.py

Fixes #5030
- show warning when number of distinct column values exceeds 100
- display info for all outputs in status bar 
- make selection schema-only setting

[FIX] Pivot: Handle big dataset

---

Orange/widgets/data/owselectcolumns.py
Orange/widgets/data/tests/test_owselectcolumns.py

New columns that come in the select columns widget are placed in selected data. It can sometimes break the workflow. *It is the most problematic when workflows still pass but results can be wrong because of new columns.*
I present the option to decide what to do with new columns.
- ideas for a good label
- since this option says about new/additional features, I decided to take checkbox into account only in cases when context already exists for this domain. In cases with new context, all features are automatically selected. Should we keep like this or should we also take this option into account with a completely new domain? If we decide for later we should change the label.

Select columns: option to unselect new columns

---

Orange/widgets/unsupervised/owdistancematrix.py

Fixes gh-5069
Reduce size hinting computational cost

owdistancematrix: Reduce size hinting computational cost

---

Orange/widgets/utils/owlearnerwidget.py

A common question we get regards this error.
Adds explanation we usually offer when people ask us what to do.
Also note biolab/orange-widget-base#122.

owlearnerwidget: Add to no-target error advice to use Select Columns

---

Orange/data/domain.py
Orange/tests/test_domain.py
benchmark/base.py

Followup to #4422; some more deletions.

Domain conversion cache cleanup

---

Orange/widgets/model/owsgd.py

Tests fail because the OWSGD is too high.
Rearrange the GUI into two columns + minor realignments.

OWSGD: Rerrange UX

---

Orange/widgets/data/owimpute.py

Fixes gh-5081
* Disable method controls when no variables are selected
* Fix a layout warning from Qt

Impute: Disable controls 

---

Orange/widgets/data/owselectcolumns.py

When talking about implementing button about selecting new features https://github.com/biolab/orange3/pull/5105 we said that it would be nice to add an info message about what this button does. 
EDIT: Later we decided to implement tooltip only.
Info message is implemented in this PR. Anyone with the idea for a better message is welcome to give his/her suggestion.
EDIT: It is implemented as a tooltip now.

Select columns info message about select new features checkbox

---

Orange/widgets/unsupervised/owhierarchicalclustering.py

This was overlooked.
Also adds some `addToLayout=False` kwargs that reduce empty space.

owhierarchicalclustering: Move autocommit to buttonsArea

---

doc/visual-programming/source/widgets/visualize/lineplot.md

Fixes #4928.
Add a short line in docs explaining how to do it.

[DOC] Line Plot: zoom by individual axis

---

Orange/widgets/data/owpreprocess.py

https://github.com/biolab/orange3-text/issues/624#issuecomment-796329762

OWPreprocess: Remove sizeHint workaround

---

Orange/data/io_base.py
Orange/widgets/data/tests/test_oweditdomain.py

Fixes #5307.
Map "True" and "False" to respective boolean values.

Edit Domain: Map bool to bool

---

.github/workflows/rebase.yml

ci: use PAT (biolab-helper) in rebase workflow

---

README.md

https://github.com/biolab/orange3-text/issues/623
I'm assuming the root of this issue is having installed Orange with pip.
Add a Windows warning next to the pip installation instructions.

README: Fixup instructions for running Orange

---

doc/visual-programming/source/index.rst

Fix aggregate columns doc link

---

Orange/widgets/data/owcontinuize.py
Orange/widgets/data/owdiscretize.py
doc/widgets.json

Resolves #5249.
Add keywords
- to Continuize: *encode*, *dummy*, *numeric*, *one-hot*, *binary*
- to Discretize: *bin*, *categorical*, *nominal*, *ordinal*
If anybody has anything to add, say so.

Continuize, Discretize: Add keywords for easier searching

---

doc/visual-programming/source/widgets/model/adaboost.md
doc/visual-programming/source/widgets/model/cn2ruleinduction.md
doc/visual-programming/source/widgets/model/constant.md
doc/visual-programming/source/widgets/model/gradientboosting.md
doc/visual-programming/source/widgets/model/knn.md
doc/visual-programming/source/widgets/model/linearregression.md
doc/visual-programming/source/widgets/model/logisticregression.md
doc/visual-programming/source/widgets/model/naivebayes.md
doc/visual-programming/source/widgets/model/neuralnetwork.md
doc/visual-programming/source/widgets/model/randomforest.md
doc/visual-programming/source/widgets/model/stochasticgradient.md
doc/visual-programming/source/widgets/model/svm.md
doc/visual-programming/source/widgets/model/tree.md

Fixes #5346.
Add information on default preprocessors for each learner.
TODO:
- Constant
- Tree
**Edit (janezd): ** Constant and Tree do not use preprocessing.

[DOC] Default preprocessing for learners

---

Orange/widgets/visualize/tests/test_owlineplot.py
Orange/widgets/visualize/utils/plotutils.py
Orange/widgets/visualize/utils/tests/test_plotutils.py
conda-recipe/meta.yaml
requirements-gui.txt

Require pyqtgraph>=0.11.1

---

doc/visual-programming/source/widgets/model/constant.md
doc/visual-programming/source/widgets/model/tree.md

Continues #5353. 
Change Constant and Tree to "does not use any preprocessors".

[DOC] No preprocessing for two learners

---

Orange/widgets/unsupervised/owmds.py
Orange/widgets/unsupervised/owtsne.py
Orange/widgets/visualize/owfreeviz.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owradviz.py

Fixes #5320.
Also reduces excessive spacing in MDS and Linear projection.
Issues related to widgets in add-ons are opened in their respective repositories.

MDS, tSNE, FreeViz, Linear Projection, Radviz: Add named boxes

---

Orange/widgets/visualize/ownomogram.py
Orange/widgets/visualize/tests/test_ownomogram.py

[FIX] Nomogram: Retain original compute_value

---

Orange/widgets/visualize/owvenndiagram.py
Orange/widgets/visualize/tests/test_owvenndiagram.py
doc/visual-programming/source/widgets/visualize/venndiagram.md

Venn Diagram: Add comparison by equality

---

Orange/canvas/__main__.py

Fixes https://github.com/biolab/orange3/issues/5396

__main__: Less verbose notification feed logging

---

Orange/widgets/data/owpythonscript.py

Resolves #5373.
Change default script to "from_numpy".

Python Script: Change default script

---

Orange/widgets/unsupervised/owdbscan.py
Orange/widgets/unsupervised/tests/test_owdbscan.py

DBSCAN: Retain data ids

---

Orange/widgets/data/owtable.py
Orange/widgets/data/tests/test_owtable.py
Orange/widgets/evaluate/owpredictions.py
Orange/widgets/gui.py
Orange/widgets/unsupervised/owdistancematrix.py
Orange/widgets/unsupervised/tests/test_owdistancematrix.py
Orange/widgets/utils/headerview.py
Orange/widgets/utils/itemdelegates.py
Orange/widgets/utils/itemmodels.py
benchmark/bench_datadelegate.py

Ref: gh-5073
Use caching DataDelegate (https://github.com/biolab/orange-widget-base/pull/139) in data itemviews.

[ENH] Caching data delegate

---

ROADMAP.md

Initial commit of the roadmap. Thanks for all contributors in drafting this document.

[DOC] roadmap

---

Orange/widgets/data/owaggregatecolumns.py

Fixes temporarily https://github.com/biolab/orange3/issues/5453
We wrap self.commit in lambda and so it is not getting called when auto-commit is not selected

Aggregate Columns - wrap commits in lambda for callbacks

---

Orange/canvas/run.py

https://github.com/biolab/orange-canvas-core/issues/144
<s>Requires: https://github.com/biolab/orange-canvas-core/pull/190</s> (was merged an released)
Add an experimental batch runner, e.g.
```
python -m Orange.canvas.run $workflow_path
```

canvas: Add 'batch' runner

---

Orange/widgets/tests/base.py

A test `test_output_model_picklable` passes in case the widget does not output the model, even though the model could not have been pickled.
Add a `model is not None` assertion.

WidgetLearnerTestMixin: improve test

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

The checkboxes in our issue templates were a bit useless, perhaps confusing.
Removes them.

ISSUE_TEMPLATE: Remove checkboxes

---

doc/visual-programming/source/widgets/unsupervised/PCA.md

[DOC] PCA: document preprocessors

---

Orange/widgets/evaluate/owliftcurve.py
Orange/widgets/evaluate/tests/test_owliftcurve.py

Fixes #5521
Implement visual settings.

Lift Curve: Implement visual settings

---

requirements-core.txt

httpx released two version from since we updated version last time
Increase httpx version to support versions <0.20. We fix httpx's versions since the package is still beta and it is suggested by the package's maintainers.

httpx: Increase supported version

---

doc/visual-programming/source/widgets/unsupervised/distances.md

Fixes #5587. 
Properly reference cosine distance in computation of distances.

[DOC] Distances: mention cosine distance.

---

doc/data-mining-library/source/reference/data.io.rst
doc/data-mining-library/source/tutorial/data.rst

Users don't know how to create a Table.
Add an example how to create a Table from scratch.

[DOC] Add example on creating data table

---

Orange/widgets/data/owunique.py

Unique widget still use listView without search. 
Replace listView with listViewSearch

Unique: replace listview with listViewSearch

---

Orange/canvas/__main__.py
Orange/canvas/config.py
requirements-gui.txt

Fixes: gh-5282
<s>Requires https://github.com/biolab/orange-canvas-core/pull/184 to be merged and released.</s>(was released)
Use Main class from orange-canvas-core

main: Refactor

---

Orange/widgets/data/owrank.py
Orange/widgets/data/tests/test_owrank.py

Fixes #5573.
- Show variable names in a column
- Implement (case-insensitive) sorting, ascending by default

Rank: Show variable names in column, not header

---

conda-recipe/meta.yaml
requirements-core.txt

Pandas 1.0.0 could not run test_aggregate

Require pandas==1.1.0

---

Orange/widgets/utils/state_summary.py

`date.month` -> `date.today.month()`

Fix date query

---

doc/visual-programming/source/widgets/visualize/heatmap.md

Fixes #5674
Added short documentation of used clustering methods and distances.

Heatmap clustering documentation

---

Orange/widgets/__init__.py
Orange/widgets/data/owaggregatecolumns.py
Orange/widgets/data/owconcatenate.py
Orange/widgets/data/owcontinuize.py
Orange/widgets/data/owcorrelations.py
Orange/widgets/data/owcreateclass.py
Orange/widgets/data/owcreateinstance.py
Orange/widgets/data/owdatasampler.py
Orange/widgets/data/owdiscretize.py
Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/data/owgroupby.py
Orange/widgets/data/owimpute.py
Orange/widgets/data/owmelt.py
Orange/widgets/data/owmergedata.py
Orange/widgets/data/owneighbors.py
Orange/widgets/data/owoutliers.py
Orange/widgets/data/owpivot.py
Orange/widgets/data/owpreprocess.py
Orange/widgets/data/owpurgedomain.py
Orange/widgets/data/owpythonscript.py
Orange/widgets/data/owrandomize.py
Orange/widgets/data/owselectbydataindex.py
Orange/widgets/data/owselectcolumns.py
Orange/widgets/data/owselectrows.py
Orange/widgets/data/owtransform.py
Orange/widgets/data/owtranspose.py
Orange/widgets/data/owunique.py

Resolve: gh-5370
(requires https://github.com/biolab/orange-widget-base/pull/179)
Move most widgets from Data to Transform or Unsupervised category

[RFC] Move some widgets from Data to Transform and Unsupervised category

---

doc/build_doc.sh
doc/widgets.json

Now that Orange3 has a Transform category, tests fail.

Update widgets.json for the new Transform category

---

Orange/tests/test_regression.py

When executing TestRegression several exceptions are printed due to CurveFitLearner's missing `expression` argument.
Explicitly pass the `expression` value to CurveFitLearner.

TestRegression: Add expression to CurveFitLearner

---

tox.ini

https://github.blog/2021-09-01-improving-git-protocol-security-github/

Replace git with zip downloads for latest dependencies

---

doc/visual-programming/source/widgets/visualize/heatmap.md

Fixes #5701. 
Explain how to use keyboard shortcuts.
(still not sure how to properly explain the difference between Cmd+0 and Cmd+9)

[DOC] Heat Map: Explain how to reset zoom

---

doc/visual-programming/source/widgets/data/applydomain.md
doc/visual-programming/source/widgets/unsupervised/kmeans.md
doc/visual-programming/source/widgets/unsupervised/louvainclustering.md
doc/visual-programming/source/widgets/unsupervised/manifoldlearning.md
doc/visual-programming/source/widgets/unsupervised/mds.md
doc/visual-programming/source/widgets/unsupervised/tsne.md

Resolves #5805.
Unsupervised widgets had no information on preprocessing.
Explain why template data is needed for transformation in Apply Domain.
Add info on preprocessing in unsupervised widgets.

[DOC] Apply Domain explained + Preprocessing for Unsupervised

---

Orange/widgets/utils/classdensity.py

Fixing random seed fixes #5825.

classdensity: Replicable sampling

---

Orange/widgets/model/owcurvefit.py
Orange/widgets/model/owsvm.py
Orange/widgets/utils/tests/concurrent_example.py
Orange/widgets/visualize/owfreeviz.py
Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/owradviz.py
Orange/widgets/visualize/owscatterplot.py

[FIX] Decorate overridden input data handler

---

Orange/widgets/model/owneuralnetwork.py
Orange/widgets/model/tests/test_owneuralnetwork.py

Resolves #5817 and #5818. 
Enable no layers and no regularization.

Neural Network: include no layers and no regularization

---

Orange/canvas/__main__.py

Fixes gh-5794
* Add command line switch to clear all known settings/caches

[ENH] orange-canvas: Add cmd parameter to clear all settings/caches

---

Orange/widgets/data/owcorrelations.py

Fixes #5864
- center variable names

Correlations: Align variable names

---

Orange/widgets/unsupervised/owsom.py
Orange/widgets/unsupervised/tests/test_owsom.py

SOM recalculates when new data appears on the input, even though the data might be the same.
- check if data has change since the last plotting and recalculate only if necessary
- consider only continuous variables

SOM: Recompute only when effective data changes

---

.github/workflows/test.yml
Orange/widgets/evaluate/tests/test_owpredictions.py
Orange/widgets/model/tests/test_owcalibratedlearner.py
Orange/widgets/tests/utils.py
Orange/widgets/visualize/tests/test_ownomogram.py

Three tests are failing after merging https://github.com/biolab/orange-widget-base/pull/187.
Do not assume how signals are connected in tests.

tests: Fix tests failing with orange-widget-base#187

---

setup.py

setup.py: update homepage URL

---

Orange/widgets/data/owaggregatecolumns.py
Orange/widgets/data/owcontinuize.py
Orange/widgets/data/owcreateclass.py
Orange/widgets/data/owcreateinstance.py
Orange/widgets/data/owdiscretize.py
Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/data/owgroupby.py
Orange/widgets/data/owimpute.py
Orange/widgets/data/owmelt.py
Orange/widgets/data/owpivot.py
Orange/widgets/data/owpreprocess.py
Orange/widgets/data/owpurgedomain.py
Orange/widgets/data/owrandomize.py
Orange/widgets/data/owtransform.py
Orange/widgets/data/owtranspose.py
Orange/widgets/data/owunique.py

Reorder widgets in the Transform category

---

doc/widgets.json

Someone merged #5933 too quickly. :)

Reorder Transform category in widgets.json

---

Orange/widgets/visualize/owtreeviewer.py
Orange/widgets/visualize/owtreeviewer2d.py

Tree Viewer: Improve tooltip

---

Orange/widgets/visualize/owviolinplot.py
Orange/widgets/visualize/tests/test_owviolinplot.py

Resolves #5929.
Add checkbox and grid.
**To do:**

Violin Plot: Add grid

---

Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/data/tests/test_owfeatureconstructor.py

Make feature constructor widget run computation in a background thread.
Make concurrent

[ENH] Feature Constructor: Make concurrent

---

Orange/widgets/visualize/ownomogram.py

Nomogram: Elide long variable names

---

Orange/widgets/data/owcreateinstance.py
Orange/widgets/data/tests/test_owcreateinstance.py

Create Instance: Unique source variable name

---

Orange/widgets/visualize/owscatterplot.py

Fixes #5900.
Set random state for ReliefF.

Scatterplot VizRank: Set random_state for ReliefF

---

Orange/widgets/data/owcreateinstance.py
Orange/widgets/data/tests/test_owcreateinstance.py

Fixes #5993
- enable missing values for discrete variables: add a `?` to the dropdown of possible values
- enable missing values for continuous variables: show `?` when the number in spin box in deleted, which is considered a missing value

Create Instance: Enable missing values

---

Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/tests/test_owheatmap.py

Fixes #5306.
Hide hidden attributes.

OWHeatMap: don't show hidden attributes

---

Orange/tests/test_knn.py

kNN did not test nan class.
Test nan instances for two kNN models (k=1, k=3).

KNN: Test nan

---

Orange/data/dask.py
Orange/tests/test_dasktable.py
Orange/widgets/visualize/owbarplot.py
Orange/widgets/visualize/tests/test_owbarplot.py

[ENH] Bar plot supports dask tables

---

Orange/data/dask.py
Orange/widgets/visualize/owboxplot.py
Orange/widgets/visualize/tests/test_owboxplot.py

- samples table for attribute and group sorting
- BoxData handles nan values, and avoids calling compute multiple times
- dask tests prototype

[ENH] Box Plot: better dask support

---

Orange/widgets/data/tests/test_owselectbydataindex.py

[ENH] Select by Data Index: test with DaskTable

---

Orange/widgets/model/owlogisticregression.py
Orange/widgets/model/tests/test_owlogisticregression.py

Closes gh-5816
Add option for no regularization.

[ENH] owlogisticregression: Add option for no regularization

---

Orange/preprocess/discretize.py

Fixes #6099.
Normalize all-zero columns/rows to sum to 1

EntropyMDL._normalize: normalize zero cols to sum to 1

---

Orange/widgets/model/tests/test_owgradientboosting.py
Orange/widgets/utils/tests/concurrent_example.py

After https://github.com/biolab/orange-widget-base/pull/204 the test will start failing/segfaulting.
Fix a call too commit in concurrent_example
Fix OWWidget cleanup in tests.

[FIX] Fix tests cleanup

---

Orange/widgets/evaluate/owconfusionmatrix.py

Confusion Matrix: Enclose output options in a box

---

Orange/widgets/visualize/tests/test_ownomogram.py

Nomogram: Fix failing tests

---

Orange/data/util.py
Orange/data/variable.py
Orange/tests/test_data_util.py

Variable eq and hash: minor text fixes and tests

---

Orange/data/table.py

This code is likely obsolete. It was called just from a single function, so I refactored a single case that made sense there.

Remove table._rxc_ix

---

Orange/projection/cur.py
Orange/tests/test_cur.py
Orange/tests/test_knn.py

Not an issue
This is PR is to make use of NumPy APIs, `np.linalg.multi_dot` and `np.mean`. What do you think about the change.

Minor improvements in use of NumPy

---

Orange/widgets/data/owselectcolumns.py
Orange/widgets/data/tests/test_owselectcolumns.py
Orange/widgets/utils/listfilter.py

Fixes #6139.
Show variable counts or, when filtering, the number of shown and the total number of variables.

Select Columns: Show variable counts

---

Orange/widgets/unsupervised/owhierarchicalclustering.py

Translation of Hierarchical Clustering (https://github.com/biolab/orange-translations/pull/5) requires some changes in code.
- disentangle function arguments from dropdown lists items
- convert a string to f-string for plural in SI
- unify names

Hierarchical Clustering: adapt for translation

---

Orange/widgets/visualize/owboxplot.py

Box Plot had a mix of `.format` functions and f-strings.
And some stylistic issues.
- convert all strings to f-strings (where appropriate)
- fix typos

Small edits for Box Plot

---

Orange/widgets/gui.py

Partially fixes https://github.com/biolab/orange-widget-base/issues/212
List Views with proxy models need to be handled differently.
- listView: set source model instead of model for views with proxy model
- CallFrontListView: map selection from source model for views with proxy model
- CallBackListView: map selection to source model for views with proxy model

gui: Introduce a new filterable listview

---

Orange/widgets/data/owcolor.py
Orange/widgets/data/owdatasampler.py
Orange/widgets/data/owselectbydataindex.py
Orange/widgets/data/owselectcolumns.py
Orange/widgets/data/owselectrows.py
Orange/widgets/data/tests/test_owselectrows.py

This PR contains further patches needed to enable translation of widgets.
- Color: use function for plural form instead of `+ "s" * (len(dom.classvars) > 1)` :)

Patches for translations

---

Orange/widgets/data/owunique.py
conda-recipe/meta.yaml
requirements-gui.txt
tox.ini

Needs #6171 and [#214](https://github.com/biolab/orange-widget-base/pull/214)
Partially fixes [#212](https://github.com/biolab/orange-widget-base/issues/212)
- replace deprecated ListViewSearch with ListViewFilter

Unique: Introduce a new filterable listview

---

Orange/widgets/evaluate/owliftcurve.py
Orange/widgets/evaluate/tests/test_owliftcurve.py

Performance Curve: Compute area under the curve

---

Orange/widgets/data/owdatainfo.py

`"targets"` -> `"target"`; an -s` is add by `pl`, when necessary

Data Info: Fix wrong plural

---

Orange/widgets/data/owcsvimport.py

Fix deprecation warning for read_csv prefix argument (#6220)

---

Orange/data/dask.py
Orange/data/table.py
Orange/widgets/data/owtable.py

Removing some hacks from `Table` so that it won't (eventually) know anything about dask.

Remove Table.is_dask_table

---

conda-recipe/meta.yaml
requirements-core.txt
tox.ini

The `-oldest` tests are failing.

update oldest tests for dask

---

tox.ini

Trying to fix remaining CI issues.

Fix lint and documentation workflows

---

Orange/data/table.py
Orange/tests/test_table.py

`RowInstance` needlessly uses the original tables again for printouts. Needlessly because it already has all the data in `_x`, `_y`, `_metas`. @lanzagar noticed this while reviewing #6241.
Interestingly, the printouts were never tested. Perhaps remember any reason for this, @janezd?

RowInstance: use existing _x, _y, _metas for printout 

---

Orange/data/dask.py
Orange/data/table.py
Orange/tests/test_dasktable.py

When starting with dask we hacked RowInstance so that we could print dask tables
A nicer implementation.

Introduce DaskRowInstance

---

Orange/widgets/visualize/owviolinplot.py

Fixes #6269.
Change labels to "density dots" and "density lines", as proposed.

Violin Plot: Change checkbox labels for strips and rug

---

Orange/data/io.py
Orange/data/io_base.py
Orange/data/tests/test_io.py

Fixes #6180.
Change the order of columns and add some tests.

Tab, Csv and Xlsx writers: Reorder columns

---

Orange/widgets/visualize/ownomogram.py
Orange/widgets/visualize/tests/test_ownomogram.py

Nomogram: Reconstruct domain for BOW

---

Orange/data/table.py
Orange/tests/test_table.py

Tried to make from_table less convoluted. Its functionality is now split among multiple functions whose names are hopefully descriptive.
A refactor like this makes future dask extensions easy.
The last commit also fixed an old bug that I noticed because of improved testing.

Refactor Table.from_table for cleaner future extensions

---

Orange/distance/base.py
Orange/distance/distance.py
Orange/distance/tests/test_distance.py
Orange/tests/test_distances.py
Orange/widgets/unsupervised/owdistances.py
Orange/widgets/unsupervised/tests/test_owdistances.py
Orange/widgets/utils/distmatrixmodel.py

Distances: improved GUI

---

Orange/widgets/report/report.py
Orange/widgets/unsupervised/owlouvainclustering.py
Orange/widgets/unsupervised/owsom.py
Orange/widgets/utils/state_summary.py
Orange/widgets/utils/tests/test_state_summary.py
Orange/widgets/visualize/owfreeviz.py
Orange/widgets/visualize/owheatmap.py
Orange/widgets/visualize/owradviz.py
Orange/widgets/visualize/owruleviewer.py
Orange/widgets/visualize/utils/widget.py

Fix messages that can't be translated (mostly because of plural forms) and some other minor related corrections.

Fixes for translations

---

Orange/widgets/unsupervised/owhierarchicalclustering.py

Hierarchical Clustering: Change radio on interaction with spins

---

Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/tests/test_owlinearprojection.py
doc/visual-programming/source/widgets/visualize/linearprojection.md

Fixes #6321.
The reason why LDA was disabled has not been clearly explained.
Add informational message.

Linear Projection: Explain disabled LDA

---

Orange/widgets/utils/state_summary.py

Omit call to Table.X in state_summary

---

Orange/tests/sql/test_sql_table.py

sql tests leave table in database
drop the table

[FIX] Drop table after testing

---

Orange/data/sql/table.py
Orange/tests/sql/base.py
Orange/tests/sql/test_sql_table.py
Orange/widgets/data/owfile.py
Orange/widgets/utils/state_summary.py

`__get_nan_frequency' uses X and Y arrays, so SqlTables need an alternative implementation.

sqltable compute nan frequency

---

Orange/widgets/model/owknn.py

It could not be translated.
Modified code for better translation.

kNN: Modified code for better translation

---

Orange/widgets/tests/base.py
Orange/widgets/unsupervised/owhierarchicalclustering.py

Fixes #6360.
Set default linkage to Ward.

Hierarchical Clustering: Set default linkage to Ward

---

Orange/widgets/visualize/owboxplot.py

Some boxes are very small, and therefore difficult to select.
Besides, user may not be aware the selection is possible. 
- add lighter and bigger rect on hover
- enable selection with padding
- make selection rect line thicker

Box Plot: Emphasize selection

---

Orange/regression/base_regression.py

Fixes #6371.
Remove the confusing word "class" from "numeric class (...)".

Base regression: Improve error message

---

Orange/widgets/data/owdatasets.py

Fixes https://github.com/biolab/orange3/pull/6358#issuecomment-1463500026.
~~Requires https://github.com/biolab/orange-widget-base/pull/233.~~
Gray indicators (data set is downloaded but not active) are now hollow. Green indicators have gray pen.

Datasets: Nicer indicator

---

doc/visual-programming/source/widgets/evaluate/calibrationplot.md

Fixes #6376.
Mentions Predictions as widget that can precede Calibration Plot.

Calibration plot: Update documentation

---

doc/widgets.json

Documentation CI job fails due to recent widget keyword updates.
Update widget.json

[MNT] Update widget.json

---

Orange/widgets/__init__.py
Orange/widgets/data/owtable.py
Orange/widgets/data/tests/test_owtable.py
Orange/widgets/data/utils/models.py
Orange/widgets/data/utils/tablesummary.py
Orange/widgets/data/utils/tableview.py
Orange/widgets/data/utils/tests/test_tableview.py
Orange/widgets/obsolete/owtable.py
Orange/widgets/obsolete/tests/test_owtable.py
Orange/widgets/utils/tableview.py

Ref https://github.com/biolab/orange3/issues/6315
* Implement single input 'Data Table' widget.
* Obsolete old 'Data Table' implementation.
* Refactoring of common code where applicable.

[ENH] Single input data table widget

---

.github/workflows/test.yml
tox.ini

Run workfows in tests (except for the coverage test)

---

Orange/widgets/data/owselectrows.py

[ENH] Select Rows: Better label for purging unused values/features

---

Orange/widgets/model/owtree.py
Orange/widgets/unsupervised/owhierarchicalclustering.py
Orange/widgets/utils/__init__.py

Translation (si) problems with `.format`.
Minor f-string changes.

Minor f-string changes

---

Orange/widgets/evaluate/owpredictions.py
Orange/widgets/model/owknn.py
Orange/widgets/unsupervised/owsavedistances.py
Orange/widgets/visualize/owlineplot.py

Some stylistic changes (added dots `.` at the end of sentence and removed `:`), previously not changed stuff (metrics and weights options), added keyword (previously forgotten).

Minor fixes of texts in reports

---

Orange/widgets/model/owlogisticregression.py
Orange/widgets/model/owneuralnetwork.py
Orange/widgets/unsupervised/owpca.py

Couldn't translate (si) in some reports, because it was written as bool and not string.
Added already written function `bool_str` in some files.

Bool to string function: added where it was missing

---

Orange/widgets/data/owoutliers.py
Orange/widgets/data/tests/test_owoutliers.py

Missing possibility to translate metrics and then have them translated in report.
Added list of metrics names and reorganizing code for better report function.

Outliers: changes for report

---

Orange/widgets/data/oweditdomain.py
Orange/widgets/data/owtable.py
Orange/widgets/data/tests/test_owtable.py
Orange/widgets/utils/__init__.py

Ref: https://github.com/biolab/orange3/issues/6315
I.e. Data Table does not remember sorting.
Restore applied table sorting

[ENH] Data Table: Restore applied sorting

---

.github/workflows/check_pylint_diff.sh
pylintrc

Pylint shows warnings about deprecated options.

[MNT] PyLint: Resolve pylint 3.0 deprecations

---

Orange/widgets/data/owcontinuize.py

Mistake in string message.
do support -> do not support

Continuize: mistake in message string

---

.github/workflows/test.yml
tox.ini

Update CI tests to run with PyQt6 6.5 LTS

[MNT] CI: Test with PyQt6 6.5

---

Orange/widgets/data/owsql.py

Addendum to the pull request https://github.com/biolab/orange3/pull/6421
Made a message about the limit. Database table length and actual limit: MsSQL database

Add message Table length and limit for MsSQL

---

Orange/widgets/data/owcorrelations.py
Orange/widgets/data/tests/test_owcorrelations.py

Closes #6429.
Add a column "uncorrected p" to the output table.

Correlations: Add column with p-values

---

Orange/widgets/data/owconcatenate.py
Orange/widgets/data/tests/test_owconcatenate.py

Concatenate: Concatenate feature attributes

---

conda-recipe/meta.yaml
requirements-core.txt

When we updated the oldest version in tox.ini we forgot to update the actual requirement.

Raise numpy requirement to the one we actually test

---

Orange/tests/test_dasktable.py

Added a wrapper to help write tests.

Add wrapper for testing Tables and DaskTables in tandem

---

Orange/widgets/visualize/owdistributions.py
Orange/widgets/visualize/tests/test_owdistributions.py

Support Dask Tables in OWDistributions

OWDistributions: support for Dask Tables

---

Orange/widgets/visualize/owviolinplot.py
Orange/widgets/visualize/tests/test_owviolinplot.py

Support Dask Tables in OWViolinPlot

[ENH] OWViolinPlot: support for Dask Tables

---

Orange/canvas/config.py

Fixes https://github.com/biolab/orange3/issues/6522
* config: Replace and fix use of pkg_resources.parse_version

[FIX] config: Replace and fix use of pkg_resources.parse_version

---

Orange/widgets/evaluate/owtestandscore.py

Compute nans, number of values and number of features in training data.

Test & Score - fix data error conditions

---

Orange/widgets/visualize/owlinearprojection.py

Enable Number of attributes spin on initialize

---

Orange/widgets/data/tests/test_owtable.py
Orange/widgets/obsolete/tests/test_owtable.py
Orange/widgets/utils/tests/test_itemmodels.py
tox.ini

Because of pymssql constraints in tox dependencies, tests were not running with the database.
Releasing dependencies constraints.
Fixing database tests to pass successfully. Those tests were added meanwhile tests were not running on the database.

[CI] Test with pymssql

---

Orange/tests/test_naive_bayes.py

changes to test structure in preparation for merge with dask branch.

Refactor tests for NaiveBayesLearner

---

Orange/widgets/data/owdatasets.py
Orange/widgets/data/tests/test_owdatasets.py

Fixes #6574
This PR also takes care that old saved workflows also work (try with the ones attached to the issue).

[FIX] Datasets: save selected dataset platform independently

---

Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owscatterplotgraph.py
Orange/widgets/visualize/tests/test_owscatterplot.py
Orange/widgets/visualize/tests/test_owscatterplotbase.py
Orange/widgets/visualize/utils/widget.py

https://github.com/biolab/orange3/assets/15876321/6c3c6828-5520-462b-95c8-6f2eb7b980c8
https://github.com/biolab/orange3/assets/15876321/55a2468c-1670-4500-8989-a4630154114c
https://github.com/biolab/orange3/assets/15876321/c7186891-8329-4bca-8125-739333bb0dc7

[ENH] Scatterplot: interactive sampling for big datasets

---

Orange/widgets/visualize/owscatterplotgraph.py

[FIX] fix scatterplot interactive sampling

---

Orange/widgets/visualize/owlinearprojection.py
Orange/widgets/visualize/tests/test_owlinearprojection.py

Fixes #6502
Set `n_attrs` when initializing vizrank.

Linear Projection: Update vizrank Number of variables

---

Orange/widgets/data/oweditdomain.py

Fixes: https://github.com/biolab/orange3/issues/6600
Add filter to variable list

[ENH] oweditdomain: Add variable filter

---

Orange/base.py

I was playing with PLS for multi targets and got this one.

Fix an error message in Learner

---

Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/owscatterplotgraph.py
Orange/widgets/visualize/utils/widget.py

dask: enable subset selection for scatterplot

---

.github/workflows/translations.yml
i18n/si.jaml
requirements-dev.txt

- Add Slovenian translations
- Add a github workflow that reports missing and obsolete translations

Add Slovenian translations and a workflow for checking them

---

doc/visual-programming/source/loading-your-data/index.md

Missing information of how to deal with attributes of attributes.
Enhance documentation.

DOC: add information on attributes of attributes

---

Orange/widgets/data/owcorrelations.py
Orange/widgets/data/tests/test_owcorrelations.py

Correlations: Right-align the left variable

---

.github/workflows/translations.yml

test-translations was moved to biolab/orange-ci-cd
Change workflow to use biolab/orange-ci-cd/test-translations

[CI] Use test-translations workflow from common repository

---

README.md

Update conda create instructions with python version

---

Orange/widgets/utils/localization/__init__.py

Fixes #6753 
Replaced pl function with pl from orangecanvas.utils.localization

Fix localization for widgets

---

Orange/widgets/evaluate/owrocanalysis.py
Orange/widgets/evaluate/tests/test_owrocanalysis.py

Fixes #6719 
Set prior probability after reload

Fix setting prior probability in ROC

---

Orange/widgets/model/owpls.py

Rename `Data` output to `Data with Scores`.

PLS: Rename output Data

---

Orange/regression/pls.py

`PLSModel` should extend `LinearModel`.

PLS: PLSModel as LinearModel

---

Orange/widgets/data/owfeatureconstructor.py
Orange/widgets/data/tests/test_owfeatureconstructor.py

Fixes: https://github.com/biolab/orange3/issues/6639
Allow replacing existing variables

[ENH] Formula: Allow replacing existing variables

---

Orange/regression/pls.py
Orange/widgets/model/owpls.py
Orange/widgets/model/tests/test_owpls.py

PLS: Rename loadings, change U/T order

---

Orange/widgets/model/owpls.py
Orange/widgets/model/tests/test_owpls.py

- add check box for optional data scaling
- add intercepts to coefficients output
- add coeff/X_std to coefficients output

PLS: Scale data, add intercept, add coef/X_std 

---

requirements-core.txt

Limit xgboost version

---

Orange/data/io_base.py
Orange/data/tests/test_io_base.py

Fixes #6829
Consider attribute type in header flags.

CSVReader, ExcelReader: Consider attribute type in header flags

---

Orange/widgets/visualize/owboxplot.py

Fixes #6863, but I'm not sure I like it.
Add a label to the axis.

Boxplot: Add axis label

---

Orange/widgets/gui.py
requirements-gui.txt

Needs https://github.com/biolab/orange-widget-base/pull/274

[FIX] ListView: Fix selection

---

Orange/widgets/evaluate/tests/test_owtestandscore.py

Closes #6913.
Sklearn did it again.
Expect different result from sklearn >= 1.6.
It seems that we do not have to change anything else but this test? Behaviour of the Test and score widget seems to be the same as before.

Test and Score: Adapt test to change in sklearn

---

pylintrc

pylint: Disable too-many-positional-arguments

---

i18n/si/msgs.jaml

Missing translation for scoring sheet.
Add it.

Scoring Sheet: Slovenian translation

---

Orange/widgets/visualize/icons/interval-horizontal.svg
Orange/widgets/visualize/icons/interval-vertical.svg
Orange/widgets/visualize/owscatterplot.py
Orange/widgets/visualize/tests/test_owscatterplot.py
Orange/widgets/visualize/utils/error_bars_dialog.py
Orange/widgets/visualize/utils/tests/test_error_bars_dialog.py
i18n/si/msgs.jaml

Add Error Bars to points.
Closes #6428.
- introduce a dialog for variable selection
- add error bars to plot

[ENH] Scatter Plot: Error Bars

---

Orange/widgets/data/owcreateclass.py
Orange/widgets/data/tests/test_owcreateclass.py
i18n/si/msgs.jaml

Closes #6962.
Regular expressions and a bit of housekeeping (e.g. `__eq__` and `__hash__`).

Create Class: Add regular expressions

---

Orange/widgets/evaluate/owpredictions.py
Orange/widgets/evaluate/tests/test_owpredictions.py

Predictions: Hide missing target warning when not relevant

---

Orange/widgets/data/owneighbors.py
i18n/si/msgs.jaml

Output of neighbors should add "neighbors" to data table name.
Name the output table.

Neighbors: Add table name

---

Orange/widgets/unsupervised/owhierarchicalclustering.py

Fixes https://github.com/biolab/orange3/issues/7035
Fix combo box size hinting

owhierarchicalclustering: Fix combo box size hinting

---

Orange/widgets/visualize/owtreeviewer.py
Orange/widgets/visualize/tests/test_owtreegraph.py
Orange/widgets/visualize/utils/tree/treeadapter.py
i18n/si/msgs.jaml

Add a list of instance labels at the top of the node tooltips.
Added.

Tree viewer label

---

Orange/widgets/unsupervised/owdistances.py
Orange/widgets/unsupervised/tests/test_owdistances.py
i18n/si/msgs.jaml

Resolves #7053.
When the dimension of the matrix would exceed 20000x20000, an error is shown.

Distance: Limit the matrix dimension to 20000

---

Orange/canvas/config.py
i18n/si/msgs.jaml

Welcome screen includes long-defunct link to the survey.
Replace survey with Donate.

Replace Feedback with Donate
