biolab/orange3

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- pylintrc
https://github.com/biolab/orange3/pull/4425#discussion_r383130485
Prevent adding existing values through `add_value`.
Diff coverage is only 90 % due to uncovered code in tests. It's a won't fix, obviously.
> DiscreteVariable: Ignore existing values in add_value

- Orange/widgets/data/owcontinuize.py
- Orange/widgets/data/tests/test_owcontinuize.py
Resolves #4418.
The widget now provides the same normalizations as Preprocess/Normalize.
Option "zero_based" is removed. See discussion in #4418.
> [ENH] OWContinuize: Provide the same options as in Preprocess/Normalize

- Orange/widgets/data/owdatasampler.py
- Orange/widgets/data/tests/test_owdatasampler.py
> [ENH] OWDataSampler: Data info displayed in the status bar

- Orange/widgets/data/owdiscretize.py
- Orange/widgets/data/tests/test_owdiscretize.py
> [ENH] OWDiscretize: Data info displayed in the status bar

- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/tests/test_owselectrows.py
> [ENH] OWSelectRows: Data info displayed in the status bar

- Orange/widgets/data/owpivot.py
- Orange/widgets/data/tests/test_owpivot.py
> [ENH] OWPivotTable: Data info displayed in the status bar

- .github/workflows/cleanup_workflow.yml
- .github/workflows/doc_workflow.yml
- .github/workflows/lint_workflow.yml
- .github/workflows/linux_workflow.yml
- .github/workflows/macos_workflow.yml
- .github/workflows/windows_workflow.yml
- pyproject.toml
- tox.ini
**Issue**
Experimentally use Github actions as a new CI system. 
**Description of changes**
Run new CI alongside Travis and Appveyor to test how it behaves.
**Known downsides:**
Github action is not as feature reach as other systems because it was released not long ago. So I noticed that currently there is no officially supported way to cancel "stale" commits in a certain branch. Potentially this could be a problem. I hope there will soon be support for this. For now, we could use some third-party solutions that use Github public APIs (did not test those yet).
https://github.community/t5/GitHub-Actions/Github-actions-Cancel-redundant-builds/td-p/29549
To see running job go here: https://github.com/biolab/orange3/actions
**Linux job (ubuntu 18.04):**
- runs coverage for python 3.6 and 3.7. …
> [ENH] Use Github actions as a new CI system.

- .github/workflows/cleanup_workflow.yml
Run cleanup job when new commits are pushed to the pull request.
> [FIX] run cleanup job on PR push

- Orange/widgets/visualize/owvenndiagram.py
- Orange/widgets/visualize/tests/test_owvenndiagram.py
Venn diagram didn't handle properly tables where there are only metas and/or class vars.:
> [FiX] Venn diagram crashes on tables with no X

- Orange/widgets/utils/graphicstextlist.py
Ref: https://github.com/biolab/orange3/pull/4519#issuecomment-597621336
QGraphicsSimpleTextItem uses ceiled line heights in its bounding rect
estimation. Use integer metrics to layout the items.
> [FIX] graphicstextlist: Use integer font metrics again

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/preprocess/transformation.py
- Orange/tests/test_transformation.py
Renamed variables do not match their originals in widgets like Prediction.
Change `__eq__` and `__hash__` for `Variable` and `Identity`.
> Variable: Match two variables if they have the same compute_value=Identity

- Orange/widgets/data/owcolor.py
- Orange/widgets/data/tests/test_owcolor.py
> [ENH] OWColor: Data info displayed in the status bar

- Orange/widgets/data/owpurgedomain.py
- Orange/widgets/data/tests/test_owpurgedomain.py
> [ENH] OWPurgeDomain: Data info displayed in the status bar

- Orange/widgets/data/owsave.py
- Orange/widgets/data/tests/test_owsave.py
Input data info displayed in the status bar.
> [ENH] OWSave: Data info displayed in the status bar

- Orange/widgets/data/owdatainfo.py
- Orange/widgets/data/tests/test_owdatainfo.py
Input data info displayed in the status bar.
> [ENH] OWDataInfo: Data info displayed in the status bar

- Orange/widgets/data/owdatasets.py
- Orange/widgets/data/tests/test_owdatasets.py
> [ENH] OWDatasets: Data info displayed in the status bar

- Orange/widgets/data/tests/test_owpurgedomain.py
The Purge Domain widget is higher than the maximum allowed height and causing `test_minimum_size` to fail.
Temporarily skip `test_minimum_size`, until the widget is properly adapted.
> Purge Domain: Temporarily skip test

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
Fixes #4487.
- Adds `setZ` to `owscatterplotgraph.ScatterPlotItem`
- Computes z-values in `OWScatterPlotBase`
Review by commits.
> [ENH] Impose a sensible z-order to points in projections 

- Orange/widgets/utils/itemmodels.py
In Heatmap tab to the palette selection combo, change selection via up/down arrow keys.
```
File "/Users/aleserjavec/Documents/workspace/orange3/Orange/widgets/visualize/owheatmap.py", line 917, in update_color_schema
self.palette_name = self.color_cb.currentData().name
AttributeError: 'NoneType' object has no attribute 'name'
```
Disable 'category' items via model `flags`.
> [FIX] ContinuousPalettesModel: Disable 'category' items via `flags`

- Orange/widgets/data/owimpute.py
- Orange/widgets/data/tests/test_owimpute.py
> [ENH] OWImpute: Data info displayed in the status bar

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
Fixes #4503.
With many missing values, density plots get ugly. Missing values should be ignored in density plots -- if they are informative, they should be transformed to a "known unknown" value.
Add a mask in `update_density`.
> [ENH] Ignore missing values in density plots of projections

- Orange/widgets/utils/graphicslayoutitem.py
- Orange/widgets/utils/tests/test_graphicstextlist.py
Workflow:
File -> Select Rows -> Heatmap
* *File*: Load brown-selected 
* *Select rows*: choose *function*, *is on of*, *Proteas, Ribo*
* *Heatmap* Select *Split By: function* and check *Keep aspect ratio*
There is a extremely large empty space after Proteas section in the heatmap.
Fixes gh-4527
Do not attempt to scale empty widgets.
> heatmap: Fix aspect preserving scaling when a part of a 'split' is empty

- Orange/widgets/utils/state_summary.py
- Orange/widgets/utils/tests/test_state_summary.py
When info summary detail is show, the string ' (not shown)' appears in metas detail.
Remove the ' (not shown)'.
> format_summary_details: Remove '(not shown)' from metas

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
> [FIX] OWEditDomain: Clear editor when data is disconnected

- Orange/widgets/visualize/utils/heatmap.py
Ref: https://github.com/biolab/orange3/pull/4443#issuecomment-596371639
Ensure minimum width on the color annotations.
> [FIX] heatmap: Ensure minimim size for color annotations

- Orange/widgets/model/owloadmodel.py
- Orange/widgets/model/tests/test_owloadmodel.py
- doc/widgets.json
The second part of fix for #4464.
- Refactor the widget to use `RecentPathsWComboMixin`. The code is adapted from the Distance File widget.
- Add tests for the hitherto unchallenged widget.
> [ENH] Load Model: Use paths relative to workflow file

- Orange/data/variable.py
TimeVariable.parse was not thread safe and could mess up _ISO_FORMATS list losing some entries via duplication.
Make iteration order explicit, modified only via class instance assignment.
> [FIX] TimeVariable.parse: Do not modify _ISO_FORMATS

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Fixes #4436
Added an option to merge less frequent values:
- values that have less than n appearances
- keep only n different values
The current implementation of merging selected values moved in a new dialogue.
> [ENH] Edit Domain: Option to merge less frequent values

- Orange/widgets/data/tests/test_owsave.py
- Orange/widgets/utils/save/owsavebase.py
- Orange/widgets/utils/save/tests/test_owsavebase.py
- doc/visual-programming/source/widgets/data/save.md
- doc/visual-programming/source/widgets/model/savemodel.md
- doc/visual-programming/source/widgets/unsupervised/savedistancematrix.md
Fixes part of #4464 by storing paths relative to the workflow directory. 
Path is always relative to the workflow directory, and the saved file must be either in the same director or in its subtree. On loading the widget, auto-save is disabled unless a relative path is used to prevent auto saving to arbitrary locations when the workflow is loaded.
Implementation does not use `RecentPath` because it does not fit.
All core widgets for saving (Save, Save Distances, Save Model) are derived from this base class, so the patch should work for them, as well as for all properly written widgets in add-ons (Save Network).
I took care to keep the backward compatibility, though ... please check all potentially affected add-ons.
Unlike codecov, I believe that coverage is 100 %. At least judging by …
> [ENH] Save widgets: Store paths relative to workflow directory

- Orange/widgets/data/owpaintdata.py
- Orange/widgets/data/tests/test_owpaintdata.py
> [FIX] Paint Data: Send correct output after clicking Reset to Input

- Orange/widgets/utils/plot/owplotgui.py
- Orange/widgets/visualize/owscatterplot.py
- requirements-gui.txt
When many attributes it is difficult to find the specific attribute to show.
Adding a search to the combo box in the scatter plot. 
When this is merged I will start making the same changes in other widgets where required
> [ENH] Scatter Plot: Replace combo box with search combo box

- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/tests/test_owlineplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
- conda-recipe/meta.yaml
- requirements-gui.txt
Fixes #4336. This PR contains some minor fixes which make Orange compatible with pyqtgraphs develop branch.
Conda requirements are set to `~=0.10.0|~=0.11.0` to avoid pre-releases. Pip avoids them by default, therefore I set pip requirements to `>=0.10.0.
> Compatibility with pyqtgraph 0.11

- Orange/widgets/data/owoutliers.py
- Orange/widgets/data/tests/test_owoutliers.py
> [ENH] OWOutliers: Data info displayed in the status bar

- .github/workflows/cleanup_workflow.yml
- .github/workflows/linux_workflow.yml
- .github/workflows/miscellaneous_workflow.yml
- .github/workflows/windows_workflow.yml
- tox.ini
New workflow where we run Orange test suite against development versions of orange-canvas-core, orange-widget-base and pyqtgraph.
Build jobs now have a timeout limit (30 min).
> [ENH] Test against widget-base, orange-canvas and pyqtgraph development versions

- Orange/widgets/visualize/tests/test_owlinearprojection.py
- Orange/widgets/visualize/utils/widget.py
Fixes #4497 
Check for duplicates in original domain, not only in the selected one.
> [FIX] Detect duplicate names of variables in projections.

- Orange/widgets/data/tests/test_owcsvimport.py
Before, the widget sometimes processed data before a Mock was added, which caused the test to fail.
```
File "/home/runner/work/orange3/orange3/.tox/coverage/lib/python3.6/site-packages/Orange/widgets/data/tests/test_owcsvimport.py", line 125, in test_summary
format_summary_details(output))
File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/unittest/mock.py", line 805, in assert_called_with
raise AssertionError('Expected call: %s\nNot called' % (expected,))
AssertionError: Expected call: mock(3, '3 instances, 3 variables\nFeatures: 2 categorical\nTarget: —\nMetas: string')
Not called
```
> owcsvimport: fix output summary test

- Orange/widgets/utils/colorpalettes.py
- Orange/widgets/utils/tests/test_colorpalettes.py
Discrete variables save user-assigned colors in a list. This fails if the order of values changes.
This PR is intended to fix #4515.
Save colors in dictionaries, with values as keys.
> DiscreteVariable: Save color attributes with values

- Orange/widgets/utils/state_summary.py
- Orange/widgets/utils/tests/test_state_summary.py
Existing state_summary could not be used for widgets that have multiple inputs and has no information about missing values of input/output.
Information about missing values added.
`format_multiple_inputs` function added for formatting details string for widgets with multiple inputs.
> state_summary: Add multiple inputs function and missing values info

- Orange/widgets/evaluate/owtestlearners.py
- Orange/widgets/unsupervised/owsom.py
- Orange/widgets/visualize/owheatmap.py
`maximumContentsLength` parameter on ComboBox is deprecated and does not have an effect.
Removing all appearances of `maximumContentsLength` in Orange.
> Remove maximumContentsLength

- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_itemmodels.py
`PyTableModel.__setitem__` didn't properly signal the change: it emitted `dataChanged` for indices in the existing slice, which was empty for empty models.
0. In Time Series, pull https://github.com/biolab/orange3-timeseries/pull/80.
1. Take Datasets, load Philadelphia. 
2. Connect to Aggregate, change Aggregation function for one of the attributes.
3. Disconnect Aggregate
4. Connect again. Previous changes are gone (because they were not saved because the model didn't emit the signal properly).
Add proper signals.
> PyTableModel.__setitem__: properly emit signals

- .github/workflows/cleanup_workflow.yml
The cleanup workflow in Github actions sometimes fail.
Use personal access token of our biolab-helper Github account. Hopefully, this will work more consistent now.
> [FIX] Use new access token in cleanup workflow

- .github/workflows/cleanup_workflow.yml
It seems like repository secrets are not accessible in forks. 
Revert back to default token (secrets.GITHUB_TOKEN) and fail with success.
> ci: stop using custom token. Not accessible in forks. Fail with success.

- Orange/clustering/clustering.py
- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
- benchmark/base.py
- benchmark/bench_owkmeans.py
After Orange 3.21 we introduced quite a few performance-regressions to K-means, which became very slow for large data set. 
1. Preprocess data once. In master, data set is preprocessed separately for each number of clusters and then also when computing silhouettes. If used with from-to this caused too many in-memory copies of data. Which means crashes on big data due to memory usage. Note that sklearn's k-means makes another copy of the data.
2. Only compute approximate (sampled) silhouettes for big data. Fixes bug introduced in Orange 3.22. Compute them in worker threads.
3. Fix O(|features|^2) when creating centroids.
There is a further obvious improvement that I did not tackle in this PR: preprocessing in a worker thread. Now (=this branch, master, current release) the preprocessing …
> [FIX] K-means slowness

- Orange/widgets/visualize/ownomogram.py
On py3.8 nomogram crashed for logistic regression models with:
`TypeError: only integer scalar arrays can be converted to a scalar index`
Iterate over actual coefficient values (numbers) instead of rows of a ndarray (which are still ndarrays) to get a proper boolean value for `reverse`.
> [FIX] Nomogram: Fix crash on Python 3.8

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/tests/test_discretize.py
- benchmark/bench_save.py
- benchmark/bench_variable.py
Fixes #4555.
Print two more decimals when the format is not `%g` and the difference from the rounded values is outside numeric error.
> [ENH] Fix printing values with too few decimals

- Orange/widgets/data/owselectbydataindex.py
- Orange/widgets/data/tests/test_owselectbydataindex.py
> [ENH] SelectByDataIndex: data info displayed in the status bar

- Orange/widgets/data/owcreateclass.py
- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/owpivot.py
- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/owtranspose.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
Now when we have ComboBoxSearch available, it can be used where suitable. With this PR I am adding it to all widgets from the data section where a lot of options can be in the combo box - mostly where variables appear in combo boxes:
- Pivot table
- Select rows
- Merge data
- Transpose
- Create class
- Feature constructor
- Feature statistics
> [ENH] Searchable combo boxes in all data widgets

- Orange/canvas/config.py
- Orange/misc/environ.py
Ref gh-4264
* Read configured paths from a .cfg file. The cfg file can use and define install prefix relative paths
* Use the defined paths to override the default paths for storing widget and canvas settings.
> [ENH] Orange.misc.environ config

- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/visualize/utils/heatmap.py
Distance Map widget lacks a color map legend
Add a color map legend
> [ENH] Distance Map: Add a color map legend

- Orange/widgets/evaluate/owtestandscore.py
Annother stab at gh-4553
* Add cancelled tasks to dispose queue until final finished signal.
> [FIX] owtestandscore: Add cancelled tasks to dispose queue

- Orange/widgets/evaluate/tests/test_owtestandscore.py
From https://ci.appveyor.com/project/ales-erjavec/orange3-installers/builds/31860638/job/4gt7oa3p12c8eydj
```
FAIL: test_resort_on_data_change (Orange.widgets.evaluate.tests.test_owtestlearners.TestOWTestLearners)
File "C:\test-install\lib\site-packages\Orange\widgets\evaluate\tests\test_owtestlearners.py", line 288, in test_resort_on_data_change
self.assertEqual(header.sortIndicatorOrder(), Qt.AscendingOrder)
AssertionError: 1 != 0
```
Ensure the click is actually on a header section and not on an empty area.
> test_owtestlearners: Ensure a header section is clicked

- Orange/widgets/visualize/tests/test_owprojectionwidget.py
- Orange/widgets/visualize/utils/widget.py
Fixes #4515.
~~I don't like it because if a variable has 100 values, which are merged into 15, they will not use a better palette for 15 colors, but instead have a HSL-based palette with 15 hues out of 100. This rather defeats the purpose of merging.~~ No longer important after we implement #4581.
**To do:**
> [ENH] Projections keep colors after merging values

- Orange/widgets/data/owfeatureconstructor.py
Feature Constructor's height should be allowed to be decreased. It would make for nicer screenshots.
The problem was the height of the list view. Minimum height is now set to 50.
> Feature Constructor: Allow decreasing the height

- Orange/base.py
- Orange/classification/svm.py
- Orange/classification/tests/test_base.py
- Orange/tests/test_classification.py
- Support for all types of a sparse matrix in models `__call__`
- Make `data_to_model_domain` public
- Small clenup
This PR now includes essential changes that are required for the explain models widget and some cleanup. Other changes will be presented in separate PR.
@VesnaT and @lanzagar, your comments will be taken into account in the separate PR.
> [FIX] Classification models output correct shapes

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
New TimeVariable is initialized considering its parsing of string but actual data is converted by pandas.
This results in two issues:
* Edit Domain can convert more formats (like m/d/y) but the TimeVariable is not correctly initialized (have_date and have_time)
* pandas conversion is applied only when converting from Text but not when converting from Categorical.
Move pandas transformation into a separate function and apply it accordingly.
> [FIX] Edit Domain: Improve Text/Categorical to Time conversion

- Orange/widgets/data/owselectrows.py
`SelectRowsContextHandler.match` attempts to copy a dictionary, but falls a bit short. It just almost copies it.
Copy it.
> SelectRowsContextHandler: Copy attributes before updating

- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_itemmodels.py
`PyTableModel`'s constructor does not wrap an empty list but wraps another, new empty list instead.
Constructor has an argument `sequence` with default `None` and then wraps `sequence or []`. This is not OK when `sequence` is `[]`.
> [FIX] PyTableModel: Allow wrapping empty lists

- Orange/base.py
- Orange/data/tests/test_util.py
- Orange/data/util.py
- Orange/regression/linear.py
- Orange/tests/test_classification.py
- Orange/tests/test_sgd.py
- Orange/widgets/data/utils/histogram.py
SGD (same than some other models) outputs wrong shapes of probabilities when those retrieved from values (when skl_learner do not provide probabilities). The issue is caused by the one_hot encoding function that does not consider a number of values in the domain.
SGD (skl_learner) for some of the losses provides probabilities that are not used by Orange since it uses custom predict function.
- ` one_hot` function changed to accept `dim` parameter which tells what must be a resulting number of columns
- `__call__` function for model calls `one_hot` with a `dim` parameter that has a number of values in the domain as a shape.
- SGD model now uses a predict function from SklModel (which correctly retrieve probabilities from skl_learner) if possible.
> [FIX] Fix dimensionality of probabilities from values

- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/owsieve.py
- Orange/widgets/visualize/owsilhouetteplot.py
- Orange/widgets/visualize/owvenndiagram.py
Ref gh-4284
Fix an runtime error at process exit
Will require https://github.com/biolab/orange-widget-base/pull/37 to be merged and released
* Give QGraphicsScenes in VennDiagram and BoxPlot a parent the (OWWidget instance). Otherwise the scenes survive until process exit on PyQt 5.14.* 
* <s>Enable testing on PyQt5 5.14</s> (test still segfault with PyQt5 5.14 at process exit)
> [FIX] Give created QGraphicsScenes a parent

- Orange/widgets/data/owtable.py
Fix #4618 
`update_selection` added in `on_current_tab_changed` in order to change output each time the user changes tab.
> [FIX] Table: Send correct output when switching between tabs

- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/unsupervised/owsom.py
Now when we have ComboBoxSearch available, it can be used where suitable. With this PR I am adding it to all widgets from the unsupervised section where a lot of options can be in the combo box - mostly where variables appear in combo boxes:
- Distance Map
- Self-organizing map
> [ENH] Searchable combo boxes in all unsupervised widgets

- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/ownomogram.py
- Orange/widgets/visualize/owpythagorastree.py
- Orange/widgets/visualize/owpythagoreanforest.py
- Orange/widgets/visualize/owsieve.py
- Orange/widgets/visualize/owsilhouetteplot.py
- Orange/widgets/visualize/owtreeviewer.py
- Orange/widgets/visualize/tests/test_owpythagorastree.py
Now when we have ComboBoxSearch available, it can be used where suitable. With this PR I am adding it to all widgets from the visualize section where a lot of options can be in the combo box - mostly where variables (and values) appear in combo boxes:
- Tree viewer
- Distributions
- Mosaic
- Sieve diagram
- Heat Map
- Pythagorean Forest
- Pythagorean Tree
- Silhouette Plot
- Nomogram
> [ENH] Searchable combo boxes in all visualize widgets

- Orange/widgets/evaluate/owcalibrationplot.py
- Orange/widgets/evaluate/owliftcurve.py
- Orange/widgets/evaluate/owrocanalysis.py
- Orange/widgets/evaluate/owtestandscore.py
Now when we have ComboBoxSearch available, it can be used where suitable. With this PR I am adding it to all widgets from the evaluate section where a lot of options can be in the combo box - mostly where variables appear in combo boxes:
- Test and Score
- Roc analysis
- Lift curve
- Calibration plot
> [ENH] Searchable combo boxes in all evaluate widgets

- Orange/misc/server_embedder.py
When unit-tests run some server embedded logs are visible which should not be (they should be just debugging logs).
Made logs debug in the server embedder.
> Server embedder: change log level to debug

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Fixes #4599
Fixing merge data when missing values in data.
> [FIX] Edit Domain: Fix merge values when missing data

- Orange/widgets/utils/save/owsavebase.py
migrate_settting did not correctly handle the case when `filename` was None.
Change migrate_settting to correctly handle the case when `filename` was None.
> [FIX] Save base: Fix migrate_settings

- Orange/canvas/config.py
Update check was inconsistent. It was on by default until the preferences dialog was open. Opening the preferences dialog disabled it even when there was no user input.
> Fix update check setting to be True by default

- Orange/widgets/data/owcreateclass.py
- Orange/widgets/data/tests/test_owcreateclass.py
> [ENH] CreateClass: data info displayed in the status bar

- Orange/widgets/visualize/owlineplot.py
- Orange/widgets/visualize/tests/test_owlineplot.py
> [ENH] LinePlot: data info displayed in the status bar

- Orange/widgets/unsupervised/owsom.py
Fixes #4598.
SOM was incorrectly ported to new palettes: binned palette is indexed by numeric, continuous values that are put into bins by the palette. OWSOM does the binning itself and then used bin indices to index the palette.
Do not index the palette, index palette's `qcolors` array.
> [FIX] SOM: fix colors for numeric variables

- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
> [ENH] BoxPlot: data info displayed in the status bar

- Orange/widgets/utils/stickygraphicsview.py
- Orange/widgets/utils/tests/test_stickygraphicsview.py
'Heatmap' does not always hide the 'footer' shadow when it should. This seems to be style related. Observable with Fusion and Windows styles, on MacOS only if 'Show scroll bars' is 'Always' in System Preferences.
* Map the footer/header scene rect to viewport coords using float precision to avoid premature rounding.
* Accout for QRect.bottom() being one off.
Before
After
> [FIX] Heatmap: Sticky footer

- Orange/widgets/data/owfeatureconstructor.py
Feature Constructor sets the number of decimals.
Fixes #4639.
Set it to `None`, so `"%g"` is used for printing.
> Feature Constructor: Don't fix the number of decimals

- Orange/widgets/__init__.py
The old URL, docs.orange.biolab.si, has certificates managed by us, and sometimes something goes wrong and it becomes inaccessible. docs.biolab.si is managed by cloudflare.
> Help url: use docs.biolab.si instead of docs.orange.biolab.si

- Orange/widgets/data/owcolor.py
- Orange/widgets/data/tests/test_owcolor.py
Fixes #4666.
This stopped working when we removed `Variable.make`. The new variable can have a different name, hence it must use `compute_value` with `Identity`
> [FIX] Color: Fix renaming of variables

- Orange/widgets/data/owtransform.py
- Orange/widgets/data/tests/test_owtransform.py
> [ENH] ApplyDomain: data info displayed in the status bar

- Orange/widgets/visualize/owpythagorastree.py
- Orange/widgets/visualize/owpythagoreanforest.py
- Orange/widgets/visualize/tests/test_owpythagorastree.py
- Orange/widgets/visualize/tests/test_owpythagoreanforest.py
Pythagorantrees and Pythagorantrees use domain context handler without having any context variable with variables from the domain
DomainContextHandler replaced with ClassValuesContextHandler
Besides: Fixed warnings about setting index (for the selected item) when an empty combo box
> [FIX] Pythagorantrees/forests: change context handler

- Orange/widgets/data/owselectcolumns.py
Probably fixes #4691. If not, it still fixes a bug.
@Hrovatin, I see what's the problem, but can't replicate the circumstance where it would occur. I think it requires having some other stored contexts that do not refer to this particular data.
This PR does fix a potential bug and I suppose this is what you ran into, so please check whether it still happens after this. Even if it doesn't fix your issue, this change needs to be merged (if it's correct).
> SelectAttributesDomainContextHandler: Fix match when empty list

- Orange/widgets/data/owtable.py
- Orange/widgets/unsupervised/owpca.py
Fixes #4667.
`OWTable` declared, but didn't use, `DomainContextHandler`.
`OWPCA` used `DomainContextHandler`, but context matched any domain, hence the only context setting (`normalize`) was effectively non-context. I believe we discussed whether `normalize` has to be a context setting and I pushed for it, but I was probably wrong. See #4667  for more details.
> Remove DomainContextHandler from Table and PCA

- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/tests/test_owheatmap.py
- Orange/widgets/visualize/utils/heatmap.py
> [FIX] Heatmap: Split by missing values

- Orange/base.py
- Orange/classification/logistic_regression.py
- Orange/classification/outlier_detection.py
- Orange/classification/rules.py
- Orange/classification/svm.py
- Orange/tests/test_classification.py
- Orange/tests/test_logistic_regression.py
- Orange/tests/test_regression.py
- Logistic regression uses MajorityLearner when only one class in data, while SVM fails
- Softmax regression and NuSVM return the wrong shape of the probability matrix when one class missing in training data.
- Now when the `data_to_model_domain` was introduced in a Model class it is duplicated in outliers.
- Rules fail when empty list with new rules
- LogisticRegressionLearner does not use MajorityLearner when only one class in data.
- Softmax regression fixed to return the right shape of probability matrix (num cases x num classes in the domain)
- `NuSVM`: removed own predict function, adding missing dimensions is now handled by predict function on SklModel
- `data_to_model_domain` removed from outliers, added callbacks to  `data_to_model_domain` in Model class
- Rules fixed
> [FIX] Several fixes in learners/models

- Orange/widgets/data/owcolor.py
On my computer I got replicable segfaults if I:
- ran widget tests
- refocused my terminal window (our tests defocus it)
- when the color choosing box appears, clicked somewhere outside of it
Aims to fix segfaults mentioned in biolab/orange-widget-base#60
> Fix a segfault in owcolor widget tests

- Orange/widgets/visualize/owdistributions.py
> [FIX] Distributions widget's legend: Remove the square from sigma in normal and Rayleigh

- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/tests/test_owheatmap.py
- Orange/widgets/visualize/utils/heatmap.py
Fixes gh-4713
Handle all missing values for color annotations
> [FIX] owheatmap: Handle all N/A column for color annotation

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
- Fixes #4652. Report crashed since we removed info label in favour of summaries (my mistake!)
- Report also didn't have anything in the prediction columns. This was added.
- Report did not include the table with scores at the bottom. Added, too.
> [FIX] Fix report in Predictions

- Orange/preprocess/tests/test_discretize.py
Fixes (partially) #4608.
The test now translates local month names to English before asserting equality. I tested it by temporary switching to a different locale on my computer. @robertcv, please confirm it also works for you.
> test_discretize: Translate local month names to English in tests

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Resolves #4653.
Add a line edit. Placeholder shows the original name.
> [ENH] Edit Domain: Add an option to change the output table name

- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/tests/test_owselectrows.py
Allow partial matches (but request matching at least one attribute) and remove non-matching conditions.
In case of multiple matches, take the match with the most matching variables.
> [ENH] Select Rows: Allow partial context matches

- Orange/widgets/settings.py
- Orange/widgets/tests/test_domain_context_handler.py
Resolves #4664.
- DomainContextHandler now supports dictionaries whose keys are values (as used by Impute and Discretize) as context settings
- Empty matches (that is, domain contexts with no attributes to match) were promoted if they appeared first. Now they match, but with low priority.
> DomainContextHandler: support dictionaries as context settings

- Orange/widgets/visualize/pythagorastreeviewer.py
Fixes #4670. The `_target_class_index` was not resetting when new tree is built hence it was giving an error when the number of classes decreases.
Set `_target_class_index` to 0 in `clear()`.
> [FIX] PythagoreanTree: Fix crushing when number of classes decreases

- Orange/widgets/evaluate/owtestandscore.py
- Orange/widgets/evaluate/tests/test_owtestandscore.py
- Fixes #4734
- Currently, we only check that class_var has more than 1 class value, but it can happen that this condition is valid but there is only one class present in Y. I think it is better not to handle this case and show an error. The same is done by any model widget in Orange. Another argument to prevent this option is since learners do not support only one class in data. I hope my thinking is ok and that I didn't overlook any special case.
- Added error for no features
- Showing error when only one class in data - even class_var.values have more.
- Errors cleanup
> [FIX] Test and Score: Improve data errors

- Orange/widgets/data/tests/test_owsave.py
Readers support multiple possibly overlapping extensions, so saving with one Writer/Reader and opening just by the file name could possibly fail.
> Roundtrip writing tests: use the exact same Writer/Reader

- Orange/misc/server_embedder.py
Fixes https://github.com/biolab/orange3-imageanalytics/pull/176#issuecomment-615836576
It seems that QSettings().value() can return a TypeError when asking for machine-id in some rare cases. With this PR this error is caught.
> [FIX] Embedder: catch machine id setting type error

- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/utils/colorgradientselection.py
- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_colorgradientselection.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/tests/test_owheatmap.py
- Orange/widgets/visualize/utils/heatmap.py
Builds on gh-4593
Extract a color map selection combo box and thresholding sliders into a utility widget.
> [ENH] Gradient selection/parameters widget

- Orange/data/table.py
- Orange/data/tests/test_table.py
- Orange/widgets/settings.py
- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
Should fix #4663 (@VesnaT, please check; I can't replicate the issue myself)
- The widget saved selection as a list of instances of Filter.
- The widget still crashed a lot because it had a complicated, unmaintainable flow of function that called each other in a chain. To further complicate the issue, signals (such as changing of grouping or selection) were connected into different points within the chain. Consequently, events occurring withing the chain (such as clearing the scene) could cause reentering the chain, pushing the widget into inconsistent state.
- Selection is now a list of named tuples.
- Workflow is simplified.
- The amount of signals is reduced by using proxy models for sorting attributes and groups.
- Some signals are disconnected before some changes and then …
> BoxPlot: Fix saving of selections

- Orange/data/io.py
It can happen that the file name is too long due to the long suffix of the temp-file (the suffix is complete path joined together with _). It invokes File name too long: 'filename' error.
This is one of the issues causing that tests cannot run on cond-forge where file paths are really long https://github.com/conda-forge/orange3-feedstock/pull/77
Temfile does not get a complete name as a suffix but just an ending which makes sure that the correct reader reads the file.
I do not know what exactly is the reason that complete path was provided as a name so I hope that I didn't break anything.
> [FIX] UrlReader: shorten TempFile extension

- Orange/widgets/data/owcolor.py
- Orange/widgets/data/tests/test_owcolor.py
> [ENH] Color widget: Add reset button

- requirements-core.txt
Due to issues in https://github.com/biolab/orange3/pull/4768 we need to temporarily fix scikit version to <0.23
This is a temporary fix, that unittests will stop failing. I will modify it in https://github.com/biolab/orange3/pull/4768 when I see which version of scikit will fix issues.
> Temporary pin scikit-learn

- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
Supposedly fixes #4683.
Selection was stored as list of indices and wasn't used in context matching. This resulted in wrong selection when columns were reordered or even crashes when their number was reduced.
> [FIX] Feature Statistics: Fix wrong or even crashing selections

- codecov.yml
Attempt to fix constantly failing codecov checks. This will allow the coverage to drop by 1% before commit will show failed checks. We can set this to be even looser. 
But I don't know why is codecov reporting 0.03% decrease by this commit.
> codecov: add threshold to codecov commit status settings

- Orange/canvas/__main__.py
- requirements-gui.txt
Another crossover PR with canvas core!
This PR depends on https://github.com/biolab/orange-canvas-core/pull/79, hence raising the requirement, but is not necessary for merging the orange-canvas-core PR. Please check that the raised requirement is correct before merging.
I'll remove the NOMERGE tag when the canvas-core PR is released.
This applies to opening Orange without a file request (not specifying a file in args or double-clicking an `.ows` file).
Orange will check whether there were any crashed scratch (unsaved) workflows, asking the user if they wish to restore them.
I couldn't find any nice way to implement behavior on startup solely in canvas-core. Should we make a standard way for doing this? I could then also refactor some of the notifications code out of orange3.
> Load crashed scratch workflows on start

- Orange/widgets/visualize/owheatmap.py
Fixes gh-4766
Use 'is' instead of `__eq__` for column id comparisons.
> [FIX] owheatmap: Use 'is' instead of 'eq' for column id comparison

- Orange/evaluation/testing.py
- Orange/projection/manifold.py
- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
- Orange/widgets/evaluate/owconfusionmatrix.py
- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owconfusionmatrix.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
- Orange/widgets/evaluate/tests/test_owtestandscore.py
- Orange/widgets/tests/utils.py
- Orange/widgets/unsupervised/owdbscan.py
- Orange/widgets/unsupervised/owmanifoldlearning.py
- Orange/widgets/unsupervised/owpca.py
- Orange/widgets/unsupervised/tests/test_owdbscan.py
- Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py
- Orange/widgets/unsupervised/tests/test_owpca.py
- Orange/widgets/visualize/owsilhouetteplot.py
- Orange/widgets/visualize/owvenndiagram.py
- Orange/widgets/visualize/tests/test_owsilhouetteplot.py
> [FIX] Unique domain checks

- Orange/widgets/utils/colorpalettes.py
- Orange/widgets/utils/tests/test_colorpalettes.py
Fixes #4796 by cycling through colors of Glasbey palette. Nobody will notice that colors repeat.
> [FIX] Fix colors for discrete variables with >256 values

- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/tests/test_owselectrows.py
Select Rows stored values of discrete variables as indices. If the data changed so that values were reordered, it chose wrong values. If values were removed, it could crash with index out of range.
To reproduce, construct File -> Select Rows -> Select Rows. Load Iris, obviously.
- In the second Select Rows, choose the second Iris type.
- In the first Select Rows remove the first type and remove unused classes.
After this the second Select Rows will have selected the (originaly) third (now second) Iris type.
Alternatively:
- In the second Select Rows select the last Iris type
- In the first Select Rows remove one type and remove unused classes.
This will crash the second Select Rows widget.
- Use `DomainModel` for combos.
- Internally store variables as instances of `Variable`; context …
> [FIX] Select Rows: Fix incorrectly stored values in settings

- Orange/base.py
- Orange/projection/base.py
- requirements-core.txt
The new scikit-learn release yesterday caused orange learners to start failing:
- Learners parameters cannot be retrieved with learner.__init__.__code__ anymore since init is not called directly.
- KMeans is significantly slower: https://github.com/scikit-learn/scikit-learn/issues/17208
- Use `inspect.signature` instead of `__code__` to get parameters.
- I suggest temporary pin scikit-learn to != 0.23.0.
Should we release orange with these fixes after it is merged? Since I think we will not make a major release soon, people installing Orange with pip/conda will still get the newest version of scikit-learn. The same is for tests on add-ons. We just need a release for pip and condo. The installed do not need to be updated since it has packages packed together with orange.
> [FIX] Fix compatibility with scikit-learn 0.23

- Orange/classification/logistic_regression.py
- Orange/tests/test_evaluation_scoring.py
- Orange/tests/test_logistic_regression.py
- Orange/widgets/evaluate/tests/test_owtestandscore.py
- Orange/widgets/visualize/tests/test_ownomogram.py
In Orange, the defaults are `multi_class="ovr", solver="liblinear"`, while in [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/483cd3eaa/sklearn/linear_model/_logistic.py#L1251-L1255), these are `multi_class="auto", solver="lbfgs"`. `multi_class="auto"` correctly does OVR when doing binary classification, and switches to multinomial for multi class classification.
3.3.2017 - 3acf46a9f68f59c7f6ed54c5dd18b0405ac77b2b - parameters are first introduced
22.5.2019 - https://github.com/scikit-learn/scikit-learn/commit/c28ef9ef2a6980ecdb8a904c025fddf3bd477a7f - the default "multi_class" was changed from "warn" to "auto".
22.11.2018 - https://github.com/scikit-learn/scikit-learn/commit/7ed61a2 - the default was chagned from `multi_class="ovr", solver="liblinear"` to …
> logistic regression: sync defaults with scikit-learn

- Orange/data/io_base.py
- Orange/data/io_util.py
- Orange/data/tests/test_io.py
- Orange/misc/collections.py
- Orange/misc/tests/test_collections.py
- Orange/widgets/utils/domaineditor.py
Fixes https://github.com/biolab/orange3/issues/4778
When reading files sort values naturally (before alphabetical sort was used).
Natural sort sorts numbers inside string as numbers: `"sth2"` is before `"sth12"`
#4778 also said that `Ordered` is not used it is partially true. It sets the `ordered` flag in the DiscreteVariable. This flag tells whether values are ordered in the variable so that other widgets would respect that. I think values are in a current situation always ordered variable and all widgets respect this order (at least none expect FeatureStatistics care about this flag). So I think this flag can be removed. It is used only in the future statistics widget where if this flag is set the min and the max values are shown for the discrete variable.
In case we decide to leave …
> [ENH] Sort values naturally when reading files

- Orange/widgets/data/owcontinuize.py
- Orange/widgets/data/tests/test_owcontinuize.py
Fixes #4801. Probably caused by #4466.
Continuous treatments were identified in two ways, by enums `Continuize` and a newly introduced `Normalize`. However, `Continuize.Leave` does not match with `Normalize.Leave`, which was the source of problems.
All continuous treatments are now defined by `OWContinuize.Normalize`.
> [FIX] OWContinuize: Fix treatment of continuous features.

- Orange/widgets/data/owcorrelations.py
- Orange/widgets/data/tests/test_owcorrelations.py
The constant timeout can be problematic when called function needs more time than before. It happened when scikit k-means became slower #4768.
- `time.sleep` replaced with wait_unit_finished
- small fix in the widget: calling `setBlocking(False)` on start removed since it causes `wait_until_finished` to stop waiting.
> OWCorrelations - tests: replace time.sleep with wait_until_finished

- Orange/data/io.py
- Orange/tests/test_url_reader.py
In https://github.com/biolab/orange3/pull/4747 I overlooked the case when the file has two extensions (e.g. .tar.gz) - such files were not read since Orange parse them base on the extensions.
Fixed the case with two extensions.
> UrlReader: fix issue with double extensions

- Orange/base.py
- Orange/classification/base_classification.py
- Orange/classification/softmax_regression.py
- Orange/tests/test_classification.py
Fixes https://github.com/biolab/orange3/issues/4715
- Updated softmax regression
- Updated base model in parts where it is required for softmax regression to work correctly.
> [FIX] Fix and update Softmax regression learner

- Orange/widgets/data/owselectcolumns.py
- Orange/widgets/data/tests/test_owselectcolumns.py
Select Columns widget fails when getting data with additional attributes.
Fixed sorting of attributes that it does not compare Variables while sorting.
> [FIX] Select Columns: Fix attributes sorting

- Orange/widgets/visualize/owboxplot.py
When the discrete variable which is selected as a group in the box plot has values with items in the table labels are placed at the wrong positions and also sorting of the groups fails.
Fixed labels position and sorting.
> [FIX] OWBoxPlot: Fix wrong labels position and ordering for values with no items

- Orange/widgets/data/owcontinuize.py
- Orange/widgets/data/owimpute.py
- Orange/widgets/data/owpivot.py
- Orange/widgets/data/owpurgedomain.py
- Orange/widgets/data/tests/test_owpivot.py
- Orange/widgets/evaluate/owrocanalysis.py
Fixes (partially) #4608.
I changed the widgets roughly along the lines we set we discussing the issue, except for making ROC scrollable. If the user wants smaller graphs, (s)he can hide the control area, like in other widgets, IMHO.
> Rearrange a few widgets' UX to decrease their heights

- Orange/data/table.py
- Orange/widgets/utils/graphicsflowlayout.py
- Orange/widgets/utils/tests/test_graphicsflowlayout.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/tests/test_owheatmap.py
- Orange/widgets/visualize/utils/heatmap.py
- Orange/widgets/visualize/utils/tests/test_heatmap.py
Implements gh-4661
<s>Builds on: gh-4686 which should be merged before this.</s> (was merged)
Implement split by column, and column color annotations.
> [ENH] Heatmap: Split columns, Column annotations

- Orange/widgets/utils/colorgradientselection.py
- Orange/widgets/utils/tests/test_colorgradientselection.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/tests/test_owheatmap.py
- doc/visual-programming/source/widgets/visualize/heatmap.md
> [ENH] HeatMap: Allow setting the center when using diverging palettes

- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/tests/data-csv-types.tab
- Orange/widgets/data/tests/test_owcsvimport.py
Implements #4794
Implemented guessing strategy for CSV import which should match the strategy in `io_utils.guess_data_type`. 
This PR adds another iteration over the columns. For each column, it checks for the data type according to data. Complex operations here are:
- unique: Pandas unique is based on a hash table - less complex than Numpy's one
- casting times to date-time
@ales-erjavec is this kind of guessing acceptable or would decrease the performance of the widget too much?
- Tests
> [ENH] CSV Import: guess data types

- Orange/widgets/data/owdatasampler.py
- Orange/widgets/data/tests/test_owdatasampler.py
- doc/visual-programming/source/widgets/data/datasampler.md
Resolves #4802.
- Outputs are swapped.
- Option is renamed "Unused subset".
- Settings migration detects old setting, sets "compatibility_mode" flag (a schema-only seting). In this mode, the labels and outputs are as they were, and an information message is shown.
> Sample Data: Swap output signals for cross-validation

- Orange/data/variable.py
- Orange/widgets/data/owconcatenate.py
- Orange/widgets/data/tests/test_owconcatenate.py
Ref gh-4791.
`compute_value` is removed only when two variables with the same name are merged, that is, if a variable of the same type appears in the same part (attributes, classes, metas) with different compute_value. (The widget does not merge variables that appear in different parts.)
The option applies only in absence of primary table, so the related checkbox is in a box that is enabled only when there is no primary table.
> [ENH] Add an option to Concatenate to merge columns with different formulae

- Orange/widgets/data/owtable.py
- Orange/widgets/data/tests/test_owtable.py
> [ENH] owtable: output sorted data

- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/tests/test_owdistributions.py
Fixes #4813
Data output (annotated data) is always active. Before it was active only when something was selected. There was an explicit test that the output is empty after loading the data (no idea why).
Histogram data output now contains the bin and frequency data that is displayed in the widget. I don't know what was its purpose before (it was almost the same as Data).
> [ENH] Distributions: change Histogram Data output

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
May fix https://github.com/biolab/orange3/issues/4766#issuecomment-630162222 from #4766.
`__hash__` did not follow the same logic as `__eq__`. `__eq__` backtracked through identities while `__hash__` (kind of) made a single step.
I replaced the recursion in `__eq__` with a loop. I believe the new version to be equivalent to the old one. The old one exited earlier if `compute_value`'s matched, but with the same result as the new one.
`__hash__` then uses the same pieces of data as `__eq__`.
> [FIX] Variable: Fix cases when equal variables had different hashes

- requirements-gui.txt
Before release, we would like to make sure that the user has the newest versions of canvas-core and widget-base. In both packages are some changes which are important for orange to work properly.
Lift versions of both packages
> Lift minimum versions of orange-canvas-core and widget-base

- Orange/data/io_base.py
- Orange/data/pandas_compat.py
- Orange/data/tests/test_io_base.py
- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/preprocess/remove.py
- Orange/statistics/distribution.py
- Orange/tests/test_distribution.py
- Orange/tests/test_io.py
- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/tests/test_oweditdomain.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
- Orange/widgets/utils/tests/test_state_summary.py
As we already discussed in https://github.com/biolab/orange3/pull/4793 ordered attribute from the Discrete variable is not respected in most of the widgets anymore (except Feature Statistics), so it can be removed. Order defined in values tuple should be respected in any widget which needs order.
- The ordered attribute is deprecated and will stay so until 3.28.0 then it can be removed.
- Checkbox which sets ordered attribute in the edit domain is removed
- Feature statistic will never show min and max value for the discrete variable (before it happened in a case when ordered attribute was True)
- When saving data always write the order of values for discrete in the header (except in the case with only one value)
> Discrete variable: remove ordered attribute

- Orange/preprocess/normalize.py
- Orange/tests/test_normalize.py
- Orange/widgets/data/owfeaturestatistics.py
Data, when explicitly centered through the preprocess widget, would show up as having mean 1-e16 in the Feature Statistics widget (and potentially elsewhere). E.g. File (iris) > Preprocess (normalize to have mean=0) > Feature Statistics
1. Anything that is explicitly zero-centered will have `number_of_decimals=3`.
2. Sometimes things would show up as `-0.000` because of rounding a tiny negative number e.g. 1e-16 to zero. Zeros are now always positive.
This is impossible to do through the UI, but someone could potentially call `normalize` with an `sd>>1`, so all the values would be scaled to something tiny, and then `str_val` would print 0 for everything. Again, this cannot happen in Orange, because there is no way to manually specify the standard deviation. Let me know if you think this …
> [FIX] normalize: Adjust number_of_decimals after scaling

- Orange/clustering/louvain.py
- Orange/widgets/unsupervised/owlouvainclustering.py
As suggested by @pavlin-policar in a comment to #4855, cosine distance can be computed as Euclidean on row-normalized data, because we care only about ranking. This allows NearestNeighbours to use ball trees.
> [ENH] Louvain Clustering: Add cosine similarity

- Orange/widgets/data/owselectcolumns.py
- Orange/widgets/data/owselectrows.py
- Orange/widgets/settings.py
Remove `settings_to_widget`, which should be no longer necessary after https://github.com/biolab/orange-widget-base/pull/56
The change will break derived classes that override `decode_settings`. None, I suppose. (Except the two that this PR already fixes.)
> DomainContextHandler: Remove method settings_to_widget

- README-dev.md
- README.md
- README.pypi
- conda-recipe/meta.yaml
- requirements-gui.txt
- tox.ini
Older versions of PyQt5 cause problems like #4763. The solution is to set minimum supported version and thereby also setting PyQWt5 as the default binding for Qt (although Orange theoretically  also supports PyQt4, PySide and PySide2)
> Set PyQt5 as dependency

- Orange/tests/test_url_reader.py
This will allow us to drop a letsencrypt after a while.
> Change dataset url to get rid of double domain

- Orange/widgets/data/owcsvimport.py
- Orange/widgets/evaluate/owtestandscore.py
- Orange/widgets/utils/concurrent.py
- Orange/widgets/utils/itemmodels.py
Ref: gh-4615
Use PyOwned from https://github.com/biolab/orange-widget-base/pull/58 
<s>Requires https://github.com/biolab/orange-widget-base/pull/58 is merged and released.</s>
> [FIX] concurrent: Use a workaround for QObject wrapper deletion

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Resolves #4791 
#4831 added this specific option for Concatenate widget. This PR allows to remove `compute_value` through Edit Domain widget.
> [ENH] Edit Domain: Add option to unlink variable from source variable

- Orange/data/table.py
- Orange/data/tests/test_table.py
Fixes #4836.
`Table.__getitem__` and possibly also other methods only work with csr and csc matrices. Operations on other types of sparse matrices would be slow. Table `from_numpy` now convert sparse matrices that are not csr or csc to csr.
> Table.numpy: Convert non-csr/csc matrices to csr

- Orange/data/tests/test_util.py
- Orange/data/util.py
get_unique_names always returns names with all the same indices e.g. If we have an existing names: ['foo', 'baz', 'baz (1)'] and we want to add ['foo', 'baz'], new names will be ['foo (2)', 'baz (2)']. 
With this PR we are adding the possibility handle names which are independent. If the user sets `equal_numbers=False`. She/he will now get ['foo (1)', 'baz (2)'].
> [ENH] get_unique_names: Handle more independent names

- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/tests/test_owselectrows.py
Fixes #4676.
Calendar popup added when setting dates for TimeVariables filtering.
> SelectRows: Add calendar popup for TimeVariables

- .travis/install_orange.sh
- conda-recipe/meta.yaml
- requirements-core.txt
Bump minimum required version of openTSNE to 0.4.3. This also gets rid of numba. I removed the only mention of numba I was able to find in this repo. There are no mentions of numba in orange-canvas and orange-widget-base, so I think this was the only one.
> tsne: require opentsne>=0.4.3

- Orange/widgets/evaluate/owcalibrationplot.py
- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owlineplot.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owlineplot.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
- Orange/widgets/visualize/utils/component.py
- Orange/widgets/visualize/utils/customizableplot.py
- Orange/widgets/visualize/utils/plotutils.py
- Orange/widgets/visualize/utils/tests/test_plotutils.py
- Orange/widgets/visualize/utils/widget.py
Partially implements #4493
Needs https://github.com/biolab/orange-widget-base/pull/74
Enable setting label (axes, labels, legend) fonts, annotations and figure properties on projection widgets and some other widgets with plots
-  Scatterplot, MDS, tSNE, Radviz, Freeviz, LinearProjection
-  Line plot
- Calibration plot
> [ENH] Projection plots: Customizable plots

- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/tests/test_owselectrows.py
Fixes https://github.com/biolab/orange3/issues/4874
Change retrieval of values from the table for time variables. An additional test for other types of variables
> [FIX] Select Rows: fix fail when time variable in metas

- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/tests/test_owcsvimport.py
... with non C-locale number format.
Fixes gh-4913
Workaround for https://github.com/pandas-dev/pandas/issues/35365
Fallback to float_precision="high" with non C-locale number format.
> [FIX] owcsvimport: Handle decimal and thousand separator

- Orange/widgets/unsupervised/owmds.py
Fixes #4898 ...
... by calling `update_pairs` from `update_jittering` and ...
... but no tests because a test would be trivial (`update_pairs.assert_called`), or it would add yet another test that would run MDS and increase the running time, or it would require lots of mocking (and be trivial at the end, again).
> [FIX] MDS: Move lines when points are jittered

- Orange/widgets/visualize/owlineplot.py
In some cases tick texts retain after changing data on widget's input.
To reproduce:
- File(Iris) -> Select columns (Click Reset just in case) -> Line Plot (Check Mean)
- In Select column move all features to Available variables -> Ticks on Line plot retain
Remove tick texts on data change.
> [FIX] Line Plot: Reset axis ticks on data change

- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/tests/test_owcsvimport.py
CSVFileImport intends to but fails to read single member zip archive (raises a TypeError).
(e.g [precip.csv.zip](https://github.com/biolab/orange3/files/4971980/precip.csv.zip))
Fix a type error.
> [FIX] owcsvimport: Fix a type error in _open for zip archive

- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/tests/test_owcsvimport.py
Fixes https://github.com/biolab/orange3/issues/4858
Variable type guessing implemented in #4838 changed the behavior in old workflows since output data have different variable types.
Made CSV file Import backward compatible. With these changes, widget behaves like before when opening old workflows and have new behavior on newer workflows.
> CSV file Import: Backward compatibility

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
In some cases labels on projection widgets are deficiently shown.
To reproduce:
1. File (brown-selected) -> Preprocess -> MDS
2. MDS: Set `Label` to Genes
3. Preprocess (Select `Normalize Features`)
4. MDS: All labels are show
5. Preprocess (Remove normalizer)
6. MDS: Some labels (close to left and upper edge) are missing
Reset view before updating the labels.
> [FIX] OWScatterPlotBase: Reset view before labels update

- Orange/preprocess/discretize.py
- Orange/preprocess/impute.py
- Orange/preprocess/tests/test_discretize.py
- Orange/preprocess/tests/test_impute.py
- Orange/preprocess/tests/test_transformation.py
- Orange/preprocess/transformation.py
- Orange/widgets/data/owcontinuize.py
- Orange/widgets/data/owcreateclass.py
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_owcontinuize.py
- Orange/widgets/data/tests/test_owcreateclass.py
- Orange/widgets/data/tests/test_oweditdomain.py
Fixes #4895.
Equality of variables also checks equality of their `compute_value`. This can only work if `Transformation` and derived classes have `__eq__` and `__hash__`.
To fix #4895, it would suffice to change `oweditdomain.LookupMappingTransform`. The PR does it for other classes too, to prevent similar future mishaps.
Define `__eq__` and `__hash__` where needed.
Any add-ons that don't have will now misbehave in a different way -- before this, `__eq__` always returned `False`, even when transforms were the same. Now it will sometimes return `True` even though they may be different. This will happen if the class defines additional fields that are not checked by the base class.
The base class can neither check children's extra attributes, neither can it raise an exception (e.g. in a meta …
> [FIX] Edit Domain (and perhaps other widgets) could cause missing data later in the workflow

- conda-recipe/meta.yaml
- requirements-gui.txt
Scatterplot, for example, fails on master with orange-widget-base 4.6.0.
> Require orange-widget-base 4.7.0

- Orange/widgets/data/tests/test_owfile.py
There was a comment about tests that needed to be uncommented after https://github.com/biolab/orange-widget-base/pull/53 was released. Because we mostly reverted that PR with https://github.com/biolab/orange-widget-base/pull/64, I did the opposite of what the comment asked (I kept the old line).
> test_owfile: remove outdated comment in test_read_format

- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/tests/test_owheatmap.py
Heatmap widget raises an error if a dataset with exactly 1000 instances in on input and 'Clustering (opt. ordering) is selected for Row clustering.
```
-------------------------- AssertionError Exception ---------------------------
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/visualize/owheatmap.py", line 313, in _
self.set_row_clustering(cb.itemData(idx, ClusteringRole))
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/visualize/owheatmap.py", line 528, in set_row_clustering
self.__update_row_clustering()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/visualize/owheatmap.py", line 1089, in __update_row_clustering
self.update_heatmaps()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/visualize/owheatmap.py", …
```
> [FIX] Fix wrong assert in heatmap

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
> [ENH] Predictions: Allow selecting a subset of rows

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/tests/test_domain.py
Fixes (partially or completely) https://github.com/biolab/orange3/issues/4870
Problem is the following:
```
from Orange.data import Domain, DiscreteVariable
a = DiscreteVariable("Cluster", values=["c"])
var1 = a.renamed("Cluster x")
var2 = DiscreteVariable("Cluster", values=["a", "b"])
domain = Domain([], metas=[var1, var2])
print(var1 == var2)  # vars have completely different origin but still equal
>>> True
print(domain[var1]) # wrong attribute because of wrong comparison -> should return Cluster x
>>> Cluster
```
The problem is that `var1` and `var2` have equal hash (also `__eq__` returns True). This happens since `var1` have `compute_value` with identity pointing to the variable `a`; variables `a` and `var2` have same hash since they have the same name and same `compute_value` …
> [FIX] Fix variables equality and hashes 

- pyproject.toml
Fails to build on windows due to
https://github.com/pypa/setuptools/issues/2368
Force setuptools<50.0 during build
> pyproject.toml: Bound setuptools<50.0

- Orange/widgets/evaluate/owcalibrationplot.py
- Orange/widgets/tests/base.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owlineplot.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owlineplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
- Orange/widgets/visualize/utils/component.py
- Orange/widgets/visualize/utils/customizableplot.py
- Orange/widgets/visualize/utils/widget.py
Fixes #4934. To set Updater there had to be an active QApplication when Updater was imported, because default font settings were set as class attributes. This led to some segfaults in tests, which also created a QApplication instance. 
Default font properties were moved to the `__init__` of CommonParameterSetter. Also, parameter setters are now encapsulated by corresponding graphs and not mixed into them.
> Customizable plot: no need for QApplication at import

- Orange/widgets/tests/base.py
Some projection widgets (e.g. Annotator in Bioinformatics addon) have test data without Discrete variables so `attr_shape` cannot be set to any variable.
Set `attr_shape` to first Discrete variable in the domain if exists.
> [FIX] ProjectionWidgetMixinTests: set shape attribute only when discrete var available

- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/tests/test_owmergedata.py
Fixes https://github.com/biolab/orange3/issues/4870
Custom context didn't take into account that attr_pairs is schema_only. Handle cases when it is not present in context
> Merge data: fix errors in context

- Orange/widgets/data/owrank.py
Fixes #4948 in the opposite way.
PCA does not make much sense, unless you really know what you're doing. So no tooltip.
> Rank: Remove the tooltip about PCA

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
- Orange/widgets/tests/utils.py
Ref gh-4914
Enable merging by inline simultaneous multiple item rename.
* Re-enable inline multiple item edit 
* Move the functionality to the delegate an make it behave the same for edits triggered by platform edit key (Enter/Return or F2), is also available via context menu.
> [FIX] Edit Domain: Multiple item rename/merge

- Orange/data/table.py
- Orange/tests/test_table.py
For reverse slices row_indices in Table.from_table did not work properly. Also, that part of `from_table` was not properly tested, probably because of some optimizations that were added later.
Handcrafted (but wrong) measuring of slice length was replaced with calling standard methods.
> [FIX] Fix slicing in from_table

- Orange/widgets/utils/save/owsavebase.py
- Orange/widgets/utils/save/tests/test_owsavebase.py
Fixes #4932.
Change the limitations related to auto save and use of recent paths. In this PR
- auto_save is disabled if the path is absolute (previously, it was also disabled if the path was relative, but didn't exist);
- as before, auto save is also disabled if the recent path is relative and we don't have workflow_dir;
- absolute path is used only if it exists (like before; in the future, absolute paths will not be saved in .ows at all).
> Save widgets: Don't disable auto_save because of missing (relative) path

- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/tests/test_owdistributions.py
> [ENH] Distributions: Add sorting by category size

- Orange/classification/tree.py
- Orange/regression/tree.py
- doc/data-mining-library/source/reference/classification.rst
`build_tree()` had not reason to be public. It was misleading for users finding it in the documentation and thinking it prints the tree.
Also no documentation explaining how to print a tree.
Make `build_tree()` private.
Add an example of how to print a tree.
> TreeLearner: build_tree to private and add docs

- doc/visual-programming/source/loading-your-data/index.md
- doc/visual-programming/source/widgets/data/pythonscript.md
Changes such as https://docs.biolab.si//3/ -> https://docs.biolab.si/3/
This was caused by a wrong nginx rewrite rule from quite some time ago. Old and new links currently work.
> Fix ugly links in docs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
It seems that sometimes people just ignore the issue template and append their request to the end. This change declutters the templates and reworks the feature request template a bit.
- Turn all prompts into questions
- Add space in-between prompts
- Move additional information to HTML comments
> Tidy up issue templates

- Orange/canvas/__main__.py
A UUID was included only if send-statistics was enabled, but we now deem this unnecessary.
> Remove UUID from useragent string

- requirements-readthedocs.txt
Readthedocs was not building because of double dependencies since we added the PyQt5 dependency into requirements (a few months ago).
> [MNT] Fix readthedocs builds

- Orange/widgets/data/owdiscretize.py
Fixup for #4929
Default custom cut points are not restored due to an errant assignment in constructor
* Remove assign to 'default_cutpoints' in constructor
* Also enable/disable edit line entry to match the selected method.
> Fix discretize default cutpoints restore

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
If upon pressing 'New Issue', you pick "Open a blank issue.", it opened up the old issue template.
This PR changes that to an empty template with a comment linking to the two issue templates.
> Adjust default issue template, minor adjustments

- conda-recipe/meta.yaml
- requirements-gui.txt
As @markotoplak noticed here https://github.com/biolab/orange3/pull/4892 we forgot to increase the widget-base version.
Increasing the orange-widget-base version.
> Correct orange-widget-base version

- Orange/widgets/data/owcolor.py
- Orange/widgets/data/tests/test_owcolor.py
Resolves #4890.
I defined two file formats. One contains all changes done by the user, e.g.
```
{
"categorical": {
"gender": {
"renamed_values": {
"female": "women",
"male": "man"
}
},
"fasting blood sugar > 120": {
"rename": "fasting blood sugar is high",
"colors": {
"0": "#21FF06",
"1": "#996633"
}
},
"exerc ind ang": {
"colors": {
"0": "#46BEFA",
"1": "#996633"
}
},
"slope peak exc ST": {
"renamed_values": {},
"colors": {
"upsloping": "#FD8008",
"flat": "#ED462F",
"downsloping": "#AAF22B"
}
}
},
"numeric": {
"rest SBP": {
"colors": "linear_bgyw_20_98_c66"
},
"cholesterol": {
"colors": "diverging_bwr_40_95_c42"
},
}
}
```
When loading the file, it's content does not have to exactly match the domain: redundant variables/values are ignored, and data for variables that does not appear in …
> [ENH] OWColor: Saving and loading color schemata

- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/tests/test_owcsvimport.py
- Orange/widgets/utils/__init__.py
- Orange/widgets/utils/combobox.py
- Orange/widgets/utils/pathutils.py
- Orange/widgets/utils/settings.py
- Orange/widgets/utils/tests/test_combobox.py
- Orange/widgets/visualize/owheatmap.py
Fixes gh-4784
* Add a option to explicitly import a file relative to the workflow file (available only when saved).
* Add browse for missing functionality which preserves load options/parameters
> [ENH] CSV File Import: Add support for explicit workflow relative paths

- Orange/classification/simple_tree.py
- Orange/widgets/data/owimpute.py
Fixes #4982.
Model-based imputation uses `SimpleTree` with default arguments, which are 2 instances in a leaf and (essentially) unlimited depth. If data includes enough numeric attributes, this led to memory overflow.
Cut trees to 10 levels with minimum of 10 instances in leaves.
> Impute: Prevent overfitting (and exploding) in default model imputation

- Orange/regression/linear.py
- Orange/widgets/model/owlinearregression.py
Fixes #4954.
For polynomial regression in Educational add-on, I opened an issue there.
> [ENH] Add an option to set intercept in linear regression to 0

- Orange/widgets/data/owdiscretize.py
- Orange/widgets/data/owimpute.py
- Orange/widgets/unsupervised/owcorrespondence.py
- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/owlineplot.py
ListViews do not have a filter
Replacing listViews with a searchable list view
It must not merged before https://github.com/biolab/orange-widget-base is released.
> [ENH] Replace listViews with searchable listViews

- Orange/misc/server_embedder.py
Current timeout is too short and can cause an unexpected switch to local embedders. Since embedded send many images in parallel it can happen that embedded cannot handle all in 60 seconds. It usually happens when embedded pods are still turning on at the server or when more people use embedder at the same time.
Increasing timeout to 180 seconds.
> Embedders: increase a timeout

- Orange/widgets/evaluate/owtestandscore.py
- Orange/widgets/evaluate/tests/test_owtestandscore.py
The choice of k is arbitrary, so I suggest going with a lower one for faster default performance. @janezd?
> owtestandscore: Change default k (folds) from 10 to 5

- Orange/widgets/gui.py
- Orange/widgets/unsupervised/owlouvainclustering.py
- Orange/widgets/visualize/owpythagoreanforest.py
These imports cause problems in https://github.com/irgolic/orange-widget-base/tree/draggable-spinbox, and they aren't used in core neither in core Orange nor in "official" add-ons.
Removed typehints could be replaced by types from orangewidget.gui, but I don't think they add much value to the code anyway.
> Gui: Remove backward-compatibility imports

- Orange/widgets/visualize/ownomogram.py
#4998 was throwing this
```
File "/home/runner/work/orange3/orange3/.tox/coverage/lib/python3.7/site-packages/Orange/widgets/visualize/ownomogram.py", line 266, in brushColor
item.setBrush(value)
RuntimeError: wrapped C/C++ object of type DiscreteMovableDotItem has been deleted
```
This PR fixes it.
> [FIX] ownomogram: Fix wrapped C++ obj error

- Orange/widgets/utils/__init__.py
- Orange/widgets/visualize/icons/BarPlot.svg
- Orange/widgets/visualize/owbarplot.py
- Orange/widgets/visualize/tests/test_owbarplot.py
- Orange/widgets/visualize/utils/plotutils.py
Add Bar Plot widget.
I'll add the docs when the UI is approved.
> [ENH] Bar Plot: New widget

- Orange/widgets/data/owneighbors.py
- Orange/widgets/data/tests/test_owneighbors.py
OWNeighbors was limited to output distances only a subset of the input data. This change enables outputting distances to the full dataset.
For Orange Spectroscopy we would like to be able to compare the full dataset to a selected reference instance and visualize the distances to it.
The widget needs some work in my opinion, right now, every instance that is in an arbitrarily defined 1E-5 distance from the reference is excluded from the output. This should be handled dynamically based on the values of the data instances.
> [ENH] Neighbors: improve exclusion of references, checkbox to (un)limit output data

- Orange/widgets/data/owrank.py
- Orange/widgets/data/tests/test_owrank.py
Rank widget blocks Orange while computing on a larger dataset
Use `ConcurrentWidgetMixin` in the rank widget.
> [ENH] Rank widget computation in a separate thread

- conda-recipe/meta.yaml
- requirements-gui.txt
Solves https://github.com/biolab/orange3/issues/5016
Since fix for Qt is already prepared I think it will be available in the next version. This is why I propose just skipping version 5.15.1.
> Skip PyQt version 5.15.1 in requirements

- conda-recipe/meta.yaml
- requirements-gui.txt
Send line plot's send report fails with pyqtgraph==0.10.0.
```
File "/Users/primoz/miniconda3/envs/orange3/lib/python3.8/site-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 183, in boundingRect
px, py = self.pixelVectors()
File "/Users/primoz/miniconda3/envs/orange3/lib/python3.8/site-packages/pyqtgraph/graphicsItems/GraphicsItem.py", line 251, in pixelVectors
dti = fn.invertQTransform(dt)
File "/Users/primoz/miniconda3/envs/orange3/lib/python3.8/site-packages/pyqtgraph/functions.py", line 2199, in invertQTransform
inv = numpy.linalg.inv(arr)
File "<__array_function__ internals>", line 5, in inv
File "/Users/primoz/miniconda3/envs/orange3/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 546, in inv
ainv = _umath_linalg.inv(a, …
```
> [FIX] Fix line plot's send_report

- Orange/canvas/__main__.py
- requirements-gui.txt
This PR raises the orange-canvas-core requirement, it should only be merged after biolab/orange-canvas-core#125 is merged and released.
There's no rush to merge this, do it when there's some other reason to raise the requirement as well.
> Dont show welcome screen when loading crashed workflow

- Orange/canvas/mainwindow.py
To be merged after biolab/orange-canvas-core#128 is merged and released. 
Also note, this PR **doesn't raise the canvas-core requirement**. Merge #4980 first.
Aligns settings, as in the referenced PR.
> mainwindow: Vertically align notifications settings

- conda-recipe/meta.yaml
- requirements-doc.txt
- requirements-gui.txt
docutils is not directly used anywhere in Orange; it is used in orange-canvas-core.
> Remove docutils dependency

- Orange/widgets/model/owlogisticregression.py
After #4780 we often get warnings that the algorithm does not converge.
@ajdapretnar found this as a symptom in #5008, but the real problem there is elsewhere
Even `max_iter=1000` was too small for heart disease.
> Logistic regrssion widget: set max_iter to 10000

- Orange/widgets/data/owtable.py
- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/gui.py
- Orange/widgets/unsupervised/owdistancematrix.py
Horizontal scrolling is too fast when unsynthesized (e.g., using a trackpad).
When scrolling with Shift/Alt+Scroll, it scrolls a page at a time. This seems to be intentional behavior, but I don't like it.
Unsynthesized horizontal scrolling is made as fast as vertical.
Shift/Alt+Scroll will scroll in steps, just like vertical.
This applies the change to Data Table, Predictions and Distance Matrix. Is there any other widgets this should be applied to?
Should I move the mixin somewhere else, like a util file? I wasn't sure where to put it.
Off-topic, why is scrolling so slow in table view's with a larger amount of visible cells? Frames per second already drop with 80 cells visible! Is it reloading all of the visible cells on every scroll event? If fetching from the model is the bottleneck, …
> Slow horizontal scrolling in `QTableView`s

- Orange/widgets/visualize/owscatterplotgraph.py
The selection outline of scatterplot points was off-center by a pixel. This is due to the way pyqtgraph optimizes symbol drawing in `SymbolAtlas`, and also the reason for why points look like they jitter by a pixel when changing symbol size.
Before:
After:
Is there a reason for the pen to have width one larger than the set selection width? If this is necessary, it should be +2 to avoid the offset issue.
> owscatterplotgraph: Align point and selection outline

- conda-recipe/meta.yaml
- requirements-gui.txt
Even though the supported canvas-core version already requires anyqt>=0.0.11, I have also raised it here.
> Raise canvas-core version to fix some problems with Qt 5.9

- Orange/widgets/visualize/utils/customizableplot.py
- Orange/widgets/visualize/utils/tests/test_customizableplot.py
Fixes #5036.
It seems that the default font doesn't always exist.
Check whether the default font family exists. If not, just return a sorted list of families, without pushing the default to the top.
Also: tests for `available_font_family`.
> customizableplot.available_font_families: Fix for non-existent default family

- Orange/widgets/visualize/owscatterplot.py
- requirements-gui.txt
To be merged after biolab/orange-widget-base#97 is merged and released.
Controls like this one (which don't do anything unless another checkbox is checked) should be disabled when the other checkbox in question is disabled.
If there's any other controls like this, they should follow this styling. With the change in orange-widget-base, this should be easier to do.
> Disable scatterplot checkbox

- Orange/misc/collections.py
- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/tests/data-csv-types.tab
- Orange/widgets/data/tests/test_owcsvimport.py
File widget sorts discrete values naturally (implemented a few months ago) while CSV File Import doesn't. 
- Sort discrete values naturally when loading CSV file.
- Change type annotation for `natural_sorted` function.
> [FIX] CSV File Import: sort discrete values naturally

- doc/visual-programming/source/index.rst
- doc/widgets.json
A reference to the `barplot.md` is missing in the `index.rst`.
Add the reference to the`index.rst`.
> BarPlot: Docs - add reference to index.rst

- doc/visual-programming/source/widgets/data/sqltable.md
`psycopg2` need to be compiled in some cases e.g. MacOS.
The user can use (until he/she needs to use system libraries) `psycopg2-binary` instead `psycopg2` since it has already compiled wheels for many pythons-os combinations:
Citing `psycopg2`:
> You can also obtain a stand-alone package, not requiring a compiler or external libraries, by installing the psycopg2-binary package from PyPI
> Add psycopg2-binary as alternative to psycopg2 to docs

- Orange/widgets/visualize/utils/widget.py
File (Iris) -> OWScatterPlot
Enable 'Label only selection and subset', choose a label, choose some points
Change one of the attribute
The points will still be selected, but won't have labels displayed next to them. This is easily fixable by toggling the 'Label only selection and subset' option.
Retain labels next to selected points upon attribute change.
I'd love to write a test for this, but I'm honestly not sure where to do it. Could someone advise me?
> owdataprojectionwidget: Update labels on attr change

- Orange/widgets/tests/base.py
- Orange/widgets/utils/plot/owplotgui.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/utils/plotutils.py
A couple of minor changes to keyboard shortcuts and the accompanying tooltip for selection.
I removed the 'Warning: Selection is applied to unjittered data' tooltip, I appreciate the gesture in explaining that to the user, but it doesn't seem like something somebody would complain to us about. I don't see why someone would want (or expect) to have jittered data selected. (also I can't think of a way to make it look nice)
I also wanted to make the tooltip show on click+hold, but this seemed more difficult/messier to do. The problem was in resetting its visibility, other objects (e.g., ScatterPlotItem) eat the MousePressEvent.
@janezd, could you look into making the first group's color stay the same when adding a second group to selection?
> OWScatterPlotBase: Fixup selection UX

- Orange/widgets/unsupervised/owdistancematrix.py
- Orange/widgets/unsupervised/tests/test_owdistancematrix.py
Fixes #5061. 
Ignore coloring by attribute when attribute is string.
> Distance Matrix: Ignore coloring on string variables

- Orange/widgets/model/owsvm.py
While the scikit-learn's default is indeed 0, we use its defaults in lower-level code, but user-friendlier defaults in the widget. A default of 1 is user-friendlier (0 is generally useless).
> SVM: Set default coef0 in polynomial kernel to 1

- Orange/widgets/data/owselectcolumns.py
- Orange/widgets/settings.py
- Orange/widgets/visualize/tests/test_owlinearprojection.py
- Orange/widgets/visualize/tests/test_owradviz.py
Fixes #5051 to the extent (I believe) possible.
When the variables and metas are the same as those in some previous context, always use this context. Currently, the handler chooses the most recent context that has all relevant variables.
Some unexpected behaviour will remain, but I believe that it is impossible to define what has to happen in each particular instance becuase it depends on the combination of widgets and the user's intentions.
The fix introduces a slight bug: the context stores `variables` and `metas`, not `attributes, `class_vars` and `metas`. Two domains may be treated as the same although they're not, which could cause problems in any (mis)behaving(?) widgets. The problem is that this bug cannot be fixed without a backward incompatible change in data stored in domain …
> Reintroduce PerfectMatch for domain context matching

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Fixes gh-5067
Do not reset the edit state when merging.
> [FIX] Edit Domain: Preserve renames on categories merge

- requirements-gui.txt
- tox.ini
Failing future compatibility test due to changes in pyqtgraph master.
Many of our widgets, which use pyqtgraph, stop working properly on the master branch.
Remove pyqtgraph master testing in future compatibility.
Clamp required pyqtgraph version to 0.11.0.
It'd be good to see exactly what's wrong and get into contact with @pyqtgraph. Maybe they made a breaking change not caught by their tests, or we're using their libraries wrong, in which case they'd be able to advise us on what to do.
For the time being, this PR stops our builds from failing and prevents any future compatibility issues.
> Require pyqtgraph==0.11.0

- Orange/preprocess/impute.py
- Orange/tests/test_impute.py
`impute.Model` does not work on input dataset with `class_vars` since gh-3925 due to error raised by backmapping.
```python
import Orange
from Orange.modelling import ConstantLearner
from Orange.preprocess import impute
data = Orange.data.Table("brown-selected")
impvar = impute.Model(ConstantLearner())(data, data.domain[0])
impvar.compute_value(data)
```
```
File "<stdin>", line 1, in <module>
File "/Users/aleserjavec/Documents/workspace/orange3/Orange/preprocess/impute.py", line 175, in __call__
predicted = self.model(data[mask])
File "/Users/aleserjavec/Documents/workspace/orange3/Orange/base.py", line 437, in __call__
backmappers, n_values = self.get_backmappers(data)
File "/Users/aleserjavec/Documents/workspace/orange3/Orange/base.py", line 248, in …
```
> [FIX] impute: Remove class vars from input data for ReplaceUnknownsModel

- Orange/data/sql/backend/base.py
- Orange/data/sql/backend/mssql.py
- Orange/data/sql/backend/postgres.py
The database can have different collation settings (how to compare characters in the group by, distinct, ...). It has an impact on values we get when we retrieve all distinct values from column to create a discrete variable. If a collation is Latin it ignores utf8 characters, it can even be case insensitive. When creating variable we still want to have all possible values in the column since later when we retrieve actual data for a table (SELECT * FROM Table) we get values as they are (collation does not have an effect).
This PR implements a workaround for GROUP BY in cases when we want all values to create a variable.
> [FIX] SQL: Fix the issue with database collation setting when retrieving column values

- Orange/widgets/data/owpythonscript.py
- Orange/widgets/data/tests/test_owpythonscript.py
- Orange/widgets/tests/test_gui.py
- Orange/widgets/unsupervised/owsom.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
Ref gh-4952
* test_owpythonscript: Clear sys.last_{type,value,traceback} 
* test_gui: Remove widget in tearDown
*  test_owscatterplotbase: Reset Mock instances in class namespace 
* owpythonscript: Change shared_namespace to WeakKeyDictionary 
* owsom: Remove back ref to widget from closures in background thread
> [FIX] Tests: PyQt5 5.15 compatible cleanup

- Orange/widgets/data/owselectrows.py
- Orange/widgets/gui.py
https://github.com/biolab/orange-widget-base/pull/116 moves `CalendarWidgetWithTime` to orange-widget-base.
- Reexport the class in orange3 widget's gui.
- Use that class in `OWSelectRows`
> OWSelectRows: Move calendar widgets to gui

- Orange/data/sql/table.py
- Orange/tests/sql/test_filter.py
- Orange/tests/sql/test_sql_table.py
- SQL table places None where missing value for StringVariable. It should use '' (empty string) instead. It breaks merge data widget with does not expect `None` in the String variable.
- SQL table tests do not cleanup the database after testing.
- Removing `SqlRowInstance` and using `Instance` instead since it seems that Instance does the same in the `__init__` that `SqlRowInstance` used to do. It also correctly replaces None with the '' (empty string). Hope I didn't missee anything.
- Remove the database tables after testing
> [FIX] SqlTable use empty string instead of None for StringVariable

- Orange/widgets/data/tests/test_owcorrelations.py
test_owcorrelations fails with latest scikit-learn==0.24.0
```
File "D:\a\orange3\orange3\.tox\py\lib\site-packages\Orange\widgets\data\tests\test_owcorrelations.py", line 381, in test_get_clusters_of_attributes
[c.instances for c in clusters])
AssertionError: Lists differ: [[1, 2, 3, 4, 5, 6, 7], [8], [0]] != [[0], [1, 2, 3, 4, 5, 6, 7], [8]]
First differing element 0:
[1, 2, 3, 4, 5, 6, 7]
[0]
- [[1, 2, 3, 4, 5, 6, 7], [8], [0]]
?                            ---- -
+ [[0], [1, 2, 3, 4, 5, 6, 7], [8]]
?  +++++
```
Fix test.
> test_owcorrelations: Fix test for scikit-learn==0.24.0

- Orange/widgets/data/owpythonscript.py
- Orange/widgets/data/tests/test_owpythonscript.py
Python Script can lose inputs when multiple connections are made to an input from the same source node.
E.g.
In Pyhton Script
```python
>>> len(in_datas)
1
```
> [FIX] owpythonscript: Use signal id as is

- Orange/widgets/visualize/utils/scene.py
There is a small typo in Orange/widgets/visualize/utils/scene.py.
Should read `unnecessary` rather than `unncessary`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, unncessary -> unnecessary

- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
Feature Statistics raises error when displaying time variable with a formatted representation.
```
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owfeaturestatistics.py", line 575, in data
return roles[role]()
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owfeaturestatistics.py", line 540, in display
return render_value(self._center[row])
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owfeaturestatistics.py", line 518, in render_value
str_val = format_zeros(str_val)
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owfeaturestatistics.py", line 505, in format_zeros
if float(str_val) == 0:
ValueError: could not convert string to float: '2001-12-31 18:12:00'
```
The error however might not on show up on macOS in ErrorReporting …
> [FIX] Feature Statistics: Error in time variable display

- Orange/widgets/visualize/owdistributions.py
Fixes #5131.
- When bins represent unique values, their width now equals the width of the narrowest bin.
- Also, bins for unique values are now centered at the number.
> [ENH] Distribution: Show equal bar widths on unique-valued bins

- Orange/widgets/model/owadaboost.py
> [FIX] AdaBoost: Set maximum number of estimators to 10000

- Orange/widgets/visualize/owdistributions.py
OWDistributions looks out of place among other widgets with a main area, given its lack of a white background.
Unremove the white background.
> owdistributions: Add white background

- Orange/widgets/data/owimpute.py
* The default method changes to 'Fixed values' when the widget receives first data.
Steps:
* create an 'Impute' widget - do not connect it yet
* change the default method to say 'Average/Most frequent'
* connect it to 'File', the method changes to 'Fixed values'
* The date time setting is reset at widget creation and is not restored.
* Preserve the default method on set_data 
* Do not reset `default_time` in __init__
* Do not switch to 'Fixed values' by tabbing over controls
* Fix type hint comment location
> [FIX] OWImpute: Preserve default method setting

- Orange/widgets/data/owtable.py
- Orange/widgets/utils/headerview.py
- Orange/widgets/utils/tableview.py
- Orange/widgets/utils/tests/test_headerview.py
- Orange/widgets/utils/tests/test_tableview.py
Fixes gh-5162
Add a HeaderView class reimplementing QHeaderView.paintSection to avoid expensive calls to
QItemSelectionModel.isRowSelected, which traversed the whole model row/column when all items are selected.
> [FIX] Data Table: Fix freeze with large selections

- Orange/classification/tests/test_base.py
- Orange/classification/tests/test_calibration.py
Classification tests did not run.
> [FIX] Enable classification tests

- Orange/widgets/data/owpivot.py
- Orange/widgets/data/tests/test_owpivot.py
> [FIX] Pivot: Output date for group by table

- Orange/widgets/evaluate/owrocanalysis.py
- Orange/widgets/evaluate/tests/test_owrocanalysis.py
- Fixes #5119: The last point on the curve was not shown.
- Fixes the threshold shown at the bottom-left point (now set to 1; used to be 1 + the highest p in the data)
- Adds simpler preview data
- Shows ticks for actual FPR/TPR values, if there are <15 unique values
> [FIX] ROC shows all points, including the last

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
- Orange/widgets/visualize/utils/widget.py
Resolves #5109.
- No longer disable opacity in presence of data subset
- If opacity is low and subset is present, inform the user (s)he should increase opacity if (s)he can't see the subset
> [ENH] Projections: Allow transparent subset

- Orange/widgets/data/owdatasets.py
- Orange/widgets/data/tests/test_owdatasets.py
OWDataSets captures `self` in a closure executing in a worker thread.
See: https://github.com/biolab/orange3-single-cell/pull/381#issuecomment-752631590
Parameterize and move the functions out of the class.
> [FIX] owdataset: Do not capture self in closure

- Orange/widgets/data/owtable.py
- Orange/widgets/unsupervised/owdistancematrix.py
- Orange/widgets/utils/headerview.py
- Orange/widgets/utils/itemselectionmodel.py
- Orange/widgets/utils/tableview.py
- Orange/widgets/utils/tests/test_headerview.py
- Orange/widgets/utils/tests/test_itemselectionmodel.py
- Orange/widgets/utils/tests/test_tableview.py
Selecting all items (<kbd>ctrl+a</kbd>) in Distance Matrix freezes on large inputs (~4000x4000). 
Builds on top of gh-5164
Optimize SymmetricSelectionModel to operate on selection ranges not individual indices.
Refactor/extract BlockSelectionModel and SymmetricSelectionModel into utility module.
> [FIX] Distance Matrix: Fix freeze with large selections

- Orange/widgets/data/owpivot.py
- Orange/widgets/data/tests/test_owpivot.py
> [FIX] Pivot: Fix table for categorical variables

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
PR #5038 introduced jittering suspension with selection. It introduced a performance regression, because it needlessly updated point positions while the selection was being performed. For example, with 10000 data points, selection was lagging noticeably.
> [FIX] Fix performance regression in scatterplot

- Orange/widgets/data/owtable.py
- Orange/widgets/evaluate/owtestandscore.py
- Orange/widgets/evaluate/tests/test_owtestandscore.py
- Orange/widgets/evaluate/utils.py
- Orange/widgets/utils/tableview.py
Implements #5161
- move code from `owtable` to `utils`
- implement `copy selection` in `ScoreTable`
- implement `copy_to_clipboard` in `OWTestAndScore`
> [ENH] Test and Score: Copy selected rows to clipboard

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
- Orange/widgets/visualize/utils/widget.py
Fixes #5213
Projection widgets: ignore 'Other' category when showing color regions.
> [FIX] OWScatterPlotBase: Ignore 'Other' when showing color regions

- Orange/widgets/data/owpivot.py
- Orange/widgets/data/tests/test_owpivot.py
Fixes #5180 for TimeVariable.
Display TimeVariable values in time format.
> [FIX] Pivot: Display time variable in time format

- Orange/widgets/data/owimpute.py
- Orange/widgets/data/tests/test_owimpute.py
- Orange/widgets/utils/spinbox.py
- Orange/widgets/utils/tests/test_spinbox.py
The `default_numeric` parameter in OWImpute is stored as localized string and is hence not portable.
Steps to reproduce on macOS:
* Open System Preferences.app -> Language & Region -> Advanced..., Change decimal separator to '.'
* Open Orange, add *File* (load say brown-selected) -> *Impute* -> *Table*. In *Impute* set default fixed numeric value to '1.222', Observe that on the output the missing values are correctly replaced.
* Save the workflow and close Orange
* Open System Preferences.app -> Language & Region -> Advanced..., Change decimal separator to ','
* Open Orange and load the saved workflow
* Observe that in the *Impute* widget the numeric fixed value text is '1.222', and that on the output the missing values remain missing.
Replace use of QLineEdit with QDoubleSpin box for …
> [FIX] owimpute: Make `default_numeric` locale independant

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owlineplot.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
- Orange/widgets/visualize/utils/customizableplot.py
- Orange/widgets/visualize/utils/plotutils.py
- Orange/widgets/visualize/utils/tests/test_plotutils.py
- requirements-gui.txt
- tox.ini
Some tests were failing with the new release of pyqtgraph. Our tests currrently pass with 0.11.0 or 0.11.1 or master.
> Fix pyqtgraph==0.11.1 test failures

- Orange/widgets/visualize/utils/heatmap.py
- Orange/widgets/visualize/utils/plotutils.py
- Orange/widgets/visualize/utils/tests/test_plotutils.py
Before, heatmap was using pyqtgraph's monkey-patched methods, which they now removed (see pyqtgraph/pyqtgraph#1533). This PR uses proper PyQt5 interface.
> owheatmap: replace item.rotate with proper setTransform

- Orange/statistics/distribution.py
Variance used python loops, making it very inefficient. This change alone speeds-up normalization for test-case from #5219 by 10x. Issue #5219 will remain open because it is still possible to substantially improve normalization.
> [FIX] Distribution: vectorize variance, speeds up normalization

- Orange/widgets/data/owfeaturestatistics.py
Fixes #5173, currently moving controls on top, without box. Feel free to explore other options (bottom, box). :)
Noted from #5173: dilemma between consistency and practicality. Collapsability isn't an issue, IMHO, because the width of the splitter is already comparable to the space taken by these combo and button.
> Feature Statistics: Move controls to the top

- Orange/widgets/evaluate/owpredictions.py
Fixes #5074.
Continues from #5095, where the bug was hunted down by @erelin6613 (thanks!).
Check whether the source model exists before using it.
> [FIX] Predictions: Fix crash when clicking on empty left area

- Orange/data/table.py
- Orange/widgets/visualize/utils/widget.py
`numpy.bool` and `numpy.object` are [deprecated in Numpy 1.20](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations), which results in numerous warnings like
```
DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
`bool` and `np.bool` are equal in the sense that `bool == np.bool` returns `True`. Same for `object`.
> [MNT] Replace np.bool and np.object with bool and object

- Orange/widgets/data/owselectcolumns.py
- Orange/widgets/data/tests/test_owselectcolumns.py
Implements https://github.com/biolab/orange3/pull/5226#issuecomment-769967476
With this PR we rename the `Automatically select additional/new features` option to `Ignore new variables by default`
> Select columns: rename Select new features to Ignore new variables by default

- Orange/classification/base_classification.py
- Orange/classification/naive_bayes.py
- Orange/data/table.py
- Orange/preprocess/impute.py
- Orange/projection/radviz.py
- Orange/regression/base_regression.py
- Orange/regression/mean.py
- Orange/widgets/data/owcorrelations.py
- Orange/widgets/data/owpaintdata.py
- Orange/widgets/evaluate/owcalibrationplot.py
- Orange/widgets/evaluate/utils.py
- Orange/widgets/unsupervised/owsom.py
- Orange/widgets/visualize/owbarplot.py
- Orange/widgets/visualize/owlineplot.py
- Orange/widgets/visualize/owscatterplot.py
Many warnings and errors still used continuous for numeric and discrete for categorical variables.
Use correct wording.
The PR only replaces those parts of Orange that the user can see.
Docstrings still use old terms because they correspond to classes (DiscreteVariable, ContinuousVariable).
Documentation should be fixed separately since it needs to be updated anyway.
> Replace continuous with numeric and discrete with categorical

- Orange/tests/test_util.py
- Orange/util.py
`pkg_resources.load_entry_point` checks the requirements, which may fail due to inconsistent versions on developers' machines.
See, eg. https://github.com/biolab/orange3-network/issues/187
Introduce a new function (with intentionally different name to avoid the confusion), whose code is copied from `load_entry_point`, but skips the check.
> Add Orange.util.get_entry_point

- Orange/canvas/__main__.py
This is annoying because crash recovery isn't invoked when debugging/profiling.
(I use crash recovery while developing)
OASYS actually had this one figured out 4 years ago.
> __main__: Debug/Profile in PyCharm without error

- Orange/widgets/unsupervised/owmanifoldlearning.py
- Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py
I refreshed Manifold Learning as discussed on Tuesday on @irgolic's *Widgets showing show*.
Closes #5248.
- Use `QFormLayout` so that controls are properly aligned
- ~~Replace spins with line edits~~
- Put parameters in the same box as the combo for selecting the method. These are method's parameters, and they even change when the method is changed, so I think they must be in the same box.
- ~~I'm having second thoughts about removing the (now unnecessary) `_create_spin_parameter`. Do we keep it, just for the case we need it in the future? The method for check boxes is also still there.~~
- ~~Number of components is still a spin, because it probably makes sense. Keep it like this or turn it into line edit, too?~~
- I haven't tried whether the widget still works. :) It seems to pass the …
> OWManifoldLearning: Clean up UX

- Orange/widgets/unsupervised/owmanifoldlearning.py
Method `_create_check_parameter` is never used.
Remove the unused method `_create_check_parameter`.
> Manifold Learning: Remove unused code

- requirements-core.txt
```
orange-canvas 
File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
ws.require(__requires__)
File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 775, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (httpx 0.16.1 (/usr/lib/python3.9/site-packages), Requirement.parse('httpx~=0.14.0'), {'Orange3'})
During handling of the above exception, another exception occurred:
File "/usr/bin/orange-canvas", line 33, in <module> …
```
> httpx 0.16.0 now

- Orange/canvas/__main__.py
- requirements-gui.txt
https://github.com/biolab/orange-canvas-core/pull/153
https://github.com/biolab/orange-widget-base/pull/113
Decoupled from #5064.
This should be merged after https://github.com/biolab/orange-canvas-core/pull/157 is merged and released.
I considered running `execv` with the arguments Orange was run with previously (e.g., open a workflow), but it didn't seem much more intuitive than a feature that would automatically open the previously opened workflow on starting Orange (idea?).
> __main__: Restart on exit code 96

- Orange/widgets/evaluate/owtestandscore.py
- Orange/widgets/evaluate/tests/test_owtestandscore.py
Fixes #5028.
Besides, the stratification flag was actually ignored; cross-validation was always stratified.
- Warn for not stratifying when classes are discrete and the least populated has less than k instances.
- Inform when the flag is on, but data is about regression.
-
> [FIX] Test and Score: Fix stratification warnings

- Orange/widgets/data/owfile.py
- Orange/widgets/data/owselectcolumns.py
- Orange/widgets/utils/owlearnerwidget.py
- Orange/widgets/utils/tests/test_owlearnerwidget.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/tests/test_owfreeviz.py
Fixes #5144.
- File widget and Select Columns now show warnings when outputting data with multiple targets.
- Widgets that showed potentially misleading error (learners and freeviz) now explicitly state that the data has to have a **single** target.
> Multiple targets warning

- Orange/widgets/data/owdatasets.py
May resolve #5091.
After losing nerves and time with different methods that didn't work, I realized that we can pretty well know what the column widths should be, so I just fixed them. If we don't like the widths, we can modify them; but I see no reason to be fancier and resize to contents.
> Datasets: Make some columns narrower

- Orange/preprocess/discretize.py
- Orange/tests/test_discretize.py
Fixes #5253.
When differences between values are within rounding errors, computed consecutive thresholds may be the same.
`np.unique` now removes duplicated thresholds.
> Equal frequency discretization: Ensure unique thresholds

- Orange/widgets/utils/slidergraph.py
Fixes #5270. Twice.
First, it disables the auto scale button. This graph (used here and in dbscan) does not need it.
Second, it fixes the problem that caused the wrong scaling (lines going from -100 instead of from minimal x).
The second fix alone would also suffice, though auto scaling would still change the plot's y scale (I suppose that because of labels).
> SliderGraph: Disable auto scale button

- Orange/widgets/visualize/owviolinplot.py
- Orange/widgets/visualize/tests/test_owviolinplot.py
- doc/visual-programming/source/index.rst
- doc/visual-programming/source/widgets/visualize/violinplot.md
- doc/widgets.json
> [ENH] Violin Plot: New widget

- Orange/widgets/data/owcreateclass.py
- Orange/widgets/data/tests/test_owcreateclass.py
Repeated output class values created a DiscreteVariable with repeated values, which introduced problems later on. This PR fixes  Quasars/orange-spectroscopy#521.
This PR ensures that all values of the output DiscreteVariable are unique.
Allowing multiple match patterns for a single value seems like a useful feature (we get something similar to OR conditions). So I decided to support it rather than blocking it on input.
Patterns are still being matched in the same order as before, so this PR should not change any behavior that was valid before the fix. Also, the order of output values is kept.
> [FIX] Create Class: multiple patterns for a class value

- Orange/widgets/data/owrank.py
Fixes #5126.
`view.pressed(QModeIndex)` is not emitted when index is invalid. `selectionModel().selectionChanged(...)` would not distinguish between changes because of clicking and programmatic changes. Hence I overrode `mousePressEvent`, which, in super-super-class calls the `select`.
I want add tests because I don't know how to.
> [FIX] Rank: Switch to manual selection on deselect

- Orange/data/table.py
- Orange/data/tests/test_table.py
- Orange/tests/test_table.py
Resolves #5115.
Please comment the method names. 'join' reminds of SQL's join, but it's kind of correct.
> Table: Add methods 'join' and 'with_column'

- Orange/data/io.py
- Orange/widgets/data/owfile.py
- Orange/widgets/data/tests/test_owfile.py
Fixes #5127.
For xlsx, the initially selected sheet will be the one that is stored as active in the .xlsx. For Xls, it's gonna be the first sheet.
Active sheet should be stored as setting. This is however a bit complicated (see https://github.com/biolab/orange3/issues/4919#issuecomment-780749240)  and not worth fixing because it would have to be reimplemented anyway when fixing #4919.
Readers' constructors set `self.sheet`.
> File: Show correct initial sheet name

- Orange/widgets/data/owcreateinstance.py
- Orange/widgets/data/tests/test_owcreateinstance.py
Some change, almost certainly https://github.com/biolab/orange-widget-base/pull/130/files#diff-3a31caef28024e64070f007c502ff3e19b890e99719793535bc0cf9b88f9119dR394, broke tests for Create Instance by automagically inserting widgets into layout. (As I understood @ales-erjavec, this is exactly what he this morning warned against!)
Thruth be told, these tests were fragile and would also break at any other change in the UX.
Find buttons using `findChild` and `findChildren` rather than by their indices.
> CreateInstance: Fix test after changes in orange-widget-base

- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
Fixes #4973.
K-means fails when it tries to normalize sparse data. Normalization of sparse data is impossible (because it turns it dense). Hence the widget now doesn't normalize but shows a warning instead.
> KMeans: Don't try to normalize sparse data; show warning

- README.md
Fixes #5112.
Instructions on the web site do not use virtual environments. I'd prefer keeping them that way. If anything, we can redirect advanced users to instructions on github.
Besides adding `conda activate orange3` (and testing that all conda-based instructions work on my macOs), I rearranged the page
- I moved installation to the top, and emphasized the easy installation via installer.
- I replaced "steps" with a single code snippet to make it shorter, simpler, cleaner.
- I separated installation of `orange3` alone, and installation of `orange-widget-base`, `orange-canvas-core` and `orange3`, because only a few would be interested in the latter.
> README.md: Update installation instructions

- Orange/data/tests/test_io_util.py
- Orange/data/variable.py
Fixes #5196.
When guessing data types, Orange tests whether values can be converted to float. It didn't skip missing values and erroneously constructed categorical or string variables.
> guess_data_type: Ignore missing values for numeric variables

- Orange/base.py
- Orange/classification/tests/test_calibration.py
- Orange/tests/test_classification.py
Calibration models do not support passing NumPy data since their `data_to_model_domain` does not transform data correctly. It should take into account the base model domain. The error is that the calibration model stores the wrong domain. It first sets the base_learners domain, but it is then overwritten with the wrong (not preprocessed) domain.
This code snipet works with other models but not with callibrations:
```
data = Table('heart_disease')
base_learner = LogisticRegressionLearner()
model = CalibratedLearner(base_learner)(data)
model(model.data_to_model_domain(data).X)
```
The correction would support explain the model on calibration learner.
This PR fixes the base learner such that it does not overwrite the domain of models that already set it. It only set the domain for other …
> [FIX] Calibration model: Work with numpy data

- Orange/util.py
- Orange/widgets/data/owfile.py
- Orange/widgets/data/tests/test_owfile.py
Fixes #5008: the File widget seems to be the only widget that uses `catch_warnings` to record and show warnings.
The code is a bit of a hack: it's based on checking stack frames, and it patches an internal function in `warnings`. I don't see a way around any of that.
@markotoplak, can you check? If you confirm, I can add tests for context manager (besides the current tests for the widget).
There are two other potential problems
- `catch_warnings(record=True)` is used in some tests. If these are executed in parallel, they may "steal" each other's warnings.
- We call `catch_warnings()` to supress warnings in various places. Two are in code (`data.io` and the Rank widget), others in tests. This is not thread safe, but won't have very noticeable consequences.
- `catch_warnings()` is called in …
> Properly separate warnings by threads

- Orange/widgets/visualize/owbarplot.py
- Orange/widgets/visualize/tests/test_owbarplot.py
Fixes #5247
- introduce a group (bottom) axis
- separate groups by vertical line
> [ENH] Bar Plot: Improve "Group by" visualization

- Orange/data/__init__.py
- Orange/data/pandas_compat.py
- Orange/data/table.py
- Orange/data/tests/test_pandas.py
- Orange/tests/test_domain.py
- benchmark/bench_basic.py
Bases off #5190.
At the moment, our pandas solution copies the X, Y and meta numpy arrays into one contiguous array. It also sets its column `dtypes`. This is inefficient, and loses information like global row IDs, roles, variable info. 
The proposed solution is not an attempt at migration, but rather a seamless integration (both Orange and pandas operate on numpy arrays). This will be used in Python Script, but could also be leveraged by widget code.
Added a new `table_to_frames` method, which wraps the three existing numpy arrays into three DataFrames. This is near-instantaneous, as no copying occurs, it simply wraps the preexisting data structures. Also:
- it keeps global row index information by setting pandas indices in `_o1, _o2, _o3` format
- upon conversion back to table, it …
> Better pandas integration

- Orange/classification/tests/test_catgb_cls.py
- Orange/classification/tests/test_xgb_cls.py
- Orange/modelling/tests/test_catgb.py
- Orange/modelling/tests/test_xgb.py
- Orange/regression/tests/test_catgb_reg.py
- Orange/regression/tests/test_xgb_reg.py
- Orange/widgets/model/tests/test_owgradientboosting.py
Fixes #5297
- skip xgboost tests when `xgboost` is not installed
- skip catboost tests when `catboost` is not installed
> [FIX] Gradient Boosting: Skip tests if package not installed

- Orange/tests/test_table.py
Our `Table.copy()` is a deep copy (so `copy()` as in numpy, not `copy()` as usually used in Python), which Vesna kindly pointed out to me today. It relies on the `Table`'s constructor, which relies on `from_table`, which in turn relies on `from_table_rows`. Then, it does `ensure_copy` on the resulting table. Because `ensure_copy` does nothing for sparse matrices (it expects that selections in `from_table_rows` will create copies), I am putting a test on it if we ever change how `copy()`, `from_table()` or `from_table_rows()` behave.
Here are some fun ways to make a shallow or a deep copy of a Table.
```
from Orange.data import Table, Domain
"Some ways to do a DEEP copy"
"an obvious one, copy() as inspired by numpy"
iris = Table("iris")
iris2 = iris.copy()
iris.X[0, 0] = 42 …
```
> test_copy_sparse: improve test (try to change values)

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/tests/test_io.py
Ordered is deprecated and should be removed from constructor.
Remove 'ordered' argument from DiscreteVariable's constructor.
> DiscreteVariable: Remove 'ordered' argument

- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/unsupervised/owtsne.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/utils/widget.py
Projections widgets (`OWDataProjectionWidget` children) in add-ons look odd because they are missing `gui.rubber(self.controlArea)` line.
Apply general behaviour to base class.
> OWDataProjectionWidget: Move common code to base class

- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
Fixes #5305.
Normalize encoding of variable names as (seemingly) encoded by Python parser.
> Feature Constructor: Fix a problem with some unicode characters

- Orange/widgets/data/owfeaturestatistics.py
Fixes #5329. At least I think so. After tinkering with a number of glitches, I'm no longer sure what fixed it.
1. Put categorical variables at the bottom, because they are less interesting for this widget. But in particular, put them at the bottom when sorting by min and max, because these values don't apply to them.
2. Sorting by variable names didn't work because the result of `argsort` can be used for indexing, not sorting. However, calling `argsort` twice computes the inverse permutation.
3. Ensure stable order also when sorting by single number in descending order. The code used to invert the stable order. :)
4. Use ascending, not descending order by default.
These changes, at least the last one, breaks the tests. I'm gonna fix them when we confirm the changes.
> Feature Statistics: Fix sorting

- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/tests/test_owradviz.py
Fixes #5310
Implement `on_selection_changed` in RadvizVizRank.
> [FIX] Radviz VizRank: Implement on_selection_changed

- Orange/widgets/data/owfeaturestatistics.py
Resolves #5317.
- Add a column with median
- Show the most frequent value of discrete values in column with medians rather than with means,
- Rename column "Center" to "Mean"
> [ENH] Feature Statistics: Add median

- Orange/data/table.py
- Orange/data/util.py
- Orange/preprocess/transformation.py
- Orange/tests/test_data_util.py
- Orange/tests/test_table.py
- benchmark/bench_transform.py
Orange does domain transformations all the time. They are most obvious in Test Learner or Predict, if you pass test data in a different domain that the learner supports, but they are really everywhere. For example, all preprocessing is based on domain transformations.
Domain transformation can be chained. As currently implemented, each of these transformations is performed the whole data table and produces an intermediate table of the same length. All these intermediate tables count towards Orange's memory use.
This PR makes domain transformations work in batches. Essentially, space complexity of domain transformation, that used to be O(rows), will drop to O(1). In the future, we could easily add callbacks to from_table to get progress (some different PR). Also, different parts could be …
> [ENH] Domain transformations in batches for less memory use

- doc/visual-programming/source/widgets/evaluate/testandscore.md
Docs assumed that for all measures the higher value means a better model.
> Test and score docs: fix comparison interpretation

- Orange/widgets/data/owaggregatecolumns.py
- Orange/widgets/data/tests/test_owaggregatecolumns.py
Fixes #5348.
Remove selection before changing the model, not afterwards.
If you select something, change the data and change it back, the selection that you made on the first data is properly retrieved, but the list view is not properly updated and looks as if nothing was selected. 
This could easily be fixed within this PR (by adding `self.variables = self.variables` after `openContext`, I suppose), but I instead wrote a general fix for this. Check out https://github.com/biolab/orange-widget-base/pull/147 if you'd like to try (and, perhaps, review and merge both).
> Aggregate: Fix crash on changed domain

- Orange/widgets/data/owcorrelations.py
- Orange/widgets/data/owcreateclass.py
- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/owtranspose.py
- Orange/widgets/data/tests/test_owcreateclass.py
- Orange/widgets/data/tests/test_owmergedata.py
Fixes #5323, and the same in three other widgets.
This happenned because empty table is also considered false, hence `data and data.domain` resulted in passing a `Table` (instead of `None` or an instance of `Domain`) when the table was empty.
I'd prefer not to write tests for this, though they'd be trivial. I don't like tests that just replicate a bug. Of course one could say "but you should test that a widget does not crash on empty table", but then we should add such a test to all widgets, not just the four that happenned to have this problem.
> Fix calls to set_domain

- Orange/data/table.py
- Orange/tests/test_table.py
- Orange/widgets/data/owtranspose.py
- Orange/widgets/data/tests/test_owtranspose.py
Fixes #5300
Fixes #5298
- Offload work onto a separate thread
- Remove redundant instance from transposed table - one that is used for feature names
> [ENH] Transpose: Offload work onto separate thread, remove redundant instance

- Orange/preprocess/discretize.py
- Orange/preprocess/tests/test_discretize.py
- Orange/util.py
- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
- Orange/widgets/visualize/owscatterplotgraph.py
Fixes: gh-5345
`datetime.fromtimestamp` and `time.gmtime` raise OSError for negative timestamps on Windows.
Avoid use of `gmtime` and `fromtimestamp`
> [FIX] Errors when converting negative timestamps on Windows

- setup.py
The benchmark directory is installed/included as a top level package in the build wheel files.
```bash
$ zipinfo -s Orange3-3.28.0-cp36-cp36m-macosx_10_6_intel.whl | tail -n 17
-rw-r--r--  2.0 unx     5325 b- defN 12-Mar-21 08:48 Orange3-3.28.0.data/data/share/help/en/orange3/htmlhelp/widgets/visualize/venndiagram.html
-rw-r--r--  2.0 unx     4933 b- defN 12-Mar-21 08:48 Orange3-3.28.0.data/data/share/help/en/orange3/htmlhelp/widgets/visualize/violinplot.html
-rw-r--r--  2.0 unx        0 b- defN 12-Mar-21 08:45 benchmark/__init__.py
-rw-r--r--  2.0 unx     5042 b- defN 12-Mar-21 08:45 benchmark/base.py
-rw-r--r--  2.0 unx     2109 b- defN 12-Mar-21 08:45 benchmark/bench_basic.py
-rw-r--r--  2.0 unx     1507 b- defN 12-Mar-21 08:45 benchmark/bench_domain.py
-rw-r--r--  2.0 unx     1976 b- …
```
> [FIX] setup.py: Exclude benchmark directory from the install

- Orange/widgets/data/owpivot.py
The Pivot widget outputs are missing table names.
Assign input dataset name to output tables.
> [FIX] Pivot: Assign dataset name to output tables

- Orange/widgets/visualize/owlineplot.py
- Orange/widgets/visualize/tests/test_owlineplot.py
`Line Plot` crashes when input has a single instance and no `Group by` variable is selected.
To reproduce: File (housing) -> Data Table (select one row) -> Line Plot (crash)
> [FIX] Line Plot: Single instance input fix

- Orange/data/pandas_compat.py
- Orange/data/tests/test_pandas.py
`table_to_frame` is slow on large dataset. On dataset with shape (1M, 12) it took ~20s to transform dataframe to table. The reason for slow error is list comprehension used to find out if there is any nan in numeric column.
List comprehension is now replaced with NumPy functions.
Transformation on the previously mention dataset now takes ~0.6s
> [FIX] Speed-up slow table_to_frame

- Orange/widgets/visualize/owscatterplotgraph.py
Remove day from axis tick strings, when all hours belong to the same day.
> AxisItem: Remove day from tick string

- Orange/preprocess/discretize.py
- Orange/tests/test_discretize.py
Distributions widget sometimes put values at the edge in the wrong bin since bin borders are inaccurate on 17 or higher decimal place. Graph on dataset with a lot of values in the edge of bins:
In this example the bin -0.2<= x < 0 is empty even there are around 35 datapoints with value -0.2 in data. Also, some other bins include the values from the left and right of the interval.
With this PR I am fixing this error such that I round bin borders on a number of decimal places that are precise for the provided data type. Now I get the correct graph:
> Distributions: fix bins that values on the edge fall in the right bin

- Orange/widgets/evaluate/tests/test_owtestandscore.py
TestOWTestAndScore.test_no_pregressbar_warning is failing
```
ERROR: test_no_pregressbar_warning (Orange.widgets.evaluate.tests.test_owtestandscore.TestOWTestAndScore)
File "/home/runner/work/orange3/orange3/.tox/orange-released/lib/python3.8/site-packages/Orange/widgets/evaluate/tests/test_owtestandscore.py", line 479, in test_no_pregressbar_warning
assert not w
AssertionError
```
Remove TestOWTestAndScore.test_no_pregressbar_warning test.
> test_owtestandscore: Remove a test

- Orange/data/io.py
- Orange/tests/test_url_reader.py
The `OWFile` widget can't read files with special characters in their urls.
Fix UrlReader: 
- use `urllib.parse.quote` to encode the url
> [FIX] UrlReader: Support urls with special characters

- Orange/widgets/unsupervised/owdbscan.py
- Orange/widgets/unsupervised/tests/test_owdbscan.py
- Orange/widgets/utils/slidergraph.py
Fixes #5424
Add a check box to normalize/not normalize the input dataset. The check box is checked by default.
> DBSCAN: Optional normalization

- Orange/classification/outlier_detection.py
- Orange/classification/tests/test_outlier_detection.py
1. Outlier detection did not keep instance ids, so subsets did work with the `Data` output of OWOutliers.
2. Also, it was not thread-safe: multiple calls to  `_OutlierModel.__call__` could result in undefined behavior, because some caching was done at the object level.
To fix (1), I just used domain transformations instead of copying. To fix (2), I replaced object-level caching with `SharedComputeValue`.
> [FIX] Outlier detection: keep instance ids, make thread safe

- Orange/widgets/data/owcsvimport.py
- Orange/widgets/utils/textimport.py
Mark encoding errors in the CSV Import preview.
Related: gh-5436
Mark encoding errors in the preview.
> [ENH] textimport: Mark encoding errors in the preview

- Orange/data/pandas_compat.py
If column dtype is int variables `numbers_of_decimals` was still set to default value 3. 
Set `numbers_of_decimals` to 0 if dytpe is int.
> table_from_frame - set number of decimals to 0 if int

- Orange/data/instance.py
- Orange/tests/test_instance.py
`Instance` defines `__eq__`, thus it has to define `__hash__` to ensure that two equal objects have equal hashes.
However, `Instance` is mutable and shouldn't have `__hash__` at all. Thus it must raise `TypeError`.
If we some day decide to make `Instance` immutable, we can also implement a proper hash.
> Instance: Prevent hashing

- Orange/widgets/visualize/owboxplot.py
When one of q25 or 75 is zero boxes does not plot from median to q25 or q75.
Example
[bp.ows.zip](https://github.com/biolab/orange3/files/6496716/bp.ows.zip)
Fix plotting
> Box plot - fix boxes plotting

- requirements-core.txt
https://github.com/biolab/orange3/issues/5421
Version 0.6.0 implements handle saving annoy objects in the separate files while pickling so Orange will not crash anymore.
> Limit OpenTSNE to >=0.6.0

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Fixes #4385
- revert commit f19342036a92e6fb45281aeb856ca99847697aa3
- revert commit 87b67a895f2a96743228fd7d67db69145d10b7da
- apply commit 1418d09ec8630693e720b12c8d150b5c4a294ef3
> [ENH] Scatter plot: Bring discrete attributes functionality back

- requirements-gui.txt
Fixes https://github.com/biolab/orange3/issues/5460
Set minimal version of orange-widget-base to 4.13 since it is the first version that implements `itemdelegates`
> Set minimal version of orange-widget-base to 4.13

- Orange/canvas/run.py
- Orange/widgets/utils/save/owsavebase.py
[workflow.ows.zip](https://github.com/biolab/orange3/files/6560898/workflow.ows.zip)
```
python -m Orange.canvas.run workflow.ows
```
Does not save the results.tab file while 
```
python -m Orange.canvas.run ./workflow.ows
```
does
Similarly running `orange-canvas workflow.ows` resets the Save Data's auto_save setting (this one needs similar fix in orange-canvas-core)
* Always use absolute path for workflow base dir.
* Fix check for workflow base dir in OWSaveBase.
> [FIX] Save File when workflow basedir is an empty string

- Orange/widgets/unsupervised/owpca.py
Fixes #5464
Check for ```self._pca is not None and components == len(self._variance_ratio)``` prevented self.ncomponents to get updated when dragging vertical line. 
I think this check is unnecessary since the vertical line is bounded (on the x-axis) and will never exceed the number of computed components.
> [FIX] owpca: fix component selection when dragging selection line

- Orange/widgets/data/owcreateclass.py
- Orange/widgets/data/tests/test_owcreateclass.py
The implementation of `unique_in_order_mapping` was wrong. Now it is simplified, slower, but seemingly correct. I was trying to be too smart with the first implementation. Premature optimization is the root of all evil.
To reproduce the bug before this commit, try the following file
```
Filename
string
meta
A
B
C
```
with the following create class settings (keep the same order):
B: C
C: C
A: A
Fixes #5473
> [FIX] Create Class: fix incorrect value assignment

- Orange/widgets/utils/listfilter.py
Fixes gh-5471
On Qt >= 5.15.2 QListView.dropEvent depends on private state tracking
that is setup in startDrag. Since startDrag is overridden here and does
not dispatch to the base implementation, this causes items loss when
performing internal move.
Bypass QListView.dropEvent
> [FIX] listfilter: Bypass QListView.dropEvent

- Orange/data/pandas_compat.py
- Orange/data/tests/test_pandas.py
`table_from_frame` can be slow when transforming big dataframes
In this PR I identify places where transformation is slow and proposed changes.
I tested the speedup on the data frame with 6M rows and ~10 columns and succeeded in speedup the whole transformation from 16s to 2.5s.
> table_from_frame - speedups

- Orange/data/pandas_compat.py
- Orange/data/tests/test_pandas.py
`table_to_frame` fails when array (usually metas) have dtype=object and column holds numeric values. Look newly-added test.
Use `pd.isnull` instead of `np.isnan` which correctly handle columns with dtype=object.
> [FIX] table_to_frame - handle numeric columns with dtype=object

- Orange/tests/test_statistics.py
Tests on numpy 1.21 fail. `numpy.unique` changed behaviour in 1.21. Since 1.21 it treats all NaNs as the same value; before, it outputted as many NaNs as there were in the input array. The corresponding numpy issue: numpy/numpy#2111
Orange's `util.unique` function is a thin wrapper around `numpy.unique`. Because TestUnique used a test array with 2 NaNs the results were different depending on the version. Now they use a single NaN value.
> Adapt util.unique tests for numpy 1.21

- Orange/data/tests/test_pandas.py
pandas-dev/pandas#39263 is required for `test_contiguous_metas` to pass, the PR didn't make it into 1.3.0.
Raises `test_contiguous_metas` test requirement to 1.4.0.
> test_pandas: Raise contiguous metas test req

- Orange/widgets/data/owpivot.py
- Orange/widgets/data/tests/test_owpivot.py
> [FIX] Pivot: Handle empty data, metas only

- Orange/widgets/evaluate/tests/test_owtestandscore.py
This test was failing with a stack overflow here #5208. Not sure why it wasn't failing elsewhere, going through the trace on windows seems pretty sensible to fail.
Changes the mocked object to the correct one (thanks @janezd)
> test_owtestandscore: Fix testandscore test mock

- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/tests/test_owheatmap.py
Heatmap widget raises an assertion error when restoring selection and the input data has only a single column and columns clustering is selected.
```
-------------------------- AssertionError Exception ---------------------------
File "/Users/aleserjavec/Documents/workspace/orange-canvas/orangecanvas/scheme/signalmanager.py", line 1125, in __process_next
if self.__process_next_helper(use_max_active=True):
File "/Users/aleserjavec/Documents/workspace/orange-canvas/orangecanvas/scheme/signalmanager.py", line 1164, in __process_next_helper
self.process_node(selected_node)
File "/Users/aleserjavec/Documents/workspace/orange-canvas/orangecanvas/scheme/signalmanager.py", line 707, in process_node
self.send_to_node(node, signals_in)
File …
```
> [FIX] owheatmap: Fix assertion error when restoring selection

- Orange/canvas/mainwindow.py
- Orange/widgets/data/owfile.py
- Orange/widgets/data/owpythonscript.py
- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/data/tests/test_owpythonscript.py
- Orange/widgets/model/owloadmodel.py
- Orange/widgets/model/tests/test_owloadmodel.py
- Orange/widgets/unsupervised/owdistancefile.py
- Orange/widgets/unsupervised/tests/test_owdistancefile.py
- setup.py
- tox.ini
Closes biolab/orange3#4918
Uses:
* biolab/orange-canvas-core#143 
* biolab/orange-widget-base#106
Implements drop handlers for 'File', 'Load Model', 'Distance File' and 'Python Script' widgets.
> [ENH] Create nodes on canvas drag/drop

- Orange/statistics/contingency.py
- Orange/statistics/distribution.py
- Orange/tests/test_contingency.py
- Orange/tests/test_distribution.py
Fixes #5480.
Apparently and hopefully, the only classes derived from `np.ndarray` are `distribution.Discrete`, `distribution.Continuous`, `contingency.Discrete` and `DistMatrix`. The latter was already properly subclassed, so I did the same in the first three. 
`DistMatrix` also implements `__array_wrap__`; I haven't added it to the former three classes because it would change their behaviour and possible break some code without (much, if any) benefit.
> [FIX] Fix deepcopy and pickle for classes derived from `np.ndarray`

- Orange/canvas/__main__.py
- Orange/widgets/utils/plot/owpalette.py
- Sets 'darkMode' property in QApplication if 'dark' is specified in stylesheet. This can be easily queried globally elsewhere to color decisions
- Sets default pyqtgraph colors from QPalette on startup
Also removed the pyqtgraph colors set on owpalette.py import (please don't call code like this :x)
This is the first step toward proper dark mode support. Most (if not all) visualizations hardcode their colors. These hardcoded colors need to be removed and delegated to global default color settings (as set in 8f92990).
Note, this only works on startup, if the OS changes its color scheme (as Mac can upon sunset/sunrise), it won't update accordingly. But it's a first step.
This was transplanted from https://github.com/biolab/orange3/pull/5287. That PR will change into setting new default …
> __main__: Implement basic darkmode provisions

- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/unsupervised/tests/test_owhierarchicalclustering.py
Fixes #5467.
Add attribute "cluster" to variables when clustering by columns.
> [ENH] Hierarchical Clustering: Annotate variables with clusters

- Orange/widgets/unsupervised/owpca.py
- Orange/widgets/unsupervised/tests/test_owpca.py
Fixes two thirds of #5468.
To test before https://github.com/biolab/orange-widget-base/pull/162 is merged, change
```python
self.varmodel[:] = zip(self._variance_ratio[:self.maxp],
numpy.cumsum(self._variance_ratio))
```
to 
```python
self.varmodel.wrap(list(zip(self._variance_ratio[:self.maxp],
numpy.cumsum(self._variance_ratio))))
```
1. Variances are added as attributes of variables, and as extra meta columns in the components output.
2. The table with variances is shown in control area and can be used as the third mean to select components. Clicking a row selects all components up to that row. (Selecting arbitrary rows is not possible: the widget's code does not support it; interactions the other two controls would be weird; this is not typical for PCA; for atypical uses, there's …
> [ENH] PCA: Output variance of components

- Orange/widgets/data/owpythonscript.py
In the new OWPythonscript editor that was just merged #5208, the return statement isn't indented.
Fixed a whoops forgot to add parentheses bug. :x
> OWPythonscript: Fix return statement indentation

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
Projection widgets animate point resize. The animation should last half a second.
Resize points within approximately half a second.
> OWScatterPlotBase: Animate point resize for half a second

- Orange/widgets/evaluate/owrocanalysis.py
ROC Analysis raises 
```
---------------------------- ValueError Exception -----------------------------
File "/Users/aleserjavec/Documents/workspace/orange3/Orange/widgets/evaluate/owrocanalysis.py", line 674, in _on_mouse_moved
if pts:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
on mouse hover when two (or more) hovered threshold points are close to each other in viewport.
E.g on Ionospere with logistic regression:
run the mouse cursor over the curve on a small sized ROC Analysis plot.
* Fix test for non empty points array
> [FIX] owrocanalysis: Fix test for non empty points array

- Orange/data/util.py
- Orange/preprocess/fss.py
- Orange/projection/freeviz.py
- Orange/widgets/data/owdatasampler.py
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/owpaintdata.py
- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/visualize/utils/lac.py
`np.int`, `np.float` and `np.bool` are deprecated and should be replaced with `int`, `float` and `bool` to avoid warnings (https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).
~~Besides those, I also replaced most `int64` and `float64`, which are the same as `int` and `float` on supported platforms.~~
Coverage tests don't and won't pass: the missed lines were already missed before.
> [MNT] Replace deprecated numpy type aliases

- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/tests/test_owmergedata.py
Fixes #5285.
As proposed, adapt the code from Create Class.
~~The widget shows empty/disabled buttons, that is, grayed-out squares instead of hiding the button completely. I find it kind-of nice, but can change it.~~
I have also put the + button in a separate row. This looks nicer, though it uses some extra space; the widget is small, anyway. (The previous design was, I guess, OK because the buttons looked more like labels that are shown or hidden. With buttons, it is not.)
> Merge Data: Embiggen + and x buttons

- Orange/widgets/data/owsave.py
- Orange/widgets/data/tests/test_owsave.py
- Orange/widgets/utils/save/owsavebase.py
- Orange/widgets/utils/save/tests/test_owsavebase.py
Fixes #5512.
The situtation can occur if workflow is saved with Orange that has add-ons with additional file formats and then opened in Orange without that add-on, or if support for some format is dropped (as was the case with old Excel, which caused #5512).
Widgets for saving are derived from `OWSaveBase`, which fails in property `writer`. This PR changes it to return `None` for filters that are not in the list. The only place where `writer` is used is `do_save`, which in this case now indicates an error.
The error is cleared at the only place that changes `self.filter`: if the user selects a new file name, the filter cannot be invalid.
Derived widgets need changes only if they use `self.writer`, in which case they must check that it is not `None`. Among the three core widgets, only …
> [FIX] Prevent crash when saving in unsupported format

- requirements-gui.txt
- requirements-pyqt.txt
- setup.py
The PyQt5 dependency conflicts with conda, where the same package is called pyqt. Installing pyqt5 inside a conda environment that already contains pyqt may be catastrophic. Removing the dependency makes pip installation into conda environments safer; such installations frequently occur when users install an add-on not available in the conda repos that requires a newer version of Orange. The same issue appears when Anaconda users try to update Orange with the Add-on dialog box. Or when someone who installed Orange with conda downloads the master branch and does `pip install -e .`.
Orange added the PyQt5 dependency about a year ago to make pip installations friendlier. Unfortunately, that caused more problems than it fixed. 
This is an alternative to #5566.
This commit modifies setup.py to …
> [FIX] setup.py: do not overwrite conda's PyQt5

- conda-recipe/meta.yaml
- requirements-gui.txt
Conda recipe did not pass tests anymore. While fixing it, I noticed that an explicitly imported library is missing in the dependencies.
> Add the pygments dependency, update conda-recipe

- Orange/widgets/data/owtable.py
- Orange/widgets/data/tests/test_owtable.py
And add a test for the feature.
Fixes #5604.
> [FIX] OWTable: fix select whole rows regression

- Orange/canvas/config.py
- Orange/widgets/tests/test_workflows.py
Suggestion for biolab/orange-canvas-core#203
The tutorial entrypoints are sorted by name to make the order of the example workflows adjustable.
The entry point name for the default workflows starts with '000' so that they are at the beginning. 
Unless the entrypoint name of another add-on starts with e.g. '!'
This way, example workflows could also be placed at the very beginning.
Normally the entrypoints are called 'exampletutorials' and are appended to the defaults. With a prefix ('100', '200') the order between different add-ons can be controlled.
The sorting could also be moved to orange-canvas-core/orangecanvas/application/examples.py, because the add-on-internal sorting is already there.
> [ENH] config: sort example workflows

- Orange/widgets/evaluate/tests/test_owrocanalysis.py
- Orange/widgets/visualize/owradviz.py
Tests fail after release of scikit-learn 1.0.
- Scikit's fit checks whether the object has `columns` to distinguish between arrays and pandas frame. `Orange.data.Table` also has `columns`, but with different content, which caused a problem when (incorrectly) passed to scikit.
- ROC has tests for tooltips, which use test results for Titanic with kNN. Scikit changed something in kNN so that all returned probabilities are 0 or 1 (when k=5, this is not entirely unexpected).
- I fixed the call to kNN to pass an array `X`, not the whole `Table`.
- The offending test for ROC now uses artificial test results, not results from an actual model.
**To be considered:** `Orange.data.Table`'s property `columns`, which contains an instance of this: …
> [FIX] Fixes for scikit-learn 1.0

- Orange/classification/xgb.py
- Orange/modelling/tests/test_xgb.py
- Orange/regression/xgb.py
XGBoost fails on macOS is the number of jobs is left at default (details in https://github.com/dmlc/xgboost/issues/7156). This should be fixed in new release at around Oct 11, 2021.
- Set `n_jobs` to `1` on macOS
- Add a test that will fail after Oct 15, to remind us to remove the workaround.
- N/A: Documentation
> XGBoost: Temporary workaround before release of v1.5

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
Sometimes, datetime variables would come in the following format
`YYYY-mm-ddTHH:MM:SS+zz:zz`
which is not accepted by the `parse()` method.
Fix datetime to the correct format before parsing.
> Variable: fix timezone when parsing time variable

- Orange/widgets/unsupervised/owdistancematrix.py
- Orange/widgets/unsupervised/tests/test_owdistancematrix.py
Fixes #5651.
If meta attributes contain a numeric and string variable, meta variables have `dtype` `np.object`.
If numeric variable is chosen as a label, its values must be cast to `float` before mapping to colors.
> [FIX] Distance Matrix: Fix crash on numeric meta vars as labels

- Orange/widgets/model/owcalibratedlearner.py
- Orange/widgets/model/tests/test_owcalibratedlearner.py
- Orange/widgets/utils/owlearnerwidget.py
- Orange/widgets/utils/tests/test_owlearnerwidget.py
Ref: gh-5489
Use widget's name (captionTitle) as the default name
> owlearnerwidget: Use widget's name as the default name

- Orange/widgets/utils/colorgradientselection.py
- Orange/widgets/utils/spinbox.py
- Orange/widgets/utils/tests/test_colorgradientselection.py
Fixes gh-5640
Replace use of plain line edit with a DoubleSpinBox
> [FIX] HeatMap: Color gradient center value edit

- Orange/data/pandas_compat.py
- Orange/data/tests/test_pandas.py
Column with numbers with dtype object was parsed as a TimeVariable
I think it should be parsed as DiscreteVariable or StringVariable since dtype is object
> [FIX] pandas_compat: do not parse column of numbers (object dtype) to datetime

- Orange/data/pandas_compat.py
- Orange/data/tests/test_pandas.py
table_from_frames errored when it recieved a dataframe which is not OrangeDataFrame. Look at new test for an example.
fixes https://github.com/biolab/orange3/issues/5622
This PR solves two errors:
- do not expect df.orange_attributes for data frame that is not OrangeDataFrame
- make vars_from_df use take into account `role` parameter for data frame which is not OrangeDataFrame
- make sure indexes of all three data frames are equal and if index is not range index it should be placed in metas
> [FIX] pandas_compat: fix table_from_frames for "normal" dataframe

- doc/visual-programming/source/widgets/data/pythonscript.md
`in_datas`, etc. were missing from the documentation. These allow us to access inputs from the Python Script widget when we connect multiple data sources to it.
> Document plural form of input variables for Python Script Data widget

- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/owpythagorastree.py
- Orange/widgets/visualize/owpythagoreanforest.py
Fixes #5675.
**Distributions:** Set the width of the slider to match the maximum width
**Pythagorean Tree and Forest:** Set the width to accomodate 900, which is one of the widest three-digit integers.  ;) Checking all depths from 1 to maximal depth is not really necessary IMHO, and setting the width is cumbersome before merging https://github.com/biolab/orange-widget-base/pull/180, so I'd leave it and live with `900`.  Depths will typically be 2-digit anyway.
Labels in Pythagorean trees and forests are misaligned by a few pixels and will look better after merging https://github.com/biolab/orange-widget-base/pull/180 (though merging it is not required for this PR).
> Slider label widths

- Orange/widgets/visualize/tests/test_owdistributions.py
Tests with latest are failing. Hidden elements' brush can be None.
> test_owdistributions: adapt for newer pyqtgraph

- Orange/distance/tests/test_distance.py
- Orange/statistics/util.py
- Orange/tests/test_statistics.py
np.nanmean and np.nanvar create (masked) table copies. This uses unnecessary memory.
Before, sending a table into OWDataTable made a temporary copy, which is a problem with large tables. Probably not that important in practice, since if a copy does not fit then you won't be able to do much, but still ...
Replaced `np.nanmean` and `np.nanvar` with bottleneck equivalents.
> statistics.util: avoid memory wasting np.nanmean and np.nanvar

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
Before, .astype("str") was applied to the input array. This created an output array of fixed-length strings of the size of the longest string in the table. Converting numpy object arrays to string arrays should be, therefore, avoided.
This bug stems from #3722, which fixed #3671, but introduced this issue. :)
ORANGE3-311 on Sentry.
A combination of `pandas.isnull` and direct comparisons is used instead.
> Fix memory use in stats() for dtype=object

- Orange/widgets/data/owpaintdata.py
Fixes #5705 by removing points that the brush creates outside the [0, 1] interval.
The widget still applies clipping in the `Append` command. This is probably no longer needed, but let it stay for the case that some other operation also uses it (or would use it in the feature).
> Paint Data: Skip points brushed outside

- Orange/data/table.py
- Orange/data/tests/test_table.py
- Orange/tests/test_table.py
- Orange/widgets/data/owcreateinstance.py
- Orange/widgets/visualize/utils/widget.py
@VesnaT found a pickled table that could not be unlocked, because it was a view when unpickled. I thought this can not happen, but here it is.
While writing tests I also notices that EMPTY `W` from pickled tables could not be unlocked, because when unpickled it was `W.flags.owndata == False`.
> Table lock: fix unlocking unpickled tables

- Orange/widgets/data/owpaintdata.py
Fixes gh-5704
Do not use the plot's range to select what to delete.
> [FIX] Paint Data: Fix ClearTool's issued commands

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
Ref: #5425 
Instead of introducing a new slider, the opacity slider behaves differently in presence of a subset: it still regulates the opacity of the brush of subset, but at the same time it decreases the opacity of the pen of points not in the subset. The slider is still named opacity because I don't think the user will notice that (s)he now essentially regulates the contrast.
For now I implemented this for discrete coloring. If we decide that we like it, I'll change the continuous palette and monochromatic scatterplot in the same fashion.
Comments welcome.
> [ENH] Scatterplot: Use opacity for contrast

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
- Orange/widgets/visualize/utils/customizableplot.py
Fixes #5677
- Updater: implement `update_inf_lines` method
- Scatter plot ParameterSetter: 
- enable setting regression line label font
- enable setting regression line `width`, `opacity` and `style`
> Scatter Plot: Customizable regression line

- requirements-doc.txt
Currently Orange do not parse the widget list from the rtd correctly
Require docutils<0.17 for the readthedocs that documentation is compatible with the parser
> [DOC] Fix documentation build to be compatible with parser

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Ref: gh-5731
Indicate an error state (duplicated name) in the variable list view.
> [ENH] oweditdomain: Indicate variables in error state

- doc/visual-programming/source/index.rst
- doc/visual-programming/source/widgets/data/groupby.md
Image in groupby documentation have wrong casing\
Groupby is not in index
Add groupby to index
Fix wrong casing
> Fix wrong casing in Group-by docs and add to index

- Orange/preprocess/transformation.py
- Orange/tests/test_transformation.py
At around 3.28 we introduced domain caching into `Transformation` in a way that prevented older pickles to work. Fixes #5758.
This fix recreates the cache after unpickling. Furthermore, the cache (before `need_domain`, now `_target_domain`) is never pickled anymore.
> [FIX] Unpickling pre-3.28.0 Transformation

- Orange/data/io_util.py
- Orange/data/tests/test_table.py
- Orange/widgets/data/oweditdomain.py
- np.frompyfunc does convert outputs to the out type anymore
- Adapt a locking test for changed numpy internals
> [FIX] Support numpy 1.22

- Orange/widgets/data/owgroupby.py
- Orange/widgets/data/tests/test_owgroupby.py
Fixes https://github.com/biolab/orange3/issues/5738
- Fix mode to work in cases when all values in the group are nan
- test case with only nan values in the group
- additionally: use gui.deferred for autocoomit
> [FIX] Group by: compute mode when all values in group nan

- Orange/widgets/model/owadaboost.py
- Orange/widgets/model/owcalibratedlearner.py
- Orange/widgets/model/owcurvefit.py
- Orange/widgets/model/owlinearregression.py
- Orange/widgets/model/owstack.py
- Orange/widgets/utils/owlearnerwidget.py
- Orange/widgets/utils/tests/test_owlearnerwidget.py
Resolves #5703. Fixes #5577.
- Inform when preprocessors are given and the learner has its own default preprocessors, which are thusly overriden.
- Fix invalidation of model and learner, calling of updates and outputting signals.
Missing coverage is mostly in stack learner and was already missed before. This PR won't add tests there.
> [ENH] Learner widgets: Inform about potential problems when overriding preprocessors

- Orange/data/io_base.py
- Orange/widgets/data/owfile.py
- Orange/widgets/data/tests/test_owfile.py
Resolves #5724
For files, the reader used was already stored in `.file_format`, which could be either a reader's qualified name or `None` (which means that reader is detected depending on extension and priority).
All available readers are shown in a combo box.
For URLs, the reader selection is disabled. That part would have to be refactored a bit so that the chosen reader could be saved.
> [ENH] File: explicit file format choice

- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/utils/graphicsscene.py
- Orange/widgets/utils/graphicstextlist.py
- Orange/widgets/utils/tests/test_graphicstextlist.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/owsilhouetteplot.py
Closes gh-5728
* Do not clip child text items in the text annotations list.
* Allow the text to be wider (but is still limited to 750px; was 300 before)
* Generally change how the tool tips are displayed in the GraphicsTextListWidget with associated changes to all its uses (int owheatmap and owdistancemap). Before tool tips were set on individual text items, now the widget responds to QGraphicsSceneHelpEvent).
* Allow any Discrete it String variable for text Annotations.
* Also fix misaligned top/bottom axes
> [FIX] Silhouette plot text width

- Orange/widgets/unsupervised/tests/test_owdistancematrix.py
`test_labels` could fail if connection to online data set wasn't available.
Include the data into the test.
> [FIX] test_owdistancematrix: Do not download data for testing

- requirements-core.txt
Group By tests do not pass with earlier versions
> Raise pandas requirement to 1.3.0

- Orange/widgets/data/owpaintdata.py
- Orange/widgets/evaluate/owrocanalysis.py
- Orange/widgets/model/owgradientboosting.py
- Orange/widgets/model/owlinearregression.py
- Orange/widgets/model/owsvm.py
- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/unsupervised/owmanifoldlearning.py
- Orange/widgets/unsupervised/owsom.py
- Orange/widgets/utils/colorgradientselection.py
- Orange/widgets/utils/tests/test_dendrogram.py
- Orange/widgets/utils/tests/test_headerview.py
- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/ownomogram.py
- Orange/widgets/visualize/owsieve.py
- Orange/widgets/visualize/owtreeviewer.py
- Orange/widgets/visualize/pythagorastreeviewer.py
- Orange/widgets/visualize/utils/owlegend.py
Parts of Orange did not run on Python 3.10. With these changes, the tests pass on my Linux 3.10 installation with PyQt5==5.15.6 and a fork of bottleneck.
Mostly explicit casting to integers.
> Fix Python 3.10 casting errors

- Orange/widgets/utils/state_summary.py
From Python 3.7 on, single dispatch can deduce type from annotation. The type argument became redundant when we dropped support for Python 3.6.
Remove argument to decorator. Add argument type annotation where missing.
> Remove type arguments in summarize.register

- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
Fixes #5699. Also fixes #5679.
- Avoid computing the continuous contingency matrices, which may change the behaviour of the widget.
- #5679 is fixed as a side-effect of not computing contingency matrices for numeric attributes.
- Prepare the data for computation of statistics and showing it in the plot in the same way. There are still some difference in p-values at the third decimal.
> Box Plot: Treat nan's as 0's

- Orange/widgets/model/owcurvefit.py
- Orange/widgets/model/tests/test_owcurvefit.py
The Curve Fit widget needs data on the input to initialize the learner (i.e set the expression).
Refreshing the input data clears the expression (and parameters) which is undesirable in most cases.
- retain the expression when removing the template data
- enable the expression even when no data on the input
> Curve Fit: Retain expression on data remove

- Orange/widgets/data/owcolor.py
- Orange/widgets/data/tests/test_owcolor.py
Closes #5742.
The issue does not describe a bug, the mistake was on the user's side. But the user should be warned.
Add a warning when color definitions describe variables that do not appear in the data.
> Color: Warn about unused variable definitions

- .github/workflows/test.yml
- conda-recipe/meta.yaml
- requirements-core.txt
- requirements-gui.txt
- tox.ini
Our dependency list is stale. Occasionally tests fail in my valid but old python environment.
I added testing with oldest dependencies.
There are still requirements without specified versions. I left them as they were, for now, for better clarity of the changes in this PR (and due to some laziness). These should get defined in another PR.
> [FIX] Update (and test) minimum dependencies

- Orange/data/pandas_compat.py
- Orange/data/tests/test_pandas.py
1. When transforming pandas data frame to table string columns that contain nan values will 
keep them after the transformation but Orange uses an empty string for the unknown value in the StringVarable. 
For example:
df = pd.DataFrame(
[["a", "b"], ["c", "d"], ["e", "f"], [np.nan, np.nan]],
)
will be transformed to the table with two string variables and nan values will be kept even `String.Unknow = ""`
2. When a column is recognized to be a string and has an object type, it still can contain some values that are not strings. Cast column to string.
Changed that nan values are transformed to `String.Unknown` for columns that will be transformed to the string variable and values are transformed to strings.
> [FIX] table_from_frame: replace nan with String.Unknown for string variable

- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
Feature Statistics widget raises an error on Python 3.10 (warning in Python 3.9) on widget resize due to implicit conversion to int.
```
File "/home/ales/devel/orange3/Orange/widgets/data/owfeaturestatistics.py", line 687, in bind_histogram_aspect_ratio
self.verticalHeader().setDefaultSectionSize(effective_height)
TypeError: setDefaultSectionSize(self, int): argument 1 has unexpected type 'float'
```
> [FIX] owfeaturestatistics: Fix implicit int conversion error on resize

- Orange/data/io.py
- Orange/tests/test_url_reader.py
Fully support URL with query or fragment like `http://filename.txt?a=1&b=2#c=3`
Fix #5723
Use UTF-8 encoding URL with non-ascii characters, and preserve the role of special characters like ?#&=.
> Fully support URL with query or fragment like `http://filename.txt?a=1&b=2#c=3`

- Orange/widgets/data/owfile.py
Long combo box contents prevented widget resize. Offenders:
- File
- Sheet
- Reader
Used `Expanding` size-policy instead of `MinimumExpanding` and set the minimum size to something small but potentially usable. These should keep default appearance as before, observing Qt's size hints, but allows making the widget smaller.
> [FIX] File: remove some resizing limits

- Orange/widgets/data/owfeatureconstructor.py
Fixes gh-5803
* Always update models on data change
> [FIX] owfeatureconstructor: Always update models on data change

- Orange/data/io.py
- Orange/tests/test_xlsx_reader.py
- Orange/widgets/data/owsave.py
- Orange/widgets/data/tests/test_owsave.py
Fixes #5798
Beside headers, also save types and flags.
> [FIX] ExcelReader: Write roles

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
Fixes #5793
- show warning when input data has missing targets
- remove instances with missing target while scoring
- set all scores to `NA` when all targets are missing
> Predictions: Remove rows with missing target when scoring

- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/tests/test_owselectrows.py
Happy 22/2/2!
Now remove support for version==None settings in
SelectRowsContextHandler.decode_setting and SelectRowsContextHandler.match,
and uncomment OWSelectRows.migrate.
In tests, uncomment test_migration_to_version_1,
and remove test_support_old_settings and this test.
Basically, revert this commit.
> Remove old settings support in Select Rows

- Orange/data/table.py
- Orange/tests/test_table.py
> [FIX] Ensure unlockable sparse arrays after Table.copy

- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_itemmodels.py
The `tooltip` argument for `PyListModelTooltip` has a unsafe default (a mutable list) and does not accept generators. Also, if the number of tooltips is smaller than the number of rows, it gives index error.
- Tooltip argument is now `()`.
- To support generators, non-sequences (instances of classes without `__getitem__` are converted to lists. It would be better to convert all to lists (even if already a list), to match the behaviour of `PyListModel` with respect to `DisplayRole`, but I did it this way to maintain backward compatibility with any widgets that might have counted on having a reference to data in the model.
- Index ranges are now checked, and `None` is returned if there are too few tooltips.
> PyListModelTooltip: Improve handling of tooltip argument

- Orange/widgets/data/owpaintdata.py
- Orange/widgets/data/owselectrows.py
- Orange/widgets/evaluate/owcalibrationplot.py
- Orange/widgets/evaluate/owconfusionmatrix.py
- Orange/widgets/evaluate/owliftcurve.py
- Orange/widgets/evaluate/owrocanalysis.py
- Orange/widgets/unsupervised/owcorrespondence.py
- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/unsupervised/owdistancematrix.py
- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/utils/dendrogram.py
- Orange/widgets/utils/graphicstextlist.py
- Orange/widgets/utils/plot/owplotgui.py
- Orange/widgets/utils/slidergraph.py
- Orange/widgets/utils/tests/test_dendrogram.py
- Orange/widgets/visualize/owbarplot.py
- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owlineplot.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/owsilhouetteplot.py
- Orange/widgets/visualize/owtreeviewer.py
- Orange/widgets/visualize/owvenndiagram.py
- Orange/widgets/visualize/owviolinplot.py
- Orange/widgets/visualize/utils/component.py
- Orange/widgets/visualize/utils/heatmap.py
- Orange/widgets/visualize/utils/plotutils.py
- Orange/widgets/visualize/utils/tests/test_heatmap.py
Some visualizations use hardcoded colors and do not account for the effective color palette.
Replace use of hardcoded colors with palette colors.
> [ENH] Use palette colors in more places

- Orange/widgets/data/owgroupby.py
- Orange/widgets/data/tests/test_owgroupby.py
> [FIX] Group by: Restore aggregations if removed due to open context

- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/utils/histogram.py
Adds a few pixels between the bars and the horizontal line. Such Tufte-inspired histograms look better.
I agree with @kaimikael the this still does not resolve properly #5757.
> Feature Statistics: Add padding between histogram bars and horizontal line

- Orange/data/table.py
- Orange/data/tests/test_table.py
- Orange/tests/test_naive_bayes.py
- Orange/tests/test_table.py
When from_file/from_url is called on from table derived class, the type is changed after the reading (with calling table constructor) and so the view is made -- which is not expected by `from_file`
In discussion with @markotoplak we decided to remove the type conversion since it is causing issues (also destroys the type when for example Corpus is pickled). Classes that are derived from Table can handle the conversion themselves.
> [FIX] Table: from_file/from_url remove type conversion

- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/tests/test_owlinearprojection.py
- Orange/widgets/visualize/utils/widget.py
Fixes #5359
I thought about removing the overriden `effective_data` (which also fixes LDA), but then saw that it was done based on a talk between @janezd and @VesnaT (https://github.com/biolab/orange3/pull/4846#issuecomment-643242265) who must have had a good reason for it.
So I just added the class to effective_data, but @janezd or @VesnaT should confirm that that makes sense.
> [FIX] Linear Projection: Fix LDA

- Orange/widgets/unsupervised/owtsne.py
- Orange/widgets/visualize/owfreeviz.py
Default `effective_data` has changed after #5828
- set effective_data for tSNE and Freeviz widgets
> [FIX] tSNE, Freeviz: Set effective_data

- Orange/widgets/evaluate/utils.py
> [FIX] widgets.evaluate.utils: call resizeColumnsToContents before setting hidden header sections.

- Orange/widgets/visualize/owscatterplot.py
Fixes #5721.
I've no idea why I though this needs to be rotated. It's been four years; perhaps something changed in pyqtgraph?
Remove rotation.
> [FIX] Scatter plot: Fix rotation of regression line label

- conda-recipe/meta.yaml
- pyproject.toml
- requirements-core.txt
- tox.ini
Oldest-orange workflow started to fail since markupsafe does not build on build on setuptools=36
Changing oldest supported version of setuptools to 41
> Fix oldest-orange CI

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Scatter Plot widget does not always refresh the plot on input features change. To obtain this behaviour the features must be connected before the data (see the included test).
To reproduce, open the attached workflow and change the selection in the Correlations widget. The plot in Scatter Plot does not change accordingly.
[untitled.ows.zip](https://github.com/biolab/orange3/files/8047374/untitled.ows.zip)
- introduce `_attrs_invalidated` variable in Scatter Plot widget
> [FIX] Scatter Plot: Replot when input features change

- Orange/misc/server_embedder.py
- Orange/misc/tests/test_server_embedder.py
Server embedder retries sending unsuccessful requests immediately after the fauliture. 
Since it is possible that the server needs longer to compute (the request was unsuccessful because of timeout) the results (the server will cache the result when finished) it is better to retry later (there is a higher chance that the server already finished processing).
Implemented described behaviour. To achieve it I needed to change embedders to use Queue instead of just gathering the results.
> [ENH] Server embedder: use queue, handle unsuccessful requests at the end

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
Fixes #5743.
It sure looks funny, especially for numeric targets, but.
I didn't want to put the combo to the main area in order to save space; in Test and Score we have plenty space on the right, here it's precious. I have put the Restore Order button and the list view for selecting probabilities at the top, and the combo for choosing the target at the bottom (with rubber in between), so they are close to their respective tables.
This is quite nice for discrete outcomes; less so for numeric.
I've no idea what to do here except for perhaps having a different layout in this case: just put the checkbox and the button between the tables (in that order, with rubber between), and hide the control area completely.
> Predictions: Allow choosing a target

- Orange/widgets/evaluate/owcalibrationplot.py
- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owcalibrationplot.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
Fixes #5854.
The problem was essentially in Predictions, which created a malformed instance of `Results`. Folds should be `[...]`, not `None`.
- Fixed Predictions to output proper folds.
- Add `models` to `Results` that come from `Predictions`, so they can be calibrated by Calibration
- Make Calibration more resilient -- accept `folds=None` if any other widget misbehaves in the same way as Predictions
> [FIX] Calibration: Fix crash on empty folds

- Orange/misc/server_embedder.py
- Orange/misc/tests/test_server_embedder.py
- conda-recipe/meta.yaml
- requirements-core.txt
- tox.ini
Httpx is a few versions ahead and is more stable now
When the version was updated, I also noticed that I closed the client before all responses were gathered (it was now an exception before everything was still working). Wait finished with waiting when one of the workers stopped, then gather was waiting for other workers outside context manager.
Setting minimum version to 0.21, where also some bugs are resolved.
Resolving the error described above by simplifying the code - removing wait, now gather will wait until all workers finish (each worker finishes when it has no more items to pull from the queue.
Extra: do not create more than the required number of workers
> Increase minimum version of httpx

- Orange/widgets/visualize/utils/plotutils.py
Distributions widget raises an  error on Python 3.10 due to implicit int conversion (warning on 3.9). 
```
File "/home/ales/.envs/orange3/lib/python3.10/site-packages/pyqtgraph/graphicsItems/AxisItem.py", line 593, in paint
specs = self.generateDrawSpecs(painter)
File "/home/ales/devel/orange3/Orange/widgets/visualize/utils/plotutils.py", line 432, in generateDrawSpecs
text_specs = [(rect, flags, elide(text, Qt.ElideRight, max_width))
File "/home/ales/devel/orange3/Orange/widgets/visualize/utils/plotutils.py", line 432, in <listcomp>
text_specs = [(rect, flags, elide(text, Qt.ElideRight, max_width))
TypeError: elidedText(self, str, Qt.TextElideMode, int, flags: int = 0): …
```
> [FIX] plotutils: Fix and implicit conversion to int warning error

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Orange's widgets does not support datatime formats other than ISO.
Fixes https://github.com/biolab/orange3/issues/5779
Add dropdown with format selection to Edit domain widget
When no year is provided (only day and month) - the last three formats the year will become 1900, since it is the default in python's DateTime and excel too.
Implement the same functionality in the File widget --- will be implemented in the separate pull request
> [ENH] Datetime format selection

- Orange/widgets/data/owpythonscript.py
Set `auto_summary` to `False` for object input and output signals to avoid warnings.
> Python Script: Disable auto_summary for object signals

- Orange/preprocess/discretize.py
- Orange/preprocess/tests/test_discretize.py
- Orange/widgets/unsupervised/owsom.py
- Orange/widgets/unsupervised/tests/test_owsom.py
Fixes #5858.
If the variable determining the color was constant, the binning set two thresholds, which were both removed, thus creating an empty list of thresholds and labels. This created problems later in the code.
Set a threshold and label.
> [FIX] SOM: Fix crash when color is constant

- Orange/widgets/utils/__init__.py
- Orange/widgets/visualize/owtreeviewer.py
Fixes #5871.
The problem appeared only at nodes directly below the root because the text didn't contain any html tags (later, we have `<br>`), so Qt didn't recognize it as rich text. Adding a `<p>` tag solves it.
The other commit, which replaces unicode points with symbols, is cosmetic.
> Fix tree tooltips

- Orange/widgets/evaluate/owrocanalysis.py
Fixes gh-5902
Also the plot displays custom ticks for the first classifier only even when multiple are displayed and for *Merge Predictions from Folds* curves even if different combining/averaging is selected.
Fix an index error in custom tick calculation
Also check so that the ticks actually apply to the displayed points
> [FIX] owrocanalysis: Fix an index error in custom tick calculation

- Orange/base.py
- Orange/classification/base_classification.py
- Orange/evaluation/clustering.py
- Orange/evaluation/scoring.py
- Orange/evaluation/testing.py
- Orange/preprocess/impute.py
- Orange/regression/base_regression.py
- Orange/tests/dummy_learners.py
- Orange/tests/test_base.py
- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/owtestandscore.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
- Orange/widgets/evaluate/tests/test_owtestandscore.py
- Orange/widgets/evaluate/utils.py
- Orange/widgets/utils/owlearnerwidget.py
In survival analysis, it is expected to have two target variables. First is the duration of time until the event of interest, and the second is the indicator of censorship.
Preferably, the Survival Analysis add-on would then use the same infrastructure for testing and scoring survival models as it is currently in place for classification and regression related problems. To achieve this, we need to loosen the constraint of a single target variable for the input data.
With this pull request, the task was not to change the interface to accommodate for all future tasks one would like to support but to:
- allow the use of multitarget data and make no breaking changes to the existing codebase (do not change the default behaviour),
- for a start, make survival models/scorers available in Orange. …
> [ENH] Enable multitarget problem types for OWTestAndScore and OWPredictions

- Orange/data/table.py
- Orange/data/tests/test_table.py
fixes #5878 
deprecated is_view and is_copy as requested
> [FIX] Orange.data.Table: deprecated is_view and is_copy

- Orange/preprocess/tests/test_transformation.py
- Orange/preprocess/transformation.py
- Orange/widgets/visualize/tests/test_ownomogram.py
Class `Indicator` converts values of a variable to 0 or 1, depending on whether it matches the given constant or not. The class hasn't checked for nan's and hence converted them to 0, which is unexpected. Missing values should remain missing.
Same for `Indicator1`.
I am not sure what this is supposed
> Indicator: Keep missing values

- Orange/widgets/evaluate/tests/test_utils.py
- Orange/widgets/evaluate/utils.py
A scoring method defined in an addon is never shown by default. We have to decide how to allow this in general. I was thinking of storing different things in the "shown_scores" setting, but that is a change that would be too big for now and we have a deadline to catch.
This (or something similar) should be merged until Friday.
This PR proposes a temporary solution to show the scoring method for survival data. It should not influence other problem types so it should change nothing for people that do not use the survival analysis add-on.
This PR adds the "C-Index" method after the Settings are read so that it will also show up for users who have stored settings (changing a default would do nothing for them).
> A workaround to show C-Index scoring method for survival data

- setup.py
Warehouse now uses the project_urls provided to display links in the sidebar on [this screen](https://pypi.org/project/requests/), as well as including them in API responses to help the automation tool find the source code for Requests.
Example: [pypi.org/pypi/requests/json](https://pypi.org/pypi/requests/json)
Docs: [packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls)
> Add GitHub URL for PyPi 

- Orange/widgets/utils/_grid_density.cpp
Just was setting up orange via `python setup.py develop` and ran into this compilation warning:
```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/ch/miniconda3/envs/orange3/include -arch arm64 -I/Users/ch/miniconda3/envs/orange3/include -fPIC -O2 -isystem /Users/ch/miniconda3/envs/orange3/include -arch arm64 -I/Users/ch/miniconda3/envs/orange3/lib/python3.9/site-packages/numpy/core/include -I/Users/ch/miniconda3/envs/orange3/include/python3.9 -c Orange/widgets/utils/_grid_density.cpp -o build/temp.macosx-11.1-arm64-3.9/Orange/widgets/utils/_grid_density.o
Orange/widgets/utils/_grid_density.cpp:64:2: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete] …
```
> use delete[] to delete array

- Orange/misc/server_embedder.py
- Orange/misc/tests/test_server_embedder.py
- Orange/regression/linear.py
- Orange/tests/test_linear_regression.py
Tests start to fail due to two deprecations that should be removed.
- sever embedders: the removal is postponed to version 3.34, it would be fewer issues with older versions of addons if we wait for one more version
- linear regression: removed normalize and everything connected
> Resolve deprecations

- Orange/widgets/data/owpythonscript.py
- Orange/widgets/data/utils/pythoneditor/editor.py
Python script raises type errors on Python 3.10 due to implicit float to int casts.
Error 1: Enable *Vim mode* -> immediate crash.
Error 2: In the editor enter space on the end of any line.
Fix types of passed parameters.
> [FIX] owpythonscript: Fix implicit float to int cast error

- Orange/misc/server_embedder.py
Since Orange now support python>=3.7 we do not need to use `run_until_complete` and custom loop handling in embedders.
User `asyncio.run` instead which is supported python>=3.7
> server_embedder - replace run_until_complete with asyncio.run

- Orange/widgets/evaluate/tests/test_utils.py
- Orange/widgets/evaluate/utils.py
https://github.com/biolab/orange3-explain/pull/42
I forgot to make usable_scorers backwards compatible. Sorry! :)
> [FIX] make usable_scorers backwards compatible

- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
- doc/visual-programming/source/widgets/data/featurestatistics.md
Resolves #5908.
Feature Statistics now outputs statistics for all variables, ignoring selection. (`Reduce Data` output works as before.)
Documentation is mildly outdated. In paragraph "*Alternatively, if we want to store feature statistics, we can use the *Statistics* output and manipulate those values as needed. In this example, we simply select all the features and display the statistics in a table.*", I removed "*simply select all the features and *", so it does not suggest that features have to be selected for this. The screenshot shows them as selected, but this is rather irrelevant.
> Feature Statistics: Output all statistics, not just selected

- .github/workflows/rebase.yml
After latest changes in git (https://github.com/actions/checkout/issues/766) rebase fails with error:
```
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
```
Rising version to 1.6 should solve the problem
> Upgrade cirrus-actions/rebase to version 1.6

- requirements-gui.txt
SliderGraph not working due to upstream problem in pyqtgraph.
Resulting in e.g. PCA widget crashing immediately.
Bump required pyqtgraph version to at least 0.12.2, to include fix for https://github.com/pyqtgraph/pyqtgraph/issues/1484
> requirements-gui: Raise required pyqtgraph version

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplotbase.py
Fixes #5922.
Use same method for coloring when same value as for other settings.
> Scatterplot Graph: Use no brush when same color

- .github/workflows/doc.yml
- .github/workflows/test.yml
- Orange/preprocess/transformation.py
- Orange/tests/test_transformation.py
- requirements-core.txt
- tox.ini
Bottleneck should now support python 3.10. Let's try if Orange works on Py3.10
Changes:
- deprecated windows-2016 are replaced with widows-2019 (and latest with windows-2022)
- python 3.10 is added to the matrix
- fixed the hash error in Lookup (in Python 10 hashes of nan are not guaranteed to be constant)
- some smaller fixes in CI to make it working
> CI: Enable tests for python 3.10

- Orange/widgets/data/owgroupby.py
- Orange/widgets/data/tests/test_owgroupby.py
Fixes #5955
Mode is enabled for discrete variables and is now default for the discrete variables.
The mode could be technically also enabled for String variables but I decided not to enable it for string variables since they are mostly text (with different values in each row).
> Group by: Enable mode for discrete variable

- Orange/tree.py
- Orange/widgets/visualize/owtreeviewer.py
- Orange/widgets/visualize/tests/test_owtreegraph.py
Trees are used mostly for education purposes. In this context, showing majority classes in internal nodes is often annoying at first (at least, it adds unnecessary details), but can be useful later. I'd like it to be hidden, but with option for showing it.
Add a checkbox for showing/hiding details.
> Tree Viewer: Hide details

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
Fixes #5901
- Refactor item delegates into two classes, one for classification and one for regression (to avoid checks in methods)
- Add information about the actual class/outcome to `PredictionModel`
- Show actual class by using narrower lines in distribution bar
- Show the line for regression and mark the true value
- **Fix** a bug in assigning of indices for sorting by probabilities: if any models failed and their respective columns were not shows, the indices for sorting by that column were nevertheless created and inserted. Therefore, if the 3rd model has failed, the 3rd column showed the 4th model, but sorting by that column would sort by the 3rd model (and probably fail).
> Predictions: Show errors in regression

- Orange/widgets/visualize/owsilhouetteplot.py
- Orange/widgets/visualize/tests/test_owsilhouetteplot.py
Silhouette widget hasn't yet been refactored to use `Variable`'s instead of `int` indices.
- Use variables
> Silhouette: Use variables instead of indices

- Orange/data/variable.py
- Orange/tests/test_value.py
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
- Orange/widgets/utils/__init__.py
Ref: https://github.com/biolab/orange3/issues/5911
Parallel (or alternative) to https://github.com/biolab/orange3/pull/5949
Avoid iteration over table rows, checks in inner loops, construction of `Value` instances.
> [ENH] Feature constructor optimization

- Orange/widgets/data/owneighbors.py
- Orange/widgets/data/tests/test_owneighbors.py
Neighbours always returns Table regardless of input type. For example if Corpus on input the output will still be Table.
Fix output to be of the same Table derived type as an input.
> [FIX] Neighbours - support Table derived output types

- Orange/data/tests/test_util.py
- Orange/data/util.py
`util.get_unique_names` is routinely used in to avoid duplicated names. There are situations, though, when the proposed names already include duplicates due to user's choices. See, e.g. https://github.com/biolab/orange3-timeseries/issues/181.
Detect duplicated proposed names and number them sequentially.
> util.get_unique_names: Deduplicate duplicated proposals

- Orange/widgets/evaluate/owconfusionmatrix.py
- Orange/widgets/evaluate/tests/test_owconfusionmatrix.py
Fixes #5978.
Use `get_unique_names` before constructing domain.
> Confusion Matrix: Ensure unique variable names

- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_itemmodels.py
`itemmodels.PyTableModel.insertColumns` updated `_rows` instead of `_cols`, which made the model temporarily invalid and caused extra columns in https://github.com/biolab/orange3-timeseries/issues/88.
Fix typo.
> itemmodels.PyTableModel: Fix insertColumns

- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/unsupervised/tests/test_owdistancemap.py
Raises error on Python 3.10
Distance Map raises an error on Python 3.10 when setting any *Annotations* that are not *None*
```
File "/home/ales/devel/orange3/Orange/widgets/unsupervised/owdistancemap.py", line 695, in resizeEvent
self._updateFontSize()
File "/home/ales/devel/orange3/Orange/widgets/unsupervised/owdistancemap.py", line 713, in _updateFontSize
fontsize = min(self._point_size(lineheight), maxfontsize)
File "/home/ales/devel/orange3/Orange/widgets/unsupervised/owdistancemap.py", line 721, in _point_size
font.setPointSize(height)
TypeError: setPointSize(self, int): argument 1 has unexpected type 'float'
--------------------------------------------------------------- …
```
> [FIX] owdistancemap: Fix an implicit float->int conversion error

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
Fixes #5983.
- Adds `__eq__` and `__hash__` to `owfeatureconstructor.FeatureFunc` 
- Shows a warning if variable is assigned `compute_value` that has no `__eq__` and `__hash__` (unless it's an instance of `FunctionType` or `BuiltinFunctionType`, which are not deecopied, so `object.__eq__` and `object.__hash__` will work just fine)
> Warn about missing __eq__ for compute value; provide FeatureFunc.__eq__

- Orange/widgets/utils/itemdelegates.py
- Orange/widgets/utils/itemmodels.py
In 'Data Table' On dark styles the contrast of text on background for metas and class columns is poor.
Before 
After
Define foreground color when providing background to ensure text is contrasted against the background when system text color is light.
> [FIX] TableModel: Define foreground color when providing background

- Orange/widgets/data/owpaintdata.py
Fixes #6009.
Set plot's vertical size policy to `Expanding` instead of `Minimum`
> PaintData: Allow minimizing height

- Orange/data/variable.py
If time was 1.999_999_9 seconds, it was rounded to 1 second and 1_000_000 microseconds -- causing `__repr__` to crash, which could led even to core dump in the Table widget's paint.
Safer rounding.
> TimeVariable: fix rounding in repr

- Orange/widgets/utils/save/owsavebase.py
- Orange/widgets/utils/save/tests/test_owsavebase.py
Fixes #5868
Handle various combinations of file paths with slashes, backslashes, trailing slashes, etc.
> OWSaveBase: fix stored relative path

- Orange/widgets/data/owfeaturestatistics.py
Fixes #5757.
I found no simpler way to add some whitespace below the view than to embed the view into a box with white (hopefully black, in dark mode) background.
> Feature Statistics: white space below view

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
Closes #5971.
Add columns with errors for each predictor.
Please comment on functionality and interface. Checking and tests will come afterwards.
Try it on housing and heart disease; errors on iris are too small.
> [ENH] Predictions: Show errors

- Orange/tests/test_fss.py
`np.ndarray` (which `contingency.Discrete` subclasses) of a single float is not an instance of float anymore.
> Fix test_fss for numpy 1.23

- .github/workflows/test.yml
Linux gh actions runners started failing with 'qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.'
Add libxcb-shape to installed linux system packages
Also update deprecated macos-10.15 runners
> [MNT][CI] Add libxcb-shape to linux system packages

- Orange/data/dask.py
- Orange/data/sql/table.py
- Orange/data/table.py
- Orange/preprocess/normalize.py
- Orange/statistics/basic_stats.py
- Orange/statistics/util.py
- Orange/tests/test_dasktable.py
- Orange/tests/test_statistics.py
Normalization does not work for dask arrays. The computation of distributions is slow (it requires sorting). Fixes #5219
Use "fast stats" for Normalization.
> [ENH] Faster normalization, support Dask Tables

- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/tests/test_owboxplot.py
- added 2 tests to make sure sampling is working correctly for DaskTables
- changed some of the standard tests to make sure they use the already defined datasets instead of opening new Tables and subsequently not testing functionality on DaskTables
> OWBoxplot: add tests for dask

- Orange/widgets/data/tests/test_owfile.py
Fix intermittent test failure:
```
FAIL: test_warning_from_another_thread (Orange.widgets.data.tests.test_owfile.TestOWFile)
File "/Users/runner/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/unittest/mock.py", line 1369, in patched
return func(*newargs, **newkeywargs)
File "/Users/runner/work/orange3/orange3/.tox/orange-released/lib/python3.10/site-packages/Orange/widgets/data/tests/test_owfile.py", line 693, in test_warning_from_another_thread
with self.assertWarns(UserWarning):
AssertionError: UserWarning not triggered
```
Replace use of `time.sleep` to sequence threaded code.
> [FIX] test_owfile: Fix unreliable `test_warning_from_another_thread`

- Orange/misc/collections.py
- Orange/misc/tests/test_collections.py
- Orange/preprocess/tests/test_transformation.py
- Orange/preprocess/transformation.py
- Orange/tests/test_util.py
- Orange/util.py
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_oweditdomain.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
Feature Constructor can construct `compute_value` which are not picklable (defined in local function scope):
* https://github.com/biolab/orange3/blob/cd3dfeeeb7f4ac97667e2a0335923b5fa6dfebab/Orange/widgets/data/owfeatureconstructor.py#L1032-L1033
* https://github.com/biolab/orange3/blob/cd3dfeeeb7f4ac97667e2a0335923b5fa6dfebab/Orange/widgets/data/owfeatureconstructor.py#L1042-L1047)
Fixes gh-5918
* Make the `cast` function passed to FeatureFunc picklable.
* Some refactoring of classes from oweditdomain.
> [FIX] Feature Constructor cast function is not picklable

- Orange/widgets/unsupervised/owsom.py
SOM improperly calculates scene rectangle. I suppose this is also why the legend falls outside the view.
Fix the formula.
> SOM: Properly calculate scene rect

- Orange/evaluation/scoring.py
- Orange/tests/test_evaluation_scoring.py
CD diagrams crash headless tests on Linux. Because Orange does not use these functions we should just remove them.
> Deprecate CD diagrams

- Orange/widgets/data/owrank.py
- Orange/widgets/data/tests/test_owrank.py
- Orange/widgets/gui.py
- Orange/widgets/tests/test_gui.py
Rank's TableView and TableModel are not independent modules that can be called for other widgets.
Move the two classes to gui.py, so other widgets can use them.
> Rank: Move TableView and TableModel to gui

- Orange/widgets/visualize/utils/plotutils.py
Qt.Midbutton is deprecated and removed in PyQt6
Replace it with Qt.MiddleButton
> [FIX] plotutils - replace MidButton with MiddleButton

- Orange/classification/base_classification.py
- Orange/classification/catgb.py
- Orange/classification/xgb.py
- Orange/tests/test_classification.py
- Orange/tree.py
Implement `predict_proba` for classification models to be consistent with sklearn models interface.
- add predict_proba to ModelClassification class
- add predict_proba to TreeModel class
- introduce new class CatGBClsModel
> ModelClassification: Implement predict_proba

- Orange/misc/server_embedder.py
- Orange/misc/tests/test_server_embedder.py
According to httpx sending bytes as data parameters is deprecated. 
Use content for sending bytes and data for sending dictionaries
> [FIX] Server embedder - send bytes as content

- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
Fixes: gh-6113
Cast FeatureFunc result to array
> [FIX] owfeatureconstructor: Cast FeatureFunc result to array

- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
Fixes #5982.
String values were mapped through `StringVariable.str_val`, which was unnecessary (**is it?**) and replaced missing values with "?".
This PR just removes mapping, so the example in #5982 gives the desired input.
This treats missing strings as something that can be worked with, e.g. added. Given that missing strings are represented by empty strings, we do not have a good way of preventing it; replacing them with `None` would be ... artificial.
> FeatureConstructor: Don't replace missing strings with ?

- Orange/widgets/visualize/owscatterplotgraph.py
Fixes #6103 
- `Orange.widgets.visualize.owscatterplotgraph.AxisItem.tickValue` generates ticks that include the start of the first and the end of the last interval, i.e. 29 17h and 30 0h. 
- `Orange.widgets.visualize.owscatterplotgraph.AxisItem.tickStrings` uses format `"$d %Hh"` because `min_day` is not equal to`max_day`.
- Pyqtgraph's `AxisItem.generateDrawSpec` however discovers that the first and the last label are outside the data and removes them.
- 
We cannot override `AxisItem.generateDrawSpec`, but we can second-guess it: we know which label it will remove, and 
do not generate them in the first place.
> owscatterplotgraph.AxisItem: Improve time labels

- Orange/data/variable.py
- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/utils/plotutils.py
`DiscretizedScale` was defined in module `owscatterplotgraph`. It belongs to `plotutils`.
When values were ints that didn't fit into 64 bits, numpy stored thresholds as instances of `object` instead of `float`. This is now fixed by explicit conversion to `float`.
> DiscretizedScale: Move to proper place, fix a minor problem

- Orange/widgets/data/owselectbydataindex.py
- Orange/widgets/data/owtransform.py
- Orange/widgets/data/tests/test_owtransform.py
Fixes #5574.
This is very unusual and I'd hate it to become the norm. But there's nothing reasonable we can put there. Even five-row preview is pointless after #5956.
On the other hand, these descriptions may indeed be useful.
> Apply Domain and Select By Index: Replace info by description

- Orange/widgets/gui.py
- Orange/widgets/tests/test_gui.py
- requirements-gui.txt
- tox.ini
`Orange.widgets.gui` redefines `comboBox`, but uses `*args` and `**kwargs` for arguments, so we can't get any assistance from GUIs.
**Requires https://github.com/biolab/orange-widget-base/pull/203 to be merged and released.**
List arguments. Also add a `tooltips` argument, which is why it requires a new release of orange-widget-base.
> gui.comboBox: replace *args with argument list

- Orange/widgets/evaluate/owconfusionmatrix.py
- Orange/widgets/evaluate/tests/test_owconfusionmatrix.py
Confusion matrix currently presents and evaluates the predicted classes. When one wants to evaluate the probability outputs it is less useful. For example, a majority class could be predicted for all instances, but the probabilities of several minority classes are still important (and differ among predictions).
Introduce `Sum of probabilities` Show option, which uses the sum of probabilities of the predicted class (instead of predicted class counter) when constructing the matrix.
> Confusion Matrix: Add Sum of probabilities

- requirements-core.txt
Pandas may have a bug (or it is just partially implemented new rule for DateTime conversion) that cause our test to fail in the latest version https://github.com/pandas-dev/pandas/issues/48678
Skip pandas version 1.5.0 until they decide whether it is a bug or feature.
If they fix/change the issue solution will probably be available in 1.5.1, so nothing needs to be changed.
If it is not a bug, we need to adapt tests.
> Temporally skip pandas version 1.5.0 

- Orange/widgets/data/owrank.py
- Orange/widgets/data/tests/test_owrank.py
Fixes #6140.
Derives a new model from `BarRatioTableModel`, which delegates the first column to `VariableListModel`, which then provides the usual data (tooltips, decoration...) seen in other widgets.
It assumes that data is changed only through `wrap`, as is the actual case in the widget. If this is unacceptable, we could instead change `VariableListModel`'s methods that generate tooltips into class methods or static methods, and call the from `RankTableModel` instead of having an actual instance of `VariableListModel`.
> Rank: Use VariableListModel to show decoration and tooltips

- .github/workflows/doc.yml
- .github/workflows/test.yml
- requirements-core.txt
- requirements-gui.txt
- tox.ini
Numpy and Pandas already dropped the support for Python 3.7. I think it is time for Orange too. Supporting (soon) 4 versions is enough.
Dropping Python 3.7 support and tests. 
This PR also upgrades minimum versions of xlrd and matplotlib:
- xlrd 1.2.0 is the first version that supports python 3.8 (the oldest test failed with the older version).
-  for matplotlib only windows wheels (not Linux and macOS) are available for Python 3.8 in older versions and version prior 3.2.0 dont build well with the oldest supported numpy. They are also older than the oldest supported Numpy. 3.2.0 is older than 2 and a half years and is the first to provide python 3.8 wheels for Linux.
> Drop test and support for python 3.7

- Orange/widgets/utils/state_summary.py
Ref: #5873
Based on https://github.com/biolab/orange-widget-base/pull/198.
Add previewer for `Table`.
We probably want to add one for `Distance Matrix`, and that would be it (for signals in core widgets), I guess.
> Add preview for Table signal

- Orange/widgets/visualize/owscatterplotgraph.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Fixes #6086.
If there is only a single tick or no ticks, `min` that computed the min difference crashed.
Provide `default` argument. It equals the difference between the min and the max value, so `tickStrings` knows how to formulate the label.
> Scatterplot: Fix crash for a single time tick

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Transforming to Time variable fails when timezone is in strings
Correctly handle timezones in data time
Additionally: First I planned to raise the Pandas version to 1.4 since this version already supports subtracting different timezones. It was impossible since Pandas>=1.4 does not support Python 3.7 anymore, so building documentation fails (by readthedcos) since they build documentation on Python 3.7. Setting different versions of python for rtd is supported by the config file, but it cannot be used with multiple subprojects. We cannot raise the Pandas' version until they start supporting config files for subprojects or building on python 3.8.
> [FIX] Handle timezones in Edit Domain

- Orange/classification/_simple_tree.c
- Orange/classification/tests/test_simple_tree.py
Fixes #6001, which results from `SimpleTree` predicting `nan` when all target values in a branch are `nan`.
Add the necessary checks. There may be other cases that I have missed  (the code is long), but I don't want to add a blanket check for nans at the end of predictor because it could hide problems in tree inducer..
> SimpleTree: Fix (some?) nan predictions

- Orange/widgets/data/owgroupby.py
- Orange/widgets/data/tests/test_oweditdomain.py
- Orange/widgets/data/tests/test_owgroupby.py
Fixe https://github.com/biolab/orange3/issues/6125
- use Series's std instead of GroupBy one since GB aggregations do not support DateTime data https://github.com/pandas-dev/pandas/issues/48481
- for variance, first, transform DateTime to Unix epoch since Panda's variance does not support DateTime
- std and span transform TimeDelta to seconds (Orange does not have TimeDelta type)
- I disabled the sum for TimeVariable since it doesn't make sense to compute data/times' sums.
> [FIX] Group By - fix std and sum for TimeVariable

- Orange/widgets/data/utils/pythoneditor/tests/test_api.py
- Orange/widgets/data/utils/pythoneditor/tests/test_bracket_highlighter.py
- Orange/widgets/data/utils/pythoneditor/tests/test_draw_whitespace.py
- Orange/widgets/data/utils/pythoneditor/tests/test_edit.py
- Orange/widgets/data/utils/pythoneditor/tests/test_indent.py
- Orange/widgets/data/utils/pythoneditor/tests/test_rectangular_selection.py
- Orange/widgets/data/utils/pythoneditor/tests/test_vim.py
- Orange/widgets/tests/test_workflows.py
- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/visualize/owboxplot.py
- tox.ini
Since https://github.com/biolab/orange-widget-base/pull/204 was released, `Orange.widgets.tests.test_workflows` fails with
```
File "/home/runner/work/orange3/orange3/.tox/pyqt6/lib/python3.9/site-packages/Orange/widgets/visualize/owboxplot.py", line 257, in eventFilter
if obj is self.box_view.viewport() and \
AttributeError: 'OWBoxPlot' object has no attribute 'box_view'
ERROR: InvocationError for command /home/runner/work/orange3/orange3/.tox/pyqt6/bin/python -m unittest Orange.widgets.tests (exited with code -6 (SIGABRT)) (exited with code -6)
```
Change order of conditions in eventFilter to short-circuit access to widget members which can no longer exist (empty `self.__dict__`).
> [FIX] owboxplot: Fix an error in widget cleanup during tests

- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/utils/dendrogram.py
- Orange/widgets/utils/graphicstextlist.py
Closes #6126 and more.
- Labels for the subset are shown in bold.
- Adds option to show additional icons, colored by values of some variable; if subset is present, only squares for the rows in the subset are filled.
- If there are no labels and no icons, subset is indicated by small dots.
- Refactors most of `TextListWidget`'s code into a base class (`TextListBase`) and derives a new class, `TextListView` that gets data from a model. Hierarchical Clustering than uses it instead of `TextListWidget`. Distance Matrix and Silhouette can do the same.
- Since class is not used as default for coloring, the first string attribute is used for annotation. If there are none, it uses class, otherwise the first non-None option.
- Enumeration is now shown only if there are not other options (except …
> Hierarchical Clustering: Add Subset signal

- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
Fixes #6151.
- The most common value for discrete variables is now shown in separate column of output. All columns that don't apply (including min and max) are set to undefined.
- Output columns adapt to types of variables: if there are no categorical variables, the majority column is removed. If there are only categorical, the columns that do not apply are removed.
> Feature Statistics: Adapt output to types of variables

- Orange/widgets/data/owaggregatecolumns.py
- Orange/widgets/data/tests/test_owaggregatecolumns.py
> Aggregate Columns: Add additional options for selection

- Orange/statistics/util.py
- Orange/widgets/data/owfeaturestatistics.py
- Orange/widgets/data/tests/test_owfeaturestatistics.py
Fixes partially #6173 (everything except documentation).
1. Statistics is now committed after receiving data -- as it should be, unconditionally. A test that the widget does not send this data when auto commit is off is removed (because it's wrong).
Reduced data is committed after receiving data (unconditionally) and when selection is changed (conditionally).
2. Mode is also computed for numeric variables. Output needs discussion, though. See https://github.com/biolab/orange3/issues/6173#issuecomment-1279185345.
3. Fixed warnings. 
- a warning from scipy.stats.mode is fixed by setting `keepdims=True`. `False` also passes tests but I'd keep the behaviour to be safe.
- `scipy.stats.stats` is deprecated, `scipy.stats` should be used instead. Hence we now call `scipy.stats.mode`. `ModeResult` …
> [FIX] Feature statistics: Use deferred commit + minor warning fix

- Orange/widgets/unsupervised/owdistances.py
- Orange/widgets/unsupervised/tests/test_owdistances.py
Fixes #6166. @ajdapretnar, does it?
I believe the idea was that we don't want to compute inverses of matrices larger than 1000x1000, which is required by Mahalanobis, AFAIK. (The comment was wrong, it should say 1000, not 100). Therefore, the only problem was that axis was wrong -- as you already discovered.
If 2000x2000 computes in reasonable time, we can increase this limit. But let us have some limit; also, this check was certainly introduced for a reason.
> Distance: Fix check and error message for Mahalanobis distance

- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
Fixes #5635.
In #5635 I wrote about putting the checkbox into table. I disagree with my ex-self: editor for modifying the feature is at the top, not in the table. If we do change the widget to have controls in the table (including all combos?!), then we'd put the checkbox there, too.
> [ENH] Feature Constructor: Option to put new variable into metas

- Orange/widgets/unsupervised/owhierarchicalclustering.py
The widget crashes when selected `Color by` variable is from metas (and therefore has type object).
- cast column to float
> [FIX] Hierarchical Clustering: Color by metas

- conda-recipe/meta.yaml
- requirements-gui.txt
- tox.ini
Because of this change https://github.com/biolab/orange-canvas-core/pull/243, I think it would be nice to make sure Orange uses the newest version of orange-canvas-core
Increase the required orange-canvas-core version to 0.1.28
> Increase required orange-canvas-core version

- Orange/preprocess/score.py
- Orange/tests/test_score_feature.py
Learners use preprocessors. Some, like `Continuize`, create multiple features from a discrete feature. Therefore, when using learners as scorers, these multiple scores need to be consolidated into a single score for the original feature.
This commit fixes an infinite loop which appeared when the (internally) transformed variable did not identify its predecessor as its `compute_value`'s `.variable`.
Related, but won't be worked on within this PR: Orange seems to have two mechanisms for identifying predecessors: (1) `variable.source_variable` and (2) `variable.compute_value.variable`. Here the code seems to only look at the second one. Do we ever use the first one? To me that would be more straightforward.
> [FIX] Fix potential infinite loop when using learners for feature scoring

- pylintrc
(Re)Added checkers:
- ~~`no_self_use` was moved to extensions. If we want to keep it (which is up to discussion) it needs to be loaded explicitly.~~
- `eq_without_hash` is a new checker. It needs to be loaded explicitly, and I think we want it.
Removed options:
- `...-name-hint`: no effect from pylint 1.8, removed in pylint 2.4
- `optimize-ast`, `files-output` removed in pylint 2.0
- `no-space-check`, `bad-functions` removed in pylint 2.6
> pylintrc: Update configuration file

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
Predictions widget crashed when drawing error bars for data instances for which the class was not given.
This happened because class was `None` but the delegates tested for `np.isnan`.
Test for `None` and `nan`.
> [FIX] Predictions: Fix crash in error delegate when actual value is unknown

- Orange/data/table.py
- Orange/tests/test_table.py
When the table is created from the table, the attributes dict is not copied, which means that changing attributes in the new table also change attributes in the original table.
Deep copy the attributes dictionary when creating a table with `from_table` or `from_table_rows`. As discussed at the meeting, the copy should be a deep copy also to copy the structures inside the dictionary, such as lists or sets.
> [FIX] Table - copy attributes when creating table from table

- Orange/widgets/model/owloadmodel.py
The title was 'Open Distance File', most likely copy-pasted and forgotten to update. I changed it to 'Open Model File'.
> LoadModel Widget: fix open dialog title

- Orange/widgets/visualize/owtreeviewer.py
Fixes #6190.
Align numbers. Skip empty classes.
Before:
After.
Much better.
Also much better for root.
And those in between.
> Tree Viewer: Align distribution tooltip and skip empty classes

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
The tests added in the first commit of this PR fail. The new tests test a combination of unit (ones) weights and NaNs, which should give exactly the same results as unweighted samples. Well, they do not, because we have been sloppy: the current code also divided with non-used weights (corresponding to NaN data entries).
The `nanmean` function was easy to extend with weights. For sparse I just needed to add a parameter. For dense I did an extension. Now, `stats` uses `nanmean` internally.
> [FIX] Weighted mean computation in Orange.statistics.util.stats

- Orange/statistics/distribution.py
- Orange/statistics/util.py
- Orange/tests/test_statistics.py
Implements weighted variance (and mean) computation that works with sparse, dense. Also handles NaNs.
Needed in #6202.
Merge after #6204.
> Weighted variance computation for sparse and dense arrays

- .readthedocs.yaml
- doc/conf.py
- doc/data-mining-library/source/conf.py
- doc/data-mining-library/source/reference/data.table.rst
- doc/development/source/conf.py
- doc/visual-programming/source/conf.py
- requirements-doc.txt
- requirements-readthedocs.txt
Orange3 documentation consists of multiple sphinx projects, which are built as subprojects at the Read the Docs. The documentation each subproject builds is set in advanced settings at RTD. That prevents us from using the `.readthedocs.yaml` file to set a higher version of Python since `.readthedocs.yaml` overwrites all advanced settings.
We need to change the version of Python used to build documentation (the default is 3.7) since we cannot increase some package versions in Orange.
In order to use `.readthedocs.yaml` to set a different version of Python, we need to set the documentation project somewhere outside the advanced settings in RTD. Using sphinx-multiproject enables us to set it as an environmental variable which does not get overwritten by `.readthedocs.yaml`.
> Doc - use sphinx-multiproject for RTD subprojects

- conda-recipe/meta.yaml
- requirements-core.txt
- tox.ini
Tests on oldest fail after #6174, "Feature Statistics: Use deferred commit + **minor warning fix** due to the "minor warning fix" part. In scipy 1.9, `scipy.stats.mode` introduced argument `keepdims` and warns if it's not set. In Scipy 1.8 this argument did not exist.
We overlooked this because we got so used to some test configurations failing that we don't even check. Me very included.
We could
- ignore this failing configuration (obviously: no),
- remove `keepdims` argument and live with warning, but this would hunt us some day,
- do something fancy to pass the argument only when necessary,
- raise required version of Scipy from 1.3 to 1.9, which would then cascade to some other libraries (numpy 1.17 -> 1.19.5)
I see no reason against the latter. Does anybody?
> CI: Raise required oldest sicpy to 1.9

- Orange/data/io.py
Ref: https://github.com/biolab/orange3/issues/6161#issuecomment-1311675148
Add support for google drive share urls.
> [ENH] io.UrlReader: Add support for google drive share urls

- Orange/data/sql/table.py
- Orange/data/table.py
- Orange/preprocess/normalize.py
- Orange/statistics/basic_stats.py
- Orange/statistics/util.py
- Orange/tests/test_statistics.py
- benchmark/bench_preprocess.py
Fixes #5219
The computation of distributions is slow (it works through contingencies and requires sorting).
This slowdown was especially problematic for dask tables.
~~The new code does not currently support weights! Supporting them would require making a weighted variance computation. Should we go there?~~ Done in #6205.
Requires #6204 and #6205.
Testing performance on 1000x1000 tables.
Before:
```
[normalize_only_parameters] with 5 loops, best of 3:
min 233 msec per loop
avg 235 msec per loop
[normalize_only_transform] with 5 loops, best of 3:
min 120 msec per loop
avg 121 msec per loop
```
After:
```
[normalize_only_parameters] with 5 loops, best of 3:
min 71.7 msec per loop
avg 73.3 msec per loop
[normalize_only_transform] with 5 loops, best of 3:
min 117 msec per loop
avg 119 msec …
```
> [ENH] Faster normalization

- Orange/widgets/visualize/utils/plotutils.py
I've seen a test failing with division by zero in `InteractiveViewBox.tag_history`.
Change division into multiplication.
> InteractiveViewBox.tag_history: replace division by multiplication

- Orange/data/filter.py
- Orange/data/sql/filter.py
- Orange/data/tests/test_variable.py
- Orange/data/variable.py
- Orange/preprocess/impute.py
- Orange/preprocess/tests/test_impute.py
- Orange/preprocess/transformation.py
- Orange/tests/test_filter.py
Missing `__eq__` and `__hash__` in classes used for `compute_value` seems to have become the large source of warnings. In many cases, `__eq__` and `__hash__` are not needed, but the tests we have still require providing the two methods (which then just call inherited methods).
This cannot be avoided automatically, I think. The warning cannot detect whether the instance's attributes were added by instances actual type or by its parent. Furthermore, in theory, the parent's attributes can be used differently and hence require reimplementing hash.
The class can now add a class attribute `InheritEq = True`. If set, it supresses the warning. The attribute is checked for in type's `__dict__` and is thus not inheritable.
> Add option InheritEq and fix several missing __eq__s and __hash__s

- Orange/data/table.py
- Orange/widgets/data/owfile.py
- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/utils/state_summary.py
- Orange/widgets/utils/tests/test_state_summary.py
For big tables counting unknowns takes too long (especially important for table summaries that all widgets have). Therefore we opted to skip it for big tables.
The original code was also slightly rewritten to avoid a separate NaN check, which does not seem to gain anything (just an additional pass through the data).
This PR also fixes a bug with `get_nan_frequency_attribute` and sparse tables.
This comes from the `dask` branch.
> Avoid counting unknowns for big tables

- Orange/widgets/data/owdatainfo.py
- Orange/widgets/data/tests/test_owdatainfo.py
- Data Info widget used labels as widget attributes, which made it untranslatable.
- The code itself was an endless spago that was putting together various texts.
- Data is stored in dictionary, which is used to fill out the widget and the report.
- Each value is computed by a separate different method.
- Widget no longer contains n boxes but two (basic properties and table attributes), which contain rich texts.
The latter can be reformed back into boxes, though I prefer the new form.
Before:
Now:
> Datainfo: Reimplement to show rich text

- Orange/widgets/data/owpreprocess.py
- Orange/widgets/data/tests/test_owpreprocess.py
Report for this widget showed class names instead of parameters.
Classes `RemoveSparseEditor` and `ImputeEditor` missed `__repr__`, which is used by report to show parameters.
> [FIX] Preprocess: Fix reporting for remove sparse and impute

- Orange/statistics/util.py
- Orange/tests/test_basic_stats.py
- Orange/tests/test_statistics.py
- Orange/widgets/data/tests/test_owtable.py
Fixes https://github.com/biolab/orange3/pull/6208#issuecomment-1327209138
Compute stats for an empty array / Table.
> [FIX] stats: Handle empty array

- README.md
- setup.py
Now there is also pyqt6 and we still force our users to also install PyQt5. This trick we had is also dangerous because it behaves differently with wheels and source installs.
Reverts #5593.
After merging this PR please also consider: https://github.com/biolab/orange3/pull/6153
> [FIX] Remove pyqt5 install magic

- Orange/widgets/data/owdatasampler.py
- Orange/widgets/data/tests/test_owdatasampler.py
Fixes #6207.
Widget already treated a 100 % sample as special case. The same code is now also used for empty sample.
Related change: when setting the proportion, widget allowed to set 0 %, but when setting the number of instances, it enforced a minimum of 1. Now it also allows 0.
> [FIX] Data Sampler: Fix crash when requesting an empty sample

- Orange/widgets/unsupervised/owdistancematrix.py
- Orange/widgets/unsupervised/tests/test_owdistancematrix.py
Fixes #6226.
Choose the string variable with most distinct values as default label, otherwise class var otherwise enumerate.
> Distance Matrix: String variable with most distinct values as default label

- conda-recipe/meta.yaml
conda cannot build the included recipe on Python 3.9 and later because numpy 1.14 is not available for them. 
Let default conda-build provide the build numpy version.
> [FIX] conda-recipe: Remove explicit host numpy pinning

- Orange/widgets/visualize/ownomogram.py
> Nomogram: Nicer options layout

- Orange/widgets/data/owcreateclass.py
- Orange/widgets/data/owcreateinstance.py
- Orange/widgets/data/owdiscretize.py
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/owpivot.py
- Orange/widgets/data/tests/test_owpivot.py
Pivot used enum names as checkbox labels. This can't be translated. It also pickled enums, which is not recommended.
Edit Domain had a dialog that made assumptions about widths of labels (it simplified the laying out by assuming that two labels are much longer than the third; in Slovenian translation, this cause some ugly white space)
> Translation fixes: Pivot and Edit Domain

- Orange/data/table.py
- Orange/tests/test_table.py
A transposed table is missing a table name.
Assign original table name to transposed table name.
> Table: Assign name to transposed table

- Orange/widgets/evaluate/tests/test_utils.py
- Orange/widgets/evaluate/utils.py
💥  💥  💥  💥  💥  💥 
Remove support for passing Variable in favor of Domain when calling usable_scorers
> usable_scorers: Remove support for passing Variable in favor of Domain

- conda-recipe/meta.yaml
- requirements-core.txt
I like tests that pass. This is a temporary fix. #6249 should properly fix the issue.
> Avoid scikit-learn>=1.2.0 due to changes in PCA

- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/unsupervised/tests/test_owhierarchicalclustering.py
Reuse GraphicsWidgetView in OWHierarchicalclustering instead of custom layouting.
Maybe fixes https://github.com/biolab/orange3/issues/6236
Use GraphicsWidgetView for layout
> owhierarchicalclustering: Use GraphicsWidgetView for layout

- Orange/widgets/data/owcolor.py
- Orange/widgets/data/tests/test_owcolor.py
Fixes quasars/orange-spectroscopy#652
The Color widget currently saves `AttrDesc` in contexts. The problem is that `AttrDesc`  contains a variable. Because the contexts only match by names (and values for discrete features) the saved variables get colored instead of the ones on the input.
After this fix, the variable descriptors on the input are always used when creating colored variables instead of the ones stored in the context.
Also, compute_values do not need to be stored in settings (within `AttrDesc`) and are therefore removed.
> [FIX] Color: fix coloring of computed (processed) variables

- Orange/widgets/visualize/owbarplot.py
- Orange/widgets/visualize/tests/test_owbarplot.py
Bar Plot fails when we select to annotate by Enumeration.
`get_labels` returns a `np.array` of type `int64` instead of list or array of `str`.
Change numbers into strings.
> [FIX] Bar Plot: Fix annotation by enumeration

- Orange/classification/simple_random_forest.py
- Orange/classification/simple_tree.py
- Orange/regression/simple_random_forest.py
This avoids creating intermediate tables in `predict()`, which then create problems onwards because, currently, creating a table with an array locks the array given. The array remains locked even when the intermediate table is disregarded. 
This PR is a fix for some crashes in biolab/orange3-explain#54.
The big issue here, which remains, is how Orange's Tables behave: if arrays were copied in init, only internal arrays would be locked. Anyway, I believe the code is now a bit cleaner.
> [FIX] Implement predict() in simple tree and simple RF models

- Orange/widgets/visualize/owpythagoreanforest.py
- Orange/widgets/visualize/tests/test_owpythagoreanforest.py
> [FIX] Pythagorean Forest: Fix report

- Orange/data/table.py
- Orange/tests/test_table.py
`Table.from_table` does not work correctly with boolean indices, but `from_table_rows` does. See the added test. 
Much of the code in `from_table` expects either slices or integer row indices, so boolean indices are converted to that.
The second last commit is a minor refactor of handling of `W` and `ids` in `from_table` so that it becomes equivalent to the `from_table_rows` implementation. Why did we handle them differently? `from_table` had some code from 2015 at that so I though it might not be needed anymore.
The last commit splits off two well-defined operations from `from_table` so that the code is a bit cleaner.
> [FIX] Table.from_table works correctly with boolean indices

- Orange/widgets/data/owfeatureconstructor.py
- Orange/widgets/data/tests/test_owfeatureconstructor.py
Fixes https://github.com/biolab/orange3/issues/6265
Enable comprehensions and lambdas in expressions
> [ENH] Feature Constructor: Enable comprehensions and lambdas in expressions

- .github/workflows/test.yml
- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/owgroupby.py
- Orange/widgets/data/tests/test_oweditdomain.py
- Orange/widgets/model/tests/test_owgradientboosting.py
- conda-recipe/meta.yaml
- requirements-core.txt
- requirements-opt.txt
- tox.ini
In Edit Domain has a timebomb suggesting increasing the minimum version of Pandas and removing a workaround for features not supported in older versions.
- Removing timebomb
- Removing extra code in the Edit domain and the Group By widgets that changed time to UTC is no longer required since Pandas from version 1.4 supports subtracting different timezones.
- Fix XGB test since `get_params` changed https://github.com/dmlc/xgboost/pull/8634
> Resolve Edit Domain (datetime to epoch) timebomb

- Orange/evaluation/scoring.py
- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/owtestandscore.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
- Orange/widgets/evaluate/tests/test_owtestandscore.py
- Orange/widgets/evaluate/tests/test_utils.py
- Orange/widgets/evaluate/utils.py
- `ScoreTable`, which is used in Test and Score, and in Predictions, has a hard coded list of scorers, which defines the (default) visibility and the order. New scores are thus invisible by default.
- The names of classes are used for names of columns. It is thus impossible to translate them. A `name` attribute exists, but is not defined and defaults to class name.
- The user may not be aware that (s)he can choose additional scores by right-clicking the header.
- Scorers define default visibility and priority as class attributes.
- Visibility settings are stored as "hints", so new scorers (e.g. from add-ons) may be visible if they that's their default.
- The `name` attribute is now defined, but in settings the scorers are referred to by their class names, so settings "survive" the change …
> [ENH] Improve scorer selection in Test and Score and predictions

- Orange/widgets/utils/graphicstextlist.py
Fixes #6285.
Silhouette seemed to often elide the longest label; "Proteas" also became "Prote..." without an obvious reason.
I added a single pixel to label width and can no longer reproduce this. I assume it could had been some rounding issue.
@larazupan, if you know how to checkout a pull request, please try whether this works for you, too.
> [FIX] Silhouette Plot: Fix needless eliding

- Orange/misc/distmatrix.py
- Orange/misc/tests/test_distmatrix.py
- Orange/misc/tests/test_distmatrix_xlsx.py
- Orange/widgets/unsupervised/owdistancematrix.py
- Orange/widgets/unsupervised/tests/test_owdistancematrix.py
- Orange/widgets/utils/distmatrixmodel.py
- Orange/widgets/utils/state_summary.py
- Orange/widgets/utils/tests/test_distmatrixmodel.py
- benchmark/bench_datadelegate.py
The issue was basically to add summary previews for distance matrix outputs ... and as usual this small change resulted in major rewrite of a widget.
This included support for non-square matrices and visual changes.
**Based on #6245.**
- Widget can now show non-square matrices (not that we really need this)
- Horizontal and vertical header are no longer necessary the same
- Detection of default labels is now more flexible
- Model and view are extracted into a separate file
- ... where they are used by summary previewer
- Colored borders around cells were awful and are removed.
> Distance Matrix: Allow non-square matrices; Previews in summary

- Orange/classification/gb.py
- Orange/classification/random_forest.py
- Orange/classification/xgb.py
- Orange/regression/random_forest.py
- Orange/tests/test_random_forest.py
- Orange/tests/test_score_feature.py
- Orange/widgets/model/owrandomforest.py
- Orange/widgets/model/tests/test_owrandomforest.py
- conda-recipe/meta.yaml
- requirements-core.txt
- requirements-opt.txt
- tox.ini
Fixes #6217, #6218, #6219
- set default RandomForestLearner.max_features to `sqrt`
- set default RandomForestRegressionLearner.max_features to `1.0`
- set default GBClassifier.loss to `log_loss`
- remove `use_label_encoder` parameter from XGBClassifier 
- remove `use_label_encoder` parameter from XGBRFClassifier
- set catboost minimum version
> Random Forest, Gradient Boosting: Handle deprecated parameters

- Orange/evaluation/scoring.py
- Orange/tests/test_evaluation_scoring.py
- doc/visual-programming/source/widgets/evaluate/testandscore.md
Add `Matthews correlation coefficient` to classification scores.
> [ENH] MCC: Add Matthews correlation coefficient score

- Orange/widgets/unsupervised/owsom.py
- Orange/widgets/unsupervised/tests/test_owsom.py
Fixes #6254 
SOM throws error when receiving only one row, added tests for receiving only one row of data.
> Fix for bug in SOM when receiving one row of data

- Orange/widgets/data/tests/test_owselectcolumns.py
- Orange/widgets/utils/listfilter.py
Fixes: https://github.com/biolab/orange3/issues/6287
In PyQt6 Qt.DropAction is not an integer.
*  Change dragDropActionDidComplete signal type (in PyQt6 Qt.DropAction is not an integer)
> [FIX] listfilter: Fix dragDropActionDidComplete signal type

- Orange/widgets/data/owcolor.py
Crashes because drawPixmap does not support the current given types.
> [FIX] Fix Color for python 3.10

- Orange/tests/test_third_party.py
Setuptools 66.0.0 was released and one test does not run.
I removed the offending test and added 2 that make more sense for our repository.
> Adapt tests for the new setuptools version

- Orange/widgets/data/owfile.py
- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/utils/combobox.py
- Orange/widgets/utils/tests/test_combobox.py
- Orange/widgets/utils/textimport.py
Fixes: gh-6250
Fix used combobox so it inserts new items in the model on focus out.
> [FIX] File Widget: Fix recent urls save/restore

- Orange/widgets/unsupervised/owmds.py
- requirements-gui.txt
- tox.ini
Fixes #6228.
- Optimization ensures that at least 0.1 s passes between each refresh.
- Added step button, reorganize layout of buttons.
- I thought the widget was not updating. It was, but it was very slow because of cosmetic lines with widths different than 1. Enabling `segmentedLineMode` (available from latest pyqtgraph) makes it smooth. Drawing lines during optimization is no longer disabled.
- Graph now recomputes closest pairs only when necessary.
This PR also raises required versions
- pyqtgraph to 0.13.1; segmented line mode may also be useful for speeding up other widgets.
- (oldest) pyqt >=15.2 (I don't know what was this needed; it used to be 15.* and pip couldn't resolve it?!)
- (oldest) numpy ==  1.20, because pyqtgraph is not compatible with 1.19.5, which was pinned …
> MDS: Timing of updates, step button, visual improvements

- Orange/widgets/visualize/owruleviewer.py
Fixes #6299.
I removed learner parameters from report. They should be reported in learner, not here.
> Rule Viewer: Remove learner params from report

- Orange/widgets/data/owcsvimport.py
owcsvimport (pandas_to_table) stil uses deprecated np.float alias
Replace use of deprecated np.float alias
> owcsvimport: Replace use of deprecated np.float alias

- Orange/statistics/util.py
- Orange/tests/test_statistics.py
> [FIX] stats.utils: Don't count zeros as nans

- Orange/widgets/data/owgroupby.py
- Orange/widgets/data/tests/test_owgroupby.py
Resolves https://github.com/biolab/orange3/issues/6065
Adding Q1, and Q3 aggregations, moving min and max to the first column.
Mini test refactoring
> [ENH] Group By - add quantile aggregations

- Orange/data/domain.py
- Orange/tests/test_classification.py
- Orange/tests/test_domain.py
Fixes  #6202, where the domain could not be unpickled if data included something based on SharedComputeValue (that redefined `__hash__`) and was further preprocessed before learning (thus only scikit-based learners failed but TreeLearner did not).
Unpickling dictionaries that include objects that redefine `__hash__` as keys is sometimes problematic (when said objects do not have `__dict__` filled-in yet in but are used as keys in a restored dictionary).
See the following for a problem description. https://petrounias.org/articles/2014/09/16/pickling-python-collections-with-non-built-in-type-keys-and-cycles/
Orange's `Domain` includes `_indices` for name-based or var-based indexing. That is a dictionary with `Variables` as keys, and these can cause problems during unpickling. Because …
> [FIX] Fix unpickling domains: do not pickle indices (which can cause problems)

- Orange/widgets/model/tests/test_owcalibratedlearner.py
- Orange/widgets/model/tests/test_owcurvefit.py
- Orange/widgets/model/tests/test_owgradientboosting.py
- Orange/widgets/model/tests/test_owlogisticregression.py
- Orange/widgets/model/tests/test_owneuralnetwork.py
- Orange/widgets/model/tests/test_owrandomforest.py
- Orange/widgets/model/tests/test_owrulesclassification.py
- Orange/widgets/model/tests/test_owstack.py
- Orange/widgets/tests/base.py
- Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py
Tests fail after https://github.com/biolab/orange-widget-base/pull/228 because they click disable buttons.
Call `clicked.emit()` directly.
> WidgetLearnerTestMixin: Fix for clicks of disabled buttons

- Orange/widgets/data/owconcatenate.py
- Orange/widgets/data/tests/test_owconcatenate.py
Coconcate widget does not preserve table names when compute value is ignored, so `unknown` appears in the `Source ID` column instead of the correct name.
Preserve table name also when ignore compute value is ticked.
> [FIX] Concatenate - preserve table names when compute value ignored

- Orange/widgets/data/owrank.py
- Orange/widgets/data/tests/test_owrank.py
- Orange/widgets/utils/__init__.py
Probably fixes https://github.com/biolab/orange3/issues/6229
Store the sorting setting as an integer and transform it to Qt.SortOrder when passed to model/wiev
> [FIX] Rank - make sorting setting PyQt6 compatible

- Orange/widgets/visualize/owboxplot.py
The sampling added for initial dask compatibility sometimes caused differences in the order of grouping and variable relevance.
> OWBoxplot: fix failing tests

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
When transforming continuous variable to time, Edit Domain does not set `have_time` and `have_date` attributes.
Fixes https://github.com/biolab/orange3/issues/5648
Set to mentioned attributes when transforming Continuous to TimeVariable
Additionally, when implementing #5819, it was agreed that CountinousVariable always transforms to Time as UNIX epoch (seconds from 1970-01-01). Still format selection dropdown remained active, which can confuse the user. In this PR, I lock the format selection dropdown when transforming ContinousVariable (and TimeVariable - which was done already before).
> [FIX] Edit Domain - set have_time and have_date to time variables

- Orange/widgets/utils/colorgradientselection.py
- Orange/widgets/utils/intervalslider.py
- Orange/widgets/utils/tests/test_colorgradientselection.py
Resolves #6323.
Adds `IntervalSlider` with similar behavior as `QSlider`, but with two handles.
To test it, it is used in color gradient selection. The change can be observed in widgets Heat Map and Distance Map.
> Implement IntervalSlider; use it for color gradient selection

- Orange/widgets/unsupervised/owmds.py
- Orange/widgets/unsupervised/tests/test_owmds.py
Fixes #6070.
To reviewer: please check that I indeed called `update_stress` from all places where it's needed -- and that it's not called multiple times.
I don't know where to show the stress. Optimization box was about the best place. I don't want to put it on the graph, because then we'd need to at least allow the user to move it and ... no.
> [ENH] MDS: Show Kruskal stress

- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/tests/test_owselectrows.py
In PyQt6 checkState is not integer anymore (it is enum), so checked elements (in one of) are not correctly considered.
Fix that checked groups are correctly selected
> [FIX] Select Rows - Fix checked groups not considered in PyQt6

- conda-recipe/meta.yaml
- requirements-core.txt
Tests fail after the new openTSNE release.
> Avoid openTSNE 0.7.0 due to segfaults

- Orange/widgets/visualize/owtreeviewer.py
- Orange/widgets/visualize/owtreeviewer2d.py
Some labels were created using f-strings and thus impossible to translate
> Tree Viewer: Replace format with f-string

- Orange/widgets/visualize/utils/plotutils.py
Selection by dragging a rectangle crashes in Choropleth.
Choropleth is not a projection and doesn't "jitter" anything, yet it uses `InteractiveViewBox`. Drag event therefore crashes when it tries to suspend jittering.
Call (`un`)`suspend_jittering` only if such method exists.
No tests. I'm not creating drag events to check this single if with an obvious test. :)
> InteractiveViewBox: Don't suspend_jittering for graphs that don't support it

- Orange/widgets/unsupervised/owmds.py
Graph and stress were updated twice in a row - in last call of `on_partial_result` and in `on_done`
Remove updates in `on_done` - @VesnaT , @janezd please check and confirm that they were indeed unnecessary and that `on_partial_result` is always already called before it.
> [FIX] MDS: Remove repeated updates at the end of optimization

- Orange/data/variable.py
- Orange/tests/sql/test_sql_table.py
Cannot create a discrete `Value` from it's string representation. This means indexing into SQLTable like `table[row, variable]` doesn't work.
add special case for `DiscreteVariable` in Values `__new__` method as well as extending sqltable tests.
> FIX: create Values from strings

- Orange/data/table.py
- Orange/data/tests/test_table.py
- Orange/widgets/visualize/owtreeviewer.py
`Table.copy()` does not copy ids, but uses a reference to existing ids, as detected by tests in Image Analytics (https://github.com/biolab/orange3-imageanalytics/actions/runs/4314962156/jobs/7529016431).
> Table: Fix ensure_copy to also check ids

- Orange/widgets/data/owdatasets.py
- Orange/widgets/data/tests/test_owdatasets.py
Data sets in the repository now have a language flag, and Data Sets widget allows user to filter files by language.
Default is English, but translations of Orange to other languages can change this default.
> [ENH] Datasets: Add language selection

- Orange/widgets/visualize/owboxplot.py
When Box plot was resized, it always scrolled to the center.
Position of the view is no longer changed manually. Qt's default behaviour is appropriate.
We manually scroll to the top when the view is changed entirely, that is, when "rows" no longer correspond to the same values as before. This happens when the widget receives new data or the grouping variable is changed.
> Box Plot: Remove scroll on resize

- Orange/widgets/utils/state_summary.py
Trubar does not recognized single-dispatched functions with the same name as different functions.
Function are now renamed. Names don't matter anyway.
> State summaries: Use different names for single-dispatched functions

- Orange/widgets/unsupervised/owlouvainclustering.py
After https://github.com/biolab/orange-widget-base/pull/228, Louvain's particular handling of deferred commit left the button disabled on change -- and at the same time telling the user to click it.
To test, disable auto commit and change the number of PCA components. Button remains disabled.
Explicitly enable the button.
No tests. In the longterm, we would refactor this widget to use deferred commit.
> Louvain Clustering: Enable Apply button on change

- Orange/widgets/data/tests/test_owtable.py
- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_itemmodels.py
Trying to avoid the use of `RowInstance` in anticipation of upcoming dask integration (see #6267).
Includes preliminary tests.
> TableModel avoid RowInstance

- Orange/widgets/visualize/tests/test_owmosaic.py
Tests timeout on Macs.
Decrease the number of combinations scored by VizRank. In the tests that still takes 0.5 s on my machine, I increased the timeout from 5 s to 10 s, just to be sure.
> Mosaic tests: Speed up the tests, increase timeout where necessary

- .github/workflows/doc.yml
- .github/workflows/test.yml
ubuntu-18.04 actions runners are deprecated
replace obsolete ubuntu-18.04 runners
> [MNT] CI: Update/replace obsolete ubuntu-18.04 runners

- conda-recipe/meta.yaml
- requirements-core.txt
- tox.ini
Temporary alternative to #6395.
Pandas 2 includes too many backward incompatibilities, in particular related to datetime, which we use heavily. Hence it'd be wise to pin in at least before release.
> Pin pandas to <2

- Orange/widgets/data/utils/tableview.py
After merging #6346, tests sometimes fail with
https://github.com/biolab/orange3/actions/runs/4577138548/jobs/8085131305#step:8:7161 - if they get this far. In #6346, we haven't seen this because they crashed earlier. I've seen this on all OSs, and on PyQt5 and 6.
`QObject.disconnect()` (https://github.com/baoboa/pyqt5/blob/11d5f43bc6f213d9d60272f3954a0048569cfc7c/qpy/QtCore/qpycore_pyqtboundsignal.cpp#L535)  is failing on `false` result from `QObject::disconnect()`. The latter returns `false` for wrong combinations of argument (https://github.com/qt/qtbase/blob/46b483ace0248bec349e3c2e87736f717510d400/src/corelib/kernel/qobject.cpp#L3104), which should not be the case here, or when no signals were disconnected (https://github.com/qt/qtbase/blob/46b483ace0248bec349e3c2e87736f717510d400/src …
> widgets.data.utils.tableview: Fix failing test when disconnecting corner button

- Orange/widgets/data/tests/test_owpythonscript.py
`pythoneditor` tests were called twice (additionally because of import from `test_owpythonscript`. It seems caused various types of Segfaults.
Removing unnecessary imports from `test_owpythonscript`.
> Remove unnecessary imports from test_owpythonscript

- Orange/widgets/data/owpaintdata.py
- Orange/widgets/evaluate/owcalibrationplot.py
- Orange/widgets/evaluate/owliftcurve.py
- Orange/widgets/evaluate/owrocanalysis.py
- Orange/widgets/unsupervised/owcorrespondence.py
- Orange/widgets/unsupervised/owdistancemap.py
- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/unsupervised/owpca.py
- Orange/widgets/unsupervised/owsom.py
- Orange/widgets/visualize/owbarplot.py
- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/owheatmap.py
- Orange/widgets/visualize/owlineplot.py
- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/ownomogram.py
- Orange/widgets/visualize/owpythagorastree.py
- Orange/widgets/visualize/owpythagoreanforest.py
- Orange/widgets/visualize/owsieve.py
- Orange/widgets/visualize/owsilhouetteplot.py
- Orange/widgets/visualize/owtreeviewer.py
- Orange/widgets/visualize/owtreeviewer2d.py
- Orange/widgets/visualize/owvenndiagram.py
- Orange/widgets/visualize/owviolinplot.py
- Orange/widgets/visualize/utils/widget.py
We don't know which object types are passed to methods for reporting, saving charts and copying to clipboard.
- Added comments with one of the four types handled by `ImgFormat` (`pg.GraphicsItem`, `QGraphicsScene`, `QGraphicsView`, `QWidget`), and the actual derived type, if applicable.
- Mosaic and Tree Viewer passed the object to be plotted as an argument to `report_plot`. If `graph_name` is given, it's better to use if for `report_plot` to avoid ambiguity.
> Annotate graph_name with graph's types

- Orange/widgets/unsupervised/owmanifoldlearning.py
- Orange/widgets/unsupervised/tests/test_owmanifoldlearning.py
Method parameters were written as variables (variable names were used as text in report and it was not neatly visualised). 
Added new function `get_report_parameters` for every method in order to access it in `send_report` and displayed text in report.
Added new test for report.
> Manifold learning: change in report display

- Orange/widgets/data/owtable.py
Due to bad refactoring multiple connections to selectedFinished signal were established (on each input change) leading to multiple calls to commit.
Remove multiple connections to 'selectionFinished'
> [FIX] owtable: Remove multiple connections to 'selectionFinished'

- .github/workflows/test.yml
- tox.ini
Codecov is not available at pyp anymore
Use codecov-actions instead
> Replace pip's codecov with codecov-actions

- Orange/widgets/data/owtable.py
- Orange/widgets/data/tests/test_owtable.py
- Orange/widgets/data/utils/models.py
- Orange/widgets/data/utils/tableview.py
- Orange/widgets/data/utils/tests/test_tableview.py
Since #6370 errors appear in data table when a sparse basket column in on input.
When clicking 'Show variable labels':
```
File "/home/ales/devel/orange3/Orange/widgets/data/utils/tableview.py", line 175, in __headerDataChanged
text += "\n".join(key for key, _ in items)
File "/home/ales/devel/orange3/Orange/widgets/data/utils/tableview.py", line 175, in <genexpr>
text += "\n".join(key for key, _ in items)
ValueError: not enough values to unpack (expected 2, got 1)
```
When trying to sort a basket column:
````
File "/home/ales/devel/orange3/Orange/widgets/data/owtable.py", line 341, in _on_sort_indicator_changed
self.stored_sort.append((var.name, order))
AttributeError: 'NoneType' object has no attribute 'name'
````
Fix …
> [FIX] tableview: Fix errors with sparse basket columns

- Orange/widgets/data/owtable.py
- Orange/widgets/data/tests/test_owtable.py
- Orange/widgets/utils/itemdelegates.py
Closes: https://github.com/biolab/orange3/issues/6315
Add Data Subset input and indicate the subset in the table
Uses opacity of non subset data to emphasize subset to match other visualization widgets, and also adds an indicator to the row header (I don't like either).
Add subset input
> [ENH] Data Table: Subset input

- Orange/widgets/data/owsql.py
Made a message about the limit. Database table length and actual limit
Now the message looks like this:
```
Data appears to be big. Do you really want to download it to local memory?
Table length: 1,000,100. Limit 1,000,000
```
> Add message `Table length` and `Limit`

- Orange/projection/pca.py
> [FIX] pca: n_features_ attribute of decomposition.PCA is deprecated in favor of n_features_in_

- Orange/widgets/unsupervised/owsom.py
- Orange/widgets/unsupervised/tests/test_owsom.py
The orange widget base does not support settings with type `np.ndarrray`
```
File "../orange-canvas-core/orangecanvas/application/canvasmain.py", line 1612, in save_swp
if not document.isModifiedStrict() and undoStack.isClean():
File "../orange-canvas-core/orangecanvas/document/schemeedit.py", line 664, in isModifiedStrict
node_properties(self.__scheme)
File "../orange-canvas-core/orangecanvas/document/schemeedit.py", line 2538, in node_properties
scheme.sync_node_properties()
File "../orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 99, in sync_node_properties
if settings != node.properties:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Store SOM's settings in a list instead.
> [FIX] SOM: Store selection Settings in list instead of np.ndarray

- Orange/widgets/unsupervised/owsom.py
- Orange/widgets/unsupervised/tests/test_owsom.py
Fixes https://github.com/biolab/orange3/issues/6424
Similarly in t-SNE, it is better that user is warned to rerun optimization after changing parameters.
> [ENH] SOM - Warn user to restart optimization after parameter change

- Orange/widgets/data/owneighbors.py
- Orange/widgets/data/tests/test_owneighbors.py
The resulting instances in the Neighbour widget are in the original order. It would be better to sort them according to distance.
Sort neighbours according to distance in ascending order.
> [ENH] Neighbours - Sort resulting instances in order according to distance

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Fixes #6414, if I'm guessing correctly.
None of context settings were variables, so all contexts always matched. While contexts piled up, the widget most likely picked the most recent context and used whatever was applicable.
Instead of context setting with changes for particular domain, the widget now uses a schema-only settings with hints that are matched to any applicable variables. To prevent bloating, up to 1000 hints are kept (unless the current domain contains more).
> [FIX] Edit Domain no longer forgets its settings

- Orange/widgets/data/owselectcolumns.py
- Orange/widgets/data/tests/test_owselectcolumns.py
Fixes #5897.
Drag & Drop between VariablesListViews rejects drops that contain any variables of unacceptable type.
- Reimplement drag procedure to accept partially correct drops.
- Same for buttons: the are enabled if there is anything to move, and move only what they may
- N/A: Documentation
> [ENH] Select Columns: Accept partially correct drops

- tox.ini
MacOS Python 3.8 run is failing on installing dependencies since Catboost increased the minimal OS version for wheels to 11 (which should work fine on macOS-latest). 
It is the GitHub action's issue. Read more here: https://github.com/catboost/catboost/issues/2371
I think. Currently, we have two options:
1. install the ninja package to enable building Catboost from the source
2. use Catboost<1.2
I first tried option 1, but it took too long to build on GH actions, so now I am considering option 2.
> CI - Install catboost<1.2 on MacOS, python 3.8 runner (temporary solution)

- Orange/widgets/gui.py
- Orange/widgets/tests/test_gui.py
When using `ExtendedSelection` or `MultiSelection` and all values are unselected, the setting attribute still keeps the old selection.
Set the setting attribute to the empty list when all values are unselected.
> [FIX] ListView - empty variable when all values unselected

- Orange/projection/manifold.py
Parameter eigvals is deprecated and will be removed in scipy==1.12.0
Replace the parameter with subset_by_index parameter.
> torgerson: Replace deprecated parameter

- .github/workflows/test.yml
- Orange/tests/test_txt_reader.py
Add Python 3.11 to test matrices
* Add Python 3.11 to test matrices
* Skip one test on Python 3.11 due to added support for null bytes in the csv module
> [CI] Add Python 3.11 to test matrices

- Orange/canvas/run.py
- Orange/widgets/utils/save/owsavebase.py
- Orange/widgets/utils/save/tests/test_owsavebase.py
Ref: https://github.com/biolab/orange3/issues/6449#issuecomment-1559709448
Display a warning when auto save is disabled in a loaded workflow. 
Also change auto save to be a schema only setting.
Also print out warning widget messages in run.py
> [ENH] owsavebase: Display a warning when auto save is disabled

- Orange/data/io_base.py
- Orange/data/tests/test_io.py
Fixes #6456. Numeric variables ignored the number of decimals when writing.
Convert to strings via `repr_val`. This will be slower, though.
> CSVWriter: Write numeric variables via repr_val

- Orange/data/sql/backend/mssql.py
Loading table fails when values of the column in the table have trailing spaces, and the column interprets as DiscreteVariable since MSSQl ignore trailing spaces while comparing string values.
Add `DATALENGTH` to `groupby` comparison to ensure trailing spaces are not ignored while grouping.
> [FIX] Sql - Fix comparison with values trailing spaces

- Orange/widgets/data/owdatasets.py
- Orange/widgets/data/tests/test_owdatasets.py
Fixes #6461.
- Language setting is now stored.
- The selected language is always added to combo, even if no data sets with that language exist (which should never happen, but let's play it safe), resulting in an empty list of data sets.
> Data Sets: Remember selected language

- Orange/widgets/data/owgroupby.py
- Orange/widgets/data/tests/test_owgroupby.py
Fixes (partially) https://github.com/biolab/orange3/issues/6367
Make Group By work with hidden attributes in the table
Additionally: Replace deprecated ListViewSearch with ListViewFilter and use it directly via gui.listView
> [FIX] Group By - Fix error with hidden attributes

- Orange/evaluation/scoring.py
Closes #6464
Straightforward addition of the MAPE metric to Test & Score by delegating to scikit-learn.
> Make MAPE available to Test & Score

- Orange/data/tests/test_pandas.py
- tox.ini
Currently, we do not test Orange on Pandas 2.
Remove the constraint and test on Pandas 2. Two tests are still affected by Pandas 2 changes/[bugs](https://github.com/pandas-dev/pandas/issues/53134#issuecomment-1546011517), so I suggest skipping them temporarily. I think it is safe since the problem appears in the tests and not in the Orange code (the Pandas module is unaffected by the issue).
> Test on Pandas 2

- Orange/data/dask.py
- Orange/tests/test_dasktable.py
Calling len(Table) keeps causing trouble all over Orange, so maybe computing it would be reasonable to compute chunks. AFAIK it only needs to be done once.
> Dask: compute Table chunks if unknown

- Orange/widgets/utils/itemmodels.py
- Orange/widgets/utils/tests/test_itemmodels.py
Currently the data is read one row at a time, which causes issues when the dataset is very wide.
Updated `RichTableModel` with a new mechanism to read only the data currently in view and cache it. This only gets used for `DaskTables`. Otherwise if the data is stored in `numpy` arrays it reads each element from them directly, and if the data is sparse it will default to the old behaviour of using `RowInstance`. This is done because the entire row must be read in order for the "basket_formatter" to work. I haven't tested or considered what should happen for `SQLTable`, but I'm thinking we also default to the old behaviour?
also a small change in `test_owtable` because the sorting test was failing.
> [ENH] Faster TableModel for Dask tables (through caching)

- tox.ini
According to https://github.com/catboost/catboost/issues/2371#issuecomment-1594282255 universal wheel for catbost >= 1.2 will now install on Python 3.8, so it is time to revert https://github.com/biolab/orange3/pull/6440
> Tox - remove catboost pin

- Orange/clustering/clustering.py
- Orange/clustering/kmeans.py
- Orange/tests/test_clustering_kmeans.py
- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/tests/test_owkmeans.py
Add `dask_ml.cluster.KMeans` as an alternative to `sklearn.cluster.KMeans` for dask arrays.
Probably worth mentioning, dask_ml adds the "k-means||" init option but defaults to the sklearn implementation in the case of "k-means++" or "random" initialization. So using "k-means||" is what enables working with larger datasets at all. However, smaller datasets are still processed much faster just using sklearn directly as there seems to be a lot of overhead with dask_ml.
> Dask: KMeans

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Fixes #6088.
Based on #6415 to avoid conflicts.
Allows changing the variable type for multiple variables at once.
As discussed with @markotoplak, editing other properties, even labels, would be confusing because controls would have to be disabled if selected variables differ in those properties. Also, the widget already has over 3000 lines of complex code.
The only feature we could easily add would be a tri-state checkbox for unlinking.
The widget has four separate editors for different variable types, which are stacked into a single editor. This PR implements a  fifth editor, which is blank (except for the combo with type) and can handle multiple variables. Existing editors are kept as they are, that is, they accept a single variable. The "top editor" has separate methods for single and …
> [ENH] Edit Domain: Change types of multiple variables

- Orange/preprocess/_relieff.pyx
- Orange/preprocess/score.py
- Orange/widgets/unsupervised/tests/test_owdbscan.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/ownomogram.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/owscatterplotgraph.py
Fix various numpy DeprecationWarnings 
* Replace deprecated np.bool8 alias with np.bool_ 
* Replace use of np.bool_ use as bool argument to PyQt methods
* test_owdbscan: Remove test for `get_kth_distances` with orange distances.
This is never used except in tests and raises/spams deprecation warnings with numpy 1.25. This in turn results in significant test runtime of 40+ seconds for this test.
> Fix numpy deprecation warnings

- Orange/classification/_tree_scorers.pyx
- Orange/tests/test_orangetree.py
I started seeing this on github tests (only on Ubuntu).
```
FAIL: test_full_tree (Orange.tests.test_orangetree.TestClassifier)
File "/home/runner/work/orange3/orange3/.tox/orange-released/lib/python3.9/site-packages/Orange/tests/test_orangetree.py", line 37, in test_full_tree
self.assertTrue(np.all(table.Y.flatten() == pred))
AssertionError: False is not true
```
The bug ran deeper. See my last comment: `find_threshold_entropy` skipped computing too many entropies.
> [FIX] Fix classification trees for data with repeated feature values

- Orange/canvas/config.py
- Orange/evaluation/scoring.py
- Orange/statistics/util.py
- Orange/tests/test_doctest.py
- Orange/widgets/evaluate/tests/test_owliftcurve.py
- Orange/widgets/evaluate/tests/test_utils.py
Distutils stdlib is [deprecated](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated)
Remove import and use of distutils except in setup.py where setuptools provides it.
> Remove use of deprecated distutils

- pyproject.toml
Cython 3.0 was released. Thus our tests fail.
As a temporary change use the older cython version.
> Use pre-3.0 cython

- pyproject.toml
- setup.py
Fixes #6519.
Cython 3.0 with current setup.py cythonizes pyx -> c, but doesn't call compiler.
Call `cythonize`. Whyever.
I checked that there should be no problems with new default behaviour of `/` ("true division", producing floats). In most pyx files we specifiy `cdivision=True` anyway, so the behaviour of Cython remained the same).
If this is OK, we need to
Interestingly, with addon Associate we distribute .cpp. When was the last time anybody touched that add-on?
> Change setup.py to work with Cython 3.0

- Orange/base.py
- Orange/classification/logistic_regression.py
- Orange/tests/test_logistic_regression.py
- Orange/widgets/evaluate/owtestandscore.py
- Orange/widgets/model/owlogisticregression.py
LogisticRegressionLearner and the corresponding widget now support DaskTables. Currently only for binary problems (*filtering rows doesn't work, because it doesn't update the target variable's list of possible values, to fix this we would need to check the contents the table instead).
Changes:
- LogisticRegressionLearner imports dask_ml which we may not want to add to the requirements
- _initialized_wrapped method of SklLearner now takes two arguments
- DaskTable overrides _filter_has_class method to avoid using bottleneck on dask (assumes DaskTables are never sparse)
- added np.asarray in a number of places to compute values when it seemed reasonable (statistics, predictions, test & score)
> [ENH] Dask: Logistic Regression

- Orange/data/tests/test_pandas.py
Tests fail. Pandas already fixed the problem in master so we need to just wait a bit.
> Extend date for ignoring test_time_variable_compatible

- Orange/projection/base.py
- Orange/widgets/unsupervised/owpca.py
- Orange/widgets/unsupervised/tests/test_owpca.py
For larger data PCA takes longer. Moving computation to a separate thread allows canvas to still be responsive.
The first two commits only refactor the widget to lose some attributes.
This PR only improves the responsiveness of canvas. I did not find any easy ways to interrupt PCA so that is not done here. 
*Edit*: I added a commit that allows for cancelling within preprocessing. Code was stolen from owoutliers and the current implementation in `Learner`.
> [ENH] PCA widget runs a separate thread

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Fixes (partially) #6367 
Make Vizran consider only attributes that can be plotted (skipping hidden attributes).
> [FIX] Scatter Plot - Fix Vizrank for hidden attributes

- Orange/projection/pca.py
- Orange/tests/test_pca.py
In the initial implementation of dask_ml into PCA I used IncrementalPCA instead due to memory concerns. This has now proven to be pointless, so it seems better to have each of the two projectors use the appropriate base class.
*IncrementalPCA is never actually used in Orange. If memory does end up being a concern though, I think the distinction between regular and incremental PCA should probably be made in the widget instead.
> PCA: distinguish between PCA and IncrementalPCA

- Orange/preprocess/preprocess.py
Current implementation works fine for numpy, but because dask is lazy it will iterate over the entire table multiple times (once for each attribute).
On a 3000 by 3000 example dataset this reduced the performance of logistic regression by a factor of 10. Without preprocessing it runs in ~500 msec, with preprocessing it took ~5 sec.
solution: compute nans once in advance and store them in memory.
> RemoveNaNColumns - compute nans in advance

- tox.ini
Tox fails saying it can not find the environment
> Fix CI to work with tox 4.9.0 (released Aug 16)

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
Fix an error when reporting regression model with data that does not have the target column:
```
File "/home/ales/devel/orange-widget-base/orangewidget/report/report.py", line 59, in show_report
self.create_report_html()
File "/home/ales/devel/orange-widget-base/orangewidget/report/report.py", line 98, in create_report_html
self.send_report()
File "/home/ales/devel/orange3/Orange/widgets/evaluate/owpredictions.py", line 930, in send_report
self.report_table("Data & Predictions", merge_data_with_predictions(),
File "/home/ales/devel/orange-widget-base/orangewidget/report/report.py", line 340, in report_table
body = report_list(table, header_rows, header_columns) …
```
> [FIX] owpredictions: Fix a type error in report when using NoopDelegate

- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/utils/annotated_data.py
- Orange/widgets/utils/state_summary.py
- Orange/widgets/utils/tests/test_annotated_data.py
- Orange/widgets/utils/tests/test_state_summary.py
- conda-recipe/meta.yaml
- requirements-gui.txt
- tox.ini
> [ENH] Lazy signals for Hierarchical Clustering

- Orange/data/util.py
- Orange/data/variable.py
The warning that classes used for `compute_value` need to define `__eq__` and `__hash__` (or signal that inherited methods are OK) do not set the stack level.
These warnings cannot point to the place where the error needs to be fixed (that is, the class definition), but this PR sets the stack level so that it will (usually) point to the place where the class is used, that is, to the line that contains `compute_value=AClassThatHasNoEqual()`. Imperfect, but better.
For string attributes, the level is incorrect because they have no `__init__`. This could be fixed by defining an `__init__`, but we seldom compute string variables, and defining an `__init__` just for this sound rather pointless.
> Improve stacklevel for warning about inherited eq for compute_value

- Orange/widgets/model/owknn.py
- Orange/widgets/model/owneuralnetwork.py
- Orange/widgets/model/owrules.py
- Orange/widgets/model/owsgd.py
- Orange/widgets/tests/base.py
Fixes: https://github.com/biolab/orange3/issues/6516
... the same problem is also fixed in kNN, Stochastic Gradient Descent and CN2 Rule Induction
* Remove learner_name setting redefinition
> [FIX] Neural Network: Default learner name propagation

- Orange/widgets/data/owdiscretize.py
- Orange/widgets/data/tests/test_owdiscretize.py
Fix an error in display string formatting when updating widget input while a filter/search string is entered in the list view. I.e. 
* `File -> Discretize`, 
* Enter some text in the filter edit line
* Reload the file.
```
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/owdiscretize.py", line 345, in data
hint, points, values = index.data(Qt.UserRole)
^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```
Fix formatting display string when user role is undefined
> [FIX] owdiscretize: Fix formatting display string when user role is undefined

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
An error is raised when there is a regression dataset on input but no model and the user changes the 'Show regression error:'
```
File "/home/ales/devel/orange-widget-base/orangewidget/gui.py", line 2261, in __call__
self.func(**kwds)
File "/home/ales/devel/orange3/Orange/widgets/evaluate/owpredictions.py", line 328, in _reg_error_changed
self.predictionsview.model().setRegErrorType(self.show_reg_errors)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'setRegErrorType'
```
> owpredictions: Fix an exception when switching regression error in gui

- Orange/widgets/data/utils/pythoneditor/tests/base.py
- Orange/widgets/data/utils/pythoneditor/tests/test_api.py
- Orange/widgets/data/utils/pythoneditor/tests/test_bracket_highlighter.py
- Orange/widgets/data/utils/pythoneditor/tests/test_draw_whitespace.py
- Orange/widgets/data/utils/pythoneditor/tests/test_edit.py
- Orange/widgets/data/utils/pythoneditor/tests/test_indent.py
- Orange/widgets/data/utils/pythoneditor/tests/test_indenter/indenttest.py
- Orange/widgets/data/utils/pythoneditor/tests/test_indenter/test_python.py
- Orange/widgets/data/utils/pythoneditor/tests/test_rectangular_selection.py
- Orange/widgets/data/utils/pythoneditor/tests/test_vim.py
Cleanup teardown python editor tests
Maybe alleviates  segfaults in CI tests.
Do not use WidgetTest to test a non OWWidget component.
> [MNT] Cleanup python editor tests

- Orange/widgets/data/utils/pythoneditor/tests/base.py
- Orange/widgets/data/utils/pythoneditor/tests/test_edit.py
PyQt6 CI tests fail for concurrent widget's tests
```
File "/Users/runner/work/orange3/orange3/.tox/pyqt6/lib/python3.9/site-packages/Orange/widgets/tests/base.py", line 712, in test_sparse_data
self.wait_until_finished(timeout=timeout)
File "/Users/runner/work/orange3/orange3/.tox/pyqt6/lib/python3.9/site-packages/orangewidget/tests/base.py", line 526, in wait_until_finished
self.assertTrue(
AssertionError: False is not true : Did not finish in the specified 5000ms timeout
```
This seems to be caused by pythoneditor test's use of 'in_main_loop' decorator.
Remove use of in_main_loop decorator (seems to be unnecessary)
> [MNT] Fix timeout errors in concurrent widgets when running unittests

- Orange/data/dask.py
- Orange/tests/test_dasktable.py
There were problems with loading zero length dask arrays. Example:
```
import Orange
from Orange.tests.test_dasktable import temp_dasktable
data = Orange.data.Table("iris")[:0]
print(data.X.shape, data.Y.shape, data.metas.shape)
data = temp_dasktable(data)
print(data.X.shape, data.Y.shape, data.metas.shape)
data.transform(Orange.data.Domain(data.domain.attributes))
```
This crashed because X's shape was (0,0), but it should have been (0,4).
> DaskTable: fix loading zero length dask arrays

- Orange/data/pandas_compat.py
- Orange/data/tests/test_pandas.py
pandas_compat imports `SparseDtype` from `pandas.core.arrays.sparse.dtype`, which is no longer valid.
Fix SparseDtype import
> [FIX] Adapt to newly released pandas 2.1

- .github/workflows/test.yml
- Orange/data/pandas_compat.py
- Orange/data/tests/test_pandas.py
- conda-recipe/meta.yaml
- pyproject.toml
- requirements-core.txt
- tox.ini
- CI - Stop testing Python 3.8 since it isn't recommended to support it anymore, according to [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html). Pandas, Numpy, and Scipy dropped support already (after reading skip in the second point of this PR, it is unnecessary to drop those tests anymore, but I would go further with this anyway).
- Re-add skip to pandas test that was removed as part of #6559 (since, at some point, we will probably run the oldest supported workflow with Pandas 2.0.*). It was updating the skipp that was still present and a minor update of the test.
- Handle some deprecations in the Pandas module (is_categorical_dtype and setting value by index without `iloc`).
- Reupdate import from #6559
> [FIX] Adapt tests to pandas 2.1 and fix deprecations

- Orange/data/sql/table.py
- Orange/data/table.py
- Orange/tests/sql/test_sql_table.py
- Orange/tests/test_table.py
- Orange/widgets/visualize/tests/test_owvenndiagram.py
Different Tables could have the same ids when unpickled.
Create new table.ids in `__setstate__`.
> Table: Assure unique table.ids when unpickling

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Connected to #6367 
When some features are hidden in the data, and those features are present on Scatter Plot's feature input widget fails.
Handle describe scenario and do not plot anyting
> [FIX] Scatter Plot - Handle input features that are hidden in data

- Orange/projection/_som.pyx
- Orange/projection/som.py
- Orange/widgets/unsupervised/owsom.py
- Orange/widgets/unsupervised/tests/test_owsom.py
- Orange/widgets/utils/signals.py
- Orange/widgets/utils/tests/test_signals.py
Resolves #6540.
Added columns, with lazy values and everything.
**To discuss**:
- `som_cell` column type.
- split into fitter and model or leave as is? (I'd keep it until (if ever) we really need separate classes)
> [ENH] SOM: output columns with coordinates and errors

- Orange/classification/naive_bayes.py
- Orange/tests/test_naive_bayes.py
Partially addresses #6553.
There was an off-by-one error in the Naive Bayes classifier, which resulted in treating unknown feature values as the largest values instead of a separate unknown value (which doesn't contribute towards either class).
> [FIX] Naive Bayes: fix predictions with unknown values

- Orange/widgets/evaluate/owpredictions.py
Fixes: https://github.com/biolab/orange3/issues/6554
* Do not subtract margins from left/right text area
* Hint maximum possible text size for classification
> [FIX] Predictions: Fix column size hinting

- Orange/projection/freeviz.py
- Orange/widgets/visualize/owfreeviz.py
- Orange/widgets/visualize/tests/test_owfreeviz.py
Fixes #6479.
Adds an option to control the strength of attractive and repulsive forces.
> FreeViz: Allow setting ratio btw attractive and repulsive forces

- Orange/base.py
- Orange/classification/naive_bayes.py
- Orange/data/dask.py
- Orange/tests/test_contingency.py
- Orange/tests/test_naive_bayes.py
Reimplement `_compute_contingency` on `DaskTable` to enable the naive Bayes learner (other uses of this function have not been tested and instead raise an error).
> [ENH] Naive Bayes for Dask

- conda-recipe/meta.yaml
- requirements-gui.txt
- tox.ini
After https://github.com/biolab/orange-widget-base/pull/253, we may request users to have the newest orange-widget-base.
While building the Miniconda installer, I noticed it didn't take the newest version (4.21 instead). Since it can happen to any other user, I propose requiring 4.22 by Orange. I think it doesn't hurt.
> Require orange-widget-base>=4.22

- conda-recipe/meta.yaml
- pyproject.toml
- requirements-core.txt
- requirements-dev.txt
- requirements-doc.txt
- requirements-gui.txt
- tox.ini
Every time I make a release, I have difficulty checking requirements versions between Orange and conda-forge because of different orders in configuration files.
With this PR, I propose to order requirements alphabetically so they can be matched more easily.
I also remove `docutils` constraint that is not required anymore due to fix in https://github.com/biolab/orange-canvas-core/pull/224
> Reorder requirements alphabetically

- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/tests/test_owdistributions.py
Fixes #6576.
Instead of storing indices of columns, `self.selection` now stores selected bar values.
> [FIX] Distributions: Fix selection output

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
Fixes #6572
Attach prediction errors to output when the errors are shown in the table.
> [ENH] Predictions: Output errors

- Orange/data/io.py
- Orange/data/io_util.py
- Orange/data/tests/test_io_util.py
- Orange/data/tests/test_variable.py
- Orange/tests/test_io.py
- Orange/tests/test_tab_reader.py
- Orange/tests/test_txt_reader.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
For example, files that Orange loads (with the File widget) may contain paths in one or more columns—for example, the path to images for image analysis. One way to store paths may be to keep them as origin prefixes in attributes of attribute and the last part of the path as column values. Paths (origin + column values) are absolute paths. When the table is transferred to another computer, the path may not be valid anymore. 
If the dataset's author provides files besides the CSV file, they may be discovered, and the origin can be fixed.
Additionally, I replaced StringIO reader inputs with actual files in the test. The code should not be adapted to cases only possible in tests.
> [ENH] IO - Change origin attribute when not find on system

- Orange/misc/tests/test_embedder_utils.py
- Orange/misc/utils/embedder_utils.py
Issue described here: https://github.com/biolab/orange-canvas-core/pull/288
When no read or write permission, do not load or save embeddings to cache.
> [FIX] EmbedderCache - Handle cache persisting when no permissions

- Orange/widgets/data/owpreprocess.py
When signals are handled when objects are being destroyed we can bugs as in #6136.
The test in https://github.com/biolab/orange3-single-cell/actions/runs/6010124237/job/16300932397?pr=395 failed with 
```
test_editor_normalize_groups (tests.test_owscpreprocess.TestNormalizeEditor) ... Traceback (most recent call last):
File "/Users/runner/work/orange3-single-cell/orange3-single-cell/.tox/orange-oldest/lib/python3.9/site-packages/Orange/widgets/data/owpreprocess.py", line 1412, in __update_size_constraint
sh = self.flow_view.minimumSizeHint()
AttributeError: 'OWscPreprocess' object has no attribute 'flow_view'
```
Thanks to @elapraznik for the crash. :)
Check if the object is still live.
> owpreprocess: fix potential crash at destruction

- Orange/tests/test_util.py
- Orange/util.py
I was passing by, and I cleaned up some ancient lint issues and even wrote some tests.
> Orange.utils: Some random pylinting

- Orange/data/table.py
- Orange/tests/test_table.py
- Orange/widgets/data/owdatainfo.py
- Orange/widgets/data/tests/test_owdatainfo.py
Resolves #6621.
To show counts (not just frequencies) and to also do so for meta variables, new methods have been added to `Table`. Perhaps somebody who works on Dask (e.g. @markotoplak , @noahnovsak) should take a look.
> [ENH] Data Info: Show statistics about missing values

- Orange/misc/tests/test_embedder_utils.py
- Orange/misc/utils/embedder_utils.py
In https://github.com/biolab/orange3/pull/6611, I forgot to log loading errors. 
Log warning added
> EmbedderCache - Log loading/saving errors

- Orange/widgets/evaluate/owcalibrationplot.py
- Orange/widgets/evaluate/owliftcurve.py
- Orange/widgets/evaluate/owrocanalysis.py
- Orange/widgets/evaluate/tests/base.py
- Orange/widgets/evaluate/tests/test_owcalibrationplot.py
- Orange/widgets/evaluate/tests/test_owliftcurve.py
- Orange/widgets/evaluate/tests/test_owrocanalysis.py
- Orange/widgets/evaluate/utils.py
- doc/visual-programming/source/widgets/evaluate/rocanalysis.md
Fixes #6437.
Output a model when the widget shows the threshold line (and a single model is selected). The official reason (but to some extent an excuse) that it's tied to the line is that otherwise the widget doesn't clearly indicate what the output would be.
The widget is too graph-centric. The optimized threshold is computed in passing, while drawing the line. This PR (supposedly) works and it doesn't significantly degrade the quality of the existing code. We can improve this code if/when we rewrite the whole widget.
As a small step toward this goal, I've done a small refactoring of code that is repeated in Lift Curve, Calibration plot and (now) the ROC Analysis widget, and in the corresponding tests.
> ROC: Output a model with a new operating threshold

- .github/workflows/test.yml
Coverage is not reporting since reporting was done on Python 3.8, which is no longer used in CI.
Report on Python 3.11 that will be used until Apr 24, 2026, according to NEP https://numpy.org/neps/nep-0029-deprecation_policy.html
> CI - Fix coverage 

- Orange/projection/base.py
- Orange/projection/manifold.py
- Orange/tests/test_pca.py
There are too many warnings when using PCA.
Having worked with this code, I saw that just about everything is wrong with this class hierarchy - it is much too circular. These classes need to be rewritten - at first I though I won't even be able to implement `__eq__` and `__hash__`, but then I somehow remembered the trick in the second commit.
I also added a tiny test. I could theoretically test all classes in the chain separately by initializing them manually and call corresponding functions, but am not sure that would make sense. Do I have to?
> Implement __eq__ and __hash__ for PCA (and family)

- .github/workflows/translations.yml
A minor improvement of setup and output in the workflow for checking translations.
> Minor improvements in translations workflow

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
Fixes #6566. See in particular https://github.com/biolab/orange3/issues/6566#issuecomment-1772746527.
The first commit does the job and is trivial: checkbox is no longer disabled, and having `compute_value` is no longer required for unlinking.
The second commit is not needed for fixing #6566. However, now that `compute_value` is no longer required for unlinking, we do not need to check it in hint matching. I thus removed it from the key in hint dictionary and consequently from settings. This required a zillion small changes in tests (removals of the additional argument), settings migration and tests for settings migration.
> Edit Domain: allow the (existing) checkbox to also control removal of newly created compute value

- Orange/tests/test_util.py
- Orange/util.py
- i18n/si.jaml
When animating an optimization like laying out a network (and supposedly also MDS, tSNE, freeviz) frequent updates of the graph can make the gui unresponsive.
In particular, when optimizing a network layout in the network add-on, the user can temporarily decrease the gravity and then increase it again, using a slider. The slider is unresponsive when the network has a lot of connections.
Decorator `allot(p)` allocates a given proportion of time to the function. I tried it in the Network Explorer, decorating `on_partial_result` with `allot(0.02)` makes the widget responsive on graphs with 10000 nodes and edges.
> Orange.utils: Add decorator 'allot'

- Orange/widgets/data/owcsvimport.py
/home/runner/work/orange3/orange3/.tox/orange-latest/lib/python3.11/site-packages/Orange/widgets/data/owcsvimport.py:1773: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
> Replace use of the deprecated pandas.api.types.is_categorical_dtype

- Orange/ensembles/ada_boost.py
- Orange/tests/test_ada_boost.py
- Orange/tests/test_pca.py
- Orange/widgets/evaluate/tests/test_owliftcurve.py
- Orange/widgets/model/owadaboost.py
- conda-recipe/meta.yaml
- i18n/si.jaml
- requirements-core.txt
- tox.ini
/home/runner/work/orange3/orange3/.tox/orange-latest/lib/python3.11/site-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
> adaboost: adapt to scikit-learn's 1.4 deprecation of base_estimator

- Orange/widgets/visualize/owpythagoreanforest.py
Can't compute QPoint and QPointF since PyQt6.
Cast QPoint to QPointF.
> OWPythagoreanForest: Cast QPoint to QPointF

- Orange/evaluation/scoring.py
- i18n/si.jaml
It is deprecated and will be removed in scikit-learn 1.5. Our tests are full of these:
/home/runner/work/orange3/orange3/.tox/orange-latest/lib/python3.11/site-packages/sklearn/metrics/_classification.py:2851:
FutureWarning: Setting the eps parameter is deprecated and will be removed in 1.5. Instead eps will always have a default value of `np.finfo(y_pred.dtype).eps`
> Remove the eps argument from LogLoss

- Orange/widgets/model/owneuralnetwork.py
- Orange/widgets/model/owrules.py
- Orange/widgets/tests/base.py
- Orange/widgets/utils/owlearnerwidget.py
Fixes gh-6649
Fix model's effective name
> [FIX] CN2 Rule Induction: Fix model's effective name

- .github/workflows/test.yml
- Orange/tests/sql/base.py
- tox.ini
Sometimes Orange starts crashing when newer scikit-learn & company get released. We could at least anticipate that.
~~Needs #6637 to be merged first.~~ I remembered doing something like this when I was removing `scikit-learn<1.4` limit in #6637.
Adds a nightly build repository to one of our tests.
> [CI] Test with scientific python nightly wheels 

- pylintrc
Pylint introduced a check for duplicated code.
As we discussed, lint should warn us against things we do accidentally. Duplicated code is not on the list of our common sins, and we can safely assume (and can also already observe) that in our code these issue will be false positives.
> Lint: Disable duplicate-code

- Orange/widgets/visualize/owlinearprojection.py
- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/owsieve.py
- Orange/widgets/visualize/tests/test_owlinearprojection.py
- Orange/widgets/visualize/tests/test_owmosaic.py
- Orange/widgets/visualize/tests/test_owradviz.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
- Orange/widgets/visualize/tests/test_owsieve.py
- Orange/widgets/visualize/tests/test_vizrankdialog.py
- Orange/widgets/visualize/utils/__init__.py
- Orange/widgets/visualize/utils/tests/test_vizrank.py
- Orange/widgets/visualize/utils/vizrank.py
- i18n/si.jaml
Fixes #6504. Also fixes #6624.
#6614 would fixed the above problems, but poking the VizRank code that didn't age well introduced new bugs, and testing exposed some existing bugs.
This PR implements a new, cleaner and leaner VizRank.
> VizRank: Reimplementation

- Orange/widgets/data/owtable.py
- Orange/widgets/data/utils/tableview.py
https://github.com/biolab/orange-widget-base/issues/258
* Do not reset header view state on new data
> owtable: Do not reset header view state on new data

- Orange/widgets/visualize/owmosaic.py
- Orange/widgets/visualize/owsieve.py
- Orange/widgets/visualize/tests/test_owmosaic.py
- i18n/si.jaml
Minor improvements over #6661.
**Mosaic:**
- Mosaic: disable vizrank for less than two variables
- Mosaic: disable the option to select three or four variables when the number of variables is smaller than that.
- Mosaic: don't declare vizrank dialog as setting provider because it no longer is, and can't be.
**Sieve:**
- Remove unused `caption_title`.
> Minor fixes in Mosaic and Sieve vizrank

- Orange/data/io_base.py
- Orange/data/tests/test_io.py
Fixes #6527.
The function that creates a string representation for storing values in file didn't expect that a `StringVariable` can be `np.nan`. Now it does.
Our handling of StringVariable unknowns is a mess; the Table widget will apparently sometimes show `nan`. This must be solved in general. The present PR only fixes the crash in saving of Excel files.
> [FIX] Writers: Store nans in StringVariable as empty strings instead of 'nan'

- Orange/canvas/__main__.py
- Orange/canvas/config.py
- Orange/tests/test_third_party.py
- Orange/util.py
- Orange/widgets/__init__.py
- Orange/widgets/data/owpreprocess.py
- Orange/widgets/tests/test_workflows.py
- conda-recipe/meta.yaml
- i18n/si.jaml
- pylintrc
- requirements-core.txt
- requirements-gui.txt
- tox.ini
[pkg_resources](https://setuptools.pypa.io/en/latest/pkg_resources.html)  is deprecated.
Requires:
* https://github.com/biolab/orange-canvas-core/pull/289 merged and released
* https://github.com/biolab/orange-widget-base/pull/260 merged and released
Remove/replace use of pkg_resources with importlib.metadata, importlib.resources, pkgutil and packaging.
> [ENH] Remove use of pkg_resources

- setup.py
`imp` module was deprecated and removed in Python 3.12. This means that installing from a sdist package fails on Python 3.12+.
Replace use of imp module
> [FIX] setup.py: Replace use of imp module

- Orange/data/tests/test_variable.py
- Orange/data/variable.py
As @janezd noticed in #6670, "NaN" is displayed as it would have been a string in the DataTable.
Display "?" if pandas.isnull returns True.
Although we have been allowing None or NaN to appear in StringVariables for some time now, there are probably many bugs like this. As I was reading the code, it seems that we really assumed StringVariables to actually be, well, strings, when we wrote that code 10 years ago.
> Display NaNs in StringVariable as "?"

- Orange/widgets/visualize/utils/customizableplot.py
Changing the axis font (using a Visual Settings dialog) on the following plot
results in a changed color:
Retain original color when changing the axis font.
> Visual settings Updater: Retain axis color

- Orange/widgets/utils/headerview.py
- Orange/widgets/utils/tests/test_headerview.py
- Orange/widgets/utils/tests/test_textimport.py
- Orange/widgets/utils/textimport.py
- i18n/si.jaml
Closes https://github.com/biolab/orange3/issues/6675
Add row check marks for skipping rows.
https://github.com/biolab/orange3/assets/4716745/12efee86-7cb0-4634-85c4-a7452c281c3b
Allow selection of multiple rows for easy skipping of many rows.
https://github.com/biolab/orange3/assets/4716745/4d8bd277-1943-494e-b41a-68917e63439d
> [ENH] CSV Import: Skip multi rows edit

- Orange/widgets/data/owcsvimport.py
Fixes an error with dev version of pandas as seen on CI i.e.
```
FAIL: test_load_csv (Orange.widgets.data.tests.test_owcsvimport.TestUtils.test_load_csv)
File "/home/runner/work/orange3/orange3/.tox/beta/lib/python3.11/site-packages/Orange/widgets/data/tests/test_owcsvimport.py", line 449, in test_load_csv
self.assertSequenceEqual(
AssertionError: Sequences differ: [dtype('O'), dtype('float64'), dtype('O'), Catego[100 chars]64')] != [dtype('<M8[ns]'), dtype('float64'), dtype('O'), [24 chars]64')]
First differing element 0:
dtype('O')
dtype('<M8[ns]')
+ [dtype('<M8[ns]'), dtype('float64'), dtype('O'), 'category', dtype('float64')]
- [dtype('O'),
-  dtype('float64'),
-  dtype('O'),
- …
```
> [FIX] CSV Import: Add explicit datetime conversion

- Orange/widgets/unsupervised/owdistancematrix.py
- Orange/widgets/unsupervised/owdistances.py
- Orange/widgets/unsupervised/tests/test_owdistancematrix.py
- Orange/widgets/unsupervised/tests/test_owdistances.py
- Orange/widgets/utils/distmatrixmodel.py
- Orange/widgets/utils/tests/test_state_summary.py
Distance Matrix crashes when 0×0 matrix appears on the input.
To reproduce:
- Distance Matrix: handle empty matrix on the input
- Distances: warn when data on the input has no featues
> Distance Matrix: Crash on empty matrix

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
- i18n/si/msgs.jaml
Fixes #6711.
Add a (potentially lazy) output with annotated predictions.
I haven't made the existing output lazy, although this should be done at some point -- but perhaps as a general change in other widgets as well.
> Predictions: Output annotated table

- Orange/widgets/utils/domaineditor.py
Metas and class attributes are poorly visible in the domain editor in dark mode.
Use dark colours for a light background in the dark mode. It is exactly the same implementation as in the Data Table.
Before:
After:
> [FIX] Domain Editor - Adapt to dark mode

- .github/workflows/build-wheels.yaml
- .github/workflows/doc.yml
- .github/workflows/rebase.yml
- .github/workflows/test.yml
Various actions raise warnings:
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`
Update actions
> [MNT] ci: Update various action versions

- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/tests/test_owcsvimport.py
The CSV widget fails to parse the data in some cases, such as columns with many numbers, one string, and more numbers. Pandas seem to parse that column as categorical with categories as integers first, and from the string on categories, they are stored as strings (and therefore duplicated).
Before creating a table, the CSV widget transforms all categories to strings so it gets duplicated categories for each category (categories were repeated initially when Pandas read them, but the exact value was both string and int, so it didn't seem to be duplicates).
For the exact scenario, check the newly added test.
Fixing the issue by ensuring unique categories after conversion to string.
> [FIX] CSV Import - Fix categorical parsing for "mixed-type" column

- Orange/ensembles/stack.py
- Orange/tests/test_stack.py
Fixes #6665.
Stacking transformed the data to the same data type as the input. However, Timeseries has an inbuilt assert for time variable, which was missing from stacked_data.
Tests will be added to Timeseries add-on.
> Stack: new table instead of transform

- Orange/widgets/data/tests/test_owcsvimport.py
test_owcsvimport tests sometimes segfault in CI tests. 
```
test_browse (Orange.widgets.data.tests.test_owcsvimport.TestOWCSVFileImport) ... ok
test_browse_for_missing (Orange.widgets.data.tests.test_owcsvimport.TestOWCSVFileImport) ... Fatal Python error: Segmentation fault
Thread 0x000070000d724000 (most recent call first):
File "/Users/runner/work/orange3-installers/orange3-installers/mnt/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
File "/Users/runner/work/orange3-installers/orange3-installers/mnt/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953 in run
File "/Users/runner/work/orange3-installers/orange3-installers/mnt/Orange3.app/Contents/Frameworks/Py …
```
> [FIX] test_owcsvimport: Workaround for segfault in tests on macos

- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/owfile.py
- Orange/widgets/data/tests/test_owcsvimport.py
- Orange/widgets/data/tests/test_owfile.py
- Orange/widgets/model/owloadmodel.py
- Orange/widgets/model/tests/test_owloadmodel.py
- Orange/widgets/tests/utils.py
- Orange/widgets/unsupervised/owdistancefile.py
- Orange/widgets/unsupervised/tests/test_owdistancefile.py
- Orange/widgets/utils/filedialogs.py
- Orange/widgets/utils/tests/test_filedialogs.py
Open dragged files on CSV Import, Load Model and Distance File widgets similar to how existing File works.
* owcsvimport.py Handle drops on the widget. Implement common OWUrlDropBase abstract class.
* Use OWUrlDropBase in File, LoadMode, Distance File widgets.
> [ENH] Open draged files on CSV Import, Load Model and Distance File widgets

- Orange/data/table.py
- Orange/data/tests/test_table.py
When a table has no rows add_column still tries to insert (empty) data to the table's array. In case the table's array is empty Orange doesn't unlock it and so inserting fails.
Skip inserting empty data when the array is empty
> [FIX] Table.add_column - Do not try to insert data in locked empty array

- Orange/widgets/data/utils/pythoneditor/editor.py
Python editor tests (vim) frequently segfault.
Terminate subelements before clearing the text
> [FIX] pythoneditor/editor: Change order in `terminate`

- Orange/data/io_util.py
Fixes: gh-6755
`asarray(..., dtype=str)` creates an array or uniform length strings matching the length of the longest string.
Fix memory usage when parsing columns with at least one long string.
> [FIX] io_util: Fix memory usage when parsing columns

- .github/workflows/test.yml
- Orange/tests/test_ada_boost.py
- Orange/tests/test_base.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
- Test Orange on Python 3.12, which has been out for some time now.
- Replace `distutils`, which was deprecated and removed in Python 3.12 form tests.
- Replace wrongly used called_with (should be assert_called_with) in test_owpredictions. Since it was not even a valid check (selection model change when the model is set to None in the widget), I replaced it with just assert_called_once, which checks that `unregister` was called.
> [CI] Test with Python 3.12

- Orange/widgets/unsupervised/owsom.py
- Orange/widgets/unsupervised/tests/test_owsom.py
Fixes #6750
Fixed TypeError: 'DiscreteVariable' object is not iterable.
> [FIX] OWSom: Fix crash for data without class variable

- Orange/misc/_distmatrix_xlsx.py
- Orange/misc/tests/test_distmatrix_xlsx.py
Resolves https://github.com/biolab/orange3/issues/6599
Description of changes
Added handling for NaN (Not a Number) values - implemented handling cells with NaN values by leaving them empty when writing to the file and interpreting them as NaN when reading from the file.
> Saving Distance Matrices: Handle NaNs in Excel #6766

- Orange/widgets/data/utils/tableview.py
- Orange/widgets/data/utils/tests/test_tableview.py
An error occurs when displaying a zero columns dataset in RichTableView
```python
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/utils/tableview.py", line 173, in __headerDataChanged
items = model.headerData(
^^^^^^^^^^^^^^^^^
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/data/utils/models.py", line 72, in headerData
var = super().headerData(
^^^^^^^^^^^^^^^^^^^
File "/Users/aleserjavec/workspace/orange3/Orange/widgets/utils/itemmodels.py", line 1050, in headerData
coldesc = self.columns[section]
~~~~~~~~~~~~^^^^^^^^^
IndexError: list index out of range
```
Example workflow *Python Script -> Table* with 
```python
import Orange
out_data = Orange.data.Table.from_list(
Orange.data.Domain([], None),
[[],
[],
[]]
)
```
script, …
> [FIX] tableview: Fix index error when displaying dataset with zero columns

- Orange/widgets/visualize/owscatterplot.py
- Orange/widgets/visualize/tests/test_owscatterplot.py
Implements #6734
Add ellipse (similar to regression line).
> [ENH] Scatter Plot: Add ellipse/s

- Orange/classification/_simple_tree.c
Non standard `qsort_r` is not defined unless _GNU_SOURCE is defined or `--std=gnu99` flag is used.
Fix compilation error with gcc 14
> [FIX] _simple_tree.c: Fix compilation error with gcc 14

- Orange/regression/pls.py
- Orange/regression/tests/test_pls.py
- Orange/widgets/model/owpls.py
- Orange/widgets/model/tests/test_owpls.py
Implement Residual normal probability plot.
Implement Residual normal probability plot by adding `Sample Quantiles` and `Theoretical Quantiles` for each target to output Data.
> PLS: Add residual normal probability, distance to the model

- Orange/regression/pls.py
- Orange/regression/tests/test_pls.py
- Orange/widgets/model/tests/test_owpls.py
PLS widget crashes when data has target with missing values.
> PLS: Handle missing target values

- conda-recipe/meta.yaml
- requirements-core.txt
PCA test are failing due to the latest scikit-learn release.
Limit the scikit-learn version as a temporary fix.
> Limit scikit-learn version

- Orange/projection/pca.py
- Orange/tests/test_pca.py
- Orange/widgets/unsupervised/tests/test_owpca.py
- conda-recipe/meta.yaml
- requirements-core.txt
- tox.ini
This PR basically reverts #3532.
At the time this was implemented, scikit-learn did not support PCA on sparse matrices without first densifying them. It has since added this support.
PCA failing on scikit-learn 1.5 due to PCA internal API changes.
The reason for our own custom PCA implementation (proper sparse support) is now invalid, since scikit-learn properly handles sprase data now. Therefore, I just removed our implementation of PCA and we now rely purely on scikit-learn. Our implentation was always meant to be temporary.
> Remove Orange implementation of randomized PCA

- Orange/projection/pca.py
- Orange/widgets/unsupervised/tests/test_owpca.py
#6815 broke a few things that went under the radar, primarily due to scikit-learn 1.5.0 changes.
> [FIX] PCA: ensure tests pass on sklearn 1.4 and 1.5, which can return different results

- Orange/widgets/visualize/owlineplot.py
Replace scipy.sparse `.A` with `.toarray()`. `.A` shortcut was removed in scipy 1.14.
> [FIX] Line plot: compatibility with scipy 1.14

- tox.ini
Tests fail on arm macs with Python<3.11 because the pymssql library cannot be installed.
Skip this dependency on systems for which it is not available.
> [CI] tox.ini: Skip pymssql dependency on MacOS with py<3.11

- Orange/data/table.py
- Orange/tests/test_table.py
#6189 introduced deep-copying of the dictionary `Table.attributes` at table transformations. Because table transformations often happen withing table transformation, this can lead to wasting computation and memory. An example of the bug that can happen is Quasars/orange-spectroscopy/pull/726.
For illustration, here is a small example:
```python
import numpy as np
import Orange
from Orange.projection import PCA
from mem_use import MemUse
mem = MemUse()
mem.start()
data = Orange.data.Table(np.random.random((1000, 1000)))
data.attributes["big"] = [ i for i in range(100000) ]
mem.wait_gc("loaded data")
p = PCA(n_components=10)(data)
mem.wait_gc("pca")
mem.draw()
````
The memory use/time graphs below (first master, then this branch) show big differences (~30 seconds vs 1 second) that all stem …
> [FIX] Only deepcopy the .attributes for the outermost Table transformation

- Orange/widgets/unsupervised/owhierarchicalclustering.py
- Orange/widgets/unsupervised/tests/test_owhierarchicalclustering.py
Fixes #6883.
The spin box expects some maximum value; Qt's default is 99. I set it to 1000, but the widget will show a warning if the value is above 20.
The warning checks the final number of clusters. It won't be shown if Top N setting is too high, but there are not enough data instances for so many clusters. And the warning is also shown when >20 clusters are obtained in some other way, either manually or via treshold.
> Hierarchical clustering: Allow more than 20 clusters in Top n spin

- requirements-doc.txt
Readthedocs fails with 
```
File "/home/docs/checkouts/readthedocs.org/user_builds/orange3/envs/6894/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 795, in copy_download_files
copyfile(self.srcdir / src, dest, force=True)
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```
The direct cause of the problem is a recent change in Sphinx: https://github.com/sphinx-doc/sphinx/commit/0897b5948b933af38e86ab623770b2ece035c7c2#diff-be839d87d39d93093003a0a4ce40cf9610d0a9445e5e0aeb1cdc6bab527bfbbcR786
The Sphinx code is correct, though, because `self.srcdir` must be an instance of `pathlib.Path`, which defines `/` as a path-concatenating operator. The actual problem is in extension sphinx-multiproject, here: …
> Pin sphinx to <8

- Orange/data/tests/test_pandas.py
pytz 2024.2 seems to have changed treatment of DST and of timezones, which broke our tests.
The failing assertion could be fixed, but we prefer removing it: it was a test of pytz regressions rather than of our code.
> test_pandas: Remove a failing test caused by pytz

- i18n/si/msgs.jaml
Resolve missing and redundant translations.
> Resolve missing/redundant translations

- tox.ini
These tests fail because pymssql on macOS fails to install on CI. I tried hard to build them, but failed.
Don't install pymssql and tests are skipped.
Our code that uses it is tested on Windows and Linux. Our releases include a properly built pymssql on macOS: according to @markotoplak, tests of releases would detect any problems.
> CI: Remove pymssql tests on macOS

- Orange/widgets/model/owlogisticregression.py
- Orange/widgets/model/tests/test_owlogisticregression.py
Fixes #6885.
As of 1.3.2, Scikit used to accept `'none'` as penalty. In 1.5.1 it expects `None`.
I unsuccessfully tried to find where, when and why it changed, but it doesn't really matter, I guess.
Replace `'none'` with `None`.
> [FIX] Logistic regression: fix penalty argument for no regularization

- Orange/widgets/data/oweditdomain.py
- Orange/widgets/data/tests/test_oweditdomain.py
- Orange/widgets/utils/itemmodels.py
Fixes: #6861
* Hide/show warning on change
* Indicate items with a warning with a yellow color
> [FIX] oweditdomain: Hide "categories mapping" warning on change

- Orange/widgets/model/owpls.py
- Orange/widgets/model/tests/test_owpls.py
- requirements-core.txt
Adjust PLS coefficients due to https://github.com/scikit-learn/scikit-learn/pull/28612
- remove `coef/X_sd` column
- keep fixed intercept value
> PLS: Adjust coeffs to newest sklearn

- Orange/data/pandas_compat.py
- Orange/data/tests/test_pandas.py
- Orange/preprocess/_relieff.pyx
- Orange/widgets/data/tests/test_owcsvimport.py
- Orange/widgets/visualize/tests/test_ownomogram.py
*Scientific Python nightly wheels* fails.
- **Cython code in Relief**: Import `NAN` and `INFTY` from `libc.math` instead of from `numpy.math`. This caused an error in cythonizing.
- **Importin pytz**: In `test_pandas`, do not import `pytz`. We do not (directly) depend on it, and pandas removes it in 3.0.
- **Indices in sparse matrices**: Index-out-of-range error is a bug in scipy and was fixed in https://github.com/scipy/scipy/pull/21616.
- **Different result in nomograms:** scipy changed the optimizer that is used for fitting logistic regression. @markotoplak fixed this by increasing the number of iterations
- **Time resolution in pandas**: Pandas can now import time in 1 s resolution, where it previously used 1 ns, and the resulting type is `<M8[s]` instead of `<M8[ns]`. We convert this …
> Fixes for tests on nightly builds of numpy/scipy/pandas

- Orange/widgets/visualize/utils/plotutils.py
Fixes #6854
Since 384f6f4 the AnchorItem does not properly update its layout due to difference in pg.GraphicsObject/pg.GraphicsWidget implementations.
Track scene transform changes.
> [FIX] plotutils: Fix scene layout tracking in AnchorItem

- Orange/ensembles/ada_boost.py
- Orange/tests/test_ada_boost.py
- Orange/widgets/model/owadaboost.py
- Orange/widgets/model/tests/test_owadaboost.py
- i18n/si/msgs.jaml
In Sklearn 1.6, the only acceptable value for `AdaBoost's argument `algorithm` is `SAMME`. In 1.8, the argument will be removed. (https://github.com/scikit-learn/scikit-learn/pull/29997)
- I removed the argument. This doesn't break any tests, so it apparently didn't have any effect (or we didn't test it properly). Any potential changes are however unavoidable because the current algorithm is removed from SkLearn (for the reasons, see https://github.com/scikit-learn/scikit-learn/issues/26784).
- I removed the setting from the widget. I haven't provided any migration, not even showing a warning because the user would have no way to disable the warning. Besides, it probably doesn't matter.
- Some tests depend on random seed. I change one of them to `4` so that results in scikit-learn=1.6.dev …
> Adaboost: Remove deprecated argument 'algorithm'

- Orange/widgets/model/owcalibratedlearner.py
- Orange/widgets/model/tests/test_owcalibratedlearner.py
Fixes #6915
* Never return `base_learner` instance from `create_learner`
* Replace IdentityWrapper (which did not work) with copy.deepcopy of the instance.
> [FIX] Calibrated Learner: Prevent in place modification of base learner

- Orange/widgets/data/owdatasets.py
- Orange/widgets/data/tests/test_owdatasets.py
- i18n/si/msgs.jaml
- When reimplementing the repository of data sets, we added a field "Domain". Its current values are "core" and "sc", but the plan was to add (a very limited) number of others, such as "Education", and to allow the user to select a domain in the Data sets widget. Domains were not meant to be like tags but rather to allow the user select a single specific domain.
- With the new repository, the Datasets widget started showing single-cell data sets that were previously (if I remember correctly) accessible only in the single cell's widget. This PR reverts the behaviour to the more sensible original: by default, it only shows "core" data sets.
- With @BlazZupan we discussed that it would be handy if a data set could be unlisted - shown only if the user types the first five characters of the …
> [ENH] Datasets: Add domain field; respect "Unlisted"

- Orange/widgets/data/owdatasets.py
- Orange/widgets/data/tests/test_owdatasets.py
- i18n/si/msgs.jaml
Adding the domain and language combo made it more difficult to load educational data sets.
Also fixes #6931.
Make the filter override the domain (and language) setting. The number of data sets is large, so users always filter them anyway.
The fix may also provide an alternative to 16bbfdfeecff0bb6fc6de562014d1faca1e8905d? @markotoplak
> [ENH] Datasets: Let the filter override domain and language

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
Fixes gh-6911
@janezd what was the point of using 2 as invalid value. I cannot find any place where it would be used/checked, 
except where it is replaced with NaN on output.
Remove special magic value 2. Just use NaN.
> [FIX] owpredicttions: Remove special magic value 2

- MANIFEST.in
- doc/visual-programming/source/conf.py
- setup.py
Fixes #6949
Reimplement sphinx build command
sphinx removed sphinx.setup_command.BuildDoc in https://github.com/sphinx-doc/sphinx/pull/11363
> [FIX] Fix documentation in packages: fix sphinx build command

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/utils/localization/__init__.py
- conda-recipe/meta.yaml
- i18n/trubar-config.yaml
- requirements-gui.txt
- tox.ini
Fixes #6952. Requires https://github.com/biolab/orange-canvas-core/pull/320 to be merged and released.
Import localization from a place that doesn't require Qt.
The most important change is the one in configuration of Trubar - this will allow running Orange without Qt.
The other two changes in `[Orange/widgets/utils/localization/__init__.py](https://github.com/biolab/orange3/compare/master...janezd:fix-headless-orange?expand=1#diff-3bf6fd4d089b6924794714d11768d90dbac35b1b370e9cfc788c6cd6f216eece)` are not strictly necessary, but  prevent a warning about importing localization from a deprecated module.
> [FIX] Orange can be imported without Qt (fixed importing localization)

- Orange/classification/logistic_regression.py
- Orange/evaluation/scoring.py
- Orange/tests/test_logistic_regression.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
- Orange/widgets/visualize/tests/test_ownomogram.py
- i18n/si/msgs.jaml
As per https://scikit-learn.org/1.5/modules/generated/sklearn.linear_model.LogisticRegression.html,
```
Deprecated since version 1.5: multi_class was deprecated in version 1.5 and will be
removed in 1.7. From then on, the recommended ‘multinomial’ will always be used
for n_classes >= 3. Solvers that do not support ‘multinomial’ will raise an error. Use
sklearn.multiclass.OneVsRestClassifier(LogisticRegression()) if you still want to use OvR.
```
Remove the argument.
> LogisticRegressionLearner: Remove deprecated argument 'multi_class'

- setup.py
Fixes #6992.
Editable install (pip install -e, python setup.py develop) does not run trubar. This PR imports it locally to avoid the unnecessary dependency.
Add-ons already do so. We made a mistake only here.
> setup: Import trubar locally

- Orange/classification/__init__.py
- Orange/data/io_base.py
- Orange/data/util.py
- Orange/preprocess/_relieff.pyx
- Orange/preprocess/discretize.py
- Orange/preprocess/remove.py
- Orange/regression/__init__.py
- Orange/tests/test_classification.py
- Orange/tests/test_domain.py
- Orange/tests/test_preprocess.py
- Orange/widgets/data/owselectbydataindex.py
- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/tests/test_owcontinuize.py
- Orange/widgets/model/tests/test_owlogisticregression.py
- Orange/widgets/tests/test_matplotlib_export.py
- Orange/widgets/visualize/owboxplot.py
- Orange/widgets/visualize/ownomogram.py
- Orange/widgets/visualize/owradviz.py
- Orange/widgets/visualize/owsilhouetteplot.py
- Orange/widgets/visualize/tests/test_owmosaic.py
- Orange/widgets/visualize/tests/test_owsilhouetteplot.py
- Orange/widgets/visualize/utils/heatmap.py
- conda-recipe/meta.yaml
- pyproject.toml
- requirements-core.txt
Numpy 2.0 compatibility
Currently numpy 2.0 support is still missing in catboost (https://github.com/catboost/catboost/issues/2671).
np.float_ -> np.float64
np.NaN -> np.nan
np.ndarray.ptp -> np.ptp
np.in1d -> np.isin
np.row_stack -> np.vstack
Replace oldest-supported-numpy with numpy>2.0 in the build dependencies. This is the [new preferred way](https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice).
Remove catboost from requirements.
> [ENH] Numpy 2.0 compatibility 

- Orange/widgets/evaluate/owrocanalysis.py
Fixes #7013
Fix typo causing incorrect error bars for threshold averaged ROC curves.
For functions `roc_curve_threshold_average` and `roc_curve_thresh_avg_interp` in ROC Analysis widget
> [FIX] Fix error bars for threshold averaged ROC curves

- Orange/data/io_util.py
- Orange/tests/test_txt_reader.py
- i18n/si/msgs.jaml
Detect utf-8-sig when using file utility.
Fixes #7000
Note: An alternative would be to remove the [use of `file` utility](https://github.com/biolab/orange3/blob/091e88c53214e7adbfb367ee88f1ba98085a1ef3/Orange/data/io_util.py#L55-L70), chardet would recognize the BOM (and does so on windows where file is typically not available). 
Detect utf-8-sig when using file utility.
> [FIX] io_util: Detect utf-8-sig when using `file` utility

- Orange/classification/scoringsheet.py
- Orange/widgets/model/tests/test_owscoringsheet.py
> [FIX] ScoringSheet deterministic results

- Orange/widgets/data/owpaintdata.py
- Orange/widgets/data/tests/test_owpaintdata.py
- i18n/si/msgs.jaml
Ref: #6971
Slight optimization. Most of the time still spent in ScatterPlotItem constructor.
> [ENH] Paint Data: Slight optimization

- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/tests/test_owdistributions.py
https://github.com/user-attachments/assets/51a3e693-e5f6-447e-bbb8-c2931988c430
- consider control value instead of setting value
> Distributions: Always show bars when no fitted distributions

- Orange/widgets/data/owcorrelations.py
- Orange/widgets/data/owcsvimport.py
- Orange/widgets/data/owmelt.py
- Orange/widgets/data/owmergedata.py
- Orange/widgets/data/owpaintdata.py
- Orange/widgets/data/owpivot.py
- Orange/widgets/data/owrank.py
- Orange/widgets/unsupervised/owcorrespondence.py
- Orange/widgets/unsupervised/owkmeans.py
- Orange/widgets/unsupervised/owlouvainclustering.py
- Orange/widgets/unsupervised/owpca.py
- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/utils/widget.py
Ref: https://github.com/biolab/orange3/issues/7043
CSV Import in particular should not have declared dynamic output.
Disable dynamic outputs where applicable.
> [FIX] Disable dynamic signals where applicable

- setup.cfg
We've probably been bitten by https://setuptools.pypa.io/en/stable/history.html#deprecations-and-removals -- all tests fail in build.
Change `with-` with `with_`, i.e. `with-htmlhelp` to `with_htmlhelp`.
> setup.cfg: Remove dashes in options

- Orange/widgets/visualize/owboxplot.py
Add space below the Box Plot chart to accommodate the statistic text.
Fixes #7051
Add space for text.
> Update owboxplot.py add space for text below graph

- Orange/tests/test_manifold.py
- Orange/widgets/unsupervised/tests/test_owmds.py
Current Scientific Python nightly tests fail
Relax test tolerance due to upstream scikit-learn implementation change (probably modified stopping condition in https://github.com/scikit-learn/scikit-learn/pull/30514)
> [MNT] tests/mds: Fix tests w.r.t. current dev scikit-learn

- Orange/widgets/visualize/owscoringsheetviewer.py
- i18n/si/msgs.jaml
Fixes #6985 
- Changes to the slider styling to suggest the slider is not interactive.
- Created a custom slider which ignores mouse events instead of disabling the default slider. By doing this, the tooltip should work on macOS.
> [FIX] ScoringSheetViewer slider style and tooltip

- Orange/widgets/data/owselectrows.py
- Orange/widgets/data/tests/test_owselectrows.py
…nd error unexpected type 'QDate'
Fix error: QLayout: Attempting to add QLayout "" to ErrorReporting "", which already has a layout
Fix error: TypeError: setDateTime(self, dateTime: Union[QDateTime, datetime.datetime]): argument 1 has unexpected type 'QDate'
> Update owselectrows.py fix error QLayout: Attempting to add QLayout and error unexpected type 'QDate'

- i18n/si/msgs.jaml
Fixes #7022.
Break line before the information about missing data.
> Table: Narrower widget in Slovenian translation

- Orange/widgets/visualize/owscoringsheetviewer.py
Fixes #6996 
- Refactors the ScoringSheetViewer widget so the displayed values are computed from base values which never change.
- Sorts the attributes by importance (absolute value of coefficients), so the most important attributes are displayed on top.
> [FIX] ScoringSheetViewer computing target class values from base values

- .github/workflows/doc.yml
- .github/workflows/test.yml
- conda-recipe/meta.yaml
- requirements-core.txt
- setup.py
- tox.ini
Add Python 3.13 to test matrix, drop 3.9
This needs https://github.com/biolab/orange3/pull/6850 merged first to remove catboost as dependency because it does not support 3.13
> [MNT] CI: Add Python 3.13 to test matrices drop 3.9

- Orange/widgets/data/utils/tableview.py
Fixes: https://github.com/biolab/orange3/pull/7103
setSortingEnabled disconnects/reconnects Qt's internal connections to model.sort(), causing client
sortIndicatorChange connections to trigger before the model is actually sorted. Avoid unnecessary calls.
The strange thing is this should have been happening also on Qt < 6.8.
> [FIX] tableview: Avoid unnecessary calls to setSortingEnabled

- Orange/data/sql/backend/postgres.py
The list of available PostgreSQL tables should by ordered by both schema_name and relation_name
I noticed that the table list in the SQL Table widget is not ordered.
This simple patch add the relation name to the ORDER BY
Added the order by for the second column too
> [FIX] Order available PostgreSQL tables

- Orange/widgets/unsupervised/owdbscan.py
- Orange/widgets/unsupervised/tests/test_owdbscan.py
Fixes #7105.
Handle empty X (often from plain Corpus).
> [FIX] OWDBSCAN: handle empty X

- Orange/widgets/visualize/owdistributions.py
- Orange/widgets/visualize/tests/test_owdistributions.py
Fixes #7102.
When all instances in a particular bar had the same value (up to the precision shown in the label), bars were shifted for one-half width to the left for cleaner visualization.
However, the *position of the bar* was then used to determine the bin thresholds, hence shifting it into the previous bin.
I also strongly suspect that padding between bars also caused some instances to be skipped in other histograms, too.
Although we could "unoffset" the bar, a cleaner solution is to store the actual range into each bar to make it independent of visualization, that may include other offsets and paddings in the future.
Unrelated: I cleaned the code so that is consistently uses `_is_last_bar` method, and I also added `is_first_bar` (however trivial it is) to make call arguments easier to …
> Distributions: Fix invalid selection and tooltip for some histograms

- Orange/widgets/evaluate/owpredictions.py
- Orange/widgets/evaluate/tests/test_owpredictions.py
- i18n/si/msgs.jaml
Fixes #7015.
When a workflow is opened with Orange set to a different language, it crashed because the setting for target classes was saved as literal, e.g. `(Average over classes)`.
This is the only literal value, other possible values of the setting are class values. I replaced it with an empty string. `None` would be better, but `gui.combobox` allows setting a display value for an empty string.
Migrations replace the setting with an empty string if
- it matches the literal *for the current language*, or
- if the value of the setting doesn't appear in the list of classes.
The second patches the bug for existing workflows. The second condition also covers the first, but let us keep the first for clarity.
> [FIX] Predictions: allow loading of workflows saved in a localized version (target class setting fix)

- Orange/widgets/visualize/tests/test_owprojectionwidget.py
- Orange/widgets/visualize/utils/widget.py
Fixes #7089.
@wvdvegte, this was indeed the most snackish snack. If I haven't overlooked something, it only required changing `>=` to `>`. Plus adding a test, but changing a `4` into a `3` in the existing test would also suffice.
> [FIX] Projections: When the number of colors equals the limit, do not introduce 'other'

- Orange/data/util.py
- Orange/tests/test_data_util.py
- i18n/si/msgs.jaml
`SharedComputeValue` doesn't allow inheriting (or, rather, disabling the warning about inheriting) `__eq__` and `__hash__` in classes that compute values.
I added a check for the flag.
> SharedComputeValue: Allow inheriting __eq__ and __hash__

- Orange/widgets/unsupervised/owdbscan.py
- Orange/widgets/unsupervised/tests/test_owdbscan.py
[Q] Why not skip second checks by using elseif in line 180?
Fixes #7111
Change a way of checking epsilon after assign it from `k_distances` at default cut point.
> [Fix] DBSCAN #7111, Change a way of checking eps.
